### ISSUE TITLE
Add attribute directive for performing calculations

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1016]
Calculating numbers is a common requirement when writing documents that include financial information (e.g., contracts, business plans, projections). Add an attribute directive named `calc` that can be used for performing basic arithmetic (additional, subtraction, multiplication and division) on literal values and/or attribute references. 

Example:

```
:a: 1
:b: 2

{calc:a + b} resolves to '3'.
```

Assume that non-numeric values are attribute references.

An alternative approach is to introduce a calc inline macro that can be used in the value of an attribute entry:

```
:a: 1
:b: 2
:c: calc:[a + b]

{c} resolves to '3'.

calc:[a + b] also resolves to '3'.
```

We could consider supporting both forms.

**Comment by mojavelinux** [comment]
I think this is best done with a custom inline macro.

It could be done using custom attribute reference if we make it pluggable (a similar discussion to #528).

**Comment by Hollerweger** [comment]
Did anybody implement such an inline macro for calculations?
Still would be great if it could be supported without any further dependency so that it works on Github & Gitlab.
