### ISSUE TITLE
Include a document title when header_footer is suppressed

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#103]
Although a deviation from AsciiDoc, I think we should include some semblance of a document title (h1 heading) in the embedded template by default. I think this is important because the current behavior of cropping the document title is not parallel with Markdown, and not what the user would expect.

Obviously, we want to leave off the document element (html) and document metadata element (head) because, after all, we are embedding the content. But I think the content of the header div is worthwhile to keep.

I am proposing including the following markup at the top of the embedded template:

``` html
<h1>Title</h1>
<span id="author">Dan Allen</span><br>
```

If the toc is enabled, then it would grow to:

``` html
<h1>Title</h1>
<span id="author">Dan Allen</span><br>
<div id="toc">
  <div id="toctitle">Table of Contents</div>
  <ol>
    ...
  </ol>
</div>
```

I'm not sure if we should wrap the header in the header div and the content in the content div. I'm kind of leaning towards the minimal approach.

Perhaps to be consistent w/ AsciiDoc, we should have an option for this behavior. Perhaps something like:

```
:embedded_content_header => true
```

(Of course, this can be overridden by creating a custom template for the embedded view).

**Comment by darabos** [comment]
Apologies for commenting on this old issue. Is there a way now to include the ToC in embedded mode? Thanks.

**Comment by darabos** [comment]
> Apologies for commenting on this old issue. Is there a way now to include the ToC in embedded mode? Thanks.

Apparently there is! It is via the `toc` macro. I had to set `:toc: macro` and `:toc-placement: macro` and then use `toc::[]`. Perhaps this helps someone following in my footsteps :). (This is kind of documented, but not directly like this.)

**Comment by mojavelinux** [comment]
> Apologies for commenting on this old issue. 

We never object to having more information and clarity :)

>  I had to set :toc: macro and :toc-placement: macro and then use toc::[]

Actually, `:toc: macro` is a shorthand way of enabling the toc and setting `toc-placement`, so you only need the one declaration.

Here's the relevant section in the manual. http://asciidoctor.org/docs/user-manual/#manual-placement Perhaps we can add a note which toc settings work when in embeddable mode (header_footer is disabled).

**Comment by darabos** [comment]
> > I had to set `:toc: macro` and `:toc-placement: macro` and then use toc::[]

> Actually, `:toc: macro` is a shorthand way of enabling the toc and setting `toc-placement`, so you only need the one declaration.

If I only set `:toc: macro` I get `<!-- toc disabled -->` in place of the ToC. I think it comes from https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/lib/asciidoctor/converter/html5.rb#L816 which led me to setting `toc-placement` as well. I'm using grunt-asciidoctor &mdash; maybe that also plays into this.

I tried dropping the `:toc: macro` setting now, and only keeping `:toc-placement: macro`. This works, I get a ToC.

**Comment by mojavelinux** [comment]
@darabos chances are, `toc-placement` is being set somewhere else (either in the document or in the options passed to it). If `toc-placement` is not set, then you should be able to set `:toc: macro` alone. That, in turn, sets `toc-placement` as you can see here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L751-L754

Having said that, it doesn't hurt to set `toc-placement` too.

**Comment by mojavelinux** [comment]
Btw, the value `macro` only works on Asciidoctor 1.5.0 and above, which is why this value won't work on GitHub until they upgrade from 0.1.4. However, best to assume they will and set it correctly.

**Comment by darabos** [comment]
Thanks for all the information! Looks like the mysterious `toc2` plays into this too somehow (https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/lib/asciidoctor/document.rb#L719) and `grunt-asciidoc` does something with it (https://github.com/asciidoctor/asciidoctor-grunt-plugin/blob/v0.2.0/tasks/asciidoctor.js#L49). I'm Ruby-illiterate, sorry.

Anyway, it's all great now. Thanks for all the work put into Asciidoctor! It's exactly what we needed. (Markdown output isn't structured enough.)

**Comment by mojavelinux** [comment]
It's more with how the Grunt plugin is setting the toc value. That needs to be fixed...it shouldn't be hardcoding `toc=preamble`. Could you file an issue there?

> Thanks for all the work put into Asciidoctor!

You bet!
