### ISSUE TITLE
Create a macro to display document statistics

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor#1039]
I think it could be great to gather statistics about the document to allow users to print them.

For example the estimate reading time: `docstat:[reading-time]`. The default time unit is minute but can be specify via the option `unit`:  `docstat:[reading-time, unit="second"]`

The reading-time is usually estimate with the number of words and the average word per minute read (around ~250-300). So we can also display the word count of the document with: `docstat:[word-count]`

The average word per minute should be configurable via an attribute.

We can also count the number of headings, paragraphs, code blocks... and the min, max and average length of paragraphs.. this statistics can help writers to find out if their documents is structure correctly.

What do you think ?

**Comment by Mogztter** [comment]
> You are looking for the words as the reader sees them. I've encountered the need for something similar a few times. To be specific, I needed the plain text of a given content area after it was rendered.

I have another use case for this feature request. I'm trying to index in a search engine only the content of a document (without markup). AFAIK #504 is specific to doctitle.

> I think the solution here is to provide an API that extracts plain text out of the rendered output. 

Why not but we will need to sanitize the rendered output for every converter (HTML, dookbock...) ?
For HTML a simple method is to strip out HTML tags: http://stackoverflow.com/questions/822452/strip-html-from-text-javascript

What about providing an API on the AST ? For every blocks we could have a `text_content` method that returns the text content (without markup) no ?

**Comment by mojavelinux** [comment]
> For every blocks we could have a text_content method that returns the text content (without markup) 

That's an interesting proposal. What I'm concerned about it is that it leans too much towards the "object knows too much" problem. It would be better, I think, if we had a node mapper that "textualized" the content of nodes. That composition gives us a lot more flexibility and allows the problem to be solved in different ways by different implementations. It also opens the door to a "json" exporter. wdyt?

**Comment by mojavelinux** [comment]
> I'm trying to index in a search engine only the content of a document (without markup). 

We definitely want to get into this space.

**Comment by Mogztter** [comment]
>  think, if we had a node mapper that "textualized" the content of nodes.
That composition gives us a lot more flexibility and allows the problem to
be solved in different ways by different implementations. It also opens the
door to a "json" exporter. wdyt?

That's a really good idea. My only concern is that this concept is close to
the concept of converters. What is the difference between a node mapper
that will produce a json document from an AsciiDoc content and a custom
converter that will produce a json document from an AsciiDoc content ?
I think the main advantage is that node mapper could be used on extensions
(Treeprocessor...) and avoid to converter the document twice. (Just
thinking out loud ;))

**Comment by mojavelinux** [comment]
> What is the difference between a node mapper that will produce a json document from an AsciiDoc content and a custom converter that will produce a json document from an AsciiDoc content ?

The advantage of a mapper is that you can pick and choose what you want to convert (esp when combine with find_by). You also are picking out content rather than catching it as it goes by (in the converter stream).

**Comment by mojavelinux** [comment]
> I think the main advantage is that node mapper could be used on extensions (Treeprocessor...) 

Exactly, even more flexibility.

Naturally, if there are core changes we need to make this mapper easier to write, then I think we definitely want to do that.

**Comment by Mogztter** [comment]
@mojavelinux Do you still think it's a good idea to introduce a node mapper ? if it's the case I can create a separate issue for this part so we don't lose track of it ?

**Comment by wols** [comment]
It would be cool if the output in CLI could be used for a wordcloud:
```
pip install wordcloud

wordcloud_cli --text asciidoctor-macro-out.adoc --imagefile wordcloud.png
```

**Comment by mojavelinux** [comment]
>  What is the difference between a node mapper that will produce a json document from an AsciiDoc content and a custom converter that will produce a json document from an AsciiDoc content

This has more or less become a goal of the AsciiDoc Language project. Asciidoctor will implement that once finalized. Until then, I can't see us changing anything in Asciidoctor along these lines as it may diverge from our efforts in the language project.

Sine the docstat macro is now part of the extensions lab, I'm closing this issue as completed.
