### ISSUE TITLE
Integrate Rouge for source highlighting

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1040]
Integrate the Rouge library as an alternate or replacement syntax highlighting library to Pygments.rb. Rouge is a port of Pygments to Ruby. The current Pygments integration calls Pygments by way of an interprocess communication bridge. This bridge doesn't work in AsciidoctorJ.

If we integrate Rouge and verify that it provides the same experience as Pygments, we can make it a drop-in replacement. If there are big enough differences, we can simply recognize it as an additional syntax-highlighter option named "rouge".

Rouge: https://github.com/jneen/rouge

**Comment by AlexanderZobkov** [comment]
What is status of integration of Rouge?
Looking on the following line: https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-example/pom.xml#L61-L63
it has been already integrated and this particular issue needs to be closed.

**Comment by AlexanderZobkov** [comment]
Probably asciidoc documentation needs to be updated as well. Currently the documentation mention support for pygments and coderay only.

**Comment by abelsromero** [comment]
Documentation is partially accurate and probably needs a review.
The thing is that not all source highlighters work on all backends and integration layers.
For instance rouge only works for PDF with asciidoctor-pdf, and pygments does not work in Java.

I always check the [table here](https://github.com/asciidoctor/asciidoctor.org/blob/c9d1b0c9dadafe04def8f8fe21d06541b177f9da/docs/_includes/src.adoc) for the details, but maybe we should add a new column with the supported backends.

**Comment by mojavelinux** [comment]
That's exactly correct @abelsromero. Rouge was integrated into Asciidoctor PDF first as a trial. The alpha status of Asciidoctor PDF presented us with an opportunity to experiment with this library before committing to it. The results were good. Rouge works great! That's the point when we decided to integrate it into core. That part is not yet done.

Pygments is going to continue to be a problem because it just doesn't play well with JRuby (and other Ruby implementations). CodeRay is mediocre at best. That's why I think Rouge is the future.

**Comment by mojavelinux** [comment]
I think when we integrate Rouge into core, we're going to drop CodeRay (and alias coderay to rouge). We have to keep Pygments because we have a handful of faithful users of it (and because it really is the most comprehensive), but we won't recommend it.

**Comment by AlexanderZobkov** [comment]
I think It would be better to update the table/section mentioned by @abelsromero with information on Rouge. It will make users (existing and new ones) aware on the integration with Rouge and allow more users to experiment with it so that you can get more feedback on this feature.

**Comment by mojavelinux** [comment]
I agree. Keep in mind, though, that we haven't extensively documented Asciidoctor PDF yet because it is still in alpha and we are changing a lot of things. I'm hopeful we'll be emerging from alpha soon and thus getting ready to integrate the documentation into the user manual.

**Comment by AlexanderZobkov** [comment]
I see a strange issue when using rouge syntax highlighter. 
`[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (generate-pdf-doc-default-theme) on project asciidoctor-pdf-with-theme-example: Execution generate-pdf-doc-default-theme of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: required gem 'rouge' is not installed. Processing aborted. -> [Help 1]`

The issue is seen when converting a document into PDF on Windows under cygwin or Netbeans IDE. On Linux, I see no such issue. 

Could you please suggest for which project I should submit an issue? For asciidoctorj, asciidoctor-maven-plugin or asciidoctor?

In addition, I think I need to ask author of asciidoctor-maven-examples to add some dummy code to example documents to catch problems with highlighters.

**Comment by abelsromero** [comment]
We'll need more information to see the problem, I run the `asciidoctor-pdf-with-theme-example` example in Cygwin with Win 8.1 and it worked.

> Could you please suggest for which project I should submit an issue? For asciidoctorj, asciidoctor-maven-plugin or asciidoctor?

Deppends...are you trying to run the example "as-is" or doing something else?

> In addition, I think I need to ask author of asciidoctor-maven-examples to add some dummy code to example documents to catch problems with highlighters.

First, we are all authors here :) And secondly, how to test examples is something that appears from time to time. One one side we rely on 'manual' testing and good faith', but on the other adding testing in the examples destroys the purpouse of keeping them as simple as possible. But still, we are open to ideas, feel free to file an issue in the examples projects if you have some idea in mind.

**Comment by abelsromero** [comment]
Correction, Windows 7

**Comment by AlexanderZobkov** [comment]
I'm using unmodified `asciidoctor-pdf-with-theme-example` with added a source code block to demonstrate and discuss the issue.

I think it will be enoght to add the following block to enable rouge and see the issue.
[source,ruby]  
.app.rb 
---- 
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----

**Comment by abelsromero** [comment]
Confirmed :disappointed: In MacOS works, but not in Windows. Even after adding rouge as a dependency of the gem-maven-plugin it still says it's not installed.
```
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: required gem 'rouge' is not installed. Processing aborted.
        at RUBY.require_library(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/helpers.rb:30)
        at RUBY.convert_listing_or_literal(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:948)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71)
        at RUBY.block in content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
        at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2300)
```

**Comment by AlexanderZobkov** [comment]
Okay, great, it's reproducable not only on my side. Could you please suggest for which project I should submit an issue?

**Comment by robertpanzer** [comment]
@abelsromero Is there maybe another nested exception?

**Comment by mojavelinux** [comment]
The way that we require the rouge gem is a bit different than other libraries. We require a relative file with extensions to Rouge, which in turn requires the rouge gem. It appears that this path does not resolve properly on Windows. (This looks like other path issues we've had with JRuby).

Therefore, I'd say we probably have to address this issue in Asciidoctor PDF. But first, we need to understand what to do to get JRuby to resolve the path correctly.

* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L31
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L948

**Comment by mojavelinux** [comment]
Do we have a test in AsciidoctorJ that attempts to syntax highlight using Rouge?

**Comment by robertpanzer** [comment]
Yes, @abelsromero added a nice test: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-pdf/src/test/java/org/asciidoctor/WhenBackendIsPdf.java#L63
It's currently only on the 1.6.0 branch though.

**Comment by robertpanzer** [comment]
1.6.0 is JRuby 9.0.4.0 atm

**Comment by mojavelinux** [comment]
Awesome!

@AlexanderZobkov or @abelsromero, can you try the example on Windows using JRuby 9k. I have a feeling this is another JRuby 1.7 issue (or perhaps one we've already seen).

**Comment by mojavelinux** [comment]
Nevermind, that example is already using JRuby 9k. Hmm..

**Comment by abelsromero** [comment]
> Nevermind, that example is already using JRuby 9k. Hmm..

I recall it's using 9k, because of the version of prawn. Anyway, also with 1.7.21 just in case, but nothing.
If it helps, here is the log https://gist.github.com/abelsromero/356d18af5fe56087dd1e#file-asciidoctor_maven_pdf_rouge_error-log

Note that in that example I also added rouge [see L5](https://gist.github.com/abelsromero/356d18af5fe56087dd1e#file-asciidoctor_maven_pdf_rouge_error-log-L15) and it's properly deployed into the gems-provided folder, but still fails.

PS: coderay works

**Comment by robertpanzer** [comment]
Where does the prawn 2.0.2 come from?
With asciidoctorj-pdf we're still on 1.3.0.



Am Mittwoch, 16. März 2016 schrieb Abel Salgado Romero :

**Comment by abelsromero** [comment]
There was an issue when adding templates:
https://github.com/asciidoctor/asciidoctor-maven-examples/issues/40
http://discuss.asciidoctor.org/Asciidoctor-YAML-style-file-for-PDF-and-maven-td3849.html#a3858

Summary from Dan in the forum:

```
Aha! I figured out what the problem is. AsciidoctorJ PDF bundles Prawn 1.3.0. In Prawn 1.3.0, the method needed to add a background image to a page was removed. It was then restored in Prawn 2. AsciidoctorJ PDF ships with Prawn 1.3.0, so this functionality is temporarily unavailable. AsciidoctorJ can't yet ship with Prawn 2 because Prawn 2 depends on Ruby 2, which means using JRuby 9.0.0.0. Since we hadn't made that jump yet, the current release of the toolchain is stuck between a rock and a hardplace. (Prawn put the JRuby community in a tight spot with their decision to drop Ruby 1.9, in my opinion).

Suffice to say, background images and colors aren't available when using AsciidoctorJ PDF right now. They will work as soon as we bundle Prawn 2 in AsciidoctorJ PDF (or you decide to temporarily use external gems with JRuby 9.0.0.0, which is tricky but possible).
```

**Comment by robertpanzer** [comment]
OK, then I'd completely remove the dependency on asciidoctorj-pdf and collect the deps in the plugin configuration yourself.
I am not 100% sure how require_relative works, but I think it relatively walks along the (Jar-) Filesystem, so it could be that it does not find rouge which is relative to the old asciidoctor-pdf version packaged in asciidoctorj-pdf.

In particular on Windows JRuby had some issues with require_relative.

Did you also upgrade to JRuby 9.0.5.0?

**Comment by sbrannen** [comment]
@mojavelinux, is there an update on the support for Rouge on Windows?

I ask, b/c JUnit 5 users have run into the same issue now that we've switched to Rouge when generating a PDF: https://github.com/junit-team/junit5/issues/799

**Comment by sbrannen** [comment]
Naturally, this now affects the Spring Framework build on Windows as well: https://jira.spring.io/browse/SPR-15471 😉

**Comment by mojavelinux** [comment]
I am completely baffled why Rouge would not load properly on Windows. It's a 100% Ruby library with no dependencies. I'm also confused why there is no issue reported upstream in rouge. I'll need to do some investigation as to what might be causing this problem. However, looking at the Rouge code, this extremely bizarre way of loading libraries worries me.

https://github.com/jneen/rouge/blob/master/lib/rouge.rb#L37-L80

**Comment by mojavelinux** [comment]
In the interim, you could switch back to CodeRay. CodeRay isn't bad, per se. It's just starting to fall behind, lacks a decent theming system, and doesn't have as broad language support. But if using Rouge is breaking users, then by all means just switch until it's resolved.

**Comment by mojavelinux** [comment]
I figured out why Rouge doesn't load on Windows. See my comment here: https://github.com/asciidoctor/asciidoctorj-pdf/issues/3#issuecomment-296347988

**Comment by sbrannen** [comment]
Thanks for getting to the bottom of this, @mojavelinux!

I just subscribed to https://github.com/jneen/rouge/issues/661.

Much appreciated! 👍

**Comment by sbrannen** [comment]
> In the interim, you could switch back to CodeRay.

Yep, that's the route we're going for the time being.

**Comment by mojavelinux** [comment]
We've learned that pygments.rb can randomly fail due to a timeout communicating with the background process. That makes an even stronger case for getting Rouge integrated into core.

Technically, Rouge isn't a drop-in replacement for CodeRay. It's just that CodeRay is such a lackluster highlighter that we might as well just replace it.

**Comment by jirutka** [comment]
Since I didn’t want to wait for this next few years and needs a customizable solution, I’ve implemented **complete** (including line callouts and line highlighting) support for Rouge as an extension: [asciidoctor-rouge](https://github.com/jirutka/asciidoctor-rouge). It’s tested MRI and JRuby, but I haven’t tried it on Windows.

**Comment by mojavelinux** [comment]
Great! That should help move this effort along. Thanks!

**Comment by miltador** [comment]
@jirutka, thanks! Works fine on Windows.

**Comment by mojavelinux** [comment]
@sbrannen A new version of Rouge is available that resolves the Windows problem (plus several more releases following that one). You should be able to use it now, though you'd have to depend on it explicitly (using jruby gradle). We'll include the upgrade in the next release of AsciidoctorJ PDF.

**Comment by nfrankel** [comment]
Hello,

I'm using Jekyll, and my legacy content is in Markdown. Jekyll 3 uses Rouge by default for code highlighting. I've configured Coderay for the Asciidoctor content, but for the sake of consistency as well as the number of languages supported, I'd be very happy to have Rouge implemented by plain Asciidoctor as well.

Hence, do you have enough feedback regarding AsciidoctorPDF to make the port?

**Comment by chickenkiller** [comment]
Hello, any news of the progress on Rouge integration in Asciidoctor? Thanks!

**Comment by miltador** [comment]
@chickenkiller it's not there out-of-the-box yet, but you can use an awesome [asciidoctor-rouge](https://github.com/jirutka/asciidoctor-rouge) plugin that adds Rouge integration and works just fine.

**Comment by chickenkiller** [comment]
@miltador Thanks, and I was actually about to give it a try!

**Comment by nfrankel** [comment]
I confirm this works well in my case, thanks @miltador

**Comment by chickenkiller** [comment]
I confirm as well. Works for me with asciidoctor-rouge extension. Thanks!

**Comment by anidotnet** [comment]
How do I enable rouge in asciidoctor-gradle?

**Comment by mojavelinux** [comment]
Now that the syntax highlighter adapter in Asciidoctor is pluggable, this issue can proceed without adding complexity to the codebase.

Instead of trying to map coderay to rouge, I've decided to simply add rouge as a proper adapter.

Even though we're adding rouge to core (for convenience), it's still possible to override it with a separate implementation thanks to the pluggable syntax highlighter design.

I'm thinking about extracting coderay as a separate gem. Since coderay doesn't match the quality of rouge, there's no reason to keep both in core. And if you still need it, you can just add the gem to the require path. But that will be handled as separate task.

**Comment by mojavelinux** [comment]
Rouge does not support the "inline" mode for line numbers, but honestly I don't think that matters since that mode is much harder to style anyway.

One thing that's missing from Rouge out of the box is highlighted (aka emphasized) lines. I'd like to see that added upstream. However, if that's a blocker, we could add a custom formatter for Rouge that adds this functionality. I'd like to do that in a separate issue, though.

**Comment by mojavelinux** [comment]
> One thing that's missing from Rouge out of the box is highlighted (aka emphasized) lines.

I've implemented this feature as part of this PR. I'll still pursue getting it added upstream, at which point we may decide to switch the code over to using that instead.

**Comment by mojavelinux** [comment]
Here are the upstream issues:

* https://github.com/jneen/rouge/issues/1082 (allow table formatter to wrap a line-wise formatter)
* https://github.com/jneen/rouge/issues/264 (add support for highlighted lines)
* https://github.com/jneen/rouge/issues/1084 (redesign line-wise formatter to preserve newlines)

**Comment by mojavelinux** [comment]
I'd also like to see support for customizing the CSS class prefix for tokens, which is https://github.com/jneen/rouge/issues/1074.
