### ISSUE TITLE
Add API to retrieve collection of authors

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1042]
Currently the list of authors is stored in the authors attribute as a comma-separated value. Expose this list as a collection.

We should also consider adding an Author class that holds the data for an individual author. That way, we can easily extract all the information for the authors.

This feature is needed in Asciidoctor EPUB3, among other places.

**Comment by Mogztter** [comment]
It should be track in another issue but what do you think about adding author's metadata in the `Author` class ? Until we improve the parsing of the author line, we could extract document attributes that start with `author`. For instance:

#### Given

```adoc
= Getting Real: The Smarter, Faster, Easier Way to Build a Successful Web Application
:author_1: David Heinemeier Hansson
:authorbio_1: David Heinemeier Hansson is a Danish programmer and the creator of the popular Ruby on Rails web development framework.
:email_1: david@37signals.com
:author_2: Jason Fried
:authorbio_2: Jason Fried is the co-founder of 37signals, makers of Basecamp and other web-based collaboration tools.
:email_2: jason@37signals.com

Getting Real details the business, design, programming, and marketing principles of 37signals.
```

#### Then

```rb
doc = document_from_string input
doc.authors.first.metadata['bio'] # get the author's bio (ie. 'authorbio_1' attribute)
```

**Comment by mojavelinux** [comment]
I like the idea, though I would propose to separate the word author, as in `author_bio_1`.

But if we're going to rethink the author metadata, I think we should come up with a better system post-Asciidoctor 2.0.0 that doesn't rely on such verbose attribute names. I haven't thought of a solution yet.

**Comment by Mogztter** [comment]
> But if we're going to rethink the author metadata, I think we should come up with a better system post-Asciidoctor 2.0.0 that doesn't rely on such verbose attribute names. I haven't thought of a solution yet.

You're probably right.
Adding this feature before Asciidoctor 2.0.0 is maybe not a good idea (that's why I didn't introduce this change).

> I like the idea, though I would propose to separate the word author, as in author_bio_1.

Should we create another issue without being too specific about the implementation ?
Just that we want to define author metadatas as document attributes (and that we want this metadata to be available in the authors API) ?

**Comment by Mogztter** [comment]
https://github.com/asciidoctor/asciidoctor/issues/2939
