### ISSUE TITLE
Image width and scaledwidth can't be used at the same time

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor#1059]
If I use both `width` and `scaledwidth` in the image attributes in asciidoc:
- The **html** output only shows `width` (this is correct)
- The **xml** output shows both `contentwidth` and `width` (incorrect, causes output to be scaled to `width`, instead of to `scaledwidth`).

I would like to be able to scale my images for both outputs in the same line without a conditional.

**Comment by mojavelinux** [comment]
I'm going to go ahead and fix this.

**Comment by mojavelinux** [comment]
The DocBook page for imagedata confirms this:

> Specification of content area, scaling, and scaling to fit are mutually exclusive.
