### ISSUE TITLE
How to Revert To Visual Look-and-Feel of 0.1.4

### ISSUE THREAD

**Issue by jnorthr** [asciidoctor/asciidoctor#1079]
hi all -
yes can say overall i like this new version. Syntax improvements should help once i can map my keyboard to find a back-tic char. for mono-space. Here are 2 views of proposed documents we are doing, one in a/d 0.1.4 and one in a/d 0.1.5  

![ad014](https://cloud.githubusercontent.com/assets/382990/4148634/826d303e-3428-11e4-931d-872b078fe3e9.png)

![ad015](https://cloud.githubusercontent.com/assets/382990/4148639/8abbdf24-3428-11e4-91b5-43bd0831485d.png)

which version do you think my visually impaired users can cope with ? Yes, me too. 

Well now if i use 0.1.5, i'll need to retrofit the font-face and font-weight for both body and h1/h2/h3 bits at the least. I am thinking my choices are 
1. stick with 0.1.4 for generation
2. use 0.1.5 but have :linkcss: declared to get a style sheet i can tweek back to 0.1.4. choices.
3. same as 2. but use style sheet from 0.1.4

any other ideas ?

PS we don't use chinese or greek char.s just the latin stuff :-)

**Comment by mojavelinux** [comment]
If you're looking for additional styles, consider https://github.com/darshandsoni/asciidoctor-skins.
