### ISSUE TITLE
First Look@Asciidoctor-pdf 0.1.5 --pre

### ISSUE THREAD

**Issue by jnorthr** [asciidoctor/asciidoctor#1082]
Hi Dan and co.
Just found out you have a version of asciidoctor that creates native PDF from here: http://rubygems.org/gems/asciidoctor-pdf 
and https://github.com/asciidoctor/asciidoctor-pdf#example-asciidoc-document 

so thought i'd offer the results of generating a 43 pg PDF, see attached .adoc which rendered as http://builder1.mybluemix.net/cons  using 0.1.4.

my google chrome browser lets me save that as a PDF so it's attach here too and finally after following all your thorough directions, have produced a PDF using asciidoctor-pdf  - see attached.

// ---> OUCH !
// ok, github wont let me post them here so i renamed with a .png suffix and if you can take off the .png you can see these results (or i can send them to you if u have an email)

Wonderful work with few issues !
thx
jim

![groovy-contributions](https://cloud.githubusercontent.com/assets/382990/4175311/0118b418-35cc-11e4-92a6-406252c9e2c0.png)

![groovy-contributionspdf](https://cloud.githubusercontent.com/assets/382990/4175313/19c4d744-35cc-11e4-9e79-b5f530bd7bc1.png)

![groovy contributions chrome pdf](https://cloud.githubusercontent.com/assets/382990/4175315/4e36c2bc-35cc-11e4-95f5-39b339c3396d.png)

/// ---------------------------------------------------
// my ubuntu 14.04 joblog was : 

jnorthr@jnorthr-EC548AA-ABU-a1128-uk:~/Dropbox/builders/war$ asciidoctor-pdf groovy-contributions.adoc 
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: dropping line containing reference to missing attribute: projectdir
asciidoctor: WARNING: conversion missing in backend pdf for pass
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for pass
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for pass
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for pass
asciidoctor: WARNING: conversion missing in backend pdf for inline_image
asciidoctor: WARNING: conversion missing in backend pdf for pass
jnorthr@jnorthr-EC548AA-ABU-a1128-uk:~/Dropbox/builders/war$

**Comment by jnorthr** [comment]
Will we need a fresh asciidoctor gem to get PDFs? Or just gem install asciidoctor-pdf ?
Thx

**Comment by mojavelinux** [comment]
You can gem install, but you have to specify the prerelease.

```
$ gem install --pre asciidoctor-pdf
```

If you are on the Java / Groovy side, you can just use the asciidoctorj-pdf jar.

**Comment by jnorthr** [comment]
Oh, wonderful Dan -this is a real treat 😆
Thx

**Comment by jnorthr** [comment]
Ok, tried that but my aging  MacBook 10.6.8 does not have Ruby 1.9.3+ to support this pdf tool. Will see if it's poss. to upgrade to 1.9.3 - fingers crossed

**Comment by mojavelinux** [comment]
This is one of the main reasons I recommend RVM. It really shouldn't matter what Ruby your system has as the system Ruby is for the system. For development, I am a firm believer in bringing your own environment. RVM helps you do that. I have 15 different Rubies on my computer and I select whichever one the situation calls for. You may not need that many, but at least you don't have to mess with the system.

**Comment by jnorthr** [comment]
Well that sure is an eye-opener Dan - many thanx for that. Will see if my old Mac can take the RVM tool. As soon as Alex Soto gets this pdf logic into asciidoctorj, then i can improve our http://caelyftemplate.de.a9sapp.eu/asciidoctor to produce downloadable PDFs from files,etc. Well thats the idea 😏

**Comment by gscheibel** [comment]
If it can help, I can create a specific version of the docker container so
you don't have to install new thing.

**Comment by jnorthr** [comment]
Heavens Guillaume ! Would i need to install something to make docker happy ? Oh, mon tete 😉

**Comment by gscheibel** [comment]
If you have docker you're good to go.
I'll update the container and let you know.

**Comment by jnorthr** [comment]
If you see this sample http://caelyftemplate.de.a9sapp.eu/ad it would be fairly simple to add a button to gen an asciidoctor-pdf for download 2 client browser. Would put all that up on my github repo 4 everyone to clone - kind of 'pushing the boat out' as the Brits say 😃

**Comment by gscheibel** [comment]
there we are:
docker pull asciidoctor/docker-asciidoctor:pdf-015

**Comment by jnorthr** [comment]
Maybe tonite ? Thx jim

**Comment by jnorthr** [comment]
Wonderful, thx. Just found this to load Docker on my Mac: http://blog.docker.com/category/engineering/
So must crack on now - good things are coming 😎

**Comment by mojavelinux** [comment]
This discussion has become outdated, so I'm going to close it out. If there are any issues you'd still like to see addressed, please file them in the corresponding issue tracker. Thanks!
