### ISSUE TITLE
Add attribute to warn on missing inter document cross references

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor#1101]
Add a way to know if the name of a document being referenced has changed causing broken references. Would like to be warn when asciidoctor can't find the file that is being referenced.

**Comment by DavidGamba** [comment]
If you look at my code above, I used `files_to_check = doc.references[:includes]`, however, that call doesn't return the file extension so I had to add it later (`extension_list = ['.adoc', '', '.py', '.iRule', '.conf', '.rb']`).

Is there a way to get the includes with their extension?

**Comment by mojavelinux** [comment]
> Is there a way to get the includes with their extension?

Not yet, but I am aware that we need to store it both ways (or resolve the docname dynamically and store the file name with the extension). In other words, we need more metadata.

**Comment by mojavelinux** [comment]
This is now possible by enabling the `-v` flag (which should have few false positives once 1.5.7 is out). Issue #1586 is tracking when this will be enabled by default.
