### ISSUE TITLE
Colophon placement clarification

### ISSUE THREAD

**Issue by sethwoodworth** [asciidoctor/asciidoctor#1102]
http://asciidoctor.org/docs/user-manual/#user-colophon

> In most mass market books, the colophon is on the verso (back side) of the title page, but it can also be located at the end of the book.

I took this to mean that the colophon can be placed at the end of a book:

``` asciibook
= Book
== Chapter 1
[colophon]
= Colophon
```

Can the colophon only be placed before the first section of the book?  If so, I will update the docs

**Comment by mojavelinux** [comment]
I've written everything I know to write on the following page in the new docs: https://docs.asciidoctor.org/asciidoc/latest/sections/colophon/ If there is anything you think needs to be said, please click "Edit this Page" and propose a revision.
