### ISSUE TITLE
Support custom YouTube playlists with ?playlist=

### ISSUE THREAD

**Issue by dmalan** [asciidoctor/asciidoctor#1105]
As a follow-up to #1054, it turns out that YouTube also supports custom playlists, whereby you can specify a comma-separated list of video IDs as the value of a `?playlist=` parameter as opposed to a playlist ID as the value of a `?list=` ID. (YouTube's choice of semantics seems admittedly backwards.) For instance, the below URL embeds a player for 3 videos:

```
http://www.youtube.com/embed/1VbHJz2L6dM?playlist=Ja8YoR-u9TA,mXj188eyRFE
```

In addition to syntax like

```
video::U8GBXvdmHT4/PLg7s6cbtAD15Das5LK9mXt_g59DLWxKUe[youtube,853,480]
```

might it be compelling to support, e.g.,

```
video::1VbHJz2L6dM,Ja8YoR-u9TA,mXj188eyRFE[youtube,853,480]
```

for such playlists? Alternatively, for slightly more consistency, the latter could instead be

```
video::1VbHJz2L6dM/Ja8YoR-u9TA,mXj188eyRFE[youtube,853,480]
```

but that approach would require distinguishing video IDs from playlist IDs (as by checking their length, since the former are shorter), but YouTube doesn't appear to guarantee a particular length (cf. http://webapps.stackexchange.com/a/54448), so that syntax might prove more fragile.

**Comment by RichardJECooke** [comment]
Why is this closed without the [docs ](https://asciidoctor.org/docs/user-manual/#youtube-and-vimeo-videos) being updated?

It's very useful and shouldn't be hidden under loads of google searching

**Comment by mojavelinux** [comment]
At the time, we didn't have a workflow for adding docs as part of a feature (as we're starting to do now). You can open a docs issue at https://github.com/asciidoctor/asciidoctor.org.
