### ISSUE TITLE
Add source style automatically to listing blocks if source-language is set

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1117]
If the source-language (or perhaps source-highlighter) is set on the document, automatically add the source style (i.e., block name) to a listing block. Require an explicit listing style to create a plain listing block. The reasoning is that the source block type is more often the desired behavior.

The following would create a source block under this proposal.

```
:source-language: ruby
:source-highlighter: coderay

----
puts "Hello, World!"
----
```

The following would create a listing block.

```
:source-language: ruby
:source-highlighter: coderay

[listing]
----
puts "Hello, World!"
----
```

**Comment by mojavelinux** [comment]
It should also be possible to set the language without setting the block style.

```
[,ruby]
----
puts 'Hello, World!'
----
```

So check for either the first positional attribute (after the style) or the `source-language` on the document.

I don't think this should be coupled with the `source-highlighter` attribute since we are talking about semantics, not output.

**Comment by elextr** [comment]
Not criticising the idea, just questioning why there would be a need for a language if no source highlighter is identified?

**Comment by mojavelinux** [comment]
Because it still adds metadata to the HTML that can be processed downstream (think HTML pipeline).

```
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-ruby" data-lang="ruby">puts "Hello, World!"</code></pre>
</div>
</div>
```

(arguably it should be a sourceblock, but we're working with the existing CSS classes rn).

**Comment by mojavelinux** [comment]
Now that I figured out how to do this with almost no change to the code, I'm really liking the idea. As it turns out, it broke zero tests. In the worst case, users will get syntax highlighting on some extra listing blocks, so the side effects are extremely low.

At the simplest, you can now define a source block as follows:

```
[,ruby]
----
puts 'Hello, Ruby!'
----
```

If you're using the source-language attribute, here's how your document might look:

```
:source-language: java

----
System.out.println("Hello, Java!")
----

[,ruby]
----
puts 'Hello, Ruby!'
----

[listing]
----
Generic listing block.
----
```

I'd go so far to say that this matches the convenience of Markdown-style fenced code blocks, which is what we really wanted all along.
