### ISSUE TITLE
Introduce configuration to customize reference labels

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1132]
Introduce configuration, or otherwise document how, to customize reference labels.

> Can I influence how cross references are rendered and how? The default asciidoctor html output does just render the section/example/table title. I would like to have something as we had in the docbook rendering 'Section x.y "bla bla"' or "Example 2.1 "bla bla"'.

**Comment by mojavelinux** [comment]
Customization of the built-in labels using attributes is now documented in the user manual. See http://asciidoctor.org/docs/user-manual/#language-support. Therefore, the focus of this issue will now turn to the custom configuration file.

**Comment by mojavelinux** [comment]
Similar to #858.

**Comment by getreu** [comment]
+1 for [issuecomment-63163932](https://github.com/asciidoctor/asciidoctor/issues/858#issuecomment-63163932):
>    it would be nice to have the same 3 styles available: xref, xref-number and xref-number-and-title

By default docbook renders references like this
* _Section  7.6, “Functionality oriented validation”_
or just
* _Section 7.6_ 

I need both versions in HTML5. Now with the new [labels](http://asciidoctor.org/docs/user-manual/#customizing-labels) the groundwork is in place. Are there any news? 


*) The numbered only version you get with `<xsl:param name="xref.with.number.and.title" select="0"></xsl:param>`

(see same [comment  in #858](https://github.com/asciidoctor/asciidoctor/issues/858) )

**Comment by mojavelinux** [comment]
I'm rolling this into the fix for #858 since to fix one, we really have to fix the other.

**Comment by mojavelinux** [comment]
> I need both versions in HTML5.

These are the very two cases that will be covered by the fix for #858. The style is controlled by the `xrefstyle` attribute. The values are as follows:

* full - label number, title in quotes (e.g., Section 7.6, “Functionality oriented validation”)
* short - label number (e.g., Section 7.6)

The title in quotes is quiet fancy. If the reference is a chapter or appendix, the title is italicized. Otherwise, it is enclosed in curved double quotes.

**Comment by mojavelinux** [comment]
The fix for this issue is contained in PR #2220.

**Comment by mojavelinux** [comment]
Resolved by 8e80317dee56483e48a07451bff0cd14f0bfd59c.

Documentation: http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text
