### ISSUE TITLE
Allow multiple hyphens to be used to create a nested list item

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1136]
Between 1 and 5 asterisks can be used to create a list item, but only 1 hyphen can be used. Thus, while it's possible to use asterisks to create nested list items:

```
* item 1
** 1a
** 1b
```

It's not possible to use only hyphens to create list items. Under this proposal, the following syntax would be permitted for creating nested list items:

```
- item 1
-- 1a
-- 1b
```

Double hyphen is already used in several places in the AsciiDoc syntax:
- open block delimiter
- dash replacement
- attribution for the shorthand blockquote form

We don't anticipate than any of these scenarios will conflict with the use of multiple hyphens for nested list items. If you know of a case, please cite it.

**Comment by mojavelinux** [comment]
I'm less convinced now that we should do this. The hyphen is really a special case and asterisks should be preferred.

Can someone cite another markup language that uses repeating hyphens for list items?

**Comment by u0421793** [comment]
What if it were
- first level
-> next level
->> even nexter level

Could that work for lists that have an order?
. first level
.> next level
.>> even more of that

or would that get accidentally interpreted as the closing tag of <<this>>

**Comment by mojavelinux** [comment]
The more I've worked with AsciiDoc, the more I'm convinced allowing multiple hyphens is a bad idea. We don't want to add more ways to do things. The preferred way is multiple asterisks. Hyphens remain an alternate way to create the top level list, but should not really be used otherwise.

**Comment by RichardJECooke** [comment]
Why don't you allow hyphens?  Asterisks take *far* longer to type. This is the first thing I googled now that I'm learning asciidoc

**Comment by elextr** [comment]
Agree with @mojavelinux, dash is already so heavily overloaded in Asciidoc (emdash and open block and listing block, oh and dash and minus if you do math) that there is no clear backward compatible way to allow multiple levels of list using only dash as the markup character.  

Perhaps you are using a different keyboard layout, but on the most common keyboard layouts asterisk is a shifted key, it takes no longer to type.
