### ISSUE TITLE
Support options="breakable" and options="unbreakable" for tables in Docbook backends.

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor#1140]
These options tell FOP to allow tables to split across a page break or not: see

http://discuss.asciidoctor.org/Preventing-tables-from-breaking-across-pages-td2182.html#a2337

Changes required: add 

if (node.option? 'breakable')
  result << %(<?dbfo keep-together="auto"?>)
end 

and similar for unbreakable to docbook5.rb and docbook45.rb. Possibly update user guide and tests.

**Comment by mojavelinux** [comment]
Keep in mind you can write this using the following syntax:

```
[%unbreakable, format=csv]
|===
customers.csv[]
|===
```

That's how it should be documented so we are recommending the most concise way :)
