### ISSUE TITLE
TOC together with no-header-footer option

### ISSUE THREAD

**Issue by Hocdoc** [asciidoctor/asciidoctor#1161]
If I use the `--no-header-footer` option, Asciidoctor doesn't render the Table of contents (TOC).

F.ex.: `asciidoctor -a toc --no-header-footer mydoc.adoc`

When I would like the document without TOC, I wouldn't use the `-a toc`argument.

Is it possible to render the TOC without the HTML headers?

**Comment by mojavelinux** [comment]
I'm going to mark this as a documentation issue. There needs to be a dedication subsection in the user manual about how to enable the toc in the embeddable HTML output. The documentation should also clarify that, at the moment, the left and right toc are not available in this scenario.

**Comment by mojavelinux** [comment]
Note that there's an open issue to insert the TOC in a default position in the embeddable HTML. See #1443.

**Comment by mojavelinux** [comment]
This is now documented in the user manual:

http://asciidoctor.org/docs/user-manual/#using-a-toc-with-embeddable-html

(it could still use some work, but at least it is now mentioned).

**Comment by abelsromero** [comment]
> (it could still use some work, but at least it is now mentioned).

Having suffered this issue, I think the new explanation is good enough. If only, I would add the explanation of what `preamble` and `macro` do, to the initial bullet list at the beggining.

**Comment by mojavelinux** [comment]
There is a section on macro, but not preamble. The next step is to add the missing section on preamble, then make the links.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor.org/issues/418

**Comment by rockyallen** [comment]
There is a section on preamble, but it is confused with toc-placement:
````


Asciidoctor also has a toc-placement attribute, that when set with a value of preamble places the TOC below the preamble. You do not need to include the toc::[] block macro in the document when using the preamble value.

If you set toc-placement but don’t assign it a value, the TOC will be placed in the document’s header by default.
	The toc-placement and toc-position attributes are mutually exclusive. 
````
