### ISSUE TITLE
Consider addition of "click" to style sheet

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1166]
Consider addition of "click-to-reveal" style (see http://www.noteshare.io/notebook/56/?note=856 for an examples and fuller description).  

Good for quizzes, problem sets, etc: click on title to reveal content, click again to hide

This requires a few lines of CSS and also of javascript (I don't know if the latter is permitte).  I am injecting both into asciiodctor docs experimentally using a crude preprocessor).

Asciidoctor example:

The CSS:

```
[source, css]
--
.openblock.click {
  .title { color: blue; }
  .content {
    .paragraph {
      font-style: oblique;
      }
  }
}
--
```

The Javascript

```
[source, javascript]
--
$('.openblock.click').find('.content').hide()

  $('.openblock.click').click ->
    $(this).find('.content').slideToggle('200')
--
```

**Comment by mojavelinux** [comment]
I'm happy to say that this feature is now available in 2.0.0. See #1699.

```
.Toggle Me
[%collapsible]
====
This content is revealed when "Toggle Me" is clicked.
====
```

The best part is, we're relying on built-in behavior of the browser / HTML 5.
