### ISSUE TITLE
Source code block inside a sidebar block is not rendered correctly

### ISSUE THREAD

**Issue by lordofthejars** [asciidoctor/asciidoctor#1171]
If you create a sidebar block and inside it you create a source code block. Then when you render to html it is not rendered correctly because of colors. Because source code block and sidebar block uses the same grey color, it seems that source code block is floating inside the sidebar instead of being a part of it.

Maybe we should change grey color of one of both blocks, or detect that source code block is inside a sidebar block and change it to white.

**Comment by mojavelinux** [comment]
This was resolved in 1.5.0 and further refined in 2.0.0. It's still going to highly depend on the style used for syntax highlighting, but we've taken steps to try to prevent it from happening in the default case.
