### ISSUE TITLE
Add support for epigraphs

### ISSUE THREAD

**Issue by bk2204** [asciidoctor/asciidoctor#1195]
DocBook provides an epigraph element, that it describes as "a short inscription, often a quotation or poem, set at the beginning of a document or component." I like to use epigraphs, and notable works like _The Practice of Programming_ use them as well.

It would be nice if Asciidoctor provided support for epigraphs. We should support `literallayout` elements (verse-style blocks) as well as `para`/`simpara` elements (prose blocks), and support attributions as well.

**Comment by shahryareiv** [comment]
Just to add that epigraphs can include images both inline and block.

**Comment by mojavelinux** [comment]
This is now implemented in PR #2664 and slated for the 1.5.7 release.

**Comment by bk2204** [comment]
Awesome, thanks!

**Comment by mojavelinux** [comment]
Thanks for replying. Here we go!

**Comment by mojavelinux** [comment]
Thanks again @bk2204! Sorry for taking so long to get this merged. Issues like this one are why we're reevaluating how the project is managed so we can do better.
