### ISSUE TITLE
Support inlining SVG images in HTML5 output

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor#1224]
When generating HTML5 output, SVG images can be inlined directly into the main output document. This could be an optional feature of the HTML5 backend that is enabled when data-uri is set.

**Comment by mojavelinux** [comment]
Do you think we should do this when

a. the `data-uri` is set on the document and
b. the interactive option is set on the image

instead of using a base64 encoded data URI?

**Comment by mojavelinux** [comment]
In other words, I'm trying to decide under what conditions this happens.

**Comment by mojavelinux** [comment]
We are now discussing this as part of #1301.

**Comment by mojavelinux** [comment]
I'm going to say that this change is covered by #1301. I don't think that `data-uri` alone should enact this behavior because there are certain implications brought on by using the `<svg>` element. In other words, these are two separate things.
