### ISSUE TITLE
Load highlight.js asynchronously

### ISSUE THREAD

**Issue by kendall** [asciidoctor/asciidoctor#1238]
Hey,

Google Speed test thingie recommends to load highlight.js asynchronously to improve the above-the-fold rendering performance of my Asciidoctor site (http://docs.stardog.com/)...I suspect it would say the same for most Ad sites.

Would you consider switching to loading https://cdnjs.cloudflare.com/…x/libs/highlight.js/8.4/highlight.min.js asynchronously?

**Comment by webarthur** [comment]
I found a way to do this:

```html
<script async src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
<script>
var awaitFor = function (cond, cb, timeout = 100) {
  !cond() ? setTimeout(() => awaitFor(cond, cb, timeout), timeout) : cb()
}
awaitFor(() => typeof hljs !== 'undefined', function () {
  const blocks = document.querySelectorAll('pre code');
  blocks.forEach(hljs.highlightBlock);
})
</script>
```
