### ISSUE TITLE
Role not applied to section header in HTML

### ISSUE THREAD

**Issue by kenfinnigan** [asciidoctor/asciidoctor#1239]
I'm unable to specify a css class to be attached to a section header.

If I specify:

``` AsciiDoc
[role="section-header first"]
== Getting Started
```

or

``` AsciiDoc
[.section-header.first]
== Getting Started
```

the css classes are added to the surrounding section `div` instead of the `h2`.

**Comment by mojavelinux** [comment]
I've logged this in the semantic HTML 5 issue. We'll address it there.
