### ISSUE TITLE
Cross-Reference to Section titles: problematic with lower-case or non-ascii first characters

### ISSUE THREAD

**Issue by nicesw123** [asciidoctor/asciidoctor#1242]
In the following the rendered version yields cross-reference links that do _not_ work

```
= Test
:toc:
:icons: font

[TIP]
====
Refer to:

* <<aaa>>
* <<Bbb>>
* <<Übersetzungen>>
====



== aaa

aaa section

== Bbb

Bbb section

== Übersetzungen

Übersetzungen section
```

**Comment by mojavelinux** [comment]
Thanks to improvements in Ruby itself, this now works without any changes to Asciidoctor. You just need to be using Ruby 2 (preferably 2.5).
