### ISSUE TITLE
Switch the CI builds to the new Travis CI infrastructure

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1243]
Switch the CI builds to the new Travis CI infrastructure.

Making this switch seems to be a matter of adding the following change to the *.travis.yml* file:

```
sudo: false
```

We should also consider when caching is appropriate. I do worry that caching gems could give us false positives, so let's weigh the tradeoffs.

See http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by Mogztter** [comment]
Resolved by 38c2d32fb0e9504f350cdca496eff0e9b7683de8 ?

**Comment by mojavelinux** [comment]
Indeed! Good catch!
