### ISSUE TITLE
Multi-numbered list and links to the numbered list items request

### ISSUE THREAD

**Issue by shpshp** [asciidoctor/asciidoctor#1246]
**A. Numbered list:**
_Source:_

```
, List item
, List item
,, List item
,,, List item
,, List item
, List item
, List item
```

_Result:_
1. List item
2. List item
  2.1. List item
    2.1.1. List item
  2.2. List item
3. List item
4. List item

**B. Links to numbered list items:**
_Source:_

```
, List item
,[[link1]] List item
,, List item
,,,[[link2]] List item
,, List item
, List item
, List item

Link to the <<link1>> item. Another link is to the <<link2>> item.
```

_Result:_
1. List item
2. List item
  2.1. List item
    2.1.1. List item
  2.2. List item
3. List item
4. List item

Link to the 2 item. Another link is to the 2.1.1 item.

**C. Links to the ordinary alpha-numbered list items:**
_Source:_

```
. List item
.[[link3]] List item
.. List item
...[[link4]] List item
.. List item
. List item
. List item

Link to the <<link3>> item. Another link is to the <<link4>> item.
```

_Result:_
1. List item
2. List item
  a. List item
    i. List item
  b. List item
3. List item
4. List item

Link to the 2 item. Another link is to the 2.a.i item.

P.S. Thank you!!!

**Comment by mojavelinux** [comment]
This is now possible thanks to the fix for #2257.

**Comment by grv87** [comment]
Looks like this feature request was not implemented fully. Numbered links are still missing, see #3253

**Comment by mojavelinux** [comment]
What you're talking about is styling the reference using the xrefstyle. That's a different issue, so I disagree it means this issue is incomplete. If you have thoughts about #3253, please comment there.

**Comment by grv87** [comment]
@mojavelinux, in **B** expected result is:

```
Link to the 2 item. Another link is to the 2.1.1 item.
```

How is it implemented now? Without using xrefstyle?

**Comment by mojavelinux** [comment]
List items have never been an xref target*, and thus xrefstyle has never applied here. Adding that functionality would be an entirely new feature.

\* It's possible to define an inline anchor at the start of a list item, but then the xref is targeting that anchor, not the list item itself.

**Comment by grv87** [comment]
@mojavelinux, so, just like I said: this feature is not fully implemented. What is described in the first post is not actually available right now.

I'm not complaining, just clarifying for myself and others.

**Comment by mojavelinux** [comment]
Fair enough. But I never claimed that was the goal since the list number is simply not a referencable label. HTML does not make that information available and thus we can't use it. And we're not going to start tracking list numbers ourselves (at least, not right now) since that would lead to all sorts of other complications.
