### ISSUE TITLE
Follow ascii-id attribute for titles with accents with dblatex

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor#1247]
Asciidoctor doesn't follow [ascii-id attribute reference of asciidoc](http://www.methods.co.nz/asciidoc/asciidoc.css-embedded.html#_section_ids). It will be difficult to produce books that has titles with accents with dblatex.

I know it has a Warnning:

> "This attribute may be deprecated in future releases and should be avoided"

But as long it is necessary for dbaltex we will need it.

```
wget https://gist.github.com/edusantana/1390ad6b3cbb28633f23/raw/3beed1044a506c61968ee97c93037519406f6268/gistfile1.asciidoc -O asciidoctor.adoc
wget https://gist.github.com/edusantana/1390ad6b3cbb28633f23/raw/3beed1044a506c61968ee97c93037519406f6268/gistfile1.asciidoc -O asciidoc.adoc

asciidoctor -d book -b docbook45 asciidoctor.adoc
asciidoc -d book -b docbook45 asciidoc.adoc
```

Works with `asciidoc.xml`:

```
~/temp/asciidoctor$ dblatex asciidoc.xml
Build the book set list...
Build the listings...
XSLT stylesheets DocBook - LaTeX 2e (0.3.5)
===================================================
Build asciidoc.pdf
'asciidoc.pdf' successfully built
```

The `asciidoctor.xml` won't build with dblatex:
```
    ~/temp/asciidoctor$ dblatex asciidoctor.xml
    Build the book set list...
    Build the listings...
    XSLT stylesheets DocBook - LaTeX 2e (0.3.5)
    ===================================================
    Build asciidoctor.pdf
    pdflatex failed
    asciidoctor.aux:31: Missing \endcsname inserted.
    asciidoctor.aux:31: leading text: ...{}tulo}{{1}{1}{Meu cap�tulo}{chapter.1}{}}
    asciidoctor.aux:33: Missing \endcsname inserted.
    asciidoctor.aux:33: leading text: ... }o}{{1.1}{1}{Minha se��o}{section.1.1}{}}
    asciidoctor.aux:35: Missing \endcsname inserted.
    asciidoctor.aux:35: leading text: ... � minha subsubse��o}{subsection.1.1.1}{}}
    asciidoctor.aux:35: Missing $ inserted.
    asciidoctor.aux:35: leading text: ... � minha subsubse��o}{subsection.1.1.1}{}}
    asciidoctor.aux:73: Missing $ inserted.
    asciidoctor.aux:73: leading text: \end{document}
    Unexpected error occured
    Error: pdflatex compilation failed
```

**Comment by edusantana** [comment]
To fix the *problem*, we are to set uft8 param as described [here].(http://aerostitch.github.io/misc/asciidoc/asciidoc-title_uft8.html):

    dblatex -P "latex.encoding=utf8" asciidoctor.xml

With this, we don't have to change a thing.

**Comment by mojavelinux** [comment]
Fantastic! I think this is a much more sound approach because it honors the original id.

Perhaps we can get this mentioned in the Asciidoctor user manual. See https://github.com/asciidoctor/asciidoctor.org/commit/9eacccdc1ae749f19e7789dab977565377cec848.

**Comment by philipmarion** [comment]
solution 1: dblatex -b xetex file.xml  works fine for me (file.xml is utf8 encoded with french accent) 
solution 2: using "explicit id" without accent for titles subtitles in file.adoc

[[title-without-problem]]
=== titre à problème
