### ISSUE TITLE
include:: fails with weird in-document message instead of failing to build

### ISSUE THREAD

**Issue by ktoso** [asciidoctor/asciidoctor#1251]
This issue is a follow up to https://github.com/asciidoctor/asciidoctor/issues/1250

Getting weird things when `include::` "seems to fail" - no idea if it actually fails or what is happening. Nothing useful in the logs as well - no warnings, no errors.

See below, such code (the path is valid, in safe mode it rendered a proper link):

```
include::{sourcedir}/actor/ActorDocSpec.scala[]
```

yields in the rendered document:

```
Unresolved directive in <stdin> - include::../../test/scala/akka/actor/ActorDocSpec.scala[]
```

I'm running in UNSAFE mode.

**Comment by mojavelinux** [comment]
Starting in 1.5.7, warnings and errors are routed to the logger. It's possible to consult the maximum severity reported and fail the build if it is reached. This functionality is also accessible via the `--failure-level` CLI option.
