### ISSUE TITLE
v 1.5.2 with args '-d inline' return nothing.

### ISSUE THREAD

**Issue by dongwq** [asciidoctor/asciidoctor#1258]
v 1.5.2 with args '-d inline' return nothing.

**Comment by mojavelinux** [comment]
May I ask what the input document looks like?

Here's an example that shows the inline doctype in action:

```
$ echo '_hello_' | asciidoctor -d inline -
```

Produces:

```
<em>hello</em>
```

Inline is intended for a single paragraph of content. It doesn't work with non-paragraph blocks.

**Comment by dongwq** [comment]
how about this
```
 ==== section 1
- line 1
- line 2
```
i am trying to find the usage like [bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/)

**Comment by mojavelinux** [comment]
The inline doctype is intended only for formatting a single sentence (or
group of sentences), nothing else.

You may just want to disable the header & footer (i.e., the surrounding
HTML template). In that case, use -s instead.

**Comment by dongwq** [comment]
got it ,thank you very much

**Comment by mojavelinux** [comment]
This information is detailed in the user manual. http://asciidoctor.org/docs/user-manual/#document-types

**Comment by dongwq** [comment]
with header_footer = false, toc is not showed either. is there a way to get toc only?

**Comment by mojavelinux** [comment]
Not without using the API. What you are probably looking to do is create a custom script that loads the document and hand-selects nodes to render, such as the toc. You can do this using something like:

```ruby
doc = Asciidoctor.load_file 'sample.adoc', safe: :safe, attributes: 'toc=macro'
converter = doc.create_converter
puts converter.convert doc, :toc
```

You are essentially forcing the `toc::[]` macro to render.
