### ISSUE TITLE
Using Passthroughs

### ISSUE THREAD

**Issue by gvaish** [asciidoctor/asciidoctor#1259]
I am trying to make pass `++++` work.

I started with this content: [example.adoc](https://raw.githubusercontent.com/asciidoctor/asciidoctor-pdf/master/examples/example.adoc)

Added the following:

```
.Code using Pass
====
++++
<programlisting language="ruby">
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
</programlisting>
++++
====
```

Sadly, the result is not what I expected. See the screenshot.

Wondering where did I mess up.

![screen shot 2015-01-09 at 9 41 52 am](https://cloud.githubusercontent.com/assets/266251/5684293/c8c2bfb2-97e3-11e4-8546-5d55376ba8b5.png)

**Comment by gvaish** [comment]
Just to add... noticed that the `[source]` is rendered as `listingblock` while the `++++` is rendered as `exampleblock`. To me, it suggests that my markup is wrong.

Any suggestions...

**Comment by mojavelinux** [comment]
Gaurav, you can't pass DocBook content directly to Asciidoctor PDF / Prawn. Asciidoctor PDF only understands how to process AsciiDoc content and, in some places, inline HTML.

You could take this approach using fopub (or a2x), which will use the DocBook toolchain to process the content. First, you'd convert the document to DocBook using the `-b docbook` backend, then run fopub or a2x on the result.

**Comment by gvaish** [comment]
Oh well, I just ran `asciidoctor` rather than the `asciidoctor-pdf`.

But I think, the rule still applies.

**Comment by mojavelinux** [comment]
Indeed. It's important to keep in mind that passthrough takes the content as is and passes it to the output. So you need to surround it with a conditional guard so it only outputs to the appropriate backend.

For instance:

```
ifdef::basebackend-docbook[]
++++
docbook markup here
++++
endif::[]
ifdef::basebackend-html[]
++++
html markup here
++++
endif::[]
```

Keep in mind that Asciidoctor PDF responds to `basebackend-html`, so you might want to just use `backend-html5` instead if you only want to output when the backend is `html5`.

**Comment by gvaish** [comment]
:+1: That worked.

However, I noticed that the default `html` template only shows the images `./images/icons/callouts/1.png`. See [html5 converter](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L388)

Won't it be better to output as:

```
<a id="#{callout-id}"><img src="#{node.icon_uri "callouts/#{num}"}" alt="#{num}"#{@void_element_slash}></a>
```

for the co-id and then render the ref using `<a href="#{callout-id}"><img ... /></a>`?

* PS: I don't know how to get `callout-id`. I see it generated [href](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/callouts.rb#L31)

**Comment by mojavelinux** [comment]
Asciidoctor mimics the output from AsciiDoc Python, which is the reasoning why we have the output we do in the html5 backend. Having said that, we could definitely consider adding an anchor point and a xref between the callout description and the callout location. Perhaps best to file that as a separate issue.

**Comment by gvaish** [comment]
Created #1263

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Closing issue in favor of #1263.
