### ISSUE TITLE
asciidoctor -h should list backends

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor#1271]
As per https://github.com/asciidoctor/asciidoctor.org/issues/348

**Comment by plaindocs** [comment]
The 'nice' way to do it might be to dynamically list the installed backends, but I'll just add the defaults manually for now.

**Comment by mojavelinux** [comment]
I agree, Asciidoctor should be able to determine which backends are available. I've noted that down in my list to look into.

Keep in mind, when working with the template converter, the backend actually tells the converter where to look to find templates. Thus, the backend is not always something that is available as much as it is a directive. It's funny like that.

**Comment by mojavelinux** [comment]
Closed via 01714175cafe4b9db6fc50f079502881a8516dc5 and 2157285d0458cb3afb3f3f4919af9ad84e00613b.

We've settled on the manual list for now. Let's track the dynamic list in a separate issue.
