### ISSUE TITLE
Use separate attribute for extension of inter-document links

### ISSUE THREAD

**Issue by nh2** [asciidoctor/asciidoctor#1273]
I'd like to create PDFs from AsciiDocs by printing the generated files to PDF with a headless browser (e.g. [`wkhtmltopdf`](http://wkhtmltopdf.org/)).

(In the future `asciidoctor-pdf` might do it for me, but right now it is not possible to get that to work with Latex too well, and my formulas look great in MathJax.)

The problem is that relative links (`<<somedoc#some-id, my link text>>`) are, naturally pointing to HTML files in the headless browser; I'd like them to become PDFs, so that I can jump from one PDF to the other one (works great in PDF readers like `evince`) - in the PDF, the link to a relative `.html` file is no longer meaningful.

I first thought I could do this with the `:outfilesuffix:` attribute, but it also changes the file type of the output files, which is not what I want (`.html` is fine and right for that).

I think there are two solutions:
- Add another property, like `:linksuffix:` to set the link suffixes independent from the output file suffix (that would be used [here](https://github.com/asciidoctor/asciidoctor/blob/5d037c3bb619505c9fc732583e641e7792dca594/lib/asciidoctor/substitutors.rb#L1087) then).
- Set (or allow me to set) a class on the `<a>`s that asciidoctor generates from `<<link>>`s. Then I could fix up the links from `.html` to `.pdf` in my headless browser (e.g. `wkhtmltopdf` has a `--run-script` option for running some JS before printing).

What do you think?

**Comment by mojavelinux** [comment]
I agree, except I would choose the name `relfilesuffix` (short for "relative file suffix") to be consistent with the prefix, `relfileprefix`.

See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb#L1087

**Comment by mojavelinux** [comment]
It will also be important to document the scenario to which this attribute applies since it's quite specific.

**Comment by jxxcarlson** [comment]
I just tried wkhtmltopdf with, alas, unsatisfactory results. Much of the math was not rendered. At the bottom of the file was a message, "Processing math 5%'.

**Comment by nh2** [comment]
> I just tried wkhtmltopdf with, alas, unsatisfactory results. Much of the math was not rendered. At the bottom of the file was a message, "Processing math 5%'.

I think that is because `wkhtmltopdf` takes its snapshot right after all JS is loaded, before JS is acutually processed.

You should be able to get it working with the `--javascript-delay N` (where N are milliseconds) option.

As an alternative more robust solution, I use `--window-status DoneRendering` together with the `--run-script "$(cat pdf-mathjax-config.js)"`, where `pdf-mathjax-config.js` contains:

```js
// Signal when rendering is done.
MathJax.Hub.Register.StartupHook("End", function () {
  window.status = "DoneRendering";
});
```

That way, MathJax "tells" the headless browser when rendering is done by setting `window.status`, on which the headless browser is polling for a specific value (`DoneRendering`).

But for just tryin it out, `--javascript-delay 3000` might be good enough.

For both options you may need a recent version of `wkhtmltopdf`.

**Comment by mojavelinux** [comment]
This issue is about the file suffix of relative links. Can we keep the conversation focused on that topic? Thanks!

**Comment by mojavelinux** [comment]
> I first thought I could do this with the :outfilesuffix: attribute, but it also changes the file type of the output files, which is not what I want (.html is fine and right for that).

Actually, you can do that. You just need to reset the value at the bottom of the document.

```
:real-outfilesuffix: {outfilesuffix}
:outfilesuffix: .pdf

content

:outfilesuffix: {real-outfilesuffix}
```

I realize that's still a hack, so I'm prepared to move forward with the relfilesuffix proposal.

**Comment by mojavelinux** [comment]
> Set (or allow me to set) a class on the <a>s that asciidoctor generates from <<link>>s. Then I could fix up the links from .html to .pdf in my headless browser (e.g. wkhtmltopdf has a --run-script option for running some JS before printing).

This is already possible. You can set a role on all links, either by adding the role explicitly to the link or by using an Asciidoctor extension. But again, this is not an optimal approach for this problem.

**Comment by mojavelinux** [comment]
This is also needed by the Middleman integration. It's necessary since manipulating outfilesuffix is not an option in that environment.
