### ISSUE TITLE
Reference to image not working

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1275]
Should not the following work?

```
== test

[[image-bird]]
image::458.jpg[]

I refer to <<image-bird>>
```

I see the image, but below the image I see only `I refer to`.

**Comment by rockyallen** [comment]
Does this work:
````
== test
.Image of a bird
[[image-bird]]
image::458.jpg[]

I refer to <<image-bird>>
````

**Comment by mojavelinux** [comment]
Jim, what you should see is:

```
I refer to [image-bird].
```

Where `[image-bird]` is a link to the `#image-bird` anchor.

As @rockyallen points out, if you expect to see a human-readable title, then you need to give a title to the image. The example @rockyallen provides should produce:

```
I refer to Image of a bird.
```

Where `Image of a bird` is a link to the anchor `#image-bird`.

Alternatively, you can assign a reference title without adding a title (caption) to the image using:

```
[[image-bird,Image of a bird]]
image::458.jpg[]
```

If you are looking for a more formal reference label, then perhaps you are interested in the following issue: #858 (and #1132).

**Comment by mojavelinux** [comment]
I filed an issue in the user manual to document the xreflabel attribute more explicitly. See https://github.com/asciidoctor/asciidoctor.org/issues/380
