### ISSUE TITLE
Dangling comment title?

### ISSUE THREAD

**Issue by nh2** [asciidoctor/asciidoctor#1276]
Could you have a look at these two AsciiDoc files?

https://gist.github.com/nh2/576b1b30f9f63a1dab37

It seems like that in `DanglingTitleProblem.adoc` the `.A comment title` title to the `////` comment is rendered *after* the next heading.

Is this to be expected, or a bug?

Thanks!

**Comment by mojavelinux** [comment]
That's as designed. A comment block can't have a title...essentially the comment block is invisible to the parser. The heading drops down to the next block element. Make sense?

**Comment by mojavelinux** [comment]
The workaround is to use the open block form of the comment block.

```
.this title is not rendered
[comment]
--
this content is not rendered
--

this content is rendered
```

**Comment by nh2** [comment]
OK, thanks for the explanation!

What still surprises me is that the dangling title is rendered *after* the next heading, even though it appears before the next `==` heading.

**Comment by mojavelinux** [comment]
I agree it's surprising, but that's the behavior that matches AsciiDoc Python. Metadata "falls through" until it hits a place where it applies. This behavior doesn't make much sense, especially in this case, so I've noted it down to revisit this when we're working on the AsciiDoc specification.

**Comment by nh2** [comment]
That makes sense. Thank you!
