### ISSUE TITLE
Strict mode for non existent attributes

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/asciidoctor#1277]
If one is using attributes it would be nice to get asciidoctor to throw an error if the attribute does not exist. 

An additional attribute in the like of http://asciidoctor.org/docs/user-manual/#catch-a-missing-or-undefined-attribute would seem to fit

```
attribute-missing: error
```

**Comment by mojavelinux** [comment]
I have news I hope you'll like. We added the value `warn` to the `attribute-missing` attribute in 1.5.1. When this value is set, Asciidoctor will issue a warning when a reference to a non-existing attribute is detected. Does that suit your requirements, or are you expecting the processor to fail?

At the very least, we need to update the docs to document this new value.

**Comment by plaindocs** [comment]
That is good news.

A fail option would make sense as well I think, but I can check for it in the build in the meantime.

I'll try to update the docs.

**Comment by mojavelinux** [comment]
:+1:

**Comment by rkratky** [comment]
@mojavelinux Perhaps this issue can be closed now that the PR has been merged?

**Comment by mojavelinux** [comment]
I just reworked the docs on this topic in the user manual. I think it's a lot clearer now and I think it covers the issue at hand.

I also mentioned how it's possible to force the document to fail as a result of the warnings so you don't have to go parsing the log.

See https://asciidoctor.org/docs/user-manual/#catch-a-missing-or-undefined-attribute.
