### ISSUE TITLE
:toc: not processed when not adjacent to doc header

### ISSUE THREAD

**Issue by Bjorn-Oksnevad** [asciidoctor/asciidoctor#1278]
First of all, thanks for all the Asciidoctor development!

I noticed there is a difference how :toc: is handled vs :numbered: and :sectlinks: in terms of being separated by a blank line from the document header.  When the :toc: attribute is separated from the document header by a blank line, the table of contents is not rendered.

Please see https://gist.github.com/Bjorn-Oksnevad/2531d473f9f794a8fac7 for passing and failing adoc examples.

OS: Windows 7
Ruby: ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
Asciidoctor: Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]) (lc:IBM437 fs:Windows-1252 in:- ex:IBM437)

**Comment by mojavelinux** [comment]
This is a syntax rule. The `toc` declaration must be in the header. The reason is because this information must be available in the document template, which can only see attributes defined in the header (as well as external attributes passed to the processor).
