### ISSUE TITLE
AsciiDoc misinterprets first row as header row if first cell contains blank second line

### ISSUE THREAD

**Issue by sandersk** [asciidoctor/asciidoctor#1284]
If an AsciiDoc table does not contain `options`, but does contain a blank line in its first table cell, e.g.

```
|======
|Row 1 cell 1 line 1

Row 1 cell 1 line 2|Row 1 cell 2
|Row 2 cell 1|Row 2 cell 2
|Row 3 cell 1|Row 3 cell 2
|======
```

Then AsciiDoctor interprets the first row as a heading row because the second line is blank, even though the first row is not separated from the second by a blank line. Relevant code:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L2279

If the table is PSV, maybe it would be preferable to check that both the second line is blank, and the third line starts with the proper delimiter before classifying the first row as a header? 

That said, this is a real edge case, so it may not be worth adding additional complex table-analysis logic for it, as users can add `[options=""]` to ensure the first row is interpreted as a body row. Just thought I'd raise as something to potentially consider.

**Comment by mojavelinux** [comment]
It's reasonable that you bring this up because this is a general problem right now in the table parser. We have a similar open issue that covers another edge case. We are cheating too much looking for a table header...so the fix is detecting the implicit header row more carefully.

For the other issue, see #644.

**Comment by sandersk** [comment]
Thanks for the quick response, Dan, and the additional context.

**Comment by mojavelinux** [comment]
We'll get it fixed asap. I scheduled it for 1.5.4 since the scope in 1.5.3 is already set. Hopefully 1.5.3 will be out soon-ish and we'll be working on 1.5.4 immediately after.
