### ISSUE TITLE
Title of some included fragments are not processed

### ISSUE THREAD

**Issue by fbiville** [asciidoctor/asciidoctor#1288]
Hi, 

I've been facing this issue with `asciidoctor-maven-plugin` (latest version, i.e. 1.5.2) and `asciidoctor` gem and even with the latest `asciidoctorj-pdf` (1.5.0-alpha.6). 

Here is the output of `asciidoctor -v`:

```shell
$> asciidoctor -v
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8) 
```

I've got the following inclusions:

```asciidoc
include::_1_FindByCode_NONE.adoc[]
include::_2_FindByCode_CHILDREN.adoc[]
include::_3_FindByCode_204.adoc[]
include::_4_FindByCode_400.adoc[]
include::_5_FindAll_Default.adoc[]
include::_6_FindAll_Paging.adoc[]
```

All sections start with a title prefixed with `===`.
**Both titles of 4th and 5th documents are not processed at all, appearing as plain text in both HTML and PDF output.**

If these documents are included separately (like I do with `asciidoclet` [v1.5.2], 1 doc = 1 integration test), no problems occur.

Feel free to tell me if you need more elements to investigate.

**Comment by fbiville** [comment]
Same problem with `asciidoctor-maven-plugin` (v1.5.3-SNAPSHOT, still using `asciidoctorj` v.1.5.2).
I tried to patch `asciidoctor-maven-plugin` (v1.5.3-SNAPSHOT) in order to get it running with `asciidoctorj` (v1.5.3-SNAPSHOT) but the build hangs, with the following message:

```shell
Running org.asciidoctor.maven.test.AsciidoctorHttpMojoTest
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at ../../../src/share/instrument/JPLISAgent.c line: 844
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "asciidoctor-thread-1"
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Thread-2"
```

**Comment by rockyallen** [comment]
Do your files 4 and 5 start with blank lines? I think that Asciidoctor needs them before section titles.

**Comment by fbiville** [comment]
It works! Quite weird but I'm glad this fixes it! :)

**Comment by mojavelinux** [comment]
The topic of includes and whitespace (blank lines) is covered in the following section of the docs.

http://asciidoctor.org/docs/user-manual/#includes-and-whitespace

**Comment by fbiville** [comment]
Thanks Dan! :)
