### ISSUE TITLE
Implementing custom UI

### ISSUE THREAD

**Issue by wongalvis** [asciidoctor/asciidoctor#1289]
Would it be possible to implement a custom UI with our own stylesheets and javascript?
Or coding a new UI template?

**Comment by Mogztter** [comment]
Hi @wongalvis !
Yes you can, Asciidoctor is very flexible and customizable. You can find out more about producing a custom stylesheet here: http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/

**Comment by mojavelinux** [comment]
And don't forget about the custom converters. The easiest path to custom HTML is the template-based converter, which is demonstrated in the [asciidoctor-backends](https://github.com/asciidoctor/asciidoctor-backends) repository. You also have the option of creating a custom Ruby or Java-based converter which allows you to control all aspects of the conversion process.

**Comment by wongalvis** [comment]
Thank you I have a brief idea of the approach to achieve it.
I would like to implement a multi-level push menu (http://tympanus.net/codrops/2013/08/13/multi-level-push-menu/) to make a more elegant and organized UI. Would you please guide me the steps to implement it?

**Comment by Mogztter** [comment]
If you need a well defined structure for the menu, I think it's better to use a custom template as mentioned by @mojavelinux 
You can have a look at https://github.com/asciidoctor/asciidoctor-backends/blob/master/erb/html5/block_toc.html.erb to understand how table of content are processed.

You can start by copying the whole directory (for example `erb/html5`) then experimenting to get the right output.

That being said this not an easy task but the multi-level push menu is really nice and I think your custom UI will be popular :smile:

**Comment by wongalvis** [comment]
See if I make this right:
The template html codes are located under erb file and I can edit it freely as html, and my edit is not limited to changing the theme with css.

**Comment by Mogztter** [comment]
Exactly, for html5 output you have different templating language available, erb, [haml](http://haml.info/) and [slim](http://slim-lang.com/):

 * erb: https://github.com/asciidoctor/asciidoctor-backends/blob/master/erb/html5/
 * haml: https://github.com/asciidoctor/asciidoctor-backends/tree/master/haml/html5
 * slim: https://github.com/asciidoctor/asciidoctor-backends/tree/master/slim/html5

**Comment by wongalvis** [comment]
If I want to ask further questions about changing the template, is there a good place for me to do so?

**Comment by Mogztter** [comment]
You can ask on the mailing-list: http://discuss.asciidoctor.org/ or open a
pull request with early changes to get help.

**Comment by wongalvis** [comment]
How could I do the testing and preview?

**Comment by Mogztter** [comment]
You can follow the [usage instructions](https://github.com/asciidoctor/asciidoctor-backends#general-usage-instructions)

The following command `asciidoctor -T TEMPLATE_DIRECTORY ${options} CONTENT_FILE` will generate HTML from Asciidoctor templates

**Comment by wongalvis** [comment]
I don't understand what does CONTENT_FILE in step 3 and onwards refer to.

**Comment by wongalvis** [comment]
And do I need to install asciidoctor for preview?

**Comment by Mogztter** [comment]
> I don't understand what does CONTENT_FILE in step 3 and onwards refer to.

`CONTENT_FILE ` refers to your AsciiDoc source file (.ad / .adoc file). 

> I don't understand what does CONTENT_FILE in step 3 and onwards refer to.

Yes `asciidoctor` will convert your AsciiDoc source file into an HTML5 page using the template directory (where you've made changes to integrate multi-level push menu). Does that makes sense ?

**Comment by wongalvis** [comment]
So I need to install both asciidoctor and asciidoctor-backends for preview?

**Comment by Mogztter** [comment]
Yes as described in the instructions:

```
gem install asciidoctor tilt haml thread_safe
gem install slim --version 2.1.0
```

Then clone the `asciidoctor-baclend` repository:

`git clone git://github.com/asciidoctor/asciidoctor-backends.git`

... https://github.com/asciidoctor/asciidoctor-backends#general-usage-instructions

**Comment by wongalvis** [comment]
What are the options available in this command:
$ asciidoctor -T TEMPLATE_DIRECTORY ${options} CONTENT_FILE

**Comment by Mogztter** [comment]
You can read the man page of the asciidoctor command line: http://asciidoctor.org/man/asciidoctor/

The important part for you is `-T TEMPLATE_DIRECTORY`.

 * Duplicate the folder `slim/html5` to `slim/custom-html5`
 * Type the following command in the  `asciidoctor-backends` folder: `asciidoctor -T slim/custom-html5 test.adoc`

**Comment by wongalvis** [comment]
What would be the slim templates that I need to change to implement the multi-level push menu?
I'm a little confused with the huge list of .slim files.

**Comment by wongalvis** [comment]
@Mogztter Any way I could get/compile a list of headings from another .adoc file?
E.g. The multi-level push menu contains a back button which leads to the list of headings of index.adoc, it also contains links to other pages with a list of headings of their own. How could it be achieved?

**Comment by Mogztter** [comment]
> Any way I could get/compile a list of headings from another .adoc file?

I don't know is this is possible... 

> E.g. The multi-level push menu contains a back button which leads to the list of headings of index.adoc, it also contains links to other pages with a list of headings of their own. How could it be achieved?

So "other pages" are included in `index.adoc` ? If this is the case you can just use section level 1 as the first level of the push menu, section level 2 as the second level.... no ?

**Comment by wongalvis** [comment]
Originally the structure is like this
index.adoc
page1.adoc
page2.adoc

That might be a solution to include everything into index.adoc.

**Comment by wongalvis** [comment]
@Mogztter Is it possible to include a js file in the template?

**Comment by Mogztter** [comment]
yes you can do that but you can also use docinfo depending on what you are trying to achieve http://asciidoctor.org/docs/user-manual/#docinfo-file

**Comment by wongalvis** [comment]
Where could I find the codes corresponding to generating the toc items in the template files?

**Comment by jirutka** [comment]
@wongalvis Take a look at the table of nodes [here](https://github.com/asciidoctor/asciidoctor-doctest/blob/master/README.adoc#examples).

**Comment by wongalvis** [comment]
For instance if I want to achieve this:
<div class="toc2" id="toc">
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a href="#_introduction">1. Introduction</a></li>
<li>
  <a href="#_installation_guide"> Installation Guide</a>
  <div class="mp-level"> <----- Adding this div
  <ul class="sectlevel2">
    <li><a href="#_setup_production_environment">Setup production environment</a></li>
    <li><a href="#_setup_development_environment">Setup development environment</a></li>
    <li><a href="#_other_ways_to_setup_initial_environment">Other ways to setup initial environment</a></li>
  </ul>
</div>
...
How could I achieve this?

**Comment by jirutka** [comment]
@wongalvis Then you must modify [block_outline.html.slim](https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_outline.html.slim).

**Comment by wongalvis** [comment]
@jirutka I'll take a look at that thank you. :)

**Comment by wongalvis** [comment]
Is it possible to have x.x.x sections?
So far I can only see x.x sections in my sample .adoc, i.e.
1
 1.1
 1.2
but not
1
 1.1
  1.1.1

**Comment by wongalvis** [comment]
^ I've successfully performed testing on more than 2-levels menu.

**Comment by mojavelinux** [comment]
> Is it possible to have x.x.x sections in the table of content?

You can set the number of toc levels using the `toclevels` attribute. See http://asciidoctor.org/docs/user-manual/#levels

**Comment by mojavelinux** [comment]
Is there any other information you need to proceed?

Btw, you can access the sections of another document (and it's blocks, for that matter) using the AST.

```
require 'asciidoctor'

doc = Asciidoctor.load_file 'document.adoc', safe: :safe
sections = doc.find_by context: :section
```

`find_by` is quite powerful. See http://www.rubydoc.info/gems/asciidoctor/Asciidoctor/AbstractBlock#find_by-instance_method

**Comment by wongalvis** [comment]
I see that is really useful and powerful.
My work has been published for almost a month. You can check it out here https://github.com/taigaio/taiga-doc

**Comment by mojavelinux** [comment]
Very, very cool. It would be good to mention this either in "who's using Asciidoctor" (see https://github.com/asciidoctor/asciidoctor.org/issues/270) or on the upcoming page of third-party extensions (see https://github.com/asciidoctor/asciidoctor.org/pull/372).

**Comment by wongalvis** [comment]
Cool, thank you so much for your help and appreciation. :)

**Comment by mojavelinux** [comment]
You're welcome! I really like the work you've done.
