### ISSUE TITLE
`:source-highlighter: Coderay coderay` syntax is not always understood  

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor#1290]
The attribute `:source-highlighter: Coderay coderay` defined in a document preamble is not understood by backend html5. 

Curiously the command line attribute works:

  `asciidoctor -a  source-highlighter=coderay my.adoc`

**Comment by mojavelinux** [comment]
Could you supply an example of when it doesn't work. Preferable link to a document somewhere (such as a gist) so that I can try it locally and hopefully create a test from it. Thanks!

**Comment by getreu** [comment]
"""
= Secure Computer Cluster Administration with SSH 
Jens Getreu
v1.0, 7.3.2014
:toc:
:numbered:
:source-language:  bash
:icons: font

ifeval::["{backend}" == "docbook5"]
:isdocbook:
endif::[]

ifeval::["{backend}" == "html5"]
:source-highlighter: Coderay coderay
//workabound: there is no bash backend in coderay
:source-language:  python
endif::[]

.Debug
Asciidoctor version: {asciidoctor-version} +
Backend: {backend} +
Source highlighter: {source-highlighter} +
Source language: {source-language}


. Append the local public key to remote `authorized_keys` files.
[source]
$ sshpass -f remotePasswordFile parallel-ssh -I -A -l root -h hostlist "cat - >> /root/.ssh/authorized_keys;chmod 600 /root/.ssh/authorized_keys" < ~/.ssh/id_rsa.pub
"""

#### asciidoctor secure_computer_cluster_administration_with_ssh adoc 

![asciidoctor secure_computer_cluster_administration_with_ssh adoc html](https://cloud.githubusercontent.com/assets/579082/6550186/887e37cc-c62a-11e4-9e5a-25606a80594c.png)

#### asciidoctor -a source-highlighter coderay secure_computer_cluster_administration_with_ssh adoc 

![asciidoctor -a source-highlighter coderay secure_computer_cluster_administration_with_ssh adoc html](https://cloud.githubusercontent.com/assets/579082/6550129/71a483b8-c629-11e4-9b9b-456f0cd77287.png)

#### asciidoctor -b docbook secure_computer_cluster_administration_with_ssh .adoc

![asciidoctor -b docbook secure_computer_cluster_administration_with_ssh pdf](https://cloud.githubusercontent.com/assets/579082/6550205/18e0f3c2-c62b-11e4-90b0-c5393e4458ae.png)

**Comment by getreu** [comment]
btw: With the asciidoctor firefox plugin the above file is rendered correctly *with* syntax highlighting!

**Comment by mojavelinux** [comment]
:source-highlighter: Coderay coderay


This line should simply be:

:source-highlighter: coderay

I'm curious as to why you have "Coderay" written twice. Is that written in
the documentation somewhere? If so, we'll want to get that fixed.

-Dan


-- 
Dan Allen | http://google.com/profiles/dan.j.allen

**Comment by getreu** [comment]
Ok, I sent you pull request #363 for the documentation. *But it is still not working.* I changed the code to ``:source-highlighter: coderay``.
'''
= Secure Computer Cluster Administration with SSH
Jens Getreu
v1.0, 7.3.2014
:toc:
:numbered:
:source-language:  bash
:icons: font

ifeval::["{backend}" == "docbook5"]
:isdocbook:
endif::[]

ifeval::["{backend}" == "html5"]
:source-highlighter: coderay
//workabound: there is no bash backend in coderay
:source-language:  python
endif::[]

.Debug
Asciidoctor version: {asciidoctor-version} +
Backend: {backend} +
Source highlighter: {source-highlighter} +
Source language: {source-language}

. Append the local public key to remote `authorized_keys` files.
[source]
$ sshpass -f remotePasswordFile parallel-ssh -I -A -l root -h hostlist "cat - >> /root/.ssh/authorized_keys;chmod 600
/root/.ssh/authorized_keys" < ~/.ssh/id_rsa.pub
'''

#### asciidoctor Secure_Computer_Cluster_Administration_with_SSH
![asciidoctor secure_computer_cluster_administration_with_ssh adoc html](https://cloud.githubusercontent.com/assets/579082/6552503/2ec5345e-c64f-11e4-8e38-0f76e8528050.png)


#### asciidoctor -a source-highlighter=coderay Secure_Computer_Cluster_Administration_with_SSH.adoc
![asciidoctor -a source-highlighter coderay secure_computer_cluster_administration_with_ssh adoc html](https://cloud.githubusercontent.com/assets/579082/6552509/38726fb2-c64f-11e4-9583-862e81c1f777.png)


#### Rendered with Chrome-plugin
![rendered with chrome-plugin](https://cloud.githubusercontent.com/assets/579082/6552512/3f4a5f20-c64f-11e4-9b88-c220265d3273.png)

**Comment by mojavelinux** [comment]
I can see where this was confusing in the user guide. I reworked the section to make it more clear which values should be used. See https://github.com/asciidoctor/asciidoctor.org/commit/dfb46e0aed772cb9bf2df79b126667619e6eef01.

**Comment by mojavelinux** [comment]
You can't use the coderay or pygments syntax highlighters when using Asciidoctor.js (which is any of the browser plugins). For those, you have to use highlightjs or prettify. The Chrome plugin highlights by default, so you don't have to enable it. The Firefox addon lags behind a bit and doesn't yet have the necessary logic yet to deal with the scenario when the document calls for the use of the coderay highlight. That needs to be filed as an issue against the firefox addon.

**Comment by getreu** [comment]
Maybe we could add a column to indicate which highlighter can be used with Asciidoctor and Asciidoctor.js. Thank you for explaining. 

There is still one issue. Please look at the picture: 
``asciidoctor Secure_Computer_Cluster_Administration_with_SSH.adoc`` (image 2, underlined in red). I still do not understand why this is not highlighted even though the attribute is set to: 
``:source-highlighter: coderay``

As you can see on the following screen-shot (image 3): when the same attribute is set on the command-line, the highlighting is rendered correctly.

**Comment by mojavelinux** [comment]
> Maybe we could add a column to indicate which highlighter can be used with Asciidoctor and Asciidoctor.js. Thank you for explaining.

Good idea!

> As you can see on the following screen-shot (image 3): when the same attribute is set on the command-line, the highlighting is rendered correctly.

That's just because the syntax highlighters behave differently. Usually, it's not noticeable, like with Java snippets. But there's no clear definition for syntax highlighting commandline prompts, so you get widely varied behavior here. In general, I don't recommend writing commandline prompts as a syntax language since coloring them isn't necessarily expected nor does it make sense to a lot of people.

**Comment by mojavelinux** [comment]
Aha! I see what it is. You are setting `source-highlighter` in the document, but not in the document header. Attributes which affect the document template must be defined in the document header. The `source-highlighter` is one of those attributes. The blank lines in your document before the ifeval statements separate the attributes in the header from the attributes in the document.

I'll clarify this in the docs as well.

**Comment by mojavelinux** [comment]
If this issue is resolve, give me the thumbs up.

**Comment by getreu** [comment]
:) Yes! This explains why the same option worked given on the command line. Thank you!
I think it is a good idea to mention this in the doc. Is there a list somewhere with commands that only work in the preamble? It would be helpful also if those commands when not correctly placed and thus ignored would generate an error or warning. (-> future enhancement?)

I think we can close this issue, or we rename it and file it under enhancement. 

I have a last practical question: 
I use the browser plugin and the html5 and docbook backend in parallel. What could I write for <browser plugin>?

"""
ifeval::["{backend}" == "html5"]
:source-highlighter: coderay     // render html5 with asciidoctor
endif::[]
ifeval::["{backend}" == "<browser plugin>"]
:source-highlighter: highlightjs  // render in browser plugin
endif::[]
"""

**Comment by mojavelinux** [comment]
> I think it is a good idea to mention this in the doc.

I have made this clear in the source highlighter section.

> Is there a list somewhere with commands that only work in the preamble?

I filed it as https://github.com/asciidoctor/asciidoctor.org/issues/369

> It would be helpful also if those commands when not correctly placed and thus ignored would generate an error or warning.

Maybe, maybe not in the core tool. The problem is, there are a seemingly endless number of these types of validations. I would prefer for developer or analysis tools to do this type of work (think an IDE or code linter). Technically it's not wrong to define the attributes this way. The current backends just aren't going to interpret them in those locations. But a backend could in theory support it.

> I use the browser plugin and the html5 and docbook backend in parallel. What could I write for <browser plugin>?

The browser plugin highlights by default (or you can set it in the plugin options pages). Therefore, I would limit what is in your document to:

```
ifdef::backend-html5[]
:source-highlighter: coderay
endif::[]
```

Personally, though, I would always pass the source-highlighter value through using the command or build tool and not put it in the document. I usually just put in the document temporarily when I first create a document or for a one-off document.

**Comment by getreu** [comment]
On 01/04/15 20:10, Dan Allen wrote:
> Personally, though, I would always pass the source-highlighter value
> through using the command or build tool and not put it in the document.
> I usually just put in the document temporarily when I first create a
> document or for a one-off document.

What you say makes sense. A purist asciidoc document should contain only
document semantic related markup.

I come from LateX. Here you commonly include all build dependencies in
the document header.

I will adopt your approach.

**Comment by mojavelinux** [comment]
:+1:
