### ISSUE TITLE
footnotes are not superscript

### ISSUE THREAD

**Issue by akostadinov** [asciidoctor/asciidoctor#1294]
I'm putting footnotes like `footnote:[...]`. Issue is that HTML generated by asciidoctor gem 0.1.4 does not set the reference `[12]` as superscript but as the regular text size. While asciidoctor.js is making these references in superscript.
If I put `^` around footnote, then ruby gem makes it superscript but asciidoctor.js shows additional ugly `^` chars around the reference like `^[12]^`.

Can we put these two in tune? I'm using asciidoctor.js through the firefox plug-in.

**Comment by mojavelinux** [comment]
They should be appearing in superscript if you use the `asciidoctor` command. However, the styling does depend on the stylesheet, so if the stylesheet is missing or changed, you could get different results.

It does make me wonder if we should use the `<sup>` tag for the footnote number so that it renders better on GitHub where the stylesheet is absent.

**Comment by akostadinov** [comment]
+1, or maybe option for inline stylesheet? It's very useful to be able to attach an html file to email and have everything self-contained. PDF can also be attached but most email clients show html attachments as part of the message and there is no need to open in external program.

**Comment by mojavelinux** [comment]
The stylesheet is included inline by default. You can also add images inline by adding the `data-uri` attribute to the header or passing to the cli.

**Comment by akostadinov** [comment]
Then why do ruby and js behave differently?

**Comment by mojavelinux** [comment]
I don't know. I'm not seeing a difference. Can you provide a bit of sample AsciiDoc and take a screenshot of the output so that I can investigate further? Thanks!

**Comment by jirutka** [comment]
@mojavelinux, he's using asciidoctor 0.1.4, that may be the problem...

**Comment by mojavelinux** [comment]
Perhaps. Though even in 0.1.4 they are superscript, so I'm not sure if that's it.

**Comment by akostadinov** [comment]
I think I see what's going on. I'm doing this:
```
[2] pry(main)> Asciidoctor::VERSION
=> "1.5.2"
[4] pry(main)> File.write("/tmp/test.html",Asciidoctor.load(File.read("/tmp/test.adoc")).render(:header_footer => true))
asciidoctor: WARNING: <stdin>: line 3: section title out of sequence: expected level 1, got level 2
=> 1252
```
The resulting document is correct html but CSS is not embedded. I'm using this way to render the file because older asciidoctor as coming with fedora 20 do not seem to support other ways. But I can't find a way to embed the css. Or is my only option to update all our jenkins slaves?

**Comment by mojavelinux** [comment]
Ah, this is an easy fix. When you use the API, you must set the safe mode (or else you get different behavior). Set the safe mode to `:safe` using:

```
Asciidoctor.render_file '/tmp/test.adoc', safe: :safe, in_place: true
```

(Note that in 1.5.0, `in_place: true` changed to `to_file: true`)

It automatically writes the file to the file system with header_footer enabled and CSS embedded. Notice how I used Asciidoctor to do all the steps you were doing. For more info, see:

http://www.rubydoc.info/gems/asciidoctor/0.1.4/Asciidoctor#render_file-class_method

(I linked to 0.1.4 since you said you were using that version).

**Comment by akostadinov** [comment]
Thank you. I'm actually having the adoc content in memory so I found this works in `0.1.4` (embedded css, footnotes are superscript, etc.):
```
Asciidoctor.render(report, :safe => :safe, :to_file => "/tmp/test.html")
```

But the same does not work in v 1.5.2 (`report` is a String):
```
[9] pry(main)> Asciidoctor.render(report, :safe => :safe, :to_file => "/tmp/test.html")
IOError: target directory does not exist: 
from /home/avalon/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1489:in `convert'
```
The above is raised no matter if the target file exists or not. Also trying this does not help:
```
[10] pry(main)> Asciidoctor.render(report, :safe => :safe, :to_dir => "/tmp", :to_file => "test.html")
IOError: target directory does not exist: /tmp
from /home/avalon/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1489:in `convert'
[11] pry(main)> Asciidoctor.render(report, :safe => :safe, :to_dir => "/tmp/", :to_file => "test.html")
IOError: target directory does not exist: /tmp/
from /home/avalon/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1489:in `convert'
```

It would be nice if this part of the API is better documented. I've read about `:safe` and other documentation but couldn't figure it out.

**Comment by akostadinov** [comment]
Ok, now I figured:
```
Asciidoctor.render(report, :safe => :unsafe, :to_file => "/tmp/test.html")
```
I guess defaults changed. I'm generating the adoc in my script, so I don't need to use safety options. I guess safe mode prevent careless devs to generate files in user selected paths.

**Comment by mojavelinux** [comment]
> IOError: target directory does not exist: /tmp

You may need to add:

```
mkdirs: true
```

It's a good idea to always set this option when using the API and writing to a fixed / known place.

> I guess defaults changed.

...or bugs got fixed and behavior that shouldn't have worked stopped working.

> I'm generating the adoc in my script, so I don't need to use safety options.

The safety options are primarily to prevent user-based content from causing problems, mostly around reading files (e.g., `include::/etc/passwd[]`). So you should be good.

> It would be nice if this part of the API is better documented. 

It's on my list for sure. I'm well aware we need to improve in this area.

**Comment by mojavelinux** [comment]
I think I'm going to open a follow-up issue to use `<sup>` for the footnote marks so that they render as superscript even when the CSS is absent...just because that seems to make more sense (and will work on GitHub).
