### ISSUE TITLE
When a url ends with a slash, url[link_name] is not properly rendered (is not an active  link)

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1295]
Example: http:://bar.room.com/[Bar room site]

**Comment by mojavelinux** [comment]
Hey Jim. It appears the problem is that you have two colons after `http`. If I remove one of them, it seems to work fine. Can you confirm?

**Comment by jxxcarlson** [comment]
Hi Dan,

  Sorry for the typo — I did some further
experimentation.  The below works find
with both Asciidoctor and Asciidoctor-LaTeX
with the HTML backend.  So it is a Noteshare
problem.  The second example misbehaves.

I do some preprocessing and post processing
to avoid some problems and this is likely the source
of the trouble.  My bad!!

	http://nytimes.com[New York Times]

	http://nytimes.com/[New York Times]

Best,
Jim

http://noteshare.io

**Comment by mojavelinux** [comment]
Thanks for the clarification Jim. If you need any help working through the issue, just let us know!

**Comment by jxxcarlson** [comment]
Will do, Dan — thanks!

Am leaving for Cuba at the end of the week for vacation
with my wife and son.  Don’t you go to France soon?

Best,
Jim

PS.  A lot of progress on Noteshare.io — I’m sending you a link to the March newsletter:

	http://noteshare.io/section/newlsetter-march-2015

**Comment by mojavelinux** [comment]
Cuba, how exciting!

Oui ! Je vais en France le mois prochain. (Yes! I am going to France next month).
