### ISSUE TITLE
Title Broken With include:: and Callout

### ISSUE THREAD

**Issue by garyrussell** [asciidoctor/asciidoctor#1297]
Consider

index.adoc
````
= Hello

include::./one.adoc[]
include::./two.adoc[]
````
... where one.adoc ends with a callout...

one.adoc
````
== One

This is the first section.

[source, java]
----
public class Foo { <1>

}
----

<1> Class definition

// comment to fix next section
````

two.adoc
````
== Two

This is the second section.
````

The __Two__ title is not rendered without adding the comment to the end of one.adoc (or adding a blank line between the two `include::`s).

    $ asciidoctor --version
    Asciidoctor 1.5.2 [http://asciidoctor.org]
    Runtime Environment (ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
The Asciidoctor project's position on this is that include directives should be separated by a blank line if the contents of the includes are not continuous (e.g., contain discrete sections). This allows for the possibility of combining content that is continuous using includes. In other words, we don't insert a blank line. You should do that in the source as follows:

```
= Hello

include::./one.adoc[]

include::./two.adoc[]
```

An alternative is to use a custom include processor that automatically inserts a blank line at the end of the included content. We have considered making this an option in issue #318. Is that acceptable for you?

**Comment by garyrussell** [comment]
Thanks, I am fine with the requirement of a blank line between includes (in fact, that's what I did to solve the issue). I was just not aware of the requirement.

That said, it now seems a little odd that adding a comment at the end of the previous include "fixes" the problem. Shouldn't comments have no effect on the surrounding formatting?

If an option comes along later, that would be fine too, but I'm ok with adding the blank lines.

Thanks again - I am soooo glad I attended your talk at DevNexus2015 and decided to (finally) take the time to convert my docbooks, as have most Spring projects now.

**Comment by mojavelinux** [comment]
We do mention this scenario in the docs, though admittedly its not easy to find.

http://asciidoctor.org/docs/user-manual/#includes-and-whitespace

> That said, it now seems a little odd that adding a comment at the end of the previous include "fixes" the problem. Shouldn't comments have no effect on the surrounding formatting?

Yes and no. It's not actually the comment that is changing the behavior, but rather the blank line that precedes the comments. Blank lines are often semantic in AsciiDoc, as is the case in this scenario.

> If an option comes along later, that would be fine too, but I'm ok with adding the blank lines.

Sounds good!

> Thanks again - I am soooo glad I attended your talk at DevNexus2015 and decided to (finally) take the time to convert my docbooks, as have most Spring projects now.

I'm thrilled to hear it! It was a pleasure meeting you as well. Best of luck. I'll be here, along with the community, to help you along your journey!

**Comment by mojavelinux** [comment]
I should add that I added an anchor in the docs so now we can link to that recommendation until it finds a better home.

**Comment by mojavelinux** [comment]
We'll address any additional improvements as part of #318.
