### ISSUE TITLE
Block processors not called for blocks inside AsciiDoc table cells

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor#1300]
As described in https://github.com/asciidoctor/asciidoctor-diagram/issues/65, it seems like extensions are not triggered for content inside table cells.
I've tried to reproduce this using the code below, and indeed the block processors are never invoked. What's intriguing in the linked issue though is that if the block is repeated before the table, somehow the block inside the table is being processed as well. Is perhaps something in the backend triggering further processing of nested content?

```
doc = <<-eos
= Hello, PlantUML!
Doc Writer <doc@example.com>

== First Section

[cols="2", width="100%"]
|===
|This host is involved in following relationships
a|
[blockdiag, target='hosts-relationships-0-from', 'png']
----
{
  A <- B -> C -- D <-> E;
}
----
|===
eos

Asciidoctor.load StringIO.new(doc), :attributes => {'backend' => 'docbook5'}
```

**Comment by mojavelinux** [comment]
Very likely that the extensions are not being passed to the nested document. If you recall, AsciiDoc table cells are actually discrete, nested Asciidoctor document objects. It's very possible something is being lost in translation. I even have a note to myself that says I need to fix this...so apparently I knew about it at some point :)

We should probably start with a test and work from there.

**Comment by mojavelinux** [comment]
After looking into this further, I don't think this is an issue at all. Block processors and other extensions do get called inside AsciiDoc table cells. In fact, this works all the way back to 1.5.0.

Here's the example code I used to provide it:

```rb
require 'asciidoctor'
require 'asciidoctor-diagram'

source = <<-EOS
= Hello, PlantUML!
Doc Writer <doc@example.com>

== First Section

[cols="1,4"]
|===
h|Diagram in a table cell
a|
[blockdiag, target=hosts-relationships-0-from, png]
----
{
  A <- B -> C -- D <-> E;
}
----
|===
EOS

# convert to HTML
Asciidoctor.convert source, to_file: 'out.html', safe: :safe

# convert to DocBook
Asciidoctor.convert source, to_file: 'out.xml', backend: 'docbook'
```

What I can say for certain is that preprocessor and tree processor extensions do not get called for AsciiDoc table cells. That's a separate issue.

**Comment by pepijnve** [comment]
Weird. Looking back through the history of this issue (and the original diagram issue) I see that I claimed to be able to reproduce this. No test case unfortunately.

If it ever pops up again I'll reopen. Ok to close for the time being.

**Comment by mojavelinux** [comment]
I added a test case so we'll have something to build on if it comes up again.
