### ISSUE TITLE
sphinx backend of asciidoctor is very important

### ISSUE THREAD

**Issue by zaxebo1** [asciidoctor/asciidoctor#1302]
just like html5, pdf etc; **is there any sphinx backend of asciidoc? So that full asciidoctor syntax document can be converted to sphinx restructred text)**. 

just like, there is a html5 backend,pdf backend for asciidoc; if there is a sphinx backend for asciidoctor, then from the advantages are :  
- the generated sphinx(rst) document - further html and chm and docx and other backends (builders/convertors) of sphinx can be easily used to further process the output.
- **Also, the html generated from that sphinx document will be compatible with the theme of native sphinx.**
- Also that generated sphinx document will be easily be uploadable to readthedocs.org
- **it will be easy to convince people to use asciidoctor also in those organizations, which use sphinx currently as standard tool. Because asciidoctor's sphinx backend will easily integrate in the workflow.**

**Comment by mojavelinux** [comment]
There is no backend for sphinx currently. I agree this would be nice to have. I think it should be developed in the asciidoctor-backends repository or as a separate module (like the LaTeX converter).

**Comment by ciampix** [comment]
Someone is working on an asciidoc input filter for pandoc that should fill in the gap. See: https://github.com/jgm/pandoc/issues/1456

**Comment by FedericoCeratto** [comment]
pandoc is huge. I'd love to see a asciidoc backend to generate HTML docs for Python projects (no need to generate .rst files)

**Comment by mojavelinux** [comment]
Our focus moving forward is Antora (https://antora.org). It's a documentation site generator designed exclusively for AsciiDoc / Asciidoctor. If there are features that Sphinx supports that Antora doesn't, we can discuss and/or address those in the Antora project.

**Comment by ciampix** [comment]
> Our focus moving forward is Antora (https://antora.org). It's a documentation site generator designed exclusively for AsciiDoc / Asciidoctor. If there are features that Sphinx supports that Antora doesn't, we can discuss and/or address those in the Antora project.

It's not clear to me (sorry) where exactly is possible to discuss the missing features of Antora compared to the easier a pretty complete Sphinx project. To name just one "feature" missing in Antora (that is present in Sphinx) that is paramount for me (I'm a translator): multi-language support of platform and (most important) of content, through the use of gettext po files. I am actually working with po4a (see https://www.po4a.org) as a viable solution to make asciidoc(tor) files international but, unfortunately, yet unsupported by Antora.

**Comment by mojavelinux** [comment]
You're welcome to ask questions about Antora in the project chat at https://antora.zulipchat.com. Here's the issue regarding multi-language support: https://gitlab.com/antora/antora/-/issues/208 where you can find more information about the topic. I'm not going to comment on it further in this thread.

**Comment by mkschreder** [comment]
> Our focus moving forward is Antora (https://antora.org). It's a documentation site generator designed exclusively for AsciiDoc / Asciidoctor. If there are features that Sphinx supports that Antora doesn't, we can discuss and/or address those in the Antora project.

This is a rather shortsighted approach. You need to make sure that asciidoc can be used as a drop in replacement for rst and md through sphinx. Sphinx is used today as primary tool for pooling together docsets from several sources written in rst and md and creating one huge site with all docs included - written in different markup languages and using many specific scripts that rely on sphinx. If you focus on antora you would have to reimplement all the support that sphinx already does. It would be much better to simply make adoc usable after adding `source_suffix = [".rst", ".md", ".adoc"]` to a sphinx conf.py so that adoc can start being used for kinds of project documentation tasks for which we today use RST just because sphinx supports it so well.

**Comment by mojavelinux** [comment]
I really don't appreciate you calling my decision to invest my time in Antora shortsighted. I find it insulting and a veiled attempt to coerce me. Antora is the strategy I've decided to pursue. Who are you to tell me I shouldn't? Besides, the Asciidoctor project has nothing to do with Sphinx anyway, which is separate project with a separate code base that we have no control over.

You're free to take your own approach if you think there is a better way. You can join the project chat at https://chat.asciidoctor.org and build interest around developing direct Sphinx integration. However, I expected you to do so with civil discourse, not through insults.
