### ISSUE TITLE
Problem with table heading ending in a pipe

### ISSUE THREAD

**Issue by bmomjian** [asciidoctor/asciidoctor#1306]
With asciidoctor 1.5.2, if the last cell of a table heading ends with a pipe, the rendered HTML assumes the first data row is part of the heading, e.g. this:

    [options="header",cols=">l,<l",frame="none"]
    |====
    ^l|stuff ^l|abc\|X
    |2 |hello\|
    |3 |hello
    |====

yields a correct HTML heading of:

    stuff   abc|X

which is good, but if you remove the "X" from the asciidoc heading, the
HTML output heading is:

    stuff   abc|2

The "X" is gone, but the "2" from the first data row is now in the
heading, and the first and only data row is now:

    hello|3  hello

This sure looks like a bug. Other asciidoc rendering systems do not do this, e.g. https://asciidoclive.com/ . More details can be found here:

 http://discuss.asciidoctor.org/Problem-with-table-heading-ending-in-a-pipe-tp2902p2916.html

**Comment by mojavelinux** [comment]
Thanks for filing the issue Bruce. I'll try to address it for 1.5.3.

**Comment by mojavelinux** [comment]
It turned out that this affected all cells, not just cells in the header row. The escaped delimiter was being detected, then inadvertently dropped. It is now properly preserved and a test added.

**Comment by bmomjian** [comment]
On Fri, Oct  9, 2015 at 10:53:37PM -0700, Dan Allen wrote:
> It turned out that this affected all cells, not just cells in the header row.
> The escaped delimiter was being detected, then inadvertently dropped. It is now
> properly preserved and a test added.

Great, thanks.

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I. As I am, so you will be. +
+ Roman grave inscription                             +
