### ISSUE TITLE
Support for referencing chapter numbers

### ISSUE THREAD

**Issue by dennislaumen** [asciidoctor/asciidoctor#1308]
I can't seem to find how to reference chapter numbers. It is possible to reference chapter titles like this `<<Chapter Title>>`. What would be really great if it were possible to reference a chapter and display its number, or the word "chapter" and its chapter number, automatically. Does anyone know if this is possible? If it isn't possible, please consider this issue a feature request!

Thanks for the awesome toolchain!

**Comment by mojavelinux** [comment]
This is not currently possible in the built-in backend. We are discussing something similar in the following issue #858 (so this may already be covered by an existing feature request).

Keep in mind you can customize any of the output using custom backend templates or a custom converter. Most people prefer to customize the HTML using the templates. See https://github.com/asciidoctor/asciidoctor-backends

**Comment by dennislaumen** [comment]
Ah, that's a shame! We'll look into the alternative you mentioned. Thanks for the quick reply @mojavelinux!
