### ISSUE TITLE
Support tabsize attribute

### ISSUE THREAD

**Issue by rwinch** [asciidoctor/asciidoctor#1309]
It would be nice if Asciidoctor supported the tabsize attribute defined in Asciidoc. See http://www.methods.co.nz/asciidoc/userguide.html#_tabs

**Comment by mojavelinux** [comment]
I think we've already got this one scheduled for 1.5.3. Does #1170 cover it?

**Comment by rwinch** [comment]
@mojavelinux Thanks for the fast reply! That seems like it would resolve my functional need. Thank you.

I'm wondering though that given the fact that asciidoc's attribute is named tabsize if asciidoctor's attribute name should be the same. Thoughts?

**Comment by mojavelinux** [comment]
Agreed. I added a comment to this effect on #1170.

I'm going to close as a duplicate.

**Comment by rwinch** [comment]
Thanks!
