### ISSUE TITLE
Tilt not being required when manipulating options without CLI

### ISSUE THREAD

**Issue by S0lll0s** [asciidoctor/asciidoctor#1313]
When I build an Invoker from a custom `::Cli::Options` object Tilt won't be require'd.

For example this will fail:

    options = Asciidoctor::Cli::Options.parse! ARGV
    options[:template_dirs] = ['templates/']
    invoker = Asciidoctor::Cli::Invoker.new options
    invoker.invoke!

but this is a bit ugly:

    ARGV << "-T"
    ARGV << "templates/"
    invoker = Asciidoctor::Cli::Invoker.new ARGV
    invoker.invoke!

**Comment by mojavelinux** [comment]
Why not just require tilt?

```
require 'tilt' unless defined? ::Tilt
```

If you want the error message, then you have to follow your approach. If you can think of a way to improve the API, suggestion are welcome. However, the invoker isn't really designed as a public API, so using it requires these types of hacks atm (I have a similar comment in the code for the invoker for Asciidoctor PDF).

**Comment by S0lll0s** [comment]
Well, it might make sense to move the "require tilt" out of the Options API and into the invoker; that way modifying the options object always has the inteded effect.

**Comment by mojavelinux** [comment]
That's reasonable, I think. I would propose also moving the load paths and requires as well, since these are all related.

**Comment by mojavelinux** [comment]
I'm going to move forward with having the template converter automatically load tilt (since it also handles loading slim and erb). I'm going to handle the requires and load paths as a separate issue.
