### ISSUE TITLE
ASCIImage support

### ISSUE THREAD

**Issue by nikolay** [asciidoctor/asciidoctor#1317]
It would be nice to have [ASCIImage](http://asciimage.org/) as an extension similar to the diagramming one.

There's a Ruby-based library already: https://github.com/Oblomov/asciimage-ruby

**Comment by jirutka** [comment]
+1

**Comment by mojavelinux** [comment]
We could integrate it as part of Asciidoctor Diagram. Just looks to be another format, yes? If so, I encourage you to file a feature enhancement in Asciidoctor Diagram. https://github.com/asciidoctor/asciidoctor-diagram

**Comment by nikolay** [comment]
@mojavelinux Thanks! I thought of creating it here to expose the feature request to a broader audience.

**Comment by mojavelinux** [comment]
Thanks!
