### ISSUE TITLE
Upgrade icons to use Font Awesome 4.3.0

### ISSUE THREAD

**Issue by tedbergeron** [asciidoctor/asciidoctor#1318]
update code: 
https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L74
to use latest version:
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by mojavelinux** [comment]
Note that you can control the URL used for Font Awesome by setting the following attribute in the document header (or by passing the attribute to the cli or API).

```
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
```

(This probably needs to be documented).

**Comment by lordofthejars** [comment]
Yes so useful attribute
El dl., 4 de maig, 2015 a les 21.37 Dan Allen <notifications@github.com> va
escriure:
