### ISSUE TITLE
Include directive with multiple line ranges is broken

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor#1322]
As mentioned on the [mailing list](http://discuss.asciidoctor.org/Include-directive-by-line-range-with-multiple-ranges-not-working-tp3056.html), I think that the include directive working with multiple line ranges is broken.

I am using the [Include directive by line ranges described in the User Manual](http://asciidoctor.org/docs/user-manual/#by-line-ranges).

Set-up to reproduce my test:

1) Create a first document `lines.txt`:

    line one
    line two
    line three
    line four
    line five
    line six
    line seven
    line eight
    line nine
    line ten
    line eleven
    line twelve
    line thirteen
    line fourteen
    line fifteen
    line sixteen
    line seventeen
    line eighteen
    line nineteen

2) In a second asciidoc document (`document.adoc`):

```asciidoc
Test Multiple ranges:

[source]
----
include::lines.txt[lines=4..5,10..12]
----
```

Expected output:

    Test Multiple ranges:
    
    line four
    line five
    line ten
    line eleven
    line twelve

I got only the first range:

    Test Multiple ranges:
    
    line four
    line five

My current workaround is to repeat the include directive in the asciidoctor document:

```asciidoc
Test Multiple ranges:

[source]
----
include::lines.txt[lines=4..5]
include::lines.txt[lines=10..12]
----
```

**Comment by jmini** [comment]
As [mentioned by mojavelinux](http://discuss.asciidoctor.org/Include-directive-by-line-range-with-multiple-ranges-not-working-tp3056p3074.html)  on the Mailing list, it works with `;` instead of `,`

```asciidoc
Test Multiple ranges:

[source]
----
include::lines.txt[lines=4..5;10..12]
----
```

**Comment by mojavelinux** [comment]
@jmini, would you be willing to update this file?

https://github.com/asciidoctor/asciidoctor.org/blame/master/docs/_includes/ex-include.adoc#L26

The value needs to be quoted or semi-colons need to be used. I propose the following text to add as well.

> When including multiple line ranges or multiple tags, the individual values can be separated either by a comma or a semi-colon. If commas are used, then the entire attribute value must be enclosed in quotes. Using the semi-colon as the data separator alleviates this requirement.

wdyt?
