### ISSUE TITLE
vim-asciidoc folds break: 'E490: No fold found'

### ISSUE THREAD

**Issue by johnnyutahh** [asciidoctor/asciidoctor#1325]
How can I get vim folding to work in asciidoc content?

vim-asciidoc ( https://github.com/mjakl/vim-asciidoc ) version http://bit.ly/1c4jY7p (I just installed it earlier today) prints 'E490: No fold found' in red-backgrounded-font in bottom-left corner of my MacVim 7.4 when I press the space bar on any asciidoc-based text file I've tried, including the one below (copied from http://asciidoctor.org front page). 

Markdown-based folding works just fine, just like shown here: http://vimcasts.org/episodes/how-to-fold. I'm running MacOS 10.9.5.

(I'd post this issue to vim-asciidoc, but it appears to have no 'issues' section.)

    // vim: set syntax=asciidoc:
    = Hello, AsciiDoc!
    Doc Writer <doc@example.com>
    An introduction to http://asciidoc.org[AsciiDoc].
    == First Section
    * item 1
    * item 2
    [source,ruby]
    puts "Hello, World!"

**Comment by johnnyutahh** [comment]
Additional info. I had a previous asciidoc vim highlighter (I significantly used asciidoc prior to the advent of a mature asciidoctor) that I attempted to Vundle remove, to make sure it wasn't conflicting. Same symptoms. I've also tried https://github.com/matcatc/vim-asciidoc-folding with no success, although I suspect I may not have installed/configured the latter correctly.

Basic question: is folding working (or not working?) for everyone else?

In the meantime, I've run out of time to tinker for tonight, and I need to get back to editing my document. As a workaround, I'm temporarily converting my asciidoc section headers to markdown ('=' to '#') to enable markdown-based folding and editing, and then back to asciidoc before publishing. Slightly tedious, but folding+editing for larger documents is just too valuable.

I'm happy to provide any additional info upon request, including .vimrc, .vim/bundle dirs/files, etc.

**Comment by mojavelinux** [comment]
To my knowledge, folding has never been implemented in the AsciiDoc language support for vim. Then again, there are several solution floating around the internet, so I'm not sure what state any of them are in. It's certainly not in the official plugins for AsciiDoc that ship with vim to my knowledge.

This is very useful information for moving this feature request forward, except we are not maintaining the vim support for AsciiDoc in Asciidoctor, so there's no code here to change.

The best thing is to continue moving the discussion forward about setting up an official repository for AsciiDoc support in vim. We got close to setting up an official repository, but the thread has stalled. See https://groups.google.com/d/msg/asciidoc/R8skrs2aWxU/6bFfJj4BVB8J.

>  I'm temporarily converting my asciidoc section headers to markdown ('=' to '#') to enable markdown-based folding and editing, and then back to asciidoc before publishing.

You could just continue using the `#` symbol for headings as they are supported in Asciidoctor.

**Comment by mojavelinux** [comment]
I recommend proceeding by posting to the AsciiDoc google groups list. You could repost your findings reported in this issue.

https://groups.google.com/forum/#!forum/asciidoc

**Comment by johnnyutahh** [comment]
The `#` symbol support for headings in Asciidoctor solves the biggest, initial problem - thanks Dan / @mojavelinux (!).

Separately: the `[id='']` lines immediately prior to the section-title/heading lines present another challenge, that I detail here:  http://stackoverflow.com/q/30019414/605356.  Any help on that matter is (of course) appreciated.

Thanks again.

**Comment by mojavelinux** [comment]
Glad you got it working.

Again, this isn't source repository for the vim AsciiDoc support and I'm not actively working on it. It's best if we can move forward with getting an official vim asciidoc repo setup and then pursue the issue there.

**Comment by johnnyutahh** [comment]
On 5/3/15, 4:26 PM, Dan Allen wrote:
> Again, this isn't source repository for the vim AsciiDoc support and 
> I'm not actively working on it. It's best if we can move forward with 
> getting an official vim asciidoc repo setup and then pursue the issue 
> there.

As mentioned above, I would have posted this thread to 
https://github.com/mjakl/vim-asciidoc (the most-popular repo I've seen 
referenced elsewhere at asciidoctor community, I think) if it supported 
github-Issues, but it doesn't. At the time I didn't know where else to 
go. You've also pointed me to an asciidoc google group - noted.

I posted my only remaining, open question to stackoverflow.com, so we 
can deem that matter diverted from this thread.

Dan, does the above enable you to "close" this thread/issue/topic on 
https://github.com/asciidoctor/asciidoctor ?

**Comment by mojavelinux** [comment]
>  I would have posted this thread to https://github.com/mjakl/vim-asciidoc (the most-popular repo I've seen referenced elsewhere at asciidoctor community, I think) if it supported github-Issues, but it doesn't. 

I don't consider that to be an official vim asciidoc support. The official file is maintained currently in the main AsciiDoc Python repository. You can file an issue there: https://github.com/asciidoc/asciidoc. A more recently updated repository is here: https://github.com/dahu/vim-asciidoc.

I'll go ahead and close it here, though your report has further justified why we need an official repo. I'll add it to my list to push for that happen.

**Comment by mojavelinux** [comment]
The official vim-asciidoc now exists.

https://github.com/asciidoc/vim-asciidoc
