### ISSUE TITLE
image:: fails in some environments

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1327]
The image tag seems to work in the definition part of a defiinition list or inside a table.  See the exmaple below.  Sorry for the ridiculously long URLS, but that is what I have. In real life, one writes, say, `image::456[]` . Noteshare then looks up the URL for this image in its database and makes the substiution.  There is no problem if there is whitespace before and after the image tag. I get the same
results using `image::sunset.jpg[width=80]` throughout.

*Example*
```
(1)

image::http://s3.amazonaws.com/vschool/images/data/000/000/586/original/Screen_Shot_2015-05-02_at_10.24.36_PM.png?1430576780[]


(2)

image::http://s3.amazonaws.com/vschool/images/data/000/000/586/original/Screen_Shot_2015-05-02_at_10.24.36_PM.png?1430576780[] :: Ooops!

(3)

image::http://s3.amazonaws.com/vschool/images/data/000/000/586/original/Screen_Shot_2015-05-02_at_10.24.36_PM.png?1430576780[] Ooops!

(4)

|===
|A | B
|C | D
|===

(5)

|===
| image::http://s3.amazonaws.com/vschool/images/data/000/000/586/original/Screen_Shot_2015-05-02_at_10.24.36_PM.png?1430576780[] Ooops!
 | B
|C | *Oooops!*
|===
```

**Comment by mojavelinux** [comment]
(5) happens because you need to add an "a" in front of the table cell delimiter (to make it an AsciiDoc table cell). You can't use block-level elements in a table cell unless you prefix the table cell delimiter with "a".

**Comment by mojavelinux** [comment]
For (2) and (3), you need to use the inline image macro (one colon, not two) since the image is inline with other text.

Hopefully that solves you problems, yes?
