### ISSUE TITLE
Update MathJax to 2.5.x

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1329]
Update MathJax from 2.4.0 to 2.5.x (whatever x is).

**Comment by jxxcarlson** [comment]
Yay !

**Comment by mojavelinux** [comment]
We need to come up with a good test file for MathJax so that we can look for changes. Eventually, we can automate it, but first we need a concise example document that hits various corner cases.

**Comment by mojavelinux** [comment]
What I notice when upgrading from 2.4.0 is that the kerning seems to have gotten better. However, I have noticed that brackets around multi-line formulas are no longer grow to match the height of the formula. Instead, they are just the height of a single line.
