### ISSUE TITLE
Add CodeMirror support for syntax highlighting

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctor#1331]
This would improve consistency when writing documentation for an application which uses CodeMirror in its user interface.

**Comment by Hocdoc** [comment]
+1 (see also https://groups.google.com/forum/#!topic/codemirror/9FI4lrq_JdU )

**Comment by mojavelinux** [comment]
As of Asciidoctor 2.0, this is now possible using the new syntax highlighter API. This should be done as an extension. It can be published and shared as a RubyGem.

Here's the API you need to use: https://www.rubydoc.info/gems/asciidoctor/2.0.0/Asciidoctor/SyntaxHighlighter

Here's an example that shows how to use the API to integrate Prism: https://gist.github.com/mojavelinux/850373bb1b5a8e0334b4038e90617509

**Comment by mojavelinux** [comment]
I see that this request could also be interpreted as the other way around. To add AsciiDoc syntax highlighting in CodeMirror. That can be found here: https://github.com/asciidoctor/codemirror-asciidoc
