### ISSUE TITLE
:numbered: enhancement?

### ISSUE THREAD

**Issue by craibuc** [asciidoctor/asciidoctor#1332]
This content:

    = Lorem Ipsum
    :doctype: book
    :toc: left
    :toclevels: 3
    :numbered:

    == Chapter One
    
    === A
    :numbered!:
    ==== Foo
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
    ==== Bar
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
    ==== Baz
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
    :numbered:
    === B
    :numbered!:
    
    ==== Foo
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
    ==== Bar
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.

    ==== Baz
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
    :numbered:

Generates:

    Table of Contents

    1. Chapter One
    
        1.1. A
            Foo
            Bar
            Baz
        1.2. B
            Foo
            Bar
            Baz

While working, constantly enabling and disabling the numbering is a bit of a hassle.  Is there a better way (other than just adding the number to the H3)?  

It would be nice to supply the desired levels to the `:numbered:` attribute:
 -  `:numbered: 1-2` - levels 1 and 2 only
 -  `:numbered: 2` - level 2 only

**Comment by mojavelinux** [comment]
> It would be nice to supply the desired levels to the :numbered: attribute:

That's an interesting proposal. Similar to `toclevels` in a way. Could be related to the one for controlling numbering of special sections globally: #661.

**Comment by mojavelinux** [comment]
To answer your question directory, there is currently no other way to control section numbering from the document itself. Of course, if you start hacking on the API, then the sky is the limit ;)

**Comment by mojavelinux** [comment]
Wow, I totally forgot that there is an attribute to control the depth of section numbering. Just set the `sectnumlevels` attribute. The default value is 3. Does that provide the control you were looking for?

**Comment by craibuc** [comment]
That addressed my needs.  Is there any documentation on this?  I didn't see it.  Does it accept a range (`:sectnumlevels: 1-2`) or delimited list `:sectnumlevels: 2,3-4`?

**Comment by mojavelinux** [comment]
I filed an issue for it to be documented here:

https://github.com/asciidoctor/asciidoctor.org/issues/383

The value is a max section depth of numbering. Thus, if you want levels 1 and 2 to be numbered, specify:

```
:sectnumlevels: 2
```

There is no range capability atm. Thus, you can't skip levels and it numbers from the top level to the specified depth.

**Comment by mojavelinux** [comment]
I'm closing now that we have a documentation issue opened.
