### ISSUE TITLE
latexmath - rendering extra parenthesis in output.html

### ISSUE THREAD

**Issue by arnaldorusso** [asciidoctor/asciidoctor#1334]
Hi
While I'm rendering math equations inside .adoc,

    Inline teste latexmath:[$\sin(x)$].

    latexmath:[$C_y / C_x = \frac{Z_x - G}{Z_x}$]     (Eq. 1)

It renders extra parenthesis outside the equation, after using `pandoc` as: `pandoc -s -S input.html -f html+tex_math_dollars -o out.docx`. Is ther any way to remove them?

    <body class="article">
    <div id="header">
    <h1>Title</h1>
    </div>
    <div id="content">
    <div class="paragraph">
    <p>Inline test \($\sin(x)$\).</p>
    </div>
    <div class="paragraph">
    <div class="title">Equation 1</div>
    <p>\($C_y / C_x = \frac{Z_x - G}{Z_x}$\)     (Eq. 1)</p>
    </div>
    </div>
    <div id="footer">
    <div id="footer-text">
    </div>
    </div>
    </body>
    </html>

Cheers,
Arnaldo.

**Comment by mojavelinux** [comment]
> It renders extra parenthesis outside the equation

These are needed for MathJax to located the equations to render.

> Is there any way to remove them?

There isn't a built-in way at the moment. We have discussed the possibility of being able to customize the boundary delimiters, which would also allow you to remove them. See #758. If that seems sufficient, I'd like to mark this issue as a duplicate.

**Comment by arnaldorusso** [comment]
Tks @mojavelinux , It seems a duplicate issue.
BTW I'm using sed to parse those extra parenthesis outside equation 

    sed -r 's/\\\(\$/\$/g' < input.html | sed -r 's/\$\\\)/\$/g' > input_sed.html
