### ISSUE TITLE
"Failed to parse source, can't modify frozen Class" in second call to Asciidoctor#convert_file

### ISSUE THREAD

**Issue by S0lll0s** [asciidoctor/asciidoctor#1335]
I have set up a Guardfile to automatically re-render my document like this:

    module ::Guard
      class LoveDoctor < Plugin
        def run_all
          puts "rendering html.adoc"
          GC.start
          Asciidoctor.convert_file 'book/html.adoc', base_dir: 'book', to_file: '../public/index.html', safe: :unsafe, template_dir: 'templates'
        end

        def run_on_modifications(paths)
          puts "rendering html.adoc"
          GC.start
          Asciidoctor.convert_file 'book/html.adoc', base_dir: 'book', to_file: '../public/index.html', safe: :unsafe, template_dir: 'templates'
        end
      end
    end

    guard :lovedoctor do
      watch %r{^.*\.adoc$}
    end

This works perfectly fine the first time the hook runs, but the second time I get this stacktrace:

    20:50:24 - ERROR - Guard::LoveDoctor failed to achieve its <run_on_modifications>, exception was:
    > [#] RuntimeError: asciidoctor: FAILED: /home/s0lll0s/repos/love2d-book/book/html.adoc: Failed to parse source, can't modify frozen Class
    > [#] /home/s0lll0s/repos/love2d-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1369:in `rescue in load'
    > [#] /home/s0lll0s/repos/love2d-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1281:in `load'
    > [#] /home/s0lll0s/repos/love2d-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1465:in `convert'
    > [#] /home/s0lll0s/repos/love2d-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1569:in `convert_file'
    > [#] /home/s0lll0s/repos/love2d-book/Guardfile:16:in `run_on_modifications'
    [more irrelevant guard-interal frames below]

I have put some debug printing into `Asciidoctor#load` and narrow the problem down to [line 1356](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#l1356):

    doc = (Document.new lines, options).parse

The error is thrown within the `Document#new` call. I have tried adding `lines.dup` and another `options.dup` but neither helped. What is going on here?

**Comment by mojavelinux** [comment]
There error is completed misleading due to #1248, which has since been resolved in master. We were swallowing the real source of exceptions in core. If you comment out that line, then you see the real source of the error, which is:

```
> [#] RuntimeError: can't modify frozen Class
> [#] /tmp/love2D-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/extensions.rb:74:in `extend_object'
> [#] /tmp/love2D-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/extensions.rb:74:in `extend'
> [#] /tmp/love2D-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/extensions.rb:74:in `use_dsl'
> [#] /tmp/love2D-book/lovedoctor.rb:67:in `<class:LoveWikiMacro>'
> [#] /tmp/love2D-book/lovedoctor.rb:66:in `block in <top (required)>'
> [#] /tmp/love2D-book/vendor/bundle/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/extensions.rb:539:in `instance_exec'
```

The problem is that you defining an extension class inside the register block, which is called each time Asciidoctor runs. Once an extension class is registered, we freeze it. Therefore, on subsequent invocations of Asciidoctor, it attempts to redefined (though open classes) and already defined and frozen class.

You need to modify your lovedoctor.rb script so that the LoveWikiMacro class is defined above (and outside of) the register block. You don't need to move your other extensions that are defined using the DSL shorthand because new instances of created of those every time.

**Comment by mojavelinux** [comment]
In the extension tutorial, it will be important to clarify that extension classes must be defined outside of the register block.

**Comment by S0lll0s** [comment]
I would've liked to skip the class defintion and define the wiki macro in DSL altogether but for some reason that didn't work as expected. Thanks for the info, I'll fix it asap

**Comment by mojavelinux** [comment]
> I would've liked to skip the class defintion and define the wiki macro in DSL altogether but for some reason that didn't work as expected.

There's a small issue that makes the inline macro not work correctly. You can see my workaround in the following example:

https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/pick-inline-macro.rb

Reported as https://github.com/asciidoctor/asciidoctor/issues/1336.
