### ISSUE TITLE
Honor existing delimiters around inline stem equations

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1339]
If delimiters are used around block-level (i.e., display) equations, the delimiters are not added a second time.

```
[latexmath]
++++
\[
x = y^2
\]
++++
```

However, this is not true for inline equations. If the delimiters are already present, a redundant pair are added.

```
latexmath:[\(x = y^2\)]
```

We should probably be consistent.

**Comment by mojavelinux** [comment]
We probably want to check for this in the `restore_passthroughs` method.

```ruby
if type == :latexmath || type == :asciimath
  open, close = INLINE_MATH_DELIMITERS[type]
  if (subbed_text.start_with? open) && (subbed_text.end_with? close)
    subbed_text = subbed_text[open.length...-close.length]
  end
end
```

However, in the case of the stem block, we are handling it in the converter. We may need to rethinking where that is being done.

**Comment by jghub** [comment]
I would be greatly in favour of handling inline equation delimiters in the same way as for display equations (and not to add a redundant pair of \(, \) delimiters). I believe this actually would restore compatibility to original `asciidoc' (which at least accepts that syntax as an alternative to `$', and `$$').

**Comment by mojavelinux** [comment]
The alternate approach here is to remove the check for the delimiters from the block form (thus always requiring that they are not used). Whatever we decide, it shouldn't behave different between inline and block.

**Comment by jghub** [comment]
On Mon, 11 May 2015 23:53:30 +0200, Dan Allen <notifications@github.com>  
wrote:

> The alternate approach here is to remove the check for the delimiters  
> from the block form (thus always requiring that they are not used).  
> Whatever we decide, it shouldn't behave different between inline and  
> block.

as long as asciidoc is not changed accordingly, I would not like that  
route ... the best strategy in my view would be to make the delimiters  
optional in both cases, so that it remains permissible to use a  
asciidoc-compatible syntax.


>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/asciidoctor/asciidoctor/issues/1339#issuecomment-101059671


-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

**Comment by mojavelinux** [comment]
As it turns out, this is super easy to fix in AsciiDoc Python. Now that I've looked at it again, I'm even more convinced why I did it the way I did it in Asciidoctor. In AsciiDoc Python, the delimiters are automatically added for AsciiMath equations, but not for LaTeX equations. This just makes no sense. We really shouldn't be bleeding the delimiters into the AsciiDoc source, especially if AsciiDoc Python wasn't being consistent anyway. I'm going to start with a patch to AsciiDoc Python and see where that goes.

**Comment by jghub** [comment]
On Tue, 12 May 2015 11:42:03 +0200, Dan Allen <notifications@github.com>  
wrote:

> As it turns out, this is super easy to fix in AsciiDoc Python. Now that  
> I've looked at it again, I'm even more convinced why I did it the way I  
> did it in Asciidoctor. In AsciiDoc Python, the delimiters are  
> automatically added for AsciiMath equations, but not for LaTeX  
> equations. This just makes no sense. We really shouldn't be bleeding the  
> delimiters into the AsciiDoc source, especially if AsciiDoc Python  
> wasn't being consistent anyway. I'm going to start with a patch to  
> AsciiDoc Python and see where that goes.

I am by no means acquainted with the internals but might the difference  
have to do with support of the dblatex backend (i.e., rather, with the  
generated xml fed into dblatex)? or is this nonsense? because then you are  
of course right that it should be fixed in asciidoc rather than in  
asciidoctor.

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/asciidoctor/asciidoctor/issues/1339#issuecomment-101214695


-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

**Comment by jxxcarlson** [comment]
If there will be a change in Asciidoctor’s way of handling
math, please let me know in detail what is proposed.  Asciidoctor-LaTeX depends
on whatever low-level substitutions and pre-processing Asciidoctor does.

See, for example, 

	http://math.noteshare.io/book/asciidoctor-latex-manual <http://math.noteshare.io/>

Or

	http://math.noteshare.io/book/asciidoctor-latex-technical-report <http://math.noteshare.io/book/asciidoctor-latex-technical-report>


Thanks!

**Comment by mojavelinux** [comment]
I've found a solution for AsciiDoc Python to make delimiters optional. I'm going to submit a patch.

@jxxcarlson I'll double check the LaTeX backend, but in theory, this shouldn't affect it. However, it does present a good opportunity to align and document the options for writing math. I'll be in touch.

**Comment by mojavelinux** [comment]
Pull request submitted to AsciiDoc Python. See https://github.com/asciidoc/asciidoc/pull/72.

**Comment by jtkorb** [comment]
Is there a plan to make delimiters optional in Asciidoctor as well?  I'm using Pandoc to generate AsciiDoc and they include (per [AsciiDoc spec](http://asciidoc.org/userguide.html#_latex_math)) the delimiters in the output (e.g., latexmath:[$x = y^2$]).

**Comment by mojavelinux** [comment]
While we are talking about making the delimiters optional (which would be escaped backslashes, not dollar signs), even that should be considered deprecated. As Asciidoctor is the modern AsciiDoc processor, pandoc should be updated to not include the delimiters.

**Comment by mojavelinux** [comment]
I'm going to limit this to inline latexmath since it's not customary to put delimiters around AsciiMath.

**Comment by mojavelinux** [comment]
Since what we're shooting for is compatibility with AsciiDoc Python, we'll drop the delimiters that AsciiDoc Python required. That means, in the case of inline latexmath, we drop surrounding dollar signs (even though those delimiters aren't used by Asciidoctor at all).
