### ISSUE TITLE
With two consecutive Warning admonitions first one does not get generated

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor#1355]
WIth the following basic document,

```
= Admonitions

[chapter]
== Chapter with Warning

Some text here, then

WARNING: This is a warning admonition.

With some text in between

.Warning with title
WARNING: This is a warning with title
```

I only see the second warning appear. 

(Given that I have tried this with my own converter, I would have expected `admonition` to be passed twice in to the converter).

**Comment by robertpanzer** [comment]
I retested with the current AsciidoctorJ 1.6.0 and a modified TextConverter and a test as defined in https://gist.github.com/robertpanzer/0efc0accfd7566c6d89d

At least in this converter I see two calls with transform `admonition` and style `warning`.

**Comment by ysb33r** [comment]
I've used the latest 1.6.0 with this test https://github.com/ysb33r/asciidoctor-leanpub-converter/blob/master/core/src/test/groovy/org/ysb33r/asciidoctor/leanpub/AdmonitionsSpec.groovy#L12 and running this code:

https://github.com/ysb33r/asciidoctor-leanpub-converter/blob/master/core/src/main/groovy/org/ysb33r/asciidoctor/leanpub/LeanpubConverter.groovy#L180.

Totally possible that I am doing the wrong thing.

**Comment by robertpanzer** [comment]
I think the first warning does not appear in the output because the node has no title:

```
    def convertAdmonition(AbstractNode node,Map<String, Object> opts) {
        Block block = node as Block

        String prefix = styleMap[block.attributes.name]
        if(!prefix) {
            log.warn "${block.attributes.name} not recognised as a Leanpub admonition. Will render as normal text"
            block.attributes.style + ': ' + block.lines().join(LINESEP)
        } else {
            String content = ''
            if(block.title) { // For the first warning the title is null, therefore this method returns only a newline
                content+= prefix + '> ## ' + block.title + LINESEP
                block.lines().each {
                    content+= prefix + '> ' + it + LINESEP
                }
            }
            content + LINESEP
        }
    }
```

https://github.com/ysb33r/asciidoctor-leanpub-converter/blob/master/core/src/main/groovy/org/ysb33r/asciidoctor/leanpub/LeanpubConverter.groovy#L189

**Comment by mojavelinux** [comment]
Correct. An admonition doesn't always have a title. As Robert points out, when there is no block title, you are not populating the content.

**Comment by ysb33r** [comment]
*Slaps forehead*
