### ISSUE TITLE
literal block ending?

### ISSUE THREAD

**Issue by loreb** [asciidoctor/asciidoctor#1356]
Sorry for the nondescriptive title :)

An example from http://www.catb.org/esr/time-programming/index.asc, the paragraph "Broken down time" has a literal block which asciidoctor never closes - relevant part quoted below

```
= Time, Clock, and Calendar Programming In C =

=== Broken-down time ===

Unix represents calendar time using the following structure, which 
is consumed or emitted by several key functions:

----------------------------------------------------------------
struct tm 
{
    int    tm_sec;   /* seconds [0,60] (60 for + leap second) */
    int    tm_min;   /* minutes [0,59] */
    int    tm_hour;  /* hour [0,23] */
    int    tm_mday;  /* day of month [1,31] */
    int    tm_mon ;  /* month of year [0,11] */
    int    tm_year;  /* years since 1900 */
    int    tm_wday;  /* day of week [0,6] (Sunday = 0) */
    int    tm_yday;  /* day of year [0,365] */
    int    tm_isdst; /* daylight saving flag */
};
-----------------------------------------------------------------


Many of the most common problems with using the Unix time API can be
traced to the rather confused and inadequate design of this
structure. In what is probably unintentional humor, various manual
pages and standards documents refer to it as "broken-down time".

The most notable pain points include:

* +tm_isdst+ is easily misinterpreted as a flag when it's actually
  three-valued: 0 = DST off, 1 = DST on, -1 = DST status unknown.
  (Actually, values < -1 are treated as -1 and values > 1 treated
  as 1.)

```

**Comment by mojavelinux** [comment]
Asciidoctor is strict about matching start and end delimiters. Specifically, Asciidoctor requires that start and end delimiters (i.e., the fences) for blocks match in length. The ending delimiter line is one character longer than the starting delimiter line. This is why we recommend using shorter lines. Ideally, choose a length and stick with it. I always use the shortest length possible, which is 4 characters.

This is mentioned in the troubleshooting section of the FAQ.

http://asciidoctor.org/docs/faq/#troubleshooting

**Comment by loreb** [comment]
Doh, right there in the FAQ - sorry, that will teach me not to report bugs after a certain hour!

Yet this particular document ends without ever seeing the ending delimiter, that sounds easy to detect and report (I'd do it myself, but really ruby is like Chinese to me).

Otherwise just close the issue.

**Comment by mojavelinux** [comment]
No problem. You'll be happy to know that the warning message for this is scheduled to be added to 1.5.3. See #1133.

**Comment by loreb** [comment]
Yep :)
Among other things because your comments about speed prompted me to do some quick benchmarks and the difference was way more than I thought.

**Comment by mojavelinux** [comment]
1.5.7 will report a warning when block delimiters are mismatched. See #1133 for details.
