### ISSUE TITLE
Callouts in HTML 5 code listings break syntax when not using ':icons: font'

### ISSUE THREAD

**Issue by sometimesfood** [asciidoctor/asciidoctor#1360]
Callouts in HTML 5 code listings eat comment characters when not using `:icons: font`, thereby breaking copy & paste for code examples with callouts.

```
[source,ruby]
----
puts 'Hello world' # <1>
----
<1> I'd love to be a comment.
```

Without `:icons: font`, this results in a snippet similar to the following (note the missing `#` in front of `(1)`):

``` ruby
puts 'Hello world' (1)
```

The expected behaviour would look more like what `a2x` does:

``` ruby
puts 'Hello world' # (1)
```

Since GitHub uses asciidoctor internally, this effectively breaks code callouts on GitHub-rendered asciidoc files. See this gist for an example:

https://gist.github.com/sometimesfood/d826d5cd364e0ee5e881

**Comment by sometimesfood** [comment]
Apparently the node's text is wrapped in parentheses without adding a comment character in [Converter::Html5Converter#inline_callout](https://github.com/asciidoctor/asciidoctor/blob/2d221cfd0682896d43926aa11d3ff52663ccae44/lib/asciidoctor/converter/html5.rb#L1027).

The comment character is stripped in [Substitutors#highlight_source](https://github.com/asciidoctor/asciidoctor/blob/2d221cfd0682896d43926aa11d3ff52663ccae44/lib/asciidoctor/substitutors.rb#L1420).

Since the comment character is removed in `Substitutors#highlight_source`, I cannot think of a simple way to add the correct comment without breaking any of the other exporters.

Does anyone who knows the code base better than I do have an idea on how to solve this?

**Comment by mojavelinux** [comment]
The comment character is stripped because it's considered source information (not output information). However, I can see how this is a problem on GitHub where font-based icons are not enabled (because they can't be) and we don't have control over the stylesheet. In this case, we need to preserve the comment character, if present.

One way to do this is to preserve the comment character when the source highlighter is html-pipeline. That's our hint that we're on GitHub (or similar environment). We can certainly make that change.

**Comment by mojavelinux** [comment]
Of course, there will always be languages where this is going to stay broken because the language itself doesn't have anyway to hide the callout using a trailing line comment. We'd need a more sophisticated solution to address that issue.

**Comment by sometimesfood** [comment]
Thanks for the quick response. It would be great to see this fixed for languages with trailing line comments on GitHub, even if the fix has to be amended later for languages that do not have trailing line comments.

I am not so much concerned with environments where I can control myself if font-based icons should be used, but having callouts rendered in a way that does not break copy & paste of source code examples on GitHub would be great.

**Comment by hjwp** [comment]
+1!  I have a series of tests for my book that parse the html output to check the code listings are correct, and they are seeing `(1)` instead of `# (1)` in the raw text of code listings, which means syntax errors.  it's a silly little thing but it would make my life easier.  will fix it with regexes or something for now.  makes me want to learn ruby so i could fix it myself!

v. impressed with the current "non-selectable" feature on callouts btw.

**Comment by hjwp** [comment]
ps - I *am* using `:icons:font`, but the raw html still has the `(1)` in:

```
<i class="conum" data-value="1"></i>
<b>(1)</b>\
```

ideally this would become

```
<i class="conum" data-value="1"></i>
<b># (1)</b>\
```

**Comment by mojavelinux** [comment]
I figured out a workaround for this problem on GitHub. Keep in mind, it's just a workaround, but at least it gives you a stopgap in the near term.

In the document header, add the following lines:

```
:conum-guard-js: //
ifndef::icons[:conum-guard-js: // //]
```

(You'll need one of these for each language family).

Then, in a source block that has a conum, use:

```
[source,js,subs=attributes+]
----
var foo = "bar"; {conum-guard-js} <1>
----
<1> Assigns the String value `bar` to the variable named `foo`.
```

Basically, you just double up the comment leader. The parser removes the second one, but leaves behind the first. We use an attribute reference to work out whether to use a double comment leader or leave it as a single, based on whether icons are enabled.

**Comment by brunchboy** [comment]
Ow, this is painful… callouts make my code examples so much easier to follow, and work great on my locally generated version of my user guide, but most people will first encounter it on GitHub. Why must things always  be so difficult on GitHub? 😿 Thanks for the stopgap workaround though!

**Comment by mojavelinux** [comment]
I just sent a PR that will preserve the comment guard if icons are not enabled (as they are not on GitHub).

As an added bonus, the guard is now passed as an attribute named "guard" to the inline_callout converter method / template. This means a custom converter or template can choose if/when it wants to display it. So despite adding this behavior, we've still made it possible to opt-out of it.

The one thing that's still a bit weird about all this is how spaces are handled. But that's a separate issue ;)

**Comment by brunchboy** [comment]
Interesting! Thank you, how will we know if/when this makes it to production on GitHub so we can get rid of the extra pair of comment guards that will then appear?

**Comment by cup** [comment]
https://github.com/asciidoctor/asciidoctor/pull/2893
