### ISSUE TITLE
Allow table striping to be controlled by role or attribute

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1365]
Allow the striping of table rows (alternating colors) to be controlled by either a role or attribute.

To be consistent with how the borders are handled, the attribute might make the most sense.

```
[stripes="none"]
|===
|first row
|second row
|third row
|===
```

Though, we could disable it by default and allow it to be enabled using a role:

```
[.striped]
|===
|first row
|second row
|third row
|===
```

This would be similar to how Bootstrap works. See http://getbootstrap.com/css/#tables-striped.

As a side note, hovered rows might be interesting too. This may tip the scale towards using roles.

```
[striped.spotlight]
|===
...
|===
```

**Comment by mojavelinux** [comment]
You can add the following CSS to a [docinfo file](http://asciidoctor.org/docs/user-manual/#docinfo-file) to get this behavior today:

```
<style>
table tr.even, table tr.alt, table tr:nth-of-type(even) {
  background: none
}
table.striped tr.even, table.striped tr.alt, table.striped tr:nth-of-type(even) {
  background: #f8f8f7;
}
</style>
```

You could also switch this around by coloring the odd rows:

```
<style>
table tr.even, table tr.alt, table tr:nth-of-type(even) {
  background: none
}
table.striped tr.odd, table.striped tr.alt, table.striped tr:nth-of-type(odd) {
  background: #f8f8f7;
}
</style>
```

**Comment by dsisnero** [comment]
Would like this somehow in asciidoctor-pdf also

**Comment by antoyo** [comment]
@dsisnero It is already possible to do so in the whole document (but not on a specifi table) by modifying the theme.
You just have to comment the line:
```yaml
  even_row_background_color: f9f9f9
```
under the section `table:`.

**Comment by mojavelinux** [comment]
Exactly. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#table for more info.

**Comment by mojavelinux** [comment]
I think the option should be named "stripe" to be congruent with the frame and grid options. The CSS classes should also follow suite.

It's possible to control this behavior either using the option or the role directly. After all, the option just sets the role.

* stripe=even|odd|all|none
* .stripe-even, .stripe-odd, .stripe-all, .stripe-none

I don't add the role by default to reduce bloat. If we decide it should be added by default (like with frame and grid), I can update the PR.

**Comment by mojavelinux** [comment]
In the end, I decided to go back to the plural form, "stripes", as I think this is more parallel and natural.

* stripes=even|odd|all|none
* .stripes-even, .stripes-odd, .stripes-all, .stripes-none

**Comment by fdellwing** [comment]
Good decision because asciidoctor-pdf is using `stripes` as well!

**Comment by earshinov** [comment]
Hello! Shouldn't the `stripes` attribute be documented in the official documentation like [Writer's Guide](https://asciidoctor.org/docs/asciidoc-writers-guide/) or [User Manual](https://asciidoctor.org/docs/user-manual/)?

**Comment by mojavelinux** [comment]
This feature is now documented in the User Manual.
