### ISSUE TITLE
Methods to add roles on a node are missing

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1366]
AFAICS there is no simple way at the moment to add a role to a node for an extension.
The roles are stored as a blank separated string in the attribute `role`.
Without knowing about this implementation detail it is hard to add a role.
It would be nice to have dedicated methods add_role and remove_role.

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/abstract_node.rb#L197-L227

**Comment by mojavelinux** [comment]
I agree. Internally, we really need to switch to an array anyway. The implementation is really only half done.
