### ISSUE TITLE
Mathjax in Asciidoc in Middleman

### ISSUE THREAD

**Issue by rsbowman** [asciidoctor/asciidoctor#1367]
Hi, Love asciidoc, love the work you guys are doing.

I'm using the asciidoc support in middleman 3.3.12 (asciidoctor 1.5.2).  In my config.rb I have 

```
 set :asciidoc_attributes, %w(stem=latexmath)
```

and if I pritnt out `config[:asciidoc]` I get

```
{:safe=>:safe,
 :backend=>:html5,
 :attributes=>
    ["showtitle",
     "env=middleman",
     "env-middleman",
     "middleman-version=3.3.12",
     "stem=latexmath",
     "imagesdir=/images"],
 :base_dir=>"(whatever dir)"}
```

My inline stuff (using $ delimiters) all works great.  Display stuff mostly works, too.  However, sometimes it doesn't.  For example, I have a line 

```
\[ M .....  etc, etc..... ). \]
```

which renders perfectly (without any ++++ blocks or "stem" annotations) but another line

```
\[ \bigoplus_i M_i \]
```

Doesn't render properly.  I'm confident there are no syntax errors in the formula because it renders in LaTeX itself and also markdown.  I can put a 

```
<script type="math/tex; mode=display"> \bigoplus_i M_i</script>
```

tag in a ++++ block and things work great, but otherwise I get a weird rendering: it's centered, the "\bigo" is in red, plus<sub>i</sub> in italics, and M<sub>i</sub> in italics.

I realize this stuff is in an early stage and you're working hard on it (thanks!), but is there a way to get things working without having to wait for middleman 4?  LaTeX math is a MUST for me, and I'll have to go back to markdown otherwise...

Thanks again!

**Comment by jxxcarlson** [comment]
Are you running vanilla Asciidoctor?  

it might be worth trying Asciiidoctor-LaTeX, which is
what I have the most experience with and which
aims to bring as full a LaTeX experience
as possible to you.

 I’ve made some recent changes to it deal
with problems that sound similar to yours.

 Asciiidoctor-LaTeX is the engine that powers
http://math.noteshare.io <http://math.noteshare.io/> .  There is a lot of math
there, and it is all done with Asciidoctor-LaTeX.


You would need to clone the repository at 

	https://github.com/asciidoctor/asciidoctor-latex <https://github.com/asciidoctor/asciidoctor-latex>

then run 

	$ rake install

after which you can say

	$ asciidoctor-latex -b foo.adoc

for html output or

	$ asciidoctor-latex foo.adoc

for LaTeX output (this part is quite rough).
Somewhere at the head of your file you may have to put :latex:

if you can do this, I’d be very interested the result.

— Jim  (@jxxcarlson on GitHub, @epsilon2718 on Twitter)

**Comment by jxxcarlson** [comment]
I have no experience with middleman.  What does it do?

**Comment by mojavelinux** [comment]
This needs to be addressed in the following project.

https://github.com/middleman/middleman-asciidoc

However, that would require upgrading to Middleman 4. AsciiDoc support is provided out of the box in Middleman 3, so the change would have to be made to Middleman itself...but that is unlikely to happen in Middleman 3).

**Comment by mojavelinux** [comment]
Of course, you can solve this problem in code for your own side by adding MathJax to the base template. Asciidoctor doesn't actually do anything special to process expression other than get them ready for MathJax to process. So all the work is in the template.

See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L112-L132

**Comment by mojavelinux** [comment]
Aha. On closer examination, I realize that the problem you are having is with the interpretation of the expressions. I apologize for missing the point originally.

You can't put expressions directly in AsciiDoc* without surrounding it in a stem inline macro or stem block. The reason is, the content needs to be escaped from AsciiDoc. That's what these containers do. That's probably why you are getting problems. They also prepare the expression to work with the configuration of MathJax that we load in Asciidoctor (that perhaps you copied from the converter).

\* The exception here is if you are using the Asciidoctor LaTeX extension which basically solves the exact problem at hand.

**Comment by rsbowman** [comment]
Yes, gotcha.   I suppose I just thought from a cursory glance at #492 that that would be possible with the correct options.  I tried using asciidoctor-latex but it's not clear how to integrate it with middleman 3.  Also, middleman 4 is pretty much impossible to install these days unless you're smart and have lots of time.

For now I'm going back to markdown, but I certainly hope to revisit asciidoc/asciidoc-latex when markdown 4 arrives!  Thanks for your help and explanations.

**Comment by mojavelinux** [comment]
>  I just thought from a cursory glance at #492 that that would be possible with the correct options.

The correct approach at this point is to use the stem macro and stem block as documented.

http://asciidoctor.org/docs/user-manual/#activating-stem-support

> For now I'm going back to markdown

I'm confused how that solves your problem. Math formulas are very possible with Asciidoctor, you just have to insert them as directed.

**Comment by mojavelinux** [comment]
> middleman 4 is pretty much impossible to install these days

Thanks for your feedback about Middleman 4. I didn't realize it was getting so complex. That's a shame.

**Comment by rsbowman** [comment]
Hi,

Going back to markdown doesn't solve the problem of rendering math formulas, but as a mathematician I'm used to latex.  Typing

[stem]
++++
blah blah blah
++++

is much more work than

\\[ blah. \\]

It adds up, and I don't see compelling reasons for it.  Especially for documents consisting largely of mathematics (inline and display) this makes the document much longer, harder to skim, and just more verbose in general.  

As you say, math works fine now (and that's great!) but it looks like there will be (hopefully) more and better options in the future.  

Thanks again!

**Comment by mojavelinux** [comment]
>  it looks like there will be (hopefully) more and better options in the future.

Indeed. Tailoring AsciiDoc to writers who are most familiar with LaTeX is a new consideration, one that came up after the initial design for STEM / LaTeX integration was done. Despite the fact that this audience wasn't catered to originally (perhaps a mistake), we certainly welcome them and want them to feel comfortable writing in this environment. It's clear to me that treating LaTeX delimiters natively is an important direction for the syntax.

> It adds up, and I don't see compelling reasons for it.

I can say that the compelling reason is for the AsciiDoc syntax to be consistent. However, this is a great example of a case when breaking consistency with other parts of the syntax actually produces a better language. After all, we aren't machines...so consistency isn't the only factor.

**Comment by mojavelinux** [comment]
> It's clear to me that treating LaTeX delimiters natively is an important direction for the syntax.

And having said that, it's critical that LaTeX delimiters be treated with "passthrough" semantics to avoid any interpretation within them. This is something that is being experimented with in Asciidoctor LaTeX, but still requires some work to get right. Of course, it likely will get rolled into core so that Asciidoctor LaTeX isn't needed for this part.

**Comment by jxxcarlson** [comment]
Just out of curiosity, what is middleman?


I am a mathematician also (Hodge theory, algebraic geometry).  So I am
in agreement with you about it “adding up”.  And it adds up really fast!

This was one of the reasons why I got involved in the Asciidoctor-LaTeX
project.   Asciidoctor-LaTeX allows you to freely use $ .. $ and \[ … \].

There a other goodies as well.  For example,

[env.theorem#fermat]
—
If $p$ is prime and $a$ is not divisible
by $p$, then $a^{p-1} \equiv 1 \text{ mod } p$
—

gives you an automatically numbered theorem, just like the LaTeX
theorem environment.  The text after the hash mark is a label for
cross referencing.  For example: <<fermat>> produces the cross
reference (a hyperlink).

See http://math.noteshare.io/section/asciidoctor-latex-manual-intro <http://math.noteshare.io/section/asciidoctor-latex-manual-intro>
for more info if you are interested.

I’ve used this for my Hodge theory course in Beijing:

	http://math.noteshare.io/book/hodge-theory <http://math.noteshare.io/book/hodge-theory>

The still experimental LaTeX back end for Asciidoctor-LaTeX
converts this into a LaTeX file that tex without error.

Regards,

Jim

**Comment by mojavelinux** [comment]
> Just out of curiosity, what is middleman?

A static site generator like Jekyll. It has a much more sophisticated extension system, which is its defining characteristic in my mind. See https://middlemanapp.com/

**Comment by rsbowman** [comment]
Hi jxxcarlson, as mojavelinux says, middleman's extension system is very nice, and it seems that with the upcoming version 4 it will be even nicer.  For one thing, asciidoc integration will be its own plugin, so we won't have to muck with the application itself to change behavior.  Unfortunately I don't have any examples set up (yet) but middleman plus mathjax makes a very nice math blog.

**Comment by jxxcarlson** [comment]
Thanks both rsbowman and @mojavelinux.  Now I understand.

Jim

http://noteshare.io <http://noteshare.io/>
http://home.noteshareblog.io <http://home.noteshareblog.io/>

**Comment by mojavelinux** [comment]
Please reopen this issue here if you want to continue the discussion: https://github.com/middleman/middleman-asciidoc
