### ISSUE TITLE
Table with trailing comma in cols argument wraps wrongly?

### ISSUE THREAD

**Issue by and3k** [asciidoctor/asciidoctor#1375]
Hi!

Not sure if this is a bug, or purposely done by Asciidoctor.

When I use this, I get a table with 4 rows (wrong):

```adoc
[cols="<,"]
|============================
| 1 | 2
| 3 | 4
|============================
```

When I use this, I get a table with 2 rows and 2 cols (correct):

```adoc
[cols=","]
|============================
| 1 | 2
| 3 | 4
|============================
```

I noticed because I converted Pandoc’s simple table [example](http://pandoc.org/README.html#tables)

```md
  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12
    123     123       123          123
      1     1          1             1
```

to AsciiDoc

```adoc
[cols=">,<,^,",options="header",]
|============================
|Right |Left |Center |Default
|12 |12 |12 |12
|123 |123 |123 |123
|1 |1 |1 |1
|============================
```

which gave me a table with only 3 cols.

Thanks!
Bela

**Comment by mojavelinux** [comment]
Right you are! We're getting cut by one of the sharpest edges in Ruby. When you split a string, by default Ruby (conveniently?) drops empty records. Thus, the empty colspec records are being ignored. Fortunately, Ruby also provides a way to suppress this (helpful?) behavior of split.

This makes for an excellent test case. I've applied the fix and added a test case to prove it in #1376.

**Comment by and3k** [comment]
Works. Thank you!

**Comment by mojavelinux** [comment]
Excellent! Thanks for testing!

**Comment by mojavelinux** [comment]
To clarify for the record, if the limit argument to `split` is empty, then trailing fields are dropped (not all empty fields).
