### ISSUE TITLE
recursively generating html files with destination directory, generates all the html files in single directory "without honouring subdirectory tree in the source"

### ISSUE THREAD

**Issue by zaxebo1** [asciidoctor/asciidoctor#1394]
say, there is a document tree like

```
prj1/
     doc1/
            source1/
                        a1.adoc
                        a2.adoc
                        subdir_a/
                                      a11.adoc
                                      a12.adoc
                                      subdir111/
                                                     a111.adoc
                                                     a112.adoc
                        subdir_b/
                                      b11.adoc
                                      b12.adoc 
```

Now, if i want to create html output of it (on linux,windows both) **in a seaprate directory tree out1** (not generating in-place), 
then by command

```
    $   cd prj1/doc1/
    $   asciidoctor  "**/*.adoc" -D out1
```

it currently generates all the html file in the same directory
Current output:

```
prj1/
      doc1/
             source1/
              out1/
                     a11.html
                     a12.html
                     a111.html
                     a112.html
                     b11.html
                     b12.html
```

it clubbed all the .html outputted in the same destination directory. **which is wrong**
      whereas , i would like it to honour the directory tree as in source tree, the target output directory should have also the same directory tree.
Expected output:

```
prj1/
     doc1/
             source1/
             out1/
                    a1.html
                    a2.html
                    subdir_a/
                                  a11.html
                                 a12.html
                                 subdir111/
                                               a111.html
                                               a112.html
                     subdir_b/
                                 b11.html
                                 b12.html
```

```
    **sphinx generates html in the above expected ^ way only**. It keeps the subdirectory tree as it is for the generated html documents
```

 So currently "what"(?) command should i give, to generate, something **may be** like(in pseudo code)

```
         $ cd prj1/doc1
         $ asciidoctor -b html5 -R --source-dir source1  --destination-dir out1
```

```
             here "-R" is for recursive (may be)
```

As i want to be able to do this in linux and windows both, hence i do not want to be dependent on some bash trick.

**Comment by mojavelinux** [comment]
My feeling on this issue is that this is not within the scope of the `asciidoctor` command. Once we start going down this road, we become a build tool, and I really don't want Asciidoctor (core) to be stepping on the toes of what other tools handle so well. The `asciidoctor` command is primarily indented for light/casual usage, some tooling integrations and for checking documents. When you want to work with a project that has many AsciiDoc files that you want to process, I think it is much better to use a build tool like Gradle + the Asciidoctor Gradle plugin.

Having said all that, I am willing to look at a change that meets us half way. If we acknowledge that Asciidoctor is not a build tool, but there is something in the realm of the light/casual that is very non-intuitive...and the change is relatively small...then I'm certainly willing to consider it.

**Comment by mojavelinux** [comment]
I think there may be room here for a change to honor the subdirectories, but I want to make it clear that it won't process non-AsciiDoc files. The reason is because I think this is the role of a build tool.

**Comment by mojavelinux** [comment]
I don't mean to sound so tough about this issue. It's just that I really want Asciidoctor to stay focused and I'm very worried that build-related stuff can sidetrack us. If anything, I'm just nervous about making the right choices here.

**Comment by mojavelinux** [comment]
There's one more thing I want to add that will hopefully clarify my current thinking. I definitely think there is room for a documentation-focused build tool within Asciidoctor, if not the Gradle plugin. Something that will fill in some features that users are familiar with from Sphinx. I'm totally in support of that, but I see that as a separate module, not the main `asciidoctor` command. In fact, I'd like to see multiple options (which is the direction we're already headed) so that all the eggs aren't in one basket and we don't end up with a monolithic tool.

Having said that, I do think it's reasonable that output folders are preserved in the destination directory :)

**Comment by zaxebo1** [comment]
My Feedback regarding proposal#1 (adding small enhancement to asciidoctor):

Thanks a lot. i will be happy even with your proposed limitation too.
even if enhanced asciidoctor does that much with version 1.5.4 release, even then it will be good enough for first time users like us

*****

My Feedback regarding proposal#2 (full scale build tool):

regarding your proposal for "some other tool for doing the full fledged  build thing" and gradle suggestion:

 i think asciidcotor and asciidoctorj both run on ruby native and jruby both; and rake build tool (in ruby only) is available on ruby native and jruby both - it is inbuilt bundled with the "distribution" of ruby and jruby both. 
Hence, some rake task(which will be applicable to ruby and jruby both) example can be put so that anybody who is coming from sphinx (but does not know ruby), can have immediate example in standard documentation , as to how to achieve this via any  other tool.

If somebody wants to use gradle, then they are java/groovy people, example may be given for them too. But for other people coming from python and other platforms, who have already added ruby as a dependency , they may not want to add gradle (depending upon groovy and java) as one more dependency. **So may be "rake task" plugin which makes it easy to do such thing, and its example in the user manual will ease the transition for sphinx users.


Just like "asciidoctor-pdf" is just wrapper over along  "asciidoctor -r ..... " command line
in the same way, Some other proposed tool can be just a wrapper which just calls this "rake task easily". 
But anyway right now, probably a rake task plugin and example is good enough for sphinx migrationThanks a lot for accepting this. i will be happy even with your proposed limitation too.
even if enhanced asciidoctor does that much with version 1.5.4 release, even then it will be good enough

****

regarding your proposal for "some other tool for doing the full fledged  build thing" and gradle suggestion:

 i may suggest that - because asciidcotor and asciidoctorj both run on ruby native and jruby both; 
                     and because rake build tool (in ruby only) is available on ruby native and jruby both 
                     and because rake  is inbuilt bundled with the "distribution" of ruby and jruby both. 
                     
Hence, some rake task(which will be applicable to ruby and jruby both) example can be put so that anybody who is coming from sphinx (but does not know ruby), can have immediate example in standard documentation , as to how to achieve this via any  other tool.

If somebody wants to use gradle, then they are java/groovy people, example may be given for them too. But for other people coming from python and other platforms, who have already added ruby as a dependency , they may not want to add gradle (depending upon groovy and java) as one more dependency. **So may be "rake task" plugin which makes it easy to do such thing, and its example in the user manual will ease the transition for sphinx users.


**Just like "asciidoctor-pdf" is just wrapper over along  "asciidoctor -r ..... " command line
in the same way, Some other proposed tool can be just a wrapper which just calls this "rake task easily".**
 
But anyway right now, probably a rake task plugin and its example is good enough for full scale sphinx migration of docs .

**Comment by mojavelinux** [comment]
I like the idea of a Rake task for Asciidoctor. That would certainly make for a nice addition to the Asciidoctor ecosystem.

**Comment by mojavelinux** [comment]
Here's the capability I'm prepared to offer.

If you're converting multiple files at once (a glob) and a destination directory, if you also specify a source directory, then the intermediate directories between the source directory and the file being converted get mirrored under the destination directory. This is a feature exclusive to the CLI tool for now.

In the example you provided, you'd use this command:

```
$ cd prj1/doc1
  asciidoctor -R source1  -D out1 '**/*.adoc'
```

In this example, `-R` is shorthand for `--source-dir`.

You still have to specify a file glob. That's where we draw the line from Asciidoctor being a CLI tool and Asciidoctor being a build tool. If we only required specifying the source directory, then Asciidoctor would have to scan or glob for files itself to convert. I don't want to open that box.

**Comment by mojavelinux** [comment]
I can definitely see this being a useful tool.
