### ISSUE TITLE
How to set Asciidoc toc.section.depth value from simple 'asciidoctor file.txt -o file.html' command?

### ISSUE THREAD

**Issue by johnnyutahh** [asciidoctor/asciidoctor#1398]
http://stackoverflow.com/questions/31255103/how-to-set-asciidoc-toc-section-depth-value-from-simple-asciidoctor-file-txt-o

**Comment by mojavelinux** [comment]
What you're looking for is toclevels. See http://asciidoctor.org/docs/user-manual/#levels.

**Comment by johnnyutahh** [comment]
Excellent, works exactly as desired. Thanks.
