### ISSUE TITLE
Print text is too large.

### ISSUE THREAD

**Issue by nwmcsween** [asciidoctor/asciidoctor#1410]
A single A4 page styled with asciidoctor can hold about ~20-25 lines of text, this makes using asciidoctor for anything print related many pages.

**Comment by mojavelinux** [comment]
Are you referring to the print CSS styles? They are designed to maximize accessibility by default. If you'd like different behavior, you have the option of supplying your own stylesheet. If you are referring to the Asciidoctor PDF converter, could you file it in that repository? Even then, you can supply your own theme with a font size of your choosing.

**Comment by nwmcsween** [comment]
Yes the print css styles seem to be way too large, imo accessibility is great but I doubt it should a default for print.

**Comment by mojavelinux** [comment]
I count 40 lines fitting in an A4 page when printing to PDF using Chrome.

![lorem-ipsum](https://cloud.githubusercontent.com/assets/79351/8692250/d3449814-2a89-11e5-9cdf-0f754dfd4474.png)

Here's the quickest workaround for this without creating your own stylesheet.

Assume your document is file.adoc. Create a docinfo file named after your document:

*file-docinfo.html*

```html
<style>
@media print{
  @page {
    margin: 1.25cm .75cm 1cm .75cm;
  }
  #header,
  #content,
  #footer{
    font-size:75%;
  }
}
</style>
```

Enable docinfo when running Asciidoctor:

```
$ asciidoctor -a docinfo file.adoc
```

You'll now have much smaller text when you print. And you can adjust it to suit your needs exactly.

Of course, the other option is to create a whole new stylesheet, or hack on the one that comes with Asciidoctor. In that case, you'd run:

```
$ asciidoctor -a stylesheet=my-styles.css file.adoc
```

You can quickly extract the Asciidoctor default stylesheet to hack on it using the following command:

```
$ asciidoctor -a linkcss file.adoc
```

You'll find asciidoctor.css in the current directory (the output directory). You can rename it, hack on it and feed it to the command above.

**Comment by nwmcsween** [comment]
thanks that helped

**Comment by mojavelinux** [comment]
I had totally tricked myself. I had my print settings set at 75% when I was testing. So in the end I was getting skewed results. I'll address as part of #1484.
