### ISSUE TITLE
CSS source block not resolving subs, even with +attributes

### ISSUE THREAD

**Issue by tbee** [asciidoctor/asciidoctor#1413]
I'm using asciidoclet to generate the documentation for the JFXtras open source project, and I have problems with CSS source block. I suspect this is related to asciidoctor and not asciidoclet, hence this issue.

The problem is simple, if I include a source block of type CSS the attributes are not replaced. If I make it of type xml or java, then it is. Since JFXtras is open source, the code can be easily inspected.

https://raw.githubusercontent.com/JFXtras/jfxtras/bc9c57a6d659e1e5a3b08e152814dc87c5e61d2e/jfxtras-controls/src/main/asciidoc/scene/control/CalendarTextField_icon.adoc

I've used XML here, because correct content is more important than formatting.

**Comment by mojavelinux** [comment]
The problem here is with the order of substitutions. If you append the attributes sub, that means it happens last. The CSS lexer separates the curly braces from the keyword, so you end up with:

```xml
.{<span class="key">control</span>}
```

By the time Asciidoctor gets a chance at it, it no longer looks like an attribute.

The solution is to put the attributes replacement first in the list, which you should probably be doing anyway.

```
[source,css,subs="attributes+"]
----
.{control} .icon  {
    -fx-image: url("AlternateCalendarIcon.jpg");
}
----
```

**Comment by tbee** [comment]
Thanks! That makes perfect sense, and was probably something I could have thought of myself, if I were a bit more experienced with asciidoctor. Which maybe is a good reason for changing the example in the user manual to "attributes+" instead of "+attributes". Because while feeling out this (to me) new concept of attributes and trying to get replacement to work in source blocks, Googling led me to the user manual and copying the example in 38.7 to this issue. Changing the example may save you from more noob questions :-)

**Comment by mojavelinux** [comment]
Example changed! Thanks for the suggestion.

https://github.com/asciidoctor/asciidoctor.org/commit/e2a94bd7c5dd004b2cabe32ad7bad4bf85de5f77
