### ISSUE TITLE
Unwanted space characters in Japanese language

### ISSUE THREAD

**Issue by yantarou** [asciidoctor/asciidoctor#1420]
Good Morning,

I'm inserting line breaks into the AsciiDoc source to make long sentences easier readable.

For the English language this works as expected, a line break in the source translates into a space in the output.

AsciiDoc:

```
This example sentence is split
over multiple lines in order
to make editing easier.
```

Output:

```
This example sentence is split over multiple lines in order to make editing easier.
```

The Japanese language doesn't know spaces between words though, the line breaks should be ignored.

I wonder if there is any configuration option that can influence this behavior?

AsciiDoc:

```
この例文は、編集作業を
楽にするために複数の行
に分割されています。
```

Output:

```
この例文は、編集作業を 楽にするために複数の行 に分割されています。
```

Desired output:

```
この例文は、編集作業を楽にするために複数の行に分割されています。
```

Thanks,
Jan

**Comment by mojavelinux** [comment]
This is actually HTML adding the spaces in, sort of. You see, Asciidoctor passes the text as you see it (after removing trailing whitespace on the line) to HTML. All whitespace gets consolidated by HTML into a single space. That looks normal in English text (as the endline in the source is most likely at the boundary of a word or sentence). However, in Japanese text you end up with an unwanted space.

One solution to this problem today is to create a Treeprocessor or Postprocessor extension that finds all paragraph text and removes the unwanted space.

For the long term, this is an intriguing question as it affects all similar languages. Poetry-style writing (aka sentence or phrase per line) should be an option when writing in these languages but still get the desired output. I think perhaps the solution is to change the behavior when the `lang` attribute is one of the languages in which whitespace has no significance.

**Comment by mojavelinux** [comment]
...and we certainly want Asciidoctor to friendly and comfortable for all languages.

**Comment by chloerei** [comment]
Chinese has the same problem. I write a Treeprocessor

```ruby
require 'asciidoctor/extensions'

class TrailingTreeprocessor < Asciidoctor::Extensions::Treeprocessor
  def process document
    return unless document.blocks?
    process_blocks document
    nil
  end

  def process_blocks node
    node.blocks.each_with_index do |block, index|
      if block.context == :paragraph
        node.blocks[index] = create_paragraph block.document, block.content.gsub("\n", ''), block.attributes
      else
        process_blocks block
      end
    end
  end
end

Asciidoctor::Extensions.register do
  treeprocessor TrailingTreeprocessor
end
```

Save in `config.rb`, then:

```
$ asciidoctor -r ./config.rb filename.adoc
```

**Comment by mojavelinux** [comment]
The switch that needs to be enabled here in core is what is the character for a prose endline. In Latin-based languages, it is a literal endline. For CJK, it would need to be an empty space.

**Comment by mojavelinux** [comment]
And this would be something that could be controlled through the language or language family.

For now, you need to either take the approach that @chloerei suggested, or don't insert endlines in your prose in the AsciiDoc source document.

**Comment by l1048576** [comment]
Macros in CJK have the same problem (unwanted spaces).

```
これは link:http://example.com[リンク]です。
```
is currently (ver1.5.4) converted to
```
これは <a href="http://example.com">リンク</a>です。
```
, which contains unwanted space before `<a>`.
(Fortunately, space is not necessary after `]` and it is good for CJK.)

## Proposal
I propose two (exclusive) rules below.

Note that:
- [ ] <- means asciidoctor-1.5.4 doesn't do.
- [x] <- means asciidoctor-1.5.4 does.


### Rule to remove spaces
These are removed in the output:
- [ ] single whitespace right before macro and right after CJK character
- [ ] single breakline right after CJK character

Example:
```
これは link:foo[リンク]です。

改行を
含みます。
```
would be converted to:
```
<p>これは<a href="foo">リンク</a>です。</p>
<p>改行を含みます。</p>
```

### Rule to preserve spaces
These are converted to single space in output:
- [x] single breakline right afer non-CJK character
- [x] spaces at the beginning of the line (except for the first line of the paragraph)
- [ ] two or more successive whitespace characters before macro

Example:
```
空白のあとに  link:bar[リンク]があります。
// Contains two whitespace characters before `link`.

この空白は
 保持されます。
// Contains single whitespace before "保持".
```
would be converted to:
```
<p>空白のあとに <a href="bar">リンク</a>があります。</p>
<p>この空白は 保持されます。</p>
```

**Comment by oncletom** [comment]
Digging a bit in the issues, I found we probably had a similar conversation in #1174.

**Comment by crocket** [comment]
@lo48576 Yo, man.
I found that the following snippet compiles.

```
これはlink:http://example.com[リンク]です。
```

Even, the following snippet compiles properly.

```
crocketlink:http://example.com[リンク]です。
```

If you like to make a visual distinction, you can use `pass:[]`

```
pass:[これは]link:http://example.com[リンク]です。
```

**Comment by crocket** [comment]
What about letting backslash at the end of a line to concatenate the next line to the current line?

Could

```
この例文は、編集作業を\
楽にするために複数の行\
に分割されています。
```

be converted to

```
この例文は、編集作業を楽にするために複数の行に分割されています。
```

without breaking backward compatibility?

**Comment by zhangkaizhao** [comment]
Hi.
I just wrote a Treeprocessor which is a port of [markdown-it-cjk-breaks](https://github.com/markdown-it/markdown-it-cjk-breaks) but for Asciidoc.
Feel free to try it if you are interested: https://github.com/zhangkaizhao/asciidoctor_cjk_breaks

---
Related information in Markdown as far as I know:

https://talk.commonmark.org/t/soft-line-breaks-should-not-introduce-spaces/285

(which came from https://github.com/TryGhost/Ghost/issues/3893 )

Plugin for markdown-it to automatically deal with segment breaks:

https://github.com/markdown-it/markdown-it-cjk-breaks

whose algorithm matches [CSS Text Module Level 3](https://www.w3.org/TR/css-text-3/#line-break-transform)

(which came from https://talk.commonmark.org/t/soft-line-breaks-should-not-introduce-spaces/285/9 )

It is said this plugin is similar to one in pandoc:

https://github.com/jgm/pandoc/pull/534

**Comment by mojavelinux** [comment]
Related issue: #4468.

**Comment by tats-u** [comment]
The CSS spec has been changed. (It's handled by CSS, not HTML)
A newline surrounded by  *only Chinese/Japanese* characters must be just removed. Unconditional insertion of a space *is a bug* today:

https://wpt.fyi/results/css/css-text/line-breaking?label=experimental&label=master&aligned&q=segment-break-transformation-rules-
https://drafts.csswg.org/css-text-4/#line-break-transform
https://issues.chromium.org/issues/40069685
https://bugs.chromium.org/p/chromium/issues/detail?id=1223979
https://bugs.webkit.org/show_bug.cgi?id=260857

**Comment by tats-u** [comment]
In the first place, why doesn't AsciiDoc leave spaces to browsers like many Markdown parsers?

**Comment by tonytonyjan** [comment]
> The CSS spec has been changed. (It's handled by CSS, not HTML) A newline surrounded by _only Chinese/Japanese_ characters must be just removed. Unconditional insertion of a space _is a bug_ today: Browsers other than Firefox have this bug.
> 
> https://wpt.fyi/results/css/css-text/line-breaking?label=experimental&label=master&aligned&q=segment-break-transformation-rules- https://drafts.csswg.org/css-text-4/#line-break-transform https://issues.chromium.org/issues/40069685 https://issues.chromium.org/issues/40774934 https://bugs.webkit.org/show_bug.cgi?id=260857

@mojavelinux  I think we can close the issue because it is a browser's issue rather than asciidoctor's issue?

**Comment by tats-u** [comment]
Does AsciiDoctor just retain newlines?

**Comment by mojavelinux** [comment]
Yes, Asciidoctor leaves the space characters as they are written (spaces remain as spaces and newlines remain as newlines). The assumption is that the renderer will normalize them, such as the browser for HTML.

**Comment by tats-u** [comment]
I got it. Do you know where we should discuss the specification shared with the entire of Asciidoctor family?
I remember Asciidoctor-pdf doesn't use any browsers to render the document.

**Comment by mojavelinux** [comment]
You're free to ask open-ended questions in the project chat at https://chat.asciidoctor.org.

**Comment by tats-u** [comment]
I see. Asciidoctor supports DocBook & EPub ports, too. I don't know how they treat newlines in XML. Are they left to renderes? How many renderers for them use the browser architecture?

**Comment by mojavelinux** [comment]
Please continue this discussion in the chat. The issue tracker is intended to track design decisions. It's not for open-ended discussions.

**Comment by mojavelinux** [comment]
In terms of the HTML converter, it seems this issue has been resolved by CSS and thus no action is needed here.

**Comment by tats-u** [comment]
> In terms of the HTML converter,

Are you saying EPub & DocBook both use CSS for styling?

**Comment by tats-u** [comment]
Also Asciidoctor shouldn't trust the CSS implements of web browsers today too much.

**Comment by mojavelinux** [comment]
If this is a behavior you need, you're welcome to extend the converter and add the logic to that extended converter. This is not something we're going to add to Asciidoctor right now.
