### ISSUE TITLE
-a theme=flask does nothing

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1436]
A couple of sources I found on the web say that setting the theme attribute with `-a theme=flask` will make asciidoctor use the asciidoc flask theme. But there is no difference in output when this attribute is set. The standard asciidoctor CSS is still used. There are no errors or warnings even with -v.

What am I doing wrong?

**Comment by mojavelinux** [comment]
Asciidoctor does not implement the theme feature of AsciiDoc Python. To supply your own stylesheet, use the `stylesheet` attribute.

```
:stylesheet: my-styles.css
```

The value is a path to a stylesheet relative to the `stylesdir`. If the `stylesdir` is not set, then the value is relative to the document.

By default, Asciidoctor will attempt to embed the stylesheet into the document. If you just want to link to it, then you can set `linkcss`.

```
:linkcss:
:stylesheet: my-styles.css
```

For more information, see http://asciidoctor.org/docs/user-manual/#applying-a-stylesheet

**Comment by mojavelinux** [comment]
You can use the flask theme by copying the CSS to the location of your project then activating it using:

```
:stylesheet: flask.css
```

It will mostly work with Asciidoctor output, though there will be slight differences.

**Comment by mojavelinux** [comment]
Asciidoctor only provides a single default stylesheet intended for reference and document preview. Check out the following repository for a bunch of alternate themes that are based on the default stylesheet.

* https://github.com/darshandsoni/asciidoctor-skins
