### ISSUE TITLE
Does asciidoctor have a standard set of icons?

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1438]
I am using callouts in an included source file. When I run asciidoctor I get errors that the icons can't be found.
```
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/1.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/2.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/3.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/4.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXXXXX/samples/src/DisplacementMapper/images/icons/callouts/1.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/2.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/3.png
asciidoctor: WARNING: image to embed not found or not readable: /Users/XXX/XXX/samples/src/DisplacementMapper/images/icons/callouts/4.png
```
Doesn't asciidoctor have a standard set of icons? In asciidoc this *just works*. I only need to set :iconsdir: if I want to use my own icons.

**Comment by msc-** [comment]
I figured out that if I use `:icons: font` in the header asciidoctor will use characters from a font for the icons.

Perhaps this problem occurred because I had just `:icons:` in my document header, which tells asciidoc to use icons rather than text for callouts, etc. and unlike asciidoc, asciidoctor does not have a set of default icon images.

**Comment by mojavelinux** [comment]
> Perhaps this problem occurred because I had just `:icons:` in my document header, which tells asciidoc to use icons rather than text for callouts, etc. and unlike asciidoc, asciidoctor does not have a set of default icon images.

Precisely correct.
