### ISSUE TITLE
admonition icon/character not displayed

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1440]
I have 2 `NOTE:` admonitions in my document. Instead of a nice picture I get a black-bordered box containing the symbol used when a specified character is not found. 
![screen shot 2015-07-24 at 4 55 45 pm](https://cloud.githubusercontent.com/assets/2244683/8886782/1cb6bb60-3225-11e5-8dfe-ca48ae7ae66e.png)
 Do I have to download FontAwesome? If so, will readers of my document also need to do that?

I looked in the html5 source. There is no mention of FontAwesome. I can't see where it is selecting the font to use for `fa icon-`.

**Comment by mojavelinux** [comment]
FontAwesome should be loaded into the HTML output document automatically when you set `:icons: font`. However, you will also need to use the default Asciidoctor stylesheet, which contains some mappings from admonition icons to FontAwesome. You can also supply this mapping yourself by cutting out that part of the stylesheet and adding it to your own. You can see the SASS file that generates it here:

https://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/sass/components/_awesome-icons.scss

Here's the relevant bits from the default Asciidoctor stylesheet:

https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css#L348-L353

**Comment by msc-** [comment]
I am using the default Asciidoctor style sheet.

**Comment by msc-** [comment]
Ahhh! This happened because I am using Firefox with NoScript which was not allowing scripts from cloudfare.com to run. It seems a script from there is needed to get the font.

The odd thing is that NoScript did not tell me my document was trying to run these scripts. I only saw it when I visited a link to the Asciidoctor user manual and also saw the same problem. But that is a NoScript problem.

Sorry for the noise.

**Comment by mojavelinux** [comment]
Aha! I was going to say next that it seems like FontAwesome isn't
loading... which turned out to be the case.

You can load FontAwesome from a local folder. One way is to change the CDN
path:

:iconfont-cdn: path/to/fontawesome.css

You can also disable the remote font and it will default to a local
relative path.

:iconfont-remote!:

Look at the HTML source to see where it's pointing.
