### ISSUE TITLE
Expanded Links Won't Show in Block Titles

### ISSUE THREAD

**Issue by devunwired** [asciidoctor/asciidoctor#1442]
Block titles that include links generated from expanded macros do not render a link, but show the raw text instead.  For example, the following works as expected:

```asciidoc
.http://www.example.com/file.html[Table Title]
|===
…
|===
```

When built, the generated HTML has a link as the title. However, the following does not work:

```asciidoc
:base_url: http://www.example.com

.{base_url}/file.html[Table Title]
|===
…
|===
```

In the above case, the text is properly expanded, but the title for the block element is not a clickable link. Inserting that same text outside of a block title _does_ generate a proper link. The following also works as expected:

```asciidoc
:base_url: http://www.example.com

Visit a {base_url}/file.html[link to our site] for more information.
```

**Comment by mojavelinux** [comment]
This has to do with the fact that block attributes are not substituted by default (the block title is a block attribute under the covers). The value will get substituted eventually when displayed, but is dependent on the order of expansion. In this case, the order doesn't produce the result you expect.

To force expansion of the block title, use the explicit block attribute syntax and surround the value in single quotes.

```
:base_url: http://example.com

[title='{base_url}/file.html[Table Title]']
|===
|a
|===
```

Side note: I keep revisiting this syntax in my mind and I think that we should reverse the meaning of single quote and double quote enclosures. Like many programming languages, single quotes means to not interpolate and double quotes means to interpolate. That would have to be a change for 1.6.0.

**Comment by mojavelinux** [comment]
This is a duplicate of #1333, which is scheduled for 1.5.4 atm.

**Comment by devunwired** [comment]
Thanks for the sanity check. I was surprised because I was used to this working with `asciidoc.py` (I'm new to Asciidoctor), but I realized that the syntax I was using didn't match. What I typically did in the past was actually include a `link` macro:

```
:base_url: http://www.example.com

.link:{base_url}/file.html[Table Title]
```

Doing this works fine in Asciidoctor as well. Thanks for the alternate syntax option!

**Comment by mojavelinux** [comment]
:+1:
