### ISSUE TITLE
Support default toc position in embeddable HTML

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1443]
When converting to embeddable HTML (`header_footer: false`), defining the `toc` attribute on the document with no arguments (and no placement specified otherwise), the toc should appear directly below the document title to mimic the behavior of the standalone document (`header_footer: true`).

If the document title is not enable, it's reasonable to assume that the toc will not appear, again to align with the behavior of the standalone document.

**Comment by mojavelinux** [comment]
Making this change should help alleviate confusion about the use of the `toc` attribute. This is a minor departure from the behavior of the html5 backend in AsciiDoc Python, but a worthwhile one.

**Comment by mojavelinux** [comment]
I'm almost thinking that any placement not currently handled in embeddable HTML should result in the toc being placed in this position. That mimics the behavior of the standalone HTML document below the break point.

**Comment by Mogztter** [comment]
Nice!
