### ISSUE TITLE
Rename header_footer option to clarify its intent

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1444]
The `header_footer` option controls whether the converter outputs a standalone document (`document` converter method) or an embeddable document (`embedded` converter method). Not only is this distinction not clear from the name `header_footer`, the terms "header" and "footer" are overloaded, so it's really not clear what this option does for someone who doesn't read lots of mailinglist posts.

We should consider changing the name of this option to `embeddable` or similar so the real intent is clear. Of course, can can continue to support the old option for backwards compatibility reasons, though it will be considered deprecated (and may issue a deprecation warning). If both are specified, the new option will win out.

**Comment by jxxcarlson** [comment]
I’m all for it!

**Comment by obilodeau** [comment]
Is there an attribute to trigger the header_footer option? I couldn't find any.

**Comment by mojavelinux** [comment]
You mean from the asciidoctor CLI command? If so, it's `-s`.

**Comment by obilodeau** [comment]
I meant a document attribute like `:header_footer:`

**Comment by mojavelinux** [comment]
For me, that doesn't really make sense since whether to include the HTML framing / template around the body is really a concern of the converter, not something that the source dictates. The point of AsciiDoc is that it can produce the output that the converter needs, so it is up to the converter to decide what to make.

**Comment by mojavelinux** [comment]
I think it would be confusing if we reversed the boolean logic when introducing a new name. Therefore, I propose naming the attribute `:standalone`. I think that's quite clear because it builds on the meaning of the "standalone" attribute in the XML declaration, which serves the same purpose. A standalone document provides a complete shell (whereas an embeddable document must be enveloped in another document).

**Comment by mojavelinux** [comment]
Note that the existing option will continue to work as a deprecated alias.
