### ISSUE TITLE
Question about open blocks

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1446]
In asciidoctor-latex I have a style sheet "extras.css" that makes the definitions for
`.openblock.box` and `.openblock.capsule` (see below).  Then in the main text I can say

```
[box]
--
whatever
--
```

and 

```
[capsule]
--
whatever else
--
```

and get the desired output.  The only problem is that asciidoctor-latex (through asciidoctor itself)
issues warnings:

```
asciidoctor: WARNING: capsule.adoc: line 5: invalid style for open block: box
asciidoctor: WARNING: capsule.adoc: line 25: invalid style for open block: capsule
```

These seem to be harmless, though I'm not certain of this.  Do I need to somehow
register these blocks?  Hope this is permissible.  It is a wonderful way of customizing
the Asciidoctor environment for special needs.

```
/* BOX */

.openblock.box {
  margin-top:1em;
  margin-bottom: 1em;
  margin-left:3em;
  margin-right:4em;
  padding: 1em;
  font-size: 0.85em;
  background-color: #ddd;
}


/* CAPSULE */


.openblock.capsule {
  margin-left:10em;
  margin-bottom:2em;
  font-style:italic;
  font-size:0.85em;
}
```

**Comment by mojavelinux** [comment]
You need to add a period before the role name. Otherwise, you are creating a custom block, which doesn't seem to be your intent in this case.

```
[.box]
--
whatever
--
```

With the dot, it's a role (e.g., `role=box`). Without the dot, it's the block name (aka style).

**Comment by mojavelinux** [comment]
Did that clear things up?

**Comment by jxxcarlson** [comment]
Yes, thanks~

**Comment by mojavelinux** [comment]
:+1:
