### ISSUE TITLE
Feature Rq: optional built-in heading links in HTML output.

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor#1449]
[This page](http://www.hl7.org/fhir/allergyintolerance.html#resource), which is part of a set of standards in e-health published by HL7 provides an example of 'heading links' which are visible as small icons to the right of each heading. Here they use a somewhat ugly coloured globe but it could be anything.

Could a similar thing be generated in the Asciidoctor HTML output, with a suitable option turned on. People seem to like these links for passing references around easily (I know they are also in the TOC of the doc, but this makes it even easier).

![image](https://cloud.githubusercontent.com/assets/1481744/8962443/89bfe6fa-3612-11e5-92f4-d24fdf7e539c.png)

**Comment by mojavelinux** [comment]
Two flavors of heading links are already supported in Asciidoctor. See http://asciidoctor.org/docs/user-manual/#links

(Where the icon is placed is a concern of the stylesheet).

**Comment by wolandscat** [comment]
You guys are scary, you thought of everything! Very nice.

**Comment by mojavelinux** [comment]
We just bring the ideas of the community together. Lots of great minds have come through this way.

If there's something specific about the links that you think could be enhanced, feel free to follow-up with another issue.
