### ISSUE TITLE
cols="asciidoc,asciidoc" doesn't work

### ISSUE THREAD

**Issue by nwmcsween** [asciidoctor/asciidoctor#1452]
cols="asciidoc,asciidoc" produces 2 implicit cols styled with asciidoc within asciidoc, in asciidoctor it produces one unstyled col.

**Comment by mojavelinux** [comment]
Asciidoctor only implements the style abbreviation (e.g., `a`), not the full term (e.g., `asciidoc`). Therefore, you must type it as:

```
[cols="a,a"]
|===
|
****
sidebar
****

|
====
example
====
|===
```
