### ISSUE TITLE
Add support for reproducible builds

### ISSUE THREAD

**Issue by bk2204** [asciidoctor/asciidoctor#1453]
Asciidoctor should support building documents reproducibly. Debian is using this to allow people to prove that their builds actually were built from the specified source, and numerous organizations use rsync or other content-based transfer systems where data is only copied or downloaded if it is modified ($DAYJOB does this).

From what I can see of the code, the only real change that's required for this is to change the code that creates and emits date stamps. I'm thinking this could be controlled by a "reproducible" attribute, but I'm open to other ideas.

**Comment by mojavelinux** [comment]
Or you could just turn it off as it's an optional feature.

```
asciidoctor -a last-update-label! file.adoc
```

You can also feed it with a fixed time:

```
asciidoctor -a docdatetime='1970-01-01 00:00:00'
```

**Comment by mojavelinux** [comment]
If you are emitting a header, then you can turn off the revdate as well:

```
asciidoctor -a revdate file.adoc
```

In total, that would be:

```
asciidoctor -a last-update-label! -a revdate file.adoc
```

Oddly enough, `-a revdate!` doesn't work. You have to set it to blank. This seems like a bug.

**Comment by bk2204** [comment]
I was hoping that there would be an option that we could apply equally to converters such as asciidoctor-pdf, which embeds dates as well. Do you think that's a useful endeavor?

**Comment by mojavelinux** [comment]
I'm certainly no opposed to it, just wrapping my head around how to approach it. It's certainly nice to let the converters know that timestamps should be avoided, if possible, in the conversion. Something like `-a timestamps!`. I think the term "reproducible" is too vague here (and no guarantee that it is), but let me ponder it a bit.

**Comment by getreu** [comment]
Are in the tool-chains `adoc->pdf` or `adoc->html` other non-deterministic transformations then `timestamps`?

**Comment by mojavelinux** [comment]
I don't think so.

**Comment by bk2204** [comment]
I don't know about asciidoctor-pdf, but some PDF generators embed XMP metadata, which may contain variable data (usually timestamps, but it can be other stuff, too).  I'm hoping to have some time this weekend to make a pass through the main codebase and asciidoctor-pdf and implement this.

**Comment by mojavelinux** [comment]
Cool!

Now that you mention it, Asciidoctor PDF does include the current date/time in the PDF meta info.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L299

**Comment by mojavelinux** [comment]
There's also the version of Asciidoctor that gets inserted into the HTML head. I wonder if that should be dropped as well.

**Comment by mojavelinux** [comment]
We are missing a test for reproducible builds of the manpage output.

**Comment by mojavelinux** [comment]
Btw, thanks for your contribution and patience on getting this implemented @bk2204!

**Comment by mojavelinux** [comment]
For the sake of documentation, we decided to use the attribute named "reproducible" to control this behavior.

    $ asciidoctor -a reproducible file.adoc

**Comment by mojavelinux** [comment]
Debian is requesting support for the SOURCE_DATE_EPOCH environment variable.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820435

Should we honor that when the reproducible attribute is set?

**Comment by bk2204** [comment]
We can either honor it when reproducible is enabled, or always.  I think #1721 sets it to always be enabled. There are upsides to both approaches.
