### ISSUE TITLE
Issue when the last character in a table cell is an escaped pipe

### ISSUE THREAD

**Issue by kanecta** [asciidoctor/asciidoctor#1457]
Pipes need to be escaped within table cells.

They also need to be escaped within literal blocks inside table cells ([Issue-1421](https://github.com/asciidoctor/asciidoctor/issues/1421))

However when the last character in a table cell is an escaped pipe it causes the table or content to get corrupted.

*Example*

    |===
    | First cell
    | I'm cell content with an escaped pipe as the last character \|
    | Third cell
    |===

*Result*

These vary depending on a number of factors:

* In the example above the third cell content is pulled into the second cell and there is no third cell.
* If you wrap the content of the second cell in a literal block then the literal block 'markers' are pulled into the second cell, while the third cell remains.  ie second cell content is:

    ....I'm cell content with an escaped pipe as the last character |....

* If the second cell is the last cell in the table then the second cell disappears completely.
* I have not tested any other scenarios.....

*Environment*

    $ asciidoctor -v
    Asciidoctor 1.5.2 [http://asciidoctor.org]
    Runtime Environment (ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux])

*Hint for resolving*

Dan made the following comment in the original [Nabble comment](http://discuss.asciidoctor.org/Tables-get-mangled-when-there-is-a-pipe-character-inside-a-literal-block-within-a-table-cell-td3623.html) where I reported this issue:

*That looks like another bug. When it restores the pipe, it drops the endline and, as a result, the block doesn't render properly.*

**Comment by mojavelinux** [comment]
I have good news. This was addressed as part of the fix for #1306. The fix will be part of the 1.5.3 release.
