### ISSUE TITLE
Asciidoctor fails with asciidoctor style cells in tables with wrongly defined columns

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1460]
When a table only defines 2 columns, but makes Asciidoctor detect 3 columns and a cell in the third column uses an asciidoctor style rendering fails with:
```
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to parse AsciiDoc source, undefined method `table' for nil:NilClass
    at RUBY.initialize(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.3.dev/lib/asciidoctor/table.rb:224)
    at RUBY.close_cell(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.3.dev/lib/asciidoctor/table.rb:480)
    at org.jruby.RubyInteger.upto(org/jruby/RubyInteger.java:133)
```
This is because in https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/table.rb#L223 the column variable is `nil`.

I cannot tell whether Asciidoctor should better 
- fail with a clearer error message ("Fix your column specification!") or 
- should ignore the asciidoctor style and continue rendering (In case of accepting the asciidoctor style rendering will still fail in https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/table.rb#L226 because the Cell has the column(=nil) as parent and therefore `@document` is also nil.
- or should automatically add a column with default settings.

**Comment by mojavelinux** [comment]
Could you post the sample AsciiDoc content as well?

**Comment by robertpanzer** [comment]
Will do once I'm back at an ordinateur. 
But it should be sth like this:
```
[cols=","]
|===
|foo |bar a| another content
|===
```

**Comment by mojavelinux** [comment]
Thanks! That's what I was looking for. Just needed confirmation to make sure I was testing the right scenario.

**Comment by robertpanzer** [comment]
The example I mentioned before works.
I just retried.
The smallest example that fails taken from Sean's document is:
```
[cols=","]
|===
3+|D
|E
a|F

Still F
|===
```

Removing the `cols` attribute or the initial `3+|D` makes rendering pass again.

**Comment by mojavelinux** [comment]
I think I've got it sorted out with PR #1506. If a column can't be resolved when attempting to close a cell, skip the cell with a warning. The output of the table is still very likely to be empty or missing rows, but it's better than a crash.

Asciidoctor doesn't attempt to recover a broken table if the actual number of columns (as a result of cells with colspan and rowspan) differs from the colspec.

**Comment by mojavelinux** [comment]
To be more clear, I opted for "skip cell and warn". Adding a default column is not really possible with the current parsing code.
