### ISSUE TITLE
Upgrade icons to use Font Awesome 4.4.0

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1465]
Font Awesome is moving fast with 66 New Icons in 4.4 ! :smile:

**Comment by mojavelinux** [comment]
Moving fast indeed! We can measure the time between Asciidoctor releases in Font Awesome release numbers :)

Icon :candy: FTW!

**Comment by mojavelinux** [comment]
Here's a link to what's new: http://fortawesome.github.io/Font-Awesome/icons/#new

**Comment by mojavelinux** [comment]
The new creative commons icon should come in very handy for writers.
