### ISSUE TITLE
support snip-snap in source code including

### ISSUE THREAD

**Issue by skycaptain** [asciidoctor/asciidoctor#1469]
Asciidoctor provides a mechanism to include source files:

```asciidoc
[source,ruby]
----
include::app.rb[]
----
```

It also allows the selection by line numbers:

```asciidoc
[source,ruby,indent=0]
----
include::lib/document.rb[lines=5..10]
----
```

This attempt is reasonable, since it does not require the change of the source file. But source code can change rapidly, so do line numbers. Changing everything manually is cumbersome. Therefore, I'm suggesting to implement snip-snap comments. E.g. a Python-file might look like this:
```python
do_something()
# asciidoctor_snip
do_something_two()
# asciidoctor_snap
do_something_three()
```

And the asciidoc might look like:
```asciidoc
[source,python,indent=0]
----
include::code.py[snip=0]
----
```
where 0 indicates the first snip-snap occurrence. Named snip-snaps might also be allowed:

```python
do_something()
# asciidoctor_snip:do_something_two
do_something_two()
# asciidoctor_snap:do_something_two
do_something_three()
```

```asciidoc
[source,python,indent=0]
----
include::code.py[snip='do_something_two']
----
```

Even nested or overlapping snip-snaps might be possible:

```python
do_something()
# asciidoctor_snip:do_something_two_three
do_something_two()
# asciidoctor_snip:do_something_three_four
do_something_three()
# asciidoctor_snap:do_something_two_three
do_something_four()
# asciidoctor_snap:do_something_three_four
```

If one would not like to annotate the source code with comments, one would be able to add a FILE.ext.snipsnap next to FILE.ext, which translates the corresponding line numbers. The snip-snap comment lines will always be hidden in the output. To be more bullet-proof, one would have to match against the comment literals as well. The most common literals can be found at http://rigaux.org/language-study/syntax-across-languages/Vrs.html#VrsCmmnt

 I'll try to provide a pull-request in the near-future to see if this feature is useful.

**Comment by robertpanzer** [comment]
I think what you mean can already be achieved with tags:

```
include::code.py[tags=do_something_one]
```

```python
do_something()
#tag:: do_something_one[]
do_something_else()
#end:: do_something_one[]
```

This is also explained in the user manual: http://asciidoctor.org/docs/user-manual/#by-tagged-regions

**Comment by skycaptain** [comment]
Thank you. I'm sorry, I've totally missed that. I'm closing this issue, for obvious reasons.

**Comment by abelsromero** [comment]
> Thank you. I'm sorry, I've totally missed that. I'm closing this issue, for obvious reasons.

Not so obvious, I never though of those nestes and overlapped cases and just tested them with this (it's Java):

public class StringUtils {
    // tag::contains-over[]
    // tag::contains[]
    public boolean contains(String haystack, String needle) {
        // tag::contains-in[]
        System.out.println("hello hystack")
        // end::contains-over[]
        // end::contains-in[]
        return haystack.contains(needle);
    }
    // end::contains[]
}

Everything works btw.

**Comment by skycaptain** [comment]
Thank you. I'm glad we've tested this out now.
