### ISSUE TITLE
"list continuation" does not work with callout lists

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor#1478]
I have in a document

```
<1> This is the first paragraph of the description of callout number 1. The
       paragraph continues for a couple of lines but this is enough for an example.
+
This is the second paragraph.
+
This is the third paragraph.

<2> This is the second callout.
```

This works perfectly with Asciidoc as a list continuation. That is, callout <1> has three paragraphs all properly indented and then we see callout <2>. In Asciidoctor the second and third paragraphs are completely missing from the output document. No error or warning is emitted by Asciidoctor.

I am using the html5 backend in both cases.

Is there any fix or workaround?

**Comment by mojavelinux** [comment]
That is correct. Callout lists only consists of simple list items. That's a core assumption in AsciiDoc (and I think DocBook too).

One workaround is to make the callout list a custom block. But a better workaround is to get the fix for #1077 done, which is probably what you really want here.

**Comment by msc-** [comment]
> That's a core assumption in AsciiDoc

But it works in Asciidoc, which is why it is in my document in the first place.

I think #1077 is indeed a useful feature but I think I would still need callout lists with continuation paragraphs.

I will have a look at custom blocks.

**Comment by mojavelinux** [comment]
> But it works in Asciidoc, which is why it is in my document in the first place.

I can confirm that. I vaguely remember making the decision not to support that case, though I don't exactly remember my reasoning.

> I will have a look at custom blocks.

On second thought, I'm not sure that's the direction I recommend. If you're going to touch the source, I'd recommend just trying to get rid of the extra paragraphs. Do the callout list items really need to be that long? Perhaps it's better to move the content into paragraphs, which is why I suggest looking at the fix for #1077. Btw, you could implement #1077 as a custom inline macro (or postprocessor) in the interim. It's just a matter of looking for the callout numbers and replacing them.

Another approach is to use a numbered list, give it a unique role and that use CSS to replace the numbers with callout symbols. That's probably the quickest fix in the short term. In fact, you could get away with a regular numbered list and it would still be understandable to the user.

(At this point, it's going to be hard to go back and add complex content for callout lists because it would ripple through a lot of parts of Asciidoctor).

**Comment by msc-** [comment]
I am a complete neophyte when it comes to Ruby so I am not going to touch the source.

The regular numbered list with a unique role is a good idea. How to you make CSS replace the numbers with callout symbols?

One of the reasons for wanting  a continuation is so I can append an admonition, specifically NOTE:, to a callout item. I can do it at the end of the callout list obviously but then it is slightly out of context. The regular numbered list works for this too.

**Comment by mojavelinux** [comment]
> How to you make CSS replace the numbers with callout symbols?

See something like http://blog.teamtreehouse.com/customize-ordered-lists-pseudo-element

> One of the reasons for wanting a continuation is so I can append an admonition, specifically NOTE:, to a callout item.

Of course, you are free to write your document however you want, but I strongly recommend against using admonitions in a callout list item. I think it over-complicates the structure and does not make for a good reading experience. If that's happening, I think time is better spent trying to figure out why a clarification needs a clarification. (It's akin to a sidebar inside of a sidebar.)

**Comment by msc-** [comment]
I see your point but I am using the callouts in a source code listing so the callout list items are explanations of what the code is accomplishing, rather than straightforward clarifications. For example

```<1> The triangle is parameterized using barycentric coordinates so the
    shader first computes basis vectors for each attribute. Because the
    incoming triangles have counter-clockwise winding, it uses the last
    vertex as the origin.
+
NOTE: Since the geometry is planar in this app, the shader does not need
      to compute a basis vector for the normal but it does so in case
      it will be used with other geometry.

<2> Explanation of a another part of the code.

<3> Explanation of still another.
```

Thanks for the blog pointer.

**Comment by mojavelinux** [comment]
I just don't think that callout lists should have complex content. To me, it's not that far from a footnote within a footnote. A callout list item is already an explanation. Adding an explanation to the explanation is a sure sign (to me at least) that the structure of the content needs to be rethought.

On the other hand, I do see the need to be able to reference a callout number from an arbitrary block of text, which is covered in #1077. I think that's a reasonable compromise for this requirement.

**Comment by janicecmt** [comment]
I am primarily using callouts to discuss the allowed values of variables used in what are essentially syntax blocks. I do think it's useful to be able to add an example line to a callout in more complex cases. For instance, do something like this:

```
[source,JSON]
----
{
  "key1": "value1", <1>
  "key2": "value2"
}
----
<1> Foo. For instance, value1 might look like this:
+
[source,JSON]
----
"key1": "zyxwvuts...",
----
```

Right now, the content after the + is just silently omitted from the output. If it can't be handled then I would prefer an error. It's too easy to not notice that it didn't render as expected and move on thinking it worked.

Right now I am including the code without the line continuation and artificially adding spaces to the beginning so it lines up to the callout text. It's not quite correct as the code background still extends to the left, but it's better than the alternatives I tried:

```
[source,JSON]
----
{
  "key1": "value1", <1>
  "key2": "value2"
}
----
<1> Foo. For instance, value1 might look like this:

[source,JSON]
----
   "key1": "zyxwvuts...",
----
```

**Comment by mojavelinux** [comment]
> Right now, the content after the + is just silently omitted from the output.

Eek. That's not good. Hmm. Since we have to do something with the content, we might as well go ahead and allow complex content to be attached to the list item.

I'll go ahead and schedule this.

**Comment by mojavelinux** [comment]
As it turns out, this actually works in the DocBook converter, so we actually parse and store the complex content. It's just not output by the HTML converter. I can't believe it was that simple all along. I'll see about getting this fixed.

**Comment by mojavelinux** [comment]
@msc- Thanks for reporting! Sorry it took me so long to figure out what was going on.

**Comment by Mogztter** [comment]
This is awesome! :+1: 
I always wanted to use this syntax but I didn't know it was a :bug:

**Comment by rmannibucau** [comment]
Hi, seems this issue is not solved if there is a source or block in between callouts (it is bad but it happens ;))

**Comment by mojavelinux** [comment]
I don't want to encourage that behavior.

**Comment by rmannibucau** [comment]
@mojavelinux it would at least require an ERROR but silently swallowing it and misbehaving is the worse potential way to treat it IMHO.

**Comment by mojavelinux** [comment]
Without an example, I can't comment further. As far as I can see, it no longer swallows anything in the case cited in this issue.

**Comment by rmannibucau** [comment]
<1> blabla
    blabla
    
    blabla : `[scheme]://[authority][?version][&configuration]`
    
    * *a*: aaaa
    * *b*: bbbb 
    
    [source]
    -----
      ....
    ----
    foo: bar
    
    IMPORTANT: something
    
    <2> blabla
    
     blabla.
    
     blabla.
    
    <3> blabla:
    
    * blabla
    * blabla
    
     <4> blabla


Here this sequence show 4 x a "1" callout instead of just recognizing it is all part of the same one.

**Comment by mojavelinux** [comment]
That's a perfectly valid AsciiDoc document (if you include the listing block before it). It's just not what you might want. You are missing list continuations. The processor is not a validator. It's not going to look ahead and try to see patterns that you meant to do but didn't.

**Comment by rmannibucau** [comment]
Having <2> rendered as 1. is still a bug Dan and does worth an ERROR at least.

**Comment by mojavelinux** [comment]
Actually, the reason you are not getting any warnings is because your listing block is not closed. If the listing block is closed properly, then you'll get lots of warnings.

So what you're really talking about here is https://github.com/asciidoctor/asciidoctor/issues/1133

**Comment by rmannibucau** [comment]
Oops, it is a github typo, the source was ok.
