### ISSUE TITLE
Need help with HTML template

### ISSUE THREAD

**Issue by mstanleyjones** [asciidoctor/asciidoctor#1480]
I need to be able to modify the HTML template to put a navigation element in before the book title. I've already tried putting the navigation in via docinfo, and using positioning to tweak things around, but it's too hard. I've found lots of info on creating CSS templates, but I don't know where to start with the HTML template.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor.org/issues/80. Formal documentation is still needed, but that should at least provide a starting point.
