### ISSUE TITLE
[PDF] Allow to embed an image in base64

### ISSUE THREAD

**Issue by flarcher** [asciidoctor/asciidoctor#1481]
Hello, 

I would like to insert an image in the generated PDF having the Blob in the _base64_ format. 
This is related with the closed issue #986 ( I would like to do the same with the PDF backend ).

I tried to add
```
image::data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==[]
```
in the document and I got in the logs the following line :
```
asciidoctor: WARNING: image to embed not found or not readable: data:image/png;base64,iVBOR...
```
Here is the command returned by the logs :
```
asciidoctor -B /home/fabrice/tmp -S SAFE -o /home/fabrice/tmp/test.pdf -b pdf -a docdate=2015-09-10 -a data-uri -a allow-uri-read -a doctime=11:34:51 CEST -a icons=font -
```

I am using `org.asciidoctor:asciidoctorj:1.5.2` and `org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.9`. 
Is there a workaround ? Or is it planed for a coming release ?
Many thanks

**Comment by flarcher** [comment]
I moved the issue to https://github.com/asciidoctor/asciidoctor-pdf/issues/318 because it is probably more related to that project.

**Comment by mojavelinux** [comment]
Thanks! We'll address it there.
