### ISSUE TITLE
Commas in index entries

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor#1486]
It is sometimes the case that an index entry has an "internal comma".  This cannot be handled by the 
current scheme because commas are used to parse the index markings.  For example, suppose we 
want to make the index entry `(((Carlos Machado Quintela, Cuban film)))`.  It will appear as

```
Cuban film
  Carlos Machado Quintela
```

But we want it to appear as

```
Cuban film
  Machado Quintela, Carlos
```

One solution would be to use semicolons as language elements,
so that one writes

```
    (((Machado Quintela, Carlos; Cuban film)))
```

But this goes against the current syntax.  Do you see a good solution to this problem?
One that film programmers would iike:-)!

For an example, see [Mockup film guide](https://vschool.s3.amazonaws.com/manuscripts/468.html).

**Comment by eskwayrd** [comment]
I think your example may have certain aspects backwards, and it doesn't contain an extra comma.

However, you can use double quotes around each term:

    (((("Cuban Film", "Machado Quintela, Carlos")))

which renders within the index as:

    Cuban Film
      Machado Quintela, Carlos
    Machado Quintela, Carlos

Note that the duplication of the secondary term is related to the issue I recently filed; this may not be a problem for you:
https://github.com/asciidoctor/asciidoctor/issues/1487

**Comment by jxxcarlson** [comment]
@mojavelinux I am starting to rework my code for generating an index for an Asciidoc document.  Is it a bad idea to use strings as inputs and outputs?  This is what I generally do in Noteshare, since the source "files" are really entries in a database.  So the question is really about maximium size of strings vis a vis the OS and Asciidoctor.

**Comment by mojavelinux** [comment]
>  is there a better place to post this?

discuss.asciidoctor.org is the place for general discussions.

Btw, does @eskwayrd's response answer your question for $subject?

**Comment by mojavelinux** [comment]
I believe that the response provided by @eskwayrd answers this question. I also documented it in the user manual (see http://asciidoctor.org/docs/user-manual/#user-index). I'm going to close this issue now. Reopen if you need further assistance.
