### ISSUE TITLE
Setting docdate and doctime attributes from the API

### ISSUE THREAD

**Issue by davebaldwin** [asciidoctor/asciidoctor#1495]
docdate and doctime are currently set from the root adoc file.  There is an open issue to extend this to set these attributes from the most recent included file as well, however this doesn't cope with the case where content is being inserted via the API or an extension such as from a database or web service.  The simple solution is to allow docdate and doctime to be overridden by any passed in via the API.

This can simply be done by changing (in asciidoctor.rb)

attributes['docdate'] = docdate = input_mtime.strftime('%Y-%m-%d')
attributes['doctime'] = doctime = input_mtime.strftime('%H:%M:%S %Z')

to

attributes['docdate'] ||= input_mtime.strftime('%Y-%m-%d')
attributes['doctime'] ||= input_mtime.strftime('%H:%M:%S %Z')
docdate = attributes['docdate']
doctime = attributes['doctime']

The only other thing to consider is if it should be changeable from within the root document itself via the normal attribute setting mechanism.

Dave.

**Comment by mojavelinux** [comment]
I think for now we should leave it as something that is controlled via the API. I don't think that the document should be aware of its own doc date/time. That's what the revdate / revision info is for.

**Comment by mojavelinux** [comment]
Want to try a PR? I'll help you through it, but having one helps me prioritize the work.

**Comment by davebaldwin** [comment]
PR?

Dave.

**Comment by mojavelinux** [comment]
Sorry for the lingo. A pull request (aka patch)
