### ISSUE TITLE
Alternative images (TIF/PNG)

### ISSUE THREAD

**Issue by mfitzp** [asciidoctor/asciidoctor#1513]
I'm generating a book in both HTML and PDF format and would like to be able to use high resolution TIF images in the PDF. However, using TIF for the web version doesn't work (not supported, e.g. in Firefox or Chrome).

At the moment I'm generating two versions of the file (PNG/TIF) then post-processing the html output to replace all `.tif` references to `.png` but that feels a bit hacky. Is there a nicer solution?

**Comment by mojavelinux** [comment]
You have the right idea with postprocessing, though I'd recommend using a TreeProcessor. The only downside of TreeProcessor is that it only catches the block-level images...but likely those are the ones that are TIF files.

Here's a TreeProcessor example: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/shell-session-treeprocessor/extension.rb

**Comment by mojavelinux** [comment]
Oh, there is another way that you can address this at the source. Simply set an attribute based on the backend for the extension (for when you have a image set).

```
ifdef::backend-pdf[:hires-image-ext: .tif]
ifndef::backend-pdf[:hires-image-ext: .png]
```

Then use:

```
image::figure-1{hires-image-ext}[Figure 1]
```

Hopefully that gives you some ideas.

**Comment by mfitzp** [comment]
@mojavelinux That's perfect, thanks! The tree processing will probably come in handy for a few other things too. Much appreciated.

**Comment by mfitzp** [comment]
Just an update for others having the same idea —

So the extension-replacement works great! But unfortunately it doesn't seem to be possible to embed `.tif` files in the pdf giving error `WARNING: could not embed image: image file is an unrecognised format`. According to [the Prawn homepage](http://prawnpdf.org/api-docs/2.0/) it supports PNG and JPG (only?). 

I did wonder about a round-trip via latex but then [TIF isn't supported by pdflatex](http://tex.stackexchange.com/questions/1072/which-graphics-formats-can-be-included-in-documents-processed-by-latex-or-pdflat) and the definition in [preamble_article.txt](https://github.com/asciidoctor/asciidoctor-latex/blob/master/data/preamble_article.tex) looks like it only supports the same file types?:

    \usepackage{graphicx}
    \usepackage{wrapfig}
    \graphicspath{ {images/} }
    \DeclareGraphicsExtensions{.png, .jpg, jpeg, .pdf}

I also tried PDF but that results in the images being inserted as distinct pages.

I'll have a look whether hi-res (aka big) PNGs works well enough for printing.

**Comment by mojavelinux** [comment]
I see that iText supports TIF files, so in theory it should be possible to
get them working in Prawn. You'd have to file an issue upstream in Prawn.

Out of curiosity, does it work if you use AsciiDoc->DocBook->PDF (fop)? In
that case, you'd use backend-docbook.

**Comment by mojavelinux** [comment]
From that thread, it sounds to me like if you install prawn-gmagick, it should just start working with TIF images. I haven't tried it, though. If so, then we can also reevaluate the fast-fail that we have on GIF images.

**Comment by mojavelinux** [comment]
Prawn now supports all image types if you have the [prawn-gmagick](https://github.com/packetmonkey/prawn-gmagick) gem installed. This feature will be enabled in alpha.14.
