### ISSUE TITLE
Unable to add inline roles to parts of image title (at least in DocBook backend)

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1515]
This:

```
[.some_custom_blockrole]
image::image.png[ This is sample [.my_in_red]#title# .]
```

only translates the quoted text inside the title but not the image iteself:

``` xml
<simpara role="some_custom_blockrole">
image::image.png[This is sample <phrase role="myredtext">title</phrase>].
</simpara>
```

**Comment by shahryareiv** [comment]
The same can happen if any character follows the closing bracket of the image (needs opening a new issue?)

**Comment by mojavelinux** [comment]
You are attempting to add formatting to alt text. Alt text is not designed for formatting. If you want to add formatting to the title of an image, you can do that using the following:

```
.This is a sample [.my_in_red]#title#.
[.some_custom_blockrole]
image::image.png[Alt Text]
```

**Comment by shahryareiv** [comment]
Thanks for clarification! But still the second problem (or by design?) remains. This:
```
[.some_custom_blockrole]
image::image.png[] some extra text happened to be here
```
converts to:
```
<simpara role="some_custom_blockrole">
image::image[] some extra text happened to be here
</simpara>
```
Probably the back-end might consider some default role for the extra text after block image instead of breaking.

**Comment by shahryareiv** [comment]
Also the same problme if we do this:

```
[.some_custom_blockrole]
image::image.png[ title="This is sample [.my_in_red]#title# ."]
```
or

```
[.some_custom_blockrole]
image::image.png[ title=This is sample [.my_in_red]#title# .]
```
or
```
[.some_custom_blockrole]
image::image.png[ title='This is sample [.my_in_red]#title# .']
```
Here is also good if there would be a default conversion without breaking the image itself.
Also the interpolation for single quotes matches other similar cases
https://github.com/asciidoctor/asciidoctor/issues/1381

**Comment by mojavelinux** [comment]
This:

```
[.some_custom_blockrole]
image::image.png[] some extra text happened to be here
```

is not a block image because the image is inline with other text. You must write it with a single colon to make it an inline image.

```
image:image.png[role=some_custom_role] some extra text happened to be here
```

**Comment by mojavelinux** [comment]
If you are going to format the title of a block image, I strongly recommend using a dedicated title line as I proposed above:

```
.This is a sample [.my_in_red]#title#.
[.some_custom_blockrole]
image::image.png[Alt Text]
```

However, if it's really important to you that you define it inline, then you need to escape the closing square bracket inside title attribute's value:

```
[.some_custom_blockrole]
image::image.png[title='This is sample [.my_in_red\]#title#.']
```

This is true anytime you use syntax that has square brackets inside an attribute value.

(Btw, you can use either single or double quotes around the attribute value in this case and get the same results).

**Comment by shahryareiv** [comment]
Thanks for the information! Actually I fixed my problem with using the dedicated title (As you recommended). My later suggestion was that rendering should not break because of a simple mistake like this, this can probably negate the philosophy of Asciidoctor. My real world case was just a dot mistakenly put after an image block, hard to be found in a long text or to debug in a multi-level toolchain. A warning plus some graceful degradation (such as considering the extra text as a separate text block)  might be a better choice.

**Comment by mojavelinux** [comment]
Great to hear! And thanks for the suggestion. Validation is important to us in Asciidoctor, though my philosophy is that it should be a separate tool. The goal of the main Asciidoctor processor is to convert documents as fast as possible. There's a ton of stuff we could stop and check and that would slow down all the cases when the document is already ready to go. What I envision is a validation tool (ideally part of an IDE) that picks apart the document and looks for invalid syntax. Then, it can take all the time it needs.

**Comment by mojavelinux** [comment]
...I also say that because there are actually few cases where the syntax is truly invalid. What looks like a block macro with trailing content to one person might be valid content that shouldn't be interpreted as an AsciiDoc construct to another. Content is very loose like that (unlike programming languages). That's why it's critical that the tool help guide the author, but not get in the way.

**Comment by mojavelinux** [comment]
> This is true anytime you use syntax that has square brackets inside an attribute value.

For the record, it's no longer required to escape square brackets in text of a block macro. That's because we already know it's a single line, so we can assume only the closing bracket at the end of the line matters.

```
[.some_custom_blockrole]
image::image.png[title='This is sample [.my_in_red]#title#.']
```

Since this issue was about clarifying the syntax, I'm going to mark it as resolved.
