### ISSUE TITLE
Allow the option to exclude tags when using the include directive

### ISSUE THREAD

**Issue by kito99** [asciidoctor/asciidoctor#1516]
Sometimes you want to include parts of a document, but exclude other parts (child tags). I'd like to see something like this:

include::presentation.asc[tag=content,exclude-tag=demo1]

or:

include::presentation.asc[tag=content,exclude-tags=demo1;demo4]

**Comment by mojavelinux** [comment]
I like the idea, but I'd like to propose an alternative syntax. Following how we markup substitutions, we'd prefix the exclusions with a negative sign.

```
include::presentation.asc[tags=content;-demo1]
```

This would be very straightforward to implement since we already detect the inner tagged regions (in order to discard the directives).

**Comment by kito99** [comment]
Makes sense to me. How would you handle multiple exclusions?

**Comment by mojavelinux** [comment]
```
include::presentation.asc[tags=content;-demo1;-demo2]
```

**Comment by kito99** [comment]
Cool.

**Comment by mojavelinux** [comment]
The more I use the include for source content, the more I'm finding I need this granularity of control. I've moved this up in priority.

**Comment by mojavelinux** [comment]
Keep in mind that this can be implemented today using an include processor. All we're talking about here is making this a built-in feature.

**Comment by mojavelinux** [comment]
The way this is done currently is to turn on and off the tags as you go down the file.

You markup the source as:

```java
//tag::initial[]
package com.tomitribe.training.cdi.named;

import javax.enterprise.context.Dependent;
import javax.inject.Named;

//end::initial[]
@Named("X")
//tag::initial[]
@Dependent
public class TheBeanCalledX {
    private String mission = "Save the world";

    public String getMission() {
        return mission;
    }
//end::initial[]

    //tag::setter[]
    public void setMission(String mission) {
        this.mission = mission;
    }
    //end::setter[]
//tag::initial[]
}
//end::initial[]
```

Then in the AsciiDoc

```
include::TheBeanCalledX.java[tag=initial]
```

This is far from ideal, but it works for now.

**Comment by mojavelinux** [comment]
I believe we'll want to allow a `*` exclude so that you can easily handle cases when you don't know what tags are inside for the tag you are including, but you want to exclude all of them.

**Comment by mojavelinux** [comment]
I decided to use `!` instead of `-` as the negate prefix. Also, if you only negate, then it will select all lines except for the specified tags.

We can now rewrite the sample code from above as:

```java
package com.tomitribe.training.cdi.named;

import javax.enterprise.context.Dependent;
import javax.inject.Named;

//tag::named-x[]
@Named("X")
//end::named-x[]
@Dependent
public class TheBeanCalledX {
    private String mission = "Save the world";

    public String getMission() {
        return mission;
    }

    //tag::setter[]
    public void setMission(String mission) {
        this.mission = mission;
    }
    //end::setter[]
}
```

To include all lines except for the tagged regions, use:

```
include::ABeanCalledX.java[tags=!named-x;!setter]
```

or simply:

```
include::ABeanCalledX.java[tags=!*]
```

This also works with nested tags.

**Comment by mojavelinux** [comment]
I introduced a double asterisk wildcard if you want to include lines that are not tagged.

```
include::TheBeanCalledX.java[tags=**]
```

which is shorthand for:

```
include::TheBeanCalledX.java[tags=**;*]
```

But now you can turn and and off tags independent of selecting non-tagged lines:

```
include::TheBeanCalledX.java[tags=**;named;!*]
```

The double asterisk is implied when you are only excluding tags (since you have to have something to exclude from). Thus, the following syntax:

```
include::TheBeanCalledX.java[tags=!named]
```

is shorthand for:

```
include::TheBeanCalledX.java[tags=**;!named]
```
