### ISSUE TITLE
Question about using Font Awesome admonition icons

### ISSUE THREAD

**Issue by SandMann1** [asciidoctor/asciidoctor#1535]
I have set the ":icons: font" attribute in my adoc file, and created my .css with the ascidoctor styling factory. I notice that my xhtml output gets an ekstra link in the ```<head>``` segment:
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css"/>
```
Is there a reason why this is included in the html output and not as 
```css
@import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css)
```
in the _font-awesome.scss related to the styling factory?

I am asking as I am looking for the simplest way to make the admonition icons visible in my documentation when on a intranet without online access.

**Comment by Mogztter** [comment]
> I am asking as I am looking for the simplest way to make the admonition icons visible in my documentation when on a intranet without online access.

You can load Font Awesome from a local file with `:iconfont-remote!:` (see [html5.rb#L73](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L73)). If `stylesdir` is undefined, this will create the following `<link>`:
```html
<link rel="stylesheet" href="./font-awesome.css"/>
```

> Is there a reason why this is included in the html output

I think the reason is that we don't want to import Font Awesome when `:icons: font` is not set.

**Comment by mojavelinux** [comment]
> I think the reason is that we don't want to import Font Awesome when :icons: font is not set.

Precisely. This gives us control to turn and an off the stylesheet import and to control the URL.

**Comment by mojavelinux** [comment]
There's an open pull request to the user manual to add this information. However, the details are still being sorted out. https://github.com/asciidoctor/asciidoctor.org/pull/415

**Comment by SandMann1** [comment]
@Mogztter @mojavelinux  Thanks! This is great. Asciidoctor and font-awesome is awesome!

**Comment by mojavelinux** [comment]
:+1:
