### ISSUE TITLE
Links inside codeblocks?

### ISSUE THREAD

**Issue by jasonkuhrt** [asciidoctor/asciidoctor#1555]
Is this possible?

I've tried e.g. this without success:

```adoc
[source, haskell, subs="macros"]
DeviceSpec -> Device
            | link:https://github.com/foo/bar[ErrorDeviceAlreadyOwned]
            | ErrorAlreadyDeviceOwner
```

**Comment by mojavelinux** [comment]
Indeed. Except you'll want to use the incremental subs feature:

```
[source,haskell,subs=macros+]
----
DeviceSpec -> Device
            | https://github.com/foo/bar[ErrorDeviceAlreadyOwned]
            | ErrorAlreadyDeviceOwner
----
```

NOTE: You don't need the `link:` prefix in this case.

For more details, see http://asciidoctor.org/docs/user-manual/#applying-substitutions

**Comment by jasonkuhrt** [comment]
@mojavelinux Hm, maybe this is a Github limitation but here is the result I got which is not what I want:

Source:

<img width="350" alt="screen shot 2015-10-28 at 8 17 55 pm" src="https://cloud.githubusercontent.com/assets/284476/10806975/1faba92a-7db1-11e5-9d82-c141ca3e926e.png">

Render:

<img width="407" alt="screen shot 2015-10-28 at 8 17 29 pm" src="https://cloud.githubusercontent.com/assets/284476/10806979/286690de-7db1-11e5-953e-292756cd171f.png">

**Comment by mojavelinux** [comment]
First, I had the incremental subs backwards. You actually need to do the macro substitution last (the plus at the beginning). But even with that change, this is one of the cases where the rendering pipeline on GitHub mangles the result. You can see that if you run Asciidoctor locally or using the browser extension that the link appears.

Sample file: https://gist.github.com/mojavelinux/e07418b232eac10e0fe8

**Comment by mojavelinux** [comment]
Combining links with syntax highlighting is naturally a very fragile operation. One way to get around this problem is to use a passthrough around the link so that the syntax highlighter has less chance of getting confused (which I added to the gist), but there are still edge cases.

**Comment by jasonkuhrt** [comment]
@mojavelinux Hm, I must be missing something because in your example gist, and my Chrome AsciiDoc extension, and in my Atom Editor AsciiDoc preview, none are producing a clickable link in the codeblock. Do you see otherwise?

**Comment by mojavelinux** [comment]
Yep:

![link](https://cloud.githubusercontent.com/assets/79351/10807243/02e2ffea-7da3-11e5-8f32-bad2038680a6.png)

**Comment by jasonkuhrt** [comment]
Ah! After updating my Chrome extension, mine is just like your screenshot now. Thanks for putting that up. Was confused for a bit there.

Alas this does _not_ work in Github correct? Any recourse here or should the community accept this fact for the foreseeable future?

**Comment by jasonkuhrt** [comment]
Oh, maybe never mind as I guess this _will_ work after Github updates to `1.5.3`.

**Comment by mojavelinux** [comment]
> I guess this will work after Github updates to 1.5.3.

Actually, not in this case. The problem is that GitHub performs syntax highlighting in a post-processing step and the syntax highlighter seems to escape or mangle the links within the source code. So this is a general GitHub "bug" (or feature) and would also affect Markdown output. It may be something that needs to be filed in github/markup (or jch/html-pipeline). You can confirm this by taking away the `source,haskell` part and see that links do work. I've updated the gitst to show this.

**Comment by jasonkuhrt** [comment]
Ah I see. Do you have any pull with the GitHub team here? It's a cool feature for some important code documentation features.

**Comment by mojavelinux** [comment]
If I say yes, I would jinx it. So let's just say that on good days we have a good relationship :)

It appears the problem is with Pygments. When it receives code with a link in it, it escapes those links. In order words, I'm not sure it's even possible to have links and syntax highlighting at the same time. The reason this is possible in Asciidoctor is because we are syntax highlighting first, then converting the links. The only way we could do this on GitHub is if we moved the syntax highlighting into the Asciidoctor pipeline. I'm not sure that GitHub will allow us to do that though (it was hard enough just to get syntax highlighting at all, on their terms, after Asciidoctor runs).

**Comment by mojavelinux** [comment]
But I view the rendering on GitHub as a reasonable preview, not high fidelity output. I've come to this believe based on where GitHub is willing to meet us. That's the half way point. It's not their passion to have perfect rendering. I'll continue to do what I can do in Asciidoctor to make that the best output we can get, but it's never (or not likely) going to be final product quality. Another way to think of it is that it's good enough to manage edits, but not what end users would read. For that, you publish using your own tools (e.g., a static site generator).

**Comment by jasonkuhrt** [comment]
Fair response! Thanks for clarifying. I think a paraphrase of what you have written here would be a good addition to content for https://github.com/asciidoctor/asciidoctor.org/issues/419.

**Comment by jasonkuhrt** [comment]
I guess we should close this issue then?

**Comment by jasonkuhrt** [comment]
Oh I just realized that your updated gist https://gist.github.com/mojavelinux/e07418b232eac10e0fe8 now with an example of highlighting disabled does permit the links to function in a `pre` context which is better than nothing!

This entire gist would be useful as part of a "Asciidoc Cookbook" kind of manual IMO.

**Comment by mojavelinux** [comment]
Since we have another issue tracking the documentation, I think we can close.

Btw, one way to handle this so that you don't lose source highlighting in the production version is something like:

```
ifndef::env-github[[source,haskell]]
```

Another way is to use an attribute:

```
ifdef::env-github[:source-style: listing]
ifndef::env-github[:source-style: source]

...

[{source-style},haskell]
----
code goes here
----
```

**Comment by mojavelinux** [comment]
The `env-github` attribute is very powerful :)

**Comment by jxxcarlson** [comment]
Cookbook: great idea!!
