### ISSUE TITLE
A way to reset a counter

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1559]
It seems that `{counter:index:5}` only initialize the counter but rerunning that does not reset the counter. This can be needed for example to keep the number for figures in each chapter of a book and reset the counter at the begining of each chapter.

**Comment by mojavelinux** [comment]
That's correct. The `{counter:name:start}` syntax is only for initializing the counter. You can change the value using a document-level attribute entry:

```
Initialize index as {counter:index:5}.

:index: 9

{counter:index} == 10
```

Perhaps we should make this a docs issue?

**Comment by jaredmorgs** [comment]
http://asciidoctor.org/docs/user-manual/#counter-attributes describes this attribute, but there seems to be some specific requirements documented above that are worth noting. I'm going to clone and reference this in .org for comment.

**Comment by ahus1** [comment]
The cloned issue https://github.com/asciidoctor/asciidoctor.org/issues/550 is now closed. 

The documentation now contains a description on how to reset a counter followed by an example: "To reset a counter attribute, unset the corresponding attribute using an attribute entry. The attribute entry must be adjacent to a block or else it is ignored."

Therefore it seems to me that this issue can be closed?

**Comment by mojavelinux** [comment]
I agree. Thanks for following up @ahus1!
