### ISSUE TITLE
Disable table numbering

### ISSUE THREAD

**Issue by Svish** [asciidoctor/asciidoctor#1563]
I have a bunch of these tables in my document. When rendered the "Input Parameters" headings/labels are all prefixed with "Table N. ". How can I disable this text being added to the output? Tried looking in the documentation and googling, but can't seem to find anything that works...

```
.Input Parameters
[{pt}]
|===
|param1|string|foobar
|param2|long|blah
|===
```

**Comment by mojavelinux** [comment]
You can either set `caption` on each table to blank:

```
.Input Parameters
[caption=]
```

or you can set it globally:

```
:table-caption!:
```

In this case, "caption" refers only to the label not the title. In other words, it will show only the title as you entered it.

**Comment by Svish** [comment]
Ah! I tried ´:caption!:`, but that didn't work. Thank you. This should definitely be documented better in the [user manual](http://asciidoctor.org/docs/user-manual/). Only reference I find to `table-caption` is a row in the enormous Appendix A :anguished:

**Comment by mojavelinux** [comment]
I added an issue to track it. https://github.com/asciidoctor/asciidoctor.org/issues/421
