### ISSUE TITLE
Drop leading blanks

### ISSUE THREAD

**Issue by molmich** [asciidoctor/asciidoctor#1566]
_b_: stay for blank
for example:

...
_ATTENTION:_ This is an example of 
_bbbbbbb_leading blank.
...

has in PDF:
...
ATTENTION: This is an example of _bbbbbbb_leading blank.
...

is it possible to dron the leading blanks?

**Comment by mojavelinux** [comment]
I'm not quite understanding what you are asking. Also, if this pertains to PDF, then it should be in the PDF repository: https://github.com/asciidoctor/asciidoctor-pdf

**Comment by molmich** [comment]
yes you ar right, I use this call:

asciidoctor -r asciidoctor-pdf -b pdf

that why I thing its asciidoctor issue

**Comment by mojavelinux** [comment]
Yep, that loads https://github.com/asciidoctor/asciidoctor-pdf.

**Comment by mojavelinux** [comment]
I have an explanation and suggestion prepared for you, so if you ask your question in the project chat, I will follow-up as soon as I see it.
