### ISSUE TITLE
Adding Asciidoctor TOC to Velocity template

### ISSUE THREAD

**Issue by mstanleyjones** [asciidoctor/asciidoctor#1571]
I finally have everything working with building my docs as part of my site. I had to use the following kind of syntax for including files, when the main `book.adoc` is in `src/site/asciidoc/book.adoc` and the chapters are in `src/site/asciidoc/_chapters/`. It seems odd but it works.

----
include::{docdir}/src/site/asciidoc/_chapters/getting_started.adoc[]
include::{docdir}/src/site/asciidoc/_chapters/configuration.adoc[]
include::{docdir}/src/site/asciidoc/_chapters/upgrading.adoc[]
----

Now my next problem is that Maven's site skin template does not seem to have support for displaying the table of contents div. This is a Velocity template, and I can't find any guidance on displaying the TOC within it. Any ideas?

**Comment by mojavelinux** [comment]
There are two solutions. The first is to include the toc inside the content by placing it using the toc macro.

```
:toc: macro

...

toc::[]
```

The other solution is to invoke the Asciidoctor API from the Velocity template to extract the structure of the document and iterate over the sections to output a TOC. This would allow you to put the TOC in the sidebar. However, it's a much more technical approach and I'm not exactly sure where everything would need to go to make it work. It just seems possible in theory.

**Comment by mojavelinux** [comment]
> I had to use the following kind of syntax for including files

This is due to https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/180.

**Comment by mstanleyjones** [comment]
Thanks, I'll keep watching these issues.

**Comment by mojavelinux** [comment]
Great! We'll continue the discussion there.
