### ISSUE TITLE
Images with link should not overflow

### ISSUE THREAD

**Issue by jeremyVignelles** [asciidoctor/asciidoctor#1572]
Hi,
In my documentation source file, I am declaring a picture with a link, like this:

```
image::Dockerized_Environment.svg[role="text-center", link="Images/Dockerized_Environment.svg"]
```

However, with the HTML output, the image overflows if there is not enough space.
This issue disappears when removing the `link` attribute, and I did not notice this behavior in 1.5.2 .

After digging a little, I found that `img` has a `max-width:100%;`, but `.image` doesn't, which seems to cause this issue.

**Comment by mojavelinux** [comment]
Could you show a screenshot or point to a document that has this error? I'm not able to visualize the problem from your description, but likely I'd get it right away if I could see it.

**Comment by mojavelinux** [comment]
Is this specific to SVGs?

**Comment by jeremyVignelles** [comment]
Hi,
Thanks for your reply.
I made some tests on my home computer and this issue seems to be specific to firefox, not to SVGs.
Here the code I used for testing:
```
image::http://fakeimg.pl/2000x100/[role="text-center", link="http://fakeimg.pl/2000x100/"]
```

**Comment by mojavelinux** [comment]
This seems to have been a bug in Firefox that has since been fixed. It fails for me on Firefox 42, but works on Firefox 54. (Maybe fixed in Firefox 46 by this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=434230).

Do you think we should close or try to fix it for older versions?

**Comment by jeremyVignelles** [comment]
Hi,
I don't work at the same place anymore, and I'm not using asciidoctor anymore, so I can't really test.
You have reproduced the issue with an old version of FF, and saw it was fixed in the newest version, then you can close the issue.
Thanks

**Comment by mojavelinux** [comment]
The reason you started seeing this in Asciidoctor >= 1.5.3 is because of this additional rule:

```
a.image {
  display: inline-block;
}
```

That was added to allow links around SVGs to work.

**Comment by mojavelinux** [comment]
I proposed a PR, but I'm not convinced yet we should merge it. See #2453.

**Comment by mojavelinux** [comment]
Thanks for the follow-up @jeremyVignelles!

**Comment by mojavelinux** [comment]
We've decided to close this issue, but at least we understand now why it was happening. We left behind a solution in PR #2453 in case this continues to be a problem.
