### ISSUE TITLE
[1.5.3] TOC in table cells

### ISSUE THREAD

**Issue by jeremyVignelles** [asciidoctor/asciidoctor#1577]
Hello,
I'm using the new version of AsciiDoctor, but I've seen a strange behavior with this file: 
```
= Test file
:toc:

== Header
[cols="1a,1a", options="header"]
|===
|Name of Column 1
|Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===
```

In the output, I have a summary in each cell.

**Comment by mojavelinux** [comment]
I realized I reported the same issue. Since that issue has more details about what needs to be fixed, I close this one in lieu of that one.

**Comment by mojavelinux** [comment]
Note that I also documented a workaround.

**Comment by river-wang** [comment]
great!
