### ISSUE TITLE
GitHub 'italic' rendering depends on document title markup

### ISSUE THREAD

**Issue by powerman** [asciidoctor/asciidoctor#1580]
Sorry, I'm not sure is this asciidoctor's issue or github's one, but I failed to find (again) github repo where such issues should be reported. So, I'll report it here and hope you'll let me know about better place to report it if it's not an asciidoctor's issue.

Problem is, italic markup `'italic'` rendered differently by GitHub depending on document title markup:
```
= Document Title

This is not 'italic', but this is _italic_.
```
while:
```
Document Title
==============

This is 'italic', and this is _italic_.
```

**Comment by mojavelinux** [comment]
Your observation is correct. The reasoning is described here:

http://asciidoctor.org/docs/migration/

**Comment by mojavelinux** [comment]
You can force the behavior to be the same using by specifying `compat-mode` explicitly.

```
= Document Title
:compat-mode:

This is 'italic'.
```

**Comment by powerman** [comment]
Just to make it clear, am I correct: you've just killed 'italic' syntax support for the Great Good of having just one way for italic markup instead of two? To "simplify learning asciidoc syntax".

**Comment by mojavelinux** [comment]
Yes, the modern Asciidoctor syntax only uses underscore for italic for numerous reasons. The most pertinent is that single quotes have well-defined meaning in English and it is thus inappropriate to override such a strong language convention.

Making this changed also opened the way to use single quotes adjacent to backticks to create typographic quote marks.

**Comment by mojavelinux** [comment]
Btw, we didn't "kill" the single quotes italic. It still works in compat mode (`:compat-mode`) and will continue to work as we make changes to the syntax in Asciidoctor. We do respect the need for backwards compatibility as Asciidoctor and the AsciiDoc syntax evolves.

**Comment by powerman** [comment]
BTW, is there any real needs in new syntax for “ and ”? Nowadays it usually not a big deal to enter Unicode in text editor.

**Comment by mojavelinux** [comment]
I'm starting to advocate for the use of Unicode characters directly, but shifting that mindset is going to take time. Personally, that's how I do it. But it would be too soon to take away the option to use a shorthand and I think that what we came up with in 1.5.0 is a really clear way of expressing it.
