### ISSUE TITLE
Warning for broken internal cross-references

### ISSUE THREAD

**Issue by Svish** [asciidoctor/asciidoctor#1586]
Re asciidoctor/asciidoctor-maven-plugin#175, it would be very helpful if warnings were generated when internal cross-references turns out to be broken.

There already seems to be some sort of logic there, as for example `<<Foo>>` will turn into `[Foo]` rather than `Foo` if it doesn't exist, so shouldn't be too much of a fix to also generate a warning when this happens?

Would make it a lot easier to catch these errors at least!

**Comment by Svish** [comment]
The #1101 issue might be considered sort of a duplicate, but that one talks about inter document references. Don't know if that makes any difference though... either way, it suggests an attribute to generate warnings for this, but I'd prefer this was the default behavior, just like for failing includes.

**Comment by mojavelinux** [comment]
I agree. The internal references are something that the core processor can warn about. The external (inter-document) references require a broader scope than what the processor can see (the corpus of documents), so it belongs in something like a build tool (Maven, Gradle, etc).

**Comment by mojavelinux** [comment]
> Would make it a lot easier to catch these errors at least!

+1 This seems like a warning that should have been there all along.

...in fact, I know why it isn't in AsciiDoc Python (and why we didn't think to implement it). AsciiDoc Python can't see references in front of the cursor, so if you link forward in a document, it would always think that is invalid. Asciidoctor sees the whole document, so we can look ahead and back for references. With that said, we definitely missed the opportunity before now to make this a built-in validation.

**Comment by mojavelinux** [comment]
This is now implemented if you enable the verbose switch:

```
asciidoctor -v sample.adoc
```

It's behind the `-v` switch because there are still some false positives. There are still some places the processor is not looking for anchors, such as in list items.

I'm going to leave this open until we enable this validation without the verbose flag.

**Comment by mojavelinux** [comment]
> the verbose switch:

You can think of this as pedantic mode.

**Comment by mojavelinux** [comment]
I've opened #2722 to track turning on these warnings by default, even without verbose mode.

In the interim, we encourage anyone using 1.5.7 to enable verbose mode so we can collect feedback about whether these warnings are helpful / tolerable.

1.5.7 is going to have a lot less false positives than previous versions. But there will still cases of a reference that looks invalid to the processor, but is in fact valid. We'll document these scenarios and determine which ones need to be addressed.

**Comment by mojavelinux** [comment]
This was actually implemented in 1.5.6 by #2268. It just becomes a lot more usable in 1.5.7.
