### ISSUE TITLE
manpage: leading \. is left as is, should be \&.

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#1589]
When the manpage backend is used, `\.` (backslash, period) at the head of a line in the source document is left as is. This causes the line to be treated as a macro call by `man` (and if the characters following the `\.` don't constitute a macro, the entire line is ignored).

It should be translated to `\&.` (i.e., backslash, ampersand, period).

**Comment by mojavelinux** [comment]
Perhaps add a replacement under the one for the lone `.` at https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/manpage.rb#L24

```
.gsub(/^\\\./, '\\\&.')
```

**Comment by ds26gte** [comment]
Yes, your suggested snippet will resolve it. You may either add it yourself, or take my recent PR.
