### ISSUE TITLE
manpage: translating links to .URL introduces extraneous newline/space

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#1590]
When translating `http://asciidoctor.org[Asciidoctor],` as
```
.URL "http://asciidoctor.org" "Asciidoctor" ","

```
the introduction of the newline plays havoc with following text, unless the following text is another link. For instance,

- If the comma is followed by a space and then some regular text, that space becomes a line-leading space which forces a linebreak in troff.

- If the comma is followed by a newline, that newline is added to the newline already introduced by the `.URL` and causes vertical space that was not intended (so it looks like a paragraph break).

As an example:
```
The relevant sites are
http://asciidoctor.org[Asciidoctor], http://racket-lang.org[Racket],
http://neovim.io[NeoVim], and
http://gnu.org/software/groff[Groff].
```
gets translated to
```
The relevant sites are
.URL "http://asciidoctor.org" "Asciidoctor" ","
.URL "http://racket\-lang.org" "Racket" ","

.URL "http://neovim.io" "NeoVim" ","
 and
.URL "http://gnu.org/software/groff" "Groff" "."

```
so the two newlines after `Racket,` and the space before `and` cause problems.

While the newline is certainly needed in order to terminate the arguments to `.URL`, in order to stop it from being treated as actionable space by troff, it needs to be immediately followed by `\c`.

I.e., the translation above should be
```
The relevant sites are
.URL "http://asciidoctor.org" "Asciidoctor" ","
\c
.URL "http://racket\-lang.org" "Racket" ","
\c

.URL "http://neovim.io" "NeoVim" ","
\c
 and
.URL "http://gnu.org/software/groff" "Groff" "."
\c

```

**Comment by mojavelinux** [comment]
I was having tremendous difficulty figuring this out, so I'm very glad to see that you've proposed a way to solve it. Would you like to make a pull request that introduces this change?

We are still getting an extra space before the "and" even with this change. I think it's as simple as adding a `\\c` after the `#{LF}` in the following line: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/manpage.rb#L26

**Comment by ds26gte** [comment]
> We are still getting an extra space before the "and" even with this change. I think it's as simple as adding a \\c after the #{LF} in the following line

You're right. My algorithm was correct but I goofed in my illustrative example.  There is a `\c` after the newline terminating the .URL macro-call but no newline should be introduced after the `\c`.

PR submitted.

**Comment by mojavelinux** [comment]
Thanks!
