### ISSUE TITLE
Wrong element in DocBook output for glossary section with level > 1

### ISSUE THREAD

**Issue by FeiWongReed** [asciidoctor/asciidoctor#1591]
When I'm compiling source like this:
```
= Sample
:doctype: book

== Glossaries

[glossary]
=== Example Glossary

Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.

```
with command
```
asciidoctor -b docbook -d book -D out example.ad
```
I getting the following output:
```
...
<chapter xml:id="_glossaries">
<title>Glossaries</title>
<section xml:id="_example_glossary">
<title>Example Glossary</title>
<simpara>Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.</simpara>
<glossentry>
<glossterm>A glossary term</glossterm>
<glossdef>
<simpara>The corresponding (indented) definition.</simpara>
</glossdef>
</glossentry>
<glossentry>
<glossterm>A second glossary term</glossterm>
<glossdef>
<simpara>The corresponding (indented) definition.</simpara>
</glossdef>
</glossentry>
</section>
...
```

It's incorrect because ```glossentry``` sections must be wrapped with ```glossary``` one. This doesn't happen when glossaries are chapters instead of sections but I'm sure that it should work correctly in this case too.

**Comment by mojavelinux** [comment]
You are correct, this appears to be a compliance issue. For some reason, we are using the element name "section" for special sections that have a level that is greater than 1. However, there is no such restriction in AsciiDoc Python. We should lift this restriction (and perhaps discover under which circumstances, if any, it should still be applied).

**Comment by mojavelinux** [comment]
I've updated the issue titled to reflect the real issue.
