### ISSUE TITLE
Allow to use custom admonition icons even if fontawesome is used via :icons: font

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1593]
As mentioned in http://discuss.asciidoctor.org/icons-customization-conflicts-with-icons-font-td3973.html it is at the moment not possible to use own admonition icons if the attribute `:icons: font` is set.

A workaround is to temporarily unset the icons attribute, but this is actually a bit inconvenient: 
```asciidoctor
:icons:

[icon=personal.png]
[NOTE]
====
blabla
====

:icons: font
```

Instead it would be better if an icon attribute on the admonition block would override the document level attribute `icons`:
```asciidoctor
= Test document
:icons: font

[icon="a.png"] 
[NOTE] 
blabla 
```

**Comment by mojavelinux** [comment]
As a follow-up question, I'm curious whether the icon attribute value should be resolved relative to the `iconsdir` or whether it should be used as is. wdyt? cc @jmbruel

**Comment by mojavelinux** [comment]
If you think we should change how the icon is resolved, we'll create a separate issue to track it.

**Comment by jmbruel** [comment]
I'd say icon attribute value should be resolved relative to the iconsdir (one directory for icons and that's it).

**Comment by mojavelinux** [comment]
Sounds pretty reasonable. AsciiDoc Python doesn't have the custom icon feature, so we are defining new territory here. I don't know of anyone who is using the feature yet (other than you), so now's the right time to change it. Issue filed. https://github.com/asciidoctor/asciidoctor/issues/1634
