### ISSUE TITLE
html theme/looking changed after installation of asciidocpdf

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1596]
this is really weired.
I have a doc rendered into html with asciidoctor perfectly.
and I just installed asciidoctorpdf. and it works great too.
but now if I render html with same command, the theme/looking changes alot.

```
:doctype: book
:toc: left
:toclevels: 3
:toc-title: Table of Content
:numbered:
:Author:  Ping
:Author Initials: SP
:Date:   Aug 2015
:iconsdir:
:icons: font
:source-highlighter: pygments
:source-highlighter: coderay
:source-highlighter: prettify
:source-highlighter: highlightjs
...rest of my doc...
```

I render it with this command:

```
 asciidoctor -d book mydoc.txt
```

the original looking "before" install asciidoctorpdf:
![image](https://cloud.githubusercontent.com/assets/2038044/11523552/2a5ae174-9891-11e5-8221-b26610e17f14.png)

how it looks now "after" installing asciidoctorpdf:
![image](https://cloud.githubusercontent.com/assets/2038044/11523569/59f326da-9891-11e5-8dcb-a8f01fa4a5ee.png)

what happened? I like the beautiful PDF , but I also want my original HTML back...
please advise...

**Comment by mojavelinux** [comment]
On Tue, Dec 1, 2015 at 11:11 PM, pinggit <notifications@github.com> wrote:

> :source-highlighter: pygments

:source-highlighter: coderay

:source-highlighter: prettify

:source-highlighter: highlightjs


It probably has something to do with this. When you installed Asciidoctor
PDF, you may have installed coderay or pygments, so now it's using one of
them. I suggest removing these attributes and adding them back one at a
time until you get the result you had before.

-Dan

-- 
Dan Allen | @mojavelinux | http://google.com/profiles/dan.j.allen

**Comment by robertpanzer** [comment]
Strange thing is that the original document had a sans-serif font, but the new one contains the well known font with serifs. 
As if a completely different renderer was used originally. (Maybe docbook/fop?)

> Am 02.12.2015 um 07:15 schrieb Dan Allen <notifications@github.com>:
>

**Comment by mojavelinux** [comment]
Aha. Asciidoctor PDF brought in Asciidoctor 1.5.x, which is when we introduced the new stylesheet. So it forced a major upgrade of Asciidoctor. The old stylesheet is RIP, so if you want it, you need to go back into the git history and dig it out. We've moved on from that styling.

**Comment by pinggit** [comment]
I've tested for a long time and I couldn't bring back the orignal html
style. what a pity.
I think the original style looks far better than the current ones...can we
get an option to choose between different stylesheet?

**Comment by mojavelinux** [comment]
Of course, you just use the `stylesheet` attribute and you can use whatever CSS you want.

Download the original stylesheet by copying the following lines to a CSS file (call it asciidoctor-classic.css):

https://github.com/asciidoctor/asciidoctor/blob/v0.1.4/lib/asciidoctor/backends/_stylesheets.rb#L112-L462

Then just link to it using:

```
asciidoctor -a stylesheet=asciidoctor-classic.css file.adoc
```

We're only shipping with a single stylesheet because the idea is to provide something that looks nice out of the box. I imagine that most people will end up using their own stylesheet for anything other than prototyping or casual documents.

**Comment by mojavelinux** [comment]
I pasted the stylesheet into a gist to make it easier to get.

https://gist.github.com/mojavelinux/6062c5f11e16bc8f759d

Note that it's not perfect because some of the HTML changed in Asciidoctor 1.5.0, so you'll need to make some adjustments. I'm happy to update the gist if you have a fix.

**Comment by mojavelinux** [comment]
I think we've sorted out why the style changed. Once you can confirm you are able to use the classic stylesheet, I'd like to close the issue.

**Comment by pinggit** [comment]
Dan:
thanks for the help.
but it looks nothing changed even with the style sheet specified.
I reversed the asciidoctor-pdf installation steps (uninstall
asciidoctor-pdf, coderay pygments.rb)
I even remove the asciidoctor (apt-get remove) and reinstall it back, still
I don't see any change...
it just look like I never get the orignal stylesheet back.

I hope I can understand the stylesheet better so I can fix it myself, but I
don't...

regards
ping

**Comment by mojavelinux** [comment]
> but it looks nothing changed even with the style sheet specified.

You'll need to share the HTML document that it produces in order for me to debug further.

> I even remove the asciidoctor (apt-get remove) and reinstall it back, still
> I don't see any change...

I wouldn't expect you to see a change if you reinstall Asciidoctor because that's going to install Asciidoctor 1.5.3. One thing to try is to install Asciidoctor 0.1.4 explicitly.

```
$ gem install asciidoctor --version 0.1.4
```

**Comment by pinggit** [comment]
you are exactly right!
looks like when I do gem uninstall I saw 2 versions here:
```
ping@ubuntu47-3:~$ sudo gem uninstall asciidoctor
Select gem to uninstall:
 1. asciidoctor-0.1.4
 2. asciidoctor-1.5.3
 3. All versions
> 3
```
now remove all and 
```
sudo gem install asciidoctor --version 0.1.4
```

now I got the original HTML, great!!

I'm thinking if I stick to this old version, I'll miss a lot of new feature and great PDF rendering for sure.
but comparing between the 2 styles, old and new, not only the font, but also other obvious changes:
the old style has a grey box covered the quoted texts blocks, so giving reader an good impression that this is a block of code quote, while the new style don't have this grey background in the box. I still think this is a small pity.

it will be ideal if the stylesheet you provided will work, so this will provide a "backward compatibility" while moving on.
I can send you the doc, but actually just any list block will show the issue. like this

```
[source,bash]
----
ping@trinity:~$ cat /etc/issue.net
Ubuntu 14.04.2 LTS

ping@trinity:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS  #<------
Release:        14.04
Codename:       trusty

ping@trinity:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

ping@trinity:~$ uname -a
Linux trinity 3.19.0-25-generic #26~14.04.1-Ubu
----
```

**Comment by mojavelinux** [comment]
> I can send you the doc, but actually just any list block will show the issue.

What I'm trying to show is that the stylesheet isn't actually being applied correctly, which is why I asked for you to share the result because then I can check.

If you do manage to get the old stylesheet applied, you should see close to the same style as with 0.1.4. I say close because certain things did change which makes the old stylesheet miss a few small things.

Keep in mind that you can developer your own stylesheet and the output can look however you want it to look. You can also use the new stylesheet and add additional styles, either at the bottom of the stylesheet or using something like docinfo.

**Comment by mojavelinux** [comment]
In other words, convert that example you gave and post the result in a gist (or anywhere you can post a code excerpt). Then I can check to see what the result is. (of course, make sure you are using Asciidoctor 1.5.3 so we can be sure we are testing the right thing).

**Comment by pinggit** [comment]
Hi Dan:
here is the gist URL about the doc excerpt:

https://gist.github.com/pinggit/78fdabfd8bcbb94b3d3d

with or without -a stylesheet, there is really no much difference...

 asciidoctor -a stylesheet=asciidoctor-classic.css asciidoctest.txt

thanks!
