### ISSUE TITLE
link macro produces invalid docbook5 document when caption starts with left bracket.

### ISSUE THREAD

**Issue by l1048576** [asciidoctor/asciidoctor#1597]
If link caption starts with left bracket (`[`), docbook5 backend produces invalid xml fragment for that link.

Example input:
```
http://example.com/[[bracket1\]]

link:http://example.com/[[bracket2\]]

link:http://example.com/[\[bracket3\]]

link:http://example.com/[ [bracket4\]]
```

Output (by `asciidoctor --no-header-footer -b docbook5 input.adoc -o -`)
```
<simpara><link x<link xlink:href="href="http://example.com/">">bracket1</link></link></simpara>
<simpara><link x<link xlink:href="href="http://example.com/">">bracket2</link></link></simpara>
<simpara><link x<link xlink:href="href="http://example.com/">\">bracket3</link></link></simpara>
<simpara><link xlink:href="http://example.com/"> [bracket4]</link></simpara>
```

Output for bracket2,3,4 is broken.

This does not occur when using docbook45 backend.

My environment is [here](https://gist.github.com/l1048576/f7c1524cfeeef74e4a0a#file-asciidoctor-enviroment-md)

**Comment by mojavelinux** [comment]
This happens because Asciidoctor performs substitutions incrementally and the namespaced attribute in the DocBook 5 backend `xlink:href` matches the inline link macro pattern. The simplest short-term solution is to change the namespace prefix from `xlink` to `xl` so that it stops getting caught up in substitutions.

(The long-term solution is to use a proper parser for inline substitution instead of a regexp approach, which is already planned. See #61).

**Comment by hmflash** [comment]
change f8f47ce seems to break dtd verification.

Using the example .adoc above I get the following output:

```
$ asciidoctor -b docbook5 input.adoc -o out.xml
$ xmllint -noout -dtdvalid docbook-5.0/dtd/docbook.dtd out.xml
out.xml:4: element article: validity error : No declaration for attribute xmlns:xl of element article
out.xml:9: element link: validity error : No declaration for attribute href of element link
out.xml:10: element link: validity error : No declaration for attribute href of element link
out.xml:11: element link: validity error : No declaration for attribute href of element link
out.xml:12: element link: validity error : No declaration for attribute href of element link
Document out.xml does not validate against jobs/seth-440s/peach-pro/3rdParty/docbook-5.0/dtd/docbook.dtd
```

**Comment by mojavelinux** [comment]
DocBook 5 cannot be properly validated using DTD because DTD is not advanced enough to express the full capabilities (such as custom XML namespaces). You should instead use the XSD to validate.

```
xmllint -noout --schema http://www.docbook.org/xml/5.0/xsd/docbook.xsd out.xml
```

Then you should see:

```
out.xml validates
```
