### ISSUE TITLE
Included URI content not being rendered from CLI builds, but is in Chrome Live Preview.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor#1599]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Can&#39;t get <a href="https://twitter.com/asciidoctor">@asciidoctor</a> URI Includes to work with sample content. Get `Unresolved directive in &lt;stdin&gt;` errors. :( <a href="https://t.co/IRC3auPtcY">pic.twitter.com/IRC3auPtcY</a></p>&mdash; Jared Morgan (@jaredmorgs) <a href="https://twitter.com/jaredmorgs/status/673675566126465024">December 7, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

A twitter support thread about getting asciidoc content rendered from URI includes needed to be branched off into an issue so we could diagnose the issue further.

.test.adoc
````
:allow-uri-read:
:asciidoctor-source: https://raw.githubusercontent.com/asciidoctor/asciidoctor/master

= Test

include::{asciidoctor-source}/README.adoc[]
````

If I try to publish test.adoc using the asciidoctor CLI, the included content is rendered as a link only when built to HTML, and not transformed/expanded into rendered content.

If I drag the file into Chrome, with the Asciidoctor Preview Extension active, the content is rendered in-line by asciidoctor.js

I'm wondering what I'm doing wrong with this when trying to build locally from the CLI.

I'm focusing on this now because I'm trying to get URI includes working from Atlassian Stash content. I feel I'm getting some false-negatives when encountering this issue with URIs on .

**Comment by jaredmorgs** [comment]
@mojavelinux @LightGuard This is the formal issue from the tweet.

**Comment by mojavelinux** [comment]
Thanks @jaredmorgs.

This happens because `allow-uri-read` must be set from the CLI, not the document. Reading from a URI is considered a security vector and we have to make sure that the user requested this operation (and not something controllable from the content).

Thus, you must run:

```
asciidoctor -a allow-uri-read sample.adoc
```

Then it will work. We should definitely update the docs to make this more clear.

It works in Chrome because it's not insecure for the browser to read a different URL since that is what browsers do :)

**Comment by jaredmorgs** [comment]
Aha! That is the missing piece of info I needed.

Let me make a PR. What repo should I be making the changes in, Dan?

I wonder how I would set this to work correctly in something that uses the
asciidoctor.min.js library.

I want to be able to link to source files inside Confluence pages, through
the https://github.com/norganna/adoc-usermacro and have them pulled in and
rendered.

I'd imagine I'd need to set this directive in the
https://github.com/norganna/adoc-usermacro/blob/master/adoc.velocity inside
the jQuery block where it declares the command-line parameters.

On Tue, 8 Dec 2015 at 11:03 Dan Allen <notifications@github.com> wrote:

> Thanks @jaredmorgs <https://github.com/jaredmorgs>.
>
> This happens because allow-uri-read must be set from the CLI, not the
> document. Reading from a URI is considered a security vector and we have to
> make sure that the user requested this operation (and not something
> controllable from the content).
>
> Thus, you must run:
>
> asciidoctor -a allow-uri-read sample.adoc
>
> Then it will work. We should definitely update the docs to make this more
> clear.
>
> It works in Chrome because it's not insecure for the browser to read a
> different URL since that is what browsers do :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/1599#issuecomment-162720359>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Exactly. You would add it to the list of attributes in that file.

```
attributes: ['showtitle', 'allow-uri-read']
```

If there are still issues, then it would be on the Asciidoctor.js side of things.

For the documentation, the PR would be made to the following file:

https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/uri-include.adoc

Additionally, that file says "assuming the safe mode is less than SECURE". It should be clearly stated that if the safe mode is SECURE or above, this feature can't be enabled at all.

**Comment by jaredmorgs** [comment]
https://github.com/asciidoctor/asciidoctor.org/pull/428

I note that in
http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely there
is only mention of SECURE, nothing higher. Is there a level above Secure?

On Tue, 8 Dec 2015 at 11:23 Dan Allen <notifications@github.com> wrote:

> Exactly. You would add it to the list of attributes in that file.
>
> attributes: ['showtitle', 'allow-uri-read']
>
> If there are still issues, then it would be on the Asciidoctor.js side of
> things.
>
> For the documentation, the PR would be made to the following file:
>
>
> https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/uri-include.adoc
>
> Additionally, that file says "assuming the safe mode is less than SECURE".
> It should be clearly stated that if the safe mode is SECURE or above, this
> feature can't be enabled at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/1599#issuecomment-162725649>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks!

>  Is there a level above Secure?

Not currently, but space is reserved for PARANOID :)

**Comment by jaredmorgs** [comment]
I've set that parameter inside the file but the content is still not
rendering in the user macro.

Do I need to somehow set a safe-mode parameter inside the macro through an
attribute. Something like:

safeMode: unsafe

Or is asciidoctor.js set to support allow-uri-read if it is specified?

I've taken a look at
https://github.com/asciidoctor/asciidoctor.js/blob/master/README.adoc but
can't see anything specific about Safe modes.

I've also tried searching for attributes in the Users Guide, but nothing
seems to be coming up specifically for .js implementations.

On Tue, 8 Dec 2015 at 11:23 Dan Allen <notifications@github.com> wrote:

> Exactly. You would add it to the list of attributes in that file.
>
> attributes: ['showtitle', 'allow-uri-read']
>
> If there are still issues, then it would be on the Asciidoctor.js side of
> things.
>
> For the documentation, the PR would be made to the following file:
>
>
> https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/uri-include.adoc
>
> Additionally, that file says "assuming the safe mode is less than SECURE".
> It should be clearly stated that if the safe mode is SECURE or above, this
> feature can't be enabled at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/1599#issuecomment-162725649>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
I was considering raising a bug, but I think it is more a bug in my
understanding rather than a bug wiht asciidoctor.js. ;)

On Tue, 8 Dec 2015 at 15:33 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> I've set that parameter inside the file but the content is still not
> rendering in the user macro.
>
> Do I need to somehow set a safe-mode parameter inside the macro through an
> attribute. Something like:
>
> safeMode: unsafe
>
> Or is asciidoctor.js set to support allow-uri-read if it is specified?
>
> I've taken a look at
> https://github.com/asciidoctor/asciidoctor.js/blob/master/README.adoc but
> can't see anything specific about Safe modes.
>
> I've also tried searching for attributes in the Users Guide, but nothing
> seems to be coming up specifically for .js implementations.
>
> On Tue, 8 Dec 2015 at 11:23 Dan Allen <notifications@github.com> wrote:
>
>> Exactly. You would add it to the list of attributes in that file.
>>
>> attributes: ['showtitle', 'allow-uri-read']
>>
>> If there are still issues, then it would be on the Asciidoctor.js side of
>> things.
>>
>> For the documentation, the PR would be made to the following file:
>>
>>
>> https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/uri-include.adoc
>>
>> Additionally, that file says "assuming the safe mode is less than
>> SECURE". It should be clearly stated that if the safe mode is SECURE or
>> above, this feature can't be enabled at all.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidoctor/asciidoctor/issues/1599#issuecomment-162725649>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
> I think it is more a bug in my understanding rather than a bug wiht asciidoctor.js.

Actually, I think your first instinct it right. This is a bug (or at least a deficiency) in Asciidoctor.js. I tried it from the Asciidoctor.js cli (https://github.com/asciidoctor/asciidoctor-cli.js) and it doesn't work. I think the Chrome extension (or the browser mode) has a configuration that is missing when running it outside the browser (but still in JavaScript). Likely it has something to do with this code: https://github.com/asciidoctor/asciidoctor.js/blob/master/lib/asciidoctor/opal_ext/file.rb#L102-L148

**Comment by jaredmorgs** [comment]
Hah! I'm glad I'm not going insane! \o/

Should I create an issue in the asciidoctor.js repo to track the issue. As most folks won't have access to confluence, I'll see if I can create a video or a screenshot that best illustrates the issue.

**Comment by mojavelinux** [comment]
The Confluence stuff shouldn't matter. We can test just with the jQuery bit alone and make sure the result is handled correctly. If that works, the rest will work.

**Comment by mojavelinux** [comment]
Following up in Asciidoctor.js repo.
