### ISSUE TITLE
Internationalize macros and attributes

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1600]
When writing asciidoctor in another language it can be weird to use English for macros and attributes. This is especially true for Right to Left scripts (such as Persian, Arabic, Urdu, Hebrew, ...) that using any macro or attribute needs to change from LTR to RTL just for that macro or attribute, and this can be quite annoying in some editors.

Fortunately I guess asciidoctor should not have much problem with internationalization (i18n) as most of things are punctuation or one-word names. The burden of writing in RTL is up to the editor and the burden of rendering on back-end rendering engines  (which is already well-implemented in some such as HTML). Signalling the right direction is another issue that I would open one later.

I think a dictionary mechanism can be helpful where standard macros and attributes are translated. Github does not let me to write in RTL (?) but  an example can be like this:

```
// to signal to the backend (inline is also needed)
:text-direction: rtl

//to signal to the backend it can have some impact such as using the right number symbols, calendar system, ...
:text-lang: fa

//replace the image macro name with تصویر
:replace-image: تصویر

// or just import a dictionary
:keywords-dictionary: some.adoc.txt

//example
[IMPORTANT] 
some text
[مهم]
یک نوشته

// file extensions are usually in Latin scripts and that is unavoidable
// note: Github does not support RTL and the second line is messed somehow
image::figure.png[]
تصویر::فایل.png


```

**Comment by mojavelinux** [comment]
See #1977. We're not going to do this in AsciiDoc.
