### ISSUE TITLE
Callouts in HTML code are interpreted as HTML content

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor#1608]
Hi,

I include snippets of code like the following:

```adoc
[source,html]
.universal-http/index.html
----
include::{sourceDir}/universal-http/index.html[]
----
<1> Comment
```

The content of the HTML page being:

```html
<!DOCTYPE html>
<script src="../../node_modules/superagent/superagent.js"></script> <1>
<script src="index.js"></script>
```

The problem here is the `<1>` is interpreted as HTML content.
If I wrap it in HTML comments (eg: `<!-- <1> -->`), then **it is not displayed** as a callout:

![screen shot 2015-12-11 at 12 28 59](https://cloud.githubusercontent.com/assets/138627/11743871/ddd7965c-a002-11e5-9839-6f621cb932e8.png)

Do you know any workaround, is it a bug or do you suggest another approach to use callouts in HTML listings?

Thanks :-)

**Comment by Mogztter** [comment]
If your sample is a not a production sample, you can use the syntax `// <1>`:

```adoc
[source,html]
.universal-http/index.html
----
<!DOCTYPE html>
<script src="../../node_modules/superagent/superagent.js"></script> // <1>
<script src="index.js"></script>
----
<1> Comment
```

Otherwise there's two options:

 1. you can write an extension to rewrite `<!-- <1> -->` into `// <1>` (not sure if `Preprocessor` extensions are called after or before includes are resolved)
 2. we need to improve the [callout regexp](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L745) to support xhtml callout `<!-- <1> -->`

**Comment by mojavelinux** [comment]
> - we need to improve the callout regexp
> <https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L745>
> to support xhtml callout 


The correct syntax is:



That's the recommended way to write it a callout number in an XML or SGML
language.

**Comment by mojavelinux** [comment]
On Fri, Dec 11, 2015 at 5:30 AM, Thomas Parisot <notifications@github.com>
wrote:

> The problem here is the <1> is interpreted as HTML content.
>
By which program?

Also, what source highlighter are you using?

**Comment by Mogztter** [comment]
Thanks for the tip, I tried `<!-- 1 -->` (with spaces between the number) but you have to write it without spaces.

**Comment by oncletom** [comment]
I confirm, the `<!--1-->` syntax made the trick :-) Waouh! Thanks a lot!

**Comment by mojavelinux** [comment]
Correct. We might be able to loosen that up once we use a separate parser per source language, but trying to do it all with a single regexp means we have to be more strict.

**Comment by mojavelinux** [comment]
These are related issues: #1360 and #1467.
