### ISSUE TITLE
:leveloffset: seems to not be nesting content correctly.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor#1615]
# Problem

I've got a main document with `include` paths declared to section files set to the standard root section level (== Section Title). Unless I've got something wrong with the syntax, or my understanding of the syntax is incorrect, the :leveloffset: attribute is not being honoured correctly.

````
:sectnums:
:toc: left
:toclevels: 5
:doctype: book

= Development Environment Configuration

== Set Up Your Mac Environment 

include::SSH_Local.adoc[leveloffset: +]

== Setting Up a Vagrant Docker Development Environment
````

.SSH_Local.adoc
````
== Configure SSH Keys for Stash and GitHub

Ladbrokes currently has two VCS it uses to manage code:

* GitHub
* Stash
````
# Expected Behaviour

I'd expect that with leveloffset specified as +1 that would add one extra `=` to the already declared `==` main heading, which would result in a `===` heading level and a nested structure like this:

````
== Set Up Your Mac Environment

=== Configure SSH Keys for Stash and Github
````
# Actual Behavior

I'm getting the following structure when built from the CLI, and when the document is rendering in AsciidocFx and Atom Editor:

````
== Set Up Your Mac Environment

== Configure SSH Keys for Stash and Github
````

<img width="1027" alt="screenshot 2015-12-14 11 39 33" src="https://cloud.githubusercontent.com/assets/952793/11771112/76502312-a257-11e5-8911-adf7c1e96238.png">

**Comment by jaredmorgs** [comment]
include::SSH_Local.adoc[leveloffset: +] is the problem, and it's not Asciidoctor.

It's PEBKAC.

include::SSH_Local.adoc[leveloffset= +1] is what it should be in my code.

Sorry for the noise. I seem to regularly encounter issues with top-declared attributes vs inline attributes.

I just need to retrain my brain. ;)

**Comment by mojavelinux** [comment]
:+1:
