### ISSUE TITLE
Toc's title appear in a Table's Cell

### ISSUE THREAD

**Issue by river-wang** [asciidoctor/asciidoctor#1617]
Hi:

I want to embed a list in a Table's cell like the following example,but 
the Toc's title appears in the cell.

asciidoctor version :1.5.3

```
= Title
:toc: left

{asciidoctor-version}

|===

|a|b

a|

* item
* item

a|

. item
. item

|===

```

Thanks

**Comment by mojavelinux** [comment]
This is a known issue with 1.5.3. See #1577. Schedule for 1.5.4.
