### ISSUE TITLE
data-uri

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1627]
I thought with `:data-uri:` , my pictures will be embedded in the webpage so I can see it even without Internet.

```
image::https://cloud.githubusercontent.com/assets/2038044/11611255/xxxx.png
```

but I just tested it , once I disable Internet I can't see the images. 
am I missing anything?

**Comment by Mogztter** [comment]
You most likely need to add the `:allow-uri-read:` attribute and configure the safe mode: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/#allow-uri-read-attribute
