### ISSUE TITLE
Image encoding as Base64 within the resulting output

### ISSUE THREAD

**Issue by jnorthr** [asciidoctor/asciidoctor#1629]
Only a query if there is a way to ask asciidoctor to base64 encode a small image as part of the html output stream? This would save a lot of faffing about hauling images in a companion folder where the image is only used in a single document and not all of them. ?

Thx

**Comment by mojavelinux** [comment]
The data-uri attribute does exactly this.

**Comment by jnorthr** [comment]
WOW ! will have that one chiseled on my tombstone 😉

**Comment by mojavelinux** [comment]
:)

Here's the link to the reference: http://asciidoctor.org/docs/user-manual/#managing-images
