### ISSUE TITLE
manpage: listings with leading `.` that happens to be valid troff are mistranslated

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#1631]
This is almost related to #1589 but not quite.

If a listing contains a line that's valid troff, the translated manpage treats it as valid troff (instead of verbatim text) and tries to execute it!  E.g.,

```
AAA should show.

----
BBB should show.
.if 1 .nx
CCC should show but doesn't.
----

DDD should show but doesn’t.
```

Same thing happens for the indent-everything-approach to getting a listing:

```
AAA should show.

   BBB should show.
   .if 1 .nx
   CCC should show but doesn't.

DDD should show but doesn’t.
```

A user remedy is to make sure that the `.`-line is indented (in the second case, indented relative to the other lines), but this does put the onus on the author.

The conceptual fix is to prefix  line-leading `.` with `\&` inside listings, so `manify` may need an option just for this.  (BTW, `manify` currently has a `preserve_space` option which I don't think is used.)

**Comment by mojavelinux** [comment]
Thanks for pointing this out. This problem isn't limited to listing blocks, so I think it needs to be something that is added to manify.

The way to think about it is that manify maps roughly to escaping reserved XML chars for the HTML/XML backends.

> A user remedy is to make sure that the .-line is indented (in the second case, indented relative to the other lines), but this does put the onus on the author.

I agree, the author should not have to worry about this.

**Comment by ds26gte** [comment]
I'll come up with a PR and you can give it the once-over.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by ds26gte** [comment]
PR submitted: ee11a2f.
