### ISSUE TITLE
Hide table of contents if empty

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1633]
Hide the table of contents if it would otherwise be empty. There's no point in showing an empty toc.

If, for some reason, we want to allow an empty toc, then it should require an attribute to enable it (e.g., `toc-show-if-empty`).

**Comment by mojavelinux** [comment]
Interesting to note that the requested behavior is consistent with the PDF generated by DocBook => Apache FOP.

**Comment by mojavelinux** [comment]
I'm going to defer on the `toc-show-if-empty` because I think that would be better handled using custom templates (or docinfo). It just doesn't make much sense to show a toc when there is nothing in it.

**Comment by wsalembi** [comment]
All my cells with source code listing have such an empty TOC because the cells use asciidoc style (a|). Will this solve this problem? Any workaround to avoid this behavior in 1.5.3?

**Comment by mojavelinux** [comment]
This is a known issue and is addressed in the upcoming (and imminent) 1.5.4 release. See #1582 for a workaround.
