### ISSUE TITLE
Resolve custom icon on admonition relative to iconsdir

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1634]
The custom icon (i.e., the value of the icon attribute) on an admonition block should be resolved relative to iconsdir. Currently, it is being passed through as written.

See #1593.

**Comment by mojavelinux** [comment]
@jmbruel I've adjusted the code for 1.5.4 so that it resolves the icon relative to iconsdir and automatically adds the icontype extension if an extension is not specified. So you can type:

```
.Réponse
[icon=personal]
[NOTE]
====
blabla
====
```

And it will resolve the icon as `{iconsdir}/personal.png`. Hopefully a nice time saver!

**Comment by robertpanzer** [comment]
:+1: Absolutely makes sense

**Comment by mojavelinux** [comment]
This should also pave the way in the future to be able to customize the font-based icon using this same strategy. But we still have some other things to sort out in the mapping to make that feasible. But we could add it sooner in Asciidoctor PDF.

**Comment by jmbruel** [comment]
Great! Thanks. This is a real christmas gift +1:

**Comment by mojavelinux** [comment]
The next gift is the release, on the way!
