### ISSUE TITLE
Table of content in table cells

### ISSUE THREAD

**Issue by daojoo** [asciidoctor/asciidoctor#1635]
When I set the `toc` attribute as `left` or `right` , and set a `a` style to table cell, then in the table cell will display a table of content. Is this deserved ?

![2015-12-28 15 15 49](https://cloud.githubusercontent.com/assets/1996504/12015340/f57aa684-ad75-11e5-8505-a7021ee024b8.png)

My English is poor!

**Comment by mojavelinux** [comment]
This is a known issue and will be resolved in 1.5.4, which I'm working on finishing right now.

**Comment by mojavelinux** [comment]
See #1582.

**Comment by daojoo** [comment]
Thanks!
