### ISSUE TITLE
Upgrade to highlight.js 9.9.0

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1652]
Upgrade to highlight.js 9.9.0.

This upgrade introduces a new styling system, so we'll need to check the output to make sure it doesn't break any of our CSS. See https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md#version-900 for details.

**Comment by jponge** [comment]
@mojavelinux how can you include a custom, local highlightjs? We would need it for eclipse/golo-lang since highlightjs does not include the Golo syntax highlighter by default, one needs the full distribution.

**Comment by mojavelinux** [comment]
Indeed. Just set the `highlightjsdir` attribute to a web path and it will resolve the files from there. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L209-L213 for details about how it is used.

It might be nice to add `highlightjs-defs` (or `highlightjs-langs`) that will load additional paths not included the highlight.min.js file.

**Comment by jponge** [comment]
Thanks Dan.

I tried using this variable and point it to a local folder where I had downloaded a copy of highlight.js.

First the links are wrongly generated, and then the latest highlight.js library is now named highlightjs.pack.js.

Would you like to have a look on our code base?

**Comment by mojavelinux** [comment]
You're going to need to rename the highlight.js files. It's not designed to work with the downloaded distribution (since it differs from the layout used on cdn.js).

**Comment by mojavelinux** [comment]
@jponge Can you make that work for you?

**Comment by jponge** [comment]
Yes Dan, I just made it work :-)

https://github.com/eclipse/golo-lang/pull/353

Thanks a lot.

**Comment by mojavelinux** [comment]
Super!

**Comment by mojavelinux** [comment]
Yep, we're all compatible. If you had defined your own highlight.js style, then it will need to be migrated to the 9.x system...but most people seem to use the built-in styles (or just copy one from the project).

**Comment by mojavelinux** [comment]
I noticed that the upgrade brings highlighting of annotations in Java. Nice!
