### ISSUE TITLE
`/compat/` missing from asciidoctor-1.5.4.gem

### ISSUE THREAD

**Issue by ktdreyer** [asciidoctor/asciidoctor#1659]
The `/compat/` directory was present in asciidoctor-1.5.3.gem on rubygems.org, but it's missing in asciidoctor-1.5.4.gem.

The `/compat/` directory is still here in Git, so I'm guessing this might have been an oversight in the 1.5.4 release?

**Comment by mojavelinux** [comment]
I dropped it since the recommendation is to get the files from git if you
need them. I'd rather not have people dig around in the installed location
for these files and the library itself never reads them anyway.

**Comment by ktdreyer** [comment]
Thanks Dan! That makes sense. I'll drop it from the Fedora packaging as well then.

**Comment by mojavelinux** [comment]
Thanks Ken!

**Comment by ktdreyer** [comment]
Sure, done @ https://github.com/asciidoctor/rubygem-asciidoctor-rpm/commit/d6c93927cda1c5c716d1ecca7acf9166b8a85124
