### ISSUE TITLE
Index entries defined with double parenthesis are not hidden in the HTML output 

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#1662]
If I read this correctly I can use ((myterm) to add to the index.

http://asciidoctor.org/docs/user-manual/#user-index

Quote: The double parenthesis inline macro adds a primary index term, and includes the term in the generated output.

But entries like this are included in the HTML output. Entries with (((myterm) are hidden. Either the docu or the tooling might be incorrect.

**Comment by vogella** [comment]
Example below. First one is visible in the HTML output, second not.

== View file in different revision

((git show))
(((git show)))

**Comment by jxxcarlson** [comment]
I need to be educated on the proper use of ((*)) and (((*))).  The way I did
it, both are added to the index, but the second is an invisible mark in the
HTML, just used for linking the term in the index to it occurrence in the text.

**Comment by vogella** [comment]
@jxxcarlson that makes sense. The first version can be used if the text should also be displayed in the rendered HTML and the third version if the text should be invisible except in the index. 

If @mojavelinux or someone else from the @asciidoctor team can confirm that, I suggest to update the http://asciidoctor.org/docs/user-manual/#user-index description.

**Comment by mojavelinux** [comment]
> Example below. First one is visible in the HTML output, second not.

You have explained exactly how it works. I've updated the documentation to be more clear about this.

In essence, the `((term))` form is just a shorthand way of writing `term(((term)))`. It only supports a primary index entry (since that's the only thing that makes sense to display).

I suppose the `((term))` could allow secondary and tertiary entries but only show the last entry (the most granular). So `((letter,A))` would show `A`, but sort both terms in the index of course. wdyt? If so, we should file that as a separate issue.

**Comment by mojavelinux** [comment]
To clarify $subject:

> Index entries defined with double parenthesis are not hidden in the HTML output

This is by design.

**Comment by mojavelinux** [comment]
Let me know if that clears things up for you.

**Comment by jxxcarlson** [comment]
Good for me!

**Comment by vogella** [comment]
Thanks looks good. Maybe also add the link to the PDF issue? From the current description it is not clear (to me) that the index is not created for the PDF output.

You have:
We’re tracking support for native index generation when using the HTML5 backend in issue #450.

Suggested change:

We’re tracking support for native index generation when using the HTML5 backend in issue #450 and for the PDF backend in issue https://github.com/asciidoctor/asciidoctor-pdf/issues/386.

I could send a PR for this change, if desired.

**Comment by mojavelinux** [comment]
Sure! Only one small change. Could you use the word "converter" in place of the word "backend". We're trying to get that updated everywhere, but one step at a time.

**Comment by vogella** [comment]
https://github.com/asciidoctor/asciidoctor.org/pull/474

**Comment by vogella** [comment]
Thanks for merging the PR
