### ISSUE TITLE
Attributes should allow letters from any Unicode script, not just Basic Latin

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1665]
Attributes are currently restricted to basic latin word characters ([A-Za-z0-9_]). This should be extended to recognize letters in any Unicode script.

This can be accomplished by changing the match from `\w` to `\p{Word}`. Note that this is a departure from AsciiDoc Python.

**Comment by shahryareiv** [comment]
Is there a reason why not be able to use any unicode character except a forbidden list? I have no idea if \p{Word} implementation is not different in different languages. But we are some how sure that for example `[^-\[\]:]` works in the same way.

**Comment by mojavelinux** [comment]
This is a duplicate of #2376, which is now resolved (as of 1.5.7).
