### ISSUE TITLE
Abbreviated blockquote does not support link in attribution

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1667]
```
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, https://jeffersonpapers.princeton.edu/volumes/volume-11[Papers of Thomas Jefferson: Volume 11]
```

URL in the "from" text it won't be rendered, can this be supported?

**Comment by mojavelinux** [comment]
Subs are not currently applied to the attribution fields in this form, though they probably should be.

As a workaround, you need to use the formal structure:

```
[quote,Thomas Jefferson,'https://jeffersonpapers.princeton.edu/volumes/volume-11[Papers of Thomas Jefferson: Volume 11]']
I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.
```

**Comment by mojavelinux** [comment]
My proposal is to treat the credit line as an implicit block attribute line. Therefore, the same rules would apply as in the formal quote block. That would mean that if you want the URL macro to be parsed, you'd need to enclose it in single quotes as follows:

```
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, 'https://jeffersonpapers.princeton.edu/volumes/volume-11[Papers of Thomas Jefferson: Volume 11]'
```

What I'm not sure about is what to do about a second comma in the line. Should we require that the value be enclosed in single quotes, such as:

```
-- Famous Person, "Famous Quotes, Volume 10"
```

Or should we ignore it, which would imply special parsing rules:

```
-- Famous Person, Famous Quotes, Volume 10
```

We could go either way.

My instinct is to stick with the same rules as block attributes so it's easier to explain and remember.

**Comment by mojavelinux** [comment]
I've given this some more thought and now I think it would be more intuitive just to apply normal subs to the line, then split the line on comma. The line looks like paragraph text, so it's natural to assume that normal (paragraph) substitutions are applied to it. If you need to escape anything, then you can use the normal escaping mechanisms in AsciiDoc.

That leaves us with:

```
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, https://jeffersonpapers.princeton.edu/volumes/volume-11[Papers of Thomas Jefferson: Volume 11]
```

I've added a commit that implements this strategy to the PR. We just need to decide which approach to take and then commit it.

**Comment by mojavelinux** [comment]
The more I think about, the more I think the element of least surprise is to apply normal subs to the credit line, then split on comma. I've merged that approach.
