### ISSUE TITLE
can there be an attribute to adjust the line space and font size

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1668]
one reason I like asciidoc is that with it It's super quick to draft technical docs, which involves a big portion of cmds outputs for demonstration purpose. this applies at least for me.

then I realized if my doc contains too many cmds outputs, It's probably good idea to squeeze them a bit. this will differ them from the normal text and make the page looks better.

I guess this is again about theme, which I never understand how to write one on my own, or even change an existing one. 

does it worth it to implement a new attribute to specify linespace or font for a specific block?
## [linespace=3, fontsize=10]

w-rw-r-- 1 ping ping 39793 Dec 19 17:40 asciidoctor.css
w-rw-r-- 1 ping ping 36715 Dec 19 17:40 colony.css
w-rw-r-- 1 ping ping 36217 Dec 19 17:40 foundation.css
w-rw-r-- 1 ping ping 36826 Dec 19 17:40 foundation-lime.css
w-rw-r-- 1 ping ping 36786 Dec 19 17:40 foundation-potion.css
w-rw-r-- 1 ping ping 37988 Dec 19 17:40 github.css
w-rw-r-- 1 ping ping 37233 Dec 19 17:40 golo.css
w-rw-r-- 1 ping ping 38305 Dec 19 17:40 iconic.css
w-rw-r-- 1 ping ping 36991 Dec 19 17:40 maker.css
w-rw-r-- 1 ping ping 37391 Dec 19 17:40 readthedocs.css
w-rw-r-- 1 ping ping 38834 Dec 19 17:40 riak.css
w-rw-r-- 1 ping ping 36970 Dec 19 17:40 rocket-panda.css

**Comment by mojavelinux** [comment]
This can be accomplished by using a custom stylesheet. It would be inappropriate for this type of information to be in the AsciiDoc document itself because it would be mixing content and presentation too tightly. The common abstraction point is the "theme" or "stylesheet".

You are probably looking for the compact theme, which is still in a pull request. See https://github.com/asciidoctor/asciidoctor-stylesheet-factory/pull/11

**Comment by pinggit** [comment]
thanks Dan. the compact theme looks something close for me.
is there a dummy step that I can try it out?

**Comment by mojavelinux** [comment]
I'll try to get that merged soon. Then, you'd follow this guide: http://asciidoctor.org/docs/user-manual/#stylesheet-factory

**Comment by pinggit** [comment]
got it. thanks!
look forward to seeing it happen.

**Comment by mojavelinux** [comment]
You can find additional themes / skins here: https://github.com/darshandsoni/asciidoctor-skins. Try the boot yeti.

There's also these theme: https://github.com/nerk/asciidoctor-bs-themes
