### ISSUE TITLE
A problem to export pdf!

### ISSUE THREAD

**Issue by lyshsgc** [asciidoctor/asciidoctor#1669]
I tired to transfer adoc to pdf yesterday. You could see the style that Book name with picture and word description on front page in html-preview (That is exactly I need!).  However, after using asciidoctor-fopub, there was no words and picture in home page. The picture and word was moved to pp.6. Why is this happening? Is it possible to generate pdf that is the same as html 100%?

![html](https://cloud.githubusercontent.com/assets/16219008/12220988/6c76d044-b7c3-11e5-878a-7d871f3d9d7b.png)

![pdf](https://cloud.githubusercontent.com/assets/16219008/12220992/83e83ec0-b7c3-11e5-9fef-65510421e280.png)

![pdf1](https://cloud.githubusercontent.com/assets/16219008/12220986/5ceb1996-b7c3-11e5-98c1-f7862a17dc9f.png)

![pdf2](https://cloud.githubusercontent.com/assets/16219008/12221022/5e83ac1c-b7c5-11e5-9ca8-ec50c1106d8d.png)

**Comment by mojavelinux** [comment]
Since this is related to asciidoctor-fopub, could you file the issue in that repository? https://github.com/asciidoctor/asciidoctor-fopub Thanks!

**Comment by lyshsgc** [comment]
Ok！

**Comment by mojavelinux** [comment]
Moved to https://github.com/asciidoctor/asciidoctor-fopub/issues/53.
