### ISSUE TITLE
StackOverflowError while rendering Java 8's default method

### ISSUE THREAD

**Issue by jinahya** [asciidoctor/asciidoctor#1671]
I piled https://github.com/jruby/jruby/issues/3596 to resolve StackOverflowError thrown while rendering a code snippet which includes Java 8's `default method` declaration. An noted in that issue, I couldn't pinpoint which stack has to be revolved so that I'm issuing here too.

**Comment by mojavelinux** [comment]
How are you invoking Asciidoctor? Are you using AsciidoctorJ?

**Comment by jinahya** [comment]
I'm using `asciidoctor-maven-plugin` for generating `html5`.
I'm sorry it seems that I used a wrong syntax. I'll reopen this issue if it occur again.

**Comment by mojavelinux** [comment]
If it comes up again, please file it here: https://github.com/asciidoctor/asciidoctor-maven-plugin. Thanks!
