### ISSUE TITLE
Section numbers for levels bigger than 3 not printed in TOC

### ISSUE THREAD

**Issue by filiphr** [asciidoctor/asciidoctor#1672]
I am not sure if this is a bug or it is expected. When I have this example:

``` ASCIIDOC
= Test Document
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 5

== Level 1
=== Level 2
==== Level 3
===== Level 4
====== Level 5
```

The headers for the Levels are correctly displayed. However, in the table of contents the section numbers are only displayed up to level 3. See the attached image.

![asciidoc_toc](https://cloud.githubusercontent.com/assets/6012094/12258570/e9ca6cca-b90f-11e5-99e8-96c5766ab776.png)

**Comment by mojavelinux** [comment]
This can happen if the sectnumlevels is defined after the document header.

```
= Document Title
:toc:
:toclevels: 5
:sectnums:

:sectnumlevels: 5 <- not in the document header
```

Are you sure it's exactly how you wrote it and that nothing is overriding the sectnumlevels? How are you invoking Asciidoctor? Are you passing options to it?

**Comment by filiphr** [comment]
Yes, that is exactly how I wrote it. I have ```:toc!:``` outside of the header, due to the table of contents appearing in some tables. And after that I have the ```sectnumlevels``` and some other parameters. When it is in the header it works, I was not aware about the header.

I am invoking Asciidoctor via the maven plugin in java. The passed options do not have anything related to the toc and sections

Thanks for the help

**Comment by mojavelinux** [comment]
You can now upgrade to Asciidoctor 1.5.4 and the toc in table cell problem is gone. Then, make sure you define document-oriented attributes in the header and you should be good to go.

**Comment by mojavelinux** [comment]
All the problems reported in this issue should now be resolved. I invite you to file a new issue if you run into other problems.

**Comment by filiphr** [comment]
Thanks. I am not on that project anymore, but will give it a try in another one. If there as any issues, I'll open a new one.

**Comment by mojavelinux** [comment]
Great!
