### ISSUE TITLE
docfile-like builtin for filename only

### ISSUE THREAD

**Issue by IanDarwin** [asciidoctor/asciidoctor#1673]
The _docfile_ built-in attribute actually produces the full path rather than the file, e.g,.
 /Users/ian/workspace/project/src/doc/ref/intro/0105-bleah.adoc.

It would be nice if there were a way to directly get just the filename, 0105-bleah.adoc

**Comment by mojavelinux** [comment]
You can get the basename from the attribute "docname". In your case, it would be "0105-bleah". If you always use .adoc as the AsciiDoc file extension, you can build it using `{docname}.adoc`.

I suppose we should add an attribute for infilesuffix (to complement outfilesuffix). Do you like that idea?

**Comment by IanDarwin** [comment]
Ah, docname isn't in the reference manual so I didn't see it.

I'm less concerned about the file suffix.

**Comment by mojavelinux** [comment]
Thanks for pointing that out @IanDarwin. I added it to the user manual.

I think we should still add docfilesuffix (rather than infilesuffix) for completeness.
