### ISSUE TITLE
Add support for checklist in table

### ISSUE THREAD

**Issue by dsisnero** [asciidoctor/asciidoctor#1674]
I have documents that have tables that have checkmarks for yes / no.  Would it be possible to have checkmarks in a table cell?

Example asciidoc

== Minimum EOSH Requirements
[cols= "80,10,10"]
|===
3+h| Project Plan Minimum EOSH Checklist
.2+h|Facility Procedures 
2+h|Applicable?
h|Yes*
h|No

|Asbestos Contingency Plan|[x] |
|Hazard Communications | [x] | 
|Lock Out/Tag Out| [x] | 
|Work Permits (e.g. Confined Spaces, Energized Electrical)| | [x]
|Emergency Plans (e.g. Occupant Emergency Plan)|  | [x]
|Impacts to Fire Alarm and Suppression Systems|  | [x]
|Confined Space Entry|  | [x]
|Restricted Areas Due to OSH|  | [x]
|Blood borne Pathogens|  | [x]
|Restricted Areas Due to OSH|  | [x]
|Fall Protection| [x] | 
|Arc Flash Analysis| | [x]
|Personal Protection Equipment (PPE)|[x]  | 

|===

**Comment by mojavelinux** [comment]
I'd recommend just using the underlying characters that the checklist uses. That's one of the following:

* icon:check[]
* \&#10003;
* +++&lt;input type="checkbox"&gt;+++

You can assign these as an attribute to make it easy to reference.

```
:y: &#10003;

{y}
```

We do something similar in the Asciidoctor user manual. http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc

I don't really see this as something that requires a change to Asciidoctor.

**Comment by dsisnero** [comment]
:chk: icon:check[]

worked perfectly!  Thanks

**Comment by mojavelinux** [comment]
Super!

**Comment by dsisnero** [comment]
I got mtex2MML and lasem included in the MSYS2 packaging system.
https://github.com/Alexpux/MINGW-packages/pull/3126

I need help getting the mathematical gem to compile under windows.

Please help


Thanks,

Dominic

**Comment by dsisnero** [comment]
I am trying to get Mathmeatical gem supported in windows.  I got lasem and
mtex2mml included in the MINGW-PACKAGE list to be able to install with
pacman

pacman -S mingw64/mingw-w64-x86_64-lasem

pacman -S mingw64/mingw-w64-x86_64-mtex2MML

I have forked mathematical and got it to create the makefile with my
changes to extconf.rb

ruby extconf.rb --use-system-lasem --use-system-mtex2MML

when I run make I get the following

n file included from mathematical.c:23:0:
./mathematical.h:12:10: fatal error: lsmmathml.h: No such file or directory
 #include <lsmmathml.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:242: mathematical.o] Error 1stem-lasem
--use-system-mtex2MML

So, for some reason the lasem header lsmmathml.h file is not included in
the header list for lasem

  I do not know autotools system very well.  If I could get help on the
patches to lasem 's Makefile.am file to include the headers needed for
mathematical we can get this gem to install on windows.

Here's my fork of the MINGW-PACKAGES which has lasem and mtex2mml that were
accepted.

https://github.com/dsisnero/MINGW-packages  look under the lasem and
mtex2mml directories.  I need to patch the lasem Makefile.am somehow to
include the needed headers

Thanks

dominic

**Comment by mojavelinux** [comment]
I'm closing as the original question was answered. If you need help with the mathematical gem, please file an issue in https://github.com/asciidoctor/asciidoctor-mathematical or https://github.com/gjtorikian/mathematical.

**Comment by SjoerdV** [comment]
Just to leave an additional option on the table. You can put table rows in 'asciidoc' mode and use default checklist method
```asciidoc
.title
[options="header,footer",width=100%]
|====
| COLUMN1 | COLUMN2 
a| * [ ] Unfinished | Stuff
a| * [x] Finished | Stuff
|====
```

**Comment by mojavelinux** [comment]
That looks really nice @SjoerdV. Thanks for providing that tip!
