### ISSUE TITLE
Infinite loop with list syntax

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1679]
The following syntax will cause Asciidoctor to loop infinitely:

```asciidoc
 * first item
 *. second item
```

NOTE: There's dot right after the asterisk in the second item

I'm not sure what the expected output for this "wrong" syntax but this should not cause an infinite loop. Tested with Asciidoctor 1.5.2 and Asciidoctor 1.5.4.

### Reproduction

```
$ echo -e " * first item\n *. section item" | asciidoctor -
```

```
$ asciidoctor -v
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Yikes! We'll get that fix and a test in place for 1.5.5.

**Comment by mojavelinux** [comment]
I was misunderstanding something about how repeat groups worked. I thought once it matched a character in a group, it applied the repeat to that match. Turns out, it looks for the group the specified number of times. Thus, `.*` was matching as the start of a list.

**Comment by mojavelinux** [comment]
To answer your question, the second line should just be treated as normal text.

**Comment by Mogztter** [comment]
Thanks Dan :smile:
