### ISSUE TITLE
Create a DocBook to AsciiDoc converter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#168]
All the raw material is there to create a DocBook to AsciiDoc converter. The DocBook source can be loaded using NokoGiri and translated into an Asciidoctor::Document. From there, we can either use a custom backend to output AsciiDoc or walk the nodes in Ruby code to generate the output.

**Comment by zaxebo1** [comment]
any update on this issue from year 2013 ?

**Comment by LightGuard** [comment]
Have you looked at docbookrx[1]? That's were effort is/will be for this
sort of conversion.

[1] https://github.com/opendevise/docbookrx

On Tuesday, April 19, 2016, zaxebo1 <notifications@github.com> wrote:

> any update on this issue from year 2013 ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/168#issuecomment-212180093>
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
I'm going to close this issue as soon as docbookrx graduates to the asciidoctor organization. For that to happen, I just need to merge a few pull requests and cut an alpha release.

**Comment by mojavelinux** [comment]
docbookrx is now in the Asciidoctor organization and doing quite well. All issues related to the conversion from DocBook to AsciiDoc should be directed there.

https://github.com/asciidoctor/docbookrx
