### ISSUE TITLE
HTML output for QuoteBlock has no trailing quotation mark

### ISSUE THREAD

**Issue by james-bostock** [asciidoctor/asciidoctor#1680]
Asciidoctor version 1.5.2 but, looking at the current version of the default .css stylesheet, I believe the issue is still present.

The HTML rendering for a QuoteBlock has an opening double quotation mark but no matching closing double quotation mark (see the attached zip archive which contains the AsciiDoc source and the HTML output generated by Asciidoctor).

I think that the output would look much better were the color and font size of the quote the same as the text that follows it.

[quote.zip](https://github.com/asciidoctor/asciidoctor/files/102713/quote.zip)

**Comment by mojavelinux** [comment]
Using a single quotation mark was a design decision for the default stylesheet. It's a popular style for showing blockquotes (for example, http://html5doctor.com/cite-and-blockquote-reloaded/). Of course, since it is being added by CSS, it's entirely possible to change this behavior using custom styles (either an override with docinfo or a separate theme).

**Comment by james-bostock** [comment]
Then I guess we can close this issue as WAD. Thanks for the rapid response.

**Comment by mojavelinux** [comment]
I'm open to discussing style changes. I was pointing out that using a single quotation mark was an intentional choice. If you have a reference to a style that you would prefer, I'd be open to considering it. But I need a reference because the ideas I had for it are what you see now.

**Comment by james-bostock** [comment]
There is no formal reference that I can point to (my expectations are conditioned largely by what I have seen in print), though I will look around to see if I can find one. Thanks again!

**Comment by mojavelinux** [comment]
Great! Some visual reference (screenshot, photo or other reference) helps because that's something we can bring to a designer as a requirement. I agree there's something about the shape of them that doesn't feel like we've nailed it yet, but as I mentioned, I ran out of ideas of what else to do with it.

**Comment by james-bostock** [comment]
I have done a bit of looking round and, as is not surprising, there is quite a bit of variety. In no particular order:

W3Schools.com says that most browsers will display block quotes with the following CSS properties:

blockquote {
    display: block;
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: 40px;
    margin-right: 40px;
}

http://www.w3schools.com/tags/tag_blockquote.asp

The AsciiDoc guide indents the text with a bar on the left: http://asciidoc.org/asciidoc.css-embedded.html#X94 (personally, I am not crazy about the bar as it makes me think of a document change mark).

The example in DocBook 5: The Definitive Guide is similar: http://www.docbook.org/tdg5/en/html/blockquote.html.

CSS-Tricks gives several examples of styling for block quotes: https://css-tricks.com/examples/Blockquotes/

Etc, etc :-)

**Comment by mojavelinux** [comment]
I'm not a fan of the left-hand bar either. That's what a lot of CSS frameworks use, such as Bootstrap.

What I'm interested in is how you want it to look. I have no trouble making it look anyway we want it to. I just don't know how else it should look (since the left-hand bar idea is out).

**Comment by james-bostock** [comment]
My preference would be for something along the lines of text indented relative to the body and possibly with a smaller font. If you like, I will play around a bit to see if I can come up with something concrete. However, the fact that no one else has complained about this (they haven't, have they) means that either they are all OK with the current behaviour or that they don't use block quotes.

**Comment by ecki** [comment]
I think the quote style is pretty fancy and bold. Thats not to my taste, but I can understand that I can adjust the template. However I wonder if we want to have a different style for a different type of quotes. One which is less like a personal statement (looking like a demotivational poster) but mir a subtle quote - in my case of a normative reference.

This is from https://github.com/ecki/habibi-passwordhash/blob/5f3d950448fd16fbcc473d79518a665bf355ddac/README.adoc

![image](https://cloud.githubusercontent.com/assets/361432/24085826/2c8e5dd0-0d03-11e7-8bd0-4983bfb7c3dc.png)

The GitHub style is (besides the source attribution) much more to my preferences for this kind of text:

![image](https://cloud.githubusercontent.com/assets/361432/24085865/d06f90c2-0d03-11e7-85fb-ae9f9c3d5f16.png)

**Comment by mojavelinux** [comment]
> I wonder if we want to have a different style for a different type of quotes.

I have encountered this need in my own writing, so :+1: to the idea. There's clearly a difference between a quote of what someone said and an excerpt from literature.

I'd say the common use case is a personal quote. What we can do is style the block differently if it has a dedicated role. I propose the role name "excerpt" for this purpose:

```
[quote.excerpt,NIST,SP 800-63b]
Verifiers SHALL store memorized secrets in a form that is resistant to offline attacks.
Secrets SHALL be hashed with a salt value using...
```

wdyt?

(As a side note, we're also discussing how to support the epigraph, another use of the quote block).

**Comment by mojavelinux** [comment]
Btw, if you'd like to pursue this change, we'll need a new issue to track it.
