### ISSUE TITLE
what is the difference between normal "anchor" and a "bibliography"

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1684]
I see in the document there is an example:

```
_The Pragmatic Programmer_ <<prag>> should be required reading for
all developers.

[bibliography]
- [[[prag]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
- [[[seam]]] Dan Allen. Seam in Action. Manning Publications.
  2008.
```

but with a normal "anchor" I tested and got the same thing:

```
_The Pragmatic Programmer_ <<prag>> should be required reading for
all developers.

[bibliography]
- [[prag]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
- [[seam]] Dan Allen. Seam in Action. Manning Publications.
  2008.
```

and I saved one bracket.

what is the design consideration on this?

**Comment by mojavelinux** [comment]
Technically they are different things. The difference is semantics. As a result, they produce different results in some converters (like DocBook). In HTML, they end up being functionally equivalent.

If you'd like more clarification on this topic, I recommend filing an issue in the documentation (currently https://github.com/asciidoctor/asciidoctor.org/issues).

**Comment by pinggit** [comment]
got it, so if I later need to convert to pdf, I think the [[[prog]]] works better. I'll test this out.
thanks.

**Comment by mojavelinux** [comment]
:+1:
