### ISSUE TITLE
Syntax highlighting for asciidoc broken?

### ISSUE THREAD

**Issue by andya9** [asciidoctor/asciidoctor#1695]
On highlight.js demo page I see that asciidoc is definetely supported. 
Still, when I run asciidoc with ```:source-highlighter: highlightjs``` my asciidoc code (marked using ```[source,asciidoc]```; i also tried AsciiDoc, markup and markup-asciidoc) doesn’t seem to be processed, whereas for example xml works perfectly. Am I doing something wrong?

A sample:

```
[source,asciidoc]
----
= My title

*Some bold text!*
----
```

will produce:

```
<div id="content">
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-asciidoc" data-lang="asciidoc">= My title

*Some bold text!*</code></pre>
</div>
</div>
</div>
```

EDIT: I also tried the other available highlighters, but none of them works for asciidoc.

**Comment by Mogztter** [comment]
Hello @andya9 

Asciidoctor is using cdnjs to serve [highlight.js](https://cdnjs.com/libraries/highlight.js) and only a handful of languages are included in this "bundle".

But you can download and use a custom version of Highlight.js then set the attribute `highlightjsdir` to a local directory: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L210

**Comment by andya9** [comment]
I’ll try it right now, thank’you very much

**Comment by andya9** [comment]
I closed the issue because it’s solved (it’s not broken, just not enabled).
Still, I couldn’t make it work no matter what. I compiled with `asciidoctor -a highlightjsdir=highlight` (highlight is the folder in current dir where i downloaded highlight.pack.js), and now no language is highlighted, not only asciidoc. I’m surely missing something? I tried also `asciidoctor -a highlightjsdir=highlight/highlight.pack.js`, and also with full path.

**Comment by abelsromero** [comment]
> But you can download and use a custom version of Highlight.js then set the attribute highlightjsdir to a local directory

I fear is not that easy. The Javascript and CSS for highlight JS have a different name than the on Asciidoctor assumes (min.js is now pack.js).

I got something working using a docinfo file to add the scripts/css manually but there are some issues with the background color.
What I did was:

1- Go to https://highlightjs.org/download/, mark AsciiDoc and download the package.
2- Unpack it next to my asciidoc file in a folder called 'highlight'
3- Create a file called `docinfo-footer.html` in the same directory as my asciidoc file with this content:
```
<link rel="stylesheet" href="highlight/styles/default.css">
<script src="highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```
4- Render **WITHOUT** any highlightning attribute, just add `docinfo1=true`.

That renders the AsciiDoc source blocks but created an additional margin around the section. Setting the attribute `source-highlighter=highlightjs` adds the default CSS and the margin is fixed...but this means adding two versions of highlight.js CSS (not a clean solution imho).

Regarding closing this issue, depends on the support we want to provide to highlight.js since rouge is on the way. But I we want to keep it, I think it make sense to keep it open and try to define a clean way to pack custom versions. Now that we know what to add to the footer, it should be easy.

**Comment by andya9** [comment]
@abelsromero I can confirm it works! Thank’you very much for diving into this.
My 2 cents on Rouge: when it lands here, maybe dismissing support for all the rest (pygments, coderay, highlightjs, ecc) would be better, so that energies are not wasted on something that doesn’t add anything. 
I myself looked into highlightjs only because it seems to be the only one supporting asciidoc yet, I’ll be more than glad to highlight server side with Rouge.

**Comment by mojavelinux** [comment]
>  The Javascript and CSS for highlight JS have a different name than the on Asciidoctor assumes (min.js is now pack.js).

Exactly. The easy solution is that you just need to rename the files after unpacking the highlight.js distribution. The simplest way to know what to name them is to generate the HTML and look at the path it is referencing. Here are the relevant bits from the generated file:

```
<link rel="stylesheet" href="highlight/styles/github.min.css">
<script src="highlight/highlight.min.js"></script>
<script>hljs.initHighlighting()</script>
```

Name the files the same and everything will work.

**Comment by mojavelinux** [comment]
We definitely want to make sure this is covered in the user manual. We are missing a section on highlight.js.

http://asciidoctor.org/docs/user-manual/#source-code-blocks

**Comment by mojavelinux** [comment]
> I think it make sense to keep it open and try to define a clean way to pack custom versions.

One way to address this is to use the distribution path when `highlightjsdir` is set and only use the CDN path when it is not. (I really wish highlight.js would follow some sort of standard so that it isn't different in different places).

**Comment by mojavelinux** [comment]
>  depends on the support we want to provide to highlight.js since Rouge is on the way.

These are orthogonal. We have to continue supporting both server-side and client-side highlighting libraries or else we break a lot of people. Dropping CodeRay for Rouge can be done transparently, which is why I have suggested that change.

**Comment by mojavelinux** [comment]
> I myself looked into highlightjs only because it seems to be the only one supporting asciidoc yet,

To be honest, there isn't a single highlighter that does a good job highlighting AsciiDoc. At best, it works with simple documents, but no one has really put in the effort to do it right. (except maybe Ace and Atom, but even they have a long way to go).

**Comment by andya9** [comment]
@mojavelinux I’ll add the relevant section in the user manual and do a pull request.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Note that there is a related discussion here: https://github.com/asciidoctor/asciidoctor/issues/1652

**Comment by andya9** [comment]
Thank’you very much!
