### ISSUE TITLE
combine [subs="quotes"] and [source,linux,linenums]

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1697]
is it possible to combine the two?

* [subs="quotes"] 
* [source,linux,linenums]

I tried it many ways and none works.
```
 [subs="quotes"] 
 [source,linux,linenums]
```

```
[subs="quotes",source,linux,linenums]
```

```
[source,linux,linenums,subs="quotes"]
```

I think it's because the `source` is for highlighters and only `subs=` are asciidoc attributes.
but anyway is there a way I can use both?

thanks.

**Comment by mojavelinux** [comment]
This is indeed possible. Your first way is correct, except you almost never set subs to an explicit value. Rather, you append (or prepend).

```
[subs=+quotes]
[source,linux,linenums]
----
...
----
```

The quotes has to come after the specialchars substitution or else the XML/HTML added by the quotes substitution gets escaped.

**Comment by mojavelinux** [comment]
If that doesn't work for you, please be more specific about what it is that isn't working. What do you expect the output to be and what is it?

**Comment by pinggit** [comment]
thanks. what you gave works:

[subs=+quotes]
[source,linux,linenums]
----
...
----


but what I used didn't:


[subs="quotes"]
[source,linux,linenums]
----
...
----


I'm still learning asciidoc tricks and don't know why , but I'm happy
with this working example.

thanks!
