### ISSUE TITLE
New block: details

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor#1699]
The new [`<details>` and `<summary>`](https://developer.mozilla.org/it/docs/Web/HTML/Element/details) elements are getting support on [firefox too](https://bugzilla.mozilla.org/show_bug.cgi?id=591737) as of latest nightly (47) – they already are on chrome, safari and opera.

Currently we can use an open block and a custom template, but I think it would be great implementing out-of-the-box support for them, as they can be very useful (they even got their official html element, so...)

Maybe it could be merged with the [Q&A](http://asciidoctor.org/docs/user-manual/#question-and-answer-style-list)?

**Comment by andya9** [comment]
Here the erb code to insert into the one provided into asciidoctor-backends:
```ruby
elsif role == 'details'
  if not title?
puts 'asciidoctor: WARNING: details block always needs a title'
end
  %><details>
      <summary><%= title %></summary>
      <%= content %>
  </details><%
```

**Comment by mojavelinux** [comment]
As defined by MDN:

> The HTML `<details>` element is used as a disclosure widget from which the user can retrieve additional information.

An AsciiDoc block lends itself well to this element. The details is clearly the block content and the summary the block title.

We can mark a delimited block as a details element by adding the `details` block style. All we need to decide is which structural container is most fitting.

The details element can support compound content, so the options are:

* open
* example
* sidebar
* quote

The open block clearly makes sense, but I don't think it should be the only one. I'm leaning towards the sidebar block.

````
[details]
****
These details are not disclosed on page load.
****
````

The details element is closed by default. We can use an option to make it open by default.

```
[details%open]
****
These details are disclosed on page load.
****
```

I'm open to other block style names, such as conceal, cover, coil, etc.

**Comment by mojavelinux** [comment]
> details block always needs a title

Actually, that's not true. The title is option. If one is not given, a default name is added by the browser.

**Comment by Foadsf** [comment]
Dear Dan @mojavelinux  I would appreciate if you could help me know how to have a collapsible part similar to the one I have mentioned [here ](https://github.com/asciidoctor/atom-asciidoc-preview/issues/200#issuecomment-473575038) but without HTML.

**Comment by mojavelinux** [comment]
After giving this more thought, I've decide what makes the most sense is to create the details/summary tag set from an example block if the collapsible option is set.

```
.Toggle Me
[%collapsible]
====
This content is revealed when the "Toggle Me" label is clicked.
====
```

The block will be open by default if the `open` option is also set.

```
.Toggle Me
[%collapsible%open]
====
This content is hidden when the "Toggle Me" label is clicked.
====
```
