### ISSUE TITLE
literal block and listing block

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1708]
I'm very confused by the usage of literal block.
1. what is the main difference of the two, from the final look? any examples?

![image](https://cloud.githubusercontent.com/assets/2038044/13401880/e0917c56-dedb-11e5-9186-e00092bb102a.png)

![image](https://cloud.githubusercontent.com/assets/2038044/13401895/ef695316-dedb-11e5-8303-793745e4d627.png)
1. also literal paragraph:
   ![image](https://cloud.githubusercontent.com/assets/2038044/13402081/b5d06670-dedc-11e5-889c-2d892c00da49.png)

without knowing the diff of usage case, I just think literal paragraph is more convenient, - you just indent the pasted texts grabbed from the log file , and no need to bother adding marks (----, eg). so I always prefer literal paragraph whenever possible. but when it comes to multiple paragraphs (make it a literal block?), I got this:

![image](https://cloud.githubusercontent.com/assets/2038044/13402219/59265550-dedd-11e5-957b-dbf31d553bd6.png)

when the expected result is :

![image](https://cloud.githubusercontent.com/assets/2038044/13402260/82fd081a-dedd-11e5-8e53-244228c3459f.png)

can I get some clarification of the diffs of these 2 block? and shall we fix this to make it consistent?

**Comment by mojavelinux** [comment]
Could I ask that you post these sorts of questions on the [discussion list](http://discuss.asciidoctor.org) instead? We want to reserve the issue tracker for actionable tasks. Before we get to something actionable in this case, we need to have a discussion about it. Thanks!

I do agree we need to establish patterns of usage for these different block types.

**Comment by mojavelinux** [comment]
Here's how I define the differences:

* listing - computer input
* source - a listing block that features syntax highlighting
* literal - computer output
