### ISSUE TITLE
Sidebar block cannot render section titles

### ISSUE THREAD

**Issue by rmpestano** [asciidoctor/asciidoctor#1709]
Hi guys,

I'm trying to add titles to a sidebar block:

```
****
= title1 

== subtitle
**** 
```

here is what asciidoctor 1.5.2 renders:

![sidebar](https://cloud.githubusercontent.com/assets/1592273/13549329/9917c380-e2e1-11e5-9061-f462d48cb769.png)

same output in firefox with asciidoctorjslivepreview 0.5.1 

It should work, right?

**Comment by rmpestano** [comment]
Just to clarify, my use case is to show rendered asciidoc content inside a "manual", something like asciidoctor user-manual

**Comment by mojavelinux** [comment]
You cannot put sections inside of other blocks as this would violate the structure rules of the document. However, you can create standalone headings that are effectively the same as section titles by adding the discrete style.

```
****
[discrete]
= title1 

[discrete]
== subtitle
**** 
```

We use this technique in the quick reference.

**Comment by rmpestano** [comment]
This will render in PDF backend? 
(can't test now)

Thank you!

**Comment by mojavelinux** [comment]
Yep!

**Comment by rmpestano** [comment]
This just works!

there is a way to style an entire block, eg: 

```
[discrete]
****
= title1 

== subtitle
**** 
```

**Comment by mojavelinux** [comment]
Nope. The block style doesn't get inherited.

Another approach is to put the AsciiDoc in an AsciiDoc table cell. That
creates a nested document. However, it won't work with Asciidoctor PDF yet.

**Comment by rmpestano** [comment]
Also I had to use [open blocks](http://asciidoctor.org/docs/user-manual/#open-blocks) styled as sidebar because I can have sidebar markup inside the 'discrete' block, eg:

```
[sidebar]
--
[discrete]
= Title
[discrete]
****
Inner sidebar 
****

more asciidoc content
--
```

it render as:

![openblocks](https://cloud.githubusercontent.com/assets/1592273/13553710/4f1de7ac-e370-11e5-9ffa-1d66a79ddd6d.png)

**Comment by rmpestano** [comment]
I will keep with the discrete class, adding it to every line of the open block content is not an issue in my case.

Thank you very much!

**Comment by mojavelinux** [comment]
You can vary the length of the delimiters to use the same block type nested inside another:

```
******
sidebar
****
nested sidebar
****
******
```

**Comment by rmpestano** [comment]
hmmm this is quite interesting :+1:
