### ISSUE TITLE
Implement showcomments

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor#1710]
In Asciidoc Python this caused single line comments to become DocBook remark elements. This was very useful when writing PDFs, as I could  insert notes for non-asciidoc reviewers.
There is an extension in the extension lab which would do; could it be added to the main distribution?

**Comment by mojavelinux** [comment]
I'm open to having some way to create remark elements in the DocBook output, but I don't want to tie it to comment lines. I think comment lines should remain in the source code only, just like in programming languages. Passing comment lines to the output changes their purpose (and breaks a contract, IMO). (Comment lines are also allowed in a lot of places that content is not allowed, so it's not a perfect 1-to-1 mapping).

I'd rather have a dedicated inline macro for this purpose.

**Comment by rockyallen** [comment]
Duplicate of #932, discussion continued in #1031
