### ISSUE TITLE
source code highlighting for shell/bash?

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor#1714]
Would any of the highlighters support ```sh``` or ```bash```? I tried the various names (sh, bash, shell) and ```source-highlighter```s to no avail.

    ```shell
    cat foo.txt
    ```

Thanks

**Comment by mojavelinux** [comment]
Pygments has support for various shell languages. See: http://pygments.org/docs/lexers/#lexers-for-various-shells (e.g., language=sh)

highlight.js has support for bash scripts (language=bash), but only what you'd find in a shell script.

Having said that, I've never really seen good syntax highlighting for shell commands. (I'm not even sure what I would expect).

NOTE: We are experimenting with something in the extension lab. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/shell-session-treeprocessor/extension.rb

**Comment by gliptak** [comment]
@mojavelinux Thank you. So what would be the right syntax (today) to get some ```shell``` highlighting?

Maybe highlighting keywords and commands (like [https://gist.github.com/agnoster/3712874](agnoster.zsh-theme)) could be a start?

![ohmyzsh_agnoster](https://cloud.githubusercontent.com/assets/50109/13729194/118686b0-e906-11e5-82c3-dc35d61da939.png)

**Comment by mojavelinux** [comment]
You'll need to take this issue/request upstream to the source highlighter you choose (Pygments, highlight.js, etc). Asciidoctor does not handle source highlighting. It simply delegates to a source highlighting library. So whatever features it has, Asciidoctor has.

Having said that, I do think what you're asking for is a nice idea. It's akin to a doctest (Python) or irb (Ruby) repl session, only for the shell itself. 

(The exception, as I mentioned, is that you could create a Treeprocessor that supplements what the source highlighter leaves behind, but that's really a final polishing step when there's no other option).

**Comment by mojavelinux** [comment]
You do at least get some basic highlighting of the shell prompt and comment lines when you use the following with Pygments:

    ```sh
    # print the contents of foo.txt to STDOUT
    $ cat foo.txt
    ```

So that's a start.

**Comment by gliptak** [comment]
@mojavelinux Thank you. I submitted https://bitbucket.org/birkenfeld/pygments-main/issues/1220/

**Comment by mojavelinux** [comment]
Super! We'll track the progress.

**Comment by jawira** [comment]
Only for documentation purposes: 

**Rouge** can handle **console** highlighting http://rouge.jneen.net/v3.22.0/console/

Initially I was looking for a way to display console command with white text over black background, but **rouge**'s highlighting is good enough.
