### ISSUE TITLE
Install dev version: libxml2 required

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor#1715]
Apologies if this is newbie error, but:
I followed the instructions for installing on Ubuntu using bundler (on Ubuntu 14.04 LTS), but it choked on Nokogiri. The 
Nokogiri home page does not cover the required version (1.5.11) but suggested looking in the document history, which eventually led me to 

 sudo apt-get install libxslt1-dev libxml2-dev

which worked.

Should this be added to the install instructions?

**Comment by mojavelinux** [comment]
Yes, but specifically on the contributing page as opposed to general installation. In other words, the end user should never need it, just developers.

In fact, the contributing page is missing the step to setup the project. So we should convert this issue into "instructions for preparing the project for development".

**Comment by mojavelinux** [comment]
Also related to #1407.

**Comment by tnir** [comment]
This can be closed now since we are using Nokogiri 1.10.x, which has vendored libxml2/libxslt library. cc @mojavelinux

**Comment by mojavelinux** [comment]
I agree this is outdated.

**Comment by mojavelinux** [comment]
Caching leads to results which are not reproducible and miss errors introduced by dependent gems. So we don't use gem caching in CI. While globally there may not be many people who have libxml2/libxslt, plenty of developers do and the performance improvements at install time are substantial enough to make a note of it. But beyond that, it's a reminder to myself ;)
