### ISSUE TITLE
Convert latex math/asciimath to mathml when outputting to html5 too

### ISSUE THREAD

**Issue by andya9** [asciidoctor/asciidoctor#1716]
I was wondering if it would be possible to let users choose whether outputting mathml or leaving it unprocessed in the html5 backend too (currently only in docbook).

Why:
* firefox users wouldn’t need mathjax
* all users would need javascript just to style the math, not to also produce it before styling (I don’t know of any benchmarks, but imo it’s the heaviest part of the workflow)

**Comment by mojavelinux** [comment]
Certainly an interesting idea! We currently don't have a way to convert LaTeX expressions to MathML, but we can use the asciimath gem to convert AsciiMath expressions to MathML.

We'd need to think about what attributes to introduce (or repurpose) to describe this behavior. Perhaps something like `mathjax!` or `mathml`?

**Comment by andya9** [comment]
imo mathml would be safer, so that the name doesn’t depend on the tool. 
Do you think that just doing it the only available behaviour would affect asciidoctor users negatively? Surely it wouldn’t break compatibility, as they are already using mathjax anyway; but maybe the conversion asciidoc > html would take significantly longer?

**Comment by andya9** [comment]
As for latex > mathml, I recall using mathjax as a nodejs cli tool successfully some time ago. But it would mean spawning an external process (and I don’t know how many users will already have / will want to have node + mathjax installed)

**Comment by mojavelinux** [comment]
> As for latex > mathml, I recall using mathjax as a nodejs cli tool successfully some time ago. 

Indeed. I've learned this is now possible. I'm now using it for the mathoid extension in the extensions lab. It uses https://www.npmjs.com/package/mathoid-mathjax-node.

I think the way we are going to proceed here is by handling this as an extension. By default, the HTML converter just passes the stem content to the HTML to be handled by MathJax. For different behavior, you'll load and configure one of the stem extensions. There's too many permutations for core to be handling them all. This is where extension shine.

**Comment by mojavelinux** [comment]
> there’s mathematical available as a ruby gem! but I never tried it

It works quite well, but is limited to TeX equations only (it does not yet handle AsciiMath).

**Comment by andya9** [comment]
Yes, I too think extensions are the way to go. It's unpleasant that ruby doesn't have a library for asciimath – python has a [good one](https://github.com/ShadowKyogre/python-asciimathml)

**Comment by mojavelinux** [comment]
Fortunately, we do. It's developed by our very own @pepijnve. See https://rubygems.org/gems/asciimath.

The asciimath gem just gets us to MathML. If used for HTML output, that would require that the browser support MathML...which is spotty. The next step would be to convert MathML to SVG.

**Comment by andya9** [comment]
Ahh, I totally missed it.. thank'you for telling me.
Why mathml > svg? doesn't mathjax just create the needed html + css on the fly when given mathml, latex or asciimath input?

**Comment by mojavelinux** [comment]
> doesn't mathjax just create the needed html + css on the fly when given mathml, latex or asciimath input

Yes, that's true. But there's no reason to convert from AsciiMath to MathML when using MathJax since MathJx will do that anyway. I mean, we could.

One of the challenges here is that there are many, many paths to get from input to output. That's why I think core should just provide one of those solutions and extensions should allow you to take other paths from A to B.

**Comment by andya9** [comment]
it's the best choice, yes. I close the issue as it's not relevant to core asciidoctor

**Comment by mojavelinux** [comment]
You can be sure we're going to keep pursuing those paths. We may be able to integrate the asciimath gem into asciidoctor-mathematical to handle AsciiMath expressions. Also, as soon as I have a few spare moments, I'm going to be setting up asciidoctor-mathoid, which brings MathJax into the processor ("server-side").
