### ISSUE TITLE
Create an integration branch with all the Gem dependencies 

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1719]
I'm getting closer to be able to build Asciidoctor.js without involving any Ruby. 
The last challenge is to resolve dependencies. I don't want to implement [Gem library](http://ruby-doc.org/stdlib-2.3.0/libdoc/rubygems/rdoc/Gem.html) in JavaScript using Opal. I think that would be a waste of time.

Instead, I was thinking maybe we could create an integration branch and use `bundle package` to copy all the dependencies into a directory: http://bundler.io/v1.2/bundle_package.html
If all the dependencies are in a well known directory, its become easy to resolve them and convert them to JavaScript using Opal.

@mojavelinux What do you think ?

**Comment by mojavelinux** [comment]
I would say yes, except Asciidoctor doesn't have any mandatory runtime dependencies. Is there something I'm missing?

**Comment by Mogztter** [comment]
Uh Oh! No I think you're right...
During my last attempt to build Asciidoctor.js in JavaScript, it couldn't resolve the following line `require 'set'` in [asciidoctor.rb](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L8) but this "dependency" is part of the stdlib... 

I will try to understand why this require wasn't resolved, sorry :unamused:

**Comment by mojavelinux** [comment]
:+1: 

We may have to consider an integration branch when we do get to the point of transpiling gems, though, like asciimath. We're just not there yet.

Side commentary: I find it extremely strange that Ruby doesn't require 'set' by default like it does for all other collection types. I would have thought that they'd fix that for Ruby 2, but they didn't.

**Comment by Mogztter** [comment]
The error message is:
```
MissingRequire: can't find file: "set" in [
"/home/guillaume/workspace/opensource/asciidoctor.js/opal", 
"/home/guillaume/workspace/opensource/asciidoctor.js/stdlib", 
"/home/guillaume/workspace/opensource/asciidoctor.js", 
"/home/guillaume/workspace/opensource/asciidoctor.js/lib", 
"/home/guillaume/workspace/opensource/asciidoctor.js/asciidoctor/lib"]
```

If I copy the `stdlib` from Opal in Asciidoctor.js root folder, then the problem is solved.

**Comment by mojavelinux** [comment]
I would expect Opal to provide the stdlib as transpiled files. However, given that we only need 2 files, I'm okay with just copying them over (or maybe we can download them at build time or use a submodule?)

**Comment by Mogztter** [comment]
"set" dependency is now resolved using the Opal compiler node package: https://github.com/Mogztter/opal-node-compiler/tree/master/src/stdlib
