### ISSUE TITLE
Introduce a header insertion point for docinfo

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1720]
Introduce a new docinfo location, header, which expands docinfo content above other content. In the HTML backend, this would go directly under the document title. In the DocBook backend, this would go above other content.

Look for a docinfo file with the prefix docinfo-header to expand to this location.

**Comment by mojavelinux** [comment]
Note that it's possible to implement this today by feeding a custom document template to the template converter.

**Comment by mojavelinux** [comment]
Open question: In the HTML backend, should the content go inside the `<div id="header">` element, and if so, should it be inserted as the first child or the last child?

**Comment by lodestone** [comment]
What else goes in the existing `<div id="header>` section?

**Comment by mojavelinux** [comment]
The document title followed by the author and revision info. Here's a snippet:

```html
<div id="header">
<h1>Document Title</h1>
<div class="details">
<span id="author" class="author">Author Name</span><br>
<span id="email" class="email"><a href="mailto:author@example.org">author@example.org</a></span><br>
<span id="revnumber">version 1.0.0,</span>
<span id="revdate">2016-04-05</span>
</div>
</div>
```

**Comment by lodestone** [comment]
Ok, I just tried to educate myself on docinfo as much as possible. I'm not sure I succeeded very well, but I wondered the following:

* What advantages does including it in the `#header` section have? Is it logically associated with that content or simply associated by name space (aka "header").

**Comment by mojavelinux** [comment]
I'll turn the question around. Where would you expect the docinfo header content to go.

The docinfo footer goes below the `<div id="footer">`. That tells us that the docinfo header should go below (or above) the `<div id="header">` to be consistent.

**Comment by lodestone** [comment]
From your question-turning-around, I would say ***after*** `<div id="header">`.

**Comment by mojavelinux** [comment]
Roger that! We'll move forward with after unless we hear counter arguments.

**Comment by ulehnerhs** [comment]
I would prefer that content right _before _ `<div id="header">`. 

In my specific case I would need it to add a custom header with a logo, some navigation and last release date right at the top of the documentation. So it should appear right before the document title.

Adding the custom content after the document title wouldn't make sense in my eyes. When generating a pdf or other paper format document, I would expect a customized and corporate designed top  before the title and the toc, preamble and all that stuff right after the title. 
When generating a html-output, I would expect my custom content at the very beginning of my html-document, right before the title. If I want to put some content after the title, I already can do that within my adoc-file and don't need the docinfo-mechanism. Dan, please correct me, if my experiences are wrong here.

Nevertheless, thanks for adding this feature!

**Comment by Phlow** [comment]
Today I worked the first time with `:docinfo:` and I love it. Because now I can build almost little websites with Asciidoctor. The only thing I ask myself, why isn't there a possibility to add some code right after `<body>`… Like @ulehnerhs commented, it would be great to add a navigation on top. Currently my navigation is in the footer, which is not so optimal of course ;) 

I can glue it with some CSS-wizardry at the top, but that's not very clean.

It would be great, if you would enhance this marvellous tool. With a bash-script I nearly have my little static website generator.

Thankyou very much for Asciidoctor.
