### ISSUE TITLE
Upgrade to Font Awesome 4.6

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1723]
https://articles.fortawesome.com/font-awesome-4-6-released-d7213342698a

**Comment by Mogztter** [comment]
This issue is perfect for new contributor. The corresponding line to update: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L77

**Comment by mojavelinux** [comment]
I'm super glad to hear that Font Awesome is working on accessibility. That really helps us out.
