### ISSUE TITLE
Deployment on github lacking features

### ISSUE THREAD

**Issue by kindlychung** [asciidoctor/asciidoctor#1727]
Please see this file: https://github.com/kindlychung/testGistDoc/blob/master/main.adoc 

So far I can see that  none of latexmath, asciimath, btn and menu are supported. That's a lot of things lacking. 

BTW, it looks ok on docgist: http://gist.asciidoctor.org/?github-kindlychung%2FtestGistDoc%2F%2Fmain.adoc

**Comment by jxxcarlson** [comment]
If you are using asciidoctor-latex (the html backend), you should say

$sqrt(4) = 2$
Water ($H_2O$) is a critical component.


i.e., don’t escape the dollar signs.

**Comment by kindlychung** [comment]
You were probably looking at the rendered result instead of the source: 

```

image::sunset.jpg[]

[source,ruby]
.app.rb
----
require 'sinatra'
get '/hi' do
 "Hello World!"
end
----

[stem]
++++
sqrt(4) = 2
++++


Water (stem:[H_2O]) is a critical component.


latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

kbd:[Ctrl+Alt+Delete]


btn:[Save]

menu:File[New > Folder > Private]

image::http://yuml.me/c9ce39b0.png[]
```

**Comment by mojavelinux** [comment]
Due to GitHub's strict policies for rendering content, the appearance is always going to be a bit lacking...or perhaps I should say it's an ongoing challenge to make it better.

> BTW, it looks ok on docgist:

That's why we created docgist ;)

I maintain the following sample up to date to demonstrate what works and what doesn't on GitHub. (Contributions welcome).

https://github.com/opendevise/asciidoc-samples/blob/master/runtime.adoc

Right now, the STEM support (asciimath, latexmath) doesn't work on GitHub because GitHub has not yet show a willingness to enable the necessary libraries.

The UI macros do work. However, you need to enable the `experimental` attribute in your document.

```
= Document Title
:experimental:

kbd:[Ctrl+Alt+Delete]

btn:[Save]

menu:File[New > Folder > Private]
```

The appearance is highly dependent on the GitHub stylesheet.

**Comment by kindlychung** [comment]
Ok, I see. I have also emailed support@github.com, they have appended this issue to their list.

In the mean time, I think it's highly desirable to have a chrome/firefox plugin that automatically redirects a asciidoc page on github to docgist.

**Comment by mojavelinux** [comment]
>  I think it's highly desirable to have a chrome/firefox plugin that automatically redirects a asciidoc page on github to docgist.

We don't have an automatic redirect, but if you click Raw you will be able to see the document in the Chrome or Firefox live preview extension.

What I tend to do is put a link to the docgist in the file itself, encouraging people to view it through that lens.

**Comment by kindlychung** [comment]
Unfortunately the chrome extension is not rendering the doc as well as docgist:

![](http://i.imgur.com/0L5bKjH.png)

**Comment by mojavelinux** [comment]
If you have an issue with the Chrome extension, please file it in the appropriate repository. => https://github.com/asciidoctor/asciidoctor-chrome-extension

**Comment by kindlychung** [comment]
Yeah, just did it. I am also working on a chrome extension for automatic redirection.

**Comment by kindlychung** [comment]
And here it is: https://github.com/kindlychung/docgistify

**Comment by zaxebo1** [comment]
@kindlychung : excellent . Can you upload it to chrome extensions store at https://chrome.google.com/webstore/category/extensions
and then put the url link to your final uploaded extension, in the https://github.com/kindlychung/docgistify/blob/master/readme.adoc

**Comment by kindlychung** [comment]
Oh, I need a google merchant setup for that. That will take a while.

**Comment by mojavelinux** [comment]
> And here it is: https://github.com/kindlychung/docgistify

Very cool!

Do you agree that all the points in this issue have either been resolved or accounted for in other repositories?

**Comment by kindlychung** [comment]
Yeah, feel free to close it.

**Comment by mojavelinux** [comment]
Thanks for reaching out to GitHub support to request better support for AsciiDoc content!

**Comment by kindlychung** [comment]
My pleasure. 😄
