### ISSUE TITLE
callouts get lost inside diagrams (if they have text to their right?)

### ISSUE THREAD

**Issue by jzacsh** [asciidoctor/asciidoctor#1728]
Given the following `callouts.adoc` file:
```
----

+---------------+
|               |
| i am an   <1> |
| ascii diagram |
|               |
+---------------+

<2>

----
<1> how does this part of the system work?
<2> happy, works!
```

# expected behavior
`asciidoc` handles this, exits 0, and renders some HTML like:
```html
<pre><code>+---------------+
|               |
| i am an   <b>&lt;1&gt;</b> |
| ascii diagram |
|               |
+---------------+

<b>&lt;2&gt;</b></code></pre>
```
# actual behavior
`asciidoctor` seems to lose track of where `<1>` has gone
```sh
$ asciidoctor callouts.adoc
asciidoctor: WARNING: callouts.adoc: line 12: no callouts refer to list item 1
```
And it renders markup like this:
```html
<pre>+---------------+
|               |
| i am an   &lt;1&gt; |
| ascii diagram |
|               |
+---------------+

<b class="conum">(2)</b></pre>
```
Of course, I'm assuming this is a bug _(ie: that `asciidoc` handling it well isn't a lucky accident)_. Feel free to just close this bug otherwise.

# debugging info
+ `asciidoc --version` outputs `asciidoc 8.6.9`
+ `asciidoctor --version` outputs:
```sh
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
_(installed on debian testing via `apt-get` from "Debian Ruby Extras Maintainers")_

**Comment by mojavelinux** [comment]
In Asciidoctor, callout numbers must appear at the end of the line. This is a constraint we added to avoid callout numbers from being matched where they shouldn't. AsciiDoc Python matches them anywhere, which was causing problems.

**Comment by mojavelinux** [comment]
I'll make sure this point gets added to the user manual.

**Comment by mojavelinux** [comment]
I've added documentation to the user manual to emphasize this point. See http://asciidoctor.org/docs/user-manual/#callouts

**Comment by jzacsh** [comment]
@mojavelinux can you briefly describe what problems are caused by matching anywhere? _(both because i'm curious and because it may be helpful for me/others when writing asciidoc)_

**Comment by jzacsh** [comment]
_(also, thanks for the quick response and doc update!)_

**Comment by jzacsh** [comment]
ah, ignore me :) _"the [section that follows](http://asciidoctor.org/docs/user-manual/#copy-and-paste-friendly-callouts) details these features"_
