### ISSUE TITLE
Add an inline menu macro to identify a menu selection

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#173]
Add an inline menu macro (for menu references and menu selections) as described in this AsciiDoc issue:

http://code.google.com/p/asciidoc/issues/detail?id=18

**Comment by magi42** [comment]
The currently implemented macro bugs if the first menu choice contains whitespace or other non-identifier characters (I encountered the problem also with `+`, `'`, etc.). For example: `menu:New Project[]`. Quotes around the target do not seem to help.

According to http://www.methods.co.nz/asciidoc/chunked/ch21.html, the target is not allowed to contain whitespace. It suggests using markup such as `%20` to handle such special characters, but A) it%27s%20not%20very%20neat%20to%20write%20text%20like%20that, B) such codes only work with one kind of output; the suggestion appears to be for URLs.

Hence, I'd suggest supporting `menu:[Some Menu > Some Item]`. For compatibility, you could still allow giving the first choice in the target, as it's now, but it shouldn't be required.

The freeform format `"A > B > C"` seems to work with whitespace and other characters fine, but it does not work for single-level menu choices, such as `"New Project"`. Yes, there are single-level menu choices sometimes, and it would be good to have same formatting for them as with other menu choices. Hence, the suggested format `menu:[New Project]` would help with that as well.

Should I create a separate ticket for the issue?

**Comment by magi42** [comment]
Also noticed that, while the freeform format allows whitespace, and some special characters in some cases, a menu choice may not begin with a special character. For example, `"+ > New"` doesn't work.

**Comment by mojavelinux** [comment]
The known workaround for this is to use a space attribute:

```
menu:Some{sp}Menu[]
```

That will work regardless of backend. I recognize it's not the prettiest syntax, but it gets the job done.

I will consider the `menu:[Some Menu]` syntax if you file a new issue (since this one is already complete).

The shorthand syntax isn't designed to work with a single menu or a menu choice that begins with a special character. It's intentionally designed for simple cases. Otherwise, we run the risk of matching normal text.

**Comment by Mo-Gul** [comment]
Is there a way to escape the `>` in a `menu` command?

This is "needed" when the menu entry depends on something, e.g. in the VBE of Excel on menu entry is `menu:Debug[Compile <project name>]` where `<project name>` is the corresponding project name. I'd say this is the usual approach to do so.

My current workaround is to use guillemets instead, i.e. `menu:Debug[Compile ‹project name›]`.

**Comment by mojavelinux** [comment]
Please ask questions in the project chat at https://chat.asciidoctor.org. Thanks.
