### ISSUE TITLE
Supporting callouts by line number

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor#1731]
Regarding source code blocks, in some cases, such as when a line continuation token (e.g.,`\`) ends the line, using a callout at the end of the line is not possible because it will break copy-pasting when not using font icons.

For example, this will not work when not using font icons (e.g., on GitHub).
```sh
find -type 'f' -name 'verylonglonglonglongline' \ ## <1>
-or -name 'verylonglonglonglongline' 
```
Quite a few issues have been reported related to callouts. What about an approach in which the author can specify callouts as an attribute of the source code block (e.g., pointing to line 2), instead of from inside it?

**Comment by mojavelinux** [comment]
It's a good idea. I think this is a duplicate (or closely related to) #598.

**Comment by sanmai-NL** [comment]
Thanks. Okay, I'lll leave it to you to close the ticket if you think that's best?

**Comment by mojavelinux** [comment]
I'll carry this idea over to #598 and mark this one as a duplicate.
