### ISSUE TITLE
Debian package is out of date, updating with gem installs parallel version in secondary path

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor#1732]
The Debian package for Jessie is still at 0.1.4. It's possible to use gem update to get 1.5.4 installed, but doing so results in /usr/bin/asciidoctor still being the 0.1.4 Debian version, while /usr/local/bin/asciidoctor is the new version.

Presumably there's some way to configure gem to overwrite the Debian versions (which might or might not be a desirable default), but as it isn't obvious this is what's happening, newbies such as myself get very confused trying to find the new version.

I suggest enhancing the README.adoc to note this issue.

**Comment by mojavelinux** [comment]
The rule of thumb is that `gem update` should never be used for a gem that is managed with a package manager. That gets you into undefined territory in the Linux world. That's true of all gems, but also for all module managers in other languages (Perl, Python, etc).

**Comment by mojavelinux** [comment]
> Presumably there's some way to configure gem to overwrite the Debian versions (which might or might not be a desirable default)

The answer is rvm. System gems should be managed only with the system package manager. User-space gems should be managed by rvm (or something equivalent). That's the position of the Asciidoctor project. We simply can't afford to support other scenarios because it's just too difficult to provide assistance.

**Comment by mojavelinux** [comment]
Asciidoctor 1.5.x is only in stretch and sid. We should link to the following page to show the full picture:

https://packages.debian.org/search?keywords=asciidoctor&searchon=names&suite=all&section=all

**Comment by oddhack** [comment]
@mojavelinux unfortunately, the advice given on the front page of the project for installation results in an out-of-date install, and trying to follow any other advice on that page apparently gets me into "officially unsupported" territory (I have no clue what "rvm" is, but it sure isn't mentioned there).

I'm not arguing with your policy, but the install advice given for Debian is simply not helpful or accurate, and should be fixed.

**Comment by mojavelinux** [comment]
I agree we need to provide better instructions and a more accurate description of the current state. There's just a certain way I'd like to explain it so it gives people the best path to success. Specifically, it's important to keep a clear separation between the system and user space, and to understand why there's a difference. If we aren't careful with those instructions, people can find themselves in hot water very quickly.

I'll submit a proposed revision to your PR.

**Comment by oddhack** [comment]
Cool. At the end of the day I just want to be able to run the current asciidoctor, without knowing anything about Ruby (which I, basically, don't), as I expect others do.

**Comment by Mogztter** [comment]
@oddhack Earlier this month, on the debian-ruby mailing list, someone ask for a backport of Asciidoctor to jessie:

>Hello,
I sent the message below to the alioth mailing list for
pkg-ruby-extras-maintainers a few days ago, but I don't see it in the
mailing list archives.

>If necessary, I could upload the backport, but I think it would be
better coming from the actual maintainers.

>Thanks and regards
>Afif

>على الأربعاء 30 آذار 2016 ‫23:04، كتب Afif Elghraoui:
> Hello,
> I understand that recent versions of asciidoctor have the capability to
> generate manpages. One package that I maintain for jessie-backports
> started doing so as well. I cannot continue to maintain the backport
> without a newer version of asciidoctor available in jessie unless I
> modify them to use another system.
>
> Users might also benefit from the backport, seeing as there is a big
> version jump between the version in jessie and testing/unstable. Would
> someone mind uploading it to jessie-backports?
>
> Many thanks for everything you do
>
> regards
> Afif
>

I will try to make it happen!

**Comment by mojavelinux** [comment]
While the Asciidoctor package still lags behind on certain distributions / distribution lines, the package is starting to move faster now (thanks to amazing community work) and a note has been added to the README. Therefore, I believe we can close this issue since there's nothing more we can do in this project.

Here's a list of which versions of Asciidoctor are available per Debian release.

https://packages.debian.org/search?keywords=asciidoctor&searchon=names&suite=all&section=all
