### ISSUE TITLE
Add max-height attribute on code block

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1738]
Long code block can take up a lot of space in a document. It would be great if we could set a `max-height` attribute on code block to control the space taken.

```
[source,java,max-height=200]
----
include::LongFile.java[]
----
```

Initial discussion: https://github.com/asciidoctor/asciidoctor/pull/1063#issuecomment-195861398

**Comment by mojavelinux** [comment]
I suppose this could be done using custom CSS and a role. It wouldn't give you control over the number of lines directly, but it could be a good page-wide solution.

**Comment by Mogztter** [comment]
I think this is a good enough solution :+1:

**Comment by mojavelinux** [comment]
It's probably something you want controlled globally anyway for visual consistency.

**Comment by mojavelinux** [comment]
Agree, the more I think about this, the more I'm convinced this is a presentation issue and should be handled either globally or via a role.
