### ISSUE TITLE
Replace gsub! and sub! in adjust_indentation method

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1739]
Currently, using `:tabsize:` in Asciidoctor.js throws an exception: `NotImplementedError : String#sub! not supported. Mutable String methods are not supported in Opal.`

If this method is not a hotspot I think we can safely replace `gsub!` with `gsub` and `sub!` with `sub`: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L2658

If this is not possible I will do it in Asciidoctor.js build.

**Comment by mojavelinux** [comment]
I think we've decided to handle this in the Asciidoctor.js build for now. It's really hard to insert an Opal guard at this point in the code because it would mean duplicating a lot of logic.

See https://github.com/asciidoctor/asciidoctor.js/issues/173

**Comment by mojavelinux** [comment]
We may revisit this in the future.
