### ISSUE TITLE
Can I use a variable in the code block? How?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#1741]
I define a variable as follows:

```
:var_gradle_version: gradle-2.13-bin.zip
```

I want to use the variable in a code block. The document content is as follows:

```
.Gradle links
----
distributionUrl=file\:///home/diguage/develop/tools/{var_gradle_version}
----
```

I try it. But it does not work.

**Can I use the variable in the code block?  How?**

Thanks a lot.

**Comment by robertpanzer** [comment]
Hi,

Source blocks do by default not apply attributes substitutions like described at the bottom of http://asciidoctor.org/docs/user-manual/#built-in-blocks-summary
(Source blocks use the verbatim substitutions.)

You want to try this to also apply attribute substitutions:
```
[subs="attributes"]
----
distributionUrl=file\:///home/diguage/develop/tools/{var_gradle_version}
----
```

Cheers
Robert

**Comment by diguage** [comment]
@robertpanzer This is OK. Thanks a lot.

**Comment by mojavelinux** [comment]
>     [subs="attributes"]

Almost right. You either need to use incremental subs:

>     [subs=attributes+]

or you need to provide all the other subs you want to keep

>     [subs="attributes,verbatim"]

The incremental subs are preferred.

**Comment by diguage** [comment]
@mojavelinux 
First, AsciiDoctor is a awesome project. Thank you. Thank all the people who contribute to the project.

You show me some subs. I knew the subs. But, **how I to find all the subs?**

**Comment by mojavelinux** [comment]
See http://asciidoctor.org/docs/user-manual/#applying-substitutions
