### ISSUE TITLE
How to set the code block start line number? 

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#1742]
I know how to set the start line number of the list. The example is as follows: 

```
// I copied the code from Hubert Klein's blog

// Start this list from 10.
[start=10]
.Start from 10
. Makes writing easy
// We can use it on all levels.
[start=10]
.. Keep focus
.. Syntax
. Different output formats
```

And I know how to show the code block line number. The example is as follows:

```
// I copied the code from Hubert Klein's blog, too.

[source,groovy,linenums]
----
// File: User.groovy
class User {
    String username
}
----
```

**I want to set the code block start line number. How to do it?**

**Comment by mojavelinux** [comment]
It's not currently possible. This is closely related to #1541.

Note that the line number offset will only work if the syntax highlighter supports it. However, several of the syntax highlighters we integrate with do support a line number offset, so we can certainly support it in those cases.

**Comment by diguage** [comment]
Today, I found a syntax highlighter wha could suppout to set the line number offset. 

It is [Prism](http://prismjs.com/). 

The plugins [Line Numbers ▲ Prism plugins](http://prismjs.com/plugins/line-numbers/) supports the feature.

**Comment by mojavelinux** [comment]
We're probably not going to support Prism. However, we do plan to support Rouge very soon, and it also has the ability to set the start line number.

https://github.com/jneen/rouge#full-options

**Comment by diguage** [comment]
A few days ago, I found the Pygments could highlight lines.

The example is as following:

```
[source,groovy,linenums,highlight='5,7-9']
----
package com.mrhaki
 
import static ratpack.groovy.Groovy.ratpack
 
ratpack {
    handlers {
        get {
            render "Hello World!" // <1>
        }
    }
}
----
<1> Render output
```


The article is [Awesome Asciidoctor: Highlight Lines In Source Code Listings](http://mrhaki.blogspot.com/2016/10/awesome-asciidoctor-highlight-lines-in.html)

**Comment by mojavelinux** [comment]
DocBook supports a starting line number, so we could start by mapping to that attribute (startinglinenumber).

**Comment by mojavelinux** [comment]
It turns out that Pygments also supports this. I'll go ahead and add support for it.

**Comment by mojavelinux** [comment]
CodeRay also now supports a starting line number.

**Comment by mojavelinux** [comment]
The name of the attribute that was chosen to set the starting line number is `start`.
