### ISSUE TITLE
How to set the translator?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#1755]
I know how to set the authors as follows:

```
= Doc Title
authorName <Emails>;...
```

How to set the translator? 

 I googled it, but I cound not find the answer.

**Comment by mojavelinux** [comment]
This is not something that is currently supported out of the box. You could simply define a custom attribute as follows:

```
:translator: Person Name
```

It would be up to you to reference this attribute somewhere in the document or customize the converter to add it to the document template.

**Comment by diguage** [comment]
I recommand :

```
:translators: Person Name; Person2 Name
```
