### ISSUE TITLE
Inconsistent expansion of attributes (and contained macros)

### ISSUE THREAD

**Issue by ygra** [asciidoctor/asciidoctor#1756]
Inline markup is legal in attributes and (usually) works fine. However, there are a few places where it breaks down. Given a document like this:

```asciidoc
:experimental:
:attr: kbd:[F1]

== {attr} Section

.{attr} Title
{attr} Paragraph

[title={attr} Title]
Paragraph
```

the attribute works just fine, just the embedded `kbd` macro doesn't work in section titles, or block titles. However, it *does* work in Block titles, when given as a `title` attribute in that block's attribute list.

Is all that intentional? Documented somewhere? A quirk in the implementation? Did I have to do something differently for that to work?

As a side note: I used the `kbd` macro here because, curiously enough, it works fine with the `pass` macro. In my use case where I noted this, it's actually a custom macro.

EDIT: The inline `image` macro also doesn't work, same as `kbd`.

**Comment by mojavelinux** [comment]
> A quirk in the implementation?

A quirk in the language specification. See https://github.com/asciidoctor/asciidoctor/issues/1173#issuecomment-61440584. I'd consider this a duplicate.

**Comment by ygra** [comment]
Oh nice, even with workaround. Then yes, this is pretty much a duplicate. Sorry for that.

**Comment by mojavelinux** [comment]
No problem! It's important to have a record of another case where this was confusion. It further proves my point that this difference in ordering seems arbitrary.
