### ISSUE TITLE
Mixing lists and checklists

### ISSUE THREAD

**Issue by k-mack** [asciidoctor/asciidoctor#1771]
Hi,

I'm currently making a bulleted list of items where some have checkboxes and some do not.

For example,

```
* 1st level bullet
** 2nd level bullet
*** 3rd level bullet
* 1st level with bullet
** 2nd level with bullet
*** [ ] 3rd level checkbox
**** 4th level bullet
*** 3rd level bullet
**** 4th level bullet
** 2nd level bullet
** [ ] 2nd level checkbox
** 2nd level bullet
* 1st level bullet
** 2nd level bullet
*** 3rd level bullet
```

It seems once a checkbox is entered at a level of the list, bullets are no longer rendered at that level or above until a top-level bullet is created again.

The reason why I am using a bulleted list with checkboxes is to create a hierarchical list of notes. Some notes require future action, so they are entered into the list with a checkbox. Some notes are just notes and do not require any future action, so they are entered as a regular list item.

I'm not sure if this is a bug. Maybe I am going against the design of checklists and regular lists?

**Comment by mojavelinux** [comment]
You're correct that when the checklist class is added to a list, it suppresses the bullet for non-checkbox items in the list. This behavior is controlled by the default stylesheet. If you want different behavior, you are free to modify the stylesheet to always show the bullets. That's not something we plan to change in the default stylesheet.

**Comment by mojavelinux** [comment]
I've filed #4499 to make the HTML easier to style.
