### ISSUE TITLE
I developed a Chrome extension: Copy as AsciiDoc.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#1775]
I developed a Chrome extension: [Copy as AsciiDoc](https://chrome.google.com/webstore/detail/copy-as-asciidoc/kabphjofkinmakglobecmbgpbopknobc)

The extension can copy the current page link and title as AsciiDoc. It helps me to refer the current page link.

My I contribute the extension to the AsciiDoctor project?

The code repo <https://github.com/diguage/ADL>

**Comment by mojavelinux** [comment]
Very cool. This is a nice addition to the ecosystem!

If you'd like this mentioned on the asciidoctor.org website, please submit a pull request to add it to a page. It probably fits best on the following page: http://asciidoctor.org/docs/#tools-and-apps-for-writing-and-editing

I also encourage you to post this information to the discussion list, which is where we make announcements about related projects and tools such as this one. http://discuss.asciidoctor.org/

**Comment by diguage** [comment]
I had post the information to the discussion list [Discussion - I developed a Chrome extension: Copy as AsciiDoc.](http://discuss.asciidoctor.org/I-developed-a-Chrome-extension-Copy-as-AsciiDoc-td4944.html)

**Comment by mojavelinux** [comment]
It's best to post this sort of announcement on the discussion list. We'll continue the discussion there.

**Comment by diguage** [comment]
@mojavelinux You mean is published in the mailing list?

**Comment by mojavelinux** [comment]
You did the right thing. You posted it to the mailinglist list. That's the best way to announce something (rather than using the issue tracker).
