### ISSUE TITLE
Gem spec git ls-files issue

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor#1779]
Hello,

In my system the following command https://github.com/asciidoctor/asciidoctor/blob/a5574c9743f9fab2a8fa0f434189e1c965453497/asciidoctor.gemspec#L19 doesn't return related directories and so, needed files  isn't moved to gems output. But, after rescue does work.

git version 2.8.1.windows.1

**Comment by mojavelinux** [comment]
The exclude keyword wasn't implemented consistently across git versions (and/or platforms). However, I'm pretty sure I've already fixed this in master. Are you still having a problem when using master?

**Comment by rahmanusta** [comment]
Sorry I shared the old line, yes I have problem when using the master.

For example the following line returns empty string

`git ls-files -z -- {bin,data,features,lib,man,test}/*`

**Comment by mojavelinux** [comment]
It seems to me like this feature of git is operating system dependent. If you can figure out a portable command that returns a list of files from the file tree, I'd gladly switch to it.

**Comment by rahmanusta** [comment]
`git ls-files -z -- {bin,data,features,lib,man,test}/* {CHANGELOG,CONTRIBUTING,LICENSE,README}.adoc Rakefile`

Could you please describe the parameters after the --, I will try to find a similar one for it.

**Comment by mojavelinux** [comment]
We want files that are known to git, but not all of them. We only want the files in bin, data, features, lib, man and test, plus a handful of files from the project root.

**Comment by rahmanusta** [comment]
Here is my pull request https://github.com/asciidoctor/asciidoctor/pull/1780

**Comment by mojavelinux** [comment]
Resolved with 1eca14f62ef0256b8cedcf82fe61b10b1747a10b and 7271e1321220afc5aecc0d9a4564aef82a117c4c.
