### ISSUE TITLE
Add linking to plugin pages in the home page

### ISSUE THREAD

**Issue by ADTC** [asciidoctor/asciidoctor#1782]
I noticed the Asciidoctor home page has these sentences:

> There are plugins available, based on AsciidoctorJ, that integrate the Asciidoctor processor into Apache Maven, Gradle or Javadoc builds.
> In addition to an AsciiDoc processor and a collection of stylesheets, the project provides plugins for Maven, Gradle and Guard and packages for operating systems such as Fedora, Debian and Ubuntu.

But none of the names have any links to the respective plugin pages. Example: [Maven](http://asciidoctor.org/docs/install-and-use-asciidoctor-maven-plugin/), [Gradle](http://asciidoctor.org/docs/install-and-use-asciidoctor-gradle-plugin/)

I found the Docs page has links for AsciidoctorJ, Maven and Gradle. But no mention of Guard.

The above was originally posted in asciidoctor/asciidoctor-gradle-plugin#188 where @mojavelinux replied:

> The asciidoctor.org home page is the README from Asciidoctor core. I agree these should probably be links. We'll need an issue in core to track this change.
> The Guard plugin is a bit in flux at the moment. It didn't materialize as well as we had hoped, mainly because better solutions came along. It should probably not be mentioned on the home page for now.

If you decide concretely what changes can be made, I'll make them on a fork and open a PR.

**Comment by mojavelinux** [comment]
I've proposed a change. See #2920.

**Comment by mojavelinux** [comment]
This will go live on asciidoctor.org automatically once 1.5.8 is released.
