### ISSUE TITLE
io/console not supported; tty will not be manipulated

### ISSUE THREAD

**Issue by tweinreich** [asciidoctor/asciidoctor#1783]
Hi,

When I run a gradle build (windows 10) that has the asciidoctor task to convert some json reports I get this error on the console:
```
io/console not supported; tty will not be manipulated
```
I already searched but found nothing useful on the mailing list etc. The error is not bad because all tasks get done as they should but I don't want it to annoy me in the future and maybe others ran into the same problem. Does anybody have a clue?

**Comment by robertpanzer** [comment]
Hi Thor,

it is indeed harmless.
It's not nice, but is coming from JRuby so we cannot do much about it at the moment: https://github.com/jruby/jruby/issues/1614 

Cheers
Robert

**Comment by tweinreich** [comment]
Hey @robertpanzer, thanks for the hint. So maybe the next Update will solve this.

Have a nice day,
Thor
