### ISSUE TITLE
rendering german vowels doesn't work

### ISSUE THREAD

**Issue by tweinreich** [asciidoctor/asciidoctor#1784]
Hi,

Today I tried to translate some of my templates but the german vowels 'ä', 'ö', 'ü' etc. don't get rendered correct. See this screenshot for the output:
![asciidoc_render_vowels](https://cloud.githubusercontent.com/assets/4059641/15705855/3d4e3278-27f1-11e6-8818-8802c8bd6ffc.png)

I already tried to add the language / encoding attributes to the head of my templates:
``` 
:encoding: ISO-8859-1
:lang: de
```
But it still get's rendered this way. Does anybody have an idea how to solve this?

**Edit:** Sorry that I opened this issue, it is not a bug in asciidoc. Seems that just the eclipse IDE converts/saves those characters in a strange way. After editing the files with Atom the characters were rendered correct.

**Comment by mojavelinux** [comment]
The editor should save the document as UTF-8 (or UTF-16). Asciidoctor assumes the document uses one of those two encodings. Otherwise, you can get broken output. The encoding attribute is not used in Asciidoctor (because we don't believe that's the right way to handle it).

**Comment by tweinreich** [comment]
And that makes perfect sense to me. It is just eclipse that uses cp1252 as default (mars, win10, german). If someone has the same problem just go to: Edit / Set Encoding and choose UTF-8.

**Comment by mojavelinux** [comment]
I'll update the README to hint that you need to do this in Eclipse. This really comes down to a colossal failure of Windows to not use UTF-8 by default in European installations (particularly German). It drives me insane that they do that. It makes absolutely no sense. But, such is life.

**Comment by tweinreich** [comment]
Yeah and the best part comes now: eclipse doesn't save this (in my case?). While going on coding it just switched back to cp1252 -.-

Searching for a global encoding option in windows leads to many crude hacks via editing the registry or creating some batch-scripts. I'm glad that I only use windows at my job :+1:
