### ISSUE TITLE
Getting positional attributes from a short inline macro

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor#1797]
I'm processing this `stem:[x^2]` inline macro in AsciidocFX in short format. I'm getting the text with target parameter. However, I optionally want to provide users to declare image name and extension like `stem:[x^2,abc,png]`. But in this way, inside the [] becomes target, I can't get the parts as positional attributes. How can I do that?

Thanks.

**Comment by mojavelinux** [comment]
This is an issue I've been meaning to file. Currently, it's not possible to specify how the contents inside the square brackets gets parsed in this case. I want to honor the following setting (which works if using the long format):

```ruby
parse_content_as :attributes
```

Until then, you must parse the attributes manually:

```ruby
process do |parent, target, attrs|
  attrs = (Asciidoctor::AttributeList.new target).parse if attrs.empty?
end
```

**Comment by mojavelinux** [comment]
In case I wasn't clear, you can get the positional attributes when using a long-form inline macro by setting the following option:

```ruby
parse_content_as :attributes
```

Alternatively, you have the option of parsing them yourself:

```ruby
parse_content_as :text
process do |parent, target, attrs|
  attrs = (Asciidoctor::AttributeList.new attrs['text']).parse
end
```

What we need to do is align the behavior of the long and short format inline macros.

**Comment by rahmanusta** [comment]
Thank you @mojavelinux, I couldn't test the codes you suggested yet, but it is okay in anyway for me, so I parsed attributes manually.

Best.

**Comment by mojavelinux** [comment]
With the upcoming fix, the short and long forms of the inline macro will work the same. The only difference is that for the inline macro, the target will be the (unescaped) value of the text between the brackets. If the content model is set to `:attributes`, that text will also be parsed into attributes. Otherwise, the (unescaped) value will also be assigned to the attribute named `text`.

**Comment by mojavelinux** [comment]
In 1.5.6, this will come as a standard feature.
