### ISSUE TITLE
Callouts renders differently from reference examples

### ISSUE THREAD

**Issue by pavs** [asciidoctor/asciidoctor#1800]
I was playing with asciidoctor examples from reference guide and callouts don't seem to work the same way as shown in reference examples here:
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

![screen shot 2016-06-18 at 6 40 25 am](https://cloud.githubusercontent.com/assets/3807064/16168033/b3c088a8-351f-11e6-97e5-7dffdb154a5b.png)

```
λ | Desktop: asciidoctor -V
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
You must set the icons attribute to the value "font".

```
:icons: font
```

See http://asciidoctor.org/docs/user-manual/#callout-icons.

**Comment by pavs** [comment]
Thanks it worked. Beautiful output, I can see myself using this.
