### ISSUE TITLE
Mixed line endings in html output

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor#1804]
When generating HTML, we are getting mixed line-endings like below. Do you have any idea for this issue?

Thanks

![image](https://cloud.githubusercontent.com/assets/1158804/16339713/cd96cfd2-3a2c-11e6-8286-65a07f34e42b.png)

**Comment by mojavelinux** [comment]
I am confident this is being causes by an extension. We explicitly test for Unix line endings in the test suite now.

**Comment by mojavelinux** [comment]
I'm also pretty confident this is not coming from core since core hasn't changed since before and after the versions in the AsciidocFX report.

**Comment by rahmanusta** [comment]
The reason is below;

In Asciidoctor.js, I'm seeing like below;

`result['$<<']("<style>\r\n" + (node.$read_asset(node.$normalize_web_path((node.$attr("stylesheet")), (node.$attr("stylesdir", ""))))) + "\r\n</style>")`

We are seeing here "\r\n" line ending

And, EOL constant is  Opal.cdecl($scope, 'EOL', "\n");

If we change it to Opal.cdecl($scope, 'EOL', "\r\n");

It fixes the issue

**Comment by mojavelinux** [comment]
> If we change it to `Opal.cdecl($scope, 'EOL', "\r\n");`

Oh, we definitely don't want to do that. We should be using "\n" everywhere. It's the other lines in Asciidoctor.js we need to fix:

> `result['$<<']("<style>\r\n"`

This shouldn't be happening. It might be because you are compiling Asciidoctor.js on a Windows machine. I don't see it this way in the git tag. Maybe Opal is replacing "\n" with "\r\n" when you compile it. It definitely shouldn't be. If it is, that is Opal overreaching.

**Comment by mojavelinux** [comment]
For reference, the git tag: https://github.com/asciidoctor/asciidoctor.js/blob/v1.5.5-1/dist/asciidoctor-core.js#L4737

**Comment by rahmanusta** [comment]
Yes, you are right. Do you have a short fix for me

**Comment by mojavelinux** [comment]
Use Asciidoctor.js from the tag?

**Comment by mojavelinux** [comment]
Another option would be to use a regex replacement of "\r\n" to "\n" after you build.

**Comment by rahmanusta** [comment]
I can't use from the tag because I've custom build for AsciidocFX, but as you said replacing output is a short cut.

**Comment by mojavelinux** [comment]
:+1:
