### ISSUE TITLE
Cooperation with DocOnce towards markup unification

### ISSUE THREAD

**Issue by dumblob** [asciidoctor/asciidoctor#1805]
I wonder why everybody tries to compare AsciiDoc mainly with other poor markups (including Markdown) when there is one markup which beats them all (in ease of use and features) - [DocOnce](https://github.com/hplgit/doconce).

Do you think it might be possible to cooperate a bit and improve both or either to increase compatibility, ease of use, and the list of features?

**Comment by dumblob** [comment]
By the way, in case someone wants to see a comprehensive yet easy to use wiki markup (e.g. for comparison with AsciiDoc), head over to [Phabricator Remarkup](https://secure.phabricator.com/book/phabricator/article/remarkup/ ). It's well engineered, but there seems to be no implementation producing e.g. A4-sized PDFs nor books.

**Comment by mojavelinux** [comment]
We welcome your participation in the AsciiDoc Working Group. https://accounts.eclipse.org/mailing-list/asciidoc-wg
