### ISSUE TITLE
Footnotes on paragraphs and section titles (headings) follow different numering sequences

### ISSUE THREAD

**Issue by jjkavalam** [asciidoctor/asciidoctor#1807]
> = Title
> 
> = Heading 1 footnote:[footnote #1]
> 
> Paragraph 1.footnote:[footnote #2]
> 
> = Heading 2 footnote:[footnote #3]
> 
> Paragraph 2.footnote:[footnote #4]

The footnotes 1 through 4 are expected to be numbered, well, 1 through 4. But, asciidoctor seems to distinguish the heading footnotes from the paragraph footnotes. This results in the rendered output having four footnotes numbered as follows (This was rendered on Chrome browser using Asciidoctor.js Live Preview extension version 1.5.4.110) :

![image](https://cloud.githubusercontent.com/assets/4114293/16491457/9ca6bf70-3f10-11e6-809c-ac1ce1cd1c7b.png)

**Comment by mojavelinux** [comment]
This issue has been duplicated in #2903. Let's continue the discussion there.
