### ISSUE TITLE
ifdef with inner include directive

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/asciidoctor#1808]
Hi

I'm having issues getting an include directive working within a ifdef macro call. Is this supposed to work?

I'd like to conditionally include a sub page within an adoc file depending on an attribute being set

Thanks

**Comment by mojavelinux** [comment]
Yes, this should work. Can you provide more specifics?

**Comment by Mogztter** [comment]
Hello,

Yes this is supposed to work. Could you please provide a sample ?

Thanks

**Comment by Mogztter** [comment]
Damn @mojavelinux is faster! 😫

**Comment by mattadamson** [comment]
Thanks both. I realised ifdef does actually work fine. I had this definition

ifdef::myattribute[]
	include::mypage.adoc[]
endif::myattribute[]

and

<myattribute>true</myattribute>

However I initially thought ifdef tested the attribute to be true however it's simply an existence check of the attribute being present at all. The ifval variant seems to be suited to that i.e.

ifeval::[{myattribute} == true]
	include::mypage.adoc[]
endif::[]

However this didn't seem to work i.e when the value was set to true. I also tried these variants

ifeval::[{myattribute} == 'true']
	include::mypage.adoc[]
endif::[]

and

ifeval::[{myattribute}]
	include::mypage.adoc[]
endif::[]

**Comment by mojavelinux** [comment]
When you are working with ifeval, you almost always want to quote both sides.

```
ifeval::["{myattribute}" == "true"]
include::mypage.adoc[]
endif::[]
```

Generally in AsciiDoc world, it's better to do booleans not by assigning a value, but by setting and unsetting the attribute.

on

```
:myattribute:
```

off

```
:!myattribute:
```

That allows you to use ifdef instead of ifeval.

**Comment by mojavelinux** [comment]
I found a related issue and filed an issue for it. See #2146.
