### ISSUE TITLE
Complex links (e.g. to Kibana visualizations) are not rendered correctly

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1809]
When embedding links to Kibana visualizations the URL gets corrupted in a way that is very difficult to detect.

Example:
Render a document containing this link:
```
http://localhost:5601/app/kibana#/visualize/create?type=line&indexPattern=sirona-*&_g=(refreshInterval:(display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-30m,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'role:%22cpu-user-time%22')),uiState:(),vis:(aggs:!((id:'1',params:(customLabel:'CPU%20user%20time',field:value),schema:metric,type:avg),(id:'2',params:(customInterval:'2h',extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1),schema:segment,type:date_histogram)),listeners:(),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,defaultYExtents:!f,drawLinesBetweenPoints:!t,interpolate:linear,radiusRatio:9,scale:linear,setYExtents:!f,shareYAxis:!t,showCircles:!t,smoothLines:!f,times:!(),yAxis:()),title:'Delete%20Refresh%20Token%20Response%20Time',type:line))
```
The result will contain this link:
```
http://localhost:5601/app/kibana#/visualize/create?type=line&indexPattern=sirona-*&_g=(refreshInterval:(display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-30m,mode:quick,to:now))&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'role:%22cpu-user-time%22')),uiState:(),vis:(aggs:!id:'1',params:(customLabel:'CPU%20user%20time',field:value),schema:metric,type:avg),(id:'2',params:(customInterval:'2h',extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1),schema:segment,type:date_histogram,listeners:(),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,defaultYExtents:!f,drawLinesBetweenPoints:!t,interpolate:linear,radiusRatio:9,scale:linear,setYExtents:!f,shareYAxis:!t,showCircles:!t,smoothLines:!f,times:!(),yAxis:()),title:'Delete%20Refresh%20Token%20Response%20Time',type:line)
```

While they look pretty much the same there are small diffs that make Kibana not open the visualization:
1. The original link contains `(aggs:!((id:'1',` while the rendered link looks like this `(aggs:!id:'1'` (Two opening braces missing)
2. `segment,type:date_histogram)),`is rendered to `segment,type:date_histogram,`
3. One trailing brace is also missing

I see it with Asciidoctor 1.5.4, with Asciidoctor.js in the Brackets plugin and on a Github Wiki.

**Comment by mojavelinux** [comment]
When embedding complex links, it's always a good idea to do one of the following:

1. Define the link in an attribute
2. Use an inline passthrough around the link

This is covered in the user manual. See http://asciidoctor.org/docs/user-manual/#complex-urls

**Comment by mojavelinux** [comment]
The only way we can avoid these workarounds in the future is to implement an inline parser :)

**Comment by robertpanzer** [comment]
Thanks! :-)

Sorry for not looking at the User Guide first… :-(

**Comment by robertpanzer** [comment]
For me only the last notation works.
I.e `link:++http://…..++[Open nice viz]`

The trick with the attribute suffers from the same problem (missing braces)

**Comment by robertpanzer** [comment]
Another solution is certainly to encode the URL correctly, i.e. in this case replace `(` with `%28` and `)` with `%29`.

**Comment by mojavelinux** [comment]
Attributes aren't a fail safe, just a more safe. The safest is the passthrough.
