### ISSUE TITLE
Shadow man pages not working properly

### ISSUE THREAD

**Issue by KI7MT** [asciidoctor/asciidoctor#1811]
Hello All,

I did a fairly extensive search, which yielded little by way of useful result, so I'm posting the question here.
AsciiDoc via docbook / xmlto has the ability to produce shadow manpages e.g.:

File name: page.1.txt
NAME
page1, page2, page3 - Description of page(s)

Then use:
a2x --doctype manpage --format manpage --no-xmllint page.1.txt

Using the following Asciidictor conversion:

asciidoctor -d manpage -b manpage page.1.txt

I get a file name with: 

'page1, page2, page3.1'

rather than
page1.1
page2.1
page3.1

I'm not sure if I'm doing something wrong with Asciidoctor or it's simply not capable of producing shadow manpages at this time.

Any assistance would be greatly appreciated.

best regards,

KI7MT

**Comment by mojavelinux** [comment]
Is this the same as multiple manpage names? If so, that is not yet implemented.

What would be helpful to implement this is a reference to how multiple manpage names should be interpreted. In other words, what are the acceptance criteria?

**Comment by mojavelinux** [comment]
There are three tasks at hand here:

* [ ] capture all manpage names into the mannames attribute
* [ ] convert each manpage name to a refname element in the DocBook output
* [ ] write a dedicated manpage for each auxiliary manpage name that imports to the primary manpage using the [so](https://www.gnu.org/software/groff/manual/html_node/I_002fO.html#index-so) request

AsciiDoc Python stores each manname in a dedicated indexed property (manname1, manname2). This is very hard for converters and other extensions manage. I've decided instead to store the value as an array in the mannames attribute.
