### ISSUE TITLE
Enhanced CSS styling

### ISSUE THREAD

**Issue by darshandsoni** [asciidoctor/asciidoctor#1812]
Asciidoctor makes it very easy to change the default look by including a stylesheet. But many users would not be familiar with this / don't want to get into CSS. This repository explains how styling works, allows users to browse through some popular stylesheets and has an API to allow them to test it out before using it in their documentation.

Check out [asciidoctor-skins](https://github.com/darshandsoni/asciidoctor-skins)

**Comment by mojavelinux** [comment]
Very nice. I encourage you to add this catalog as a suggestion on the following docs page:

http://asciidoctor.org/docs/#get-started-with-asciidoctor

We could also go deeper and either update [the page about the stylesheet factory](http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/) to be more generic or introduce a new page.

Either way, the right place to discuss this is the asciidoctor.org repository.

**Comment by darshandsoni** [comment]
Ahh perfect! Yes I wasn't sure where to put this so I figured I'd place it here till someone gave a recommendation. Let me port that over to the right place and you can close this.

**Comment by mojavelinux** [comment]
I'd like to be careful not to criticize the default stylesheet, especially since many people have said they like it. The problem is more that all documentation ends up looking the same if everyone uses the default stylesheet. In other words, it creates a monoculture. It's important to have additional choices that don't require much extra effort. To me, that's what this is about.

**Comment by darshandsoni** [comment]
I agree... The default isn't bad at all... like all defaults, it can just become monotonous. Let me rework that description...

**Comment by darshandsoni** [comment]
I've reworded the repo description. The repo is more clearly described as using the default as a base and "giving people choice" rather than criticising the existing defaults.

**Comment by darshandsoni** [comment]
Issue ported to asciidoctor.org

**Comment by mojavelinux** [comment]
Thanks @darshandsoni! I'll follow-up over there.
