### ISSUE TITLE
Add docbook orient="land" attribute for tables

### ISSUE THREAD

**Issue by Thoragan** [asciidoctor/asciidoctor#1815]
I want some tables in my document to be turned by 90 degree. In docbook I can simply use 'orient' attribute. Does asciidoctor supports it?

Example:
`<table frame="all" rowsep="1" colsep="1" orient="land">`

**Comment by mojavelinux** [comment]
Seems perfectly reasonable to me. Should we use the abbreviated terminology used by DocBook:

```
[orient=land]
|===
...
|===
```

or should we use the proper terminology?

```
[orientation=landscape]
|===
...
|===
```

I'd also be willing to support the landscape role:

```
[.landscape]
|===
...
|===
```

**Comment by Thoragan** [comment]
In my opinion, Asciidoctor trys to be readable alternative for DocBook. So second variant is more readable than first.
Landscape role is also good, but what DocBook.xml code will be produced if user already using this role for something other?

**Comment by mojavelinux** [comment]
:+1: 

> Landscape role is also good, but what DocBook.xml code will be produced if user already using this role for something other?

We'd still pass through the role, just act on it.

The other option for the shorthand is a simple option (since the default is portrait and there are only two modes).

```
[%landscape]
|===
...
|===
```

**Comment by Thoragan** [comment]
> The other option for the shorthand is a simple option (since the default is portrait and there are only two modes).

This is the best one, IMHO.
Also it is readable in full variant as
```
[options="header,landscape"]
|===
...
|===
```

I mentioned the similar DocBook syntax of lists in #1842.

**Comment by mojavelinux** [comment]
I thought about this a bit more and I like the explicit attribute, `orientation=landscape`, but I don't think we have the option name right. `landscape` is a value, not a switch. I think `rotate` is more appropriate as the name of the option. wdyt?

So the two ways of expressing it would be:

```
[orientation=landscape]
```

or

```
[opts=rotate]
```

also written as:

```
[%rotate]
```

If you have a better suggestion than rotate, I'd be glad to hear it.

**Comment by Thoragan** [comment]
`[%rotate]` is good, but it is not quite understandable is it rotating table clockwise or counterclockwise. That's why I like `[orientation=landscape]` more. But `rotate` option is good for shorthand.

**Comment by mojavelinux** [comment]
Excellent. Seems like we're on the same page. :+1:
