### ISSUE TITLE
Include macro with Firefox using WebExtensions API

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1833]
WebExtensions are available in Firefox 48. This is great news because this means that we can have a single code base (with few exceptions) for Edge, Firefox, Opera and Chrome/Chromium.

Most of the code of the [Asciidoctor Chrome extension](https://github.com/asciidoctor/asciidoctor-chrome-extension) is working in Firefox 48+ but I have a small issue with include macro using relative path.
#### Documents

a.adoc

```
= File a

include:b.adoc[]
```

b.adoc

```
File b
```

Both documents are in the same director (let's say `/foo/bar`).
#### Options

In the Asciidoctor Chrome extension we're using the following options:

``` javascript
var pwd = Opal.File.$dirname(href);
Opal.ENV['$[]=']("PWD", pwd);
return Opal.hash({
  'base_dir': pwd,
  'safe': safeMode,
  // Force backend to html5
  'backend': 'html5',
  'attributes': attributes
});
```

https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/app/js/renderer.js#L142-L150
#### Path resolver

We are using the following code in core to resolve relative URIs when running in Opal:

``` ruby
if ::RUBY_ENGINE_OPAL
  # NOTE resolves uri relative to currently loaded document
  # NOTE we defer checking if file exists and catch the 404 error if it does not
  # TODO only use this logic if env-browser is set
  target_type = :file
  include_file = path = if @include_stack.empty?
    ::Dir.pwd == @document.base_dir ? target : (::File.join @dir, target)
else
  ::File.join @dir, target
end
```

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/reader.rb#L837-L846

With this configuration `::Dir.pwd` and `@document.base_dir` are the same and `include_file` will be resolved to `b.adoc` (ie. we are _not_ appending the `base_dir`).

In Chrome, this is working fine and somehow the browser can find the file.
In Firefox, the browser can't find the file.

One way to fix this issue is to remove the line `Opal.ENV['$[]=']("PWD", pwd);`.
In this case, `::Dir.pwd` will be resolved to `.` and `@document.base_dir` will be resolved to `/foo/bar`, so the `include_file` will be `/foo/bar/b.adoc`.
Another way way to fix this issue is to remove the special condition and use `::File.join @dir, target`.

**Comment by mojavelinux** [comment]
Has this been resolved now that we a) fixed the default resolution behavior and b) added an API to write an IncludeProcessor extension in Asciidoctor.js?

**Comment by mojavelinux** [comment]
I believe this is covered by #2455, #2518, #2595, #2597, #2599, #2602, and/or #2610. If we find that there are still outstanding issues, let's start a new issue.
