### ISSUE TITLE
includes and sections not working

### ISSUE THREAD

**Issue by MrStiMu** [asciidoctor/asciidoctor#1834]
Hi,

I have a very simple setup:

index.adoc that includes an overview.adoc using the includes command/macro. Example

= My title

include::overview.adoc[]

The problem is that sections using the == prefix inide the overview.adoc are just rendered as paragraphs in the index.html page. When i goto the overview.html page is see them correct.

Is it normal that section headers do not work when used in an include?

**Comment by mojavelinux** [comment]
> Is it normal that section headers do not work when used in an include?

They are expected to work exactly the same way as they are when no include is used. The include expands the content in place, then the parser proceeds.

My guess is that you are missing a blank line above the section heading. A section heading (including any metadata lines above it) must follow a blank line.

In other words, the following does not contain a valid section heading:

```
content before
== Section Heading
content after
```

The following does:

```
content before

== Section Heading

content after (the blank line after the section heading is recommended, but not required)
```

**Comment by MrStiMu** [comment]
That you very much for the quick response! It was indeed like you suggested.

**Comment by mojavelinux** [comment]
:+1:
