### ISSUE TITLE
Font smoothing on firefox

### ISSUE THREAD

**Issue by pavs** [asciidoctor/asciidoctor#1837]
I am still fairly new to asciidoctor. I have noticed that on the default asciidoctor CSS file `-webkit-font-smoothing:antialiased;` was used for webkit browser but for firefox `-moz-osx-font-smoothing: grayscale;` is missing.

**Comment by mojavelinux** [comment]
My understanding is that `-moz-osx-font-smoothing` is deprecated. See:

* https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
* http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

If my understanding is incorrect, I'd be glad to make whatever changes are necessary. Could you provide screenshots to show that this property gets used in the latest Firefox?

**Comment by pavs** [comment]
From the links you gave, it is just saying that vendor specific CSS properties are not advised to be used because in the future if its gets removed then it will stop working on newer browsers. but this is also true for `-webkit-font-smoothing:antialiased;` After a quick search through the CSS file I found 6 Firefox specific CSS properties and 26 WebKit-specific CSS properties. Since we are already doing this, I don't see any reason not to use it this time.

According to Mozilla link:

> Though present in early (2002) drafts of CSS3 Fonts, font-smooth has been removed from this specification and is currently not on the standard track.

So it's likely they will be sticking to this for a long time.

Unless I am missing something obvious, I suggest we use it.

On Firefox 48, this property is being used please check under body.

![screen shot 2016-08-10 at 2 12 51 am](https://cloud.githubusercontent.com/assets/3807064/17531969/2718a660-5ea0-11e6-9b7c-53bc8cbaa4b2.png)

**Comment by mojavelinux** [comment]
Thanks for looking into this. It looks likes we should enable it then. When you enable it, do you notice a visual difference?

**Comment by pavs** [comment]
Yes very similar to how it looks under WebKit/chrome browser. I have checked both with and without it.  But without it under firefox, the text looks quite a bit sharp and thicker, that's why I am suggesting this to maintain consistency, at least in the two most popular browsers.

**Comment by Mogztter** [comment]
> Though present in early (2002) drafts of CSS3 Fonts, font-smooth has been removed from this specification and is currently not on the standard track.
1 Webkit implements something similar with a different name -webkit-font-smoothing and different values: none, antialiased and subpixel-antialiased.
2 Firefox implements something similar with a different name -moz-osx-font-smoothing and different values: auto, inherit, unset, grayscale.
3 Works only on Mac OS X platform.

http://caniuse.com/#feat=font-smooth

I tried on Windows but as stated by caiuse this only works on Mac OS X :unamused:

**Comment by pavs** [comment]
General font support is just horrible in windows all around regardless of the browser.

At the expense of going a bit off topic. Last year I installed windows10 to check out windows platform for the first time in about 10 years. I have been using only ubuntu and OSX all this time. My first reaction was how horrible the font rendering was (compare to other platforms), not only on the browser just the whole OS has really bad font rendering with jagged edges. So I used the windows 10 built-in chat support to ask if this is normal or if I am missing something. The response was this is how windows 10 font rendering looks. After googling around for about 30 mins and finding no reasonable solution I removed the OS right away.

My point is, IE browser might have come a long way in terms of standard compliance but font rendering remains horrible in windows platform, unfortunately.

**Comment by mojavelinux** [comment]
@pavs My observations exactly. I've also noticed that Windows has fallen far behind in font rendering. It also seems that font rendering is handled at the OS level instead of by individual applications, which is why the font smoothing settings don't apply on Windows.

>  I am suggesting this to maintain consistency, at least in the two most popular browsers.

:+1: 

We'll need to first update the asciidoctor-stylesheet-factory. I'll then take the output from there and merge it into this repository.

**Comment by mojavelinux** [comment]
Here's the line that needs to be updated:

https://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/sass/components/_asciidoc.scss#L34

Let's drop the use of `@extend .antialiased` and just add the two properties directly.

**Comment by mojavelinux** [comment]
For the record, here's another article on the subject.

https://davidwalsh.name/font-smoothing
