### ISSUE TITLE
Create an epub 3 backend or export

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#184]
epub 3 is the HTML 5 of mobile books. Explore whether an epub3 backend would be feasible in Asciidoctor (to avoid having to go through DocBook to get there).

**Comment by benhourigan** [comment]
Not sure it’s safe to close this issue given that asciidoctor-epub no longer processes all .adoc files. https://github.com/asciidoctor/asciidoctor-epub3/issues/25

Pandoc looked like a good alternative but because the `h1` tags, etc. are wrapped in divs, it's not possible to split an asciidoctor-generated HTML file at chapter headings when producing an ePub.

**Comment by mojavelinux** [comment]
This is closed because we decided it's not an issue with core. That doesn't mean the EPUB3 converter is done (after all, it's still alpha), it's just going to be a separate module. Unfortunately, I don't have time to focus on the EPUB3 converter at the moment, but it is in the plan in the near future.

**Comment by benhourigan** [comment]
Ah, okay—probably should have realized the two projects were coordinated. Seems like there's good progress being made at pandoc in the interim.

**Comment by mojavelinux** [comment]
Yep, it's definitely correlated. It's good to see pandoc moving forward too, but pandoc is completely outside of the Asciidoctor ecosystem and following its own path. Of course, if there's something pandoc does that is interesting to implement in Asciidoctor EPUB3, don't hesitate to file an issue at https://github.com/asciidoctor/asciidoctor-epub3. As the Asciidoctor fundraising campaign becomes more successful, I'll be able to dedicate more time to modules like Asciidoctor EPUB3.

**Comment by benhourigan** [comment]
Is there anywhere users can donate at present?

**Comment by mojavelinux** [comment]
Oops, I forgot to paste the link. https://salt.bountysource.com/teams/asciidoctor

**Comment by mojavelinux** [comment]
Thanks for the support @benhourigan! As you can see on the overview page, EPUB3 is on the initial roadmap and I'll be sure to get the linked bug fixed as soon as I pick up the EPUB3 converter again. I don't anticipate it being a hard issue to fix...just something that requires putting my head into it.
