### ISSUE TITLE
http://discuss.asciidoctor.org/

### ISSUE THREAD

**Issue by ojn** [asciidoctor/asciidoctor#1845]
I wanted to register on the forum and looks like it doesn't use https. May I suggest this solution: 
http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/
They have Let's Encrypt support so you wouldn't need to pay for certs.

I quite like  their software and setting it at my own server at the moment. I hope you will move away from Nabble for something better.

**Comment by usermail** [comment]
Suggestion for discuss.asciidoctor.org

**Comment by Mogztter** [comment]
Hello @usermail 

> I quite like their software and setting it at my own server at the moment. I hope you will move away from Nabble for something better.

Indeed, we do want to migrate from Nabble to Discourse but we didn't manage to find the time to complete the migration: https://github.com/asciidoctor/asciidoctor.org/issues/304

Any help would be greatly appreciated :smile:

**Comment by mojavelinux** [comment]
> but we didn't manage to find the time to complete the migration

I'll also admit that I've been hesitant because I'm very concerned it's going to wreck my workflow. I rely heavily on replying by e-mail (as do others on the list). I've been participating in several other communities that use Discourse and I'm forced to have to use the web interface to reply. That introduces a lot of overhead that I can't afford.

I have yet to discover a solution that allows me to send and receive messages to Discourse through an e-mail gateway. Until we can figure this one out, I'm hesitant to move forward.

**Comment by mojavelinux** [comment]
Since Let's Encrypt now supports DNS (TXT) verification, I think we might be able to enable this now. I'll at least give it a shot to bridge the gap until we move forward with the migration.

**Comment by mojavelinux** [comment]
I created the cert and verified it, but I don't see where in Nabble to put it. If someone knows, please feel free to provide guidance.

**Comment by mojavelinux** [comment]
This page details how to do it: http://greghelp.991552.n3.nabble.com/Embedded-Forums-and-https-td4012846.html

What it comes down to is that you have to request SSL to be enabled. I have made that request here: http://support.nabble.com/Https-Protocol-Request-tp7600969p7604191.html

**Comment by nkalvi** [comment]
Great! We will wait and see 😄

**Comment by nkalvi** [comment]
[Https enabled.](http://support.nabble.com/Https-Protocol-Request-tp7600969p7604196.html)

And https://discuss.asciidoctor.org is working (including the registration page.)

You may want to update the links on the main page after some time.

**Comment by mojavelinux** [comment]
This is absolutely fantastic news! Thanks for pushing on this, @nkalvi!
