### ISSUE TITLE
Bug when rendering source callouts to html with subs="attributes"

### ISSUE THREAD

**Issue by matthewadams** [asciidoctor/asciidoctor#1857]
The following source,
```
[source,sh,options="nowrap",subs="attributes"]
----
$ mkdir myapp && cd myapp                        <1>
$ docker run -it --rm --user node \
  -v "$PWD":/app --entrypoint bash \
  yaktor/node:{yaktorNodeDockerTag} -c \
  'npm install yaktor && $(npm bin)/yaktor init' <2>
$ ./yak gen-src gen-views start                  <3>
----
<1> Create & change into new app directory
<2> Initialize Yaktor application (alias this?)
<3> Generate source & views then start app
```
produces incorrect HTML. Notice the callouts in the left cell are of the form `<1>` instead of the expected images:
![image](https://cloud.githubusercontent.com/assets/449952/18135312/1e40de68-6f67-11e6-9465-027bf9dcfb49.png)

If I simply remove the `,subs="attributes"` from the header (and replace the attribute reference `{yaktorNodeDockerTag}` from the contents), making the source
```
[source,sh,options="nowrap"]
----
$ mkdir myapp && cd myapp                        <1>
$ docker run -it --rm --user node \
  -v "$PWD":/app --entrypoint bash \
  yaktor/node:0.39.0 -c \
  'npm install yaktor && $(npm bin)/yaktor init' <2>
$ ./yak gen-src gen-views start                  <3>
----
<1> Create & change into new app directory
<2> Initialize Yaktor application (alias this?)
<3> Generate source & views then start app
```
it renders correctly:
![image](https://cloud.githubusercontent.com/assets/449952/18135356/486eeff4-6f67-11e6-81ee-434bc845fe93.png)
Further, the invocation yields warnings:
```
asciidoctor: WARNING: index.adoc: line 19: no callouts refer to list item 1
asciidoctor: WARNING: index.adoc: line 20: no callouts refer to list item 2
asciidoctor: WARNING: index.adoc: line 23: no callouts refer to list item 3
```
Vitals:
```
$ asciidoctor --version
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ uname -a
Darwin newt.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

**Comment by robertpanzer** [comment]
Hi Matthew, 

Like this you set the substitutions to ONLY substitute attributes.
Instead you should ADD the substitution for attributes like this:

[source,sh,options="nowrap",subs="attributes+"]

Cheers
Robert

**Comment by matthewadams** [comment]
Can you please point me to the doc on that?

**Comment by robertpanzer** [comment]
Hi Matthew,

You can find the explanation here:
http://asciidoctor.org/docs/user-manual/#incremental-substitutions

Cheers
Robert

Am Mittwoch, 31. August 2016 schrieb Matthew Adams :

**Comment by janicecmt** [comment]
Is there a way to do this without having < and > get switched to &gt; and &lt; - the value of my variable contains these symbols. When I just use [subs="attributes"] I get the expected value, but when I add the + they get substituted as &gt; and &lt;.

Note that when I do this without using the variable and not setting a substitution (just in a plain vanilla block), I get < and > so using the + does not just reset default substitutions but adds some extras.
