### ISSUE TITLE
Trailing comments break header attributes

### ISSUE THREAD

**Issue by stefanct** [asciidoctor/asciidoctor#1858]
I was preparing a showcase asciidoctor file and thus commented it heavily. And that actually broke some of the attributes. For example to get font-awesome support adding

`:icons: font`

works fine, while the following unexpectedly breaks:

`:icons: font // for this bug whitespace before the comment doesn't matter nor contents of this comment`

A comment on the next or previous line works fine. This is with Asciidoctor 1.5.4.
I have noticed that the same is true for other attributes as well but have not tested it rigorously.

**Comment by mojavelinux** [comment]
Lack of support for trailing line comments isn't limited to attribute entries. AsciiDoc doesn't support trailing line comments in general. Line comments must start at the beginning of the line:

```
// a comment about the next attribute entry
:icons: font
```

If we do decide to support trailing line comments, the question would be where? I suppose it's reasonable to limit their scope to attribute entries. It would probably be too risky to support them on any line since it could easily be mistaken for content, though I have thought about it on multiple occasions.

**Comment by stefanct** [comment]
I had to resist the urge to just reply with wtf to be honest... :) This seems to be the most trivial thing - not only for implementation but also for users to grasp. Who should confuse them with content really? Who would not expect line comments to start at any point in a line and continue till the end of the line. It's not like there are many languages supporting single-line comments that do handle them differently. I was obviously completely perplexed by the fact that the aren't working that way. :)

**Comment by jirutka** [comment]
Trailing comments are common in _programming_ languages, but AsciiDoc is not a programming language. Trailing comments may be really problematic here.

**Comment by stefanct** [comment]
Latex.

The only problem I perceive is that it would potentially lead to regressions in case someone really has used `//` in the middle of a line in an existing document (which I deem rather unlikely at least outside links and monospaced blocks).

In any case the behavior should be described in the manual... the current documentation does not give the slightest hint about being limited that way and thus will confuse anybody with some programming experience (which in my limited sample of about 25 asciidoc writers comprises 100%).

**Comment by mojavelinux** [comment]
The general discussion about adding trailing comments is now a dedicated issue. See #991.
