### ISSUE TITLE
Allow CSS file to be written even for HTML string output

### ISSUE THREAD

**Issue by sschuberth** [asciidoctor/asciidoctor#1859]
When Asciidoctor is asked to convert to an HTML string, the HTML code refers to the `asciidoctor.css` file which does not get written in this case. I think two things should change:
1. For HTML string output, the default should be to inline the CSS code to not break the rendering.
2. It should be possible to override this default behavior by still writing the CSS code to a file, or alternatively introduce a function that returns the CSS code as a string.

As a side note, I need this functionality in the context of AsciidoctorJ.

**Comment by abelsromero** [comment]
Could be I am wrong, or that you found a bug with some configuration, but all options mentioned (except for `introduce a function that returns the CSS code as a string`) are possible. Can you share what code are you using?

By chance, I had this snipped that generates the HTML in a String with the default inline CSS and it works on my machine (Asciidoctorj  1.5.3.2).

```
        Asciidoctor asciidoctor = Asciidoctor.Factory.create((String) null);
        
        AttributesBuilder attributes = AttributesBuilder.attributes();
        attributes.tableOfContents(true);
        attributes.tableOfContents(Placement.LEFT);

        OptionsBuilder options = OptionsBuilder.options();
        options.safe(SafeMode.UNSAFE);
        options.attributes(attributes);
       /* When generating to String headerFooter must be set to true because it is assumed the String will be embedded into another content and Headers are omitted. */ 
       options.headerFooter(true);
 
        options.backend("html5");
        setSourceHighlighter("html5", attributes);

        String source = IOUtils.readFull(new FileInputStream(file("sample.adoc")));
        String output = asciidoctor.convert(source, options);
        /* Following line generates inplace file */
        // String output = asciidoctor.convertFile(file("sample.adoc"), options);

        FileUtils.writeStringToFile(new File("my-output.html"), output);
*/

**Comment by abelsromero** [comment]
_Apologies, external issues, I had to disconnect. Here follows the answer._

Note that in the previous example, no CSS options are used, so by default it is inline.
To generate the HTML linked to the CSS in a separate file you need some extra configuration and there are some limitations.

If you want just to generate the HTML in a String with the css linked like this
```
<link rel="stylesheet" href="./asciidoctor.css">
```
use `attributes.linkCss(true);`, to modify the path (in case you already have the CSS in some place), use `attributes.stylesDir("somePath");`.

If you want to generate both HTML and CSS at the same time, then you need to output directly to a File. Following the previous example, just add this options (toFile is required if you convert from String)
```
        options.mkDirs(true);
        options.toDir(new File("build"));
        options.toFile(new File("output-" + System.currentTimeMillis() + ".html"));
```
In this case, you will get both the html and the css linked and in separated files, but output variable will be null.


Note: beware with `attributes.styleSheetName("path/myCSS.css")`. Asciidoctor includes some CSS to googlefonts and with this options those are removed. Use `stylesDir` if you just want to set the path and you're happy with the default css name.

**Comment by sschuberth** [comment]
Thanks for your explanations and sorry for not finding the time to come back to you earlier. The background is [this change](https://gerrit-review.googlesource.com/#/c/83613/1/lib/asciidoctor/java/AsciiDoctor.java) of mine in Gerrit. I wanted to avoid creating temporary HTML output files and directly create ZIP entries from HTML strings. The HTML strings should link to the CSS file and not have it inlined. However, as noted by one of the reviewers, "asciidoctor.css" is missing from the resulting ZIP file.

So, are you saying the only thing I need to do in order to fix this is to set `attributes.linkCss(true);` and maybe `attributes.stylesDir("somePath");`?

**Comment by mojavelinux** [comment]
Asciidoctor does include the CSS inline by default, but you have to set the safe mode. The default safe mode is very conservative and does not read files. Therefore, you should set the safe mode to "safe" or "unsafe" (safe is usually sufficient). Then, no matter how you load the content into Asciidoctor, it will put the CSS inline by default.

Here's an example in Ruby code:

```ruby
require 'asciidoctor'

source = %(content)

html = Asciidoctor.convert source, safe: :safe, header_footer: true

puts html
```

You'll see that the CSS is included in the HTML.

> It should be possible to override this default behavior by still writing the CSS code to a file, or alternatively introduce a function that returns the CSS code as a string.

This is all possible. You can control whether the CSS is embedded or linked using the linkcss. If you want to capture the CSS, then you can use the Stylesheets class.

```ruby
Asciidoctor::Stylesheets.instance.write_primary_stylesheet '.'
```

The stylesheets interface may not be exposed to AsciidoctorJ yet, but perhaps we can consider it.

I agree that perhaps it should be possible to get Asciidoctor to write the stylesheet to disk even when streaming the output, though that's a really specific edge case that can perhaps be handled better another way. We want to try to avoid creating files if the primary interface is not writing a file.

**Comment by sschuberth** [comment]
Thanks again for the examples. For now my request turned obsolete as in my use case we now *do* want to write the HTML files, as the Zip file containing the docs may or may not be created depending on some runtime argument to our tooling. This means the optimization to not write HTML files to disk in case of creating the Zip file is not valid anymore, which is why I'll close this issue.
