### ISSUE TITLE
Attribute scope of included files

### ISSUE THREAD

**Issue by montrivo** [asciidoctor/asciidoctor#1863]
I have documentation spread across different projects at different folder levels. The documents are split in small chunks and are aggregated into bigger documents with multi level includes. Due to asciidoctor resctrictions, the paths need to be relative because I want to be able to process each file as standalone (basedir includes) or included files (relative includes). To help structure the documentation, at the beginning of each document I set a few attributes referring document directories in different projects. 

The problem is that included files' attributes override the parent file's attributes. I'd like to be able to define a `projects_location` attribute in each file header without overriding attributes if the file is included into another one.

**Comment by mojavelinux** [comment]
This is possible using an ifeval preprocessor directive. You just need to check if the name of the current file matches the `docname` attribute. The only way I can think to do it at the moment is to hardcode the name of the current doc.

```
ifeval::["{docname}" == "include-file-name"]
// define "local" attributes here
endif::[]
```

Another trick is to just check if the attribute is already set before defining it.

```
ifndef::attribute-name[:attribute-name: value]
```

It's important to remember that include files are not sub-documents or scoped. They are simply expanded in place as the reader touches the line...just like an include directive in C.

Of course, it is possible to implement custom include behavior using either an IncludeProcessor or by implementing a custom block macro.

Eventually, we want to be able to define the infile and indir attributes dynamically, which are only set for the lines of an include file, but the current reader implementation does not give us an easy/reliable way to do this.

**Comment by montrivo** [comment]
Let's say I want to define a set of attributes (for example: `srcdir`, `sqldir`, `javadir`,etc) that would be available in all my adoc files.
The problem lies in that documents resolve files relatively to themself whenever that are themself included in a master document (they don't resolve to the `base_dir` any more). This becomes an issue when the included file is not in the same folder as the main document as all inherited path attributes from the master document are not valid any more in the included file  (since they don't resolve to the same directory). And overriding them is not a solution as it will break  the master document attributes.

**Comment by mojavelinux** [comment]
This is just a general limitation of AsciiDoc right now. The one way around it is to create an include processor extension that takes information about the include stack from the reader and passes it down to document attributes. Until we do some rearchitecting, there's no other way I know to solve the issue.

There are numerous issues in the issue tracker about attribute values and includes that come from different folders. I believe the problem is well covered by those issues and we will take up the discussion there.
