### ISSUE TITLE
Escaping plus signs

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor#1864]
Consider this input:

```
Hello
=====
Sample Document
v1.0


Monospace +text+ content.

Monospace++in++aword.

Some programming language is called C++.

How about C++? Is fine.

As long as C++ does not occur twice in a line; C++.

Escaping approaches:

C\{++} and C\{++} 

C\++ and C\++ 

C\+\+ and C\+\+
```

Running `asciidoctor-pdf test.adoc` gives the following visual output on page 2:

![cplusplus](https://cloud.githubusercontent.com/assets/358358/18350388/ff460ee6-75d5-11e6-8ce3-e430dd77d597.png)

The [documentation](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#escaping-text) indicates that one of the last approaches should work. Hence the problem: I cannot see a way to have C++ twice on a line without creating monospace text.

**Comment by meisterluk** [comment]
I just recognized, that I was very close:

```
Hello
=====
Sample Document
v1.0


C\++ and C++ 
```

gives

![cplusplus](https://cloud.githubusercontent.com/assets/358358/18350538/aa94c1ca-75d6-11e6-94ca-3f373a6809a7.png)

So apparently the rule is "escape without brackets in the first instance". Can we make it more explicit in the documentation when to use `\{}` and when a backslash suffices?

**Comment by robertpanzer** [comment]
Hi Meister!

for the particular case of C++ you can use the predefined attribute `{cpp}`.
For other string containing pluses you can also go the route of defining your own attribute.
Please see https://github.com/asciidoctor/asciidoctor/issues/1208 for details.

Cheers
Robert

**Comment by meisterluk** [comment]
Oh thank you, issue #1208 covers this already. Sorry, for the noise.

**Comment by robertpanzer** [comment]
No problem, you're welcome. :-)

**Comment by sylvaticus** [comment]
Hello when I use `{cpp}` in ASciiDoc in Atom -> ASciiDoc preview is fine, but if I then right-click->export to PDF it is rendered still as `{cpp}` instead of `C++`

**Comment by mojavelinux** [comment]
Yes, that will work. Though it seems like the version of asciidoctor-pdf you are using is out of date. If you upgraded it, you'd find that the `{cpp}` replacement works out of the box.

**Comment by cirosantilli** [comment]
To summarize some things that seem to work for the non C++ case:

```
Notepadpass:[++] is *great*, I like Notepadpass:[++]

Notepad{blank}pass:[++] is *great*, I like Notepad{blank}pass:[++]

Notepad{plus}{plus} is *great*, I like Notepad{plus}{plus}
```

Also mentioned at: https://stackoverflow.com/questions/63917351/how-to-escape-double-plus-sign-in-asciidoctor-asciidoc
