### ISSUE TITLE
Previous include influences semantic interpretation in next include

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor#1869]
**Given:**

`test.adoc`
```
= Hello World

include::a.adoc[]
include::b.adoc[]
```

`a.adoc`
```
== First chapter

First text
```

`b.adoc`
```
== Second chapter

Second text
```

**Expected result:**
![expected](https://cloud.githubusercontent.com/assets/358358/18421288/095a54ec-7887-11e6-9547-a107880b0ce7.png)

**Actual result:**
![actual](https://cloud.githubusercontent.com/assets/358358/18421286/024e3132-7887-11e6-9312-2a6e29f1f36d.png)

**Workaround:**
A workaround seems to be adding "a paragraph of spaces before the title" in `b.adoc` (I'm not sure which whitespace combination works in all cases, but this one works here).

However, this workaround should not be necessary in first place. In general all semantic intermediate states should be flushed when the include has been finished processing.

(Wrongfully posted to asciidoctor-pdf as [issue 554](/asciidoctor/asciidoctor-pdf/issues/554) first)

**Comment by mojavelinux** [comment]
Actually, this is exactly as designed. The include directive is mean to read files and place them into the lines of source faithfully. If there are no spaces between the includes, then there should be no extra lines added. That's useful when adding lines to a source block, for instance. If you are including entire sections, then I always recommend using a blank line between the include directives.

Having said that, I have suggested the possibility of adding a hint to the include directive that the content should be kept at least a line apart. See #318.

**Comment by mojavelinux** [comment]
> A workaround seems to be adding "a paragraph of spaces before the title" in b.adoc (I'm not sure which whitespace combination works in all cases, but this one works here).

I strongly recommend against this approach. An unknowing author (or editor) could strip this line. The proper solution is to put blank lines between the include directives, where the intent is clear.

**Comment by mojavelinux** [comment]
```
= Hello World

include::a.adoc[]

include::b.adoc[]
```

**Comment by meisterluk** [comment]
I don't like that design, but backwards compatibility is more important here and the proper solution is reasonable. Thanks for pointing out my problem!

**Comment by meisterluk** [comment]
Just to point this out: This is so ridiculously difficult to maintain if the previous file ended with a labeled environment. I am not sure there is a bug or not. As far as I cannot dump the interpretation state of the parser, I cannot debug this. I just cannot get it running in many cases.

IMHO bad design choice. Or the lack of a final solution to issue #318.

**Comment by mojavelinux** [comment]
It's not a bad design choice. An include pulls in lines from another file. There is no expectations to add extra lines as those would be unwelcome in contexts where the included content is meant to be directly adjacent, such as inside a verbatim block. You may wish there to be a structural include that knows about the blocks around it and makes such decisions, but there isn't one. However, it is possible to create one using a custom block macro. It's also possible to use a custom include processor to add extra lines when including, if that's what you prefer.
