### ISSUE TITLE
Header height fails with 3 digit number

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor#1870]
```
meisterluk@linux ~ % cat test.adoc
Hello World
===========

Test
meisterluk@linux ~ % echo "header:\n  height: 99\n" > default-theme.yml
meisterluk@linux ~ % asciidoctor-pdf -a pdf-stylesdir=. test.adoc  # fine
meisterluk@linux ~ % echo "header:\n  height: 100\n" > default-theme.yml
meisterluk@linux ~ % asciidoctor-pdf -a pdf-stylesdir=. test.adoc  # fail
undefined method `-' for "100":String
Did you mean?  -@
  Use --trace for backtrace
1 meisterluk@linux ~ % asciidoctor-pdf --trace -a pdf-stylesdir=. test.adoc
/var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.12/lib/asciidoctor-pdf/converter.rb:1947:in `layout_running_content': undefined method `-' for "100":String (NoMethodError)
Did you mean?  -@
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.12/lib/asciidoctor-pdf/converter.rb:175:in `convert_document'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.12/lib/asciidoctor-pdf/converter.rb:96:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503:in `convert'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /var/lib/gems/2.3.0/gems/asciidoctor-1.5.4/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /var/lib/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.12/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:23:in `load'
	from /usr/local/bin/asciidoctor-pdf:23:in `<main>'
```

**Comment by meisterluk** [comment]
`trim_height.class == "String"`

**Comment by mojavelinux** [comment]
I'm pretty sure you should always specify units (like in CSS). Do you mean to specify 100pt?

(Keep in mind, the theme is not validated yet, so we're not yet into the discussion of applying validation to all the values. What we're shooting for right now is that the "happy path" works).

**Comment by mojavelinux** [comment]
Actually, something does seem off there. It's not getting converted correctly.

Only, this is the wrong repository. This should be part of asciidoctor-pdf.

**Comment by meisterluk** [comment]
> Only, this is the wrong repository. This should be part of asciidoctor-pdf.

Still not getting a hang of it 😬

**Comment by mojavelinux** [comment]
I see what's happening. We're escaping possible color values before parsing the YAML and 100 is a valid hex color value. As we parse, we have no way to distinguish between a color value and a 3-digit integer in the current implementation. We could, of course, coerce it to a float when reading it, but that's leaking into the client.

The short-term solution is to use a float value (e.g., 100.0) or add a unit (100pt). I can make this recommendation in the theming guide.

I want to emphasize that the theme parser is not very robust. It's getting the job done for what we need right now. It will eventually need to be redone using a formal grammar.

**Comment by mojavelinux** [comment]
> Still not getting a hang of it

You're doing just fine, I think ;)

**Comment by mojavelinux** [comment]
To summarize, numbers above two digits should either be written as a float (e.g., 100.0), a math expression (e.g, 1 * 100), or with a unit (e.g., 100pt). Otherwise, they get confused as color values.

**Comment by mojavelinux** [comment]
But, if we are sticking with the CSS theme, it's not that much of a stretch to enforce the use of units.

**Comment by mojavelinux** [comment]
If you reopen this in asciidoctor-pdf, I'll carry over my comments and we'll address it as a docs issue for now.

**Comment by meisterluk** [comment]
> If you reopen this in asciidoctor-pdf, I'll carry over my comments and we'll address it as a docs issue for now.

I guess now you are mixing up 😉 We are currently in asciidoctor and this issue is closed. The asciidoctor-pdf issue is still open. Nothing to reopen. What do you need me to do?

**Comment by mojavelinux** [comment]
Oh, I didn't realize you had already created it. I'll proceed then.
