### ISSUE TITLE
some non-alphanumeric characters in anchor ids can cause parsing problems for headers - doc oversight?

### ISSUE THREAD

**Issue by hossman** [asciidoctor/asciidoctor#1873]
In the processes of converting a lot of programatically generated HTML into asciidoctor files, I've got a lot of anchor definitions that contain non alphanumeric characters (examples: `(),^%&`) that are causing asciidoctor to not recognize my headers when converting the docs.  

For example:

```
[[CommonQueryParameters-Thefl(FieldList)Parameter]]
== The `fl` (Field List) Parameter

X X X X X X X X
```

...is causing the html5 backend to generate the following HTML...

```
<div class="paragraph">
<p>[[CommonQueryParameters-Thefl(FieldList)Parameter]]
== The <code>fl</code> (Field List) Parameter</p>
</div>
</div>
<div class="paragraph">
<p>X X X X X X X X</p>
</div>
```

...w/o any sort of warning/error being logged.

---

The documentation regarding the set of valid characters in anchor defintions is a bit vague, and in combination with the documentation on Custom (Section) ids, it seems like either this anchor is valid and there is a bug in asciidoctor's parsing, or the documentation is missleading and should be updated....

Section 19.2 of the user guide: [Auto-generated IDs](http://asciidoctor.org/docs/user-manual/#auto-generated-ids) says...

> Asciidoctor permits all valid UTF-8 characters in section ID ...

...immediately after that, section 19.3 (Custom IDs) says...

> You can also assign a custom ID and reference text label to a section (see Defining an Anchor). This can be useful when you define a cross reference pointing to the section.

If you then review Section 30.1: [Defining an Anchor](http://asciidoctor.org/docs/user-manual/#anchordef) there is is no details on any sort of restrictions about what characters are allowed in an anchor definition.  Leading to the conclusion that there are no restrictions. (Particularly since the reason you are reading about anchor definitions is to create a custom section ID, and acording to the doc that linked here section IDs can contain any UTF-8 characters)

Leaving the question: Documentation oversight, or code bug?

---

FWIW: the xref links that refer to these anchor IDs, generate the correct and expected HTML...

Example...

```
<<CommonQueryParameters-Thefl(FieldList)Parameter,fl>>
```

...becomes...

```
<p><a href="#CommonQueryParameters-Thefl(FieldList)Parameter">fl</a></p>
```

---

A few final notes:
- In the examples above I noted the HTML output created by the html5 backend because it's easy to review the final documents source/structure, but I should note the same problems also occur when using the pdf backend (which is my ultimate goal)
- I've been testing via asciidoctor-ant-1.5.3.jar since that's the latest version i can find on maven.org and ultimately i need to use asciidoctor-ant

**Comment by mojavelinux** [comment]
This point is now made in the AsciiDoc language documentation. See https://docs.asciidoctor.org/asciidoc/latest/attributes/id/#anchor

> The anchor is declared by enclosing a valid XML Name in double square brackets (e.g., `[[idname]]`)
