### ISSUE TITLE
:author: attribute should support rich text (such as a link)

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor#1879]
We can't name all the authors of our user guide, so we just put "The OptaPlanner Team" with a link to the team page. However that doesn't work:

```
 = OptaPlanner User guide
 :author: http://www.optaplanner/community/team.html[The OptaPlanner team]
```

It renders "http://www.optaplanner/community/team.html[The OptaPlanner team]" instead of "the OptaPlanner team" with a link, both in html and pdf.

**Comment by ge0ffrey** [comment]
I haven't tried it yet, but I presume other style controls, such as having superscript TM in your name (some artists have this) might be a problem too.

**Comment by mojavelinux** [comment]
To get markup in an attribute value, you have to surround the attribute with `pass:[]` and specify the substitutions you want to have performed.

```
:author: pass:m[http://www.optaplanner/community/team.html[The OptaPlanner team]]
```

In this case, however, it's probably better to write it as follows:

```
 = OptaPlanner User guide
OptaPlanner Team <http://www.optaplanner/community/team.html>
```

The URL for the author is available as the attribute name `email` (for legacy reasons).

**Comment by mojavelinux** [comment]
When you use the first solution, I noticed it does cause the `<meta>` element for author in the HTML head to get messed up.

**Comment by ge0ffrey** [comment]
Thanks Dan - sorry for creating an issue for something that should be a support question apparently.

**Comment by mojavelinux** [comment]
I'll also link the to relevant spot in the docs for anyone who finds this issue.

http://asciidoctor.org/docs/user-manual/#substitutions-in-an-attribute-entry

**Comment by ge0ffrey** [comment]
Note: this doesn't work:

     = OptaPlanner User Guide
     :author: The OptaPlanner Team <http://www.optaplanner.org/community/team.html>

Both in single HTML and PDF it renders as is. But without ":author:" it does work fine, which is a bit inconsistent.

**Comment by mojavelinux** [comment]
You're trying to use both the implicit and explicit syntax at the same time. That's not going to work. You either can use the implicit author line:

```
= OptaPlanner User Guide
The OptaPlanner_Team <http://www.optaplanner.org/community/team.html>
```

(The underscore is a grouping function and gets erased).

 or you have to define each attribute individually.

```
= OptaPlanner User Guide
:firstname: The
:lastname: OptaPlanner Team
:email: http://www.optaplanner.org/community/team.html
```

There are three fields for a name, firstname, middlename, and lastname. Here I'm just using firstname and lastname.

**Comment by mojavelinux** [comment]
> sorry for creating an issue for something that should be a support question apparently.

No need to apologize. This is just how I organize issues so I can keep track of them. If I determine a code change is needed, I graduate it from support.

**Comment by mojavelinux** [comment]
I'm going to close this issue and open a separate one to track this problem that I cited:

> When you use the first solution, I noticed it does cause the `<meta>` element for author in the HTML head to get messed up.

**Comment by mojavelinux** [comment]
See #2112.
