### ISSUE TITLE
GitHub ignores table column widths

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/asciidoctor#1880]
I hope this is the right place for this issue. It is my understanding that GitHub uses AsciiDoctor internally.

I have a table that starts like this:

`[cols="1h,2,6"]`

When I run asciidoctor locally, the resulting HTML correctly contains column width information:

```
<colgroup>
<col style="width: 11.1111%;">
<col style="width: 22.2222%;">
<col style="width: 66.6667%;">
</colgroup>
```

However, when GitHub renders the same table, it omits this information, so that the browser auto-sizes the columns. See this site: <https://github.com/DanielSWolf/rhubarb-lip-sync#mouth-shapes>

**Comment by mojavelinux** [comment]
I find this really annoying too. Unfortunately, it's GitHub's policy to strip away all attributes (with a few exceptions like src on img). I really would like to at least be able to set a table as 100% width. But until we can convince them to allow it, there's nothing we can do in Asciidoctor. I recommend e-mailing support or following one of the ongoing conversations about attributes in the [github/markup](https://github.com/github/markup) repo.

**Comment by DanielSWolf** [comment]
Thanks @mojavelinux, that makes sense. I contacted GitHub support and I'm closing this issue.
