### ISSUE TITLE
footer localization

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor#1882]
Is it possible to localize `last updated` stuff in a footer?

I can see there is #974, but it looks like it is more about what date should be inserted.

I am more interested in changing `Last updated` to another language and the date format to be compliant to that language too.

All other parts could be localized using attributes :caption-bla:.

I think there is a workaround to build your own footer, but that is not very convenient.

**Comment by mojavelinux** [comment]
Yes, it is possible to customize these labels. Please see the following file to find all the localized attributes that can be set (and examples of them translated in other languages).

https://github.com/asciidoctor/asciidoctor/blob/master/data/locale/attributes.adoc

**Comment by mojavelinux** [comment]
You can also find a complete list of all built-in attributes in the user manual.

http://asciidoctor.org/docs/user-manual/#builtin-attributes

**Comment by habamax** [comment]
Thx a lot, I have missed that somehow.

Looks like I was lurking not the full version of docs.

So date formatting is not supported, but would it be in a future?

**Comment by mojavelinux** [comment]
Perhaps. Though it's possible to get whatever format of the date you want by defining the date attributes (docdate and doctime) directly from the command line or API.

**Comment by habamax** [comment]
:docdate: attribute set inside document has no effect on Last update date.

On a command line I have tried:
    
     asciidoctor -a docdate="2010-01-01 20:00" index.adoc

Result

    Last updated 2010-01-01 20:00 13:02:21 Russia TZ 2 Standard Time 

Guess it is not enough, but

    asciidoctor -a docdate="2010-01-01" -a doctime="20:00" index.adoc

gives me what I want.

Now I have to find out how to provide that data to a command line from vim. But this is another story.

Thank you!

**Comment by habamax** [comment]
For those who curious about vim part:

    let &l:makeprg = "asciidoctor -a docdate=".strftime("%Y-%m-%d")." -a doctime=".strftime("%X")." ".shellescape(expand("%:p"))

**Comment by mojavelinux** [comment]
:+1: 

Thanks for the info. I'm going to add a mention how to make that customization in the user manual since it's not obvious. (For instance, it's necessary to set docdate and doctime individually rather than docdatetime).
