### ISSUE TITLE
[feature request] Link attributes should allow all valid <a> attributes

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor#1883]
The `a` tag in HTML5 [allows number of attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). For example, the `download` attribute is similarly useful as `target`.
I found that Asciidoctor 1.5.4 [only supports a few of them](http://asciidoctor.org/docs/user-manual/#summary-4).
This does not work:
```asciidoctor
link:file.vcf[vCard,window="_blank",download="true"]
```
My feature request is to support this.

**Comment by mojavelinux** [comment]
There's an open issue to support the download attribute. See #1781.

I'd prefer to handle these on a case-by-case basis since I don't want to bloat AsciiDoc with unnecessary attributes. We want attributes that make sense specifically for content and map those to HTML where they align. (In the end, may end up being all/most of them, but I prefer to discuss it).

**Comment by sanmai-NL** [comment]
Ah, I hadn't found that issue.

I agree with whitelisting the attributes, of course it's a slippery slope to allow all kinds of HTML specific constructs into Asciidoctor. On the other hand, the issue I'm facing is how to use Asciidoctor in static website generation context that does require me to have this level of control.

**Comment by mojavelinux** [comment]
> On the other hand, the issue I'm facing is how to use Asciidoctor in a static website generation context that does require me to have this level of control.

Remember, you can override the template that generates the links, and that template can refer to an open schema of attributes defined on the macro. In other words, you have the power to create the HTML anyway you want. What we're discussing here is just the default behavior.
