### ISSUE TITLE
Asciidoctor should issue a warning if there is a block but it's not a candidate for inline conversion

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#1890]
## Current state

``` javascript
var asciidoctor = require('asciidoctor.js')();
var processor = asciidoctor.Asciidoctor(true);

var content = "= This is a title!";
var options = {doctype: 'inline', attributes: ['showtitle']};
var html = processor.convert(content, options);
console.log(html); // returns Opal.nil
```

In the sample above, "This is a title!" is not a candidate for inline conversion and Asciidoctor returns "nil".
## Proposal

Asciidoctor should issue a warning message:

```
No candidate for inline conversion.
Inline document type should be used to convert a single paragraph. If you want to convert a complete document, use the default document type 'article' or simply remove 'doctype' from the options.
Read more about document types: http://asciidoctor.org/docs/user-manual/#document-types
```

I think this warning will help users to understand why the `convert` method returned `nil` (and outline the differences between each document type).

**Comment by mojavelinux** [comment]
This seems reasonable. I don't think we need quite so much information in the warning message...but I do like the idea.

**Comment by Mogztter** [comment]
@mojavelinux I think the following code should also issue a warning:

*sample.rb*
```ruby
require 'asciidoctor'

content = "= This is a title!"
html = Asciidoctor.convert content, doctype: :inline, attributes: { 'showtitle' => '' }
p html
```

```
ruby sample.rb
nil
```

Tested with Asciidoctor 1.5.6.1.

**Comment by mojavelinux** [comment]
Seems reasonable. I just changed the check to `block = blocks[0] || @header`.

Granted, there are still plenty of cases we don't look for. The idea is to guide the user of the API on the right track. This could certainly help.

**Comment by mojavelinux** [comment]
An interesting question is whether we should allow the use of the discrete heading in the inline mode. It has no children, so it fits the model. But I'm not sure if it's useful.

**Comment by Mogztter** [comment]
Hmmm... I never thought about this. Indeed `= This is a title!` could be converted in inline mode (or `== This is a section!`).

What about the `showtitle` attribute in this case ?

**Comment by mojavelinux** [comment]
showtitle definitely does not apply to the inline document.

To be honest, the inline document is really indent to convert a single phrase (i.e., sentence). Anything beyond that is really an abuse of the feature.

(I'm still thinking about discrete headings since they are by nature inline).
