### ISSUE TITLE
asciidoctor plugin 1.5.3 failed in ubuntu(NotImplementedError) fstat unimplemented unsupported or native support failed to load

### ISSUE THREAD

**Issue by saravankrish** [asciidoctor/asciidoctor#1892]
I am receiving below error when we generate pdf for hbase. 

> [INFO] --- asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) @ hbase ---
> asciidoctor: WARNING: conversion missing in backend pdf for pass
> Failed to parse formatted text: To supply filters to the Scanner object or configure the Scanner in any other way, you can create a text file and add your filter to the file. For example, to return only rows for which keys start with &lt;codeph&gt;u123&lt;/codeph&gt; and use a batch size of 100, the filter file would look like this: <pre> &lt;Scanner batch="100"&gt;   &lt;filter&gt;     {       "type": "PrefixFilter",       "value": "u123"     }   &lt;/filter&gt; &lt;/Scanner&gt; </pre> Pass the file to the <code>-d</code> argument of the <code>curl</code> request.
> Failed to parse formatted text: To supply filters to the Scanner object or configure the Scanner in any other way, you can create a text file and add your filter to the file. For example, to return only rows for which keys start with &lt;codeph&gt;u123&lt;/codeph&gt; and use a batch size of 100, the filter file would look like this: <pre> &lt;Scanner batch="100"&gt;   &lt;filter&gt;     {       "type": "PrefixFilter",       "value": "u123"     }   &lt;/filter&gt; &lt;/Scanner&gt; </pre> Pass the file to the <code>-d</code> argument of the <code>curl</code> request.
> asciidoctor: WARNING: image to embed not found or not readable: /home/jenkins/jenkins-slave/workspace/hbase_generate_website/hbase/src/main/asciidoc/images/sunset.jpg 
> Oct 10, 2016 2:56:06 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
> SEVERE: (NotImplementedError) fstat unimplemented unsupported or native support failed to load

You can look at the complete failure in the below link.
https://builds.apache.org/job/hbase_generate_website/372/

 This is the plugin version I am using.

```
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>${asciidoctor.plugin.version}</version>
    <inherited>false</inherited>
    <dependencies>
      <dependency>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctorj-pdf</artifactId>
        <version>1.5.0-alpha.11</version>
      </dependency>
    </dependencies>
```

Any help is appreciated.

**Comment by abelsromero** [comment]
Just looking around I found two similar issues. I saw in the log that the root failure seems to be caused by this:
```
SEVERE: (NotImplementedError) fstat unimplemented unsupported or native support failed to load
```
Not sure if it's the same thing, but found two possible solutions:

- https://github.com/asciidoctor/asciidoctorj/issues/402
- https://github.com/elastic/logstash/issues/2962  

The first case may be a possible solution. If not maybe switching to a more updated version of JRuby may help. But I am really just guessing.
You can change the jRuby version in the plugin like in this example https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-example/pom.xml#L33-L37

**Comment by mouseratti** [comment]
```
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
-                <version>1.5.2</version>
+                <version>1.5.3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj</artifactId>
                        <version>1.5.4</version>
                    </dependency>
```
An update from 1.5.2 to 1.5.3 fixed this problem in my project

**Comment by rgarrigue** [comment]
Hello

I had the same error messagefor a different reason : running jenkins' official docker, I was missing a library. Here's my solution, for other people coming around

```
FROM jenkins/jenkins:lts
USER root 
RUN apt-get update \
    && apt-get install -y libc6-dev 
USER jenkins
WORKDIR /var/jenkins_home
```

I opened an issue for a fix on jenkins' upstream, : https://github.com/jenkinsci/docker/issues/603

Best regards,

**Comment by mojavelinux** [comment]
If this continues to be a problem, please file an issue in https://github.com/asciidoctor/asciidoctor-maven-plugin.

**Comment by polaroidkidd** [comment]
> 
> 
> Hello
> 
> I had the same error messagefor a different reason : running jenkins' official docker, I was missing a library. Here's my solution, for other people coming around
> 
> ```
> FROM jenkins/jenkins:lts
> USER root 
> RUN apt-get update \
>     && apt-get install -y libc6-dev 
> USER jenkins
> WORKDIR /var/jenkins_home
> ```
> 
> I opened an issue for a fix on jenkins' upstream, : [jenkinsci/docker#603](https://github.com/jenkinsci/docker/issues/603)
> 
> Best regards,

For WSL2 users (on ubuntu), installing `libc6-dev` also fixes this issue.
