### ISSUE TITLE
Image callout icons disappear for long callouts [html5]

### ISSUE THREAD

**Issue by cristoper** [asciidoctor/asciidoctor#1895]
When the `icons` attribute is set to "image" with the html5 backend, then the callout icons in callout table shrink and then disappear as any of the callout text wraps to more than one line.

For example, this asciidoc file:

``` [source,python]
----
def normalize_tokenize(text):
    norm = text.lower() #<1>
    norm = re.sub(r'(?u)[^\w\s]', '', norm) #<2>
    return tokens
----
<1> First we coerce the entire string to lower case using the `lower()` method of Python's standard https://docs.python.org/3/library/stdtypes.html#str[string] type.

<2> This https://docs.python.org/3/library/re.html[regular expression] matches everything that is not a word (`\w`) or whitespace (`\s`) and replaces it with the empty string. The `(?u)` flag at the start enables Unicode matching (this is only needed in Python 2; Python 3 matches Unicode by default).
```

Looks like this when rendered (Chromium version 48.0.2564.82 on Linux):

![bug](https://cloud.githubusercontent.com/assets/331548/19545852/0ed5e1ec-9647-11e6-867f-c247e86e92a8.png)

I think the fix is to set the 'max-width' CSS property of icon img's to 'none' as is done for admonitionblock icons. Following the example of admonitionblock, the patch in the subsequent pull request adds an 'icon' class to the <td> element containing the callout icon and a corresponding line in the default stylesheet.

With that fix, the above snippet renders as expected:

![expected](https://cloud.githubusercontent.com/assets/331548/19545867/3fcdde58-9647-11e6-8077-fa8af4b8f338.png)

**Comment by mojavelinux** [comment]
Let me know if the fix works for you.

**Comment by cristoper** [comment]
Yep, your CSS change in aa3e33e fixes it for me. Thanks!

**Comment by mojavelinux** [comment]
Great! Thanks for testing!
