### ISSUE TITLE
File objects created by ::File.new must be closed explicitly

### ISSUE THREAD

**Issue by nerk** [asciidoctor/asciidoctor#1897]
`convert_file`, `load_file`  methods invoke `::File.new` which creates open file objects that are never closed. 

`::File.new` is also used in 

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/cli/invoker.rb

See https://github.com/asciidoctor/asciidoctorj/issues/524

**Comment by mojavelinux** [comment]
I'm wondering whether we should close a file if passed to the `convert` or `load` methods, or whether we should only close a file that we ourselves opened. wdyt?

**Comment by nerk** [comment]
I think we should only close things we opened ourselves. If we pass an already opened file object to a method, we should have to close it explicitly. If we pass ::File.new and this represents an opened file, we'd have to close it explicitly after the method returns. Different story if we just pass a filename, of course. (I don't know any Ruby...)

**Comment by mojavelinux** [comment]
Thanks for clarifying the requirements. That's exactly the feedback I was looking for and it sounds reasonable.

> (I don't know any Ruby...)

You don't need to. This is software design. Language agnostic ;)
