### ISSUE TITLE
avoid inline javascript when using :source-highlighter: highlightjs

### ISSUE THREAD

**Issue by ulrichwinter** [asciidoctor/asciidoctor#1900]
If highlightjs is used, the generated html markup contains the following script tag:
`<script>hljs.initHighlighting()</script>
`
Problem:
This leads to errors and prevents the actual highlighting, if the content security policy of the site forbids inline scripts.

Suggested solution:
The generated markup should include an external script which does the actual initialization call of the highlighter.
This might be the default or be configurable as an option.

**Comment by mojavelinux** [comment]
My first reaction is that preventing inline scripts would pretty much break the web. It seems like a pretty insane policy to me.

It would be convenient if highlight.js had an automatic loading mode based on the value of a query string parameter or something. That way, we could just include the script and it would automatically initialize. Perhaps you can suggest that upstream. Since we rely on the script from a CDN, there's no way for us to provide a loading script otherwise (since we don't use local files).

**Comment by mojavelinux** [comment]
I simply don't agree with this request. Nevertheless, the syntax highlighter is now pluggable. Therefore, you are free to substitute a different implementation of the highlight.js integration that loads the script in a different way.

```rb
require 'asciidoctor'

class MyHighlightJsAdapter < (Asciidoctor::SyntaxHighlighter.for 'highlight.js')
  def docinfo location, doc, opts
    puts 'load highlight.js as you wish'
  end
end

Asciidoctor.convert_file 'document.adoc', safe: :safe,
    syntax_highlighters: { 'highlight.js' => MyHighlightJsAdapter }
```

**Comment by m-van-tilburg** [comment]
> My first reaction is that preventing inline scripts would pretty much break the web. It seems like a pretty insane policy to me.

Using a Content Security Policy that prevents inline scripts (and/or styles) would indeed break a lot of web pages on the web, in some environments this is required however. For an application I am working on we must adhere to the [OWASP guidelines](https://owasp.org/). This can be a tremendous amount of work, but results in an application that is not easily hacked. Thus far for AsciiDoctor, we could get away with not writing custom code. We put all fonts/css/js in a local folder and this works great, except for the inline script for highlightjs

**Comment by mojavelinux** [comment]
@m-van-tilburg Have you tried the adapter? You could also just use a different syntax highlighting library that doesn't rely on JavaScript like Rouge (which is supported out of the box).

**Comment by m-van-tilburg** [comment]
@mojavelinux Tried using Rouge but [asciidoctor-maven-plugin](https://asciidoctor.org/docs/asciidoctor-maven-plugin/) does not seem to support it. For Coderay we did not find an official way to customize the stylesheet, although it copies {{coderay-asciidoctor.css}} to the output directory which we could override manually. Maybe we have to figure out how to load a custom MyHighlightJsAdapter, hopefully written in Java like the rest of our code

**Comment by mojavelinux** [comment]
> Edit: found a way around it by using asciidoctorj 2.0.0 (which includes Rouge) with asciidoctor-maven-plugin 2.0.0-RC.1

:+1:
