### ISSUE TITLE
Add support for tel tag

### ISSUE THREAD

**Issue by jwillemsen** [asciidoctor/asciidoctor#1902]
In html we have the ability to explicitly add a href for a telephone like below. Would be useful is within adoc we could trigger this generation using "tel:1-847-555-5555"

`<a href="tel:1-847-555-5555">1-847-555-5555</a>`

See more at http://stackoverflow.com/questions/17219688/href-tel-and-mobile-numbers

**Comment by mojavelinux** [comment]
This is the perfect case for an extension. I added one to the extensions lab. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/tel-inline-macro.rb

**Comment by jwillemsen** [comment]
Works perfect, thanks for adding the extension to the lab!

**Comment by mojavelinux** [comment]
:+1:
