### ISSUE TITLE
Use a specific (or multiple) vocabluary (markup) for class attributes in html conversion

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1908]
At the moment the elements in the html ouptut use seems-to-be-arbitrary vocabulary in the class attribute. So while `class="sect1"` maps with Docbook `sect1` element, but `class="sidebarblock"` does not map to anything. If there would be compatible vocabulary (borrowed from DocBook, JATS, ...) then it becomes much easier to convert everything from the html ouput on fly.  

So for example, if there would be a `vocab:jats` and/or `vocab-conversion-table:sometable.yaml` attribute then asciidoctor translates paragraphs to `<div class="p">` or even `<div class="paragraph v-jats-p v-docbook-simpara ...">` if multiple vocabularies are required.  This suggestion is only for the internal components of asciidoc and authors might need to add extra roles (for elements attributes) or comply with some component model if their target format requires.

These compatible vocabularies make the html output suitable for on fly conversion to other formats using jquery like conversions. 

Styling through css can be format sensitive also.

**Comment by mojavelinux** [comment]
This is something that's going to be done in the new (semantic) HTML converter. See https://github.com/asciidoctor/asciidoctor/projects/1?query=is%3Aopen+sort%3Aupdated-desc. There's no way we can change this now in the existing HTML converter without breaking the publishing process of everyone who uses Asciidoctor today.
