### ISSUE TITLE
Automatically add bibliography style to list in bibliography section

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1924]
If the section marked with the bibliography role has exactly one child, and that child is an unordered list, automatically add the bibliography style to that block.

Example:

```
[bibliography]
== Bibliography

- [[[taoup]]] Eric Steven Raymond.
  _The Art of Unix Programming_. Addison-Wesley.
  ISBN 0-13-142901-9.
- [[[walsh-muellner]]] Norman Walsh & Leonard Muellner.
  _DocBook - The Definitive Guide_. O'Reilly & Associates. 1999.
  ISBN 1-56592-580-7.
```

We may want to consider other scenarios as well, but this one is the most typical.

**Comment by mojavelinux** [comment]
I decided it makes sense to add the bibliography style to the first unordered list that's a direct child of the section.

**Comment by cristian-5** [comment]
We should have a selector in the `theme.yml` that allows us to change the appearance of the list:

``` yml
bibliography:
  item-spacing: 6
  font-color: #000000
  style: circle
  link-color: #FF0000
```

Note the `style` property allowing us to chose from different list styles, with the addition of `none` to hide the bullet point.
Also note the `link-color` that only applies to external links in the bibliography.

**Comment by mojavelinux** [comment]
Your comment is not relevant for this repository. You are talking about Asciidoctor PDF theme settings. This repository hosts Asciidoctor core, which parses AsciiDoc and provides built-in converters, which does not include PDF.

**Comment by cristian-5** [comment]
oops
