### ISSUE TITLE
Allow third argument of attr/attr? to be name of document attribute

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1934]
The third argument to the attr and attr? methods controls whether the attribute can inherit from the document scope. However, it's not always desirable to share the same attribute name between the node and the document. Thus, as an alternate to a boolean value of true, allow the name of the attribute on the document to be specified as the third argument.

For example:

```ruby
image_format = node.attr 'format', nil, 'image-format'
```

This method call would look for the format attribute on the node, but the image-format attribute on the document (if the format attribute is not present on the node).

**Comment by mojavelinux** [comment]
I've given this a lot of thought and I think it would be better to make this the fourth argument. For one, it won't confuse the AsciidoctorJ API (which already defines the third argument as a boolean). But also, it will make it easier to switch the default value of inherit to false. Plus, it reads a bit nicer.

```rb
image_format = node.attr 'format', nil, true, 'image-format'
```

**Comment by mojavelinux** [comment]
@Mogztter recommended that we reuse the third argument. Since I was on the fence, I'm inclined to lean that way.

```rb
image_format = node.attr 'format', nil, 'image-format'
```

**Comment by Mogztter** [comment]
It would be neat to be able to use named arguments (so we could skip the second argument) but as far as I understand in Ruby you can't use both positional and named arguments because you need to define arguments as "keyword arguments" but then you can't use positional arguments anymore right ?

**Comment by mojavelinux** [comment]
It is possible to use both (as we do in the TemplateConverter). But keyword arguments aren't yet fully optimized and this is an extremely hot method. So I'd prefer to avoid it right now.
