### ISSUE TITLE
Feature request: :front|back-cover-image: for docbook

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor#1939]
This is a follow-up of:  https://github.com/asciidoctor/asciidoctor-fopub/issues/69

First `<cover>` corresponds to `:front-cover-image:`.
I am not sure what the second  `<cover>` refers to. Is it the page that follows the first `<cover>`page or is it the very last page in the document?

```xml
<book xmlns='http://docbook.org/ns/docbook'>
<info>
  <title>DocBook</title>
  <subtitle>The Definitive Guide</subtitle>
  <!-- THIS IS FRONT COVER -->
  <cover>
    <mediaobject>
      <imageobject>
	<imagedata fileref="graphics/duck-cover.png">
	</imagedata>
      </imageobject>
    </mediaobject>
  </cover>
  <!-- THIS IS BACK COVER -->
  <cover>
    <mediaobject>
      <imageobject>
	<imagedata fileref="graphics/duck-backcover.png"/>
      </imageobject>
    </mediaobject>
  </cover>
</info>

<preface>
<title>Preface</title>

<para>DocBook provides a system …</para>
</preface>

<!-- … -->

</book>
```

### TODO

* Make `asciidoctor` translate  `:front-cover-image:` to `<cover>` when `-b docbook`

**Comment by mojavelinux** [comment]
According to the [DocBook reference](http://tdg.docbook.org/tdg/5.0/cover.html),

> DocBook does not attempt to define semantics for their order or relationship to one another.

It's also important to know that the the DocBook XSL stylesheets currently do not provide direct support for covers (only front title pages). Starting with version 1.73 of the stylesheets, the book template includes empty placeholder templates.

SageHill [summarizes](http://www.sagehill.net/docbookxsl/TitlePagePrint.html#BookCovers) the situation succinctly:

> Starting with DocBook 5.0, the cover element was added to DocBook as part of the collection of metadata in the info element. The cover element is simply a container of information that can be presented on a cover. By default, the cover element is not processed, so you can add whatever information you need and create custom templates to format it.
