### ISSUE TITLE
:doctype: book issue

### ISSUE THREAD

**Issue by pinggit** [asciidoctor/asciidoctor#1940]
I'm surprised that below code does not work as what I expected:

'''
= python tips
:doctype: book
//this line is to generate a "side panel"
:toc: left
:toclevels: 3
:toc-title: Table of Content
:iconsdir:
:icons: font
:source-highlighter: prettify
//:prettify-theme:

== data structure

a

=== numbers

a

= pyez

a

== XML and xpath

a
'''

it generate this:
![image](https://cloud.githubusercontent.com/assets/2038044/20459576/fa957e16-ae94-11e6-98fa-9777ec5bd12f.png)

so why the chapter "pyez" (level 0) is in same level as of "data structure" (level 1)?
I think previously it worked , or maybe my code is wrong?

**Comment by pinggit** [comment]
any help?

**Comment by PauloFrancaLacerda** [comment]
It's "level 0".
See:
http://asciidoctor.org/docs/user-manual/#sections

**Comment by PauloFrancaLacerda** [comment]
What output did you expect?

**Comment by pinggit** [comment]
I'm expecting an TOC structure like this:
```
python tips(0)
   data structure(1)
         numbers(2)
pyez(0)
   XML and xpath(1)
```

not this (current result):
```
data structure(1)
   numbers(2)
pyez(0)
   XML and xpath(1)
```

but...I figured it out...
I'm not sure if it is a bug or design.

to achieve what I wanted, I have to write it like this:
```
= python tips
:doctype: book
//this line is to generate a "side panel"
:toc: left
:toclevels: 3
:toc-title: Table of Content
:iconsdir:
:icons: font
:source-highlighter: prettify
//:prettify-theme:

= python (<----------add this line here)

== data structure

a

=== numbers

a

= pyez

a

== XML and xpath

a

```

I thought the very first line can be used as the level 0 title...guess I didn't get it.

**Comment by mojavelinux** [comment]
The requirement you are describing is exactly how AsciiDoc works. The table of contents does not include the document title. If you want that, you can use a custom converter template for the outline node.
