### ISSUE TITLE
'Figure' numbers of block images in tables do not increase (html output)

### ISSUE THREAD

**Issue by EikeRethmeier** [asciidoctor/asciidoctor#1942]
The numbers of the generated "Figure" description inside tables will not increase if you are generating .html output (tested Chrome plugin and the standard ruby stuff).
Example:

```
== Table stuff

And now some errors with the generated numbers of the Figures. I only use "image::" here and %20 for masking the spaces:

.Outside the table
image::thank%20you.jpg[]

[cols="2*a"]
|====
|
.Inside the table
image::thank%20you.jpg[]

|
.Also inside, same number!
image::cp3.png[]
|====


Next table:

[cols="2*a"]
|====
|
.Inside the table
image::thank%20you.jpg[]

|
.Also inside, same number!
image::cp3.png[]
|====

.Outside again
image::thank%20you.jpg[]

.and again
image::thank%20you.jpg[]
```

**Comment by robertpanzer** [comment]
As a wild guessing side note I guess you are using Asciidoctor(J) 1.5.4, right?

**Comment by mojavelinux** [comment]
I can confirm this is a bug. The reference to the counter is not being
maintained properly.

**Comment by mojavelinux** [comment]
I implemented this for now by enhancing the `counter` method to delegate to the parent document if the parent document is present.

**Comment by mojavelinux** [comment]
Note that AsciiDoc Python suffers from this same issue, so solution will cause the behavior of Asciidoctor to diverge.
