### ISSUE TITLE
Permit spaces in the filename (target) of a block image

### ISSUE THREAD

**Issue by EikeRethmeier** [asciidoctor/asciidoctor#1943]
Inline images like this

> image:thank you.jpg[]

can handle spaces inside file names. But block images can not, you have to mask them. This means

> image::thank you.jpg[]

will not work and you have to mask them with {sp} or %20 like

> image::thank{sp}you.jpg[]
> image::thank%20you.jpg[]

You can not alway avoid spaces in names, so it would be good to enhance block images to allow spaces.

**Comment by mojavelinux** [comment]
This will also apply to audio and video macros since they share the same matcher.

We should also consider allowing spaces in generic block macros.

Let's just allow the target to be anything up to the first `[`. In other words, a left square bracket will not be allowed in the target. If we need to take it further, we'll cross that bridge later.

**Comment by mojavelinux** [comment]
I'm not going to address generic block macros at this time.

Do you think we should automatically encode spaces in the image URI as %20? (I tested the DocBook converter and it seems to be able to handle URI encoded paths).

**Comment by mojavelinux** [comment]
@EikeRethmeier Do you agree we should automatically URL encode spaces (replace with %20) in web paths that are emitted by the converter? This includes images, videos, audio, stylesheets, etc.

**Comment by mojavelinux** [comment]
Encoding the spaces seems like the right thing to do. It ensures that the output document validates properly. I moved the encoding to web_path, so it will also handle spaces in URLs when we read from remote files. (Note that I'm not handling any other characters, but for now I think this is sufficient).

**Comment by EikeRethmeier** [comment]
I have only basic knowledge of the converter(s), but it seems to be the right choice.

**Comment by mojavelinux** [comment]
:+1:
