### ISSUE TITLE
Gradle plugin and the official Gradle plugin site

### ISSUE THREAD

**Issue by mputters** [asciidoctor/asciidoctor#1946]
Hello,

Would it be possible to add the Gradle plugin to the official Gradle plugin site at https://plugins.gradle.org?
This would allow replacing this:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
    }
}

apply plugin: 'org.asciidoctor.convert'
```

With this:
```
plugins {
    id: 'org.asciidoctor.convert' version '1.5.3'
}
```

Thanks

**Comment by abelsromero** [comment]
I recall it is already. Also, I am not sure if the configuration uses 'map' notation.
Shouldn't it be
```
plugins {
    id 'org.asciidoctor.convert' version '1.5.3'
}
```

**Comment by mojavelinux** [comment]
Indeed, the plugin is published to the plugin portal. See

https://plugins.gradle.org/plugin/org.asciidoctor.convert

Please direct future questions about the Gradle plugin to https://github.com/asciidoctor/asciidoctor-gradle-plugin.
