### ISSUE TITLE
Consider alternative block quote forms

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#196]
The choice of underscores for the boundaries of the quote block have always seemed awkward to me. I'd like to explore some more intuitive alternatives.

Here's an example of a quote block as it stands right now in AsciiDoc:

```
[quote, Red, The Shawshank Redemption]
____
Andy Dufresne...who crawled through a river of shit and came out clean on
the other side.
____
```

For a basic quote w/ three parts (text, attribution and source), we could consider supporting the abbreviated form most likely found in an e-mail:

```
"Andy Dufresne...who crawled through a river of shit and came out clean on
the other side."
-- Red, The Shawshank Redemption
```

We could also emulate Markdown block quotes.

```
> Andy Dufresne...who crawled through a river of shit and came out clean
> on the other side.
> -- Red, The Shawshank Redemption
```

**Comment by john-cj** [comment]
> The choice of underscores for the boundaries of the quote block have always seemed awkward to me. I'd like to explore some more intuitive alternatives.

I would suggest to consider tilde as a possible replacement of underscores.

```
[quote, author, source]
~~~~
quote
~~~~
```

It looks neatly and similar to a physically cutted and pasted piece of paper. Sometimes it is used in books:

![sprav](https://user-images.githubusercontent.com/18004961/71545254-2cb54100-299a-11ea-9b38-7550dbc2f2bc.png)

**Comment by mojavelinux** [comment]
The tilde is being reserved for the congruent form of the open block. See #1121. There is no need to change the delimiter for the quote block. And even if we did decide it was necessary, it would have to be run through the AsciiDoc spec, so we're deferring discussions that pertain to the syntax until that is underway.

I would prefer if you didn't comment on old issues (esp one that is > 5 years old) with an attempt to take them in new direction. It's not the right forum for discussion and muddles the conclusion of the issue.
