### ISSUE TITLE
Add multi-lingual aliases for each built-in attribute

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1964]
Add language-based aliases for all built-in attributes. For example, if `:lang: "fa"` then one instead of writing:
```
:author: XXXX
```
Would be able to write
```
:نویسنده: XXXXX
```
This makes more sense to write all those attributes only in one language and the document is more readable.

Please note that the same rule can be applied for internal styles and macros such as `[bibliography]` or `image:[]` ...

**Comment by mojavelinux** [comment]
I don't agree this is the right direction to go. This would like having the ability to translate the "class" keyword when writing Java. You are free to use the native language for custom attributes, but built-in attributes use ASCII characters and are English like. This would also have a significant impact on the speed of the processor since it would have to do a double lookup every time it resolves an attribute.

**Comment by shahryareiv** [comment]
@mojavelinux 
Then that would be a big barrier for internationalization of Asciidoc/tor. Imagine that Asciidoc/tor was developed in Japan, and an ordinary person who wants to use Asciidoc needs to learn some Japanese and tolerate the odd feeling of reading English text through some Japanese keywords.

I consider Asdciidoc as a protocol for human readable unformated texts that can embed more semantic meta-information in a text, beyond punctuations. Asciidoc, like other lightweight markups, rely heavily on symbols rather than words to embed that information but it needs sometimes to recruit words anyway. Words as not language-neutral like symbols but they can have equivalents in different  languages.

Actually, at the moment I am using limited Persian keywords/attributes/roles in my Persian Asciidoc documents. I use RegEx to do a preprocessing for finding and translating those keywords back into original ones. I guess an AST extension should work better. I also guess any person who wants to use Asciidoc seriously in Persian needs to do something similar.

The point is that even if an AST extension is enough, still it can end up to different versions of Asciidoc in other languages, making it less communicable and readable. An initiative from the core Asciidoctor development team might keep thing unified. 

Also, please not that we have the same issue in Latex. There translation of major macros exist in different languages. I do not know about other languages but for Persian each language-support package have introduced different wordings for the same macro.

**Comment by elextr** [comment]
Agree with @mojavelinux that its rare for computer languages to allow keywords to be changed.  

On the other hand attributes are like variables, and by default each name denotes a _separate_ entity.  But some programming languages do allow aliases for variables and some other named entities.

A syntax would need to be defined for aliases, eg
```
:new_name:= existing_name
```
and then either name would access the same underlying value.

Of course somebody needs to contribute the code.

__BUT__ adding more attributes adds overhead to every attribute lookup, so they should not be a default part of the core. 

Instead language communities should be encouraged to maintain (perhaps in a wiki?) an include file that defines the aliases for their language, so their documents only need to include the language(s) they have used. (parenthetical note, and language communities can then bicker amongst themselves what the translation of `chapter-refsig` or `asset-uri-scheme` is in linear b :)

**Comment by mojavelinux** [comment]
For me, built-in attributes are keywords. And like keywords in programming languages, they are fixed. This has not proven to be a barrier for programming, so I don't see why it would be a barrier for writing either.

**Comment by mojavelinux** [comment]
I want to clarify that I fully support translated custom roles, IDs, and attributes. For your own text, you should be able to type whatever you want. But the built-in keywords are universal. They shouldn't even be really viewed as words, but rather special symbols that activate behavior (much like 4 equal signs).

**Comment by mojavelinux** [comment]
Related to #1600 and #1977. As I've stated here and elsewhere, we're not going to change AsciiDoc in this way.
