### ISSUE TITLE
path_resolver.system_path doesn't work for one argument

### ISSUE THREAD

**Issue by atbest** [asciidoctor/asciidoctor#1965]
In the samples, it's shown that one can pass a single argument to system_path and get the full path as follows:
```
#     resolver.system_path('images')
#     => '/path/to/docs/images'
 ```
But when you run the following test code, you will get `` `system_path': wrong number of arguments (given 1, expected 2..4) (ArgumentError)`` .
```ruby
require 'asciidoctor/path_resolver'
require 'asciidoctor'

resolver = Asciidoctor::PathResolver.new
puts resolver.system_path 'images'
```
To solve this problem, it's necessary to change line 313 in path_resolver.rb from 
```ruby
  def system_path target, start, jail = nil, opts = {}
```
to
```ruby
  def system_path target, start = nil, jail = nil, opts = {}
```

**Comment by mojavelinux** [comment]
I agree. I can't recall why I didn't make that parameter optional, especially since nil and empty string are acceptable values.

Here's the relevant test case:

https://github.com/asciidoctor/asciidoctor/blob/master/test/paths_test.rb#L190-L194
