### ISSUE TITLE
Add possibility of "invisible" attribute for block/inline objects

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1970]
If  blocks or inlines can be specified as "invisible" then extensions can process their content for another purpose. One example can be defining `role=slide` alongside `invisible` where later a `slider::[#id1,#id2, ...]` can be called for a slider. Here it is desired for the slides not to be shown (but exist) independently.

**Comment by mojavelinux** [comment]
It's already possible to have invisible blocks. One way is to make a comment block (or paragraph).

```
[comment]
--
This block gets ignored.
--
```

If you just want to hide the block in the output document, add the `hide` role:

```
[.hide]
--
This block is hidden.
--
```

If you want to do your own processing, just make a custom block and register an extension to process it.

```
[custom]
--
This block is handled by an extension.
--
```

To be handled by:

```rb
Asciidoctor::Extensions.register do
  block :custom do
    bind_to :open
    process do |parent, reader, attrs|
      # return a block built from reader.readlines    
    end
  end
end
```

Is there something else you had in mind?
