### ISSUE TITLE
non-compliance with asciidoc for `_`

### ISSUE THREAD

**Issue by c-cube** [asciidoctor/asciidoctor#1973]
Text within `` ` `` backticks is kept as is with the python asciidoc, but not by asciidoctor on github.
For instance, `` `_` `` in a .adoc
will render as `_` with asciidoc, but as an empty `` `` in asciidoctor, which is annoying when I write a document about a language in which `_` are important.

**Comment by DavidGamba** [comment]
You probably want to use `` `+_+` ``. The syntax was introduced in 1.5: http://asciidoctor.org/news/2014/08/12/asciidoctor-1-5-0-released/#spotlight-syntax

This page doesn't seem to cover all of that in that much detail:
http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/

**Comment by mojavelinux** [comment]
The 1.5.0 release post is a good start, but the page you should be looking at is http://asciidoctor.org/docs/migration/. As the page states, we decided to rework some of the syntax to make it more consistent. Backticks no longer escape text, the only perform monospace formatting. The most elegant way to get the old behavior is as David suggested. You can also enable compatibility mode using an attribute if you don't want to modernize. The migration page suggests a few other approaches.

**Comment by c-cube** [comment]
I ended up using `+++foo+++`, losing the mono font, but it works on both asciidoc and github's asciidoctor (on which I cannot set compatibiity mode).

**Comment by mojavelinux** [comment]
>  github's asciidoctor (on which I cannot set compatibiity mode).

That is not true. You can set the compatibility mode from the header:

```
= Document Title
:compat-mode:
```

> it works on both asciidoc 

Are you using AsciiDoc Python? If so, then yes, you would need to set the compat-mode for portability. But I have to ask why you are not using Asciidoctor.

**Comment by c-cube** [comment]
Ah, good to know indeed. I'm using the python version out of habit, but it's dead, isn't it? You're right, I should move to asciidoctor anyway. Thanks!

**Comment by mojavelinux** [comment]
AsciiDoc Python is in maintenance mode. Asciidoctor is now the official AsciiDoc language implementation (as it is used on all major services). We've assumed ownership to drive the language forward each and every day.
