### ISSUE TITLE
No alternatives to low contrast captchas on email registration form

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor#1975]
The captchas used on the registration page for the email list are extremely low contrast - the background and foreground are basically indistinguishable. However, there is no alternative option. Even captchas with high contrast between the foreground and background  (i.e. that are much easier to read) typically offer either an audio alternative or another way to bypass the captcha for folks who have difficulty parsing the default option.

**Comment by Mogztter** [comment]
Hello @janicecmt, are you talking about the registration form on the forum http://discuss.asciidoctor.org/template/NamlServlet.jtp?macro=start_registration_page ?

If this is the case, could you please close this issue and open a new one here https://github.com/asciidoctor/asciidoctor.org/issues ?

Thanks,
Guillaume

**Comment by janicecmt** [comment]
Done. I assume that project is for anything related to the website. Are there other projects/splits I should know about as a newbie?

**Comment by janicecmt** [comment]
Opened https://github.com/asciidoctor/asciidoctor.org/issues/641 Instead

**Comment by Mogztter** [comment]
> Done. I assume that project is for anything related to the website.

Exactly

> Are there other projects/splits I should know about as a newbie?

This repository is for anything related to the Asciidoctor (core) written in Ruby and published as RubyGem (ie. the processor and to some extent the syntax).
The Asciidoctor organization is composed of plugins (Atom, Intellij...), extensions (Chrome, Firefox...), implementations (Java, JavaScript), converters (PDF, Reveal.js...) ... and each has it own repository.
You can find them here: https://github.com/asciidoctor

> Opened asciidoctor/asciidoctor.org#641 Instead

Cool, thanks 👍
