### ISSUE TITLE
For future RTL/i18n support: consider language specific delimiters (such as ، for ,)

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1976]
In Persian (Farsi), Arabic, and Urdo comma is represented by `،` instead of `,`  . This is  to make sure comma is not confused with `و` (which means "and"), specially in hand writing. It might be a good idea to add support this delimiter to asciidoc (eg. for block attributes). Another example is using «» quoting instead of "". Note that still the original `,` and `"` can be found in standard keyboards and it is only a matter of consistency and avoiding unnecessary switches from RTL to LTR.

An extended idea might be that other similar situations for all other languages to be gathered and get supported.

**Comment by mojavelinux** [comment]
We are not going to change the delimiters used in AsciiDoc. The concept of AsciiDoc is that all markup is done using ASCII characters (whereas the content can use any characters that are valid Unicode). That's what AsciiDoc has always been and always will be. If you want to make a different language that does things differently, you are welcome to do so.
