### ISSUE TITLE
Add dictionary support for internationalization of keywords and standard attributes

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1977]
In connection with  https://github.com/asciidoctor/asciidoctor/issues/1600 and https://github.com/asciidoctor/asciidoctor/issues/1964, one option might be to add support a dictionary mechanism for keywords and standard attributes in asciidoc, so the input asciidoc is being processed based on a default or specified dictionary.

as the first contribution I created an English-Persian dictionary with some initial entries here: https://github.com/shahryareiv/persian_kewords/blob/master/asciidoc.json

**Comment by mojavelinux** [comment]
No mainstream language (at least that I know of) lets you rewrite/remap keywords (think about Java and JavaScript, for example). The keywords and built-in attribute name are a core part of the language and changing them would be to make something that isn't AsciiDoc. We're not going to do that.
