### ISSUE TITLE
Line numbering on a source block should be enabled via an option

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1981]
Since line numbering is a switch, to be consistent with the AsciiDoc syntax, it should be enabled via an option (`linenums`) instead of a positional attribute. We can continue to support the positional attribute for backwards compatibility, but the docs should be updated to use the option.

```
[source%linenums,java]
----
public @WebServlet("/ping") class PingServlet extends HttpServlet {
    @Override protected void doGet(HttpServletRequest req, HttpServletResponse res)
            throws ServletException, IOException {
        res.setStatus(200);
        res.setContentType("text/plain");
        res.setCharacterEncoding("UTF-8");
        res.getWriter().write("here");
    }
}
----
```

Alternately written as:

```
[source,java,opts=linenums]
```

**Comment by mojavelinux** [comment]
I'm not sure what name to use for the option. Here are possible candidates:

* number
* numbered
* numbers
* linenums
* linenos

I'd like to narrow it down to 1 choice.

If we follow the pattern from videos, where options include "autoplay", "loop", or the existing options on verbatim blocks, "prewrap", then I think the option "number" makes the most sense.

```
[source%number,ruby]
----
puts "Hello, World!"
----
```

(We make the assumption that "number" refers to line numbers).

**Comment by mojavelinux** [comment]
Actually, I think I can define the rule. If the option is describing the semantics of the content, such as "reversed" for a list, then we want to use the adjective (past tense verb). The list is by its nature, reversed. If we are asking the processor to do something for us, such as "to number", then we should use the action (present tense verb).

In this case, the source listing is not already numbered. We are asking the processor to number it. Thus, the option should be "number" (or even number_lines, but that would be too much to type).

**Comment by mojavelinux** [comment]
An open question is whether we should reify the line numbering option on the block when it is parsed. Currently, the global setting is being checked during conversion. This makes it so line numbering can't be turned off for specific blocks.

**Comment by mojavelinux** [comment]
On further reflection, "number" seems awkward to me. I think we should go with instinct, which tells us it should be "numbered". Also, the numbering is not necessarily already defined since it is numbered based on which lines, and what offset, is specified.

```
[source%numbered,ruby]
----
puts "Hello, World!"
----
```

**Comment by hsablonniere** [comment]
:+1: for option

**Comment by mojavelinux** [comment]
For what it's worth, DocBook names the option value "numbered", so that seems to be the most natural for people transitioning.

**Comment by mojavelinux** [comment]
After giving this a lot of thought, I think I'm going to return to naming the option linenums. The reason for that decision is motivated by the name of the global option. I tried `numbered-option`, but that just felt too ambiguous. Then I thought about `source-numbered-option` or `source-numbers-option`, but something just doesn't feel right about it. I finally arrived at `source-linenums-option` and that just seems to fit.

Thus, to enable line numbers globally, you set the document option as follows:

```
:source-linenums-option:
```

To enable line numbers for a single block, define the `linenums` option as follows:

```
[source%linenums,java]
----
System.out.println("Hello, World!");
----
```

The global option is checked at the time of parsing. This gives extensions easy access to this option and allows them to disable it per block.

Note that there is not currently away in the AsciiDoc syntax to disable the line numbers for an individual block if they are enabled globally. However, as I just described, it is possible to make this adjustment using an extension (e.g., TreeProcessor).

**Comment by lamafab** [comment]
@mojavelinux 

```
[source%linenums,java]
----
System.out.println("Hello, World!");
----
```

This does not seem to work:

![image](https://user-images.githubusercontent.com/42901763/140969642-6d57c8bf-7098-4331-84d6-cce69288b41c.png)

**Comment by manueljordan** [comment]
What is the status of this? **What is the correct syntax?** I tried the syntax shown above and does not work.

I tried the syntax according with (practically same content and old):

* [Awesome Asciidoc: Adding Line Numbers to Source Code Listings](https://blog.jdriven.com/2014/08/awesome-asciidoc-adding-line-numbers-source-code-listings/)
* [Awesome Asciidoctor: Adding Line Numbers to Source Code Listings](https://blog.mrhaki.com/2014/08/awesome-asciidoc-adding-line-numbers-to.html)

Even when I checked in the official _AsciiDoc Syntax Quick Reference_ page at the [More delimited blocks](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#more-delimited-blocks) section, the close scenario is the _Example 66. Passthrough block_ and does not work too.

**Comment by mojavelinux** [comment]
The linenums option requires that you have specified a source highlighter since the line numbering is added by the syntax highlighter, not the converter. This is explained on the following page: https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/#enable-line-numbering

In the future, please direct questions about usage to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). This page explains how we communicate in this project: [docs.asciidoctor.org/about/support](https://docs.asciidoctor.org/about/support/)
