### ISSUE TITLE
The problem with the need of some inline macros (such as footnote) to stick to the last word

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1982]
At the moment footnote macro needs to be after a space or a punctuation. But the footnote sign or number should be exactly next to the last word (if there is no punctuation). The current situation creates extra space after the last word , e.g. in  docbook ` some text <footnote><simpara>some footnote</simpara></footnote>` should be `some text<footnote><simpara>some footnote</simpara></footnote>`.

I guess that a new inline macro pattern such as `[^ some footnote]`  https://github.com/asciidoctor/asciidoctor/issues/559 can fix the problem. The solution might  be also extended to other inline macros, eg [^macro: ....] 

Another solution might be to consider a symbol for ZWSP, for example `^^`

**Comment by mojavelinux** [comment]
The footnote macro does not need a space before it. The following works:

```
some textfootnote:[some footnote]
```

I realize that looks ugly. You can fix it by using a blank:

```
some text{blank}footnote:[some footnote]
```

You could also map _ to blank, as I often do to make it even shorter:

```
:_:

some text{_}footnote:[some footnote]
```

I can't think of another way to know whether the space before footnote should be significant, hence why it is the way it is today.

**Comment by mojavelinux** [comment]
And yes, I think #559 already addresses the concern you have here, so we should discuss it there.

**Comment by shahryareiv** [comment]
Good suggestion. At the same time,  I guess supporting in-bracket macro mode `[macro:]` can be a better long term solution. I will put this in https://github.com/asciidoctor/asciidoctor/issues/559.
