### ISSUE TITLE
Add support for internal and no-display blocks (not comments)

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1989]
**internal** blocks are those which are processed as normal blocks, take part in the flow of text (eg. they can cross-reference or being cross-referenced, but they are not being delivered to the rendering backend. A post-processing extension can use these blocks to create/modify an image/table that is included somewhere else in the document. 

This  allows sophisticated layouts, text overlays, and sophisticated tables

A very similar idea is suggested in https://github.com/asciidoctor/asciidoctor/issues/1958 , but this model might exclude the need for a `render::` macro

**no-display** blocks are similar to `display:none` in css, they just signal the backend that this block should not be displayed. Foe the backend with interactivity support (such as HTML+Javascript), the content of the block can be used for dynamic rendering (or any other action)

**Comment by mojavelinux** [comment]
This is possible using an extension, such as a tree processor extension. You can mark such blocks with a role, then those blocks can be removed from the tree after the blocks have been parsed. It's also possible to use the contents of the block in some novel way, either discarding the block or transforming it to something else.
