### ISSUE TITLE
Support include images as tables

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1990]
Tables are not the best competency of asciidoc. It is good if one could include images as tables. That is the image of a table (sophisticated one probably) is included but it has the right caption (e.g. Table 1) also incorporates in the right counter. So it would be `table::sometable.png[]`

This can be joined with https://github.com/asciidoctor/asciidoctor/issues/1989 so the content of the table would be inside the document (a normal table block but internal)

**Comment by rockyallen** [comment]
Could the same mechanism be used in reverse? I have a table containing a sequence of images that I want to refer to as a single figure.  Maybe
````
image::sometable.png[renderas="table"]
````
and
````
.Table as image
[renderas="image"]
|====
....
|====
````

**Comment by mojavelinux** [comment]
I don't think this has any place in standard AsciiDoc, but you are welcome to write a block macro extension that does something like this.
