### ISSUE TITLE
Double underscore attributes {_} in a block translates to emphasis

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#1991]
If we have an attribute as `_:` and use it more than one time in a block `{_} some text {_}` it will be translated into emphasis instead of two attributes. This is especially important for this case:https://github.com/asciidoctor/asciidoctor/issues/1982

**Comment by kathawala** [comment]
I'm having a similar problem. For example, consider the following text in an .adoc file:

    `__int128` is a GCC extension which allows 64 bit computers to handle 128 bit numbers.
    Let's see some uses of the `__int128` type in example C code.

The rendering of this paragraph should have "__int128" in a code block, but instead, the rendering looks like this:

_`int128` is a GCC extension which allows 64 bit computers to handle 128 bit numbers. Let's see some uses of the_ `int128` type in example C code

**Comment by mojavelinux** [comment]
Double underscore is unconstrained emphasis, which means it's going to match anywhere that is not a passthrough / literal.

The correct way to write the previous example is as follows:

```
`+__int128+` is a GCC extension which allows 64 bit computers to handle 128 bit numbers.
Let's see some uses of the `+__int128+` type in example C code.
```

See https://docs.asciidoctor.org/asciidoc/latest/text/literal-monospace/ for details.
