### ISSUE TITLE
"Differences between Asciidoctor and AsciiDoc" document seems out of date WRT compat-mode

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor#1995]
The attached test quote.txt generates very different rendering behavior for both styles of curly quotes (asciidoc style with two backquotes, which AFAIK is still supported because the transition document says nothing about it, and the new style with double-quote / backquote) depending on the title style:

    asciidoctor -b html5 -o quote.html quote.txt
    asciidoctor -b html5 -a first -o first.html quote.txt

This is confusing; is it all expected behavior? N.b. asciidoctor 1.5.5 / Debian 8.

[quote.txt](https://github.com/asciidoctor/asciidoctor/files/698824/quote.txt)
[quote.zip](https://github.com/asciidoctor/asciidoctor/files/698827/quote.zip)

**Comment by oddhack** [comment]
OK, I see this is a compat-mode thing now. However, I got confused because I was relying on http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/ , which appears not to discuss the compat-mode issues much if at all. I assumed that if it didn't tell me some asciidoc syntax was no longer supported, it *would* be supported. So this document needs revision, at least, IMO.

**Comment by mojavelinux** [comment]
This document was mostly historical to try to keep track of how Asciidoctor differed from AsciiDoc Python as Asciidoctor evolved. But Asciidoctor has quickly out paced this document. While I agree there needs to complete coverage of compat-mode in the user manual (see https://asciidoctor.org/docs/user-manual/#changed-syntax), we really should be viewing Asciidoctor as AsciiDoc and forgetting about what bugs and quirks AsciiDoc Python had.

Feel free to propose updates to that section.

**Comment by oddhack** [comment]
We are completely off of asciidoc now so the issue is no longer relevant to our needs. Closing.

**Comment by mojavelinux** [comment]
\o/
