### ISSUE TITLE
Highlighting turtle source with pygments

### ISSUE THREAD

**Issue by jechterhoff** [asciidoctor/asciidoctor#2001]
Hello,
I'm writing a document that contains source examples in Turtle (https://www.w3.org/TR/turtle/).
Pygments supports highlighting for Turtle. However, when converting asciidoc to html the Turtle examples are not highlighted.

Here is a relatively short test (that includes source examples for Turtle, SPARQL, and Java - highlighting for the latter two works):
```
:source-highlighter: pygments
:pygments-style: autumn
:pygments-linenums-mode: inline

= Test Pygments Highlighting for Turtle Example

[source,turtle]
----
@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rel: <http://www.perceive.net/schemas/relationship/> .

<#green-goblin>
    rel:enemyOf <#spiderman> ;
    a foaf:Person ;    # in the context of the Marvel universe
    foaf:name "Green Goblin" .

<#spiderman>
    rel:enemyOf <#green-goblin> ;
    a foaf:Person ;
    foaf:name "Spiderman", "Человек-паук"@ru .
----

Highlighting for the following two code examples works:

[source,sparql]
----
SELECT ?x
WHERE { ?x  <http://www.w3.org/2001/vcard-rdf/3.0#FN>  "John Smith" }
----

[source,java]
----------
public class HelloWorld 
{

       public static void main (String[] args)
       {
             System.out.println("Hello World!");
       }
}
----------
```
Result of command 'asciidoctor --version': 
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:- ex:CP850)

The HTML source code generated by asciidoctor does not contain specific markup for the Turtle example:
```html
<pre class="pygments highlight"><code data-lang="turtle">@base &lt;http://example.org/&gt; .
@prefix rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt; .
@prefix rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt; .
@prefix foaf: &lt;http://xmlns.com/foaf/0.1/&gt; .
@prefix rel: &lt;http://www.perceive.net/schemas/relationship/&gt; .

&lt;#green-goblin&gt;
    rel:enemyOf &lt;#spiderman&gt; ;
    a foaf:Person ;    # in the context of the Marvel universe
    foaf:name "Green Goblin" .

&lt;#spiderman&gt;
    rel:enemyOf &lt;#green-goblin&gt; ;
    a foaf:Person ;
    foaf:name "Spiderman", "Человек-паук"@ru .</code></pre>
```
However, for the other examples it does contain extra markup:
```html
<pre class="pygments highlight"><code data-lang="java"><span class="tok-kd">public</span> <span class="tok-kd">class</span> <span class="tok-nc">HelloWorld</span>
<span class="tok-o">{</span>

       <span class="tok-kd">public</span> <span class="tok-kd">static</span> <span class="tok-kt">void</span> <span class="tok-nf">main</span> <span class="tok-o">(</span><span class="tok-n">String</span><span class="tok-o">[]</span> <span class="tok-n">args</span><span class="tok-o">)</span>
       <span class="tok-o">{</span>
             <span class="tok-n">System</span><span class="tok-o">.</span><span class="tok-na">out</span><span class="tok-o">.</span><span class="tok-na">println</span><span class="tok-o">(</span><span class="tok-s">"Hello World!"</span><span class="tok-o">);</span>
       <span class="tok-o">}</span>
<span class="tok-o">}</span></code></pre>
```
Any ideas?

**Comment by mojavelinux** [comment]
Asciidoctor uses pygments.rb, which uses a bundled version of pygments. You can find the Pygments tree used by pygments.rb here:

https://github.com/tmm1/pygments.rb/tree/v1.1.1/vendor/pygments-main

However, I'm not seeing support for Turtle listed anywhere in Pygments, even in HEAD. If you can point to the lexer somewhere in a Pygments tree, then it's a matter of making the case to pygments.rb to upgrade the version of Pygments. However, it looks like the last update was 2 month ago, so it should be a very recent version of Pygments (perhaps even unreleased).

**Comment by mojavelinux** [comment]
Ah, nevermind. I see turtle listed in rdf.py.

**Comment by jechterhoff** [comment]
Thank you for looking into this. 
When I try the online demo at http://pygments.org/ highlighting of Turtle code works. 
I'm not sure if this is an issue with asciidoctor or with pygments.rb. If it turns out that it's the latter, I'll open an issue there.

**Comment by mojavelinux** [comment]
It looks like the turtle lexer is not mapped in the [lexers cache file](https://github.com/tmm1/pygments.rb/blob/v1.1.1/lexers) in pygments.rb. You'll need to file an issue with the project for them to regenerate that file to include the missing lexers. (https://github.com/tmm1/pygments.rb).

In the meantime, you can work around the problem by feeding a custom script to the asciidoctor command. First, create the file *register_turtle.rb* with the following content:

```ruby
require 'pygments'

::Pygments::Lexer.create name: 'Turtle', aliases: ['turtle'],
    filenames: ['*.ttl'], mimetypes: ['text/turtle', 'application/x-turtle']
```

Next, pass this script to the asciidoctor command as follows:

```
$ asciidoctor -r ./register_turtle.rb document.adoc
```

(Btw, you can use this same trick to use your own version of Pygments by calling `Pygments.start '/path/to/pygments'`. However, I haven't yet verified that works as expected.)

**Comment by jechterhoff** [comment]
The custom script works. Thank you very much for the workaround.
I'll file an issue with the pygments.rb project to regenerate the lexers cache file.

**Comment by mojavelinux** [comment]
Great!

**Comment by mojavelinux** [comment]
I can confirm that you can use your own clone of Pygments by doing the following:

First, clone the pygments repository

```
$ hg clone https://bitbucket.org/birkenfeld/pygments-main pygments
```

Next, insert the `Pygments.start` into the script you feed to the asciidoctor command. Let's call it *pygments_init.rb*.

```ruby
require 'pygments'

# use a custom Pygments
Pygments.start '/path/to/pygments'

# register missing lexers
Pygments::Lexer.create name: 'Turtle', aliases: ['turtle'],
    filenames: ['*.ttl'], mimetypes: ['text/turtle', 'application/x-turtle']
```

Now just call:

```
$ asciidoctor -r ./pygments_init.rb document.adoc
```

Of course, you could do fancy things like reading the path to Pygments from an environment variable.

**Comment by mojavelinux** [comment]
I've updated the documentation in the Asciidoctor User Manual to make this procedure more clear.

See http://asciidoctor.org/docs/user-manual/#pygments
