### ISSUE TITLE
How do I write the labeled list?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2002]
I write a list with the labeled list. The document is as follows:

```
FirstLabel::
First content 1111
SecondLabel:::
Second content
+
First content 22
```

`First content 22`  and  `Second content` are aligned. 

If I delete the `+`,  `First content 22`  and  `FirstLabel` are aligned.

**I want that `First content 22`  and  `First content 1111` are aligned.  How?**

**Comment by 1marc1** [comment]
Try this:

FirstLabel::
First content 1111
SecondLabel:::
Second content
:: First content 22

**Comment by diguage** [comment]
@1marc1 
Thanks a lot!
