### ISSUE TITLE
Unconstrained superscript?

### ISSUE THREAD

**Issue by TobiasHector** [asciidoctor/asciidoctor#2010]
Hi,

I'm trying to get markup like the following working:

```
2^^(exp~shared~ - B - N)^^
```

I.e. the bracketed portion is supposed to be superscript.

I can work around it like this:

```
2^(exp~shared~^ ^-^ ^B^ ^-^ ^N)^
```

...but that is ugly as all heck :)

It looks like from #564 there was some notion of using double caret to mean unconstrained superscript, but not clear if it was supposed to be implemented or not - though I'm guessing not?

Is this a feature that is planned/desirable? It would certainly help with my use case :)

NB: We're deliberately avoiding using stem here due to the difficulties of rendering math with asciidoctor-pdf at the moment (mostly, build times) - though we can use it if there isn't something that is workable in plain asciidoc.

**Comment by mojavelinux** [comment]
We decided not to add unconstrained super and subscripts since that is really the realm of math equations (i.e., the stem macro). (In fact, superscript and subscript have extremely limited use in prose, so the decision was the right one I believe). The proper path forward is to make stem conversion workable.

**Comment by mojavelinux** [comment]
If the question is regarding stem conversion in Asciidoctor PDF, I'd like to continue that discussion there.

https://github.com/asciidoctor/asciidoctor-pdf/issues/45

**Comment by TobiasHector** [comment]
@mojavelinux I've switched to using stem macros for these now anyway, so it's not a big deal really - more just a question of if it was intended. An answer of "no intention to support" is fine by me. Thanks!
