### ISSUE TITLE
Source block include URL

### ISSUE THREAD

**Issue by gdolle** [asciidoctor/asciidoctor#2012]
Hi, is it possible to add the feature to include code from URLs ? (it seems it's not yet implemented like for `image::`.)

```
[source, ruby]
.text_test.rb
----
include::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/test/text_test.rb[indent=0,start=1,end=10]
----
```
same for macro (#89)
```
source::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/test/text_test.rb[indent=0,start=1,end=10]
```

**Comment by abelsromero** [comment]
As for `include` this is disabled by default for security reasons, but it's implemented. You can find the details here: http://asciidoctor.org/docs/user-manual/#include-uri.

**Comment by gdolle** [comment]
@abelsromero thank you.
