### ISSUE TITLE
Source block doxygen tags (feature?)

### ISSUE THREAD

**Issue by gdolle** [asciidoctor/asciidoctor#2013]
Hi, 
Currently, to add snippets, we have to use these tags
```cpp
// tag::tagname[]
// CODE
// end::tagname[]
```
Actually it would be nice to support doxygen snippet style as doxygen is widely used (see [snippet](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsnippet)).

I don't know if it's possible with the actual parser ?

**Comment by mojavelinux** [comment]
You're welcome to propose this change to the AsciiDoc Language project. For now, we're keeping it the way it is in Asciidoctor as many people rely on it and find it to be sufficient for their needs.

Keep in mind you could write an include processor extension to filter the lines of an include file in whichever way you wish.
