### ISSUE TITLE
include statements within (included) tables

### ISSUE THREAD

**Issue by stefanct** [asciidoctor/asciidoctor#2017]
Including multiple files within a single table cell is quite a mess with asciidoctor. If the table itself is in the top level document you simple need to start every include statement on a new line as common(ly annoying) in asciidoc. But if the table itself is included, things start to become clusterfucky. Apparently, the file suffix triggers some parsing functionality but some others work fine without it(!?!?!). In the example files the `table.table` should be named `table-table.adoc` or similar to get it to work better.

Still I deem the behavior buggy because apparently some adoc directives like asterisks and `link::` are handled correctly with any suffix and there is 0 indication what's wrong. Also, asciidoc seems to handle this correctly.

But it gets even more funnier if one tries to include files from a directory in a table residing in a subdirectory that gets itself included from a file in the parent directory, e.g., main.adoc includes build/table.adoc, which includes file.adoc, or as dir listing:

    build/table.adoc # include::file.adoc[]
    file.adoc
    main.adoc # include::build/table.adoc[]

But wait... shouldn't the include in the table not require an additional `../`? Apparently not the first include in any cell, but if you have multiple includes then all but the first one require to have a `../` prepened  to the file name(!).

[include.adoc.txt](https://github.com/asciidoctor/asciidoctor/files/760592/include.adoc.txt)
[includes.adoc.txt](https://github.com/asciidoctor/asciidoctor/files/760591/includes.adoc.txt)
[table.adoc.txt](https://github.com/asciidoctor/asciidoctor/files/760590/table.adoc.txt)
[table.table.txt](https://github.com/asciidoctor/asciidoctor/files/760589/table.table.txt)

Using some more rigorous unit tests I am pretty sure the table/include code of asciidoctor will explode even more. It will be a tremendous explosion with a big fire. Sad!

**Comment by mojavelinux** [comment]
I'm committed to helping users succeed with Asciidoctor, but to do so we all must agree to maintain a professional culture. I'm closing this issue because of the way in which you wrote it, specifically the tone and profanity. I do not think it shows respect for the community who works on this tool, including myself. If you're willing to file a new issue that presents the problem in a respectful and productive manner, then I'm willing to look deeper into what is causing you trouble. If you plan to do so, I thank you in advance.

**Comment by stefanct** [comment]
I am not surprised that you are reacting like that at all. asciidoctor treated me the whole day exactly the same :) I presented you a number of bugs and included a MWE, which is really more than it deserved for how irregularly it is behaving. If you don't want to fix obvious bugs in your code that's your decision. I am working around all of this externally now. But at least now any successors won't have to wade through the swamp themselves but can work around it after finding this bug report: avoid any fancy adoc syntax within table cells before you tear out your hairs until these bugs are fixed.

**Comment by mojavelinux** [comment]
If you continue to use that tone and show disrespect for this community, I will have no choice but to ban you from participating. It pains me to have to do that, and I really want to be of service to the community, but I simply cannot stand for this type of abuse in this community. We run a very respectful community and I am committed to upholding that. Thank you in advance for recognizing and respecting our values.
