### ISSUE TITLE
User specified footnoteref ID which is the same as the footnote number leads to duplicate HTML id attributes

### ISSUE THREAD

**Issue by djerius** [asciidoctor/asciidoctor#2019]
I couldn't come up with a clever footnote ID, so I decided to use numbers, e.g.

```
footnoteref:[1,Footnote 1]
footnoteref:[2,Footnote 2]
footnoteref:[3,Footnote 3]
```

Much to my surprise, the resultant footnote links didn't target the footnotes at the bottom of the page; instead they targetted  the first time the footnote was referenced in the body of the text.

Here's the relevant output html for the references in the body:

```
<sup class="footnote" id="_footnote_1">[<a id="_footnoteref_1" class="footnote" href="#_footnote_1" title="View footnote.">1</a>]</sup>
<sup class="footnote" id="_footnote_2">[<a id="_footnoteref_2" class="footnote" href="#_footnote_2" title="View footnote.">2</a>]</sup>
<sup class="footnote" id="_footnote_3">[<a id="_footnoteref_3" class="footnote" href="#_footnote_3" title="View footnote.">3</a>]</sup>
```

And for the footnotes

```
<div class="footnote" id="_footnote_1">
<a href="#_footnoteref_1">1</a>. Footnote 1
</div>
<div class="footnote" id="_footnote_2">
<a href="#_footnoteref_2">2</a>. Footnote 2
</div>
<div class="footnote" id="_footnote_3">
<a href="#_footnoteref_3">3</a>. Footnote 3
```

The `sup` elements in the references have the same id attribute as the `class` elements in the definitions.

Please consider making the prefix in the `sup` `id` attribute unique to them so that they cannot clash with those in the definitions.

Thanks,
Diab

**Comment by mojavelinux** [comment]
How about we use the prefix `_footnotedef_` for the footnote entry, `_footnoteref_` for the reference, and `_footnote_` for the custom ID? That way, the ID won't clash.

For example, in the case you cited:

```
<sup class="footnote" id="_footnote_1">[<a id="_footnoteref_1" class="footnote" href="#_footnotedef_1" title="View footnote.">1</a>]</sup>
```

and

```
<div class="footnote" id="_footnotedef_1">
<a href="#_footnoteref_1">1</a>. Footnote 1
</div>
```
