### ISSUE TITLE
string starting with underscore gets italicized

### ISSUE THREAD

**Issue by codynguyen** [asciidoctor/asciidoctor#2020]
Hi,

I have this piece of source converted from swagger API, which has an `_id` attribute which is optional:

```
[options="header", cols=".^3,.^11,.^4"]
|===
|Name|Description|Schema
|*_id* +
_optional_|ID of the item within the system. +
*Pattern* : `"^[a-fA-F0-9]{24}$"` +
*Example* : `"5742b1f7535cf2baba8fff91"`|string
|*currency_gain* +
_optional_|Gain value over the specified period, in investment/asset currency.|number
|===
```

which gets rendered into

<img width="248" alt="screen shot 2017-02-14 at 2 24 46 pm" src="https://cloud.githubusercontent.com/assets/252787/22919257/62bedb48-f2c1-11e6-9104-bd39e3b0d7ab.png">

There are 2 problems with the results: 1) `_id` is missing the underscore and is italicized, and 2) `optional` is prefixed with an underscore and is not italicized.

The expected result can be seen in the line below for `currency_gain`, in which `currency_gain` is bold + not italic, where as `optional` is normal weighted + italic.

When I tried to escaped the underscore being recognized as italic handle by adding a back slash before `_id` so it becomes `\_id`:

```
[options="header", cols=".^3,.^11,.^4"]
|===
|Name|Description|Schema
|*\_id* +
_optional_|ID of the item within the system. +
*Pattern* : `"^[a-fA-F0-9]{24}$"` +
*Example* : `"5742b1f7535cf2baba8fff91"`|string
|===
```

Then I get this result:

<img width="240" alt="screen shot 2017-02-14 at 2 14 14 pm" src="https://cloud.githubusercontent.com/assets/252787/22919029/1ec3988a-f2c0-11e6-8292-4f3b7e440fac.png">

Which is better because `_id` doesn't loose the underscore, but `optional` now displays as `_optional_` (not italicized and wrapped by underscores).

Is there anyway to work around this problem so that `_id` is displayed in full, and `optional` gets italicized without being wrapped by underscores?

Thanks a lot!

**Comment by JBR69** [comment]
Try this (use pass:[] for the underscore od -id)
```
[options="header", cols=".^3,.^11,.^4"]
|===
|Name|Description|Schema
|*pass:[_]id* +
_optional_|ID of the item within the system. +
*Pattern* : `"^[a-fA-F0-9]{24}$"` +
*Example* : `"5742b1f7535cf2baba8fff91"`|string
|*currency_gain* +
_optional_|Gain value over the specified period, in investment/asset currency.|number
|===
```

**Comment by mojavelinux** [comment]
You can also use a backslash in this case. It's important to keep in mind that backslashes are only recognized if formatting would be applied. In this case, it would be.

Your use case happens to be a valid formatting request, thus you have to take additional action.

**Comment by mojavelinux** [comment]
Actually, I misspoke. A backslash confuses things in this case. The other way to approach this is to make the italic around optional more explicit by using unconstrained italics.

```
*_id* +
__optional__
```

Then you get the result that you want.

**Comment by codynguyen** [comment]
Thanks @JBR69 & @mojavelinux for your answers. 

I haven't actually tried them yet because they require making changes directly in the adoc file, while my adoc file is generated by http://swagger2markup.github.io/. I'm asking the guys at swagger2markup to see if there's any option to produce the adoc with your suggested markup.

I also wonder if this can be considered a bug in asciidoctor and if it can be fixed in order to support words prefixed by an underscore? Otherwise I think it's OK to close this issue

**Comment by elextr** [comment]
Its an implementation issue that Asciidoctor, Asciidoc Python and several other lightweight markup implementations have.  

They parse and process each markup type one at a time, so when the parser is processing italic markup and it sees the underscore ahead of `id` it is not aware that this is inside the stars markup and finds the underscore after `optional` as a match, whereas since there is no matching end underscore also inside the stars then it should be recognised that it can't be markup and can just be left as text. 

This can only be solved by a full language parser which would recognise the star markup and therefore only recognise markup that nested properly.  Unfortunately such a parser is extremely difficult for markup languages which are highly context dependent (so ruling out most formal tools and methods) and are also full of that human language rubbish that isn't parsable :).

**Comment by mojavelinux** [comment]
Nice explanation @elextr.

I don't think it's that difficult to write such a parser. There will be some edge cases we'll need to deal with, but we'll get there. I just need time and resources to do it, which I'm working to amass.

I do want to point out that if a word has a leading underscore, and there is a matching underscore at the end of another word, that is actually a valid formatting request. Not even a proper parser would stop that match. (It could be programmed to honor all backslashes, which is one of the open requests in Asciidoctor). Now, if that underscore is inside of another formatting mark, then the range of formatting should be restricted to be inside of that format context. So in your specific case, you could argue that the underscore should be treated literally. But that would only come with a proper parser. So really, this is just another test case for #61.

**Comment by mojavelinux** [comment]
I added the test case to #61, so we can close this issue as the information has been preserved there.

**Comment by viebel** [comment]
No matter what I tried, I couldn't find a way to have a underscore inside a monospace span in the following use case:


![image](https://user-images.githubusercontent.com/955710/147910124-e38cef52-88b3-453e-8c76-07fc122688c4.png)



```
-*JOE*: You simply replace each occurrence of `_` with `Immutable`: `_.map` becomes `Immutable.map`, `_.filter` becomes `Immutable.filter` and `_.isEqual` becomes `Immutable.isEqual`.
```
The solution I came up with was to define `underscore` in the beginning of the document, like this:

```
+:underscore: _

+*JOE*: You simply replace each occurrence of `{underscore}` with `Immutable`: `{underscore}.map` becomes `Immutable.map`, `{underscore}.filter` becomes `Immutable.filter` and `{underscore}.isEqual` becomes `Immutable.isEqual`.
```

**Comment by mojavelinux** [comment]
Please direct support questions and feedback to the project chat at https://asciidoctor.zulipchat.com.
