### ISSUE TITLE
How to deal document to many html files with asciidoctor?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2027]
I separate a large document to many small document. 

**I want to deal document to many html files with asciidoctor. How?**

_I read the user manual. But I did not find the method._

PS:

[30.3. Inter-document Cross References](http://asciidoctor.org/docs/user-manual/#inter-document-cross-references) is greate. **How to use Inter-document Cross References?** I mean I want to deal document to many html files with asciidoctor. 

**I want to pick up the table of content to index.html. How ?**

~~Could I pick up the stylesheet to a single file?~~

I found it generate two stylesheet file: asciidoctor.css and <heightlight>-asciidoctor.css. **How to combine to a single file?**

**Comment by diguage** [comment]
@mojavelinux 

I write a bash script to pick up the stylesheet to a single file.

```bash
#!/bin/bash

html_file_name=index.html
out_file_name=index.html

while getopts "i:o:" arg # argument
do
    case $arg in
        i)
        html_file_name=$OPTARG
			;;
        o)
        out_file_name=$OPTARG
			;;
        ?)  
        echo "unkonw argument, exit"
        exit 1
      ;;
    esac
done

style_file_name=adstyles.css

gsed=`which sed`
if [[ `uname` == Darwin* ]]
then
  gsed=`which gsed`
fi

cssnano=`which cssnano`
if [ ! -n `which cssnano` ]; then
  npm install cssnano-cli --global
  cssnano=`which cssnano`
fi

## declare a array, store the line numbers
declare -a start_lines=(`awk '/<style>/{print NR}' $html_file_name`)
declare -a end_lines=(`awk '/<\/style>/{print NR}' $html_file_name`)

# array length
arraylength=${#start_lines[@]}

# pick up the stylesheet to a single file
for (( i=0; i<${arraylength}; i++ ));
do
  $gsed -n "${start_lines[$i]}, ${end_lines[$i]}p" $html_file_name | grep -v "style>" | grep -v "/\*" 1>> $style_file_name
done

# remove the stylesheet from the html file
for (( i=${arraylength}-1; i>=0; i-- ));
do
  $gsed -i "${start_lines[$i]}, ${end_lines[$i]}d" $html_file_name
done

# compass the stylesheet file
$cssnano $style_file_name $style_file_name

# add the stylesheet file to the HMTL
$gsed -i "s/\(<\/head>\)/<link rel=\"stylesheet\" href=\".\/${style_file_name}\">\n\1/" $html_file_name
```

**Comment by diguage** [comment]
I found to link a stylesheet file. I should set the `linkcss` attribute.

**Comment by mojavelinux** [comment]
It's important to keep in mind that Asciidoctor itself has a single-file scope. It relies on another tool to organize a documentation project. One way to approach that is, as you have done, create a script. But there are lots of other readily available options out there. A very popular way is to use a build tool like Gradle, Maven, or Gulp, all of which have plugins for Asciidoctor. Another are the plugins for general purpose static site generators like Jekyll and Middleman. A newer, and more comprehensive solution, is Antora, which coordinates the generation of a complete documentation site using AsciiDoc files stored in one or more git repositories.

What I just said needs to be included in the new documentation site for Asciidoctor, which is based on Antora.

**Comment by cup** [comment]
https://github.com/asciidoctor/asciidoctor.org/issues/840
