### ISSUE TITLE
If I include a document into Asciidoctor document, how to get the file name?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2028]
If I include a document into Asciidoctor document. **Could I get the file name or the file path? How?**  

I want to show the file name.

**Comment by rdmueller** [comment]
I think this is a duplicate #2608 , isn't it?

**Comment by mojavelinux** [comment]
Yes, that's correct. Since the other issue has more detail and discussion, I'll close this one as a duplicate.
