### ISSUE TITLE
I set the lang attribute, but the i18n labels do not show.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2031]
I view the sources of the project. I found that the file `asciidoctor/data/locale/attributes.adoc` provides the labels with i18n. 

I look at he document [Customizing built-in labels
](http://asciidoctor.org/docs/user-manual/#customizing-labels), follow the document, I could use the build-in i18n labels.

```
asciidoctor -a lang=zh_CN mydoc.adoc
```

**But, the labels is shown on English.**

My environment:

```
$ asciidoctor -v
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

$ ruby -v      git:(master|✚1
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
```

**Comment by elextr** [comment]
As the manual section you referenced above says, automatic language support is currently only provided for docbook outputs because the toolchains do it.

If you look at #1129 you will see that the `asciidoctor/data/locale/attributes.adoc` file is only a holding place, it is not used automatically by asciidoctor yet.

**Comment by mojavelinux** [comment]
Correct. To be more clear, you need to include that file in the header of your document so the attributes get imported. For example:

```
= Document Title
include::locale/attributes.adoc[]
```

(obviously, the path has to exist).

**Comment by mojavelinux** [comment]
Reopen if you need additional assistance.

**Comment by diguage** [comment]
Ok, I could write the tips into the manual document. 
Thanks a lot.

**Comment by diguage** [comment]
I send a PR <https://github.com/asciidoctor/asciidoctor.org/pull/652>
