### ISSUE TITLE
Allow preload attribute to be set on video HTML5 element

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor#2046]
Hello,

asciidoc(tor) doc mentions the ability to use `options` to provide some additional `video::[]` macro options but it seems the HTML `preload` attribute to be missing.

I am willing to generate a `<video src="..." preload="metadata"></video>` tag in the end. `buffered` can be nice to control how much a user would download on his end.

Cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes

Any thoughts?

**Comment by mojavelinux** [comment]
We can certainly add this support. It seems to me like it should be an attribute (key/value pair) since it accepts multiple values.

Also, is "auto" the right default or should we use a different value?

**Comment by oncletom** [comment]
If no value is provided for `preload`, indeed it should be understood as `auto`.

If no `preload` attribute is added to the video element, it is already understood as being `auto`.
