### ISSUE TITLE
Add see and see also support to index term macros

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2047]
Add support for "see" and "see also" metadata to the index term macros.

* "see" directs the reader to another location in the index (and does not have any other terms or a page number)
* "see also" directs the reader to other, possibly related terms in the index, but is otherwise a normal index term

For reference, see http://tdg.docbook.org/tdg/5.0/indexterm.singular.html.

(I think we can abbreviate "seealso" as just "also").

Refer to http://chimera.labs.oreilly.com/books/1234000001578/ch02.html for inspiration. However, we need to make sure we remain faithful to AsciiDoc syntax patterns.

**Comment by mojavelinux** [comment]
For the formal forms (indexterm and indexterm2 macros), I suggest simply adding the `see` and `also` attributes.

```
indexterm2[Flash,see=HTML5] has been supplanted by indexterm2:[HTML5,also=SVG].
```

For the informal form, I propose the following syntax:

```
((Flash >> HTML5)) has been supplanted by ((HTML5 || SVG)).
```

* \>> indicates "see" (a redirect)
* || indicates "see also" (a logical or)

This will produce the following index:

```
F
Flash (see HTML5)

H
HTML5, 1
  (see also SVG)
```

I'm open to other suggestions.

**Comment by apnadkarni** [comment]
The above suggestions seem reasonable to me. Although I might prefer +> or ++ to ||

**Comment by mojavelinux** [comment]
To the greatest degree possible, I try to build syntax on existing conventions. In most programming languages, `||` represents a logical or, which I think maps well to the phrase "or you could also see". Do you have a reference to where `+>` or `++` are used for this purpose / meaning?

**Comment by apnadkarni** [comment]
I was thinking ">>" as see and the "+>" as "additionally see"

**Comment by mojavelinux** [comment]
Okay, I could possibly get behind that if we reversed the order of the second symbol. `>>` as see (aka redirect) and `>+` as (also see, but not a redirect).

**Comment by mojavelinux** [comment]
That would look like:

```
((Flash >> HTML5)) has been supplanted by ((HTML5 >+ SVG)).
```

**Comment by apnadkarni** [comment]
I think I like this last suggestion best.

**Comment by mojavelinux** [comment]
Excellent! Then we're ready to move forward to implementation!

**Comment by mojavelinux** [comment]
I think I like this better.

```
((Flash >> HTML5)) has been supplanted by ((HTML5 >>~ SVG)).
```

It's also easier to parse because it has the same root.

**Comment by mojavelinux** [comment]
I'd be willing to go back to `||`. Anything else just doesn't feel right or conflicts with syntax we already have.

**Comment by mojavelinux** [comment]
I think this looks very reasonable:

```
((Flash >> HTML5)) has been supplanted by ((HTML5 || CSS 3 || SVG)).
```

It also removes all ambiguity that I can think of. I'll float three other options, but we can't dwell on this for long.

```
((Flash >> HTML5)) has been supplanted by ((HTML5 << CSS 3 << SVG)).
```

```
((Flash >> HTML5)) has been supplanted by ((HTML5 ~> CSS 3 ~> SVG)).
```

```
((Flash >> HTML5)) has been supplanted by ((HTML5 |> CSS 3 |> SVG)).
```

We absolutely have to avoid using the `+` character because that is passthrough and it will cause a world of headaches if we try to use it.

**Comment by apnadkarni** [comment]
I prefer || but really, as I said, I was nitpicking and in fact thinking about it, >>~ also works as the >> prefix ties the see and see also together. So as a mnemonic, that might even be better than ||.

So I'm equally happy with either || or >>~  ! I think either would work well.

**Comment by faunaee** [comment]
I like the way that this has progressed. One question: for the shorthand form, does the verb have to be a double character? Could we consider just `>` for "see" and `|` for "also"?

```
((Flash > HTML5)) has been supplanted by ((HTML5 | CSS3 | SVG))
```

I think the only downside is that there might be a greater requirement for escapement in certain books where `>` and `|` must appear in the index. I have no idea how often that would be the case, but my feeling is that it may be very rare.

If the parser requires a double-character verb, then I'm good with `>>` and `||`.

**Comment by mojavelinux** [comment]
> Could we consider just > for "see" and | for "also"?

One because it's very likely they could show up in a term, and that just creates all sorts of problems. But we're also keeping them reserved for other meanings in the event that we do need them (regarding hierarchy).

**Comment by mojavelinux** [comment]
I must admit I'm really liking `<<`. That maps to the 'push' idiom in Ruby, which can be read as an "also".

```
((Flash >> HTML5)) has been supplanted by ((HTML5 << CSS 3 << SVG)).
```

So I'd say it comes down to `<<` or `||`.

**Comment by Mogztter** [comment]
> So I'd say it comes down to << or ||.

Then I'd vote for `||`.
I don't like `<<`, it reads as the opposite of `>>`. At least for me, it's not clear why the same symbol left to right is "see" and right to left is "see also". I'm not an expert but it could also be confusing for language written from right to left.

> That maps to the 'push' idiom in Ruby, which can be read as an "also".

In my opinion, it's a bit far-fetched.

**Comment by elextr** [comment]
> > That maps to the 'push' idiom in Ruby, which can be read as an "also".

> In my opinion, it's a bit far-fetched.

Agree, and Asciidoc is for writers, not Ruby coders.  Also `<<` and `>>` are "shift" in many programming languages so it doesn't map well.

**Comment by mojavelinux** [comment]
I've given it more thought and I feel very strongly about `>>` and `<<`. They work really nicely because they are complements of each other (and thus easy to remember the as a pair). `>>` is a redirection operator, so it maps very nice to "see". And I like `<<` because it says "append" / "attach" these things to this entry.

When I think more about `||`, the problem I have with it is that it sounds like you're saying "create this index term or this index term or this index term". So while initially it felt right, it breaks now that I realize that.

**Comment by elextr** [comment]
> When I think more about ||, the problem I have with it is that it sounds like you're saying "create this index term or this index term or this index term". So while initially it felt right, it breaks now that I realize that.

Yeah, I had the same feeling, but that says it should be `&&` not `>>`?

**Comment by Mogztter** [comment]
> I've given it more thought and I feel very strongly about >> and <<. They work really nicely because they are complements of each other (and thus easy to remember the as a pair). >> is a redirection operator, so it maps very nice to "see".

What about `&>` then ? it's easy to remember "and see" ("see also").

> When I think more about ||, the problem I have with it is that it sounds like you're saying "create this index term or this index term or this index term". So while initially it felt right, it breaks now that I realize that.

The other issue with `||` and `&&` is that the "link" is gone. With an arrow you visualize a chain: 
```
(( HTML5 &> CSS 3 &> SVG))
```

HTML5 and see (also) CSS 3 and see (also) SVG.

> And I like << because it says "append" / "attach" these things to this entry.

Still sound like a coder thing 🤓

**Comment by mojavelinux** [comment]
> What about `&>` then ?

I lunch on it.

**Comment by faunaee** [comment]
"See" is for tightly-bound index terms, mostly (but bot always) direct synonyms or greatly-overlapping semantics. There is also the implicit navigation element. So I agree that `>>` works well for "see".

"See also" is for loosely-bound index terms, where the semantics one of "also" term can enhance the understanding of the primary term. There is still an implicit navigation element. In that respect, while `<<` does imply append in Ruby (it's a bitwise shift in many other places), and it reverses the navigation context in a way that makes far less sense, and implies that there is still a tight binding between terms.

`||` has a different connotation, indicating (typically) that any term satisfies the reader's interest, which is also not the best fit for "see also".

I do like the suggestion of `>>` and `&>`.

Would `=>` and `->` work better? Those have a stronger navigation implication, but don't violate the notion of primary/secondary terms.

Or, to avoid the overt navigation implication, perhaps `:=` to indicate tight-binding, and `:>` for loose?

In the end, I don't feel particularly strongly about any particular syntax. It's far more important to me to be able to express "see" and "see also", whatever the mechanism. So if there are strong feelings for `>>` and `<<`, I can live with that solution.

**Comment by mojavelinux** [comment]
I let `&>` sit for a while, looked at it from different screens, and I've really come to like it. I can see the "and see" come through. Let's go with it.

> Would => and -> work better

These are problematic because they are replacements, so we have to look for the replaced value, which seems really fragile.

> to avoid the overt navigation implication, perhaps := to indicate tight-binding, and :> for loose?

I think that gets us back into programming / math terms, which as @Mogztter points out requires pretty specialized knowledge.

**Comment by mojavelinux** [comment]
I went back and changed "also" to "see-also" since at least three standards use that terminology and we want to go with what's most familiar.

**Comment by mojavelinux** [comment]
Thanks everyone for your input!
