### ISSUE TITLE
Enable attributes in the link macro by default (set linkattrs attribute)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2059]
It's strange that the link macro behaves differently than other macros. It only accepts attributes if the `linkattrs` document attribute is set, which is only a feature of Asciidoctor. The link macros should have attributes on by default.

We now have smart parsing of the attribute text so as not to catch cases when the alt text contains a comma (a common scenario). Since we have this parsing, we should be able to safely enable this feature.

One compromise is to enable link attributes by default when the link prefix is used, but not for raw URLs. Personally, I think this would just create more confusion than it's worth, but we can discuss.

This feature can remained disabled by default when compat mode is set.

**Comment by mojavelinux** [comment]
As proposed in https://github.com/asciidoctor/asciidoctor/issues/2381#issuecomment-383777594, I'd like to take a different strategy here. I'd like to change it so that attribute parsing kicks in when an equal sign is present (except when compat mode is on, of course). And the `linkattrs` attribute will now be ignored.

**Comment by elextr** [comment]
Shouldn't attribute lists always be parsed?  Unescaped `,` and `<name>=` being the meta characters?

**Comment by mojavelinux** [comment]
See my reasoning in the linked comment. I've looked into a lot of documents and this is the safest way to make this change without breaking documents (close to zero, and most of those edge cases are bad syntax anyway).
