### ISSUE TITLE
How to get the translation result (HTML) of single asciidoc command?

### ISSUE THREAD

**Issue by Gitward** [asciidoctor/asciidoctor#2060]
I'm trying to find out how certain asciidoc commands are translated to HTML.

For example `echo "= H1" | asciidoctor -` should return:

```
<h1>H1</h1>
```
For example `echo "== H2" | asciidoctor -` should return:

```
<div class="sect1">
<h2 id="_h2">H2</h2>
<div class="sectionbody">

</div>
</div>
```
For example `echo "text" | asciidoctor -` should return:

```
<div class="paragraph">
<p>text</p>
</div>
```

1. Where are the definitions of what happens to the asciidoc commands? (I guess it is in a template file)
2. Is there a list with examples?
3. I'd like to play around and maybe build such a list. The output I generate is very long. I tried using the `-s` option (`echo "text" | asciidoctor -s -`) but then ascidoctor return nothing.
4. Is there another way to understand how the output of asciidoctor is generated? **Actually I only want to build a stylesheet and therefore need to understand how the output is organized.** Looking an the HTML output seems to be the easiest ways, since there are no docs showing which tags and attributes are used for a given command - are there (@mojavelinux)?

**Comment by mojavelinux** [comment]
The flags you are looking for to generate the output for just the content part is `-s` (which means disable the header/footer, aka chrome) and `-` which accepts input from STDIN. For example:

```
echo "== H2" | asciidoctor -s -
```

If you just want to study the HTML that is generated, have a look at the [built-in HTML converter](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb). Asciidoctor traverses the AST and invokes the methods in this class to convert each node in document order.

To customize the HTML, you either need to write a custom converter or you supply a template file for the node in question. All the HTML can be customized. The template option accommodates à la carte customizations, whereas the custom converter gives you complete control over the output. (It's also possible to combine the two options).

I'm bit ashamed to say I still haven't gotten around to writing the documentation for creating a custom converter. You can find the raw notes in the following issue: https://github.com/asciidoctor/asciidoctor.org/issues/80.

To see a list of most templates, a good reference is the Bespoke converter. See https://github.com/asciidoctor/asciidoctor-bespoke/tree/master/templates/slim. You only need to supply templates for nodes you want to customize.

**Comment by Gitward** [comment]
@mojavelinux 
Any idea, why `echo "= h1" | asciidoctor -s -` returns an empty result?

**Comment by mojavelinux** [comment]
Because that syntax is the document title, which is not included by default in the embeddable HTML output. You need to turn it on explicitly using the `showtitle` attribute.

```
echo "= h1" | asciidoctor -s -a showtitle -
```

which is the same as:

```
echo "= h1" | asciidoctor -s -a notitle! -
```

You can see where that is decided here: https://github.com/asciidoctor/asciidoctor/blob/2417881053c5e687643428fe67fec628cc135edb/lib/asciidoctor/converter/html5.rb#L263-L266

**Comment by Gitward** [comment]
@mojavelinux Thanks.
