### ISSUE TITLE
Failed to render page with asciidoc-1.5.5 with gollum framework

### ISSUE THREAD

**Issue by d-nnis** [asciidoctor/asciidoctor#2066]
I have installed [gollum framework](http://github.com) to get an asciidoc-parsed wiki to work.
It has failed with the latest asciidoctor version 1.5.5. This is the output:
> Failed to render page: undefined method `unique_id_start_index=' for Asciidoctor::Compliance:Module

See this issue: https://github.com/gollum/gollum/issues/1199

However, with version 1.5.0 it works!
Could you elaborate on when this bug(?) was introduced?
Thank you!

**Comment by mojavelinux** [comment]
This is not a bug in Asciidoctor. If anything, it's in github-markup, which is the library attempting to set this flag. But if you use at least Asciidoctor 1.5.2, then you should be able to use github-markup just fine. This flag was introduced in that version.

Please check that you are, in fact, using Asciidoctor 1.5.5. I can't see anyway it would fail if you are really using that version.

**Comment by d-nnis** [comment]
Well what can I say. Even though I specifically _wanted_ to install v1.5.0 via...
> gem install asciidoctor -v 1.5.0

I really have version 1.5.5 running in my server.
> Asciidoctor 1.5.5 [http://asciidoctor.org]
> Runtime Environment (ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

So you are right, everything is fine. Thanks for noticing!

**Comment by mojavelinux** [comment]
I could only suggest it because it's such a common occurrence when installing Ruby gems ;)
