### ISSUE TITLE
Atx-style headings should not be recognized if leading characters are mixed

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2074]
Asciidoctor recognizes both the AsciiDoc and Markdown-style atx headings.

```
=== Heading

### Heading
```

However, due to a bug in the regular expression, it's also matching a mix of leading characters:

```
=#= Heading
```

This syntax should not be recognized. Fix the regular expression and add a test to verify that this syntax is not matched.

**Comment by ds26gte** [comment]
The fact that Asciidoctor reads some occurrences of `#`, `*`, `-` in Markdown fashion forces users to rephrase (often verbosely) areas of text where these were originally treated verbatim by AsciiDoc. Perhaps these concessions to Markdown syntax should only come into effect when the first heading in the document has a Markdown syntax?

**Comment by mojavelinux** [comment]
One way is to turn off Markdown support in the compliance section:

```
Asciidoctor::Compliance.markdown_syntax = false
```

But I like the idea that once it matches an atx heading of one style (hash or equals), it sticks with that style. Please file a new issue and we can pursue that change.
