### ISSUE TITLE
Inconsistent error output with "file does not exist or cannot be read"

### ISSUE THREAD

**Issue by blueyed** [asciidoctor/asciidoctor#2089]
Given `t.asciidoc`:

    :stylesheet: asciidoc.css

`asciidoc` will adhere to the errorformat (includes the file name):
```
% asciidoc t.asciidoc
asciidoc: WARNING: t.asciidoc: line 1: include file not found: /etc/asciidoc/asciidoc.css
```

But `asciidoctor` does not:
```
% asciidoctor t.asciidoc
asciidoctor: WARNING: file does not exist or cannot be read: /home/user/src/neomake/asciidoc.css
```

Other errors will include the file name:
```
asciidoctor: ERROR: t.asciidoc: line 116: only book doctypes can contain level 0 sections
asciidoctor: WARNING: t.asciidoc: line 117: section title out of sequence: expected level 1, got level 2
```

Having the filename (and a consistent output format) is important when being used as a linter (I am adding it to Neomake currently: https://github.com/neomake/neomake/issues/1128).

Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
I can certainly add the filename of the source file in this warning message. However, I don't think the line number makes sense in this case. There are various ways to set an attribute and we don't track the line where an attribute is set.

**Comment by mojavelinux** [comment]
In this case, I'll also update the message to say "stylesheet" instead of just "file". That way, it's clear why it is being accessed.

**Comment by mojavelinux** [comment]
This is just a matter of updating the `read_asset` method to output the value of the docfile attribute (or `<stdin>` if the docfile attribute is not set.
