### ISSUE TITLE
discussion: blogpost support?

### ISSUE THREAD

**Issue by suntong** [asciidoctor/asciidoctor#209]
I know that there are static site generation tools exist e.g. Awestruct, but that's more a enterprise level solution. 

Hope your team can implement blogpost alike for asciidoctor -- a tool for individual person  to post their blog to some exiting blog sites. E.g.,

Stuart's blogs are 100% generated by AsciiDoc (via blogpost) https://srackham.wordpress.com/

Here's the example article from the AsciiDoc distribution and the blogpost README:

https://srackham.wordpress.com/asciidoc-example-article/
https://srackham.wordpress.com/blogpost-readme/

Please consider. 

Thanks

**Comment by metasean** [comment]
For other users looking for a more friendly front-end, and mad-crazy-easy installation process, checkout https://github.com/HubPress/hubpress.io . It's still very much in early development, but the early development is clearly moving toward the front-end I am looking for.

**Comment by mojavelinux** [comment]
:+1: HubPress.io is definitely one of the official methods of publishing a blog in AsciiDoc. You might also consider a static site generator like Middleman or JBake.

**Comment by tiensonqin** [comment]
Hi, you can also try [Hidifferent](https://hidifferent.com).

It has some blog features (Github sync, RSS, Tags), this is mine: 
https://hidifferent.com/@tiensonqin

**Comment by mojavelinux** [comment]
As we've determined that this is best handled by tools that integrate with Asciidoctor, I'm closing this issue as there is no action to take here. Feel free to continue to use the thread for discussion, or you can shift the discussion to http://discuss.asciidoctor.org.
