### ISSUE TITLE
Support different styles of quotes

### ISSUE THREAD

**Issue by ecki** [asciidoctor/asciidoctor#2092]
As discussed in #1680 it might be a good idea to support different styles of quotes. For example to differentiate between a persons speach and an excerpt from an external reference.

@mojavelinux proposed:

    [quote.excerpt,Author,Title]

(and possibly others). Themes can represent `quote.excerpt` by using less decoration and expecting longer text fragments.

**Comment by mojavelinux** [comment]
Agreed. We should at least support a generic blockquote and a fancy one. This is related to #2480 (which deals with verse blocks).

**Comment by mojavelinux** [comment]
I've run into this enough times to understand the problem now. What we need to agree on is how to label a fancy vs standard blockquote. A fancy one looks like a quote with the quote symbol and all. A standard one is just a vertical bar.

I thought about requiring the role "fancy" to preserve the existing styling. However, it might be better to describe when not to use fancy, and for that, the word excerpt fits really well. Plus, it will be easier for people to transition to add a role to get a different style than to require everyone who relies on the current style to change.

**Comment by mojavelinux** [comment]
I've have proposed a change. See #2894.

@ecki One open question remains. Do you expect the text to be light gray (60% gray) or should it match the color of the normal paragraph text (80% gray)?

**Comment by ecki** [comment]
Hm.. I guess styling should be configurable for the two different classes of quote. In my case 60% will be frowned upon but I can see the appeal to make it different.

**Comment by mojavelinux** [comment]
Thanks for the follow-up. That tells me what I need to know. We'll go with the default text color for now and see how it plays out.

> I guess styling should be configurable for the two different classes of quote

The styling is always configurable. We're just talking about what the default stylesheet provides.
