### ISSUE TITLE
Add Support for Highlight

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#2096]
This is a feature request:

Could you add support for **Highlight** syntax highlighter?

http://www.andre-simon.de/doku/highlight/en/highlight.php

Asciidoc python supported this highlighter, and projects relying on it (because of some particular lang definition) would require Highlight to be supported in order to work with AsciiDoctor.

Highlight has some advantages over the other syntax highlighters: creating language definitions is easier, it has a plugin system to extend its internal functionality, and it comes with a GUI frontend as well. Also, some language definitions are only available for Highlight.

Is there any way to use Highlight from current AsciiDoctor? some hacks or custom settings?

**Comment by mojavelinux** [comment]
I'm very reluctant to add any more syntax highlighter integrations directly in core. These integrations are costly to maintain and we already have so many, a list that includes Pygments, CodeRay, highlight.js, prettify, and soon Rouge. The key advantage these integrations have over Highlight is that they do not require invoking a command line. I prefer to keep command line integrations out of core for reasons of security (one of the main reasons Asciidoctor came to exist).

Having said that, I have long wanted the source highlighter to be an extension point and I think we should proceed with that effort (see #2106). It's certainly possible to use a Treeprocessor to integrate an additional syntax highlighter like Highlight, but it's not as clean as receiving a callback.

The real benefit of the extension is that it hides the side-stepping of callout numbers, which have to be removed and later reinserted or else they confuse the syntax highlighter.

Here's how you could integrate Highlights using the existing extension mechanisms:

https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/highlight-treeprocessor.rb

(that covers everything except extracting and restoring callout numbers).

**Comment by tajmone** [comment]
Thanks @mojavelinux .Your proposal seem very good and I'm looking forward to it.

The linked treeprocessor script is of great help, and allows me to start off with it.

I remember from Highlight documentation that it's also possible to build it as a library (at least on Linux, for Windows I'm not sure). Maybe this would allow for a Ruby wrapper and circumvent the command line altogether.

**Comment by mojavelinux** [comment]
It's certainly possible using a Ruby C extension.

My statement about not using a command line interface is somewhat inaccurate. Pygments is called via an IPC channel using pygments.rb. The benefit, there, is that the library sits on both sides, validating what comes across the channel.

Still, I envision this integration to be published as separate gem, something like asciidoctor-highlight.

**Comment by mojavelinux** [comment]
Integrating additional highlighters will be made possible by #2106. These integrations can then be maintained as separate projects (just like asciidoctor-diagram, for example).
