### ISSUE TITLE
Allow linebreaks in attribute-list of macros

### ISSUE THREAD

**Issue by sboekhoff** [asciidoctor/asciidoctor#2100]
In order improve readability of AsciiDoc code it would be great if line breaks in attribute-lists of macros were allowed.

Instead of:
```asciidoc
image::sunset.jpg[caption="Figure 1: ", title="A mountain sunset", alt="Sunset", width="300", height="200", link="http://www.flickr.com/photos/javh/5448336655"]
```

I'd like to write:
```asciidoc
image::sunset.jpg[
  caption="Figure 1: ",
  title="A mountain sunset",
  alt="Sunset",
  width="300",
  height="200",
  link="http://www.flickr.com/photos/javh/5448336655"
]
```

**Comment by mojavelinux** [comment]
While I appreciate what you're going for here, this very much violates the line-oriented nature of the AsciiDoc / Asciidoctor processor. If we split block macros across lines, we all of a sudden have to do a lot of look aheads...only potentially to not find a match. That could really slow down the processor...and speed is a core feature of Asciidoctor.

Fortunately, with block macros, you can use any number of block attribute lines to break up your attribute declarations. I'd argue this is pretty close to what you want:

```
.A mountain sunset
[caption="Figure 1: "]
[link=http://www.flickr.com/photos/javh/5448336655]
image::sunset.jpg[Sunset,300,200]
```

(in fact, I did it in less lines ;))

I'd be happy to add that the user manual to help people understand what's possible.

**Comment by mojavelinux** [comment]
I updated the docs to show various ways to write this block image in a more concise way.

**Comment by sboekhoff** [comment]
Thanks.
