### ISSUE TITLE
Temporary text annotation

### ISSUE THREAD

**Issue by sirjorj** [asciidoctor/asciidoctor#2102]
This is more of a feature request, really.  I think it would be useful if there was some simple markup for making temporary meta notes (as in 'note to self - get the right figures for this'.  This would be useful for placeholder text and small notes to correct later.  A suggestion would be to make the text bold and red.
Example: I am working on a document and I have some questions about some of the items I am documenting.  I could use this new feature to make placeholders so in the next review it would be easy to see what I need to correct and replace it with the right information.
Maybe there already is something like this that I don't know about, or maybe it just wouldn't be that useful to others, but I think it could be handy.
Thoughts?

**Comment by rockyallen** [comment]
I don't think there is anything yet, but there is a macro in the extensions lab that might help - see #932 and #1031.

**Comment by sirjorj** [comment]
I found something that works.  I'm not sure what it is called, but putting a '#' on each side of a string highlights it in yellow.  This works fine for my needs.

**Comment by mojavelinux** [comment]
@sirjorj that's [marked text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark), precisely what it's intended for.

Also keep in mind that simple line comments serve this purpose as well. The line comments are only visible in the source code, but I find that is sufficient for communicating with the writer (it's nothing the reader needs to see).

Finally, there is an extension that will put line comments in the converted output as marked text. This mimics what AsciiDoc Python does. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/showcomments-preprocessor.rb.
