### ISSUE TITLE
Multi-line code block in a table cell

### ISSUE THREAD

**Issue by sirjorj** [asciidoctor/asciidoctor#2113]
Is this possible?  I've made several attempts with the various code block tokens ('`foo`', ' foo', ----, etc) and none have worked in a table cell.

**Comment by mojavelinux** [comment]
To use a block element in a table cell, you need to add the AsciiDoc style to the cell. See:

* http://asciidoctor.org/docs/user-manual/#cols-style
* http://asciidoctor.org/docs/user-manual/#pipe-in-table-cell

In other words:

```
|===
a|
----
listing block in table cell
----
|===
```

**Comment by sirjorj** [comment]
Thanks!  I did not know about column styles.  I ended up using Literal and it formats it exactly how I want it.
