### ISSUE TITLE
Counter doesn't work because of its name

### ISSUE THREAD

**Issue by Amigo-sa** [asciidoctor/asciidoctor#2123]
// define counter
{counter:tableRegime1:0}
// increment value
{counter:tableRegime1}
// use it's value
{tableRegime1}

Value is 0.

If we change counter name to shorter vesion
{counter:tr1:0}

everything works perfectly

**Comment by mojavelinux** [comment]
Attribute names must be lowercase.

**Comment by mojavelinux** [comment]
Does that solve your issue?

**Comment by Amigo-sa** [comment]
Thanks! It helped. Though this is quite an unusual behaviour

**Comment by mojavelinux** [comment]
Agreed. Thanks for following up, @ahus1!
