### ISSUE TITLE
Anchors cannot be set before list items

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor#2124]
I set an anchor for an item in a list and the anchor didn't work. After some experimentation, it appears the problem only occurs when the list item follows another list item that ends in a conditional statement that evaluates to false. If the previous list item does not end in a conditional or if that conditional evaluates to true then links to the anchor work. Placing an inline anchor within the list item works (but IMO it's ugly and harder to visually parse). Please see attached file for an example of the problem and a series of links to anchors that work, narrowing down the issue to the exact case I mention.
[anchorbug.adoc.txt](https://github.com/asciidoctor/asciidoctor/files/922086/anchorbug.adoc.txt)

**Comment by mojavelinux** [comment]
To add an anchor to a list item, you must use the inline anchor syntax. A block anchor only applies to a block (and serves as what we call a block divider).

Here's how you add anchors to itemized (ordered and unordered) list items:

```
* [[item-one]] list item one
* [[item-two]] list item two
```

Here's how you add anchors to description list items:

```
[[term-one]] term one :: description
[[term-two]] term two :: description
```

**Comment by mojavelinux** [comment]
> Placing an inline anchor within the list item works (but IMO it's ugly and harder to visually parse). 

But that's the correct way to do it. You can leave a space after the anchor to make it easier to read.

**Comment by janicecmt** [comment]
Then why does using a normal anchor on the previous line (as one would with all other markups/languages I've used) work in all other list item cases that I've seen? The case where it fails is a very extreme edge case. It should either work or not work - having it work 99% of the time in what most folks would consider the normal way based on industry standards then telling them that way is incorrect is very user unfriendly.

**Comment by mojavelinux** [comment]
I want to be clear that I'm not saying you are incorrect. I recognize that taking that position is very unfriendly. I've often been on the user's side of the table and I'm committed to standing in the user's shoes.

With that said, I'm only communicating how AsciiDoc is designed so you have an accurate picture. The block attributes can only be used above the start of a block. Naturally, since a list block starts with a list item, the anchor on the list block will match the position of the first item. That's just circumstantial.

Allowing block attributes to be applied to a list item would be a fundamental change in AsciiDoc. We could do it, but it's impact would need to be studied carefully. It's certainly something that could be considered for UniDoc.

I do have an intermediary solution that I think would work really well. Following similar logic used for section titles, if a list item begins with an anchor, we could treat that anchor to the ID of the list item node.

```
* [[item-one]] list item one
```

Which would produce:

```html
<div class="ulist">
<ul>
<li id="item-one">
<p>list item one</p>
</li>
</ul>
</div>
```

This would provide the functionality many are looking for to assign an ID to the list item node itself and not an anchor in the list item text.

**Comment by mojavelinux** [comment]
> Since a list block starts with a list item, the anchor on the list block will match the position of the first item. That's just circumstantial.

To clarify this point, I'll provide an example. Consider the following AsciiDoc:

```
[[list-1]]
* one
* two
* three
```

This produces the following HTML:

```html
<div id="list-1" class="ulist">
<ul>
<li>
<p>one</p>
</li>
<li>
<p>two</p>
</li>
<li>
<p>three</p>
</li>
</ul>
</div>
```

Notice that the ID is applied to the list block and not the first list item.

**Comment by mojavelinux** [comment]
Going back to my proposal, I'd also consider supporting the shorthand syntax to make it easier to visually parse:

```
* [#item-one] list item one
```

That appears pretty clean to me.

**Comment by janicecmt** [comment]
Okay.

I noticed that you changed the title of the issue - the old title was more accurate as anchors do work in most list items. I don't understand why putting the anchor on the line before a list item works in most cases - given your explanation I don't think it should work in any case. However, it does work on the line before a list item (not the first one in the list) except when there's a false conditional ending the previous list item (see the test file attached to the initial post). Had it failed in other cases I probably would have assumed it just didn't work and that would have been better than having it work in all cases except this weird edge case. Having it work in most cases meant that I internalized "this works" for that situation and thought of the edge case as a bug. The other way I might have grumbled a bit that this thing I expected to work didn't work then gone looking for the asciidoctor way of doing it. Perhaps your change outlined here will "fix" things so that the anchor the line before a list item doesn't work in any case.

In any case, thank you for being responsive. It makes a huge difference.

**Comment by mojavelinux** [comment]
What I'm trying to explain (perhaps not very well) is that an ID is never applied to a list item itself. It's always applied to the enclosing list. If you view the HTML source, you will see that this is the case.

You're correct that it's possible to put a block attribute line on a nested list or a list that follows a list continuation without causing the outer list to terminate. But those attributes, such as the ID, still get applied to the nested list itself, not the list item.

What we're really talking about here, and why I changed the title, is a way to assign an ID (and perhaps other attributes) directly to a list item. The only way that's possible right now using the current parsing rules is to place that attribute list directly after the list marker. We'd then need to add some special parsing rules for this case (like we do with checkboxes).

**Comment by mojavelinux** [comment]
I also want to point out that what you are showing is not an edge case. The list parser doesn't see the preprocessor conditionals. It only sees the content that they emit or don't emit. Once you resolve those, what you're looking at are the normal rules for where block attributes are allowed using nested lists and list continuations.

**Comment by mojavelinux** [comment]
What I really want to get to is the intent. Is the intent to be able to assign an ID to a single list item? If so, we can work on ideas to address that requirement.

**Comment by janicecmt** [comment]
Yes, ideally I'd like to be able to link to a specific list item.

**Comment by mojavelinux** [comment]
Great. Now we just need to play around with the syntax to see what's possible and what feels right. This is what I spend most of my days doing ;)

Does this feel okay to you?

```
* [#anchor1] list item text
* [#anchor2] list item text
```

**Comment by mojavelinux** [comment]
Another sort of out there idea is to be able to set the IDs at the start of the list. Something like:

```
[item-ids="anchor1,anchor2"]
* list item text
* list item text
```

But that can result in the anchor being very far away from the list item if the list items are long.

**Comment by janicecmt** [comment]
I must be missing something - what does that gain over what we have now for individual list items? Doesn't the following already put the anchor on the list item:

```
* [[anchor1]] list item text
* [[anchor2]] list item text
```

That said, assuming the above is not sufficient, I would prefer to have it with the list item. I have some long lists and (so far) I've only needed an anchor on one item somewhere in the middle of the list. Unless it was going to be automatic in some way I'd rather only have to supply an anchor for the items that need one. Relying on an order-dependent list seems like a bad idea; it's too easy to screw up and cause mismatches, especially if I only care about having an anchor on the 7th item of a 10 item list.

I can live with this syntax:

```
* [#anchor1] list item text
* [#anchor2] list item text
```
although I wonder if it would be more consistent to use two brackets as follows:

```
* [[#anchor1]] list item text
* [[#anchor2]] list item text
```

if that wouldn't be too difficult for the parser to distinguish.

**Comment by lschmelzeisen** [comment]
Was there ever any consensus reached on a syntax to apply anchor *directly* to list items (and not just insert an `<a>` tag at the start) and implemented?

I think using the following style is the most backward-compatible.

```
* [[anchor1]] list item text
* [[anchor2]] list item text
```

**Comment by mojavelinux** [comment]
@lschmelzeisen You are very close. I think this syntax would provide what we are looking for and be perfectly consistent with the line-oriented conventions in AsciiDoc.

```
* [[anchor1]]
list item text
* [[anchor2]]
list item text
```

In fact, we could open this up to be a full-fledged block attribute line...so it would support anchor, ID, role, and other arbitrary attributes. I think it's a real opportunity to fill a void in AsciiDoc.

**Comment by mojavelinux** [comment]
I'm closing this issue in favor of #2716, which more directly addresses this capability.

The ability to set an anchor on a list item will be partially solved by #2257, which is slated for 1.5.7. I say partially because even though it will register the anchor in the reference catalog, it will still output an inline anchor instead of assigning the id to the `<li>` element. Promoting the id to the `<li>` element can be addressed as part of #2716.

**Comment by mojavelinux** [comment]
> what does that gain over what we have now for individual list items? Doesn't the following already put the anchor on the list item...

Yes, but a leading anchor can only be used to associate an ID with a list item. It does not provide a way to assign other attributes, such as role, options, start value, etc.

**Comment by mojavelinux** [comment]
> Was there ever any consensus reached on a syntax to apply anchor directly to list items (and not just insert an <a> tag at the start) and implemented?

See #2716.

**Comment by 997293** [comment]
Another issues I guess may be relevant is that currently it seems like we cannot assign a title to an list item. Maybe by figuring out a way to assign an ID to a list item, we can also assign a title to it by a similar mechanism.
