### ISSUE TITLE
Add intrinsic attribute that dumps list of attributes as attribute entries

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2135]
Add an intrinsic attribute named `attributes` that dumps a list of attributes when referenced. The attributes should appear like attribute entries, one per line, and sorted by name:

Example input:

```
{attributes}
```

Example output:

```
:appendix-caption: Appendix
:asciidoctor:
:asciidoctor-version: 1.5.6.dev
:attribute-missing: skip
:attribute-undefined: drop-line
...
```

In secure mode, it should only be possible to dump the list once.

**Comment by mojavelinux** [comment]
This can be done using a custom inline macro.

**Comment by everflux** [comment]
Any update on this? (Would make debugging a complex middleman-asciidoctor setup much easier in my case)

**Comment by mojavelinux** [comment]
You can find this extension in the extensions lab.

https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/dump-attributes-block-macro.rb

I'm not going to pursue this in core since this is better handled as an extension and allows more experimentation.
