### ISSUE TITLE
Allow usage of sectanchors together with sectlinks

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#2138]
IMHO it would be nice to allow sectanchors and setlinks to work together. Currently you can also use either sectanchors or setlinks.

**Comment by mojavelinux** [comment]
Actually, it looks like this was already fixed in 1.5.5 as #1806 indicates. Can you verify which version of Asciidoctor you are using and that you are using the following attributes?

```
:sectanchors:
:sectlinks:
```

**Comment by mojavelinux** [comment]
I'm confident this is resolved. Please open if you believe otherwise.

**Comment by vogella** [comment]
I can confirm it is @mojavelinux 

We had an issue in our build configuration but the standard works fine (our issue is now also resolved).

**Comment by mojavelinux** [comment]
:raised_hands: :muscle:
