### ISSUE TITLE
Support target and role attributes for links

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#214]
Although AsciiDoc doesn't support it, it's often a requirement to set the target attribute for a link (i.e., `<a href="..." target="_blank">`). Adding support for this is just a matter of parsing the attributes in a link macro and then using the target attribute in the template.

ex.

```
http://google.com[Google, window="_blank"]
```

We might want to support a shorthand way of doing links that target _blank, such as:

```
http://google.com[Google^]
```

**Comment by gernotstarke** [comment]
fyi: the quick ref has moved:

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

**Comment by mojavelinux** [comment]
I didn't realize that old URL was still being referenced. I set up a redirect to help visitors find the new location.
