### ISSUE TITLE
Automatically generated author initials don’t support multi-word names

### ISSUE THREAD

**Issue by huftis** [asciidoctor/asciidoctor#2143]
When *part* of an author’s name consists of multiple words, only the first word is used when constructing the `authorinitials` element in DocBook.

For example, my name is Karl Ove Hufthammer (two first names, no middle name and one last name), which I write as `Karl_Ove Hufthammer`. My initials should be `KOH`, but the generated `authorinitials` comes out as `KH`.

Ħere’s a more complete test example. The name entered as `Anne_Betty Cox_Davis Everett_Fowler_Grey` should have the initials `ABCDEFG`. However, the `authorinitials` value generated is `ACE` (in the current Git version of asciidoctor).

**Comment by mojavelinux** [comment]
The auto-generated initials are just a convenient default. You can override them using:

```
= Document Title
Karl_Ove Hufthammer
:authorinitials: KOH
```

We are also discussing a possible syntax for adding author initials in the implicit author line. See #2942. Let's continue the discussion there.
