### ISSUE TITLE
HTML entities ending with numbers are not displayed correctly

### ISSUE THREAD

**Issue by sboekhoff** [asciidoctor/asciidoctor#2144]
Whey I add an HTML-entity (e.g. `&thetasym;`) to my AsciiDoc code, the corresponding symbol is shown in the output (here `ϑ`).

When adding `&frac34;` I'd expect `¾` - the actual result is `&frac34;`

This applies to all entities ending with numbers:

* `&sup2;`
* `&sup3;`
* `&sup1;`
* `&frac14;`
* `&frac12;`
* `&frac34;`
* `&there4;`

**Comment by mojavelinux** [comment]
I never realized that a named entity could end in a number. Sure enough, it's true!

This is just a matter of updating the match expression to allow for trailing digits.

**Comment by mojavelinux** [comment]
Thanks for catching and reporting this!
