### ISSUE TITLE
Unexpected results with mis-matched table boundaries

### ISSUE THREAD

**Issue by dewachterken** [asciidoctor/asciidoctor#2147]
When rendering tables in an unordered list, I get the error message 'line [line number]: table missing leading separator, recovering automatically
The line number is always the line that contains the closing characters (|=====)

Below is a sample.

- The first table is fine.
- The second and third table bot give the error message with the line number of the closing characters.
- Rendering is perfect though.

```
[cols=",",width="100%"]
|============================================================
|JAVA_HOME|/java/sdk-1.8.0
|ANT_HOME|}/ant/apache-ant-1.9.x/
|PATH|$JAVA_HOME/bin:$ANT_HOME/bin:$PATH
|============================================================

Depending on the components, you have to provide additional options:

* CBK
+
[cols=",",width="100%"]
|============================================================
CATALINA_OPTS|-Xms512m -Xmx1024m -Dosgi.bundlefile.limit=0 -Dsun.locale.formatasdefault=true -Djava.net.preferIPv4Stack=true -Dcbkv3.ui.configFolder={cbk_home}/_CBK/CBK.Conf
|============================================================

* LGS
+
[cols=",",width="100%"]
|============================================================
CATALINA_OPTS|-Xms128m -Xmx256m -Dsun.locale.formatasdefault=true -Djava.net.preferIPv4Stack=true -Djava.library.path={cbk_home}/openoffice4/program/bin
|============================================================
```

Does anyone see what the problem could be?

**Comment by mojavelinux** [comment]
The message is actually communicating exactly what is going on. You first cell in the second and third tables are missing the leading cell separator.

```
|===
CATALINA_OPTS|-Xms128m -Xmx256m -Dsun.locale.formatasdefault=true -Djava.net.preferIPv4Stack=true -Djava.library.path={cbk_home}/openoffice4/program/bin
|===
```

It should be:

```
|===
|CATALINA_OPTS|-Xms128m -Xmx256m -Dsun.locale.formatasdefault=true -Djava.net.preferIPv4Stack=true -Djava.library.path={cbk_home}/openoffice4/program/bin
|===
```

Asciidoctor is detecting this situation and recovering automatically by adding the missing character. So it's behaving as expected.

**Comment by mojavelinux** [comment]
Btw, you should not set cols to `","`. You should use `"2*"` for two even columns. If you need automatic column widths, then set the `autowidth` option.

**Comment by dewachterken** [comment]
Thanks! I missed that. The message referred to the last line of the table, so I looked at that a million time, and forgot to read the whole table... 

Thanks a lot for the superfast feedback!

**Comment by mojavelinux** [comment]
Glad to help!

The line numbers for tables aren't perfect yet. Still a work in progress.
