### ISSUE TITLE
Hard line break regex matches differently between Node and browser

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2150]
The following regex that matches a hard line break matches different results between Node and browsers:

```ruby
LineBreakRx = /^(.*) \+$/m
```

`[^\n]` should be used instead of `.`.

The difference is in what is captured. With the built-in html5 converter, the output happens to be the same.

**Comment by mojavelinux** [comment]
I honestly can't figure out what I was talking about. This expression does exactly what we want it to do. It matches the text on the line that ends with `+` preceded by a space.

**Comment by Mogztter** [comment]
Did you create this issue after drinking a :beer:  ? :rofl:

**Comment by mojavelinux** [comment]
hahahaha!

I think what happened was that I was changing the code and testing on Asciidoctor.js and some iteration of the code caused it to break. I made a note of it, then by chance fixed the code, but didn't realize it was just temporary. I guess ;)

It's really strange how ^ and $ match differently in JavaScript depending on the regexp flag. It's easy to get bitten by that.

**Comment by mojavelinux** [comment]
Aha! It was because of https://github.com/opal/opal/issues/1596. When the Asciidoctor.js build switched to Opal 0.11.x, this automatically started working. So the issue was really in Opal.

**Comment by mojavelinux** [comment]
(The problem was the "m" flag was being dropped in the old regexp).
