### ISSUE TITLE
Nested tables grids.

### ISSUE THREAD

**Issue by github-login** [asciidoctor/asciidoctor#2151]
Asciidoctor 1.5.5 
Runtime Environment (ruby 2.4.0p0 (2016-12-24 revision 57164))

When nesting tables the nested table grids get messed up. Here are the different combinations:

<table>
	<tr>
		<th rowspan="2">Master</th>
		<th colspan="2">Sub-table</th>
	</tr>
	<tr>
		<th>Set</th>
		<th>Result</th>
	</tr>
	<tr>
		<td rowspan="4">none</td>
		<td>none</td>
		<td>none</td>
	</tr>
	<tr>
		<td>cols</td>
		<td>cols</td>
	</tr>
	<tr>
		<td>rows</td>
		<td>rows</td>
	</tr>
	<tr>
		<td>all</td>
		<td>all</td>
	</tr>
	<tr>
		<td rowspan="4">cols</td>
		<td><b>none</b></td>
		<td><b>cols</b></td>
	</tr>
	<tr>
		<td>cols</td>
		<td>cols</td>
	</tr>
	<tr>
		<td>rows</td>
		<td>rows</td>
	</tr>
	<tr>
		<td><b>all</b></td>
		<td><b>cols</b></td>
	</tr>
	<tr>
		<td rowspan="4">rows</td>
		<td><b>none</b></td>
		<td><b>rows</b></td>
	</tr>
	<tr>
		<td><b>cols</b></td>
		<td><b>rows</b></td>
	</tr>
	<tr>
		<td>rows</td>
		<td>rows</td>
	</tr>
	<tr>
		<td><b>all</b></td>
		<td><b>rows</b></td>
	</tr>
	<tr>
		<td rowspan="4">all</td>
		<td>none</td>
		<td><b>all</b></td>
	</tr>
	<tr>
		<td>cols</td>
		<td>cols</td>
	</tr>
	<tr>
		<td>rows</td>
		<td>rows</td>
	</tr>
	<tr>
		<td>all</td>
		<td>all</td>
	</tr>
</table>

**Comment by mojavelinux** [comment]
Can you please share the AsciiDoc source and a little bit more explanation of what I'm supposed to be observing?

**Comment by github-login** [comment]
```

Table !
[cols="d,a",options="header", grid="all"]
|===
| Name
| Additional Information

| Flags
|

Table 2
[cols="d,d",options="header", grid="none"]
!===
! Bit
! Name

! 1
! Entry valid

! 2
! Date valid

!===
|===
```


Table 2 (grid="none") should have no grids but have all of them.. 

# Example 2 
Set Table 1 grid="rows" , doesn't matter what grid is set Table 2 it always get overwritten to "rows".

**Comment by mojavelinux** [comment]
Aha, I see the problem. I had assumed there was no reason to set styles for the grid-none class since that's how tables start. But when tables are nested, that style is needed to reverse the inherited setting. Therefore, I'll add styles for the "none" case.

**Comment by mojavelinux** [comment]
Please test the combinations with the stylesheet attached to PR #2167.

I changed the CSS rules so that they don't get inherited by nested tables. That should prevent the interference we're observing today.

**Comment by mojavelinux** [comment]
(I managed to keep the CSS just as concise as well, which is a bonus).

**Comment by mojavelinux** [comment]
Here's an extremely crude script I threw together to generate tables with all the grid combinations (and optionally frame combinations). 

```ruby
#FRAMES = %w(all topbot sides none)
FRAMES = %w(all)
GRIDS = %w(all rows cols none)

tables = []

FRAMES.each do |oframe|
  GRIDS.each do |ogrid|
    FRAMES.each do |iframe|
      GRIDS.each do |igrid|
        #tables << %(== Outer[frame=#{oframe},grid=#{ogrid}] / Inner[frame=#{iframe},grid=#{igrid}]
        tables << %(== Outer[grid=#{ogrid}] / Inner[grid=#{igrid}]

[cols="1,1a",frame=#{oframe},grid=#{ogrid}]
|===
| Name | Information

| Flags
|
:table-caption!:

[%footer,cols="1,1",frame=#{iframe},grid=#{igrid}]
!===
! Bit ! Name

! 1
! Entry valid

! 2
! Date valid

! Bit
! Name
!===
|===)
      end
    end
  end
end

puts ':toc:'
puts ':table-caption!:'
puts
puts tables * "\n\n"
```

I definitely see the need for an automated testing script that would verify that the browser is putting the borders in the right places...because these are a lot of combinations to test.
