### ISSUE TITLE
footnote numbers aren't increment correctly when placed in section headers

### ISSUE THREAD

**Issue by asknet** [asciidoctor/asciidoctor#2152]
In the following example the footnotes should be numbered 1 & 2 in html5 output. Instead it shows 1 & 1 only.

```
= Level 1 footnote:[first footnote]
some text

== Level 2 footnote:[second footnote]
more text

```

**Comment by mojavelinux** [comment]
This issue was duplicated in #2903. Let's continue the discussion there.
