### ISSUE TITLE
compat-mode has to be specified over and over again in a doc with table cells

### ISSUE THREAD

**Issue by karlito-go** [asciidoctor/asciidoctor#2153]
If a table cell uses a| syntax, required for things like labeled lists, it defaults to non-compat even if the main document uses compat-mode or has an asciidoc title syntax (underlined).   This happens both with github and the browser plugin.

**Comment by mojavelinux** [comment]
Uh oh. It looks like a broke this behavior at some point and we're missing a specific test for it. Thanks for catching! A test will save us ;)

**Comment by mojavelinux** [comment]
Btw, I'm certain that compat mode is enabled if the cell starts with a two-line document title:

```
= Document Title
:compat-mode:

|===
a|
Table Cell
==========

The word 'italic' in this sentence should be emphasized.
|===
```

The problem is when you take away that two-line document title, then the setting is reverted.

Either way a test will prove it and check for it.

**Comment by mojavelinux** [comment]
Oddly, it works if you add a blank line at the start of the cell.

```
= Document Title
:compat-mode:

|===
a|

The word 'italic' in this sentence should be emphasized.
|===
```

So something strange is going on.

**Comment by mojavelinux** [comment]
I also noticed that the preprocessor conditional can't be used to check the compat-mode attribute. It always reports the value from the outer document. This might be unavoidable, but I've mentioned it here just in case it can be addressed.

```
= Document Title
:compat-mode:

|===
a|
:compat-mode!:

ifdef::compat-mode[compat-mode is on]

'italic'

{compat-mode}
|===
```

It reports 'compat-mode is on", but the attribute doesn't resolve (indicating that the attribute has been successfully removed).
