### ISSUE TITLE
Admonitions do not work inside of tables

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor#2169]
The documentation for tables shows asciidoc markup working inside table cells. However, when I try to add a note to a table cell, it treats the admonition label like normal text and does not use any formatting on it.

For example, including the following in an asciidoctor file:

```
.Title
[cols="3,1,6",options="header"]
|===
| Heading 1
| Heading 2
| Heading 3

| 1,1
| 1,2
| 1,3

| 2,1
| 2,2
| 2,3

Note: Foo

| 3,1
| 3,2
| 3,3
|===
```

Results in the output in the screenshot.
<img width="724" alt="admonitionsintables" src="https://cloud.githubusercontent.com/assets/24766266/25580227/336c4ebc-2e4d-11e7-87a0-d2ea6b6d9e30.png">

**Comment by Mogztter** [comment]
Could you try to change Note to uppercase and add the letter "a" after the third column size (ie. 6) ?

**Comment by Mogztter** [comment]
The letter "a" is a column style to render AsciiDoc content contains in the column and admonition must be in uppercase.

http://asciidoctor.org/docs/user-manual/#admonition

http://asciidoctor.org/docs/user-manual/#cols-format (styles section)

**Comment by janicecmt** [comment]
Thanks! The Note instead of NOTE was a typo and I just didn't notice. Sometimes it really does need a fresh set of eyes.

I was looking at the table documentation from a different file while trying to do this and missed the importance of the a - I guess this is one of the drawbacks of having several different places where documentation lives.

**Comment by Mogztter** [comment]
You're welcome :wink:
If you think we can improve the documentation on table, feel free to open an issue with your ideas: https://github.com/asciidoctor/asciidoctor.org

**Comment by stoobie** [comment]
> Could you try to change Note to uppercase and add the letter "a" after the third column size (ie. 6) ?
@Mogztter 
Do you mean this:
`[cols="3,1,6a",options="header"]`

@janicecmt 

Alternatively, I successfully added a note to a table cell with the following:
```
a|Some table cell content:
[NOTE]
====
Some note.
====
```

And this worked for a table cell spanning two columns:
```
2+a|Some table cell content:
[NOTE]
====
Some note.
====
```
