### ISSUE TITLE
Table example missing View Result option

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor#2170]
The table example titled "Table with three columns, a header, and two rows of content" in the Syntax Guide is missing a view result link.

I took a look at the guide source to see if this was something I could quickly add then submit as a PR but I couldn't figure out how to do it (sorry!)

**Comment by janicecmt** [comment]
Filed again as https://github.com/asciidoctor/asciidoctor.org/issues/664

**Comment by mojavelinux** [comment]
Thanks for routing it to the correct place!
