### ISSUE TITLE
Description list style missing in Chinese

### ISSUE THREAD

**Issue by mushanshitiancai** [asciidoctor/asciidoctor#2185]
Description list missing the bold style in Chinese：

```
test:: a test
测试:: 测试
```

pdf output:

![image](https://cloud.githubusercontent.com/assets/4251771/25842887/1d6c5102-34d8-11e7-8ba6-7f48251fcfc5.png)

**Comment by mojavelinux** [comment]
This is a font support issue. Are you using the cjk theme? https://github.com/asciidoctor/asciidoctor-pdf#support-for-non-latin-languages

**Comment by mojavelinux** [comment]
This issue is also about Asciidoctor PDF, not core.

**Comment by mojavelinux** [comment]
Please reopen in Asciidoctor PDF if the referenced documentation does not lead you to a solution.
