### ISSUE TITLE
HTML Footer: the characters in wrong encoding

### ISSUE THREAD

**Issue by lit-uriy** [asciidoctor/asciidoctor#2198]
When creating an HTML document, in the footer part of the text in the wrong coding:
![screenshot_24](https://cloud.githubusercontent.com/assets/6910067/26042589/25e99458-3950-11e7-9f10-3dee8899ab21.png)
Apparently the text in brackets should be "зима", ("winter") i.e. winter time. May be this text is encoded in IBM-866.

OS: Windows 7
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:IBM866)

**Comment by mojavelinux** [comment]
I cannot stress enough how important it is to use UTF-8 encoding. For some bizarre reason, Windows likes to live in the past and use outdated encodings for the system default. (Linux and OSX switched to UTF-8 a long time ago). Not using UTF-8 (or some UTF variant) just makes life unpleasant. I explain how to switch encoding here:

https://github.com/asciidoctor/asciidoctor#requirements

**Comment by mojavelinux** [comment]
We can have different languages, but to exchange data in a multi-language world, we have to agree on encodings. Asciidoctor assumes you are using UTF-8.

**Comment by lit-uriy** [comment]
All the source is written in UTF-8. The resulting HTML is also UTF-8.

Given my example of the footer of the HTML document is generated by **asciidoctor**, not me. And only part of the text of footer asciidoctor inserts (or takes) in an encoding other than UTF-8.

**Comment by lit-uriy** [comment]
If I execute the command
`chcp 65001`
in the console, and then run **asciidoctor**, I get a basement:
![screenshot_27](https://cloud.githubusercontent.com/assets/6910067/26056596/7c07ee5e-398f-11e7-8c35-0b725f2e489d.png)

**Comment by lit-uriy** [comment]
To transform чшьр -> зима , I used an online decoder ( https://www.artlebedev.ru/tools/decoder/advanced/ ), it tells me that the encoding transformation looks like this:
CP866 -> CP1251

**Comment by mojavelinux** [comment]
In this case, the problem is not with the document, but rather with the Ruby settings (which tend to inherit from the system settings). In your environment, Ruby is creating non-UTF-8 characters in the datetime, which it then passes to Asciidoctor which puts them into the document.

When you run `asciidoctor -v`, you should see:

```
(lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

Otherwise, you won't be able to rely on the last updated time. I suppose you could just disable it using `nofooter` or pass in an explicit datetime when you run the command using the `docdatetime` attribute.

**Comment by lit-uriy** [comment]
```
>asciidoctor -v
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:IBM866

>chcp 65001
Active code page: 65001

>asciidoctor -v
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16) [x64-mingw32]) (lc:UTF-8 fs:Windows-1251 in:- ex:UTF-8)
```
:(

thanks for the "nofooter" and answers
