### ISSUE TITLE
Add warning or error message for un/incorrectly terminated tag region

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/asciidoctor#2210]
When adding a tag region to a file and incorrectly closing the tag I have different effects.

AsciiDoctor-preview in Atom shows "Unresolved directive" and correctly doesn't to anything. Running asciidoctor 1.5.5 directly against the testfile produces HTML output that does include the full content of the second file and the `end::[]` tag. 

Using this in asciibinder I get HTML output that includes the opening tag `tag::test[]` in the output file but no included content.

Asciidoctor doesn't warn about incorrectly or unterminated tags even with the --trace option.

[Archive.zip](https://github.com/asciidoctor/asciidoctor/files/1022355/Archive.zip)

**Comment by mojavelinux** [comment]
The processor now warns when a tag in an include file is not closed. See #2361.
