### ISSUE TITLE
Add support for multiple authors in header

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#223]
AsciiDoc only supports a single author in the header. To include multiple authors, the AsciiDoc user guide recommends using a docinfo.xml file. However, this file is only incorporated into DocBook output, not HTML.

I think it's reasonable to support multiple authors directly in the AsciiDoc header. I propose supporting multiple author entries separated by a delimiter, such as a comma or a semi-colon. I think semi-colon is the best choice since a comma may appear in a name as an honorarium.

For example:

```
= Document Title
Doc Writer <doc.writer@asciidoc.org>; John Smith <john.smith@asciidoc.org>
```

These would then be mapped to indexed attribute names.

```
authorcount = 2
author = Doc Writer
authors = Doc Writer, John Doe
firstname = Doc
lastname = Writer
email = doc.writer@asciidoc.org
authorinitials = DW
firstname_1 = Doc
lastname_1 = Writer
email_1 = doc.writer@asciidoc.org
authorinitials_1 = DW
firstname_2 = John
lastname_2 = Smith
email_2 = john.smith@asciidoc.org
authorinitials_2 = JS
```

This would be a departure from compliance w/ AsciiDoc as it would require a core change since the regex is hardcoded. However, from what I've seen, people feel strongly that multiple authors should be supported.

On the other hand, it's possible to set all these variables explicitly in the AsciiDoc header and then the document would still be compliant.

**Comment by jnavila** [comment]
This does not seem to work for epub and mobi
