### ISSUE TITLE
Bug in table generation for manpage format when using caption

### ISSUE THREAD

**Issue by prudhomm** [asciidoctor/asciidoctor#2253]
table generation is broken in manpage generation, it generates some garbage text  when caption are  used. Html generation works perfectly fine
Here is an example:
https://github.com/feelpp/feelpp/blob/develop/applications/mesh/partitioner.adoc#options-1

attached a screenshot of the result of man
<img width="596" alt="screenshot 2017-06-13 05 10 02" src="https://user-images.githubusercontent.com/151693/27064228-9a187738-4ff6-11e7-9c17-1d2bf52236f6.png">

if the caption is removed `.Table ...`, then it is all right, see screenshot
<img width="611" alt="screenshot 2017-06-13 05 11 35" src="https://user-images.githubusercontent.com/151693/27064275-d69acc42-4ff6-11e7-93ee-72a2aed770ab.png">

All our manpages tables are broken the same way as soon as we use captions

**Comment by mojavelinux** [comment]
Thanks for reporting. It looks like the troff codes aren't being outputted correctly in that case. The manpage converter is definitely still a work in progress, so I appreciate you contributing the test case. I'll try to get this fixed before the release.

**Comment by prudhomm** [comment]
@mojavelinux how do you me to help exactly ? should I put the testcase here ? or propose some PR?

**Comment by mojavelinux** [comment]
I'm already a step ahead of you. I submitted a PR, in which I used your example as a test case.

Feel free to test the code in the PR. However, it turned out just to be a missing newline character. See https://github.com/asciidoctor/asciidoctor/pull/2288
