### ISSUE TITLE
Infinitely (or at least more than 5) nested lists

### ISSUE THREAD

**Issue by bobmcwhirter** [asciidoctor/asciidoctor#2255]
re-processing some government documents, I'm finding 6 or 7 levels of nesting of ordered lists.

Beyond five, though, and my `......` just emits verbatim, and not as yet-another-level of ordered list, at least with the HTML generator.

The docs:

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

do indicate that 5 is the max level of nesting.  It seems arbitrary.  Can we do better?  7? 11? 13? Or some other larger-than-5 number of levels?

fwiw, my context is gitbook, thus the javascript flavor of AsciiDoctor.

**Comment by mojavelinux** [comment]
This will be available starting in 1.5.8. See #2854. It took me a while to come around on this, but I ran into enough use cases that it finally made sense...and it turned out to be simpler to parse anyway.

**Comment by mojavelinux** [comment]
(It will take some time for the docs to catch up).
