### ISSUE TITLE
Source doesn't render in table columns (HTML5 backend)

### ISSUE THREAD

**Issue by jaikiran** [asciidoctor/asciidoctor#2259]
I seem to be running into some issue with rendering source code in table columns, via asciidoc. I have been following examples, which suggest this should work fine, but the source tags are rendered literally when run with asciidoctor with HTML5 backend. Here's an gist which shows the problem https://gist.github.com/jaikiran/229010317b7414d0ba0a8b2b7547e69c (I vaguely recollect github uses Asciidoctor to render, so looking at that rendered gist, it seems to reproduce the issue).

Am I doing something wrong in the asciidoc markup? Locally, I'm on 1.5.4 of asciidoctor (Ant task).

**Comment by mojavelinux** [comment]
You need to set the AsciiDoc table style (a) on the cell or column. For example:

```
[cols="1,1a"]
|====
| Column1 | Column2

|  Hello
|
[source]
----
public class Foo {
  public static void main(final String[] args) {
  }
}
----
|===
```

or

```
|====
| Column1 | Column2

|  Hello
a|
[source]
----
public class Foo {
  public static void main(final String[] args) {
  }
}
----
|===
```

**Comment by mojavelinux** [comment]
The AsciiDoc table style is required when the table cell contains *block* content. It effectively treats it as an embedded document.

Normal prose (aka paragraph) substitutions are always applied to table cells.

**Comment by jaikiran** [comment]
@mojavelinux, Thank you for explaining that. I hadn't known of the `a` style columns before. Now that you mentioned it, I went back and checked the docs http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables and it does mention using `a` to indicate Asciidoc content in columns. I'll give it a quick try locally and verify this.

**Comment by jaikiran** [comment]
The suggested syntax, worked fine. Thanks @mojavelinux  for the help. Closing this issue, since it clearly isn't a bug.

**Comment by mojavelinux** [comment]
Glad to help!
