### ISSUE TITLE
How to reset the position of list content？

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2281]
I have  a document as follows:

```
. list First line 1
.. list Second Line 1
.. list Second Line 2
+
list First content
. list First line 2
```

then the document is dealed as following

```
1. list First line 1
__a. list Second Line 1
__b. list Second Line 2
____ list First content   // Be careful. 4 space
2. list First line 2
```

I want to be as following:

```
1. list First line 1
__a. list Second Line 1
__b. list Second Line 2
__ list content   // Be careful. 2 space
2. list First line 2
```

How to write the document ? Thanks a lot.

**Comment by mojavelinux** [comment]
This is probably one of the least known and trickiest parts of the AsciiDoc syntax. As you know, you attach a block element (delimited block or paragraph) to a list item using a plus line:

```
. list item
+
paragraph attached to list item
```

If you want to attach that element to the parent of the list item, then you need to proceed the plus line with a blank line:

```
. parent list item
.. child list item

+
paragraph attached to parent list item
```

Each blank line above the list continuation moves up one level.

Here's an example of a paragraph attached to a grandparent list item:

```
. grandparent list item
.. parent list item
... child list item


+
paragraph attached to grandparent list item
```

I've always felt like we need to have a more robust syntax for this. Perhaps we can consider a special block attribute that would specify how many levels to skip back.

**Comment by mojavelinux** [comment]
This is now documented (along with a few other tips).

http://asciidoctor.org/docs/user-manual/#attaching-to-an-ancestor-list
