### ISSUE TITLE
Allow to specify alternative links for cross references

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#2313]
We frequently "configure" our Asciidotor document with includes.

The issue we face is that crosslinks <<thisisacrosslink>> do not always find the correct reference and we have to rework the documents due to that.

Is would be very helpful for us, if we could define alternative URL if a crosslink cannot be found.

<<thisisacrosslink|http://lalalu[Optional Text for Link>>

With the new asciidoctor enhancements, I think that would be possible to implement. 

@fap- please have a look, if you could provide a patch.

**Comment by mojavelinux** [comment]
Could you be more specific about why the correct reference is not found?

You might be able to achieve what you want to do in 1.5.7 now that the xref macro supports attributes (see #2381).

```
xref:thisisacrosslink[Optional Text for Link,fallback=https://example.com]
```

You can access the value of the fallback attribute in a custom converter.

Of course, nothing is stopping you from interpreting the refid in your own way (like Antora does). But if you want to use the implicit xref syntax, you have to adhere to its rules.

```
<<thisisacrosslink|http://lalalu,Optional Text for Link>>
```

**Comment by mojavelinux** [comment]
You'll either need to use conditionals or an extension (e.g., custom inline macro). A fallback reference is not something that we plan to support in the AsciiDoc language as it's too specific of a need.
