### ISSUE TITLE
Extension registration and unregistration seems to not work with strings

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#2324]
I am currently playing with the extension registration and unregistration from AsciidoctorJ.
It looks like the API is not symmetric at the moment:

It happily accepts a String as the name for an extension group:
https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb#L1424-L1428

On the other hand, when unregistering an extension group by name, the argument is automatically converted to a Symbol:
https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb#L1445

I just wanted to ask if this is intended or if these 2 places could be aligned to convert strings to symbols in both places.

**Comment by mojavelinux** [comment]
That does appear to be an inconsistency. I'm not sure why we are forcing the name to a symbol when unregistering.

I could always coerce the group names to a Symbol internally in both cases. That would shield us from having to worry about the type. I could also coerce to a String. But either way, it should go in the same direction.

I'll fix this for 1.5.6.1.

**Comment by mojavelinux** [comment]
See if that does the trick.
