### ISSUE TITLE
Problem with table in Admonition Block

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/asciidoctor#2326]
In admonition Block, the table's header is not rendered correctly.
(I used version 1.5.6 ; I've not tested with another version)

**my adoc**
```
= Test table in Admonition block
:commonResourcesDir: ../../../resources
include::{commonResourcesDir}/variables/commonVariables.adoc[]

====
*In exemple block*, the header background is rendered

[width="80%",cols="25%,25%,25%,25%", options="header"]
|===
|Col1|Col2|Col3|Col4

|a|b|c|d
|e|f|g|h
|i|j|k|l
|===
====

[TIP]
====
*But in admonition block*, the header background is not rendered

[width="80%",cols="25%,25%,25%,25%", options="header"]
|===
|Col1|Col2|Col3|Col4

|a|b|c|d
|e|f|g|h
|i|j|k|l
|===
====
```

**And the result**
![tableinab](https://user-images.githubusercontent.com/20417124/28428131-a3ca145e-6d78-11e7-9f73-e6baf6b1b284.png)

Jérôme

**Comment by mojavelinux** [comment]
It seems to me like you just need a stronger CSS rule. Very likely the built-in CSS rule for a table inside of another block is winning out. Given that the text is still white, that leads me to believe it is still a table head row.

**Comment by mojavelinux** [comment]
This does the trick:

```css
table.tableblock > thead th {
  color: white;
  background-color: red;
}
```

**Comment by mojavelinux** [comment]
The default stylesheet applies a background color to the `th`, which overrides any value set on `tr`.

**Comment by JBR69** [comment]
Thank you very much. 
It works perfectly.

**Comment by mojavelinux** [comment]
:+1:
