### ISSUE TITLE
Nested open blocks

### ISSUE THREAD

**Issue by tribut** [asciidoctor/asciidoctor#2340]
Is there a way to nest open blocks and if so, what is the syntax?

I was hoping for something like

~~~
[quote]
--
foo

[.underline]
---
bar
---

--
~~~

But apparently it does not work (like that?).

My use-case would be asciidoctor-latex generated documents with numbered equations inside definitions.

**Comment by mojavelinux** [comment]
Not yet. That's this issue: #1121. It's planned for 1.5.7.

I'm going to mark this as a duplicate and link it.

The workaround I've been using up to this point is nested example blocks (usually as an extension block). Not the same, but it has fit the bill in a pinch.
