### ISSUE TITLE
How to throw an error when file is not found

### ISSUE THREAD

**Issue by nakulcg** [asciidoctor/asciidoctor#2346]
First of all thanks for the nice piece of software. I am using asciidoctor-maven-plugin and whenever it throws 
`warn %(asciidoctor: WARNING: #{line_info}: include file not found: #{inc_path})` I get warnings in my CI. But I would actually want the CI build to fail. Can this be achieved? If yes how

**Comment by mojavelinux** [comment]
The way to handle this right now is to implement a custom IncludeProcessor extension, which allows you to handle the include directive in your own code and fail as needed.

Here's an example of an include processor: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/uri-include-processor/extension.rb

At the moment, when you implement a custom include processor, you lose the partial include functionality (by line number or tag). That's something we definitely want to correct. If you need that functionality, in the meantime, you can just reuse the code from core.

**Comment by mojavelinux** [comment]
This is also related to, and possibly covered by, #2003 and #44.

**Comment by mojavelinux** [comment]
When #2003 is resolved, the command will return an exit code of 1 if the specified failure level is reached. Since I believe that covers the case you are asking about, I'm going to mark this one as a duplicate.
