### ISSUE TITLE
Update footnote macro to accept a target

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2347]
Currently, the `footnoteref:[<target>,<text>]` macro is used to declare or refer to a referencable footnote. This dedicated macro is a departure from the standard macro pattern in AsciiDoc since the target is moved to the first positional attribute. The previously unused target of the `footnote` macro should be used instead for this purpose.

Instead of this syntax:

```
A paragraph.footnoteref:[fn1,Footnote]

Another paragraph.footnoteref:[fn1]
```

the following syntax should be both recognized and preferred:

```
A paragraph.footnote:fn1[Footnote]

Another paragraph.footnote:fn1[]
```

This form is consistent with the `name:<target>[<attrlist>]` pattern.

**Comment by mojavelinux** [comment]
One open question is whether we should allow the footnote macro to be used as a footnote xref. As it's currently implemented, either macro is allowed:

```
footnote:keyword[]

footnoteref:keyword[]
```

**Comment by graphitefriction** [comment]
Let me just see if I've got this straight:

```
First they ignore you. Then they laugh at you. Then they attack you. 
Then you win.footnote:g1[Many people attribute this quote to Gandhi, but he didn't say this.]

Be the change you wish to see in the world.footnote:g1[]
```

or

```
 ... you win.footnoteref:g1[Many people attribute this quote to Gandhi, but he didn't say this.]

... world.footnoteref:g1[]
```

Both ways are valid, yes?
If yes, then what do you mean by a "footnote xref"? How would that be different from `world.footnote:g1[]` and `world.footnoteref:g1[]`?

And on a `compat-mode` note, will the deprecated syntax be available in compat mode or not (so I know how to enter it into the upgrade table).

**Comment by elextr** [comment]
> One open question is whether we should allow the footnote macro to be used as a footnote xref. 

I suspect that Asciidoc Python used separate macros for footer and reference because Docbook has separate `footer` and `footnoteref` elements and it was easier to translate with separate macros.

Better implementations would not need this.  Perhaps `footnoteref` could be deprecated in Asciidoctor 2.0 and just the `footnote` encouraged.

**Comment by graphitefriction** [comment]
:+1: For deprecating `footnoteref` in 2.0.

**Comment by mojavelinux** [comment]
To clarify, what I figured out is that it's possible to enhance the `footnote` macro to cover all existing uses of footnote and footnoteref without breaking any existing syntax. Not only does this consolidate two macros into one, it also makes the footnote macro consistent with the standard macro syntax in AsciiDoc.

For now, we'll leave footnoteref alone, but we can start removing mentions of it from the documentation.

> And on a compat-mode note, will the deprecated syntax be available in compat mode

Yes, but we don't have to worry about that just yet as we're not yet removing the footnoteref macro in this change. But we can certainly do it for 2.0. We'll need a follow-up issue once this one is closed to track it.

**Comment by mojavelinux** [comment]
The only thing holding up the open PR right now is that it needs to be rebased and I need to do some performance testing / tweaking so make sure it doesn't cause any slowdown. It doesn't matter whether the document has footnotes or note. Inline substitutions have to scan all text, so any change to inline macros affects the parsing of every document.

**Comment by mojavelinux** [comment]
I found a way to make this change without any measurable impact on performance.

**Comment by mojavelinux** [comment]
We're not deprecating footnote, only footnoteref (because there is no need for a macro with a different name).
