### ISSUE TITLE
create_image_block method should check that alt and target attribute are defined

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#2349]
> I do think this should be checked in the create_image_block method. In fact, it should check for target too, which is also required. Let's pursue that change in core.

https://github.com/asciidoctor/brackets-asciidoc-preview/issues/40#issuecomment-319449094

**Comment by Mogztter** [comment]
I'm a bit confused, the following test case does not raise an error (on master):

```ruby
test 'should raise an exception if mandatory attributes are not provided' do
  Asciidoctor::Extensions.register do
    block_macro do
      named :picture
      process do |parent|
        create_image_block parent, {}
      end
    end
  end
  input = <<-EOS
.My picture
picture::cat.png[]
  EOS
  doc = document_from_string input
end
```

@nerk  @mojavelinux Am I doing something wrong ?

**Comment by mojavelinux** [comment]
You haven't converted yet. The error happens in the converter.

**Comment by Mogztter** [comment]
ahhhhhh, thanks for the clarification, I'll add a test case 👍

**Comment by mojavelinux** [comment]
I modified the code so that the alt text is auto-generated from the target, just like the main parser does.
