### ISSUE TITLE
Internal cross reference gives incorrect warning

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor#2351]
When I attempt to [define and use inline anchor](http://asciidoctor.org/docs/user-manual/#anchordef), it works fine. However Asciidoctor generates a warning that it is an invalid reference in verbose mode.

I am using Asciidoctor 1.5.6.

```adoc
= Aha

== This is a document

. with
. an
. [[internaldoda]]internal
. cross
. reference

Referenced

after a long block of irrelevancy +

after a long block of irrelevancy +

here <<internaldoda>>
```

```bash
asciidoctor -v -b html5 test.adoc
asciidoctor: WARNING: invalid reference: internaldoda
```

**Comment by mojavelinux** [comment]
That's why the warning is behind verbose mode. We don't currently catalog all anchors. One of those places is in list text.

Closing since this is already covered by #2257. Let's continue the discussion there.
