### ISSUE TITLE
A few suggestions on default CSS stylesheet for note-taking.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor#2354]
![header-mac-screenshot](https://user-images.githubusercontent.com/748856/29000726-96712308-7aaf-11e7-8ffe-411e5ef93533.png)

The screenshot above is of bear note-taking app on Mac.

I like two things about it.

1. I like the style of the text, `#context`. That style is useful for hashtags. Styles for tags and hashtags are useful.
2. The text of a done checklist item is striked over and dimmed. This makes it easier to ignore done checklist items.

**Comment by mojavelinux** [comment]
I'd be willing to accept a PR to dim checked items. I think adding the strikethrough, as in the screenshot, would be too drastic and make the text difficult to read.

**Comment by crocket** [comment]
I decided to close it because we can lose a lifetime in such little details. Those are nice to have, but I am totally fine without them.
