### ISSUE TITLE
Overriding the xrefstyle for only one link 

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor#2365]
The "xrefstyle" feature is really great (new with Asciidoctor 1.5.6.1, see [Customizing the Cross Reference Text](http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text)) 

We use `:xrefstyle: short` and this correspond to what we need for almost all cases.
In some cases, we would prefer to have the full or the basic xrefstyle. I was hoping that I could write:

````
See xref:sec-helloworld[xrefstyle="full"] to get more information
````

Feedback @mojavelinux:

> For the first version, I decided not to allow this just so we could focus on getting the mechanics of the reference text itself working. This is something we can now consider adding in a future version.
> 
> The first problem we're going to run into though, which I discovered when trying to use xref for another purpose, is that the xref macro does not support attributes. This is an inherited behavior from mimicking AsciiDoc Python. But I think that if linkattrs is set (which in 1.6.0 we want to make the default), then the xref macro should support attributes. Then, we can honor the xrefstyle setting.

See the discussion here http://discuss.asciidoctor.org/Overriding-the-xrefstyle-for-only-one-link-td5820.html

**Comment by mojavelinux** [comment]
This relies on #2381.

**Comment by mojavelinux** [comment]
Now that #2381 is resolved, this issue may proceed.
