### ISSUE TITLE
pass:q now needs pass:q,m if it includes macro (improve or regression?)

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#2374]
I am not sure if its an improvement or regression but I used to put, let's say:

```
:AOE: pass:q[[.acro]#indexterm2:[AOE]#]
```

but now (since 1.5.5 ?) it requires me 
```
:AOE: pass:q,m[[.acro]#indexterm2:[AOE]#]
```
to process the `indexterm2` macro. Please close this if it is only an improvement.

**Comment by mojavelinux** [comment]
Using Asciidoctor 1.5.6, if I pass the following document:

```
:AOE: pass:q[[.acro]#indexterm2:[AOE]#]

{AOE}
```

to the command:

```
asciidoctor -o - -s -b docbook test.adoc
```

I get:

```
<simpara><phrase role="acro"><indexterm><primary>AOE</primary></indexterm>AOE</phrase></simpara>
```

But it really depends on what substitution are applied at the location of the attribute reference. For example, if you use this document:

```
:AOE: pass:q[[.acro]#indexterm2:[AOE]#]

[subs=attributes]
++++
{AOE}
++++
```

you'll see

```
<phrase role="acro">indexterm2:[AOE]</phrase>
```

That shows that what is stored in the attribute is the raw indexterm2 macro.

If you want the indexterm2 macro to be substituted eagerly, then you'd add the macro substitution to pass macro around the attribute value:

```
:AOE: pass:q,m[[.acro]#indexterm2:[AOE]#]
```

**Comment by mojavelinux** [comment]
No matter which version of Asciidoctor I try, I always get the same result. I'll need a more detailed example if you are confident there has been a change.

**Comment by shahryareiv** [comment]
I noticed that this happens when the attribute is in the caption of a figure. So if I have

```
:AOE: pass:q[[.acro]#((AOE))#]
```
and then use

```
[#fig_some]
.blah balh, ordered by {AOE}. blah blah.
image::my_image.png[]
```
It will produce (pay attention to untranslated `(())`)

```
<figure xml:id="fig_some">
<title>blah blah<phrase role="acro">((AOE))</phrase>. blah blah.</title>
```

This does not happen for attributes in the normal text. So I guess it means substitutions in the captions is not the same as the main content.

I also wonder if this is related to https://github.com/asciidoctor/asciidoctor-bibtex/issues/17

**Comment by mojavelinux** [comment]
> So I guess it means substitutions in the captions is not the same as the main content.

That's true. After 2.0.0, we plan to have title substitutions use the same order as normal substitutions. I have never understood why they are different.

See https://github.com/asciidoctor/asciidoctor/blob/8d372463528a74735b1a7f0ce2d7e3b733672e87/lib/asciidoctor/substitutors.rb#L15-L17

**Comment by mojavelinux** [comment]
Unless you can explain how to reproduce the regression, I'm not sure what we're talking about here.

**Comment by shahryareiv** [comment]
```

== Example 
:ACRO1: pass:q[[.acro]#((ACRO1))#]
:ACRO2: pass:q,m[[.acro]#((ACRO2))#]


This is a test for {ACRO1}.
This is a test for {ACRO2}.

[#fig_some_a]
.blah balh,  {ACRO1}. blah blah.
image::my_image_1.png[]


[#fig_some_b]
.blah balh,  {ACRO2}. blah blah.
image::my_image_2.png[]
```

which results:
```

Example 1

This is a test for ACRO1. This is a test for ACRO2.
my image 1
Figure 1. blah balh ((ACRO1)). blah blah.
my image 2
Figure 2. blah balh ACRO2. blah blah.
```

Please note the extra `m` in definition of ACRO2 attribute. As you can see ACRO1 was not expanded in the figure1 caption. It used to be not like that before, only `q` was enough  and no need for `q,m`.

**Comment by mojavelinux** [comment]
> It used to be not like that before

You have still not clarified when "before" is. That's what I need to know.

**Comment by mojavelinux** [comment]
What I can say for certain is that if you don't specify a substitution for the `pass` macro, that substitution isn't going to be applied. By default, `pass` does exactly what you say, it passes through unsubstituted. You have to specify every substitution you want. It's been this way ever since #737 (which includes all releases in the 1.5 series).

**Comment by shahryareiv** [comment]
Well, my document which created a published work in December 2015 could not generate the same output Aug 18, 2017, that is what I can say. But if the current behavior the correct one then I think we can ignore it.
