### ISSUE TITLE
Try to read file with 'file://' protocol if it fails in the first place

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#2375]
https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/151#issuecomment-320489920

**Comment by mojavelinux** [comment]
To be clear, this should only be done when running in the browser environment.

```
if ::RUBY_ENGINE_OPAL && ::JAVASCRIPT_IO_MODULE == 'xmlhttprequest'
```

**Comment by mojavelinux** [comment]
Can you let me know what should change at this line?

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/reader.rb#L847-L851

I suppose we'll have to do an eager check for existence.

**Comment by Mogztter** [comment]
I think it may be better to add a special case in Asciidoctor.js: https://github.com/asciidoctor/asciidoctor.js/blob/34e64c3e95293a03d459421a55fa34978b971066/lib/asciidoctor/js/opal_ext/file.rb#L130-L132

**Comment by mojavelinux** [comment]
Since we are talking about the file read operation, I think you're right that this belongs in Opal where the file is being read. It can examine the path and make a decision based on the environment. This is not something core should really be worried about.

**Comment by Mogztter** [comment]
Agree, this should be resolved in Asciidoctor.js (not in Asciidoctor core): https://github.com/asciidoctor/asciidoctor.js/issues/389
