### ISSUE TITLE
Allow attribute reference to include any word character defined by Unicode

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2376]
Currently, only word characters from the Latin subset are permitted in an attribute reference. Extend this support to include any word character as defined by Unicode.

This change would allow the use of accented characters in attribute names (e.g., `{définition}`). While these characters are permitted in an attribute entry (the definition), they are not permitted in an attribute reference (the usage).

These are legal variable names, so it stands to reason they should be allowed as attribute names as well.

**Comment by mojavelinux** [comment]
@Mogztter @hsablonniere @shahryareiv How important / useful do you think this is?

**Comment by shahryareiv** [comment]
Very important indeed, I think. 

1- Latin characters in a Persian (probably other non-Latin)  texts are  disturbing if they are not referring to something which is not Latin in its nature. Compare it for a reverse case: 

`The quick brown {فاکس} jumps over the lazy dog.`

Even the Latin names are usually in Persian (their Latin version might get footnoted)

2- Using attributes for the acronyms (to be used for the first expansion of an acronym,not implemented in asciidoctor yet) in the non-Latin scripts requires the acronyms to be in their original script. If {سمن} should be expanded to سازمان مردم‌نهاد, it does not make sense to use {smn} in the sake of same result, nor to use its English equivalent {NGO}.

3- Most of the Latin scripts lack the concept of capital letters. Instead, writers might prefer alternative presentations to get the same functionality. Using attributes can be a solution to such situations. For example there is a stretch glyph in both Persian, Arabic, and Ordu, called Kashida (ـ) (U-640) that does not change the semantic of the word. One can use attributes to refer to those cases in a consistent way.
```
:نمونه: 
نــــــــــمـــــــــــونـــــــــــــه

این یک جمله برای  {نمونه} است.
```

4- Switching right/left in Bidi scripts is cumbersome if it happens a lot (including Gitbub post entry). Support is still not very smooth in many of editors. The less need to switch is  better.  

Please note that the same is true for macro names, ids, roles, styles, and options. It was so important that I could not wait for the implementation and I created a script to convert some macros and custom role names from Persian to the original names, so my asciidoc texts in Persian maintain to be readable.

**Comment by mojavelinux** [comment]
Thanks! That was the input I was looking for. I had already considered it awkward to have to define attributes names in English when writing in another latin language like French. But your point about bidi switching really justifies this change. (The attribute entries appear on the left margin when written using latin chars).

**Comment by mojavelinux** [comment]
> Please note that the same is true for macro names, ids, roles, styles, and options. 

This is a very different type of change. With attribute names, these are user-defined, so it makes sense they can be typed in the language of the text. Built-in names are keywords. That would be like changing "class" in Java or "var" in JavaScript.

The shorthand syntax does afford some of this since they are marked merely by a symbol:

```
#id.role
```

But we should continue that discussion in the issue that's already open on the topic.
