### ISSUE TITLE
no diagram generation if -o parameter is given in version 1.5.6.1

### ISSUE THREAD

**Issue by a4z** [asciidoctor/asciidoctor#2382]
in a docuemtation I work on, this generates html and diagram png to the right location with asciidoctor 1.5.5, but no diagram with 1.5.6.1
```
asciidoctor -r asciidoctor-diagram -a icons=font -a linkcss -a source-highlighter=prettify@ -a navurl='link:../../../html/toc.html[TOC] (you are here: link:../../../html/index.html[myapp]/link:../../foo/index.html[foo]/bar)' -a docroot='../../' -a imagesdir=index_resources@ -o html/foo/bar/index.html foo/bar/index.adoc
```

same command, but not giving a output directory, also generates the diagram png
```
asciidoctor -r asciidoctor-diagram -a icons=font -a linkcss -a source-highlighter=prettify@ -a navurl='link:../../../html/toc.html[TOC] (you are here: link:../../../html/index.html[myapp]/link:../../foo/index.html[foo]/bar)' -a docroot='../../' -a imagesdir=index_resources@ foo/bar/index.adoc
```

since everything works fine with some versions below 1.5.6, not just 1.5.5,  I think this is a bug that was introduced with the 1.5.6 version

**Comment by mojavelinux** [comment]
Thanks for reporting. There was a bug in how the target document directory was being set and there's chance Asciidoctor Diagram was relying on that bug. We'll track it down and be sure to add a test for it.

**Comment by mojavelinux** [comment]
I agree something is wrong. You can workaround the issue by specifying an output directory instead of an output file.

```
asciidoctor -r asciidoctor-diagram -a imagesdir=index_resources@ -D html/foo/bar foo/bar/index.adoc
```

**Comment by mojavelinux** [comment]
It looks like the `:to_dir` option on the Document object has the wrong value, which is confusing Asciidoctor Diagram. So this is a bug in core after all.

**Comment by mojavelinux** [comment]
As it turns out, this was already fixed by f74990becc97b06ac7d559bbc6b566068abf36ed. The fix will be included in the 1.5.7 release.

**Comment by a4z** [comment]
looking forward being able updating my tool chain to recent versions. Thanks Dan!

**Comment by mojavelinux** [comment]
Thanks to Antora, we've really got a :fire: under Asciidoctor now!
