### ISSUE TITLE
Long table captions makes html and print ugly, especially print

### ISSUE THREAD

**Issue by kallerosenbaum** [asciidoctor/asciidoctor#2392]
This document renders the table caption on a single line:

````
= Test

.Adding a very long table caption will make printing ugly, because the caption will be printed on a single line forcing the rest to become tiny. Do a print preview with and without this caption.
|===
| a 
|===

.Adding a very long image caption will not make printing ugly. The caption will be wrapped nicely. This caption does not make the pringing ugly.
image::nonexisting.svg[]
````
The web rendering looks like this:

![image](https://user-images.githubusercontent.com/1530071/29886678-38062aa6-8dbb-11e7-9265-cd8da4e63f91.png)

And the print preview displays this:
![image](https://user-images.githubusercontent.com/1530071/29886711-5f0ea0d8-8dbb-11e7-8c68-615e15370898.png)

asciidoctor -v
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by kallerosenbaum** [comment]
I work around it in css by
```
table.tableblock>caption.title {
    white-space: unset;
    max-width: unset;
}
```

**Comment by mojavelinux** [comment]
Thanks for reporting.

If I remember correctly, the reason we do this is so that the caption does not cause the table to grow wider than the content requires. But I have to double check that.

**Comment by shahryareiv** [comment]
I just ran into the same problem. I could not figure out why this exists in https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css  (line 188)
`table.tableblock>caption.title{white-space:nowrap;overflow:visible;max-width:0}`
I just added this to my scss and things work as they should:
```
table.tableblock > caption.title {
  white-space: normal;//nowrap
  max-width: none;
}
```
Note: I limit my contents by Foundation `@extend .small-8;` and it might prevent to see possible side-effect.

**Comment by mojavelinux** [comment]
>  I could not figure out why this exists

the reason we do this is so that the caption does not cause the table to grow wider than what the content requires (its natural width)

**Comment by mojavelinux** [comment]
Here's how I'm willing to compromise on this. If the width of the table is set to 100% (using the stretch role, the default), then we won't apply the nowrap/max-width styles. The thinking here is that if you don't want the table to be stretched, then the caption shouldn't influence the width. But if you have a really long caption, you'll need to use a stretch (100% width) table. In that case, we'll make the caption wrap (which is what it would do anyway if we didn't set these styles).

Without a doubt, the caption is a real pain to style because it is highly coupled with the behavior of the table (namely the width).

**Comment by mojavelinux** [comment]
In other words:

```css
table.tableblock:not(.stretch) > caption.title {
  white-space: nowrap;
  overflow: visible;
  max-width: 0
}
```

**Comment by mojavelinux** [comment]
Here's the CSS I'll use, which is a trick to prevent the caption from influencing the width of an autowidth table:

```css
table.tableblock:not(.stretch):not([style^="width:"]) > caption.title {
  white-space: nowrap;
  max-width: 0;
}
```

If you have a long caption, you won't be able to use an autowidth table. You can either make it 100% (the default) or set an explicit width. The caption will then be confined to that width.

What I can't figure out how to do is give the table an automatic width and have the caption fill the bounds of the page (like the image caption in your example above). That just doesn't seem to be something that CSS allows.

**Comment by mojavelinux** [comment]
It turns out that Firefox actually supports setting the width of the caption to 100% of the parent (independent of the table width). I'm not sure if that's a bug or a feature...but it sure would be nice for us if Chrome and Edge supported it.

**Comment by mojavelinux** [comment]
To make this simpler, I'm going to add the "fit-content" class to an autowidth table. That leaves us with:

```css
table.tableblock.fit-content > caption.title {
  white-space: nowrap;
  width: 0;
}
```

**Comment by mojavelinux** [comment]
The long-term solution to this problem will come as part of the semantic HTML5 converter. The table should be wrapped in a figure and the caption placed in a figcaption. That will allow us to style the caption independently of the table, yet still have proper semantics.
