### ISSUE TITLE
Automatically add discrete style to heading inside block

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2395]
It's not possible to have a section title inside of a delimited block. Therefore, we can imply the discrete style, which treats them as primitive headings. The discrete style is only needed outside of delimited block to disambiguate between a section title and a primitive heading.

**Comment by TheDcoder** [comment]
+1 for this feature. [Here](http://discuss.asciidoctor.org/Wrap-AsciiDoc-content-inside-a-div-container-and-assign-a-class-or-id-to-it-td5919.html) is a practical example in which this feature can be useful 😉

**Comment by mojavelinux** [comment]
This is a duplicate of #1998.
