### ISSUE TITLE
XRefLabel doesn't work the same in HTML, PDF and EPUB

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor#2397]
Let's say you have the following document:

```
In <<my-listing1>> you can see a String, in <<my-listing2>> you can see an int.

[[my-listing1, Listing 1]]
.This is a String
[source, java]
----
String s;
----

[[my-listing2, Listing 2]]
.This is an int
[source, java]
----
int i;
----
```

The sentences at the top is correctly translated to *In Listing 1 you can see a String, in Listing 2 you can see an int.* That's fine. What is not correct is the title of the listings. 

In HTML and PDF the titles are:

```
This is a String
This is an int
```

In EPUB the titles are different (notice the prefix `Listing 1.` and `Listing 2.`)

```
Listing 1. This is a String
Listing 2. This is an int
```

This syntax is the one I'm looking for actually... but it doesn't work on HTML and PDF. Is there a way to force Asciidoctor to have the same titles for HTML and PDF or is this a bug ? 

BTW, you can check the sample at https://github.com/agoncal/agoncal-other/tree/master/03-AsciidocXrefLabel if you want

So you know, I'm using : 

```
        <version.asciidoctor.maven.plugin>1.5.5</version.asciidoctor.maven.plugin>
        <version.asciidoctorj>1.6.0-alpha.5</version.asciidoctorj>
        <version.asciidoctorj.pdf>1.5.0-alpha.16</version.asciidoctorj.pdf>
        <version.asciidoctorj.epub3>1.5.0-alpha.7</version.asciidoctorj.epub3>
        <version.jruby>9.1.8.0</version.jruby>
```
#### Related issues

* https://github.com/asciidoctor/asciidoctor/issues/1562
* https://github.com/asciidoctor/asciidoctor/pull/2220

**Comment by mojavelinux** [comment]
This is intentional. When converting to HTML, the listing-caption is not set by default. The listing caption is what adds the prefix Listing X to the caption. It is not enabled for reasons of backwards compatibly.

EPUB3 conversion was a green field, so we decided to enable this attribute by default (see https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/converter.rb#L906). If you want the same behavior as the HTML5 converter, you just turn it off by adding this to the document header.

```
:!listing-caption:
```

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-epub3#tuning-listing-captions

**Comment by agoncal** [comment]
Hum... this is not what I want. When I set the `listing-caption` to true, I get 

```
1. This is a String
2. This is an int
```

I am losing the `Listing` bit. Is there a way to have the following on all formats (at least HTML, PDF and EPUB):

```
Listing 1. This is a String
Listing 2. This is an int
```

**Comment by agoncal** [comment]
I'm getting lost now. 

I've played with the [Cross reference text](http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text) and `:xrefstyle: short` is what I am looking for... but, again, this works differently in HTML, PDF, EPUB, and also if it's a Listing, Figure or Table.

Is there a way to have "Listing 1", "Table 1", "Figure 1" reference on all these formats ? 

```
<<my-listing1>>, <<my-table1>>, <<my-figure1>>

[[my-listing1]]
.This is a String
[source, java]
----
String s;
----

[[my-table1]]
.This is a useless table
[cols="35,65",options="header"]
|===
|Col1
|Col2

|`blah`
|blah blah blah
|===

[[my-figure1]]
.No more images please
image::foobar.png[]
```

**Comment by mojavelinux** [comment]
> When I set the listing-caption to true, I get

True is not a valid value. It either needs to be unset to take the prefix away or set to a string to add it.

In other words, this takes it away:

```
-a listing-caption!
```

This sets it to the same value in all converters:

```
-a listing-caption Listing
```

> I've played with the Cross reference text and :xrefstyle: short is what I am looking for

The new xrefstyle is not yet included in an Asciidoctor EPUB3 release. See #132.

**Comment by mojavelinux** [comment]
Attached to that issue is a PR.

**Comment by mojavelinux** [comment]
I already added support for Asciidoctor PDF, but it's not yet part of a release. This feature required coordination with the converters, which is why it wasn't instantly available.

**Comment by agoncal** [comment]
Yes, `-a listing-caption Listing` does the trick. Thanks @mojavelinux.

For the `xrefstyle`, I'll have to wait then ;o)

**Comment by mojavelinux** [comment]
:+1:

**Comment by jmini** [comment]
Having to set a value for `listing-caption` in order to use `xrefstyle` with value `full` or `short` was also not clear for me. This is why I added a sentence in the documentation. See: https://github.com/asciidoctor/asciidoctor.org/pull/705

By the way, it also works if you set the attributes directly at the top of the document:

```
:listing-caption: Listing
:xrefstyle: short

<<my-listing1>>, <<my-table1>>, <<my-figure1>>

[[my-listing1]]
.This is a String
[source, java]
----
String s;
----

[[my-table1]]
.This is a useless table
[cols="35,65",options="header"]
|===
|Col1
|Col2

|`blah`
|blah blah blah
|===

[[my-figure1]]
.No more images please
image::foobar.png[]
```

**Comment by mojavelinux** [comment]
Thanks Jérémie. Keep in mind that `listing-caption` is the only caption attribute that is not set by default. This was done for backwards compatibility with AsciiDoc Python (though we should consider enabling it in a future major version). The rest are already defined...though of course you may want to redefine them to customize or translate the text.
