### ISSUE TITLE
Support for searchable TOC

### ISSUE THREAD

**Issue by filiphr** [asciidoctor/asciidoctor#2411]
The Hibernate([announcement](https://twitter.com/vlad_mihalcea/status/907594043651223553) from Vlad) and Infinispan([latest server guide](http://infinispan.org/docs/stable/server_guide/server_guide.html)) have a searchable TOC based on Asciidoc. It would be really cool if this can be a core feature of Asciidoc.

**Comment by mojavelinux** [comment]
#3696 was a duplicate of this issue, which was declined. This is something that should be done as a customization, as mentioned in that issue.
