### ISSUE TITLE
Clarify admonition font awesome icon usage in documentation

### ISSUE THREAD

**Issue by chthor** [asciidoctor/asciidoctor#2419]
I've been trying to figure out how to quickly create a custom admonition using the Font Awesome icons. (Specifically, I'm writing a manual and I want `[GOOD]` and `[BAD]` blocks, with `+1` and `-1` icons or similar, blocks illustrating patterns and anti-patterns.) From #1593, it looks like I can't use Font Awesome to create custom admonition icons, right? If so, could we update the [docs](http://asciidoctor.org/docs/user-manual/#admonition-icons) to make this a bit clearer? The way they're currently written ("Asciidoctor supports font-based admonition icons, powered by Font Awesome!") makes it sound like you can create any font-based admonition icon you want, when in fact they are limited to the original five admonition types. (Or, perhaps I'm misunderstanding and you *can* do that; in that case, the docs should show me how.)

**Comment by mojavelinux** [comment]
The icons are controlled by the stylesheet. It's not currently possible to influence the choice from the AsciiDoc document (at least, not easily). I've updated the documentation to make this clear. I also provided an example for how to change the icon for one of the admonition types.
