### ISSUE TITLE
Unicode support for index entries

### ISSUE THREAD

**Issue by meisterluk** [asciidoctor/asciidoctor#2423]
[Unicode defines an ordering](http://unicode.org/reports/tr10/), but AsciiDoctor does not support it in the index. It merges all non-ASCII character entries in one entry labelled "@". This is some enhancement requiring better Unicode support.

Example testcase:
```
(((Öffentlichkeit)))
This is a message.

(((日本語)))
これは日本語の文です。

[index]
== Index
```

Result:
![index](https://user-images.githubusercontent.com/358358/30740912-2af1be40-9f93-11e7-8327-606ec56084d8.png)

**Comment by mojavelinux** [comment]
Oh, I see. In my attempt to promote symbols, I inadvertently promoted all non-Latin letters. Ruby 2.4 has Unicode-aware sorting, so I just need to figure out how to leverage that.

**Comment by mojavelinux** [comment]
...however, this issue needs to be reopened in asciidoctor-pdf because this is not a core issue.

**Comment by meisterluk** [comment]
Thanks for considering. Tell me, if I shall do this.

**Comment by mojavelinux** [comment]
Yes, please. Unfortunately, GitHub doesn't provide a way to move an issue. I wish I could just do that.

**Comment by mojavelinux** [comment]
Moved to https://github.com/asciidoctor/asciidoctor-pdf/issues/853.
