### ISSUE TITLE
Make a missing include file into an error

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor#2424]
Issue #2389 allows includes to be marked as optional, so that a warning is not output if the named file is missing.
With that in place, could a missing file where the optional flag is not set be upgraded to an error? There is now no case where it is not an error, and I really want to be able to fail automated builds.

**Comment by mojavelinux** [comment]
That seems completely reasonable to me. In addition, when the include file is not readable, we are only issuing a warning. AsciiDoc Python fails outright in this case, so I think changing that case to an error as well makes sense.
