### ISSUE TITLE
Positioning roles and attributes for video

### ISSUE THREAD

**Issue by insanetesterftw** [asciidoctor/asciidoctor#2425]
It's possible to add positioning roles and attributes for video similar to those that are available for images?

For example: align="center"

Thank you.

**Comment by mojavelinux** [comment]
Given that this is supported for images, I don't see any reason why we shouldn't support them for images as well.

**Comment by bluebrown** [comment]
Hi, this is missing from the docs page https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/#audio-and-video-attributes-and-options. 

I treid to find the page and open a pr but I cant. There is an edit button on the page but it wants me to create an intellij account. This is not an option for me.  Imo, it would be nice if there was a link to the source in github or whatever public repo its in.

Anyway, thanks for the cool tool.

**Comment by mojavelinux** [comment]
> There is an edit button on the page but it wants me to create an intellij account.

It's asking you to create an account on the Eclipse GitLab instance, not an IntelliJ account. An Eclipse account is required for filing issues or submitting merge requests. That's just how the AsciiDoc Language project is run.

>  Imo, it would be nice if there was a link to the source in github or whatever public repo its in.

There is such a link. It's the GitLab logo next to the "Edit this Page" link.
