### ISSUE TITLE
Snippets from Property List (plist) XML files cannot be included with tag

### ISSUE THREAD

**Issue by akosma** [asciidoctor/asciidoctor#2430]
I have an Asciidoc file `file.adoc` with the following include to show a particular code snippet:

```
[source,xml,indent=0]
---
include::code/Info.plist[tag=sometag]
---
```

The plist file is a standard Apple property list file, and it includes the tag inside a comment (with the spaces [specified in the docs](http://asciidoctor.org/docs/user-manual/#include-partial) )

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- tag::sometag[] -->
	<key>NSMotionUsageDescription</key>
	<string>This is a demo!</string>
    <!-- end::sometag[] -->
</dict>
</plist>
```

When creating the HTML file, Asciidoctor says

```
asciidoctor: WARNING: file.adoc: line 84: tag 'sometag' not found in include file: Info.plist
```

If I rename the file to "Info.xml" then it works:

```
[source,xml,indent=0]
---
include::code/Info.xml[tag=sometag]
---
```

I'm using these versions on Ubuntu Linux 16.04 (64 bit):

```
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

The same error happens also on macOS "High Sierra" (64 bit) with the same version of Asciidoctor and Ruby 2.4.0.

**Comment by akosma** [comment]
Just found out this is a duplicate of #2369. Sorry about the confusion.

**Comment by akosma** [comment]
I reopen it, since CIRCUMFIX_COMMENTS should probably support Apple property list files too.

**Comment by akosma** [comment]
I've just tried in my machine to modify CIRCUMFIX_COMMENTS and indeed, the build process works perfectly. May I send a pull request?

**Comment by mojavelinux** [comment]
Yep, this seems reasonable. Thanks.
