### ISSUE TITLE
Allow to style the numbers of TOC independed of the text

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#2436]
Codelabs of Google make the agenda look really good.

See https://codelabs.developers.google.com/codelabs/accelerated-mobile-pages-advanced/index.html

![Uploading Selection_050.png…]()

I think to archive this with pure CSS in the Asciidoctor output we could need to wrap the number into its own div.

Current 

````
<a href="#high-level-overview-of-android-development">1. High-level overview of Android development</a>
````
I think it would like similar to the following.
````
<div class="seclevel1">
			<a class="link" href="#high-level-overview-of-android-development"></a>
			<div class="number">1.</div>
    	                <div class="description">Read free programming and technology tutorials</div>
</div>
````

cc @jnerlich @fap- 

@fap- could you prepare a patch for @mojavelinux to review?

**Comment by mojavelinux** [comment]
To be honest, this is really the whole reason we have converter templates. If you are creating anything other than an out-of-the-box HTML document, you should definitely be using custom templates. You can customize every single character of the HTML that is produced using templates, giving you the ability to create a vastly different appearance than what the default HTML and stylesheet give you. I really encourage you to leverage that feature.

**Comment by mojavelinux** [comment]
I would consider changing the output of the built-in HTML converter if the default HTML gets you 99.9% of the way there and there's this one thing thing in the markup that's preventing you from being able to style it the way you want. Those are the types of changes that just make sense because they are just speed bumps.

But if you want to make something like the link you shared, I would strongly recommend creating your own HTML output so that you have the freedom in the HTML to make the UI you want.

**Comment by vogella** [comment]
Thanks @mojavelinux. First time I hear about converter templates (sorry for my ignorance). I close this issue and @jnerlich @fap- and I can look into them.

**Comment by mojavelinux** [comment]
Trust me, you are going to love them. Here's a sample set you can start with.

https://github.com/asciidoctor/asciidoctor-backends/tree/master/slim/html5

Remember, you only have to supply the template for the node you want to override. You don't need to duplicate work that the built-in converter does.

Every interface of Asciidoctor supports passing the directory to the templates (AsciidoctorJ, Maven plugin, Gradle plugin, etc).

**Comment by mojavelinux** [comment]
Here's how the OpenShift project uses templates:

https://github.com/openshift/openshift-docs/tree/master/_templates

**Comment by vogella** [comment]
https://github.com/asciidoctor/asciidoctor.org/issues/80 seems the issue for the documentation of this topic.

**Comment by mojavelinux** [comment]
Actually, scratch that. Those are different templates now.

You can see examples of other templates in the Asciidoctor Bespoke converter:

https://github.com/asciidoctor/asciidoctor-bespoke/tree/master/templates/slim

**Comment by vogella** [comment]
Note for @fap- I don't see how to include templates from a Gradle build (using the org.asciidoctor.convert plug-in). http://discuss.asciidoctor.org/Add-new-attribute-to-the-html-p-tag-td3976.html describes this for the standard Asciidoctor command line, maybe you know how to include that in our Gradle build?

**Comment by mojavelinux** [comment]
```
options template_dirs: [new File('templates/slim').absolutePath]
```

If you have other options defined, then `template_dirs` gets added as another key in the options map.

**Comment by mojavelinux** [comment]
(I don't know if the absolute path part is necessary, but I guess it has to do with multi-module Gradle builds. It can't hurt).

**Comment by vogella** [comment]
Thanks @mojavelinux, giving it a try right now.

**Comment by vogella** [comment]
I failed to make it work for our build but I move this to our internal discussion (Fabian and me), I think the approach should be relatively straightforward and I'm l doing just something silly.

Thanks again, @mojavelinux
