### ISSUE TITLE
ampersand in author line of document header

### ISSUE THREAD

**Issue by boxeomega** [asciidoctor/asciidoctor#2439]
Recently upgraded to most recent version of asciidoctor. In my documents, I have "Global R&D Center" in my author line, just under the document title. Previously, this would parse just fine, but now it gets outputted as: 'Global R\&amp;amp;D Center'. Any other ampersand in the document gets parsed just fine, but not this one in the author line.

**Comment by mojavelinux** [comment]
This is not the behavior I observe. Do you by chance have any extensions that are processing the document? Can you explain what you are using to convert the document?

Here's the document I tested.

```
= Document Title
Global R&D_Center

{author}
```

**Comment by boxeomega** [comment]
Here is the command line I use: asciidoctor -a nofooter -r asciidoctor-diagram -b html 

Here is the document header:

= LEAP Braze Paste Automation Cell: Operating Instructions
Global Automation and Robotics R&D Centre
Version 0.0, 2017-08-15: DRAFT
:toc: left
:toclevels: 3
:imagesdir: Img
:stylesdir: ..\..\StyleSheet\CSS
:stylesheet: ge_asciidoctor.css
:sectnums!:
:sectnumlevels: 4
:icons: font 
:projectnum: RT103428
:document-filename: {projectnum}_OI.pdf

And here is the output:
![image](https://user-images.githubusercontent.com/19697476/31225800-bce40dc2-a9a1-11e7-8e8b-b8d6c3b1e4b7.png)

**Comment by mojavelinux** [comment]
My mistake. I was testing against the master branch instead of 1.5.6.1. This has already been fixed in master. The fix will be available in the next release.

**Comment by mojavelinux** [comment]
I'll be honest. I don't know exactly what I did to fix it...but I'm sure it's fixed. I'll add a test just to be sure.

**Comment by mojavelinux** [comment]
I'll close once I've added the test.
