### ISSUE TITLE
Disable preamble

### ISSUE THREAD

**Issue by lschmelzeisen** [asciidoctor/asciidoctor#2454]
Is there any way to controll on a *per-document-basis* whether the first paragraph should be tagged as a preamble?

Let's say I have the following document:

```asciidoc
= Test

I don't want this to become a preamble.

== Heading

Some text.
```

How would I stop the first paragraph from being tagged as a preamble?

**Comment by mojavelinux** [comment]
You can't (out of the box). By its very definition, the content the precedes the first section is a preamble.

If you don't want to output it this way, you can use a custom template. As I often say, every single character of HTML can be customized using custom templates. It's exactly cases like this why Asciidoctor was designed that way.

See https://github.com/asciidoctor/asciidoctor.org/issues/80

**Comment by lschmelzeisen** [comment]
Yes, I realize I can modify the HTML output, that is the main reason I'm using Asciidoctor. And on most of my pages I want exactly this behavior of turning everything before the first section into the preamble.

However, this leaves no way for me to disable the preamble generation on a specific page. I would be fine with setting a document attribute that disables this behavior. I also think there is no way for me to do this myself, or can I pass parameters to the `block_preamble` using the existing syntax?

**Comment by lschmelzeisen** [comment]
Ok, I figured out how to do it. Thanks for providing that link!

For reference, to not generate a preamble on pages with a `:no-preamble:` document attribute you could use a template `block_preamble.haml` like the following:

```haml
- if @document.attributes.key? 'no-preamble'
  = content
- else
  #preamble
    =content
```
