### ISSUE TITLE
Cannot nest image: within btn:

### ISSUE THREAD

**Issue by enikao** [asciidoctor/asciidoctor#2462]
I'm trying to show the icon of a button with the appropriate inline macros.

# Example .adoc:

````
= Image Inside Button

:experimental:

This is a btn:[Button].

This is an image:icon.png[].

This is a btn:[image:icon.png[] inside a button] with some follow-up text.

There is also a following paragraph, that's still recognized as a button.

== Only after a new heading the button stops.
````
# Expected outcome:
````
This is a [ <<image>> inside a button ] with some follow-up text.
````

# Actual outcome:
````
This is a [ <<image>> </b> inside a button with some follow-up text. ]
````
and everything up to the next heading is formatted as button.

**Comment by mojavelinux** [comment]
The correct way to nest an image macro inside of a button macro is as follows:

```
This is a btn:[image:icon.png[\] inside a button] with some follow-up text.
```

Notice that you must escape the closing backslash on the image macro so that it does not prematurely end the button macro.
