### ISSUE TITLE
Custom admonition icon using data-uri

### ISSUE THREAD

**Issue by s-ga** [asciidoctor/asciidoctor#2465]
Using custom image for admonition using `data-uri` leads to incorrect generation.

Example :

```adoc
:data-uri:
:icons:
[icon=test.png]
[NOTE]
====
Admonition test 
====
```

One can see in generated HTML that a rogue `.png` extension is added after the base64 content:

```HTML
<td class="icon">
    <img src="data:image/png;base64,iVBORw0KGgoA [cutted] RU5ErkJggg==.png" alt="Note">
</td>
<td class="content">
    <div class="paragraph">
        <p>Test admonition</p>
    </div>
</td>
```
https://github.com/asciidoctor/asciidoctor/blob/5f4e6b1eaf23ab2541957a872e392f24dc7b1c1d/lib/asciidoctor/abstract_node.rb#L283

**Comment by mojavelinux** [comment]
Thanks for reporting!

**Comment by mojavelinux** [comment]
As it turns out, the order of logic was wrong. I just submitted a patch.

**Comment by s-ga** [comment]
Thanks!
