### ISSUE TITLE
:sectnums!: not respected

### ISSUE THREAD

**Issue by G10h4ck** [asciidoctor/asciidoctor#2470]
Hi!

In a document I have 

```
:numbered!:
:sectnums!:
[[license]]
== Licencia

(C) copyright 2017 {author}. +
Este trabajo es distribuido segun la licencia Creative Commons
Attribution-ShareAlike 4.0 International License. +
Por ver una copia de la licecia visita
http://creativecommons.org/licenses/by-sa/4.0/. +

image::images/CC-BY-SA_icon_orange_{imgExt}["License", align="left", link="http://creativecommons.org/licenses/by-sa/4.0/"]
```

I do expect that last section to be unnumbered while it keeps being numbered as you cans see here

https://imagebin.ca/v/3gFU3Jz9XcLf
https://imagebin.ca/v/3gFUHgQnRZd9

I am generating the PDF with the following commands

```
	./images.sh 300dpi
	asciidoctor --verbose \
		--backend docbook5 \
		--attribute stem=asciimath \
		--attribute imgExt=300dpi.png \
		README.adoc
	../asciidoctor-fopub/fopub README.xml
```

images.sh just create PNG to be included in the PDF from SVG

```
$ asciidoctor --version
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.8p477 (2017-09-14 revision 59906) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

asciidoctor-fopub $ git log -n 1
commit a5d8ee45b6c68c72c38c72af768e4017d70f4f75 (HEAD -> master, origin/master, origin/HEAD)
Author: apnadkarni <apnmbx-wits@yahoo.com>
Date:   Fri Apr 7 10:20:10 2017 +0530
```

**Comment by rockyallen** [comment]
I think you need to pass an option to the fopub stylesheets (somehow):
http://www.sagehill.net/docbookxsl/SectionNumbering.html
sectnums and numbered work with html and the native pdf, but docbook has its own way of doing things, and it looks like asciidoctor-fopub doesn't do it for you.

**Comment by mojavelinux** [comment]
That's absolutely correct. Selective numbering in DocBook is controlled by the XSL.

**Comment by mojavelinux** [comment]
I should clarify that DocBook does not support a way to store selective numbering, so there's technically nothing we can do in Asciidoctor core to address this. Please reopen in asciidoctor-fopub if you think this should be addressed as a documentation issue.
