### ISSUE TITLE
`:icons: font` casues `linenums` misalignment in html5

### ISSUE THREAD

**Issue by maverickwoo** [asciidoctor/asciidoctor#2474]
I am using the latest master 39f6c5e as of this writing. Consider the following foo.adoc file with `asciidoctor -b html5 foo.adoc`:

```adoc
= Listing line number bug
:doctype: book
:icons: font
:pygments-style: tango
:source-highlighter: pygments

[source,bash]
----
# edit bar.py <1>
----
<1> Put the following into `bar.py`:
[source,python,linenums]
x = 1
x = 2
x = 3
x = 4
x = 5
x = 6
x = 7
x = 8
x = 9
x = 10
```

The rendered line numbers in Chrome are misaligned. Screenshot:

![screen shot 2017-11-08 at 18 11 05](https://user-images.githubusercontent.com/172693/32579736-3ccdf524-c4b0-11e7-9d76-a3a2dd3728c6.png)

But if we take out `:icons: font`, then the alignment will be proper.

**Comment by mojavelinux** [comment]
I do not observe this behavior. Are you sure you are using the default stylesheet with no overrides?

Also, could you look in Firefox to see if you observe the same behavior?

**Comment by maverickwoo** [comment]
I have just upgraded asciidoctor to latest master c0c1af4 and rerun. I see the same result in Chrome, Firefox, and Safari on my Mac. To ensure it is not an issue with my Mac, I have also booted a fresh Windows VM and see the same result in Edge.

I use the exact same adoc file and the command line posted above. So I think I am not overriding the stylesheet. Perhaps we can diff the html. I have attached a zip file with the html file I generated. 

[adoc-bug-2474-linenums.zip](https://github.com/asciidoctor/asciidoctor/files/1486005/adoc-bug-2474-linenums.zip)

**Comment by mojavelinux** [comment]
Aha! I see what the problem is. When you gave me the example, I subconsciously changed it without knowing it. Now I see you are putting the source block inside the callout list item.

The styles for the callout list item are overriding the styles for pygments. I can fix that.

Technically, you should be attaching the source block using a list continuation. You are currently relying on unspecified behavior (which is what confused me).

```
[source,bash]
----
# edit bar.py <1>
----
<1> Put the following into `bar.py`:
+
[source,python,linenums]
x = 1
x = 2
x = 3
x = 4
x = 5
x = 6
x = 7
x = 8
x = 9
x = 10
```

**Comment by mojavelinux** [comment]
PR sent!
