### ISSUE TITLE
'basebackend' attribute is not properly set for 'pdf' backend. 

### ISSUE THREAD

**Issue by i-kuzmin** [asciidoctor/asciidoctor#2479]
I'm tring to relay on 'basebackend' attribute to register extension. It works fine for html backends, but when I set 'pdf' it still has 'html' value.

```ruby
Asciidoctor::Extensions.register do
  preprocessor AttributesPreprocessor
  $stdout.puts  document.attributes['basebackend']
  $stdout.puts  document.attributes['backend']
...
```
```bash
$ asciidoctor  -b pdf ...
html
pdf
```

While for html5:
```bash
$ asciidoctor -b html5 ...
html
html5
```

**Comment by mojavelinux** [comment]
Technically this is correct. The basebackend for the PDF converter is in fact html. That's how it's able to leverage the inline node handlers from the HTML converter. The relationship is a bit obscure, but that's how the converter is implemented.

I'd say that basebackend is largely an internal attribute, one that is used to determine the hierarchy of converters. So it's really better to check the backend, not the basebackend.

**Comment by i-kuzmin** [comment]
Examples in "Asciidoctor Users Guide"  use `document.basebackend` to check backed:
```ruby
Asciidoctor::Extensions.register do |document|
 ...
  docinfo_processor TrackingCodeDocinfoProcessor if document.basebackend? 'html'
  block ShoutBlock
  block_macro GistBlockMacro if document.basebackend? 'html'
 ...
end
```
`/lib/asciidoctor/document.rb`:
```ruby
  def basebackend? base
    @attributes['basebackend'] == base
  end
```

Does It mean examples are incorrect, and clients code should look like:
```asciidoc
Asciidoctor::Extensions.register do |document|
 ...
  docinfo_processor TrackingCodeDocinfoProcessor if document.attributes['backend'] =~ '^html'
  block ShoutBlock
  block_macro GistBlockMacro if document.attributes['backend'] =~ '^html'
 ...
end
```

**Comment by mojavelinux** [comment]
Yes, that's correct. Take for example the gist block macro. That definitely should not be based on basebackend since that's not going to work in Asciidoctor PDF.

Another way to check for HTML, or the format, is to consult the outfilesuffix attribute. For HTML, it will almost always be .html.

**Comment by i-kuzmin** [comment]
You are right, it is not difficult to work-around current behavior. Still, it looks more like a hack neither expected behaviour.

**Comment by mojavelinux** [comment]
Yep. As I said, the Asciidoctor PDF plugin is a bit obscure. Though, I have down in my notes to separate the behavior of the parent converter from the concept of a format. Since "backend" are really about selecting converters, then I think we probably want to have another attribute the expresses the type of output being produced.
