### ISSUE TITLE
verseblock shouldn't introduce new font and font-size

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#2480]
Currently, the default CSS has
```
verseblock pre {font-family: "Open Sans", "DejaVu Sans", sans; font-size: 1.15rem; ...}
```
But this is an intrusive specification. The verse block should simply inherit the surrounding font:
```
verseblock pre {font-family: inherit; ...}
```
(The setting of `font-family` is needed because `pre` would otherwise inject a monospace font. There is not need to set `font-size`.)

**Comment by mojavelinux** [comment]
This was an intentional design choice. The idea is to make the verse stand apart from the rest of the text.

Can you provide an example of what you are using the verseblock for so I can get a visual picture of how this styling is intrusive?

**Comment by ds26gte** [comment]
Using it for verse extracts amid prose: any example will do. I haven't seen traditionally typeset text changing from serif to sans (or indeed, a different typeface!) for verse. Sure, I can imagine why someone might prefer it in special cases, but then it should be offered as an opt-in block attribute, no?

**Comment by mojavelinux** [comment]
This is the style we choose for the default stylesheet. You are welcome to use a different stylesheet if you prefer a different style, or to override it by extending the default stylesheet. Information about how to do all that can be found in the docs. See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/
