### ISSUE TITLE
Displaying new lines in stem environment doesn't work

### ISSUE THREAD

**Issue by hgiesel** [asciidoctor/asciidoctor#2484]
What I wrote:

```
= My file
:stem:

[stem]
++++
a^{2} + b^{2} = c^{2} \\
(a + b)^\frac{1}{2} = c
++++
```

My expectation: equations are displayed on separate lines. 
What I got: Both are displayed on the same line.

**Comment by mojavelinux** [comment]
The problem is that you are using TeX syntax, but it's being interpreted as AsciiMath. When you set the `stem` attribute without a value, it defaults to AsciiMath. In order to use TeX, you need to set the value to `latexmath`.

```
= My file
:stem: latexmath

[stem]
++++
a^{2} + b^{2} = c^{2} \\
(a + b)^\frac{1}{2} = c
++++
```

Then it will work as expected.

**Comment by hgiesel** [comment]
Okay thanks. Just for curiosity, I looked up how to make newlines in `AsciiMathML` and [it seems like you can't](https://github.com/asciimath/asciimathml/issues/49)

**Comment by mojavelinux** [comment]
I came to the same conclusion. That seems odd, but I guess it fits with the focus of AsciiMath, which is a simple syntax for simple equations.

**Comment by hgiesel** [comment]
The only thing is that it pretty much defeats the purpose of stem blocks when using AsciiMath, which is, at least to me, to avoid having to wrap every line in inline blocks, when you have more than one line of formulas.

**Comment by mojavelinux** [comment]
I agree. If there's a way we can support newlines in AsciiMath from the
AsciiDoc side, I'm happy to add it. Otherwise, perhaps a patch to MathJax
is necessary.
