### ISSUE TITLE
Differences between inline and stem blocks when using AsciiMath

### ISSUE THREAD

**Issue by hgiesel** [asciidoctor/asciidoctor#2498]
Having the AsciiDoc:

```
stem:[AA x. xRx]

[stem,asciimath]
++++
AA x. xRx
++++

[stem,latexmath]
++++
\forall x. xRx
++++
```

... produces:

![image](https://user-images.githubusercontent.com/7188844/33242067-43ad6672-d2cf-11e7-9445-5294fcd7f72d.png)

I don't this should be the behavior, the expected behavior would be to have the latter two formulas look the same. The produced HTML looks like this:

```html
<div class="paragraph">
    <p>\$AA x. xRx\$</p>
</div>
<div class="stemblock">
<div class="content">
    \$AA x. xRx\$
</div>
</div>
<div class="stemblock">
<div class="content">
    \[\forall x. xRx\]
</div>
</div>
```

I think the simplest to match those two renderings to have two new classes `stemblock-latexmath` and `stemblock-asciimath`, where `stemblock-asciimath` adds `text-align: center; padding: 20px 0px;`, which makes both versions look pretty much the same.

**Comment by mojavelinux** [comment]
This request also came up here: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/272

Fortunately, we can solve this without any change to the generated HTML. MathJax provides a way to apply a filter during typesetting that gives us the opportunity to change the display setting (i.e., display math).

```js
MathJax.Hub.Register.StartupHook("AsciiMath Jax Ready", function () {
  MathJax.InputJax.AsciiMath.postfilterHooks.Add(function (data, node) {
    if ((node = data.script.parentNode) && (node = node.parentNode) && node.classList.contains('stemblock')) {
      data.math.root.display = "block";
    }
    return data;
  });
});
```

If we drop this into our MathJax config, it will just work.

**Comment by mojavelinux** [comment]
It's debatable whether this is a bug or a feature request. If we consider that fact that the block form of AsciiMath is not rendering like the block for of LaTeX math, then we could say it's a rendering bug.
