### ISSUE TITLE
Register media type (aka MIME type) for AsciiDoc

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2502]
There's currently no official mime type registered for AsciiDoc. Any attempt to include a mime type in a mime type database is being rejected as a result. Therefore, we need to go through the formal process of getting it registered.

Here are the instructions for doing so:

https://tools.ietf.org/html/rfc6838#section-5

The proposed mime type is as follows:

```
name: text/asciidoc
extensions: .adoc, .asciidoc
```

The format text/asciidoc follows the convention used for Markdown. (see https://tools.ietf.org/html/rfc7763)

**Comment by mojavelinux** [comment]
Discussion for context: https://github.com/jshttp/mime-db/pull/107

**Comment by elextr** [comment]
Note, its probably just as useful to get it into freedesktop, like rust did https://bugs.freedesktop.org/show_bug.cgi?id=90487

**Comment by mojavelinux** [comment]
Thanks for that pointer, @elextr!

**Comment by KantarBruceAdams** [comment]
Some interesting links relating to this:

There are two RFCs relating to markdown

[RFC 7763 - The text/markdown Media Type](https://tools.ietf.org/html/rfc7763)
[RFC 7764 - Guidance on Markdown](https://tools.ietf.org/html/rfc7764)

See also:
https://talk.commonmark.org/t/ietf-request-for-input-text-markdown-media-type/700/14

Also someone wants to use asciidoc for wrting RFCs (this is a recently expired draft)

https://tools.ietf.org/id/draft-ribose-asciirfc-08.html

Perhaps writing an RFC along these lines is the place to start.
It can reference asciidoctor (and maybe asciidoc) as an externally defined standard with a version or variant parameter as appropriate.
As in:

    content-type: text/asciidoc; charset=UTF-8; variant="asciidoctor"

Though if there was a standard specification document (as intended for [unidoc](https://github.com/asciidoctor/asciidoctor/wiki/AsciiDoc-Specification-(aka-UniDoc)-Planning)) or [a standard way of specifying one](https://github.com/asciidoctor/asciidoctor/issues/2483) we could use:

    content-type: text/asciidoc; charset=UTF-8; version="1.0"



Note also I think the correct term is now "[Media Type](https://en.wikipedia.org/wiki/Media_type)". MIME type refers to email and Content-Type is part of HTTP.

**Comment by mojavelinux** [comment]
Thank you for this fantastic information, @KantarBruceAdams!

**Comment by mojavelinux** [comment]
This should be handled as part of the AsciiDoc specification. See https://asciidoctor.org/news/2019/01/07/asciidoc-spec-proposal/

**Comment by martinjuckes** [comment]
I don't know if this matters, but a company called Authentica has a competing interpretation of the `adoc` suffix: e.g. https://whatis.techtarget.com/fileformat/ADOC-Authentica-Secure-Office-Protected-Word-Document-Authentica .

**Comment by mojavelinux** [comment]
The AsciiDoc WG will handle this (and specifically the IP management and licensing counsel provided by the Eclipse Foundation).

**Comment by dillonredding** [comment]
Since you're proposing `text/asciidoc`, I'm curious if anyone has considered [Section 3 of RFC 6838](https://tools.ietf.org/html/rfc6838#section-3)? Without a leading facet (`vnd.`, `prs.`, or `x.`), this would fall in the [standard tree](https://tools.ietf.org/html/rfc6838#section-3.1); however, according to that RFC, use of `text/asciidoc` would have to meet the following requirement:

> Registrations in the standards tree MUST be either:
> 1. in the case of registrations associated with IETF specifications, approved directly by the IESG, or
> 1. registered by a recognized standards-related organization using the "Specification Required" IANA registration policy [[RFC5226](https://tools.ietf.org/html/rfc5226)] (which implies Expert Review).

I believe the second case is most fitting, which means `text/asciidoc` would need to be added to the [IANA registry of media types](https://www.iana.org/assignments/media-types), which means an RFC describing the format (similar to [RFC 7763](https://tools.ietf.org/html/rfc7763)) is required. More to this point, note [Section 6 of RFC 7763](https://tools.ietf.org/html/rfc7763#section-6) (IANA Considerations).

**Comment by mojavelinux** [comment]
The author of mime-db also stated something similar to (2) as a requirement in this comment https://github.com/jshttp/mime-db/pull/107#issuecomment-347728127:

> all we need is a concrete specification to link to. If you publish it as the authority of AsciiDoc on whatever the website is for that ... that's good enough, because that's all I'm even looking for.

**Comment by mojavelinux** [comment]
This issue is now superseded by https://gitlab.eclipse.org/eclipse-wg/asciidoc-wg/asciidoc-wg/-/issues/5. It's the responsibility of the AsciiDoc WG and Eclipse Legal to complete this task. It's now out of the hands of the Asciidoctor project.
