### ISSUE TITLE
Strange problem with vimeo video.

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#2504]
Hello.

I have very strange problem with vimeo video embeding.

I try:
```
video::146599806[vimeo]
```
In preview I see two videos unstead of one. :open_mouth:

Then I tried `asciidoctor myfile.adoc` and there are 2 vimeo videos in result web page too.

Is this a bug? Maybe I made smth. wrong?

Best regards,
Andrey.

**Comment by mojavelinux** [comment]
This is very likely a bug in the Vimeo embed code. Here's what Asciidoctor emits.

```
<div class="videoblock">
<div class="content">
<iframe src="https://player.vimeo.com/video/146599806" frameborder="0" allowfullscreen></iframe>
</div>
</div>
```

As you can see, there's only one iframe. So the duplication is not coming from our side.

**Comment by sindzicat** [comment]
Hm..., @mojavelinux, sorry, but now I cannot agree with you now.

I've been created test file with the following content:

```
:nofooter:

video::146599806[vimeo]
```

Then in console:

```
asciidoctor test.adoc
```

Then I've been opened result `test.html` in vs code. At the end of this file I see:

```
</head>
<body class="article">
<div id="header">
</div>
<div id="content">
<div class="videoblock">
<div class="content">
<iframe src="https://player.vimeo.com/video/146599806" frameborder="0" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/146599806" frameborder="0" allowfullscreen></iframe>
</div>
</div>
</div>
</body>
</html>
```

So it seems to me that problem is in Asciidoctor. Maybe your Asciidoctor is newer than my one? My Asciidoctor:

```
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:UTF-8)
```

**Comment by sindzicat** [comment]
I just have been opened `html5.rb` and see from line 1033:
```
<iframe#{width_attribute}#{height_attribute} src="#{asset_uri_scheme}//player.vimeo.com/video/#{node.attr 'target'}#{start_anchor}#{autoplay_param}#{loop_param}" frameborder="0"#{(node.option? 'nofullscreen') ? nil : (append_boolean_attribute 'allowfullscreen', xml)}></iframe>
<iframe#{width_attribute}#{height_attribute} src="#{asset_uri_scheme}//player.vimeo.com/video/#{node.attr 'target'}#{start_anchor}#{autoplay_param}#{loop_param}" frameborder="0"#{(node.option? 'nofullscreen') ? nil : (append_boolean_attribute 'allowfullscreen', xml)}></iframe>
```

I can't understand now why so, but at least I see, how I can fix this.

So It seems to me now, that this question can be closed.
Thanks! :)

**Comment by mojavelinux** [comment]
Perhaps you were editing the file and accidentally duplicated that line. You can always uninstall and reinstall the gem to check, but I'm pretty sure it's not duplicated in the official package.

**Comment by sindzicat** [comment]
@mojavelinux, OK.
