### ISSUE TITLE
Resolve nested include directives in remote include file

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2506]
Include directives in the contents of a remote include file are not properly resolved. They should continue to be read starting from the URL of the remote file. Instead, the URL gets mangled and thus fails to resolve.

**Comment by mojavelinux** [comment]
Here's prototype code that demonstrates what needs to happen:

```ruby
Asciidoctor::Extensions.register do
  current_document = @document

  include_processor do
    handles? do |target|
      current_document.reader.cursor.dir.start_with? 'https://'
    end

    process do |doc, reader, target, attrs|
      inc_path = %(#{current_document.reader.cursor.dir}/#{target})
      inc_contents = open(inc_path, 'r') {|f| f.read }
      reader.push_include inc_contents, inc_path, target, 1, attrs
    end
  end
end
```

**Comment by mojavelinux** [comment]
Here's an example:

```
include::https://rawgit.com/asciidoctor/asciidoctor-pdf/master/README.adoc[]
```

If this document is processed using:

```
asciidoctor -a allow-uri-read test.adoc
```

It generates the following warning:

```
include file not found: /tmp/https://rawgit.com/asciidoctor/asciidoctor-pdf/master/examples/basic-example.adoc
```

The directory of the outermost file is being prepended to the URL, and thus the URL fails to resolve.

**Comment by mojavelinux** [comment]
I considered storing the `@file` and `@dir` in the include stack as a `URI` so we can simply check `URI === @dir` to know if we're currently inside of a remote document. I decided to defer that change because it needs more testing. However, it seems to make a lot of sense.

**Comment by Mogztter** [comment]
@mojavelinux :+1: 

I'm working on https://github.com/asciidoctor/asciidoctor.js/issues/394 but we need to implement OpenURI module in Opal (or at least handle URI path in the File constructor): https://github.com/opal/opal/issues/1721
