### ISSUE TITLE
 Conditional Directives (ifdef) is not converted

### ISSUE THREAD

**Issue by yoshimis** [asciidoctor/asciidoctor#2510]
I would like to have conditional directives (ifdef) to be included in the converted html file. Converting the attached asciidoc results in no contents in html.
[Chart-Views.zip](https://github.com/asciidoctor/asciidoctor/files/1550254/Chart-Views.zip)

**Comment by mojavelinux** [comment]
The document will be blank as you have filtered out all the lines. You need to define one of the attributes in the conditionals (such as desktop) if you want content to show.

```
asciidoctor -a desktop Chart-View.adoc
```

If you think lines are still being filtered out that shouldn't be, make sure there are no unclosed conditions.

**Comment by yoshimis** [comment]
Thank you Dan! It worked. :)

**Comment by mojavelinux** [comment]
:+1: Glad to hear it!
