### ISSUE TITLE
Invisible comments in source block

### ISSUE THREAD

**Issue by antoyo** [asciidoctor/asciidoctor#2516]
Hi.
Is there a way to have invisible comments (i.e. comments that won't be shown in the final output) inside code blocks?
Something like:
```adoc
[source,c]
----
//// #include <stdio.h> // This line won't be shown in the final output.

void main(void) {
}
----
```
Thanks.

**Comment by DavidGamba** [comment]
You can use tagged regions or include by line numbers (not as robust in my opinion).

The tagged regions docs can be found here: http://asciidoctor.org/docs/user-manual/#include-partial

**Comment by antoyo** [comment]
I found another way which is using `ifdef`s:
```adoc
[source,rust]
----
ifdef::doctest[]
extern crate tql;
endif::[]

fn main() {
    sql!();
}
----
```
It is similar to tagged regions, but works inline.

Also, avoiding the delimiters like the following works only for the first comment:
```adoc
[source,c]
// #include <stdio.h> // This line is not shown in the final output.
void main(void) {
}
```
But I wondered if there is a built-in way of doing so.
Thanks.

**Comment by antoyo** [comment]
My use case is to test the codes in the documentation, like with [mdBook](http://rust-lang-nursery.github.io/mdBook/format/rust.html#hiding%20code%20lines).
Is this possible to do so with asciidoctor or could this feature be added?

**Comment by antoyo** [comment]
@mojavelinux Any new or info about this?
Thank you.

**Comment by mojavelinux** [comment]
> Is this possible to do so with asciidoctor 

You can write a tree processor extension that looks for verbatim blocks and removes unwanted lines. If you need help, please ask in the chat at https://chat.asciidoctor.org. This is not a feature we are going to add to the AsciiDoc language itself. A verbatim block is intended to be output verbatim and we don't want to mess with those semantics.
