### ISSUE TITLE
Ampersand in manpage output replaced with &amp;

### ISSUE THREAD

**Issue by dimztimz** [asciidoctor/asciidoctor#2525]
Affected versions 1.5.6.1, 1.5.5, probably others.

Steps to reproduce, create sample file `hello.adoc` with ampersand in normal paragraph

```adoc
= HELLO(1)

== NAME

hello - asd < > &

== SYNOPSIS

& wer & hi hi < >
```

And run:

    asciidoctor -b manpage hello.adoc && man ./hello.1

This is the output:

```
HELLO(1)

NAME
       hello - asd < > &

SYNOPSIS
       &amp; wer &amp; hi hi < >

```

Expected output is to see normal ampersand in SYNOPSIS. Weirdly enough ampersand in NAME is OK.

I think the fix is in the `converter/manpage.rb` in the [function](https://github.com/asciidoctor/asciidoctor/blob/171183647b79726b9357f0c45a0ad6c5b5ec40f1/lib/asciidoctor/converter/manpage.rb#L34) `manify`. A substitution from "&adoc;" to "&" should be made somewhere at the end, after all other substitutions that contain ampersand.

**Comment by mojavelinux** [comment]
Right you are! Somehow we overlooked this!
