### ISSUE TITLE
Multiple man page names don't work (title & name reversed?)

### ISSUE THREAD

**Issue by gdamore** [asciidoctor/asciidoctor#2543]
Sometimes I want to have a man page with multiple entries for .NAME

For example:

```
nng_msg_append(3)
=================
:doctype: manpage
NAME
----
nng_msg_append, nng_msg_append_u32 - append to message body
```

This man page would cover two closely related functions; putting them in a single man page means I can reduce some of my redundant text.  This is also often handled via "aliases" in the man world (.so).

Unfortunately, the man format that this generates is ugly:

```
NNG_MSG_APPEND, NNG_MSG_APPEND_U32(3) nngNNG_MSG_APPEND, NNG_MSG_APPEND_U32(3)

NAME
       nng_msg_append - append to message body
```

What's happened here -- it appears -- is that the *title* and the *name* are actually reversed in the documentation output.

What I really want is something more like the output (man -s2 open on macOS):

```
OPEN(2)                     BSD System Calls Manual                    OPEN(2)

NAME
     open, openat -- open or create a file for reading or writing
```

I.e. I should have one "title", but multiple names.

**Comment by gdamore** [comment]
Oh, also for info:

```
garrett@triton{647}% asciidoctor --version
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Thanks for reporting. This feature has been resolved, but is yet unreleased. See https://github.com/asciidoctor/asciidoctor/issues/1811.

**Comment by gdamore** [comment]
Thanks!  I'll close this since you've already addressed it.
