### ISSUE TITLE
BUG: interpreter fell through to end unexpectedly with comment in list item

### ISSUE THREAD

**Issue by virgo47** [asciidoctor/asciidoctor#2544]
I tried to put comment in list item like this:
```
* List item.
// TODO
Another sentence.
```

But this causes error:
```
Failed to load AsciiDoc document - BUG: interpreter fell through to end unexpectedly
```

I'm using AsciiDoctor in Gradle build with `org.asciidoctor:asciidoctor-gradle-plugin:1.5.6` and `org.jruby:jruby-complete:9.1.15.0`.

I tried added + sign:
```
* List item.
+
// TODO
Another sentence.
```

No luck. What works fine is putting the comment on another line:
```
* List item.
Another sentence.
// TODO
```

It works fine when it's not on the second line after the list item. Is this a bug or a feature? I can't find anything in the [manual](http://asciidoctor.org/docs/user-manual) about it.

**Comment by virgo47** [comment]
BTW: One more thing regarding usability of the error message itself. Would it be possible to include some indication where the problem that caused this "fall-through" started? Because I'm using AsciiDoc for around a week and this message is quite often when you try to author any bigger document with lots of bullets containing anything beyond a single paragraph. I'm asking here in case it's clear "not possible" (for some parser reason) so I don't bother creating another issue. :-)

**Comment by elextr** [comment]
Might be a regression, seems to work for me with 1.5.4

**Comment by virgo47** [comment]
I can't say easily, I use jcenter() where I can see only 1.5.3 and older, 1.5.6 and 1.5.7:
https://bintray.com/asciidoctor/maven/asciidoctor-gradle-plugin
I tried both 1.5.3 and 1.5.7 in addition to originally tried 1.5.6 and the result was the same.

**Comment by mojavelinux** [comment]
This message is not coming from Asciidoctor core. Perhaps this has something to do with the Gradle plugin. Please reopen there.
