### ISSUE TITLE
chapter-label is not used in xref

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor#2546]
Wrt. #858 I was trying to get a cross ref to a chapter number and title, but the \:chapter-label: is not used: I was trying to set it to the German word _Kapitel_ but the PDF still contains the word _chapter_:

``````
:chapter-label: Kapitel
:xrefstyle: full
``````

![image](https://user-images.githubusercontent.com/456000/35441394-a84a9498-02a3-11e8-92f2-37a38390f320.png)

**Comment by mojavelinux** [comment]
chapter-label is used for the section title itself. The attribute you're looking for is chapter-refsig. See http://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text

**Comment by ascheman** [comment]
Thanks! Wouldn't it be good to initialize :chapter-refsig: with :chapter-label:?

**Comment by mojavelinux** [comment]
We provide it that way in the language file. See https://github.com/asciidoctor/asciidoctor/blob/master/data/locale/attributes-de.adoc

Atm, you have to do the wiring where you define it.
