### ISSUE TITLE
When source block has subs="attributes", kotlin generics are turned into html tags

### ISSUE THREAD

**Issue by rahulsom** [asciidoctor/asciidoctor#2549]
Corresponding issue where this was seen - https://github.com/spekframework/spek/issues/361
Gist demonstrating problem - https://gist.github.com/rahulsom/6dc5c9bd934993b617b051498fb55a18

The workarounds are 
* Using `&lt;` and `&gt;` instead of `<` and `>` in the code, which would not be ideal.
* Not using `subs="attributes"` which limits functionality.

This was originally observed on gradle 4.4.1 + asciidoctor plugin 1.5.3.
This can also be reproduced with github's rendering of asciidoc.
Same happens with
```
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
You should almost never use the subs attributes alone on a literal block (literal, listing, source, etc). That essentially turns it into a passthrough block. What you probably meant to do is either prepend or append the attributes substitution.

prepend:
```
[subs=attributes+]
```

append

```
[subs=+attributes]
```

Which one you use depends on whether you want the content of the attribute escaped or not.

**Comment by mojavelinux** [comment]
For more information, see http://asciidoctor.org/docs/user-manual/#incremental-substitutions

**Comment by rahulsom** [comment]
Thanks @mojavelinux! That works.
