### ISSUE TITLE
Need mechanism to have list inside paragraph

### ISSUE THREAD

**Issue by MetroWind** [asciidoctor/asciidoctor#2551]
If I write

    p1
    
    * l1
    * l2
    
    p2

It generates roughly this structure:

    <p>p1</p>
    <ul><li>l1</li><li>l2</li></ul>
    <p>p2</p>

Do we have a way to express the following?

    <p>p1
    <ul><li>l1</li><li>l2</li></ul>
    p2</p>

The distinction is important in both structural and representational sense.

**Comment by elextr** [comment]
The blank line or the start of the next structural element after p1 terminates the paragraph by definition, so no.

I think to do so would require some extra syntax and to be sure that it is expressible in all output formats.

**Comment by Mogztter** [comment]
> According to the HTML 5.0 specification, a paragraph may contain phrasing content, which still does not include other grouping elements:
http://www.w3.org/TR/html5/grouping-content.html#the-p-element

So the following HTML is not valid:

```html
<p>p1
<ul><li>l1</li><li>l2</li></ul>
p2</p>
```



> The blank line or the start of the next structural element after p1 terminates the paragraph by definition, so no.

Indeed `<ul>` will terminate the first paragraph.

**Comment by MetroWind** [comment]
> So the following HTML is not valid

That's correct. What I meant is to have some indication that they belong to the same paragraph, like wrapping them in a `div`. The HTML 5 output wrap each paragraph in a `div` anyway, so it makes sense to have

    <div class="paragraph">
    <p>p1</p>
    <ul><li>l1</li><li>l2</li></ul>
    <p>p2</p>
    </div>

**Comment by mojavelinux** [comment]
> What I meant is to have some indication that they belong to the same paragraph

That's the purpose of an open block.

```
--
p1

* l1
* l2

p2
--
```

You can now style the group by adding styles to the open block container (just give it an ID or role so you can find it). For example, you can wrap the elements in a border.

IMO, no other structure makes sense in the context of AsciiDoc. Paragraphs and lists are separate blocks and changing that would challenge deep rooted assumptions in AsciiDoc.

**Comment by MetroWind** [comment]
I see. Although it's not as pretty as I'd have hoped, it works for me. Thanks!
