### ISSUE TITLE
Ampersand breaks email links

### ISSUE THREAD

**Issue by jerodg** [asciidoctor/asciidoctor#2553]
Ampersand breaks email links

According to [RFC 5322](https://tools.ietf.org/html/rfc5322#page-12 ) ampersand is an allowed character.

I've made several attempts at using escape characters and quotes; so far nothing has worked.

I get the same output using the javascript renderer in atom and the html renderer, however, the pdf renderer ends up with something slightly different.

Asciidoctor Code:
```
me&you@myemail.com

me{amp}you@myemail.com

me&amp;you@myemail.com

http://www.test.com/?='123'&test=34
```

Atom javascript renderer:
![ampersand_in_email_javascript](https://user-images.githubusercontent.com/2856163/35819756-a2a69610-0a71-11e8-9fd5-4bdc9095983b.png)

html renderer:
![ampersand_in_email_html](https://user-images.githubusercontent.com/2856163/35819734-939f3712-0a71-11e8-9dad-dcb7cdf4da4f.png)

pdf renderer:
![ampersand_in_email_pdf](https://user-images.githubusercontent.com/2856163/35819741-99190ab0-0a71-11e8-8389-994a01daaf10.png)

**Comment by elextr** [comment]
Unfortunately characters that are legal in emails (and other URLs) conflict with other Asciidoc markup, so they are excluded from the set of characters that are automatically parsed as part of the URL.  Not sure there is any simple solution to that.

The URL workarounds given in the manual don't seem to work for emails, so AFAICT the only current option is to pass through raw HTML

```
<a href="mailto:me&you@myemail.com">me&amp;you@myemail.com</a>
```

Not sure what to do for PDF.

**Comment by mojavelinux** [comment]
It seems like the regexp is too restrictive. Here's the regexp in question:

https://github.com/asciidoctor/asciidoctor/blob/30871d7a9c586d658e095078430b1707057a25e2/lib/asciidoctor.rb#L869

You can see from that what characters it's allowing.

Fortunately, the trusty inline pass macro helps us with a simpler solution:

```
mailto:pass:c[me&you@myemail.com][]
```

That's not pretty, but it works.

Let's see about getting `&` added as a valid e-mail character.

**Comment by mojavelinux** [comment]
Since special characters have already been escaped by the time we look for e-mail addresses, we have to allow character references. We could choose to allow named character references:

```
&;
```

or we could go all the way and support any character reference, since a number of character references resolve to glyph permissible in e-mail addresses.

```
&#;
```

That would look like:


```
InlineEmailRx = %r(([\\>:/])?#{CG_WORD}[#{CC_WORD}.+\-%&#;]*@#{CG_ALNUM}[#{CC_ALNUM}.-]*\.#{CG_ALPHA}{2,4}\b)
```

The goal is not to match every e-mail address possible since that would cause serious conflicts in the syntax. But it seems reasonable to allow character references in the name part.

**Comment by mojavelinux** [comment]
Technically, semi-colon is not a valid character, but unless we look for character references specifically, it's not possible to distinguish between a standalone semi-colon and one that is part of a character reference.

**Comment by mojavelinux** [comment]
On second thought, we may need to look for `&amp;` specifically.

**Comment by elextr** [comment]
Fortunately, the trusty inline pass macro helps us with a simpler solution:

mailto:pass:c[me&you@myemail.com][]

ahh, `mailto:pass:` one combination I didn't try :)

**Comment by mojavelinux** [comment]
Expanding the regexp even a little bit can break a lot of documents. I did some tests and it would be okay to allow `&amp;` anywhere after the first character, but not much more than that.

I submitted a PR with a proposed patch.

We can either accept this, or we can deal with this in documentation (or both). 

Btw, this is definitely something that #61 would help to address.
