### ISSUE TITLE
Invalid style for paragraph when brackets inside of block

### ISSUE THREAD

**Issue by nfrankel** [asciidoctor/asciidoctor#2554]
I'm using Asciidoctor along with Jekyll (but I believe this is not related).

When I want to display outputs (such as logs) containing brackets inside a block, I've got a warning. Here's an example:

```
....
[ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21,16]
  package javax.cache is not visible
[ERROR]   (package javax.cache is declared in the unnamed module, but module javax.cache does not read it)
....
```

It outputs:

```
asciidoctor: WARNING: <stdin>: line 66: invalid style for paragraph: ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21
asciidoctor: WARNING: <stdin>: line 219: invalid style for paragraph: INFO] Attaching agents: [
asciidoctor: WARNING: <stdin>: line 66: invalid style for paragraph: ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21
asciidoctor: WARNING: <stdin>: line 219: invalid style for paragraph: INFO] Attaching agents: [
asciidoctor: WARNING: <stdin>: line 66: invalid style for paragraph: ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21
asciidoctor: WARNING: <stdin>: line 219: invalid style for paragraph: INFO] Attaching agents: [
asciidoctor: WARNING: <stdin>: line 66: invalid style for paragraph: ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21
asciidoctor: WARNING: <stdin>: line 219: invalid style for paragraph: INFO] Attaching agents: [
```

I've tried with dots and dashes, to no avail. If it happened only once, that wouldn't be a problem, but I've got tons of them that clutters my log.

Help and hint appreciated. Thanks!

**Comment by mojavelinux** [comment]
Can you please show the relevant AsciiDoc source that is including that source block?

**Comment by nfrankel** [comment]
---
title: "Migrating a Spring Boot application to Java 9 - Modules"
tags: [Java 9, Spring Boot, modules, Jigsaw]
categories: Java
permalink: /migrating-to-java-9/2/
picture:
  src: assets/resources/migrating-to-java-9/java_9.jpeg
  width: 1580
  height: 690
  alt: "Java 9 Logo"
sourcecode:
  link: https://github.com/nfrankel/spring-petclinic/tree/java9-modules
gofurther:
  -
    url: https://docs.oracle.com/javase/9/migrate/toc.htm
    text: Migrating to JDK 9
  -
    url: https://blog.codefx.org/java/java-9-migration-guide/
    text: Java 9 Migration Guide
  -
    url: https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw
    text: Maven plugins compatibility with Jigsaw
---

Last week, I tried to link:/migrating-to-java-9/1/[make a Spring Boot app^] - the famous Pet Clinic, Java 9 compatible.
It was not easy.
I had to let go of a lot of features along the way.
And all in all, the only benefit I got was improvement of String memory management.

This week, I want to continue the migration by fully embracing the Java 9 module system.

== Configuring module meta-data

Module information in Java 9 is implemented through a `module-info.java` file.
The first step is to create such a file at the root of the source directory, with the module name:

[source,java]
----
module org.springframework.samples.petclinic {
}
----

The rest of the journey can be heaven or hell.
I'm fortunate to benefit from an IntelliJ IDEA license.
The IDE tells exactly what class it cannot read and a wizard lets you put it in the module file.
In the end, it looks like that:

[source,java]
----
module org.springframework.samples.petclinic {
    requires java.xml.bind;
    requires javax.transaction.api;
    requires validation.api;
    requires hibernate.jpa;
    requires hibernate.validator;
    requires spring.beans;
    requires spring.core;
    requires spring.context;
    requires spring.tx;
    requires spring.web;
    requires spring.webmvc;
    requires spring.data.commons;
    requires spring.data.jpa;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires cache.api;
}
----

Note that module configuration in the `maven-compiler-plugin` and `maven-surefire-plugin` can be removed.

=== Configuration the un-assisted way

If you happen to be in a less than ideal environment, the process is the following:

. Run `mvn clean test`
. Analyze the error in the log to get the offending package
. Locate the JAR of said package
. If the JAR is a module, add the module name to the list of required modules
. If not, compute the automatic module name, and add it to the list of requires modules

For example:

....
[ERROR] ~/spring-petclinic/src/main/java/org/springframework/samples/petclinic/system/CacheConfig.java:[21,16]
  package javax.cache is not visible
[ERROR]   (package javax.cache is declared in the unnamed module, but module javax.cache does not read it)
....

`javax.cache` is located in the `cache-api-1.0.0.jar`.
It's not a module since there's no `module-info` in the JAR.
The automatic module name is `cache.api`.
Write it as a `requires` in the module.
Rinse and repeat.

== ASM failure

Since the first part of this post, I've been made aware that https://twitter.com/ankinson/status/919826619044331520[Spring Boot 1.5^] won't be made Java 9-compatible.
Let's do it.

Bumping Spring Boot to 2.0.0.M5 requires some changes in the module dependencies:

* `hibernate.validator` to `org.hibernate.validator`
* `validation.api` to `java.validation`

And just when you think it might work:

....
Caused by: java.lang.RuntimeException
    at org.springframework.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
....

This issue has already been https://github.com/spring-projects/spring-boot/issues/10647[documented^].
At this point, explicitly declaring the main class resolves the issue.

[source,xml]
----
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <jvmArguments>--add-modules java.xml.bind</jvmArguments>
        <mainClass>org.springframework.samples.petclinic.PetClinicApplication</mainClass>
    </configuration>
    ...
</plugin>
----

== Javassist failure

The app is now ready to be tested with `mvn clean spring-boot:run`.
Unfortunately, a new exception comes our way:

....
2017-10-16 17:20:22.552  INFO 45661 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-10-16 17:20:22.561 ERROR 45661 --- [           main] o.s.boot.SpringApplication               :
 Application startup failed

org.springframework.beans.factory.BeanCreationException:
  Error creating bean with name 'entityManagerFactory' defined in class path resource
   [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]:
    Invocation of init method failed; nested exception is org.hibernate.boot.archive.spi.ArchiveException:
     Could not build ClassFile
....

A quick search redirects to https://stackoverflow.com/questions/27202939/could-not-build-classfile-archiveexception[an incompatibility] between Java 9 and Javassist.
Javassist is the culprit here.
The dependency is required Spring Data JPA, transitively via Hibernate.
To fix it, exclude the dependency, and add the latest version:

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
    <exclusions>
        <exclusion>
            <artifactId>javassist</artifactId>
            <groupId>org.javassist</groupId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.22.0-GA</version>
    <scope>runtime</scope>
</dependency>
----

Fortunately, versions are compatible - at least for our usage.

== It works!

We did it!
If you arrived at this point, you deserve a pat on the shoulder, a beer, or whatever you think you deserve.

Icing on the cake, the Dev Tools dependency can be re-added.

== Conclusion

Migrating to Java 9 requires using Jigsaw, whether you like it or not.
At the very least, it means a painful trial and error search-for-the-next-fix process *and* removing important steps in the build process.
While it's interesting for library/framework developers to add an additional layer of access control to their internal APIs, it's much less so for application ones.
At this stage, it's not worth to move to Java 9.

I hope to conduct this experiment again in some months and to notice an improvement in the situation.

**Comment by mojavelinux** [comment]
I tried exactly that source code in a Jekyll site with the AsciiDoc plugin and using Asciidoctor by itself and I don't see any warnings.

I think somewhere you are getting a block that is terminating prematurely. Asciidoctor does not parse AsciiDoc inside of a literal block. Therefore, the only way it can be treating `[ERROR]` as a paragraph style is if the content is falling outside of the literal block (due to mismatched boundaries).

**Comment by mojavelinux** [comment]
The problem is Jekyll excerpts. Here's what is being passed to Asciidoctor:

```
With the coming of Java 9, there is a lot of buzz on how to migrate applications to use the module system.
Unfortunately, most of the articles written focus on simple Hello world applications.
Or worse, regarding Spring applications, the sample app uses legacy practices - like XML for example.
This post aims to correct that by providing a step-to-step migration guide for a non-trivial modern Spring Boot application.
The sample app chosen to do that is the Spring Pet clinic.


There are basically 2 steps to use Java 9: first, be compatible then use the fully-fledged module system.
This post aims at the former, a future post will consider the later.


Bumping the Java version


Once JDK 9 is available on the target machine, the first move is to bump the java.version from 8 to 9 in the POM:



&lt;properties&gt;
    &lt;!-- Generic properties --&gt;
    &lt;java.version&gt;9&lt;/java.version&gt;
&lt;/propertie&gt;



Now, let&#8217;s mvn clean compile.




Cobertura&#8217;s failure


The first error along the way is the following:



[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean (default) on project spring-petclinic:
 Execution default of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean failed:
  Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved:
  Could not find artifact com.sun:tools:jar:0 at
   specified path /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/../lib/tools.jar -&gt; [Help 1]



...
```

Now you should be able to see where the issue is.

As I've said before, the design of excerpts in Jekyll is extremely broken (because plugins have no idea what format the excerpt is in). Nonetheless, if we want to find a solution, this issue will need to be filed in the jekyll-asciidoc project.

**Comment by mojavelinux** [comment]
Actually, it might be simpler than we think. You are using this call chain:

```
{{ post.content | strip_html | asciidocify | truncatewords: 33, "" }}...
```

You can't strip html, then pass to Asciidoctor. That's going to result in all sorts of broken.

**Comment by mojavelinux** [comment]
In other words, switch it around. strip_html after asciidocify.

**Comment by mojavelinux** [comment]
In fact, you don't even want to pass to asciidocify because post.content is already passed through Asciidoctor.

**Comment by mojavelinux** [comment]
(so this wasn't an excerpt thing...but you still have to be careful with excepts because they have a similar problem)

**Comment by nfrankel** [comment]
Dan, many many thanks for your time. I do really appreciate it a lot!

May I ask you one final thing? The problem is, beside setting the `--trace` option on the Jekyll command-line, I've no way to debug the stuff. Could you tell me how you pinpointed the problem?

**Comment by mojavelinux** [comment]
When you install the gems into the project, they all become available under .bundle/gems. I knew to look for the AsciiDoc plugin here:

.bundle/gems/ruby/2.4.0/gems/jekyll-asciidoc-2.1.0/lib/jekyll-asciidoc/converter.rb

Then I went to the line that calls Asciidoctor#convert and I added the following lines:

```ruby
if (@page_context[:data] || {})[:path] == '_posts/2017-10-22-migrating-spring-boot-application-java-9-2.adoc'
  IO.write("/tmp/debug-#{content.object_id}", content)
end
```

Jekyll is notoriously hard to debug because it calls back into itself an incredible number of times. The only way I know how to do it is to dump data. I'm sure if you searched you could get a debugger set up, but I only do that if initial probes don't work.

**Comment by nfrankel** [comment]
FYI, there were still some warnings, and I was able to remove them all but one after also adding excerpts as you mentioned.

**Comment by mojavelinux** [comment]
Yeah, there a limitations to applying `[source]` to a paragraph. It doesn't work exactly the same as an actual delimited block.

**Comment by nfrankel** [comment]
And you fixed my last warning... 🙇 🙇 🙇
Thanks!!!
