### ISSUE TITLE
Footer causes HTML validation to fail

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#2556]
See:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fasciidoctor.org%2Fdocs%2Fuser-manual%2F
"_Error: Element tbody not allowed as child of element table in this context_"

When I use `[options="footer"]` in a doc source, I notice the entire footer block (`<tfoot>...</tfoot>`) is placed before the `<tbody>` element (in the generated html file), which causes the validator to complain.

If I manually edit the html generated and place the footer block right before the `</table>` tag, the validator does not complain anymore, and the footer works normally, as expected.

In fact, the W3C's HTML5 specification says, about the `<tfoot>` element:
_"As a child of a table element, **after** any caption, colgroup, thead, tbody, and tr elements"_
http://w3c.github.io/html/single-page.html#elementdef-tfoot

I believe Asciidoctor should place it right before the `</table>` element, and not before the `<tbody>` element.

**Comment by mojavelinux** [comment]
Thanks for bringing this up. To my knowledge, this is a new requirement in HTML 5. In fact, HTML 5.0 says:

> As a child of a table element, after any caption, colgroup, and thead elements and before any tbody and tr elements
> — https://www.w3.org/TR/html50/tabular-data.html#the-tfoot-element

So it was changed in HTML 5.1.

But, the world turns!

I thought we needed that order to compute the table borders with CSS correctly, but it turns out we don't. Therefore, I think we can safely change this. It's still a good idea to check that all permutations of header, footer, and body still render correctly with borders. (And I know, we really need a style guide page for this).

**Comment by PauloFrancaLacerda** [comment]
> So it was changed in HTML 5.1.

The specification I quoted is titled "HTML 5.3 (5 February 2018)", but is not specific regarding the minor version that affected the fotter issue. Too bad.

**Comment by mojavelinux** [comment]
If everything goes smoothly, I'll target 1.5.7, which it slated for release fairly soon.

**Comment by PauloFrancaLacerda** [comment]
> So it was changed in HTML 5.1.

It seems you were right. I just found this:

> Changes since HTML 5.0 (HTML 5.1 2nd Edition):
> Features removed:
> **Disallow tfoot before tbody.**

https://www.w3.org/TR/html51/changes.html#features-removed

**Comment by mojavelinux** [comment]
Thanks for finding that!

**Comment by mojavelinux** [comment]
As it turns out, the inverted order was causing the rows to be out of order in the manpage output. With the pending fix, the rows are now in the correct order.

DocBook doesn't seem to care which order the thead, tbody, and tfoot are, so there's no impact to this change there.

**Comment by robotsnowfall** [comment]
Here's a working transform in case anyone finds themselves here.
```xslt
 <xsl:stylesheet version="3.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns="http://docbook.org/ns/docbook"
    exclude-result-prefixes="db">

    <xsl:mode on-no-match="shallow-copy"/>

    <xsl:template match="db:tgroup">
        <xsl:copy>
            <xsl:apply-templates select="@*, db:colspec, db:spanspec, db:thead, db:tfoot, db:tbody"/>
        </xsl:copy>          
    </xsl:template>
</xsl:stylesheet>
```
