### ISSUE TITLE
counters in variables not incremented with each use

### ISSUE THREAD

**Issue by janicesignalfx** [asciidoctor/asciidoctor#2559]
If I put a counter inside a variable, it is set once and not incremented with each instance of variable use throughout the document. I'm guessing this is some sort of order of precedence issue. It would be useful to have this functionality work.

**Comment by mojavelinux** [comment]
Can you please provide a minimum AsciiDoc document that demonstrates the issue for testing purposes?

**Comment by janicesignalfx** [comment]
Merged into set of issues in #2561
