### ISSUE TITLE
Upgrade to Font Awesome 4.7

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor#2569]
Please upgrade to Font Awesome 4.7 (which seems to be the latest of the version 4 series). Version 5 seems to bring some changes so it's probably not a drop-in replacement.

**Comment by thorstenkampe** [comment]
No CDN for version 5 yet: https://fontawesome.com/updates

**Comment by thorstenkampe** [comment]
https://fontawesome.com/get-started/web-fonts-with-css says the new CDN is https://use.fontawesome.com/releases/v5.0.6/css/all.css

**Comment by thorstenkampe** [comment]
The new icons seem to work with AsciiDoctor:

Old icons:
![Old icons](https://user-images.githubusercontent.com/475462/36354586-f8be2f4e-14d6-11e8-848e-baa43e396711.png)

New icons:
![New icons](https://user-images.githubusercontent.com/475462/36354591-0be51b3c-14d7-11e8-88ee-73d808167595.png)

**Comment by abelsromero** [comment]
I think we should keep an eye on the other features that use FontAwesome: Icons and experimental buttons & menus.

**Comment by Mogztter** [comment]
Is it possible to change the color of the tip icon ? The "inner" color should be transparent/white.

**Comment by mojavelinux** [comment]
The upgrade to 4.7 was resolved by c5b2c7d6527cd47853d1a4910ed10a42fbeb08ef (1.5.7). Let's discuss the upgrade to Font Awesome 5 in #2535.
