### ISSUE TITLE
How to refer to link?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2581]
Sometimes, I maybe show the same link many times in a document.I do not repeat the link again and again.

I think reference may avoid the repetition. **How to refer to a link?**

I search _refer_ in the user manual. But I did not find anything about this.

**Comment by Mogztter** [comment]
Hello @diguage 

Do you mean an external link like https://www.google.com/ ?
I'm not sure I understand your question but maybe you could use an attribute ?

```adoc
:uri-google: https://www.google.com/

This is a link to {uri-google}[google.com] and this is the {uri-google}[same link], {uri-google}[again] and  {uri-google}[again].
```

**Comment by diguage** [comment]
@Mogztter 
Yes. But I do not write the descirption (for example `google.com`, `same link`, `again ` ) again and again.

I think it should be like section title anchor:

```
I define a anchor:

[[my-anchor]]
== My Section Title

Then I can refer to the anchor:

<<my-anchor>>

It show like as follow:

link:#my-anchor[My Section Title]

// I can use `<<my-anchor>>` anywhere, it show the link and the section title. I do not repeat the link and the section title again and again.

```

**Comment by mojavelinux** [comment]
While I tend to only extract the URI in an attribute (my preference), you can put the whole link in the attribute.

```
:link-ecosia: https://ecosia.org[Ecosia]

I search using {link-ecosia}.
```

There may be times when you need to surround the attribute value in a pass macro to have fine-grained control over substitution order. In the case I gave, it's not necessary.

**Comment by mojavelinux** [comment]
@diguage Has this answered your question? Do you think we should include this in the docs?

**Comment by diguage** [comment]
It is a tradeoff way. Shoud it have a better way?

**Comment by mojavelinux** [comment]
Why do you say that's a trade off? Is there something else you had in mind?

**Comment by diguage** [comment]
**Sorry.  I have just thought Markdown had a better way. But I tried it. It is same to the Asciidoctor `:link-ecosia:` example.** 

I think we should include this in the docs. Maybe others have the same problem.

----

Markdown deal with the link as following:

```
This is a [Asciidoctor][1].

[1]: http://asciidoctor.org/ "Asciidocotor"
```

The converted document is as following:

This is a [Asciidoctor][1].

[1]: http://asciidoctor.org/ "Asciidocotor"

**Comment by mojavelinux** [comment]
As it turns out, this is already covered in the documentation...or at least in the quick reference.

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#attributes-and-substitutions

I'll try to find a place the right place for it in the user manual as well.

**Comment by mojavelinux** [comment]
Keep in mind, you can use numbers as attributes in Asciidoctor. So you could simplify it to:

```
:1: https://asciidoctor.org[Asciidoctor]

You can't go wrong with {1}.
```

Even shorter than Markdown :wink:

**Comment by mojavelinux** [comment]
I added it to this section.

https://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document

I realize that section is too lengthy. We're embarking on an overhaul of the docs after the release of Antora 1.0, so we'll start addressing these types of problems then.

**Comment by lfrancke** [comment]
I just stumbled across this question as well and I believe that your answer solves the issue, at least it did for me, thank you. I'm not the original creator but I believe this issue can be closed.

**Comment by mojavelinux** [comment]
Excellent. I'll go ahead and close. If more information is needed, don't hesitate to file a new issue with a follow-up question.

**Comment by diguage** [comment]
@mojavelinux 
It is greate. Thank you.

**Comment by marcelocra** [comment]
Hey folks! I was looking for named links in the [**Links**](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links) part of the docs. Perhaps it would help future users if there was a quick mention of if there (maybe a NOTE, pointing to the attributes section?).

Thanks!

**Comment by mojavelinux** [comment]
If you'd like to propose an update to the documentation at https://github.com/asciidoctor/asciidoctor.org, I'd be happy to review it.

**Comment by astubbs** [comment]
Ah - i see one of the big differences from Markdown, is that asciidoc the variables have to be defined before they're used? This prevents the mice markdown style of having all the links defined as a references section at the bottom of the document. Have I got that right? Any options here?

**Comment by mojavelinux** [comment]
Please direct usage questions to the community chat at https://asciidoctor.zulipchat.com. Thanks.

**Comment by astubbs** [comment]
> Please direct usage questions to the community chat at https://asciidoctor.zulipchat.com. Thanks.

It’s not a usage question. It’s feedback/suggestion around the technical limitations of the current implementation - which appears to restrict reference links as described above, from being listed at the bottom of a document as opposed to the top.

**Comment by mojavelinux** [comment]
You're commenting on a closed issue to expand the original question about how you might be able to accomplish something in AsciiDoc. That's a usage question. Please respect my request and direct it to the community chat. Thank you.
