### ISSUE TITLE
How to escape things like double hyphen inside backticks for inline code?

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#2582]
I'm using backticks for inline code, but now I discovered that it is not really inline code, but rather monospace :-(

Can I do better than the ugly:

```
`++a--b++`
```

?

Maybe add this to the quick reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

```
$ # me likes
$ echo '`a--b`' | asciidoc -s -
<div class="paragraph"><p><code>a--b</code></p></div>
$ # me no likes
$ echo '`a--b`' | asciidoctor -s -
<div class="paragraph">
<p><code>a&#8212;&#8203;b</code></p>
</div>
$ echo '`++a--b++`' | asciidoctor -s -
<div class="paragraph">
<p><code>a--b</code></p>
</div>
$ asciidoc --version
asciidoc 8.6.9
$ asciidoctor --version
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
> I'm using backticks for inline code, but now I discovered that it is not really inline code, but rather monospace

That's absolutely correct. Backticks apply monospace formatting. To have literal text, you need to combine it with passthrough, which are pluses (plus for passthrough). You only need a single pair, though.

```
`+a--b+`
```

It's also possible to escape the ligature:

```
`a\--b`
```

In general, you'll find that the first form is more reliable. In the long term, we'll like to improve the behavior of backslash escaping.

If you want to retain the behavior of AsciiDoc Python (legacy mode), you just add the following to your document header:

```
:compat-mode:
```

More information can be found on this page: http://asciidoctor.org/docs/migration/#compat-mode

**Comment by cirosantilli** [comment]
Thanks.

**Comment by mojavelinux** [comment]
Example updated. See https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#escaping-text

**Comment by mojavelinux** [comment]
That area of the quick ref still needs work, but hopefully it's a bit clearer now.

**Comment by mojavelinux** [comment]
(It make take a minute to be available).

**Comment by cirosantilli** [comment]
I'd recommend adding it to the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code sections instead, I think this is where coders will look first. But good that an example was added.

**Comment by mojavelinux** [comment]
Good point! I'll move it there.
