### ISSUE TITLE
Dangling semicolon after em dash in manpage

### ISSUE THREAD

**Issue by commonquail** [asciidoctor/asciidoctor#2604]
The manpage backend leaves a dangling semicolon after the (rendered) em dash character. I am *pretty sure* this is because of [a funky-looking regex in the backend's em dash entity](https://github.com/asciidoctor/asciidoctor/blob/v1.5.6.1/lib/asciidoctor/converter/manpage.rb#L21) that appears to be a regression from commit abda04c ("revise manpage backend", 2015-05-09) -- note how the first entity's semicolon is contained in the optional capture group:

```ruby
 EmDashCharRefRx = /&#8212(?:;&#8203;)?/
```

For instance, the sequence

```adoc
= foo(1)
:man manual: FOO
:man source: FOO

== NAME

foo - bars

== SYNOPSIS

*foo* <file>

== DESCRIPTION

*foo* -- bars file...
```

compiled with

```sh
$ asciidoctor -b manpage -d manpage foo.1.adoc
```

yields

```roff
'\" <snip>
.TH "FOO" "1" "2018-03-12" "FOO" "FOO"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
foo \- bars
.SH "SYNOPSIS"
.sp
\fBfoo\fP <file>
.SH "DESCRIPTION"
.sp
\fBfoo\fP \(em; bars file...
```

The sequence `\(em;` should have been just `\(em`, just like the ellipsis entity was completely consumed.

```sh
~ $ asciidoctor --version
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by commonquail** [comment]
... though apparently only when the `--` is surrounded by spaces. `foo--bars` gives `\fBfoo\fP\(embars`.

**Comment by mojavelinux** [comment]
Nice catch! I'll check it out and make sure there wasn't some reason it was like this...but it sure looks like a typo to me.
