### ISSUE TITLE
rel="nofollow" is ignored

### ISSUE THREAD

**Issue by vieiro** [asciidoctor/asciidoctor#2605]
Hi,
I'm trying to generate an HTML link with the rel="nofollow" attribute using :linkattrs:, like so:

    = Hello
    :linkattrs:
    
    link:https://www.google.com[Hello, rel="nofollow"]

But the resulting HTML output ignores this "rel" attribute. The "nofollow" is handy in some situations, it would be a nice enhancement.

I'm using:
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

**Comment by mojavelinux** [comment]
I think we should follow what we did for noopener and make it an option. For example:

```
https://www.google.com[Hello,opts=nofollow]
```

wdyt?

**Comment by vieiro** [comment]
That would be great!

**Comment by mojavelinux** [comment]
PR now available! See #2692
