### ISSUE TITLE
Delegate include target resolution to method that can be overridden in Asciidoctor.js

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2610]
As a follow-up to #2599 and #2601, delegate the logic of resolving the include target to a method provided by Asciidoctor.js. Doing so allows the implementation to be managed in the Asciidoctor.js code base, thus allowing any changes to be tested immediately.

Here's the proposed API, which will be a member method on the PreprocessorReader class.

```rb
# An internal contract with Asciidoctor.js to resolve the target of an include when
# using the xmlhttprequest IO module. It must return a tuple containing the resolved
# (absolute) path and the path relative to the root document. Alternately, it can return
# a boolean to halt processing, which is used as the return value of the calling method.
def resolve_include_target_xmlhttprequest target
  ...
end
```

**OPEN QUESTION:** Should we use the term `browser` instead of `xmlhttprequest`? (i.e., `resolve_include_target_browser`)

The method can assume that attribute references in the target value have already been resolved.

The method is expected to return a tuple with the following values:

* inc_path - the resolved include path, which will later be passed to the top-level open function.
* relpath - the relative path of the target starting from the directory of the root document (i.e., root-relative)

If the method wants to halt processing of the include (for example, after replacing it with a link), it should instead return a boolean value.

**Comment by mojavelinux** [comment]
@Mogztter The tough question is whether to do this for 1.5.6.2 or wait until 1.5.7. The benefit of doing it for 1.5.6.2 is that you can move the code to Asciidoctor.js now and not have to juggle different needs for 1.5.6.x and 1.5.7. But I'm interested to hear from you whether you think that is easier or harder.

**Comment by mojavelinux** [comment]
This method will need to use instance variables (internal) and methods (public) from PreprocessorReader. Therefore, we'll have to be careful not to change these members in the future without coordinating the change with Asciidoctor.js. I'll note in the call to `resolve_include_target_xmlhttprequest` what members are likely used.

**Comment by mojavelinux** [comment]
This method is intentionally narrowly scoped. It's not the same as #571, which will allow the method / extension to return an IO object. Instead, this method is just an agreement with Asciidoctor.js to provide the logic for resolving an include when using the xmlhttprequest IO module, thus allowing the code to be tested immediately.

**Comment by Mogztter** [comment]
> OPEN QUESTION: Should we use the term browser instead of xmlhttprequest? (i.e., resolve_include_target_browser)

I think `resolve_include_target_browser` is a better and more accurate name. (XMLHttpRequest is an implementation detail, what we want is to resolve the target in a browser environment).

But shouldn't we override a method `resolve_include_target` ?

```ruby
    # ...
    elsif (abs_maxdepth = @maxdepth[:abs]) > 0
      if @include_stack.size >= abs_maxdepth
        warn %(asciidoctor: ERROR: #{line_info}: maximum include depth of #{@maxdepth[:rel]} exceeded)
        return
      else 
        inc_path, rel_path = resolve_include_target target
        return replace_next_line %(link:#{target}[]) if inc_path # the first argument can be a boolean
      end
      # ...  
```

The default implementation would be:

https://github.com/asciidoctor/asciidoctor/blob/ecd9bc7627252e4031e190d98de9913ab3ff3021/lib/asciidoctor/reader.rb#L873-L896

And the Asciidoctor.js implementation (in a browser environment) would be:

https://github.com/asciidoctor/asciidoctor/blob/ecd9bc7627252e4031e190d98de9913ab3ff3021/lib/asciidoctor/reader.rb#L838-L872


> The tough question is whether to do this for 1.5.6.2 or wait until 1.5.7. The benefit of doing it for 1.5.6.2 is that you can move the code to Asciidoctor.js now and not have to juggle different needs for 1.5.6.x and 1.5.7. But I'm interested to hear from you whether you think that is easier or harder.

In my opinion, it's better to wait until 1.5.7.
Asciidoctor.js 1.5.6 already contains a *lot* of changes. Moreover, once 1.5.6 "final" will be released, I will create a branch and master will target 1.5.7 (so the transition should be easy).

**Comment by mojavelinux** [comment]
> But shouldn't we override a method resolve_include_target ?

On a second look, I agree. This could be done rather easily. I was trying to isolate the change to the Asciidoctor.js case, but it really makes more sense just to move all the cases to their own method.

So we agree that we stick with this change for 1.5.7? That would mean the v1.5.6.x branch is ready for release then.

**Comment by mojavelinux** [comment]
Yep, I coordinate w/ you before releasing anything.

**Comment by mojavelinux** [comment]
I managed to get the proposed method extracted. I want to have a closer look at it tomorrow, but we might reconsider it for 1.5.6.2 since we know we want to take this step anyway. Might as well do it while it's fresh. Have a look and see what you think. #2613.

**Comment by mojavelinux** [comment]
Should the method be named `resolve_include_path` instead of `resolve_include_target`? I'm kind of leaning towards that change.

**Comment by Mogztter** [comment]
That's nice, the code looks simpler!

> Should the method be named resolve_include_path instead of resolve_include_target? I'm kind of leaning towards that change.

Indeed, `target` is vague, I vote for `resolve_include_path`

**Comment by Mogztter** [comment]
> I managed to get the proposed method extracted. I want to have a closer look at it tomorrow, but we might reconsider it for 1.5.6.2 since we know we want to take this step anyway. Might as well do it while it's fresh. Have a look and see what you think. #2613.

I don't know why but when you first asked I thought that we will have to rewrite this method in JavaScript but now I realize that we just have to copy a Ruby method... so I think we can do it now.

**Comment by mojavelinux** [comment]
> Indeed, target is vague, I vote for resolve_include_path

Great. I'll update it then.
