### ISSUE TITLE
Removing lead paragraph role from sections with one paragraph.

### ISSUE THREAD

**Issue by janicesignalfx** [asciidoctor/asciidoctor#2624]
It appears that any time a section has only a single paragraph that paragraph is automatically assigned the lead paragraph role and presented in a different font. Is there some way to turn this off?

**Comment by mojavelinux** [comment]
The lead role is not added automatically to any paragraph. The default stylesheet just happens to apply the same styles as the lead role to the first paragraph of the preamble. It does not style any other paragraph this way by default.

You can reverse this behavior using a custom stylesheet.

I do have one idea, though. If you apply a custom role to this paragraph, then it implicitly disables this behavior. That way, it will work only in the default scenario. I think that's a good compromise.

**Comment by mojavelinux** [comment]
@janicesignalfx What do you think about the proposed solution?

**Comment by janicesignalfx** [comment]
Do I need to do anything with this role to make it work? If I can I just add something like [.onlyPara] without doing anything else then I think that's fine.

**Comment by mojavelinux** [comment]
Nope. Just declaring it will work. I might even suggest [.nolead].

**Comment by janicesignalfx** [comment]
Sounds good

**Comment by Buzzardo** [comment]
The other way to do it is to ensure that there's more than one paragraph there. I just did that to a document, and it worked.

**Comment by john-cj** [comment]
Personally, I would be fine to *enable* leading instead of *disabling* it.

When you write some document, the leading is disabled. Then, if you need it, you add [.lead] to the appropriate paragraph. Strict and easy way.

```
= Title

[.lead]
This paragraph will be lead because I want it.

This is normal paragraph.

== Heading
```

**Comment by mojavelinux** [comment]
We've already discussed this and it's not being changed.
