### ISSUE TITLE
Obtain unique node id

### ISSUE THREAD

**Issue by s-leroux** [asciidoctor/asciidoctor#2629]
For some HTML output, I need to generate a (unique) `id` for code blocks:

```
<pre id="XXXXXX">
...
</pre>
```

Since I will convert the document using my `asciidoctor.js-pug` template converter it is not hard to write a template for that. But before re-inventing the wheel, I wonder if there already something in the Asciidoctor API that can assign or generate automagically a new unique id for a node?

**Comment by mojavelinux** [comment]
There is no such facility for blocks in general. There is an ID generation facility for section titles, but that is based on the title text.

**Comment by s-leroux** [comment]
Thanks for the clarification Dan.
