### ISSUE TITLE
How to provide translacted versions of the syntax quick reference

### ISSUE THREAD

**Issue by Siltaar** [asciidoctor/asciidoctor#2631]
Hi,

I would like to translate the quick reference. I would like to know how to provide it to AsciiDoctor project to get it online on the official website.

Should I provide a set of .fr.adoc files ? Did I missed an official invite to translate the documents ?

**Comment by Mogztter** [comment]
Hello @Siltaar,

> I would like to translate the quick reference. 

That's a good idea :+1: 

> I would like to know how to provide it to AsciiDoctor project to get it online on the official website.

Could you please open an issue here: https://github.com/asciidoctor/asciidoctor.org

> Should I provide a set of .fr.adoc files ? Did I missed an official invite to translate the documents ?

I think so, then we will add a link to the translated document. We could add a link at the top of the https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

```
Translations of this document are available in the following languages:

*  link:asciidoc-syntax-quick-reference-fr/[Français]
```

**Comment by mojavelinux** [comment]
Let's follow-up on the proposed PR. https://github.com/asciidoctor/asciidoctor.org/pull/806
