### ISSUE TITLE
using included content varying only by heading level

### ISSUE THREAD

**Issue by janicesignalfx** [asciidoctor/asciidoctor#2634]
I have a blurb that's being reused in a variety of places that starts with a heading. It turns out the heading level can vary by one depending on where it's used. Once I realized this, I tried the following structure:

```
tag::content[]
{heading-level} heading

paragraph
end::content[]
```

with :heading-level: set before each use. This resulted in the heading level being displayed in the output (i.e seeing "=== heading" rather than "heading" as a styled heading)

So clearly the order of evaluation is not my friend here. Is there another way I can define a single blurb with varying header levels?

**Comment by mojavelinux** [comment]
You should use leveloffset to adjust the heading level (and leave the source as is).

You'd define the include file as follows:

```
//tag::content[]
== Heading in Include File

content
//end::content[]
```

Then you'd include it like this:

```
include::file-to-include.adoc[tag=content,leveloffset=+1]
```

To know how much leveloffset to add or remove, you'd need to follow some soft of standard level convention in your include files.

I strongly recommend against using attribute references in place of structural syntax. That's not a standard AsciiDoc practice.

**Comment by janicesignalfx** [comment]
Thanks! That's exactly what I needed.

**Comment by mojavelinux** [comment]
\o/

**Comment by mojavelinux** [comment]
Here's more info:

https://asciidoctor.org/docs/user-manual/#include-partitioning
