### ISSUE TITLE
delimiters for admonitions

### ISSUE THREAD

**Issue by janicesignalfx** [asciidoctor/asciidoctor#2638]
This table in the user manual indicates that you can use any delimiter with admonitions:

https://asciidoctor.org/docs/user-manual/#built-in-blocks-summary

However, they only seem to work for me with `====` - most other delimiter types give an error then display the enclosed content without the admonition in the format associated with the delimiter chosen.

I'm not sure if this is a product bug or a doc bug so filing it here.

**Comment by mojavelinux** [comment]
You're absolutely correct. I've updated the docs. The preferred delimiter is the example block delimiter, though open block is also supported (which is true for all delimited blocks).
