### ISSUE TITLE
Email address in <> are rendered twice for the man pages

### ISSUE THREAD

**Issue by aerostitch** [asciidoctor/asciidoctor#2654]
Hi,

In https://bugs.debian.org/895188 a user had an issue where a string like: `User name <user@example.com>` was rendered as `User name <user@example.com <user@example.com>>` when using the manpage backend.

While I understand the correct syntax should be `mailto:user@example.com[User name]`, I was wondering if that specific transformation had a real application or was a bug.

Thanks for your help
Joseph

**Comment by mojavelinux** [comment]
> I understand the correct syntax should be mailto:user@example.com[User name]

Not necessarily. The reported syntax should work. We're likely just missing a test case here.

**Comment by mojavelinux** [comment]
Thanks for reporting! As it turns out, there's an ordering problem in the logic that's causing the check for the duplicate to fail.
