### ISSUE TITLE
Warn if footnote reference can't be resolved

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2669]
If a footnote reference cannot be resolved, log a warning message.

Example:

```
notable text.footnote:fn1[footnote text].

more notable text.footnote:foo[]
```

Currently, the invalid reference is emphasized in the converted document using red text. However, the author never sees a warning about it. This can make it hard to find in a large document set.

A footnote reference must be defined before it is used.

**Comment by elextr** [comment]
> A footnote reference must be defined before it is used.

This is fairly easy to violate when reorganising a document, so a nice noisy warning is important.

**Comment by mojavelinux** [comment]
To be consistent with the xref warnings, the message will read:

```
invalid footnote reference: name
```
