### ISSUE TITLE
Using subdirectories in images folder

### ISSUE THREAD

**Issue by jcayouette** [asciidoctor/asciidoctor#2704]
We require the following structure including subdirs due to our tooling:

```
|--project/images
|----------------/png/example.png
|----------------/svg/example.svg
|----------------/jpg/example.jpg
...
```

Is there a way to do this via :imagesdir: ?
If not can you provide an alternative? 

"I am assuming you could setup ifdef for each folder based on image extension?" However this is kind of ugly :)

Thank you!

**Comment by mojavelinux** [comment]
This is not a feature that the AsciiDoc language offers. You might be able to forgo the use of `imagesdir` and use your own attribute reference per image type. Or you could write a tree processor extension that rewrites the target of images after the document is loaded.
