### ISSUE TITLE
thesis template for asciidoc(tor)

### ISSUE THREAD

**Issue by alperyilmaz** [asciidoctor/asciidoctor#2718]
Hi,

I checked online for templates to write thesis (PhD, M.S) but couldn't find one. Can anybody point to existing asciidoc(tor) templates/config files used by universities or schools?

I'm willing to offer my university to provide asciidoctor template for its students and it looks quite difficult to write config file from scratch. If I can find a working example, I can modify it and show my university that Asciidoctor can help student save time writing their thesis.

**Comment by mojavelinux** [comment]
To reach a broader audience, you may want to consider cross posting to the discussion list. http://discuss.asciidoctor.org

**Comment by mojavelinux** [comment]
For anyone following this question, please refer to the thread on the mailinglist.

http://discuss.asciidoctor.org/thesis-template-td6281.html

**Comment by zebreus** [comment]
I recently wrote my thesis with asciidoctor-web-pdf. If anyone is interested in the thesis template, here is the link: https://github.com/zebreus/thesis-template

**Comment by mojavelinux** [comment]
Cool! I encourage you to share this in the project chat at https://chat.asciidoctor.org as that is where most people are looking.
