### ISSUE TITLE
Formatting seems to take precedence over inline anchor parsing

### ISSUE THREAD

**Issue by minad** [asciidoctor/asciidoctor#2746]
I am using xslt to import doxygen to asciidoctor. During that import long weird inline anchors are created at list item beginnings of the form `[[codedoc_structOptionDesc_1_1__anonymous___1_1ulongRange_1ae878e5331afe4d5a4d1401e007640334]]`. However the anchor is not parsed as anchor, but as emphasized text due to the underscores.

PS: Maybe my doxygen -> asciidoc importer could be interesting as a plugin. It basically adds Sphinx-like capabilities to asciidoctor.

**Comment by mojavelinux** [comment]
Double underscore has an extremely high precedence, so using it in AsciiDoc for anything other than italic text is hazardous. This is another example of a problem that #61 address as it can limit what substitutions happen in a macro (similar to double underscores in link URLs).

**Comment by minad** [comment]
Hmm, I think it would be nice to change in cases like this (Internal ids etc). However I have no idea how hard it is to change that. I just took a quick look at the regexes in the parser, but didn't see where the `__` parsing happened. Is a parser rewrite still planned, using a grammer based approach (#61)?

Maybe as a short term solution - is it safe to use `-` instead of `_` in ids, even if they occur multiple times? It would be easy to replace that in the xslt.

**Comment by mojavelinux** [comment]
Yes, the inline parser will be a key focus of the upcoming 2.x series. It's likely going to be a hybrid approach. I'm not sure yet. How it's done isn't as important as what rules it follows.

> Maybe as a short term solution - is it safe to use - instead of _ in ids, even if they occur multiple times? 

Unfortunately, repeating hyphens also get replaced. The safest thing to do is remove the repeating symbols. Single characters are not replaced in the middle of a word (except for single quote).

**Comment by minad** [comment]
Ok, thanks. I see what I can do. Doing arbitrary replacements in xslt is unfortunately notoriously inconvenient, no regex support etc ;)

**Comment by mojavelinux** [comment]
I agree it would be nice if there were protected areas of the inline syntax that didn't get replaced by default (without having to use the pass macro). But the current regexp based approach doesn't allow for that (as it's completely void of context). That's why I suggested #61. We have to change the model.

**Comment by mojavelinux** [comment]
That's one of the main reasons I stay away from XSL.

**Comment by minad** [comment]
Well it is not that bad. I think it is still the best if you have to go with xml as in the case of doxygen. There is the exslt str:replace extension in xsltproc/libxml. And if you don't bother you could go with a java xslt 2.0 solution. My first nicely looking import was only like 100 lines of xslt, which I have to admit has swollen to 500 lines now to handle more doxygen commands etc.
