### ISSUE TITLE
Manpage backend: incorrect output for links with monospace text

### ISSUE THREAD

**Issue by alecov** [asciidoctor/asciidoctor#2751]
Links containing monospace text don't render properly when using the manpage backend.

For example, the following:
```
link:test[`text text`]
```

produces:
```
.URL "test" "\f[CR" "text"
text\fP]
```

Instead, it should produce:
```
.URL "test" "\f[CRtext text\fP]" ""
```

**Comment by mojavelinux** [comment]
The problem here is that there's a square bracket in the formatting mark that turns on monospaced text, which conflicts with the AsciiDoc macro. Fortunately, there's another way to express this. We can use `\f(CR` instead, which will not cause a conflict.
