### ISSUE TITLE
Write Windows installation instructions

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor#2762]
Add a page to the documentation explaining how to install Asciidoctor on Windows using Chocolatey.

**Comment by PauloFrancaLacerda** [comment]
Very useful.
Having Asciidoc installed on Windows 7 was a real nightmare to me, since I'm not familiar to any platforms other than Windows. Eventually, I managed to get Ruby installed via [Ruby Installer](https://rubyinstaller.org), but still had to struggle with some batch files and such.
After all, I still am not confident about the steps I've taken to make it work.

**Comment by mojavelinux** [comment]
I think the best way to install commandline programs on Windows is [Chocolatey](https://chocolatey.org/packages/ruby). In that case, it can be reduced to two commands (after installing Chocolately itself)

```
choco install ruby
gem install asciidoctor
```

Under the covers, choco actually uses Ruby Installer, but all the details are handled for you.

**Comment by mojavelinux** [comment]
There's also an AsciidoctorJ package for Windows. The upside is that you can bypass the installation of Ruby. The downside is that Asciidoctor doesn't start as fast that way.

```
choco install asciidoctorj
```

That package is actually coming directly out of the AsciidoctorJ build, so it's guaranteed to be updated (assuming the AsciidoctorJ release process is configured correctly).

**Comment by xmaxrayx** [comment]
worst part is i waste my time with that RvM thing but I skip it  because `curl` command didn't work.

**Comment by mojavelinux** [comment]
This is already covered in the docs:

* https://docs.asciidoctor.org/asciidoctor/latest/install/windows/
* https://docs.asciidoctor.org/asciidoctor/latest/install/ruby-packaging/

I have corrected the mentions of RVM to make it clear it is only when using Linux (and optionally when using macOS).
