### ISSUE TITLE
Require at least one character in the term position of a description list

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2766]
Currently, the following document is interpreted as a description list with a single entry containing an empty term and description:

```
::
```

This parsing is too greedy.

The parser should enforce that at least one character is present in the term position for it to be parsed as a description list entry:

```
t::
```

If the author's intent is to create an entry with an empty term, it would be necessary to use the `{blank}` attribute reference:

```
{blank}::
```

This change is a departure from AsciiDoc Python, but justifiably so.

**Comment by mojavelinux** [comment]
Without introducing some new rules, this turns out to be much more difficult than anticipated. The problem is that the colon-based delimiter has a variable length. In our attempt to exclude the following:

```
::
```

We end up still allowing the following (where `:` is the term):

```
:::
```

This also goes for an indented delimiter (though there is a way to exclude this case):

```
 ::
```

The rule we'd need to introduce (which is already partially enforced for nested description lists), is that a list term cannot end in a colon unless that colon is followed by a space. For example, if the term is `foobar:`, it would have to be typed as:

```
foobar: ::
```

instead of

```
foobar:::
```

I think this is a pretty reasonable requirement as even a human has difficulty parsing the latter.

We need to be able to differentiate between the term and the delimiter.

**Comment by mojavelinux** [comment]
There's also a question about whether the parser should find the first delimiter or the last delimiter on the line. Consider the following:

```
foo:: bar:: baz
```

AsciiDoc Python uses the second delimiter whereas Asciidoctor uses the first. Most syntax highlighting rules for AsciiDoc match the first delimiter, which seems the most intuitive. Therefore, I think we should solidify that rule.

**Comment by elextr** [comment]
Agree the first is the logical end of the term.

**Comment by mojavelinux** [comment]
> The rule we'd need to introduce (which is already partially enforced for nested description lists), is that a list term cannot end in a colon unless that colon is followed by a space.

This rule is surprisingly effective. Only one test in the Asciidoctor suite failed, and it was deliberately checking for a longer run of colons than the longest delimiter.

Btw, the parsing for the term be as follows:

```
([^ \t].*?[^:]|[^ \t:])
```

That basically says that the term must either:

a) start with a non-space character and have any number of characters that don't end in colon
b) not be a space or colon

(we don't care about the semicolon since that variant of the delimiter has a fixed length and can only be interpreted one way).

**Comment by mojavelinux** [comment]
Down the road, I'd like to consider the possibility of always requiring a space before the delimiter...but that would be a major breaking change...so that would be unidoc material.

**Comment by mojavelinux** [comment]
I was able to figure out how to do this with basically no change in behavior. There may be edge case we aren't considering, but they would be extremely rare (and I can't think of what they are).
