### ISSUE TITLE
:toc: macro does not move toc

### ISSUE THREAD

**Issue by brownierin** [asciidoctor/asciidoctor#2768]
I'm using both asciidoctor and asciidoctor PDF to create a report. When I specify :toc: macro and place my toc::[] in a custom spot, the toc still appears in the auto field in both asciidoctor and asciidoctor-pdf.

Here is a cleaned up version of my code.

```
= Title of report
:toc: macro
**Field**: Example
**Field**: Example
**Field**: Example
**Field**: Example

<<<

toc::[]

== Section
etc
```

Instead of placing the toc below all the fields and on a new page, the toc is still below the title of the report in the generated HTML file, and in the PDF, it's on the second page of the document. 

I didn't see a bug report for this already.

**Comment by rockyallen** [comment]
toc is a header attribute which means it only has the desired effect when it appears in the header:
https://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document
Put the :toc: line above the document title and it should work.

**Comment by brownierin** [comment]
I tried both of these:

```
= Title of report
:toc: macro

**Field**: Example

<<<

toc::[]
```

```
:toc: macro
= Title of report

**Field**: Example

<<<

toc::[]
```

And neither move the toc in the HTML output. It's still directly under my primary header.

**Comment by mojavelinux** [comment]
How are you invoking Asciidoctor? Is perhaps the toc attribute being overridden by the API or CLI?

You can check the value of the `toc` attribute by adding the following to the body of the document.

```
{toc}
```

**Comment by mojavelinux** [comment]
Did those suggestions help?

**Comment by mojavelinux** [comment]
It sounds like we are talking about Asciidoctor PDF. In that case, see https://github.com/asciidoctor/asciidoctor-pdf/issues/233.
