### ISSUE TITLE
Garbled time on footer

### ISSUE THREAD

**Issue by kikijiki** [asciidoctor/asciidoctor#2770]
I'm on a Japanese Windows 7 machine.

Text is fine but the time in the footer is encoded in Shift-JIS while the document is UTF-8.  
The result is this garbled text:

```
Last updated 2018-05-10 14:29:43 ���� (�W����) 
```

Expected text:
```
Last updated 2018-05-10 14:29:43 東京 (標準時) 
```

**Comment by mojavelinux** [comment]
As I've recently learned, on Windows, the timezone is written out longhand instead of a shorthand code (like MDT). The encoding Ruby uses for this string is incorrect. This is a bug in Ruby. See https://bugs.ruby-lang.org/issues/9414

We may be able to work around this bug by re-encoding the string to UTF-8. I'd have to do some testing.

**Comment by kikijiki** [comment]
Found a temporary workaround, for my case at least.

If I do `set TZ=JST-9` before calling asciidoctor the time zone becomes "JST". 

As explained here: https://ledsun.hatenablog.com/entry/2013/01/19/124236

**Comment by mojavelinux** [comment]
Thanks for the tip! If I'm unable to find a way around it in the code, we'll just document this solution.

**Comment by mojavelinux** [comment]
I absolutely cannot make sense of encoding on Windows. I get how it works in theory, but that just doesn't translate to practice. But at least I understand the nature of this problem. The string that gets used for `%Z` is OS dependent, and not guaranteed to be encoded in UTF-8. That would mean it has to be transcoded.

We can take one of two approaches here. We can heed the warning in the Ruby documentation and use `%z` instead of `%Z`. That would mean the timezone would display as an offset instead of a timezone code. However, given that different operating systems display the timezone differently, that would at least give us consistent output across platforms.

The other way around this is to encode the result to UTF-8. That's a little tricky since the encode method is not implemented on all versions of Ruby we're currently supporting. But it's possible to make it work.

**Comment by mojavelinux** [comment]
Can you do me a favor? Can you run the following Ruby script and report the output?

```ruby
puts Time.now.strftime('%H:%M:%S %Z').encoding
puts Time.now.strftime('%H:%M:%S %Z').encode('UTF-8')
puts Time.now.strftime('%Z').encode('UTF-8')
```

You can run it in an irb session or as a script. I'm curious if that ungarbles the output.

**Comment by mojavelinux** [comment]
Would you be willing to try the PR that I just sent? https://github.com/asciidoctor/asciidoctor/pull/2784

**Comment by mojavelinux** [comment]
cc: @kikijiki

**Comment by kikijiki** [comment]
I tried the PR but I got a different type of garbled text: 

`Last updated 2018-05-15 19:14:04 ôîï₧ (òWÅÇÄ₧)  `

> Can you do me a favor? Can you run the following Ruby script and report the output?

```
puts Time.now.strftime('%H:%M:%S %Z').encoding
Windows-31J

puts Time.now.strftime('%H:%M:%S %Z').encode('UTF-8')
19:21:24 東京 (標準時)

puts Time.now.strftime('%Z').encode('UTF-8')
東京 (標準時)
```

The codepage is 932.

**Comment by kikijiki** [comment]
By the way, even if the text was right shouldn't it change according to the `lang` attribute?  
As of now with `-a lang=en` you would still get japanese kanji in the time.

**Comment by mojavelinux** [comment]
Thanks for running those commands and reporting the output.

But now I feel even more confused. Encoding on Windows really makes no sense at all.

I think the problem may be that we're still not encoding the date part of the string. I'll update the PR. In the meantime, can you try one more thing?

```rb
localdate = Time.now.strftime('%F')
puts localdate.encoding
localtime = Time.now.strftime('%T %Z').encode 'UTF-8'
puts %(#{localdate} #{localtime})
```

I'm trying to figure out at what point the text becomes garbled.

> even if the text was right shouldn't it change according to the lang attribute?

Asciidoctor ignores the `lang` attribute (unless you use it for your own purpose).

**Comment by kikijiki** [comment]
So I checked my environment again and I found that somewhere I was switching codepage to 65001 or 437. If I remove it I get the correct japanese version `東京 (標準時)`.

Codepage 932 (japanese):
![cmd_2018-05-16_16-33-39](https://user-images.githubusercontent.com/784077/40103101-4f720a2e-5927-11e8-85fa-34bed409ac60.png)

Codepage 65001 (UTF-8):
![cmd_2018-05-16_16-54-28](https://user-images.githubusercontent.com/784077/40103852-ce5dbc14-5929-11e8-952e-03db3cfd87e1.png)

Codepage 437:
![cmd_2018-05-16_16-36-23](https://user-images.githubusercontent.com/784077/40103187-9070fbca-5927-11e8-8015-fe896b7ed7a0.png)

**Comment by mojavelinux** [comment]
Thank you again. That's exactly what I needed to know. That means that Asciidoctor is doing the right thing, but codepages in Windows can just confuse Ruby and that's mostly out of our control. What I'm concerned about is making sure Asciidoctor has the right operations.

Now that we understand what's going on (mostly), I still think we should consider dropping the use of `%Z` and just use `%z`, which would avoid the encoding problem as it would only be numbers.

**Comment by mojavelinux** [comment]
Since we force encoding everything, I recommend using codepage 932 when using Asciidoctor. The result should still come out as UTF-8. But correct me if I'm wrong.

**Comment by kikijiki** [comment]
> Now that we understand what's going on (mostly), I still think we should consider dropping the use of %Z and just use %z, which would avoid the encoding problem as it would only be numbers

Yeah, that probably is the safest solution.

> The result should still come out as UTF-8. But correct me if I'm wrong.

Yes, thank you for the trouble. Building with the default codepage works as expected. I think I'll leave the `set TZ=JST-9` anyway to avoid having japanese characters in the timestamp.

**Comment by mojavelinux** [comment]
Fantastic. Thanks again!!

**Comment by mojavelinux** [comment]
I've decided to proceed with using a time offset as the timezone so the output is consistent. The one exception is if the offset is 0, in which case the timezone shows as "UTC". That's done for two reasons. First, it avoids having disagreement over whether it should be "-00:00" or "+00:00". It's also easier to read. (Several time standards provide the same recommendation).

**Comment by mojavelinux** [comment]
This also eliminates the exception we had for Asciidoctor.js, which was failing to output the OS dependent timezone string.
