### ISSUE TITLE
Support adding external links to non asciidoc file on the table of contents

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#2776]
E.g., I want a `.c` source code file to appear on the table of contents, so `include::` can't be used directly. 

Potentially also, this files is also very large, so I don't want it to show up on the document anyways.

I was thinking about a syntax like:

````
== Normal section

[external=mysource.c]
== mysource.c

== Another normal section
````

https://stackoverflow.com/questions/47205905/how-can-i-create-an-asciidoc-table-of-contents-from-external-files?rq=1

**Comment by mojavelinux** [comment]
This is not the purpose of a table of contents. If you want to customize the table of contents to be more than just a table of contents, then you should either use a custom converter, or produce a table of contents another way using a custom block macro.

**Comment by cirosantilli** [comment]
Imagine a world, where people write with chapters, subchpaters etc. and you are able to easily reuse their chapter inside your own book, without copy pasting their content, which might not be in asciidoc anyways. A world where science books are available for free to all.

But sure, wasn't expecting this to be done here ;-)

**Comment by mojavelinux** [comment]
I'm not saying it's a bad idea. I'm simply saying that's not what the built-in toc is designed to do. It's an ideal use case for extensions. If it's something you want, it can be achieved. If we put something this directly in core, we'd quickly have a scope creep problem. As much as possible we want core to be simple, but offer as many opportunities for extension as we can.

**Comment by cirosantilli** [comment]
@mojavelinux I know ;-)
