### ISSUE TITLE
If I use the option `-s` (--no-header-footer), the styling disappear

### ISSUE THREAD

**Issue by mrbig033** [asciidoctor/asciidoctor#2787]
* OS: MX LINUX 17
* Asciidoctor 1.5.4 Runtime Environment (ruby 2.3.3p222 (2016-11-21)
* [my complete environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)
* [the files related to the issue](https://gist.github.com/mrbig033/de435e79efca87d951a3dff2241f287d).

When I run `asciidoctor i3shortcuts.adoc`, the [resulting HTML](https://gist.github.com/mrbig033/de435e79efca87d951a3dff2241f287d#file-i3shortcuts-html) is styled correctly ([image](https://user-images.githubusercontent.com/36245777/40271202-5bfcaf24-5b70-11e8-8626-574a62977041.png)). 

But if I run `asciidoctor -s i3shortcuts.adoc`, it generates [HTML without styling](https://gist.github.com/mrbig033/de435e79efca87d951a3dff2241f287d#file-i3shortcutsnoheaderfooter-html) ([image](https://user-images.githubusercontent.com/36245777/40271203-5c2bfe00-5b70-11e8-86e0-dfe38dc5ca41.png)).

**Comment by mojavelinux** [comment]
You are exactly describing the purpose of the `--no-header-footer` option. When enabled, you get just the embeddable HTML (the part inside the `<body>` tag) without any of the framing or styling. (The name of the option is somewhat misleading, but that's a legacy we inherited from AsciiDoc Py. See https://github.com/asciidoctor/asciidoctor/issues/1444).

If you intention is disable the header and footer banners, then you are looking for the noheader and nofooter attributes.

```
asciidoctor -a noheader -a nofooter i3shortcuts.adoc
```

**Comment by mojavelinux** [comment]
I updated the description of this option in the man page and user manual to be more accurate.

**Comment by mrbig033** [comment]
WOW, what a great and fast and awesome response! I tested the command and it works like a charm. Thanks! Closing the issue.
