### ISSUE TITLE
Inter-document attribute references

### ISSUE THREAD

**Issue by cbeams** [asciidoctor/asciidoctor#2796]
I'd like to be able to set an attribute in one document and reference it from another.

My use case is that I'm building a collection of documents, let's say, `fred.adoc`, `wilma.adoc` and `barney.adoc`, and I wish to summarize certain information about the members of the collection in a table in a top-level `flintstones.adoc` file.

Let's assume there's an attribute called `:age:` in each of the individual character files, for example:

`fred.adoc`
```
= Fred Flinstone
:age: 45
``` 

`wilma.adoc`
```
= Wilma Flintstone
:age: 42
```

And so on. In my `flintstones.adoc` file then, I'd like to be able to do something the following:

```
|===
|Name
|Age

|<<fred#, Fred Flintstone>>
|{fred:age}

|<<wilma#, Wilma Flintstone>>
|{wilma:age}

|<<barney#, Barney Rubble>>
|{barney:age}

|===
```

Of course the `{barney:age}` syntax doesn't work, but rather expresses what I am trying to do. I've seen no mention of this kind of support for what I would call inter-document attribute references, but I can imagine it being useful in many cases, and certainly for the one I'm dealing with now. Has this ever been considered? Is it in fact already possible in some way that I've missed?

**Comment by elextr** [comment]
Well, Asciidoc isn't a database.  It can't store information from one document to another, it can only include information of one document in another.

But you can do something similar by putting the "data" part in a single file you import into each document. You need to use a different separator than `:` too, maybe `-` or `_` eg

```
:wilma-age: 42
:fred-age: 42
:pebbles-age: 7
```

Import that `flintstones_data.asciidoc` in all files that need it.

**Comment by cbeams** [comment]
That sounds like a useful approach, thanks @elextr.

**Comment by mojavelinux** [comment]
Agreed. The way this is done is to use a shared include file. See https://docs.asciidoctor.org/asciidoc/latest/directives/include/#when-is-an-include-directive-useful where this use case is listed. There are other ways to accomplish the same thing, such as using a preprocessor extension to add additional attributes to the document or to pass attributes into the processor via the API or CLI.

In the future, I invite you to ask questions like this in the project chat at https://chat.asciidoctor.org.
