### ISSUE TITLE
asciimath conversion for \$ is not working for docbook

### ISSUE THREAD

**Issue by giuliano52** [asciidoctor/asciidoctor#2797]
The asciimath equation is not interpreting inline equation \$ if output format is docbook. 

See this example

```
= Asciimath test
:stem:

Test with asciimath explicitly. asciimath:[sqrt(4) = 2] html and docbook are ok

Test with asciimath `\$`. \$sqrt(9) = 3\$ html OK, docbook *KO* 
```

with:: 
` asciidoctor  sample-math.adoc` both equation are interpreted 

` asciidoctor  -b docbook5 sample-math.adoc` only the first one is evaluated

tested with: 

> Asciidoctor 1.5.7.1 [https://asciidoctor.org]
> Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by elextr** [comment]
Does [this](https://asciidoctor.org/docs/user-manual/#stem-docbook) help?

**Comment by giuliano52** [comment]
Thank you, but it seems that the issue is not covered there. 

The conversion with asciimath to MathML is working fine, but the symbol `\$` , which is triggered correctly for the html output, is not triggered for docbook. 

Instead, the asciimath:[....] syntax is working fine for both docbook and html 

I cut and paste output of the docbook:

```
[....]
<simpara>Test with asciimath explicitly. <inlineequation><mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML"><mml:msqrt><mml:mn>4</mml:mn></mml:msqrt><mml:mo>=</mml:mo><mml:mn>2</mml:mn></mml:math></inlineequation> html and docbook are ok</simpara>
<simpara>Test with asciimath <literal>\$</literal>. \$sqrt(9) = 3\$ html OK, docbook <emphasis role="strong">KO</emphasis></simpara>
[....]
```

thank you

**Comment by elextr** [comment]
IIUC thats what this part of the linked manual section:

```
There’s no equivalent gem for converting STEM expressions written in LaTeX to MathML. Instead, you can convert the DocBook to PDF using the dblatex pipeline, which obviously supports LaTeX expressions.
```
means.

**Comment by giuliano52** [comment]
Thank you. 
So the `\$ `symbol is for latexmath and not for asciimath even if the `:stem: latexmath` is not explicity added in the header. (asciimath should be the default if you put only `:stem:`)
