### ISSUE TITLE
Support macro inside image title

### ISSUE THREAD

**Issue by free-easy** [asciidoctor/asciidoctor#2799]
I'm using the `asciidoctor-bibtex` to handle bibliography.
In order to cite something this library supplies a inline macro `cite:[key]`.
Besides text, I would like to cite properly the images that I use too.
As suggested by this answer on StackOverflow
https://tex.stackexchange.com/questions/159446/what-is-the-proper-way-of-citing-referencing-an-external-image-document-file I could cite the image in its title (or caption).
So the macro should be inserted in the image's macro:

```asciidoc
image::foo.jpg[title="bar cite:[figure:foo]"]
```

Clearly it doesn't work. Is there any workaround to this?

**Comment by mojavelinux** [comment]
Macros are supported in block titles. Here's how that would be expressed:

```
.bar cite:[figure:foo]
image::foo.jpg[]
```

**Comment by free-easy** [comment]
I've tried, but it doesn't work..

![screenshot from 2018-06-17 21-31-38](https://user-images.githubusercontent.com/20483759/41511386-27557d7e-7276-11e8-93c2-d4cf818bdee7.png)

**Comment by mojavelinux** [comment]
Then that looks like a bug in asciidoctor-bibtex.

**Comment by free-easy** [comment]
Which kind of bug could it be?
I mean, it's just a macro. Based on what I see from the generated document I'm tempted to say that
it's simply that the macro is not recognized by the asciidoctor's parser.
Intuitively asciidoctor-bibtex should only register this macro and if it works in other parts of the document then the macro should be correct.

That said I actually have no clue of how the whole mechanism works.
If I said rubbish, then just ignore what said above.

**Comment by mojavelinux** [comment]
...or that the asciidoctor-bibtex is not respecting the extension / macro mechanism correctly. I recommend following up in that project.

**Comment by free-easy** [comment]
OK

**Comment by free-easy** [comment]
Sorry, I found out that there is already an issue like this open in asciidoctor-bibtex project and there is already a fix in its `cite-in-prose` branch. I'm gonna try it mayble.

Anyway, it seems that it's not a problem related to asciidoctor itself.
I'm closing this issue. 

Thank you for the help you gave me!

**Comment by free-easy** [comment]
For anybody facing the same problem and unwilling to tweak with branches of `asciidoctor-bibtex`, there is another interesting library [asciidoctor-bibliography](https://github.com/riboseinc/asciidoctor-bibliography).
AFAICS it seems more feature-rich and 
At least citing in block titles works!

**Comment by mojavelinux** [comment]
Thanks for following up.

I believe the asciidoctor-bibliography is a better choice because it's based on Asciidoctor's extension mechanism and adheres closer to the semantics of AsciiDoc.
