### ISSUE TITLE
How to highlight lines with other highlighter?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#2806]
A few days ago, I found the Pygments could highlight lines.

The example is as following:

```
[source,groovy,linenums,highlight='5,7-9']
----
package com.mrhaki
 
import static ratpack.groovy.Groovy.ratpack
 
ratpack {
    handlers {
        get {
            render "Hello World!" // <1>
        }
    }
}
----
<1> Render output
```

The article is [Awesome Asciidoctor: Highlight Lines In Source Code Listings](http://mrhaki.blogspot.com/2016/10/awesome-asciidoctor-highlight-lines-in.html)

**How to highlight lines with other highlighter?**

**Comment by Mogztter** [comment]
Hello @diguage,

The answer is in the article you mentioned:

> First we must add the document attribute source-highlighter and use the value coderay or pygments.

```
= Source highlight lines
:source-highlighter: pygments
:pygments-style: emacs

[source,groovy,linenums,highlight='5,7-9']
----
package com.mrhaki
 
import static ratpack.groovy.Groovy.ratpack
 
ratpack {
    handlers {
        get {
            render "Hello World!" // <1>
        }
    }
}
----
<1> Render output
```

If you are using Asciidoctor Ruby it should work fine.

**Comment by mojavelinux** [comment]
The highlight feature for source blocks is only supported when using Pygments or CodeRay as the source highlighter.

**Comment by mojavelinux** [comment]
As of Asciidoctor 2.0, highlighting lines is supported in Pygments, CodeRay, and Rouge. Now that the syntax highlighter is pluggable, it's possible to integrate Prism using custom code, which also supports this feature.
