### ISSUE TITLE
Asciidoctor html5 stemblock output of asciimath

### ISSUE THREAD

**Issue by zhustec** [asciidoctor/asciidoctor#2809]
Hello guys. When i use asciimath:

```
[asciimath]
++++
x_1 − x_2 <= 0
x_1 − x_5 <= −1
x_2 − x_5 <= 1 
x_3 − x_1 <= 5 
++++
```

The output html is:

```html
<div class="stemblock">
<div class="content">
\$x_1 − x_2 &lt;= 0
x_1 − x_5 &lt;= −1
x_2 − x_5 &lt;= 1
x_3 − x_1 &lt;= 5\$
</div>
```

Which is in one line. Apparently I don't wan't it, so I add a new line between each equation:

```
[asciimath]
++++
x_1 − x_2 <= 0

x_1 − x_5 <= −1

x_2 − x_5 <= 1 

x_3 − x_1 <= 5 
++++
```

And now the output html is:

```html
<div class="stemblock">
<div class="content">
\$x_1 − x_2 &lt;= 0\$<br>
<br>
\$x_1 − x_5 &lt;= −1\$<br>
<br>
\$x_2 − x_5 &lt;= 1\$<br>
<br>
\$x_3 − x_1 &lt;= 5\$
</div>
```

As you see, asciidoctor add one more `<br>` between each equation。When I check the source code, I found this:

https://github.com/asciidoctor/asciidoctor/blob/217dc6fb3ec09ad522d86bb82ba80ec904486e27/lib/asciidoctor/converter/html5.rb#L640-L643

In my opinion, it should be `br * ($&.count(LF) - 1)` instead of `br * ($&.count LF)`. What's you guy's opinions?

**Comment by mojavelinux** [comment]
We already had a very lengthy design discussion about this behavior in issue #2497 before the last release. There are strong reasons for why it needs to be the way it is. You can find the conclusion in this comment: https://github.com/asciidoctor/asciidoctor/issues/2497#issuecomment-369865944.

Long story short, here's how you'd need to input the equation to get result you desire:

```
:stem:

[asciimath]
++++
x_1 - x_2 <= 0 \
x_1 - x_5 <= -1 \
x_2 - x_5 <= 1 \
x_3 - x_1 <= 5
++++
```
