### ISSUE TITLE
emoji does not work

### ISSUE THREAD

**Issue by asdfg0280** [asciidoctor/asciidoctor#2816]
My environment does not work emoji.

Asciidoctor may try to be like markdown for emoji.

Markdown's emoji is img tag.

sry, my poor English.

**Comment by asdfg0280** [comment]
sry, I intend to 👍 ←this emoji not working like markdown.

**Comment by asdfg0280** [comment]
thx for your reply
![image](https://user-images.githubusercontent.com/31565162/43041668-1c5656d6-8da2-11e8-84c3-5a6c2f51c030.png)

I contribute HackAdoc now. Asciidoctor does not adapt markdown's emoji.

**Comment by mojavelinux** [comment]
The reason AsciiDoc cannot support the emoji shorthand used in Markdown (and on GitHub) is because a line with a leading and trailing colon is already reserved for an attribute entry. So it wouldn't work if the emoji starts as the beginning of the line.

For further discussion, see #123.

**Comment by asdfg0280** [comment]
Okay.I see.
I try to disable 👍 ← on Hackadoc.

**Comment by WyxXu** [comment]
> If you are interested in an emoji shorthand, please refer to this extension:
> 
> * https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro.rb
> * https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro/extension.rb
> 
> For example:
> 
> ```
> = Emoji Inline Macro Extension
> :cache-uri:
> 
> Faster than a emoji:turtle[1x]!
> 
> This is an example of how you can emoji:heart[lg] Asciidoctor and Twitter Emoji.
> ```

and  how to use these rb file in asciidocfx, please?

**Comment by ggrossetie** [comment]
Please do not comment on a closed issue. If you need support, please direct your questions to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). The issue tracker is not a support portal. Thanks!
