### ISSUE TITLE
URL rendering issue

### ISSUE THREAD

**Issue by Serdaro** [asciidoctor/asciidoctor#2837]
Hello,

A couple of months ago, we have migrated all of our documentation to be generated by Asciidoctor, using the Asciidoc markup language, and aws the company, we are really happy about it. Thank you for this awesome tool.

There is a minor issue I have faced with recently. There is a link in one of our online HTML documentation which targets to another document in another website. The link does not work. After some debugging, I have learnt that it is caused by the "--" characters (two consecutive dashes) included in the URL; Asciidoctor renders it as a one long dash, hence we get 404.

We'd appreciate any help/workaround on this one.

Thanks a lot.

**Comment by Mogztter** [comment]
Hello @Serdaro 

I think you need to prevent the replacement: https://asciidoctor.org/docs/user-manual/#preventing-substitutions

One way to do it, is to use a backslash: 

```adoc
http://hello.world/foo\--bar[link]
```

If you don't want to escape the character, you can use this syntax:

```adoc
link:++http://hello.world/foo--bar++[link]
```

And if you want to use an attribute for the URL (it's a good practice), you can use the following syntax:


```adoc
:uri-hello-world: http://hello.world/foo--bar

pass:a,m[{uri-hello-world}[link\]]
```

We tell Asciidoctor to apply the **a**ttributes (with **a**) substitution and the **m**acros (with **m**) substitution.
The attributes substitution will replace the attribute `uri-hello-world` with the value `http://hello.world/foo--bar` and the macros substitution with replace the value `http://hello.world/foo--bar[link]` with a link.

You can read more about this issue: https://asciidoctor.org/docs/user-manual/#troubleshoot

**Comment by Serdaro** [comment]
Thank you very much @Mogztter , all of the above worked fine. We will go with the attribute option.
