### ISSUE TITLE
Allow list depth to be unlimited

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2854]
A frequently requested feature of AsciiDoc is to allow lists to be nested to an unlimited depth. I looked into it, and it turns out it may actually be faster to allow an arbitrary list depth than to try to restrict it. So this isn't a technical limitation.

I've also encountered use cases where an unlimited depth would make AsciiDoc more suitable as a data format. For example, in Antora, AsciiDoc is used to define the navigation structure. Currently, this restricts the navigation to a fixed depth, which can be problematic. If the AsciiDoc parser did not enforce a limit, this concern would go away.

We'll need to draw some lines, though. The default stylesheet will only provide styles up to a certain depth. It will be up the user to provide additional styles. Also, the unlimited depth will only apply to ordered and unordered lists, not description lists. The latter will still be limited by the syntax. And the output format will have to be able to support unlimited list depths, though this is already the case for HTML, DocBook, and man pages.

**Comment by mojavelinux** [comment]
Also keep in mind that GitHub starts flatting the indentation after 10 levels.

**Comment by mojavelinux** [comment]
For me, where this change adds the greatest value is in the document model.

**Comment by elextr** [comment]
Agree that the parser and Asciidoc language should not limit nesting level for ordered and unordered lists.  The semantics of some targets may limit it, but thats a backend issue.  It should not stop the parser allowing greater nesting and it working on backends that can handle it.

My only niggle is that it becomes kinda hard to quickly see the level when there are more than say 4-5 dots or stars in a row.  

```
******* quickly now, whats this level?
```

I would suggest some syntax extension like `*<level number>` eg 

```
*7 a very nested list at level 7
```

It would of course work for unordered lists but unfortunately for ordered lists it would clash with title syntax which is `<bol>.<non-whitespace>`.  Titles starting with numbers are perfectly reasonable so I wouldn't want to restrict them to having a non-digit as first character.  Better ideas anybody?

**Comment by mojavelinux** [comment]
The way I'm thinking about it is that this is more for auto-generated stuff.

However, I do have a little trick I use to make the levels a bit easier to read. Since spaces in front of the marker are optional, it actually works out visually if you indent each level by one additional space. You end up getting a straight diagonal line.

```
* item
 ** item
  *** item
   **** item
    ***** item
     ****** item
```

(notice the "i" is always under the "e").

I've started using this style in my writing and it feels pretty natural. It does violate my rule of staying on the left margin, but this is one case where it helps me see what's going on a bit better and encourages me not to nest so deeply. I haven't decided yet if I'm going to stick with this, but for now it feels right.

**Comment by elextr** [comment]
Yes that might help, especially for those whose editor can provide indentation guides:

```
  |  | ******* stuff (note the vertical bars are an editor artifact, not in the source)
```

Certainly any possible syntactic difficulties should not prevent the language removing the limits, as you say autogenerators won't care.

**Comment by mojavelinux** [comment]
I guess this change is only really needed for unordered lists, but I can't see that it hurts to add it for ordered lists as well. There is no performance impact and it saves us from having to explain a difference between rules for ordered and unordered lists.
