### ISSUE TITLE
Missing attributes always dropped when used in includes

### ISSUE THREAD

**Issue by rkratky** [asciidoctor/asciidoctor#2855]
The setting of `:attribute-missing:` is ignored when a missing attrib. is used in include statements. The line is always dropped, regardless of the setting. This is true for all includes, i.e.:
```
:attribute-missing: warn

image::{bogus-image}[]
video::{bogus-video}[]
audio::{bogus-audio}[]
include::{bogus-file}[]
{bogus}
```
Results in:
```
asciidoctor: WARNING: dropping line containing reference to missing attribute: bogus-image
asciidoctor: WARNING: dropping line containing reference to missing attribute: bogus-video
asciidoctor: WARNING: dropping line containing reference to missing attribute: bogus-audio
asciidoctor: WARNING: dropping line containing reference to missing attribute: bogus-include
asciidoctor: WARNING: skipping reference to missing attribute: bogus
```
The behaviour is the same even if there's fluff around, e.g.:
```
include::filename-{bogus-file}.extension[]
```
The result is the same as above.

I would expect the include statement to fail, not the line to be dropped (or not fail if `filename-.extension` actually existed).

**Comment by mojavelinux** [comment]
I've updated the docs to point out this exception and explain why it exists.

**Comment by rkratky** [comment]
> Is there a reason you want the include directive to be kept?

* To make the behaviour consistent. If I set `:attribute-missing: warn`, I don't expect any lines to be dropped. As it is now, the behaviour is confusing. I see that I've explicitly set the attribute not to drop any lines, and yet the log tells me "dropping line". (It's confusing even with updated docs because the log doesn't tell me anything about this particular line being one with an include statement.) So, unless I'm familiar with this exception to the rule, I'm thinking that something is broken.
* As I mentioned above, it would make more sense to me if a warning was output ("skipping reference to missing attrib."), and then the include failed with "ERROR: _[snip]_ include file not found" -- or didn't fail if the result resolved to a file that actually existed.

**Comment by elextr** [comment]
Although the log message might be improved, a warning on an include that contains an undefined attribute seems the right way to go.  You can always explicitly define the attribute to empty content so it won't add anything to the include path, but its explicit, not just forgotten, which is likely the case if its undefined.

**Comment by mojavelinux** [comment]
I've decided to go ahead and do our best to honor the attribute-missing setting in this context (though it's harder than it seems). For most users (running with default settings), this will not result in any change. However, it opens up the possibility of using drop-line as it was originally designed in AsciiDoc Python (when you know what you're doing). If we get feedback this isn't working out for some reason, we can reevaluate.
