### ISSUE TITLE
Corrupted HTML with image icon inside a link

### ISSUE THREAD

**Issue by krOoze** [asciidoctor/asciidoctor#2856]
When I do (`asciidoctor -b html5 example.adoc`):
```
:data-uri:
:icons: image
:iconsdir: ./icons/
:icontype: svg

link:++https://example.com/++[icon:exclamation[alt="Example"]Example]
```

I get a corrupted HTML:
```
<div id="content">
<div class="paragraph">
<p><a href="https://example.com/"><span class="icon"><img src="data:image/svg+xml;base64</a></p>
</div>
</div>
```

But the same works fine with `:icons: font`.
Asciidoctor version 1.5.7.1, and `master`.

**Comment by mojavelinux** [comment]
That's simply not going to work with the way the parser is designed. It's going to see the encoded data of the SVG inside the link attrlist and can get totally confused by it.

You'll need to tuck the icon away inside of a passthrough if you want to do that. Here's one solution:

```
https://example.com[pass:m[icon:exclamation[alt=Example\]]Example]
```

(Pay attention to the placement of the backslash).

But honestly, this feels more like something that should be done with CSS. You don't want to be inlining the same icon in your document over and over as it's going to balloon the size of the page.

Here's how to express that succinctly using a role.

```
https://example.com[Example,role=exclamation]
```

You'll then need to provide the supplemental stylesheet to add the icon using CSS.

**Comment by krOoze** [comment]
> You'll need to tuck the icon away inside of a passthrough if you want to do that.
> https://example.com[pass:m[icon:exclamation[alt=Example\]]Example]

I can't pretent to know how it works, but it does. Thanks!

> But honestly, this feels more like something that should be done with CSS. You don't want to be inlining the same icon in your document over and over as it's going to balloon the size of the page.

Not a bad idea, but requires some custom code, and I need it to work in PDF too. I am not overtly worried about it right now, because the HTML document already has 8 MB. And anyway, all the admonitions icons already work that way in `:data-uri:` mode...
