### ISSUE TITLE
Inline Code is indexed - it should not be.

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor#2858]
This is a copy of https://github.com/asciidoctor/asciidoctor-pdf/issues/932 as it applies to asciidoctor as well as asciidoctor-pdf. 

I have the following code in a document: `X = ~((1 << 2) | (1 << 4) | (1 << 6))` which renders correctly in a code block, but inline it renders as `X = ~  1 << 3) | (1 << 6) | (1 << 7` when the output is PDF or HTML. 

It (probably) gets indexed in HTML as well, but this isn't a problem as HTML doesn't actually render the index terms. It's definitely indexed in PDF output which does render indexes.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
If your content includes reserved formatting characters, you need to escape it using an inline passthrough. For example:

```
+X = ~((1 << 2) | (1 << 4) | (1 << 6))+
```

or

```
pass:c[X = ~((1 << 2) | (1 << 4) | (1 << 6))]
```

(it's also possible to use a backslash, but that's a lot harder to get right).

**Comment by mojavelinux** [comment]
For details about the inline passthrough, see https://asciidoctor.org/docs/user-manual/#passthroughs

**Comment by NormanDunbar** [comment]
Thanks @mojavelinux I had tried with the plusses to wrap the special characters, but I obvioulsy didn't get the correct syntax. Both the above versions work perfectly, and my index is safe again too.

I'll close this now.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
:+1:
