### ISSUE TITLE
Do not render Index Titles in HTML output

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor#2859]
When a document is rendered as HTML, there are no index entries. This I can live with, however, the Index 'chapter' heading _is_ rendered, and appears by itself, looking sad and lonely! You end up with a chapter heading, by itself, at the end of the page. See attached `indexing.html.txt` file. Rename to indexing.html please - it's a GitHub thing.

[Indexing.html.txt](https://github.com/asciidoctor/asciidoctor/files/2357239/Indexing.html.txt)

The content is just a document I used to try out various indexing strategies and is of no relevance, but the final line of the file does show the chapter heading for the index with no content. I think that the chapter heading should be omitted.

Thanks.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
There's already a mechanism for doing this in AsciiDoc.

```
ifdef::backend-pdf[]
[index]
== This is the Index
endif::[]
```

The reason this is necessary is because the html5 converter doesn't yet handle the index, so it doesn't know to look for it. That's what #450 is about.

**Comment by NormanDunbar** [comment]
Hi @mojavelinux - that works perfectly, thanks. 

One thing I noticed, I added the code to a document I've kept to show indexing etc, and when embedded in a source code block, as follows:

````
[source,none]
----
ifdef::backend-pdf[]
[index]
== This is the Index
endif::[]
----
````

The `ifdef` is still executed and the rendered  code fragment ends up looking like this in a pdf:

````
[index]
== This is the Index
````

In an HTML, it's just blank.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
Preprocessor directives like ifdef are unaware of the context. In other words, they don't know they are in a listing block. Therefore, you always have to backslash escape them if you don't want them to be interpreted.

```
----
\ifdef::backend-pdf[]
[index]
== This is the Index
\endif::[]
----
```

Btw, instead of `source,none`, you can just leave off the `source` style.

**Comment by NormanDunbar** [comment]
Brilliant. Thanks.
I'll close this issue.

Cheers,
Norm.

**Comment by mojavelinux** [comment]
\o/
