### ISSUE TITLE
Windows UNC Path as Output File Doesn't Work in 1.5.7

### ISSUE THREAD

**Issue by mperktold** [asciidoctor/asciidoctor#2869]
~~This is possibly related to #806.~~

We are using a command like the following to render asciidoc files and save them on a central server machine:

```
asciidoctor file.adoc -o \\servername\docs\file.html
```

This worked fine with a previous version (details are included below).

But upgrading to Ruby 2.5 and downloading the new version of Asciidoctor, instead of saving the output file on the server, Asciidoctor creates a local directory `servername` and saves it there.

The same is true for `asciidoctor-pdf`.

### Version Details

The previous version where this worked as expected was:

```
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:- ex:UTF-8)
```

The new version where this doesn't work as expected anymore is:
```
Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
Thanks for reporting. Giving that the issue you reference was resolved 4 years ago, I don't think that's a factor in the regression (other than general information).

The crux of the problem seems to be that we have a missing test that didn't catch this regression. I'll investigate.

**Comment by mojavelinux** [comment]
Sure enough, there was a place in PathResolver where we were assuming that `\\server\docs` was not a filesystem root. I've submitted a patch.

**Comment by mojavelinux** [comment]
What's interesting to note is that Asciidoctor does not handle UNC paths on *nix well due to an incorrect assumption in Ruby (mentioned above). This would be a problem if you wanted to use Asciidoctor to write to an output directory mapped by Samba. In order to support that, we would have to use a replacement for `File.dirname`.

**Comment by mperktold** [comment]
Great, Thanks! 👍 

The workaround you mentioned also works fine on 1.4.x, so I'll use that in the meantime.
