### ISSUE TITLE
Allow callouts to be automatically numberd

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2871]
For rapid prototyping, allow callouts to be automatically numbered, much like ordered lists. The proposed syntax for this is either `<.>` or `<0>`.

Here's an example that uses `<.>`.

```
----
site:
  url: https://docs.example.com # <.>
  title: Docs # <.>
----
<.> The absolute URL of the site.
<.> The title of the site displayed in the navbar.
```

If, instead, we opted for `<0>`, we could leverage the existing parsing rules:

```
----
site:
  url: https://docs.example.com # <0>
  title: Docs # <0>
----
<0> The absolute URL of the site.
<0> The title of the site displayed in the navbar.
```

**Comment by mojavelinux** [comment]
For now I decided to just support the syntax `<0>`. If you feel strongly it should be `<.>`, please speak up.

**Comment by mojavelinux** [comment]
cc: @amarantha-k

**Comment by elextr** [comment]
Well, having multiple `<0>` s seems kind of strange when usually a number only appears once.  Using the `<.>` syntax has a nice symmetry with autonumbered lists.

**Comment by mojavelinux** [comment]
After giving this more though, I agree. The `<0>` is not very clear and has no existing convention in the syntax, whereas `<.>` does. Let's change it.

**Comment by mojavelinux** [comment]
One thing I'd like to change is to make the leading `<` in the callout list item required (e.g., `<1>` or `<.>`). Not only is that more consistent anyway, (and slightly faster), it avoids ambiguity between our proposal for auto-numbered callout items and a block title line. (I seriously doubt anyone is using, or even knows about, the optional syntax `1>`).

**Comment by mojavelinux** [comment]
Btw, thanks for the feedback!

**Comment by elextr** [comment]
I notice that the actual callout list is already autonumbered in the HTML using `<ol>` (by both Asciidoctor and Asciidoc Python) so its really only the callout markers that need to be autonumbered by Asciidoctor.  So having numbers on the list is sort of unnecessary anyway, and using `<.>` removes the need for checking and warning about incorrect ordering of the manual numbers which are never used.  

What would be really good was if there was a way that the markers could be autonumbered (or manually numbered if you want them out of order or repeated) and the list entries were automatically reordered to match, so they stay in sync as things move and are added or removed.  I guess that would need IDs.  But thats waaay beyond the scope here.

Oh, block titles, good catch.  Especially as its not totally inconceivable that a programming language document has a block title like `> Comparison Operator`.

**Comment by mojavelinux** [comment]
One last question that remains is whether we should try to continue numbering if you switch from explicit numbering to implicit number. This is not true of ordered lists, but a case could be made it would be useful in this context.

Example:

```
----
public class Person { //<1>
  private String lastName; //<.>
  private String firstName; //<.>
}
----
```

Should the last and first name fields be `<2>` and `<3>` respectively?

**Comment by elextr** [comment]
> but a case could be made it would be useful in this context.

The example applies to the markers. 

The question I see is then what does the list do in this case?  To date all lists start a new list if the type of list changes, ie you switch from manual numbering to autonumbering.  So the callout list can't be marked up the same as the markers unless the callout list behaviour is different to other lists, or other lists are changed to behave that way (a breaking change).

It seems more consistent to ensure the callout list can be marked up the same as the markers, so since the list can't switch from manual to automatic without being inconsistent, neither should the markers be able to switch from manual to automatic.

Also, as the OP said, the auto-numbering is really only for fast prototyping, for production documents a writer really should use manual numbering to ensure that there is a link from the marker to the list item. For prototyping only then adding complexity isn't worth it.

**Comment by mojavelinux** [comment]
> So the callout list can't be marked up the same as the markers unless the callout list behaviour is different to other lists, or other lists are changed to behave that way (a breaking change).

The explicit numbering in a callout list is strictly for validation / auditing. You are correct that the list always gets numbered in a straight sequence in the rendered document.

The reason for the explicit numbering (IMO) is to make it easy for the author to make the correlation between the item in the list and the referenced callout number in the code. By choosing auto-numbering, you opt out of that visual correlation. Sometimes, that might be what you want.

> so since the list can't switch from manual to automatic without being inconsistent, neither should the markers be able to switch from manual to automatic.

I could see us starting there. But I don't really feel it's warranted to validate that explicit and implicit numbering are not mixed. So I was just curious which number to start with when that happens. Since we don't want to encourage mixing and matching (at least not yet) then I think we should not attempt to continue the numbering (which would otherwise encourage the practice).

**Comment by elextr** [comment]
> then I think we should not attempt to continue the numbering (which would otherwise encourage the practice).

Agree.
