### ISSUE TITLE
Level-related list parsing code uses superfluous comparisons

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2872]
The parsing code that consults the list level is invalid. As of right now, the `level` property on a block is the section level, so it doesn't play a factor in list parsing.

We should reconsider the meaning of the `level` property. If necessary, we should add a new property to track the list depth. Then, revisit the logic in `parse_list` to determine when the list level needs to be compared. If there are no such cases, this logic should be removed from the parser.

**Comment by elextr** [comment]
As far as I can tell the concept of "current" level for nestable lists logic is needed to tell if:

1. a list item is to start a new list if the item level is one greater than current, 

2. be put in the current list if the list item is the same as the current 

3. to end one or more lists if the item is lower than current

4. error if its more than one greater than current (must nest one level at a time)

(Note: in above "level number" == number of dots or stars in the list item markup, so greater == more nested)

**Comment by mojavelinux** [comment]
In fact, the code was always assigning the level property on the list to a value of 1, so it didn't even match the section level. This gives us a lot of room to define what value it actually should be. For now, we'll allow it to default to the level of the section (which happens in the block constructor), add a test, then decide what value we want to use in #1788.

**Comment by mojavelinux** [comment]
Since this was mostly just removing dead code, I reclassified it as an improvement. Technically, the value of the level property is now different (as it was always 1 before), but we'll add a CHANGELOG entry once we decide what we want to do with it in #1788.

**Comment by mojavelinux** [comment]
What had happened is that parse_list_item took over the logic that parse_list used to be doing. It's parse_list_item that checks when a sibling item has been encountered. It never has to worry about finding an ancestor item since the reader is scoped to the current nesting level already.
