### ISSUE TITLE
Literal text followed by apostrophe generates invalid structure in docbook format

### ISSUE THREAD

**Issue by jottinger** [asciidoctor/asciidoctor#2875]
Given this input:

    = Sample Document

    Look at the source document to the error condition.
    
    == The broken section
    
    This is a broken section test for docbook. If `class`' is possessive, the docbook generated is incorrect footnote:[This may include the use of a `footnote:`, I'm not sure.].```
    
    The generated docbook output looks like:

```<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
    <info>
        <title>Sample Document</title>
        <date>2018-09-19</date>
    </info>
    <simpara>Look at the source document to the error condition.</simpara>
    <section xml:id="_the_broken_section">
        <title>The broken section</title>
        <simpara>This is a broken section test for docbook. If
            <literal>class&#8217; is possessive, the
                docbook generated is incorrect
                <footnote>
                <simpara>This may include the use of a `footnote:
            </literal>
            , I&#8217;m not sure.
        </simpara>
    </footnote>
    .
</simpara>
        </section>
        </article>```

Note the broken first literal tag in the docbook output. This is ALSO broken in HTML generation.

**Comment by mojavelinux** [comment]
Thanks for bring this case forwarad. This just happens to be one of those strange corner cases as a result of having a language based on shorthand (and a little inference).

Here's how you'd write a possessive monospaced phrase:

```
``class```'
```

First, the monospace has to be unconstrained since technically the formatting is being applied within the boundaries of a word. Then, you need to use an explicit typographic apostrophe markup, which is an apostrophe preceded by a backtick.

Alternately, you could choose to encode the typographic apostrophe directly into the text.

```
`class`’
```

I recently encountered some other edge cases that pertained to the interaction between backticks and quotes. See https://asciidoctor.org/docs/user-manual/#unconstrained-formatting-edge-cases. I can add this case to that section.

Now, when we add the footnote in, the monospace there requires unconstrained formatting due to the typographic apostrophe markup having an affinity for the backtick in the footnote.

```
If ``class```' is possessive, and the footnote contains constrained monospace, the docbook generated is incorrect.footnote:[This may include the use of a ``footnote:``, I'm not sure.].
```

This problem should be fixed once we switch to parsing footnotes separately from the main text. (related to #61).

**Comment by mojavelinux** [comment]
I've documented this case in https://asciidoctor.org/docs/user-manual/#unconstrained-formatting-edge-cases.

Let me know if that resolves it for you.

**Comment by jottinger** [comment]
It does, thank you!
