### ISSUE TITLE
Crash on table CSV parsing by single quotation

### ISSUE THREAD

**Issue by zelivans** [asciidoctor/asciidoctor#2878]
## Short introduction
I've been testing asciidoctor with a Ruby fuzzing tool ([kisaten](https://github.com/zelivans/kisaten)) and found a few bugs. From the guidelines I understand it's best if I open an issue for each bug, the one below is the first I caught.

I tested all against the master version of asciidoctor. I used the `Asciidoctor.load` method and then the `convert` method in my script. It can all be reproduced with the `asciidoctor/bin/asciidoctor` script as well.

## Raw crash

```
asciidoctor: WARNING: <stdin>: line 1: unterminated table block
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/table.rb:599:in `close_cell': asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `strip' for nil:NilClass (`NoMethodError`)
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/parser.rb:2433:in `parse_table'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/parser.rb:838:in `next_block'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/parser.rb:356:in `next_section'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/parser.rb:98:in `parse'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/document.rb:565:in `parse'
	from /home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor.rb:1360:in `load'
	from tst.rb:4:in `<main>'
```

## Explanation

A single quotation mark under a CSV table can result in calling `strip` on nil resulting in a uncaught  `NoMethodError` (crash) in the `close_cell` function.

Reproduce with the following input:

```
,===
"
``` 

A simple fix is easy so I will send a PR, but you might want to solve this differently.

**Comment by mojavelinux** [comment]
Thanks for reporting! See PR for comments.

**Comment by mojavelinux** [comment]
Most CSV parsers will fail on an unclosed quote. However, the policy in Asciidoctor is to recover if possible, but issue a warning. Therefore, I have decided to report the issue (as you had proposed), but to also set the cell to empty (since the double quote is otherwise meaningless).

**Comment by zelivans** [comment]
Sounds good to me as well.
