### ISSUE TITLE
Wrong alignments in DocBook table when using multirow cells

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#2887]
The cell alignments from the table column specification gets mixed up when using multirow columns in translation to DocBook tables, see the following example:

[cols=">13,11,15,8,45", options="header", grid=none, frame=topbot]
|===
|Group|Item|Identifier|Fmt|Description
.4+| Project Management
|SPMP |PCERT-SPMP |pdf |Software Project Management Plan
|PHD  |PCERT-PHD  |pdf |Project History Document
|SQAP |PCERT-SQAP |pdf |Software Quality Assurance Plan
|===

The header and first row is correctly translated but second and third row is translated to

<row>
<entry align="right" valign="top"><simpara>PHD</simpara></entry>
<entry align="left" valign="top"><simpara>PCERT-PHD</simpara></entry>
<entry align="left" valign="top"><simpara>pdf</simpara></entry>
<entry align="left" valign="top"><simpara>Project History Document</simpara></entry>
</row>
<row>
<entry align="right" valign="top"><simpara>SQAP</simpara></entry>
<entry align="left" valign="top"><simpara>PCERT-SQAP</simpara></entry>
<entry align="left" valign="top"><simpara>pdf</simpara></entry>
<entry align="left" valign="top"><simpara>Software Quality Assurance Plan</simpara></entry>
</row>

which must be wrong.
I'm using asciidoctor 1.5.7.1 on a cygwin platform.

**Comment by elextr** [comment]
At first glance you have declared 5 columns but only provided data for 4, so everything is moving to fill the missing columns.

**Comment by pela9** [comment]
That's how its done in the manual after a multirow cell, and adding empty cells to fill in don't change the DocBook translation

**Comment by elextr** [comment]
ahh, wait, the `.4+` is a row span, not a column span, so the column count is right.  Although the count is wrong, should be 3 it doesn't make any difference (at least to html).

**Comment by elextr** [comment]
Can you post your docbook output, the docbook I get looks right (to my inspection)?

**Comment by pela9** [comment]
Hi,

Example again with corrected row count:

[cols=">13,11,15,8,45", options="header", grid=none, frame=topbot]
|===
|Group|Item|Identifier|Fmt|Description

.3+| Project Management
|SPMP |PCERT-SPMP |pdf |Software Project Management Plan
|PHD  |PCERT-PHD  |pdf |Project History Document
|SQAP |PCERT-SQAP |pdf |Software Quality Assurance Plan

|===

Gives this DocBook Translation where second and third row has wrong alignment
in first cell (should be left)

<informaltable frame="topbot" rowsep="0" colsep="0">
<tgroup cols="5">
<colspec colname="col_1" colwidth="14.1304*"/>
<colspec colname="col_2" colwidth="11.9565*"/>
<colspec colname="col_3" colwidth="16.3043*"/>
<colspec colname="col_4" colwidth="8.6956*"/>
<colspec colname="col_5" colwidth="48.9132*"/>
<thead>
<row>
<entry align="right" valign="top">Group</entry>
<entry align="left" valign="top">Item</entry>
<entry align="left" valign="top">Identifier</entry>
<entry align="left" valign="top">Fmt</entry>
<entry align="left" valign="top">Description</entry>
</row>
</thead>
<tbody>
<row>
<entry align="right" valign="top" morerows="2"><simpara>Project Management</simpara></entry>
<entry align="left" valign="top"><simpara>SPMP</simpara></entry>
<entry align="left" valign="top"><simpara>PCERT-SPMP</simpara></entry>
<entry align="left" valign="top"><simpara>pdf</simpara></entry>
<entry align="left" valign="top"><simpara>Software Project Management Plan</simpara></entry>
</row>
<row>
<entry align="right" valign="top"><simpara>PHD</simpara></entry>
<entry align="left" valign="top"><simpara>PCERT-PHD</simpara></entry>
<entry align="left" valign="top"><simpara>pdf</simpara></entry>
<entry align="left" valign="top"><simpara>Project History Document</simpara></entry>
</row>
<row>
<entry align="right" valign="top"><simpara>SQAP</simpara></entry>
<entry align="left" valign="top"><simpara>PCERT-SQAP</simpara></entry>
<entry align="left" valign="top"><simpara>pdf</simpara></entry>
<entry align="left" valign="top"><simpara>Software Quality Assurance Plan</simpara></entry>
</row>
</tbody>
</tgroup>
</informaltable>

Best Regards
Per

________________________________

**Comment by elextr** [comment]
Ahh, ok, I see, looks like the alignment is applied to the first column output in a row without consideration of spans.  Have to leave this to the Asciidoctor experts then.

**Comment by elextr** [comment]
PS you have closed the issue, the "comment" and "close and comment" buttons should be further apart :)

**Comment by pela9** [comment]
Oh sorry,
Do I need to reopen it or will you take care of it?
By the way, I’m amazed of the answer from you! Usually takes Days or weeks to get this kind of response on issue lists, thanks.

Per

________________________________

**Comment by elextr** [comment]
As I'm only a user I can't re-open it, but the project folks probably will, unless they filter out closed issues and don't see it :).  So probably best if you do.

**Comment by pela9** [comment]
OK, I will, thanks again for your help.


________________________________

**Comment by mojavelinux** [comment]
I would reopen, except this is a duplicate of #989 and #1558. This is a known limitation in Asciidoctor and may have been a limitation of AsciiDoc Python as well.
