### ISSUE TITLE
Inner whitespace in prose should be collapsed in manpage output

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2890]
In the manpage output, the inner whitespace in prose (such as in a paragraph) is not being collapsed. The assumption in AsciiDoc is that inner whitespace is not significant. Therefore, all inner whitespace in normal text should be condensed to a single space.

**Comment by elextr** [comment]
I thought `troff` handled filling and line breaking, so there should be no need for Asciidoctor to do so?

**Comment by mojavelinux** [comment]
Nope, not fully. There are certainly cases when it ignores it, such as newlines. But it preserves spaces around those newlines.

This actually turns out to be something that was already implemented in the manpage converter, it just wasn't being done correctly. And there's actually three modes to support: preserve (keep as is, but replace tabs with spaces), normalize (keep newlines, but remove space around newlines), collapse (condense all repeating whitespace to a single space). The previous implementation only supported two modes, and they weren't really doing the right thing.

I updated the options to manify and added tests to confirm.
