### ISSUE TITLE
Converter::Factory should support resolving a built-in converter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2891]
Currently, the converter factory only resolves custom converters. This presents a problem for integrations that need to access or extend a built-in converter. Add a flag to the resolve method (or introduce a dedicated method) that will resolve a built-in converter (honoring the order of precedence).

**Comment by mojavelinux** [comment]
Somewhat related to this is a simpler way to override the built-in converter, in particular the html5 converter. Currently, this is only possible using custom templates. But it should be simpler to compose a custom converter with a built-in one so as to extend the built-in behavior.

**Comment by Mogztter** [comment]
Is it related to https://github.com/asciidoctor/asciidoctor/issues/2824 ?

**Comment by mojavelinux** [comment]
In a way, yes. We probably have to think a little bit broader about how this architecture is going to work (which could warrant a separate issue). When Asciidoctor was first designed, there was never any intention to support custom converters, only custom templates. Then custom converters were added on. To get to something fully customizable, some assumptions will need to be challenged.

**Comment by mojavelinux** [comment]
The main change in this redesign is that built-in (aka provided) converters will become normal converters. They will inherit from the Base converter and will self register using the `Converter.register_for` method. Doing so makes them available via the API for the first time.

Here's how easy it will be to subclass and replace the built-in HTML5 conveter.

```rb
class Html5Converter < (Asciidoctor::Converter.for 'html5')
  register_for 'html5'
  def paragraph node
    %(<p>#{node.content}</p>)
  end
end
```

Notice you don't even have to reference the built-in HTML5 by its class name.

The other major change is that global registration of converters will be thread-safe, using what we learned from designing the pluggable SyntaxHighlighter API. You can be registering converters in the same loop as converting documents and will never get a phantom read looking up existing converters.

Finally, the factory mechanism will be drastically simplified. We'll use the Factory/DefaultFactory/CustomFactory/DefaultFactoryProxy design from the SyntaxHighlighter API. And we'll add the `:converter_factory` option to the API to allow the factory to be entirely replaced (while preserving support for the `:converter` option).

The redesign is not expected to break existing uses of the Converter API. (Though there may be some changes necessary in the Asciidoctor.js API).

**Comment by mojavelinux** [comment]
We'll also promote the default implementation of the convert method from the BuiltIn class (now removed) to the Base class. If you want the default implementation, extend Base. If not, just include Converter.
