### ISSUE TITLE
Bibliography entry labels may not be an integer

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor#2911]
After reading https://asciidoctor.org/docs/user-manual/#user-biblio, I noticed that using numbers as labels results in the `id` attribute not being set, causing cross-references not to work. Document this somewhere?

**Comment by mojavelinux** [comment]
I have addressed this question in the documentation. I clarify that the label must be non-numeric and that you can have it show a number by using the xreftext.

See https://asciidoctor.org/docs/user-manual/#user-biblio
