### ISSUE TITLE
Opening and ending tag mismatch in docbook backend

### ISSUE THREAD

**Issue by rahrah** [asciidoctor/asciidoctor#2913]
This asciidoctor bad syntax creates bad xml without warning.

```
:doctype: book

= Title of Work

[very big]***Title of Work***
```
The incorrect line of xml created with out of order tags is this:

```
<simpara><emphasis role="strong"><phrase role="very big"><emphasis role="strong">Title of Work</phrase></emphasis></emphasis></simpara>
```
Apologies if this is intentional or reported before

**Comment by mojavelinux** [comment]
It's important to understand that there's no guarantee Asciidoctor will create valid XML. It certainly tries to, but it's possible to convince/force it to make invalid XML, just like it's possible to type invalid XML when writing in XML. This is just something you have to be aware of. It's a good idea to validate the XML after Asciidoctor generates it to check for these types of errors.

In this case, it's the unconstrained formatting marks that are causing the problem. Double asterisk pairs are matched anywhere, regardless of context. The remaining pair of asterisks then come behind to produce the invalid XML.

The correct syntax would be as follows:

```
[very big]*Title of Work*
```

**Comment by mojavelinux** [comment]
Thanks for reporting @rahrah. This is definitely something we're going to think about while implementing #61. We may be able to avoid this type of problem by taking that approach.
