### ISSUE TITLE
How to make calloutlist clickable?

### ISSUE THREAD

**Issue by danielmenezesbr** [asciidoctor/asciidoctor#2916]
How to make calloutlist clickable like AsciiDoc?

![video_2018-10-13_114154](https://user-images.githubusercontent.com/5949657/46906660-6311b800-cedd-11e8-9444-6fc869626101.gif)

**Comment by mojavelinux** [comment]
This would need to be done using a custom Asciidoctor converter. It's possible to make the callouts in both areas into a link. But it is not something that we plan to support out of the box.

If you need help, please ask questions in the project chat at https://chat.asciidoctor.org.
