### ISSUE TITLE
Slim::Engine emits warning about invalid option when using custom slim templates

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2928]
Since Slim 4, Slim now validates the names of all options passed to the template. Slim issues a warning for any option that isn't registered with Slim::Engine. Since the `:asciidoc` option is not registered, Slim::Engine emits a warning when using custom slim templates with Asciidoctor.

The fix is to register the `:asciidoc` option so Slim knows to expect it.

**Comment by mojavelinux** [comment]
cc: @ctargett

**Comment by ctargett** [comment]
Thanks @mojavelinux!
