### ISSUE TITLE
Processor crashes when child section of part skips level and section numbering is enabled

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#2931]
If section numbering is enabled (sectnums), but part numbering is not, and the child section of a part is out of sequence (skips a level), the processor crashes when computing the section number.

Example:

```
= Document Title
:doctype: book
:sectnums:

= Part

=== Out of Sequence Section
```

When converting to HTML, the following exception is encountered:

```
6: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/converter/html5.rb:328:in `section'
	 5: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/section.rb:117:in `sectnum'
	 4: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/section.rb:120:in `sectnum'
	 3: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:221:in `int_to_roman'
	 2: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:221:in `map'
	 1: from /home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:221:in `each'
/home/dallen/projects/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:222:in `block in int_to_roman': undefined method `divmod' for nil:NilClass (NoMethodError)
```

Related issue: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/371

**Comment by mojavelinux** [comment]
The hard part is what the correct behavior should be. To be consistent with how out of sequence sections are numbered in other scenarios, the missing segment should just be empty (i.e., `.1.`). That gives a clear signal there's a problem in the hierarchy in a graceful way.

**Comment by elextr** [comment]
If Asciidoc requires sections in the correct layering (which  I think it should) then there isn't any correct behaviour as the input is invalid (except not crashing of course :).  

Some message to the user would of be helpful, I would call it a non-fatal error, not just a warning.

**Comment by mojavelinux** [comment]
:+1: I believe that's exactly how I implemented it.
