### ISSUE TITLE
relative_path_from() fails if drive differs from root's

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#2944]
I'm getting a fatal error in v1.5.8 (on Windows 7/64-bit) related to the `relative_path_from` function.
The same docs that used to compile fine with v1.5.7 now throw this error:

**`Failed to load AsciiDoc document - different prefix: "O:/" and "B:/books/the-adoc-file"`**

NOTE:
"O:/" is the drive of the Asciidoctor root:
       `:asciidoctor-root: O:/Progs/Asciidoc`

Obviously, the relative path cannot be determined in this case, since the paths involved are in different drives. Maybe the prefix/drive should be checked before using the function.

**Comment by mojavelinux** [comment]
It looks like we're missing necessary exception handling. If the relative path can't be computed, the original path should just be returned.

**Comment by PauloFrancaLacerda** [comment]
Just for the records...
After changing `asciidoctor-root` to match the same adoc source file's drive, the compile error is gone, and the same (unaltered) docs are generated exactly as in v1.5.7, as expected.  :)

**Comment by mojavelinux** [comment]
I'm glad you found a workaround. Do you think we can defer the fix for 2.0.0?

**Comment by PauloFrancaLacerda** [comment]
> 
> 
> I'm glad you found a workaround. Do you think we can defer the fix for 2.0.0?

My case was easy to workaround and I can keep it the way it is until v2.0, as I don't need any of the new features or fixes in v1.5.8 right now. Hopefully, I'm the only to use different drives for root and adocs.

On the other hand, if a significant number of users (also using cross-drive paths) is looking forward to using v1.5.8, then you might feel some "pressure" for the fix.  :D
Since this is a fresh release, it might take some days (or weeks) until they come running to the forums crying aloud. We'll see soon.

**Comment by mojavelinux** [comment]
I've got the PR ready to go, so we'll wait a bit and see which direction to go with it.

**Comment by mojavelinux** [comment]
Since this is definitely needs to go into master, I'll merge it and slate it for 2.0.0. If we decide to make another release in the 1.5.x series for any reason, I'll backport it to that branch.

**Comment by SandMann1** [comment]
We get the same exception message when we include other asciidocs from UNC path.  For instance, my documents is located at c:\temp, this document has an include::\\server\styles\print.adoc[] and then the error is thrown.  Dont know if this is a separat issue or not?

**Comment by mojavelinux** [comment]
Are you using 1.5.8? You shouldn't be getting an exception anymore.

**Comment by mojavelinux** [comment]
Oops, my mistake. This fix hasn't been released yet. Have you tried using master?

**Comment by SandMann1** [comment]
@mojavelinux Thanks. I have just tried using master (after figuring out hot to do it :) ). The exception is not present on master.

**Comment by mojavelinux** [comment]
Thanks for testing!
