### ISSUE TITLE
Double dash in ID replaced to em-dash if in single quotes

### ISSUE THREAD

**Issue by VladimirSlavik** [asciidoctor/asciidoctor#2960]
In this syntax, a double dash gets turned into an em-dash:
```
[id='foo--bar']
```

However, two dashes are interpreted as two dashes in all of these id syntaxes:
```
[[foo--bar]]
[#foo--bar]
[id="foo-bar"]
```

I don't think the single quotes are meant to be special this way? In fact this "specialty" is a nasty surprise in some situations where tools might expect the IDs to be just plain ascii, as it was typed in. (Sad as it is to write that in 2018 when we have unicode.)

It's easy to work around, just unexpected.

**Comment by elextr** [comment]
Attribute values are [double quoted](https://asciidoctor.org/docs/user-manual/#setting-attributes-on-an-element) not single quoted.  Single quotes are markup.

**Comment by mojavelinux** [comment]
When you surround an attribute value in single quotes, you are asking for normal substitutions to be applied. This has been part of AsciiDoc since day one.

See https://asciidoctor.org/docs/user-manual/#attribute-list-substitutions

**Comment by VladimirSlavik** [comment]
Thank you! So it's literally not a bug but a feature. Solved, I'd say.

**Comment by mojavelinux** [comment]
I like that description!
