### ISSUE TITLE
Icons do not work as expected in buttons

### ISSUE THREAD

**Issue by Eiskasten** [asciidoctor/asciidoctor#2962]
`Lorem btn:[icon:pencil[]] ipsum` renders to Lorem [ **✎ ipsum** ] but should be Lorem [ **✎** ] ipsum. The same issue applies to `kbd:[]`. I also tried using substitutions like
`:pencil: icon:pencil[]
Lorem btn:[{pencil}] ipsum`
but that gives the same result. I think the problem is that brackets are not handled properly but I am not sure. I have the same issue with Asciidoctor PDF.

**Comment by Eiskasten** [comment]
That works fine, thanks and sorry for that. I think this can be closed.

**Comment by Mogztter** [comment]
With the new inline parser #61 it should be unnecessary to escape the bracket right ?

**Comment by mojavelinux** [comment]
I think it will still be necessary. A closing bracket is a valid character to use in the button text. So the backslash is needed to indicate whether the bracket is part of the text or the end of the macro. It's impossible to guess the intention otherwise.

**Comment by tigregalis** [comment]
Shouldn't it be the reverse, and the backslash should be used to indicate a literal backslash?

**Comment by mojavelinux** [comment]
To output a literal backslash where the backslash is reserved for escaping a character (as it is here), a double backslash would be needed. You can think of these as the same rules as escaping a double quote in a double quoted string.

**Comment by tigregalis** [comment]
Whoops, I meant a literal bracket: Shouldn't it be the reverse, and the backslash followed by a bracket, i.e. `\[` or `\]`, should be used to indicate a literal bracket?

So in this example, `btn:[Lorem icon:pencil[] ipsum]` would work from the inside out, i.e.
`btn:[Lorem icon:pencil[]] ipsum`
=> `btn:[Lorem ✎ ipsum]`
=> **[Lorem ✎ ipsum]**

"A closing bracket is a valid character to use in the button text."
When you need to use a closing (or opening) bracket as a character in the button text, you would *then* escape it using the backslash, i.e.
`btn:[Lorem\[icon:pencil[]\]ipsum]`
=> `btn:[Lorem\[✎\]ipsum]`
=> **[Lorem[✎]ipsum]**

Hence the reverse from how it works now.
