### ISSUE TITLE
Table::Cell and Table::Column don't implement block?

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#2963]
`Table::Cell` and `Table::Column` extend `AbstractNode` which defines the method `block?`.
However these classes don't provide an own implementation so that calling `block?` raises an exception.
Returning `false` seems to be a reasonable result to me.

**Comment by mojavelinux** [comment]
They don't implement AbstractBlock in core, but semantically they are blocks. At least Cell is. Column is more of abstract concept.

**Comment by robertpanzer** [comment]
So `Cell#block?` should return true and `Column#block?` should return false?
Because currently both calls raise exceptions.

**Comment by mojavelinux** [comment]
I definitely think Cell should implement AbstractBlock. That's supported by the fact that it's already duplicating several of the AbstractBlock properties. Some stuff won't apply, but I think it's a close enough fit. And we need it to complete #2524 too.

I'm still not convinced about Column. I think that should remain as a Node for now (even though it's a little bit of both). I suppose what we can do is just implement block? as false and leave it at that. Can you tell me what the use case is?

**Comment by mojavelinux** [comment]
ping @robertpanzer

**Comment by robertpanzer** [comment]
I stumbled over this exception while looking at this issue: https://github.com/asciidoctor/asciidoctorj/issues/726
It looks like all implementations of this method return true, except these which throw an exception.

**Comment by mojavelinux** [comment]
Gotcha. That's what I needed to know. Thanks!

**Comment by robertpanzer** [comment]
Sorry for replying late. 
I am drowning right now in Service Meshes :D

**Comment by mojavelinux** [comment]
No problem at all. I just wanted to make sure to get your :+1: before proceeding.

**Comment by robertpanzer** [comment]
Well, then 👍 🙂
