### ISSUE TITLE
Feature suggestion: formatting option for {localdate}

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor#2965]
Hi,

I would like to suggest a feature: ability to change the date format of the `localdate` attribute.

Thanks. Refael.

**Comment by elextr** [comment]
> The processor treats the value of this attribute as a string, so it doesn't matter what format you use for the string you assign.

A fine alternative.

**Comment by refaelsh** [comment]
Thanks every one. I understand. I consider this issue closed. @mojavelinux's solution to do it via CLI is excellent.
