### ISSUE TITLE
HTML Generator: change <!DOCTYPE html> and wrapp content in div with a given class name

### ISSUE THREAD

**Issue by deftmaster** [asciidoctor/asciidoctor#2967]
Hello,

is it possible somehow change the <!DOCTYPE html> and wrap the whole content into a div for HTML version of the document?

I can edit html5.rb, but it is not that flexible. 

Thanks in advance!

**Comment by mojavelinux** [comment]
Are you perhaps looking to generate embeddable HTML? If that's the case, you can do so by setting the `:header_footer` option to `false`:

```
puts Asciidoctor.convert_file 'document.adoc', safe: :safe, header_footer: false, to_file: false
```

This will give you something like:

```
<div class="paragraph">
<p>paragraph content</p>
</div>
```

Of course, you can then enclose that in a `<div>` as you see fit.

I need to understand more of your use case to provide further advice.

**Comment by deftmaster** [comment]
Hello Den,
thank you very much for the reply! I want to generate such an HTML document, that I can save as .docx (Ms Word) file. I can code the  css theme, and I have already coded header and footer (page numbers etc.) to integrate. When I manually copy and paste chunk of code (header and css), everything works fine.
But I need to automate the assignment with Gradle. I came up with the postprocessor ruby script. It can actually change in html the chunks (doctype, css). I have the only problem to integrate this script into Gradle in such a way, that I can transfer arguments also (name of the file to post process).
My experience says, that if the solution is complex, it’s a wrong solution, that is why I wrote to you. Maybe there is a standard and easy way to change doctype and wrap the code.
I am very new to ruby and to Gradle.
Thanks in advance and thank you very much for extremely fast replies. I do really appreciate this.

**Comment by deftmaster** [comment]
I have solved the problem, thanks!

**Comment by mojavelinux** [comment]
> I came up with the postprocessor ruby script. It can actually change in html the chunks (doctype, css).

Using a postprocessor is certainly one approach, though more brute force. If you really want to do it a nice way, I recommend using templates. Remember that every bit of HTML that Asciidoctor produces is controlled by the converter. And templates allow you to override anything that the converter produces.

For more info about using templates, see: https://github.com/asciidoctor/asciidoctor.org/issues/80

And the Gradle plugin supports loading templates directly. See https://github.com/asciidoctor/asciidoctor-gradle-plugin#options--attributes

**Comment by deftmaster** [comment]
Thanks for better understanding how asciidoctor works!
