### ISSUE TITLE
Conversion of AsciiDoc source code examples to DocBook 

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor#2974]
The plugin converts source code with a title 

```xml
.Asciidoctor
[source, ruby]
----
My Code
----
```

into the following DocBook construct:

```xml
<formalpara>
 <title>AsciiDoctor</title>
 <para>
<programlisting>My Code</programlisting>
</para>
</formalpara>
```

Is there a way to get the following, more common DocBook?

```xml
<example>
  <title> Test title </title>
  <programlisting>My code</programlisting>
</example>
````

**Comment by mojavelinux** [comment]
The output of a converter can be customized using templates. I'll explain to do it.

First, make sure you have the necessary dependencies installed.

```
gem install tilt slim concurrent-ruby
```

Then, create a folder to hold the DocBook templates:


```
mkdir -p asciidoctor-templates/docbook5
```

In that folder, create a template file named *listing.xml.slim* to create the DocBook for a listing block (which also handles the source block):

```slim
- if title?
  example id=@id role=(attr :role) xreflabel=(attr :reftext)
    title=title
    - if (attr? :style, 'source') && (attr? :language)
      programlisting language=(attr :language) linenumbering=((attr? :linenums) ? 'numbered' : 'unnumbered') =content
    - else
      screen=content
- else
  - if (attr? :style, 'source') && (attr? :language)
    programlisting(id=@id role=(attr :role) xreflabel=(attr :reftext) language=(attr :language)
        linenumbering=((attr? :linenums) ? 'numbered' : 'unnumbered')) =content
  - else
    screen id=@id role=(attr :role) xreflabel=(attr :reftext) =content
```

Then, activate the template by passing the template to the asciidoctor command:

```
asciidoctor -b docbook -T asciidoctor-templates document.adoc
```

You can do the same to customize any of the generated DocBook.

For more information about using templates, see https://github.com/asciidoctor/asciidoctor.org/issues/80.

**Comment by mojavelinux** [comment]
We could consider changing the default in Asciidoctor 2.0.0, but formalpara seems more correct to me than example since we already have the concept of an example block in AsciiDoc.

**Comment by mafritsch** [comment]
Thanks for the fast answer. I missed the example part in the documentation. That's exaxtly what I was looking for.
