### ISSUE TITLE
Document how to escape substitutions in tables

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor#2977]
Given this code, I wanted to render the `->` and `<->` unaltered:

```
[cols="1,2a,2a"]
|===
|Name |Description |`toString()` example

|Change move
|Change 1 entity's variable
|`Process-A {Computer-1 -> Computer-2}`

|Swap move
|Swap all variables of 2 entities
|`Process-A {Computer-1} <-> Process-B {Computer-2}`
|===
```

But those `->` and `<->` got substituted anyway. I looked through the documentation (quick syntax guide, writer guide and user manual) and found several suggestions on how to deal with it - but they all failed:

* backslash \
* `[literal]`
* `[subs="none"]`

For example, none of these work:

```
|`Process-A {Computer-1} <\-> Process-B {Computer-2}`
|`[literal]Process-A {Computer-1} <-> Process-B {Computer-2}`
|`[subs="none"]Process-A {Computer-1} <-> Process-B {Computer-2}`
```

None of these disabled the substitutions in my rendering (at least in the asciidoc version used by IntellIJ 2018.2.7's latest plugin). In the end, I found this trick somewhere in a github issue and it worked:

```
|`+Process-A {Computer-1} <-> Process-B {Computer-2}+`
```

Please document this approach (or fix `[literal]` or `[subs="none"]` in tables if those should work).

**Comment by mojavelinux** [comment]
This is explained by this section. https://asciidoctor.org/docs/user-manual/#literal-monospace Same goes for tables.

**Comment by ge0ffrey** [comment]
I must have read over that. I was probably doing ctrl-f for "escape" in the user guide at the time, so this must be a new section.
