### ISSUE TITLE
Side navigation will be broken in IE11

### ISSUE THREAD

**Issue by Hentaro1989** [asciidoctor/asciidoctor#2983]
There is a checkbox that "display intranet sites in compatibility view" in IE11 [Tools -> Compatibility View setting]. This is enable by default. So, If we put documents on an intranet,  It will be Compatibility Mode 5 or 7. Because, "IE=edge" has been commented by the conditional comment. Conditional Comments is just a comment on IE10 and more. For that reason, Style will be broken.

Gitter
https://gitter.im/asciidoctor/asciidoctorj?at=5c066dcb6c3c565096d0bd93

My pull request
https://github.com/asciidoctor/asciidoctor/pull/2978

e.g.
![image](https://user-images.githubusercontent.com/18099928/49482424-7a807800-f872-11e8-87c0-c8a470cc120b.png)

**Comment by mojavelinux** [comment]
For more information about why and when this happens, see https://github.com/google/web-starter-kit/issues/728.

Based on that information, we should follow the recommendation of the web-starter-kit and keep the meta tag without a conditional comment.
