### ISSUE TITLE
Bulleted Items at unexpected indent level

### ISSUE THREAD

**Issue by adam820** [asciidoctor/asciidoctor#2986]
Asciidoctor version: 1.5.8

Hello! In the following code snippet example, I'm seeing that a bulleted list that follows a numbered list appears to automatically fall within the indent of the last numbered item despite several blank lines of separation to indicate a new list. Is this by design?

````
. Numbered Item One
. Numbered Item Two
.. Sub Numbered Item
+
image::http://ushistoryimages.com/images/samuel-adams/fullsize/samuel-adams-1.jpg[]
+
. Another Item
+
image::http://ushistoryimages.com/images/lexington/fullsize/lexington-1.jpg[]


* Bulleted item
* Another bulleted item
````
In the resultant HTML, the `<li>`s of the bulleted list appear below _Another item_ instead of as their own 1st-level list:

````
<li>
  <p>Another Item</p>
  <div class="imageblock">
    <div class="content">
      <img src="http://ushistoryimages.com/images/lexington/fullsize/lexington-1.jpg" alt="lexington 1">
    </div>
  </div>
  <div class="ulist">
    <ul>
      <li>
        <p>Bulleted item</p>
      </li>
      <li>
        <p>Another bulleted item</p>
      </li>
    </ul>
  </div>
</li>
````

 Putting anything inbetween them (text, new section, etc.) results in the new list as expected.

**Comment by mojavelinux** [comment]
Yes, this is by design. Adjacent lists have a natural affinity to be part of the same hierarchy. If you want to force the lists apart, you need to add an interrupting line, which could be an empty block attribute list.

```
[]
* Bulleted item
* Another bulleted item
```

See https://docs.asciidoctor.org/asciidoc/latest/lists/separating/
