### ISSUE TITLE
Add multi-author examples

### ISSUE THREAD

**Issue by CosmicToast** [asciidoctor/asciidoctor#2987]
It is intended to be possible to specify multiple authors, as per the [quick reference](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header) note.

This is not sufficiently clear (the one example is hard to find), so this is a tracker of where it may make sense to reference this.
Further, it may make sense to specify the exact limits the parser has (for example, spaces ` ` are clearly ok between author names, are they ok on either side of the `;`? How about `\n's?)

Here are the locations that should be modified in some way:
- [ ] [Quick Reference](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header)
- [ ] [User Manual](https://asciidoctor.org/docs/user-manual/#author-and-email) (NOTE: already referenced, but add a way to specify multiple authors using the `:author:` submethod)
- [ ] [Writer's Guide](https://asciidoctor.org/docs/asciidoc-writers-guide/#the-document-header)

It may also make sense to clarify various `author_n` substitutions - i.e is it possible to list all authors, rather than add a new entry whenever a new author is added to a document.

**Comment by mojavelinux** [comment]
This has seen been documented in the official documentation.

https://docs.asciidoctor.org/asciidoc/latest/document/multiple-authors/

The writer's guide is no longer being updated and the quick reference is not intended to be comprehensive.
