### ISSUE TITLE
Asciidoctor is treating hyperlink-only footnotes as identical

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciidoctor#2994]
We are using the `reference` attribute of footnote nodes to work out whether the text in two footnotes is identical; if it is, they end up being assigned the same value.

Experimenting, it turns out that footnotes are considered distinct based only on their text value, and not based on the entirety of their markup.

Footnotes in our downstream processing are converted into `<link>` tags. The following source:

````
A.footnote:[https://scap.nist.gov/revision/1.4/#tools[A]]
A.footnote:[https://scap.nist.gov/revision/1.4/#tool1s[A]]
A.footnote:[https://scap.nist.gov/revision/1.4/#tool1s[B]]
A.footnote:[https://scap.nist.gov/revision/1.4/#tool1s[https://scap.nist.gov/revision/1.4/#tool1s]]
A.footnote:[https://scap.nist.gov/revision/1.4/#tool1s[https://scap.nist.gov/revision/1.4/#tools]]
A.footnote:[https://scap.nist.gov/revision/1.3/#tools]
B.footnote:[https://scap.nist.gov/revision/1.3/#tools1]
B.footnote:[https://abe.com[]]
B.footnote:[https://abe1.com[]]
````

is converted to have the footnote references (based on their `node["reference"]` values: 1, 1, 2, 3, 4, 3, 3, 3, 3. So the footnotes are considered distinct based on their text A, B, https://scap.nist.gov/revision/1.4/#tool1s, and https://scap.nist.gov/revision/1.4/#tools, while links that do not wrap text are considered identical to the first link found.

I think it would be preferable for the entire markup within the footnote being considered in order to establish whether the footnote is distinct (and assigned a different `node["reference"]` value), not just the text; and the conflation of `footnote:[https://scap.nist.gov/revision/1.4/#tool1s[https://scap.nist.gov/revision/1.4/#tool1s]]` with `footnote:[https://scap.nist.gov/revision/1.3/#tools]` appears to be a simple bug.

**Comment by opoudjis** [comment]
footnoteref:[] does not present this issue, since it enforces the identifier assigned to it. However footnoteref does not tolerate markup within the macro (such as URL markup), because it is greedier than footnote about grabbing the first closing bracket.

**Comment by mojavelinux** [comment]
I'm not sure what version of Asciidoctor you're using, but in my tests, every one of the footnotes in your example gets a discrete number.

As far as I know, the footnote does consider the whole of the (converted) markup when considering what is unique. (It cannot consider the original source since the links have already been converted by the time footnotes are processed...but it does use the entirely of the converted HTML).

> the conflation of `A.footnote:[https://scap.nist.gov/revision/1.4/#tool1s[https://scap.nist.gov/revision/1.4/#tool1s]] with B.footnote:[https://scap.nist.gov/revision/1.3/#tools]` appears to be a simple bug.

I get two distinct footnotes using this example.

**Comment by opoudjis** [comment]
They get distinct footnote numbers with the default HTMNL rendering; but they do not get distinct `node["reference"]` values, and that's what I'm using to detect whether the footnote content has been repeated.

**Comment by opoudjis** [comment]
You are right. Apologies.

**Comment by mojavelinux** [comment]
Excellent to hear! If you need any other assistance, don't hesitate to reach out. :beers:
