### ISSUE TITLE
Enable copycss attribute to copy any stylesheet, not just asciidoctor.css

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor#300]
Currently -a copycss only works for the default stylesheet, asciidoctor.css

But it seemed intuitive to me to use it to copy any specified stylesheet.

I attempted to do this, thinking colony.css would be copied to the output directory:

```
asciidoctor -a copycss -a stylesheet=colony.css -a stylesdir=../stylesheets sample.adoc
```

But ended up with this:

```
ls
asciidoctor.css  sample.adoc  sample.html
```

However, the colony.css stylesheet still gets applied to the output :flushed: 

Does using the copycss attribute for any stylesheet seem applicable?
At the least, it may be helpful if a warning were produced if someone else tries to use it as I did.

**Comment by suy** [comment]
The user manual still refers to 'copycss' as being broken. Should the documentation be updated?

**Comment by mojavelinux** [comment]
Yes.
