### ISSUE TITLE
Header indentation issue in sub-lists

### ISSUE THREAD

**Issue by xsrvmy** [asciidoctor/asciidoctor#3002]
I usually like using to indent sub-lists so that they are easier to read in text form. However, I cannot indent the header or header gets treated as text. For example:
```
- 1
- 2
  [loweralpha]
  . 2a
  . 2b
```
does not work

**Comment by mojavelinux** [comment]
That's not a supported syntax in AsciiDoc. It has to be written as:

```
- 1
- 2
[loweralpha]
. 2a
. 2b
```

An indentation has been proposed in #686, so I'm marking this as a duplicate.
