### ISSUE TITLE
Create xml:id for top level section does not work for DocBook conversion 

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor#3011]
I have an AsciiDoc document that should be converted into DocBook.
For example:

```
[[SectionID]]
= MyFirstSection
Some text
[[SubSectionID]]
== SubSection
Some text
```

Is converted into:

```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<section xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>MyFirstSection</title>
<date>2019-01-10</date>
</info>
<para>Some text</para>
<section xml:id="SubSectionID">
<title>SubSection</title>
<para>Some text</para>
</section>
</section>
```
As one can see, the inner section gets the xml:id but the outer one not.
I also tried the following:
```
[[SubSectionID]]
== SubSection

Some text
```
But this converts into:

```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<section xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>SubSection</title>
<date>2019-01-10</date>
</info>
<section xml:id="SubSectionID">
<title>SubSection</title>
<para>Some text</para>
</section>
</section>
```
That is, I have two nested sections instead of only one.

I'm not sure if this is a bug in the conversion, or if I haven't yet found the correct syntax.

I use the asciidoctor-maven-plugin version 1.5.7.1.

**Comment by mojavelinux** [comment]
I believe you mean the `<article>` tag. You shouldn't be getting a `<section>` tag at the top level (as that would be an invalid document).

You are correct that the ID on the document tag is not currently supported. We should allow this since it's allowed in the AsciiDoc syntax.

**Comment by mafritsch** [comment]
`<section>` is what I expected because I've set the `doctype` property in the asciidoctor-maven-plugin. In my use case, I have a complete DocBook toolchain with documentation in DocBook and I want to give the editors the ability to also write documents in AsciiDoc. These documents are converted into DocBook and included via `xi:include`  in the existing DocBook `<book>` documents.

**Comment by mojavelinux** [comment]
:scream: section is not a valid doctype, so use at your own risk ;)

Nonetheless, that's unrelated to the issue we're talking about here, since once we add ID to the root node, it will work no matter what the name of that root node is.
