### ISSUE TITLE
Internal links with hash in DocBook when customizing with docbook45 templates

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor#3013]
I use the asciidoctor-maven-plugin in version 1.5.7.1 and convert AsciiDoc files into DocBook.
An internal link:
`A link to another section in the document: <<Overview>>`
Gets converted into:
`<para>A link to another section in the document: <xref linkend="Overview"/></para>`
Exactly what I want. 
However, when I try to customize the link creation by copying the inline_anchors.xml.slim file from the https://github.com/asciidoctor/asciidoctor-backends/tree/master/slim/docbook45 repository:
```
- case @type
- when :ref
  anchor id=@target xreflabel=@text
- when :xref
  - if @text.nil?
    xref linkend=@target
  - else
    link linkend=@target =@text
- when :link
  ulink url=@target =@text
- when :bibref
  anchor id=@target xreflabel="[#@target]"
  | [#@target]
```
The line gets converted into:
`<para>A link to another section in the document: <xref linkend="#Overview"></xref></para>`
Now, I have a leading hash. That's not what I need for DocBook.
I have looked in the AsciiDoctor source code and found the following part in the docbook5.rb converter:
```
else
          linkend = node.attributes['fragment'] || node.target
          (text = node.text) ? %(<link linkend="#{linkend}">#{text}</link>) : %(<xref linkend="#{linkend}"/>)
        end
```
I would expect that node.target in the Ruby part is the same as @target in the Slim template and that the links should be the same? 
Unfortunately, I'm new in Ruby, Slim as well as AsciiDoctor so I expect, that I miss some pretty basic things here?

**Comment by mojavelinux** [comment]
The slim templates in the asciidoctor-backends repository where not updated as Asciidoctor evolved and are only mean at this point as a starting point. You can find the correct logic in Asciidoctor's built-in DocBook converter. See https://github.com/asciidoctor/asciidoctor/blob/d26821f99ce762af106dc4e7fce3453c688047ce/lib/asciidoctor/converter/docbook5.rb#L492-L518

If you need assistance porting this logic to your template, you are welcome to ask in the project chat at https://chat.asciidoctor.org.
