### ISSUE TITLE
Delegate date/time assignments to a method

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3029]
The goal is to abstract the document date resolution and attributes assignments when a `Document` is instantiated. And most specifically the following code:

https://github.com/asciidoctor/asciidoctor/blob/e6ff47641a0e4bcc5d9e5271eaaf5b6389f5cacc/lib/asciidoctor/document.rb#L490-L506

It will then be easier for Asciidoctor.js to provide the most accurate implementation.

**Comment by mojavelinux** [comment]
I came up with a way to consolidate these assignments in the PR.
