### ISSUE TITLE
Delegate sprintf to a method

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3032]
The goal is to be able to provide a small and fast implementation. 
`sprintf` method can do a lot of things and as a consequence Opal implementation is 500+ lines long: https://github.com/opal/opal/blob/35a5da9fdf5f82335791321787ac63cc5dcfd502/opal/corelib/kernel/format.rb

As you can see above we only use `sprintf` to replace a string within the format string. I think a simple `String.replace` should be sufficient as long as the pattern to replace is clearly identified: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

#### Current usage

https://github.com/asciidoctor/asciidoctor/blob/7cb74679da7634d4aa2508f4c488cffd9c835295/lib/asciidoctor/section.rb#L131-L134

https://github.com/asciidoctor/asciidoctor/blob/7cb74679da7634d4aa2508f4c488cffd9c835295/lib/asciidoctor/abstract_block.rb#L331

#### Performance

As mentioned by @mojavelinux `sprintf` is significantly faster then `sub` that's why we can just replace `sprintf sub_quotes('_%s_'), title` by `sub_quotes('_%s_').sub('%s', title)`

**Comment by Mogztter** [comment]
> What I can do to make it more domain-specific is to alias sprintf to a name that feels more appropriate to override. Thus, this issue is just about adding that alias to AbstractNode.

Yes I would prefer an alias 👍 

> How about fill_string_template? or replace_placeholder? or sub_placeholder?

I like `sub_placeholder`. 
The placeholder will be `%s` right ?

**Comment by mojavelinux** [comment]
Yes, we'll be following the sprintf contract (just a single feature, of course).

`sub_placeholder` sounds good to me. Consistent with the other methods too. And actually, I'll add it to Substitutors so it comes along with the other methods.
