### ISSUE TITLE
Don't mutate strings

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3054]
Asciidoctor should not mutate strings directly. It's already possible to enforce this behavior starting with Ruby 2.3 using either the `--enable-frozen-string-literal` CLI flag or the `frozen_string_literal` magic comment at the top of the Ruby source file. According to the latest reports, this restriction will be enforced *by default* starting in Ruby 3.0.

It used to be the case that mutating strings produced faster code (using sub! and gsub!), but that's no longer true. It's also not supported in Opal, which requires a not-so-pretty patch. Thus, for reasons of compliance, performance, and convenience, Asciidoctor should stop mutating strings directly.

We should also add the frozen_string_literal magic comment to the top of all Ruby source files as recommended by https://www.mikeperham.com/2018/02/28/ruby-optimization-with-one-magic-comment/.

**Comment by Mogztter** [comment]
@mojavelinux So we can remove https://github.com/asciidoctor/asciidoctor.js/blob/0d406257c484ef190746a1eba0dcf3a495190233/tasks/module/compiler.js#L66 ?

**Comment by mojavelinux** [comment]
Yep!
