### ISSUE TITLE
Literal comma in quote attribution

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3073]
Currently I haven't found a way to use literal comma in quote attribution, but sometimes it could be useful:

```
[quote, William Shakespeare, A Midsummer Night's Dream\, page 15]
____
The course of true love never did run smooth.
____
```

```
[quote, Abraham Lincoln, Speech at Peoria\, Illinois (1854)]
____
Slavery is founded in the selfishness of man's nature - opposition to it, in his love of justice.
____
```

**Comment by mojavelinux** [comment]
If an attribute value contains a comma, then the attribute value must be enclosed in quotes.

If you don't want substitutions to be applied to the value, then enclose the value in double quotes.

If you want substitutions to be applied to the value, then enclose the value in single quotes.

You can learn more in the documentation here: https://asciidoctor.org/docs/user-manual/#named-attribute

**Comment by john-cj** [comment]
Indeed, it works, thanks. I was already aware about quotes (compare `role=role` with `role="role1 role2"`), but haven't assume that they will work in this case as well.

**Comment by mojavelinux** [comment]
Yep. All block attributes are parsed with the same rules (whether built-in or custom).

It's always safe to use quotes. For those who like to save characters, you have the option to drop the quotes as long as the value doesn't contain characters reserved for attribute parsing (such as a comma or quotes).
