### ISSUE TITLE
Code within italic and code within bold - sometimes works differently

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3082]
Consider this example:

> To make things clear, I use _`w` > Enter Visual mode > `13wh` > `y`_ instead of _`wv13why`_.

(It's from my Vim guide.)

You would need to use double backticks around `w` and `y`:

```
To make things clear, I use _``w`` > Enter Visual mode > `13wh` > ``y``_ instead of `_wv13why_`.
```

However, if you want to emphasize the inner text with bold instead of italic, it will be enough to use single backticks:

```
To make things clear, I use *`w` > Enter Visual mode > `13wh` > `y`* instead of `*wv13why*`.
```

Is it by design?

Complete test:

```
:stylesheet!:
:nofooter:

To make things clear, I use _``w`` > Enter Visual mode > `13wh` > ``y``_ instead of `_wv13why_`.

To make things clear, I use *`w` > Enter Visual mode > `13wh` > `y`* instead of `*wv13why*`.
```

**Comment by mojavelinux** [comment]
Yes, this is the expected (and tested) behavior. The reason for the difference is that underscore is a word character, whereas asterisk is not. Constrained formatting can only be applied around the boundaries of a word, whereas unconstrained formatting can be placed anywhere. (Technically constrained formatting is more nuanced than that, but it's a good way to think of it).

Think of the underscore as a letter like "a":

```
a``w`` > Enter Visual mode > `13wh` > ``y``a
```

Then it should become clear why double (unconstrained) backticks are necessary.

You can read more about these rules here: https://asciidoctor.org/docs/user-manual/#formatting-marks

**Comment by john-cj** [comment]
Understood, thanks.
