### ISSUE TITLE
When using vertical header and cell span in table, other cells are emphasis.

### ISSUE THREAD

**Issue by typetonk2** [asciidoctor/asciidoctor#3088]
I write the vertical header table.

```
.vertical + span
[cols="h,d,d", options="autowidth"]
|===
|header 1 |Cell in column 2, row 1 |Cell in column 3, row 1
.2+|cell spans header 2 and 3
|Cell in column 2, row 2
|Cell in column 3, row 2
|Why is it emphasis?
|Cell in column 3, row 3
|===
```

I think only the vertical header column would be emphasis, but other cells were also emphasis.

![adoc](https://user-images.githubusercontent.com/1439590/53067982-fa38ed00-3519-11e9-9298-0e41323e86fd.png)

How can I emphasis only the vertical header column?

---

* asciidoctor 1.5.8

**Comment by john-cj** [comment]
I don't understand the technical background (I'm not a developer of Asciidoctor), but this could be fixed with `a` column attribute:

```
[cols="1h, 3*", stripes="none"]
|===
|A1
|B1
|C1
|D1

.3+|A2 + A3 + A4
|B2
|C2
|D2

a|B3
|C3
|D3

a|B4
|C4
|D4
|===
```

**Comment by typetonk2** [comment]
@john-cj 
As I expected result. Thank you!

**Comment by mojavelinux** [comment]
Indeed, a quick fix is to set the type on the cell. The root cause is a duplicate of this issue: #989. It's a side effect of how cell spans are handled.
