### ISSUE TITLE
How can GitHub deal with the change in treatment of invalid character IDs such as apostrophe being removed instead of converted to idseparator?

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3093]
Hi there,

I noticed that there was a backwards incompatible change documented at https://asciidoctor.org/docs/user-manual/#auto-generated-ids

>  Prior to 1.5.7, HTML/XML tags were not removed and character references and invalid ID characters were replaced with the value of the idseparator attribute (_ by default).

Is there an option to go back to old behavior?

I can fix my own asciidotor version and never update it (not ideal) to keep my header IDs constant on my website for example, but if there is no such option, I'm just curious how GitHub will deal with it without breaking `<<>>` in existing READMEs, where users can't control the asciidoctor version used.

I'm lazy to grep the source now to find commit / PR, hopefully this will help fill the issue keyword database :-)

Thanks for awesome software.

**Comment by cirosantilli** [comment]
Ah, I think these are it:

- https://github.com/asciidoctor/asciidoctor/pull/2679
- https://github.com/asciidoctor/asciidoctor/issues/794

https://github.com/asciidoctor/asciidoctor/issues/794#issuecomment-381819341 ACKs it is a breaking change.

So I guess I'm just asking how asciidoctor deals with breaking changes in general, in particular semver seems not used and breaking changes happen across 1.x versions.

Not saying this is a bad change of course though ;-)

**Comment by mojavelinux** [comment]
>  I guess I'm just asking how asciidoctor deals with breaking changes in general, in particular semver seems not used and breaking changes happen across 1.x versions.

This post explains our position (and where we are headed) https://asciidoctor.org/news/2018/12/31/making-the-switch-to-semver/

> Is there an option to go back to old behavior?

It's not possible to control which version of Asciidoctor GitHub runs. It will run the version that GitHub chooses. This may change once we get an AsciiDoc specification in place...then it will be possible to set the version of your document. (See https://asciidoctor.org/news/2019/01/07/asciidoc-spec-proposal/).

**Comment by mojavelinux** [comment]
When it comes to IDs, the situation is a bit different. Asciidoctor doesn't control how IDs are generated on GitHub. That's handled by GitHub's HTML processing code after Asciidoctor runs. This has always been a challenge. We may eventually be able to convince them to use Asciidoctor's ID generator, but that it going to take time.

Asciidoctor does it's best to generate IDs in the same way as GitHub for this very reason...though we can't follow it exactly since some of those rules just aren't compatible with how AsciiDoc works. So it's a best effort.

**Comment by cirosantilli** [comment]
Thanks for clarifying! :-)
