### ISSUE TITLE
Exclude certain sections from output file

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3094]
Is there an option, similar to `[discrete]`, to exclude particular sections from a document? E.g., it could be useful for the sections which are considered for the writer personal use, as well as the ones which should be reworked and therefore excluded just temporary:

```
:toc:
:includedir: _includes

= Main section

== Section 1

include::{includedir}/file1.adoc[]

[excluded]
== Section 2

// Should be completely reworked according to new ISO-12345:2019

include::{includedir}/file2.adoc[]

[excluded]
= INTERNAL USE

== TODO

include::{includedir}/TODO.adoc[]

== TRASH

include::{includedir}/probably-useful.adoc[]

include::{includedir}/i-dont-understand-what-is-it.adoc[]

include::{includedir}/some-old-things-which-are-in-no-use-currently.adoc[]
```

**Comment by Mogztter** [comment]
Hello @john-cj,

You could use a block comment:

```adoc
////
to rework
////
```

Or you could also use a Tree extension to remove the block if it has an `excluded` role.
Another idea is to use a conditional directive:

```adoc
ifdef::env-draft[]
This section is not yet approved.
endif::[]
```

Does that answer your question ?

**Comment by john-cj** [comment]
Thanks, `ifdef` works for me:

```adoc
// Temporary disabled:
// :draft:

ifdef::draft[]
= DRAFT

== TODO

* Do something
endif::[]
```

It could be used as the workaround. However, it's not so convenient as a single attribute (obviously, because you have the closing `endif::[]`). The difference could be significant when you need to quickly (temporary) disable individual chapters.

**Comment by Mogztter** [comment]
I'm not aware of a built-in feature to exclude a section from the output file.
But since Asciidoctor is extensible you could write a Tree processor to do what you've described. 

A simpler solution, would be to style the block:

```
[hidden]
== Draft

This section is still a work in progress...
```

```css
.hidden {
  display: none;
}
```

The block will still be in the output but hidden by the stylesheet.

**Comment by john-cj** [comment]
Good idea. Though, it will be even better to prevent its appearance in HTML completely.

**Comment by john-cj** [comment]
Duh! It could be solved with a role.

```
[.hidden]
= TODO

* Do something

<style>
.hidden { display: none; }
</style>
++++
```

**Comment by mojavelinux** [comment]
You'll be happy to know that there's already a built-in role in the default stylesheet to do this.

```
[.hide]
== Draft
```
