### ISSUE TITLE
AbstractBlock#find_by should discover blocks inside AsciiDoc table cells

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3101]
The find_by method should descend into AsciiDoc table cells and return any matching blocks inside those cells as well.

This issue was spun off from #2524.

**Comment by mojavelinux** [comment]
Since this wasn't the behavior prior Asciidoctor 2.0, I wonder if we should introduce an option to control whether these cells are considered. My instinct is to say no since a) it's logic that they would be found and b) it's possible to detect and veto these blocks.

**Comment by mojavelinux** [comment]
To maintain compatibility with existing code, I decided to add the option `traverse_documents` to control whether blocks inside AsciiDoc table cells are considered.

```rb
doc.find_by context: :paragraph, traverse_documents: true
```

This option is false by default. If true, find_by will cross the boundary of the current document and enter the AsciiDoc table cell (which is technically a discrete, nested document).

**Comment by Mogztter** [comment]
> To maintain compatibility with existing code, I decided to add the option `traverse_documents` to control whether blocks inside AsciiDoc table cells are considered.
> This option is false by default. If true, find_by will cross the boundary of the current document and enter the AsciiDoc table cell (which is technically a discrete, nested document).

`traverse_documents` is here to stay or is it just an intermediate step ?

**Comment by mojavelinux** [comment]
> `traverse_documents` is here to stay or is it just an intermediate step ?

I haven't decided yet. But it does seem valuable to be able to look only in the current document. That's possible with a filter block, but this just makes it a bit easier. For example, if you just want the sections that are candidates for the TOC, you leave this option off and set `context: :section`. So that's certainly a strong enough use case to want to keep it. The same could be true if we ever introduce subdocuments.

**Comment by Mogztter** [comment]
> I haven't decided yet. But it does seem valuable to be able to look only in the current document. That's possible with a filter block, but this just makes it a bit easier. For example, if you just want the sections that are candidates for the TOC, you leave this option off and set `context: :section`. So that's certainly a strong enough use case to want to keep it. The same could be true if we ever introduce subdocuments.

All good 👍 
I was asking because if it was an intermediate step I would have argued 😉
