### ISSUE TITLE
Two lists deep items can't be dedented

### ISSUE THREAD

**Issue by domenkozar** [asciidoctor/asciidoctor#3108]
```
1. 1-deep
2. 1-deep
   * 2-deep
   * 2-deep
+
1-deep
3. 1-deep
```

The last `1-deep` in 2. should not be part of 2-deep, but rather deindented.

**Comment by Mogztter** [comment]
I might be missing your point but you are using the list continuation item `+` so `1-deep` will be part of `2-deep`.

You want the last `1-end` to be outside of the list ? or to be numbered `3` ?

```
. 1-deep
. 1-deep
** 2-deep
** 2-deep
. 1-deep
. 1-deep
```

![result](https://user-images.githubusercontent.com/333276/53515057-66db5b00-3ac9-11e9-9ad6-9f1420291a66.png)

```
. 1-deep
. 1-deep
** 2-deep
** 2-deep

1-deep

[start=3]
. 1-deep
```

![result1](https://user-images.githubusercontent.com/333276/53515226-c6d20180-3ac9-11e9-9caa-d5cd1d3a2dc4.png)

**Comment by domenkozar** [comment]
In your last example, 1-deep should be aligned with 2.

**Comment by mojavelinux** [comment]
This is admittedly a bizarre aspect of the AsciiDoc syntax, but you use blank lines to jump back a level. In your example, it would be:

```
. 1-deep
. 1-deep
   * 2-deep
   * 2-deep

+
1-deep
. 1-deep
```

(I'd eventually like to find a better way to do this because it feels a bit fragile).

**Comment by elextr** [comment]
Shouldn't it be spelled:

```
. 1-deep
. 1-deep
+
--
   * 2-deep
   * 2-deep
--
+
1-deep

. 1-deep
```

making it obvious what groups with what.

**Comment by mojavelinux** [comment]
I agree with @elextr's recommendation. That's a great way to make it explicit. And it's how I prefer to do it when I have that situation. The situation is rare enough that this might actually be a reasonable approach to settle on.

**Comment by domenkozar** [comment]
![2019-03-01-133859_186x272_scrot](https://user-images.githubusercontent.com/126339/53620947-c41bfd00-3bec-11e9-8ad3-5a3d135f00b3.png)

This looks good. Thank you! /cc @roberth
