### ISSUE TITLE
plans for release 1.5.9?

### ISSUE THREAD

**Issue by hakandilek** [asciidoctor/asciidoctor#3109]
There's a huge list of unreleased improvements and fixes in the change log. Is there a plan to release a 1.5.9 version or will it be jump to 2.x?

**Comment by Mogztter** [comment]
Indeed and I believe that 2.0 will be released soon. Please bear with us 😄

**Comment by mojavelinux** [comment]
I am trying to get it released as soon as humanly possible. We've been
working through the last remaining integration bugs and merging scheduled
PRs. It has taken longer than expected, but we're almost there.

**Comment by mojavelinux** [comment]
And yes, it will be 2.0. There will be no 1.5.9.

**Comment by hakandilek** [comment]
Thanks for the answers. I'm closing this one. 
May the force be with you. :smile:
