### ISSUE TITLE
Drop the verse table cell style

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3111]
A verse doesn't make much sense without attributes and, yet, there's no way to set attributes on a verse table cell (or any table cell, for that matter). Plus, the AsciiDoc cell style already provides a way to include a (fully-configurable) verse block in a table cell. We can also point out that there's no quote cell. The verse cell style just seems out of place in the model.

(The purpose of the table cell style is to set the content model and formatting shorthand, not to be a substitute for block types. The one exception is the literal style, which most closely resembles the literal paragraph, albeit supporting double line breaks.)

Given that the verse table cell is an outlier in the model, and rarely (if ever used), it should be dropped.

**Comment by mojavelinux** [comment]
I searched all the AsciiDoc files on my computer (> 45,000) and I could not find a single usage of the verse table cell style that wasn't a test of Asciidoctor itself. I think that proves just how useless this cell style is and the fact that nobody is going to miss it. (It also doesn't format correctly on GitHub).

**Comment by mojavelinux** [comment]
Interesting to note that if by chance you did want to put a sonnet in a table cell and not use a verse block in an AsciiDoc table cell, you could still use a literal table cell, add a role to the table, then use CSS to set the font family of the table cell to a prose font. And the best part of that solution is that it would still look right on GitHub (though in monospaced font). The :8ball: says YES.

**Comment by knieriem** [comment]
What I liked about the verse table cell style is that it prevented unintended line wrapping, while still having provided a variable-width font. My concrete use case is a column with SemVer version strings like 0.2.1-pre1+buildmetadata, where there may be a hyphen within the version string. In a table with quite a few columns I could prevent line wraps at the hyphens' positions by using the `v` specifier. The easiest way to get to a comparable result may be replacing hyphens by U+2011, or wrapping the text into `[nowrap]#...#`. (So perhaps what I needed is not actually the _verse_ table style, but rather a _white-space:nowrap_-like column formatting option).

**Comment by mojavelinux** [comment]
> So perhaps what I needed is not actually the verse table style, but rather a white-space:nowrap-like column formatting option

Exactly. Your testimony only further proves that this style was irrelevant since you weren't actually using it to style a verse. In other words, it was rarely used for the purpose for which it was intended.

What it sounds like you need is the new nobreak or nowrap roles added in Asciidoctor 2.0.11.

```
|[.nowrap]#do not wrap me#
```

nobreak disables forced line breaks, whereas nowrap disables breaks entirely.

**Comment by knieriem** [comment]
Thanks for pointing out nowrap and nobreak _roles._
