### ISSUE TITLE
Interdocument xref with parent path doesn't resolve in master doc

### ISSUE THREAD

**Issue by Shadowfiend** [asciidoctor/asciidoctor#3136]
We're currently working with a directory structure that looks somewhat like this:
```
/
  index.adoc
  section1/
    index.adoc
  section2/
    index.adoc
```

The top-level `index.adoc` is a master document with some top-level content that includes the section docs, in this style:

```
= Title

== Introduction

...

include::section1/index.adoc[leveloffset+=2]
include::section2/index.adoc[leveloffset+=2]
```

The goal in this structure is to have each section document stand alone when possible (we do a small amount of additional attribute trickery to manage rendering the TOC vs not in the section subdocuments). For this reason, we want interdocument links that resolve to interdocument links when we're working with the subdocuments, but resolve to internal links when the master doc is being built (seems like what #844 was meant to implement). Here's the kind of link that doesn't work that way, in e.g. the `section1/index.adoc` file:

```
This is described in more detail in <<../section2/index#,its own section>>.
```

When compiling standalone, the correct link is generated. However, when compiling the master doc, the resulting link is still a link to a relative file, `../section/index.html`. I was on an older version of Asciidoctor and thought #2642 may have fixed this, but after upgrading I'm unfortunately seeing the same issue.

Any thoughts on what might help here, or if it's a bug? I've also tried a few variants of the `xref` macro (`This is described in more detail in xref:../section2/index#[its own section].`, as well as with the `.adoc` extension) that likewise don't seem to have worked.

**Comment by Shadowfiend** [comment]
Just realized the same canonicalization of paths is also failing to happen for images. In this case we generate images to a top-level directory, `img/generated/....png`, and references of the type `image::../img/generated/...[alt]` resolve when compiling the child doc, but keep the `..` reference when compiled in the parent doc.

**Comment by mojavelinux** [comment]
@Shadowfiend you've got it. The include directive is not a subdocument. It is a stream combiner. It doesn't have any awareness of context.

**Comment by Shadowfiend** [comment]
Still struggling with the xref directive, but I’ve started tracing the codebase on this one so... I’ll report back haha.
