### ISSUE TITLE
Exception "Invalid id given" when source language is invalid during editing

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor#3137]
When editing a document, the contents might temporarily have a strange syntax. 

Expected behavior: Asciidoctor should still render some meaningful output to allow a preview. 

Actual behavior: The following snippet produces an Exception "org.jruby.exceptions.ArgumentError: (ArgumentError) Invalid id given: j n" when rendering with AsciidoctorJ 1.6.2 with CodeRay. This was first reported by a user of the Asciidoc IntelliJ Plugin: https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/240

````
[source,j a]
----
anything
----
````

I wonder what the expected behavior should be: parse the language, and ignore it if it doesn't match a valid pattern understood by CodeRay (like regex `^[a-z_]*$`)?

**Comment by mojavelinux** [comment]
This is just a matter of catching CodeRay's error and falling back to a generic syntax highlighter. I hadn't realized CodeRay threw an exception, so now I have something to test.
