### ISSUE TITLE
Infinite loop with leveloffset = -1

### ISSUE THREAD

**Issue by deining** [asciidoctor/asciidoctor#3152]
The following syntax will cause Asciidoctor to loop infinitely:

```
= My Title
:doctype: book
:leveloffset: -1

= My part
```

I'm fully aware that this "wrong" syntax does not make sense, but this should not cause an infinite loop, but output some kind of warning / error message instead. Tested with Asciidoctor 1.5.8 and Asciidoctor 2.0.0.rc.2

**Reproduction**

````
$ echo -e "= My Title\n:docbook: true\n:leveloffset: -1\n\n= My part" | asciidoctor -

Ctrl-C to terminate infinite loop

$ asciidoctor -v
Asciidoctor 1.5.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:CP850 ex:CP850)

**Comment by mojavelinux** [comment]
Thanks for reporting!

**Comment by mojavelinux** [comment]
The solution is simple. We just need to protect against the level from going negative.
