### ISSUE TITLE
Warn if ifeval doesn't match

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#3161]
Right [now](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/reader.rb#L955) if `ifeval` contains an invalid expression it is considered `false`. I think it'd be a little more friendly to emit a warning here.

If this is something that you'd like in Asciidoctor I'd be happy to open up a pull request!

**Comment by mojavelinux** [comment]
Now that we have a proper logger in Asciidoctor, I agree this is a good place to make use of it. I'll go ahead and submit a PR since I'm currently working to get 2.0 out the door.
