### ISSUE TITLE
Using attributes in custum ID return warning

### ISSUE THREAD

**Issue by SandMann1** [asciidoctor/asciidoctor#3172]
Running asciidoctor 1.5.8 on ruby 2.5.1p57 with `--verbose --failure-level ERROR` See attached example file.

I apologize if this has already been clarified. My search effort failed to find anything.

We start docments defining an attribute i.e `:anchor: some_test_`. Then we use this attribute in custum ID related to sections, like this:
`[[{anchor}typeReference]]`

`== Why do we use it?`

When referencing this ID and running asciidoctor the verbose output logs 

> asciidoctor: WARNING: invalid reference: some_test_typeReference

The reference is working as expected in the resulting html, but this means that we cannot use the build output as a reliable source of error indications on the warning level. 

Any suggestions? Are we using the custum ID in an unintended way?

[index.zip](https://github.com/asciidoctor/asciidoctor/files/2987061/index.zip)

**Comment by mojavelinux** [comment]
You need to define your anchors this way:

```
[#{anchor}typeReference]
== Why do we use it?
```

I can't exactly remember why it's different, but that gives you the result you're looking for. It's best to use the modern syntax for defining anchors on sections.

**Comment by SandMann1** [comment]
Ah. Thank you. That does the trick.

**Comment by mojavelinux** [comment]
I remember why. It's because attribute references are not allowed in the old-style section anchor (same as in AsciiDoc Python)...so it actually is an unresolved reference because the section isn't being created.
