### ISSUE TITLE
Which HTML char refs does `replacements` translate?

### ISSUE THREAD

**Issue by no-simpler** [asciidoctor/asciidoctor#3174]
On Asciidoctor `2.0.0.rc.1`, the following source:

```asciidoc
[subs=replacements]
&amp;
&amp;amp;
&dagger;
&dagger;dagger;
&amp;dagger;
```

produces the following HTML:

```html
<p>
&amp;
&amp;
&dagger;
&dagger;dagger;
&dagger;
</p>
```

Only second and fifth specimens are touched by the `replacements` substitution.

How does Asciidoctor decide, when to translate and when not to?

Evidently, it treats `&amp;` specially. But what is the actual underlying logic? I don’t think the manual explains this enough.

**Comment by no-simpler** [comment]
Ah, right. This:

> The `replacements` element depends on the substitutions completed by the `specialcharacters` element.

What this must mean is: _`replacements` assumes that `specialcharacters` has run before it_.

So it looks for patterns like these: `&amp;XXXXXX;`, assumes that the `&amp;` part is `specialcharacters`’s handiwork, and restores the ampersand to form an HTML character reference.

This is why it does not touch the free-standing `&amp;`, or anything that does not fit the character reference pattern, e.g., `&amp;@@;` remains `&amp;@@;`.

Important notes (from my own experience):

1. The approach is not entirely robust, e.g., `&amp;bogus;` is ’restored’ to nonsense `&bogus;`.
2. Restoration goes exactly one level deep, e.g., `&amp;amp;dagger;` becomes `&amp;dagger;`.

**Comment by mojavelinux** [comment]
Your observations are correct.

The current implementation is largely a side effect of regular expression-based parsing. This is something we can revisit and perhaps make more robust as part of #61 (which we've been actively investigating already).

**Comment by mojavelinux** [comment]
I would say right now that the replacements are pretty casual. They are not meant to cover every edge case, but to provide some reasonable shorthand for writing.
