### ISSUE TITLE
AD swallows first line of included file

### ISSUE THREAD

**Issue by pilhuhn** [asciidoctor/asciidoctor#318]
I have a document decomposed into several files

I do 

```
include::foo[]
include::bar[]
```

Now when `foo.adoc` does not end in an empty line, the first line of `bar.adoc` is swallowed -- at least in my case where bar started with a `= bla` line

AD should perhaps always append an empty line on include

**Comment by mojavelinux** [comment]
The behavior for this has gone back and forth, most recently #3470. The ability to control the behavior is now described in #3875.
