### ISSUE TITLE
Remap old pos_attrs extension option to new name

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3199]
Some extensions rely on the low-level option name for positional attributes (such as Asciidoctor Diagram). If the old option name is used (`:pos_attrs`), automatically remap it to the new option name (`:positional_attrs`). This change should only be made for the static `option` method. If the DSL is used, the vanity method is preferred (`positional_attributes`).

**Comment by mojavelinux** [comment]
```rb
def option key, default_value
  config[key == :pos_attrs ? :positional_attrs : key] = default_value
end
```


cc: @pepijnve @robertpanzer 

I had made the assumption the everything was routed through the DSL methods, but that's not true for Asciidoctor Diagram and AsciidoctorJ.

**Comment by mojavelinux** [comment]
I thought about remapping the option when it's assigned, but the problem is that there are so many different ways of assigning the option that it gets a bit hairy. It's far easier to just look for `:pos_attrs` as a fallback if `:positional_attrs` is not found.

**Comment by pepijnve** [comment]
@mojavelinux does 1.5 have DSL methods for positional attributes? I was under the impression those were added in 2.x.

**Comment by mojavelinux** [comment]
The DSL methods have been there since 1.5.0. They haven't really stabilized completely until now, but they've certainly been available.

**Comment by pepijnve** [comment]
Well in that case there's a simple fix for asciidoctor-diagram, just use the DSL. Can't really remember why I didn't do that in the first place.
