### ISSUE TITLE
not applying verbatim substitution to literal paragraphs inside list

### ISSUE THREAD

**Issue by tmzullinger** [asciidoctor/asciidoctor#3205]
I'm attempting to build the git documentation with asciidoctor-2.0.x and the docbook5 backend.  A number of the documents produce invalid xml due to what looks like a failure to escape angle brackets.  One example is in [git-http-fetch.txt](https://github.com/git/git/blob/041f5ea1c/Documentation/git-http-fetch.txt#L37-L41), excerpted here:

```
--stdin::
	Instead of a commit id on the command line (which is not expected in this
	case), 'git http-fetch' expects lines on stdin in the format

		<commit-id>['\t'<filename-as-in--w>]
```

Running `asciidoctor -b docbook5 -d manpage -o git-http-fetch.xml git-http-fetch.txt` produces the following for the excerpted section above:

```
<varlistentry>
<term>--stdin</term>
<listitem>
<simpara>Instead of a commit id on the command line (which is not expected in this
case), <emphasis>git http-fetch</emphasis> expects lines on stdin in the format</simpara>
<literallayout class="monospaced"><commit-id>['\t'<filename-as-in--w>]</literallayout>
</listitem>
</varlistentry>
```

The brackets around `commit-id` and `filename-as-in--w` should be converted to `&lt;` & `&gt;`.

This works in asciidoc and asciidoctor < 2.0.0, so I think it's a bug with 2.0.x.  But I could certainly be wrong.  :)

(I know that asciidoctor can convert directly to a manpage as well, which would avoid this issue.  For the moment, git would prefer to keep using the docbook/xmlto chain while still supporting asciidoc as well.)

**Comment by mojavelinux** [comment]
What the ?!?. I'm looking into it...

**Comment by mojavelinux** [comment]
FYI, this has nothing to do with the DocBook converter. The problem is that no substitutions are being set on a literal paragraph inside a list.

**Comment by mojavelinux** [comment]
I see the error in my ways. As it turns out, this was actually broken in a different way in 1.5.8 (and perhaps even earlier). It's just noticeable broken in 2.0.0. All because we're missing some tests. But the fix for it is pretty straightforward.

**Comment by tmzullinger** [comment]
Thanks for making short work of this @mojavelinux!  I tested the commit on top of 2.0.1 last night and the git docs build successfully.  In case anyone finds this later, here's the minimal patch to the [git Documentation](https://github.com/git/git/blob/041f5ea1c/Documentation/Makefile#L192-L201) build to use docbook5 for generating the man pages:

```diff
diff --git a/Documentation/Makefile b/Documentation/Makefile
index 4e4dd7ecf1..6b711d5110 100644
--- a/Documentation/Makefile
+++ b/Documentation/Makefile
@@ -193,11 +193,12 @@ ifdef USE_ASCIIDOCTOR
 ASCIIDOC = asciidoctor
 ASCIIDOC_CONF =
 ASCIIDOC_HTML = xhtml5
-ASCIIDOC_DOCBOOK = docbook45
+ASCIIDOC_DOCBOOK = docbook5
 ASCIIDOC_EXTRA += -acompat-mode -atabsize=8
 ASCIIDOC_EXTRA += -I. -rasciidoctor-extensions
 ASCIIDOC_EXTRA += -alitdd='&\#x2d;&\#x2d;'
 DBLATEX_COMMON =
+XMLTO_EXTRA += --skip-validation
 endif
 
 SHELL_PATH ?= $(SHELL)
```

There's still ongoing work to fix up minor differences between asciidoc and asciidoctor, so we might turn up other issues / have some questions.  Many thanks for such a quick fix!

**Comment by mojavelinux** [comment]
That's great to hear! I'm happy to be part of the solution ;)
