### ISSUE TITLE
Problem with asciidoctor-bibtex after update to asciidoctor 2.0.1

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#3207]
Updating to asciidoctor 2.0.1 crashes asciiidoctor-bibtex. I have also reported this as an issue at the asciidoctor-bibtex archive. I get the following stacktrace:

/home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:103:in `block in process': asciidoctor: FAILED: /home/pela/svnroot/QAG/dcs-make/sample/sample.txt: Failed to load AsciiDoc document - undefined method `lines' for #<Asciidoctor::Table::Cell:0x0000000601aa66d8> (NoMethodError)
Did you mean?  lineno
Did you mean?  lineno
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:98:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-bibtex-0.3.1/lib/asciidoctor-bibtex/bibextension.rb:98:in `process'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/document.rb:557:in `[]'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/document.rb:557:in `block in parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/document.rb:556:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/document.rb:556:in `parse'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor.rb:1301:in `load'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor.rb:1410:in `convert'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor.rb:1518:in `block in convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor.rb:1518:in `open'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor.rb:1518:in `convert_file'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/cli/invoker.rb:126:in `block in invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/cli/invoker.rb:109:in `each'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/lib/asciidoctor/cli/invoker.rb:109:in `invoke!'
        from /home/pela/.gem/ruby/2.3.0/gems/asciidoctor-2.0.1/bin/asciidoctor:15:in `<top (required)>'
        from /home/pela/bin/asciidoctor:23:in `load'
        from /home/pela/bin/asciidoctor:23:in `<main>'

**Comment by mojavelinux** [comment]
find_by now includes table cells by default. Table::Cell uses the content_type `:simple`, but doesn't implement the lines method. However, we have enough information to implement it, so I'll go ahead and add it. That should allow the extension to work unmodified.
