### ISSUE TITLE
Warn on link to a local file that does not exist with -v

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3210]
`-v` already warns about missing `<<mylink>>` links and that is awesome.

I wish it would also warn when I link to an external file (usually in a Git repo):

    link:path/to/myfile.c[]

if the path does not exist in my local disk.

**Comment by mojavelinux** [comment]
That type of validation is really outside the scope of the core processor. It's something that could be implemented in a validation framework for AsciiDoc. But Asciidoctor itself does not go fishing around for files outside of the current document.

**Comment by cirosantilli** [comment]
OK, thanks.

**Comment by cirosantilli** [comment]
BTW, I hacked up a link extractor at: https://github.com/cirosantilli/linux-kernel-module-cheat/blob/00b1d431644f4cb330ae137a466097916faadb7b/asciidoctor-extract-linkswhich I then use to verify if the files exist :+1: :+1: :+1:
