### ISSUE TITLE
Mojibake unstead of cyrillic

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#3212]
Hello.

![image](https://user-images.githubusercontent.com/33900895/55052998-d95d3d80-506b-11e9-9cf8-b857358556fb.png)

This issue started [here](https://github.com/asciidoctor/asciidoctor-vscode/issues/175), but I found that this problem is in Ruby version of Asciidoctor 2.0.1.

When I use Asciidoctor 1.5.8, all works fine, but after upgrading to Asciidoctor version 2.0.1 I see these mojibake.

-- Andrey.

**Comment by mojavelinux** [comment]
You're going to need to provide me with the source file if you want me to test it. I can't do anything with a screenshot.

Chances are, the document is not probably encoded in UTF-8.

**Comment by mojavelinux** [comment]
And you can't just post the source in the comment, be that changes the encoding to UTF-8. You need to put the file somewhere it can be downloaded so that I can access the original version of it.

**Comment by mojavelinux** [comment]
Using the source you shared in the linked issue, here's the result I get when I convert the document.

![8b347caa-247c-4b3d-80ad-75d245acd601](https://user-images.githubusercontent.com/79351/55054843-bfe5d280-5026-11e9-8e65-41a78f593242.png)

This is not an issue with the processor but rather a misconfiguration of your system. It's either that the document is not encoded in UTF-8 or you version of Ruby is configured with the incorrect input/output encoding to use the String#encode function properly.

**Comment by mojavelinux** [comment]
Btw, it's true that the encoding logic changed between 1.5.8 to 2.0.0. What we're using in 2.0.0 is now more correct. The document is read as a UTF-8 file so that the read operation is not system dependent. But it does require that the file be encoded in UTF-8.

**Comment by mojavelinux** [comment]
If you'd like to add a print statement to tell us what encoding Ruby thinks the source is in, add the following line here https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L1300

```rb
puts source.encoding
```

You can also print the source to see what the variable holds.

**Comment by sindzicat** [comment]
> You're going to need to provide me with the source file

No problems :)

```
= Вывод уравнения упругой линии балки для шпиндельного узла
:nofooter:
:lq: pass:[&laquo;]
:rq: pass:[&raquo;]
:stem: latexmath


Hello
Привет
```

> The document is very likely not encoded in UTF-8.

VS Code shows `utf-8` to me...

![image](https://user-images.githubusercontent.com/33900895/55055542-5096cf80-5074-11e9-9e5b-d303318aec4f.png)

My document:

[test.zip](https://github.com/asciidoctor/asciidoctor/files/3011845/test.zip)

> `puts source.encoding`

Done. It's IBM866, not UTF-8.

![image](https://user-images.githubusercontent.com/33900895/55055788-2f82ae80-5075-11e9-81e1-f6b036b61c2c.png)

**Comment by mojavelinux** [comment]
> Done. It's IBM866, not UTF-8.

There's your issue. Asciidoctor 2.0.0 only accepts documents that are in UTF-8. (See #1131 for a discussion about making this configurable).

You'll need to figure out how to get VSCode to write the file as UTF-8. There must be a setting somewhere.

**Comment by mojavelinux** [comment]
(Oddly enough, when you zip a file, it converts it to UTF-8, so the document you gave me in the zip is UTF-8).

The reason we made this policy change in Asciidoctor is a) to align with modern Ruby practices and b) because not using UTF-8 encoding creates a precarious situation. Other than a BOM, there is no way for a document to declare what encoding it uses, so you have to tell the program what to use. But if we assume it's UTF-8, and we align on that, then we never have to be guessing.

I do think that making it configurable would be useful for cases when you know the encoding you are using an it's not UTF-8. But that should still be seen as a temporary measure until you switch to UTF-8, which, as it's name suggests, is universal.

**Comment by mojavelinux** [comment]
I also want to reiterate just how problematic it is that Windows does not use UTF-8 like every other operating system. Problems like these are manufactured by the insistence of the Windows platform to not standardize on UTF-8.

**Comment by mojavelinux** [comment]
> VS Code shows utf-8 to me...

But it's clearly not writing the file as UTF-8. Either that, or Ruby is ignoring the mode specified here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L211

Which version of Ruby are you using?

You could try to read the file using the following program. If this doesn't give you UTF-8, then Ruby is misbehaving.

```rb
string = File.open('test.adoc', 'rb:utf-8:utf-8') {|fd| fd.read }
puts string.encoding
```

**Comment by mojavelinux** [comment]
If you are getting IBM866 as the encoding, then the problem is very likely not the encoding of the file. The problem is more likely that Ruby is not respecting the mode argument. So the program I shared should produce the same result (IBM866) on your system.

**Comment by mojavelinux** [comment]
It would appear that this is actually a Ruby on Windows problem.

One way to fix this is to change how you invoke Asciidoctor to use this:

```
ruby -E UTF-8:UTF-8 /path/to/asciidoctor
```

That should reconfigure Ruby to use UTF-8 as the internal encoding.

**Comment by mojavelinux** [comment]
I think I can confirm Ruby on Windows doesn't respect the encoding settings in the file read mode. At least, that's my theory.

**Comment by sindzicat** [comment]
> `ruby -E UTF-8 /path/to/asciidoctor`

There was such system variable, but I removed it to fix smth.)))

I will reinstall Ruby for Windows now.

**Comment by mojavelinux** [comment]
Btw, I just tried on Windows (Ruby 2.5 x64-mingw32) and the output of the program I shared is UTF-8, even when I call it using `ruby -E IBM866:IBM866 test.rb`. So I don't understand how it is that you're getting different results on your system.

**Comment by sindzicat** [comment]
Hm... I've been reinstalled Ruby and Asciidoctor. When I run in console `asciidoctor test.adoc`, result (`.hmlt`) is fine. But there are mojibake in VS Code preview still.

Maybe there are some problems in VS Code extension for Asciidoctor?

**Comment by mojavelinux** [comment]
I'm happy to hear that you can run `asciidoctor` successfully. That's great news.

I don't know exactly how VSCode is invoking Asciidoctor, but it sounds like the problem has to do with that integration. It could be using a different version of Ruby. It could be passing different settings to Ruby. I'm not sure.

**Comment by elextr** [comment]
@sindzicat is the extension using asciidoctor.js or asciidoctor, according to [this](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode) you can switch which it uses

**Comment by mojavelinux** [comment]
I think I see what's going on. I've explained the problem in the linked issue. Let's continue the discussion there as this definitely has to do with how VSCode is calling Asciidoctor.

**Comment by sindzicat** [comment]
@elextr, I use [this](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode) extension. Originally this issue was posted [here](https://github.com/asciidoctor/asciidoctor-vscode/issues/175) exactly for this extension.

**Comment by mojavelinux** [comment]
To follow-up, the extension needs to pass `-E UTF-8` using the RUBYOPT environment variable. This is required when piping content to the `asciidoctor` command on a system that configures Ruby to use an IO encoding other than UTF-8.
