### ISSUE TITLE
Running last version of asciidoctor doesn't work, it crashes

### ISSUE THREAD

**Issue by SombreroJansu** [asciidoctor/asciidoctor#3218]
I installed couple of VMs, different platforms (RHEL, CentOS, Debian, SLES) and on all of them it crashes like below:

[jenkins@xyz ~]$ gem install asciidoctor
Fetching: asciidoctor-2.0.2.gem (100%)
Successfully installed asciidoctor-2.0.2
Parsing documentation for asciidoctor-2.0.2
Installing ri documentation for asciidoctor-2.0.2
1 gem installed
[jenkins@xyz ~]$ asciidoctor -h
/home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/lib/asciidoctor/core_ext/float/truncate.rb:3:in `<top (required)>': private method `prepend' called for Float:Class (NoMethodError)
        from /home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/lib/asciidoctor/core_ext.rb:2:in `require_relative'
        from /home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/lib/asciidoctor/core_ext.rb:2:in `<top (required)>'
        from /home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1552:in `require_relative'
        from /home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/lib/asciidoctor.rb:1552:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/jenkins/.gem/ruby/gems/asciidoctor-2.0.2/bin/asciidoctor:6:in `<top (required)>'
        from /home/jenkins/bin/asciidoctor:23:in `load'
        from /home/jenkins/bin/asciidoctor:23:in `<main>'
[jenkins@xyz ~]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
[jenkins@xyz ~]$

**Comment by mojavelinux** [comment]
Asciidoctor 2.0 requires Ruby 2.3 or better. It looks like you are using an older version of Ruby. Can you report the output of this command?

```
ruby -v
```

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
I decided to fix this so that distribution vendors can provide support for running Asciidoctor on older versions of Ruby 2. Keep in mind Asciidoctor is only officially supported and tested on Ruby >= 2.3. But distribution vendors can certify it on older versions of Ruby if they choose to.

**Comment by SombreroJansu** [comment]
Ok. In the meantime, I've already upgraded all the machines to the latest ruby so I don't need to limit the version of asciidoctor installed.

**Comment by mojavelinux** [comment]
:+1: That is certainly the path we still recommend. Although I permitted Asciidoctor to run on older versions of Ruby 2, doing so is not officially supported (or tested).
