### ISSUE TITLE
Text in table unexpectedly monospace

### ISSUE THREAD

**Issue by hkp-wcd** [asciidoctor/asciidoctor#3230]
Under certain conditions text is unexpectedly displayed in monospace.
The cell must be marked with `a`. Then text preceded by a newline and a space becomes monospace.

Reduced example:
```
|===
a|
 monospace text
|===
```
![image](https://user-images.githubusercontent.com/42992894/55333897-6fdc9500-5498-11e9-8891-db2d11946900.png)

Tested with asciidoctor.js 1.5.9 (atom-asciidoc-preview) and Asciidoctor 1.5.7.1 (cli)

**Comment by PauloFrancaLacerda** [comment]
I get the same results with Asciidoctor `1.5.8`, `2.0.0`-`2.0.4` (on Ruby 2.6.1 for Windows).

**Comment by rockyallen** [comment]
Try starting 'monospace' at the left margin-you seem to have a space before it.

**Comment by hkp-wcd** [comment]
Thank you!
The space before "monospace" is intentional, because I wanted to show a reduced to the point example.
Here's a more like the real world example:

```
|===
| api-field-name a| This is a field description text.

                    Possible field values
                    - ``01``
                    - ``02``
                    - ``03``
|===
```
![image](https://user-images.githubusercontent.com/42992894/55382776-d7d9bc80-5526-11e9-85d2-1ac38c54ec93.png)


Is there any way / best practice to achieve the intended indented list like this?

**Comment by Mogztter** [comment]
@hkp-wcd I guess you could add a new line before the `a|`:


```
|===
| api-field-name
a| This is a field description text.
Possible field values:

- ``01``
- ``02``
- ``03``
|===
```

**Comment by mojavelinux** [comment]
I was going to suggest exactly what @Mogztter explained. The AsciiDoc syntax is not designed to layout out table rows horizontally. AsciiDoc is a left-aligned language, which means you need to think about columns as list, and rows as blocks. Content in AsciiDoc cannot float away from the left margin (unless you intend to create a literal paragraph). That's how the language is designed.
