### ISSUE TITLE
how to passthrough <style> locally in the block instead of globally?

### ISSUE THREAD

**Issue by ctrngk** [asciidoctor/asciidoctor#3232]
This is oversimplified sample. I am actually write a code block in the table. This is only a simpler version.

```
++++
<style>
div { 
   color: red; 
}
</style>
<div> Red content</div>
++++

++++
<hr>
++++

++++
<style>
div {
    color: green;
}
</style>
<div> Green content </div>
++++
```

which renders like this:
![image](https://user-images.githubusercontent.com/16743578/55378375-4597df80-554b-11e9-94a3-698043133c5b.png)

This is not I want. I assume the first part is Red content, but it is now unexpectedly  overridden by the second <style>.  How to make each part of <style> rendering locally or independently?  I wonder any wrapper there to make the passthrough effect locally.

**Comment by elextr** [comment]
Note that this has nothing to do with Asciidoctor, you are writing HTML directly.  

This is the way CSS works, later CSS elements override earlier ones for the _whole document_.

To apply style to one element use an [internal CSS](https://www.w3schools.com/html/html_css.asp)

**Comment by mojavelinux** [comment]
I agree with @elextr, you're mostly dealing with a CSS issue here. If you want certain CSS to apply to certain blocks, you need to target those blocks using roles. When you add a role to a block, it becomes a CSS class in HTML. You can add any number of roles you want to a block. Then, you can reference the resulting class in your CSS selector so that the styles only apply to that one block. This is how you scope CSS.

Btw, if you are adding additional styles to the page, you should be using docinfo (either a docinfo file or docinfo extension, depending on your needs). docinfo allows you to add extra HTML at the top (two locations) and bottom of the document.

**Comment by ctrngk** [comment]
I am actually taking notes about css, and I do not want to edit the code of css/html itself. I just want to add a wrapper out of the code block, and the content should be rendered dynamically.  This is a complete doc I write

```
# Four type of combinnator

## read from right to left

1. 
Space only combinator -> Descendent

[cols="2"]
|===
a| css
a| html
a|
[source,html,subs="verbatim,quotes"]
----
<style>
.main div {
    color: magenta;
}
</style>
----
a|
[source,html,subs="quotes"]
++++
<style>
.main div {
    color: magenta;
}
</style>
<body>
    <div class="main">
        Main div
        <div> - Div child of main</div>
        <article>- Article child of main</article>
        <span> 
            - Span child of main
            <div>
               - Div descendant of main
            </div>
        </span>
    </div>
    <div>
        Footer div
        <div>
            - Div child of footer
        </div>
    </div>
</body>
++++
|===


2. 
combinator -> Direct child

[cols="2"]
|===
a| css
a| html
a|
[source,html,subs="verbatim, quotes"]
----
<style>
.main > div {
  color: blue;
}
</style>
----
a|
++++
<style>
.main > div {
  color: blue;
}
</style>
<body>
    <div class="main">
        Main div
        <div> - Div child of main</div>
        <article>- Article child of main</article>
        <span> 
            - Span child of main
            <div>
               - Div descendant of main
            </div>
        </span>
    </div>
    <div>
        Footer div
        <div>
            - Div child of footer
        </div>
    </div>
</body>
++++
|===
```

This is how it renders
![image](https://user-images.githubusercontent.com/16743578/55383523-fce82280-555a-11e9-86d5-79205935bd00.png)

I just want to take note, and the result of right column should be rendered **dynamically**. However, the right column is not rendering properly, result from conflicting <style>. I want a **smart** way to accomplish this, instead of hard-code the style.  Thank you.

**Comment by mojavelinux** [comment]
Unfortunately, that's just not how CSS works. CSS is global by default. You could perhaps use a treeprocessor extension to add the role (aka CSS class) in both locations during processing. Another idea would be to make the CSS a custom block and then in the custom block processor you could add an enclosing CSS class to the raw HTML. But I don't see anyway to do it without using extensions in some way.

**Comment by mojavelinux** [comment]
Maybe scoped CSS? https://davidwalsh.name/scoped-css

**Comment by mojavelinux** [comment]
Nope, scoped is gone. See https://stackoverflow.com/questions/28633038/what-is-the-current-state-of-the-scoped-attribute-for-the-style-element-in-htm.

**Comment by mojavelinux** [comment]
The most flexible route you can take here is to manipulate the document using one or more Asciidoctor extensions. Extensions allow you to type one thing, but get another thing.

**Comment by ctrngk** [comment]
Thank you for pointing out <style scoped> is not implemented in most browsers. 

Funny thing I try to trick the system by separating the <style> into two files and combine them in one doc 
```
include::combinators01.adoc[]
include::combinators02.adoc[]
```

which makes no difference.  The problem still there. Now I think in the html-level, how would I implement this feature in html instead of asciidoc? No, I cannot, easily.  Everything starts to make sense. 

Temporally I just separate the sections into different files. Each file, containing only one <style>, works flawlessly.  

Extensions method seems overwhelm to me. I know little about ruby, and AsciidocFX IDE does not preview third-party extensions as easy as expected.

Maybe I will consider using a picture in the future. Thank you.

**Comment by mojavelinux** [comment]
> I just separate the sections into different files. Each file, containing only one <style>, works flawlessly.

:+1:

**Comment by mojavelinux** [comment]
Feel free to close unless you have other questions. Thanks!
