### ISSUE TITLE
Create Table with Source Code

### ISSUE THREAD

**Issue by Niubi90hou** [asciidoctor/asciidoctor#3233]
Can not highlight Source code within Table Please help.

[xxxxx@xxxxxx ~]$ cat topics
{
  "topics": [
    {
      "topic": "xxxx"
    },
    {
      "topic": "xxxxxi"
    },
    {
      "topic": "xxxxx"
    },
    {
      "topic": "xxxxxxi"
    }
  ],
  "version": 888
}

**Comment by mojavelinux** [comment]
This is not a complete issue report. If you'd like help, please file a new report that explains the situation clearly. Thanks for understanding.
