### ISSUE TITLE
Paste code 'as is'

### ISSUE THREAD

**Issue by deftmaster** [asciidoctor/asciidoctor#3237]
Hello,

I have to generate documents with code in tables (|===) and in inner tables(!===). I expect the same formulas in body of the document (on the same level with tables). 

Problem:
I have such symbols (!, |, ==) and potentially others, which a programmer may use. If I escape the symbol for the inner table (\!) I get \! in body. 

Is there any universal solution for avoiding any formatting of the text?

P.S. I tried to find the solution myself, but failed.

Thank you in advance and have a nice day!

**Comment by deftmaster** [comment]
For example C++ and Java use there symbols and their combinations:

() [] -> . ! ~ ++ -- + - * & / % << >> < <= > >= == != ^ | && || ?: = += -= *= /= %= &= ^=

I want to be sure, that the table, or document will not be broken (as it happens with ! and |).

**Comment by Mogztter** [comment]
Hello @deftmaster could you please provide a short example ?

The code is inside a listing block (inside a table) ?

**Comment by deftmaster** [comment]
Hi!

.Title
[width='100%', options='header']
!===
!Formula !Table
a!
    
    Concat(IF((LEVEL = "INFO");"1";""))
    !
    @
    '
    "
    :
    ===
    ==
    =
    --
    ++
    +
    ;
    .
    `
    [
    [[
    ]    
    ]]
    \|

    () 
    [] 
    -> 
    . 
    ! 
    ~ 
    ++ 
    -- 
    + 
    - 
    * 
    & 
    / 
    % 
    <<
    _
    >>
    <
    <=
    >
    >=
    ==
    !=
    ^
    |
    &&
    ||
    ?:
    =
    +=
    -=
    *=
    /=
    %=
    &= 
    ^=
    
!log
!===

**Comment by deftmaster** [comment]
Symbols ! and | break tables.

**Comment by deftmaster** [comment]
Solution that works for inner tables:
\!
\|

doesn't break the table, renders as ! and |

but if I insert it into body, or table (|===) I get \I and |

**Comment by Mogztter** [comment]
Indeed, I can reproduce this issue with:

```
[cols="1,2a"]
|===
| Col 1 | Col 2
 
| Cell 1.1
| Cell 1.2
 
| Cell 2.1
| Cell 2.2
 
[cols="2,1"]
!===
! Col1 ! Col2
 
a!
[source,c++]
----
a
!
b
----

! C12
 
!===
 
|===
```

#### Actual result

![wrong](https://user-images.githubusercontent.com/333276/55485511-e1e4e380-562a-11e9-862a-420c6be82b0a.png)

#### Expected result

![good](https://user-images.githubusercontent.com/333276/55485531-ec9f7880-562a-11e9-953c-8c28dae30d58.png)

**Comment by Mogztter** [comment]
It's also true with tables:

```
[cols="1,2a"]
|===
| Col 1 | Col 2
 
| Cell 1.1
| Cell 1.2

a|
[source,c++]
----
a
|
b
----

| Cell 2.2

|===
```

#### Actual result

![bad](https://user-images.githubusercontent.com/333276/55485901-a860a800-562b-11e9-9472-930258da76b2.png)


#### Expected result

![good1](https://user-images.githubusercontent.com/333276/55485906-aac30200-562b-11e9-8aaa-4212f129ab25.png)

**Comment by Mogztter** [comment]
I'm not sure if it's a bug, a known limitation or if I'm missing something... 
In the User Manual, I found this example:

```
|===
|Source Code 1 |Source Code 2

a|
[source,python]
----
import os
print "%s" %(os.uname())
----

a|
[source,python]
----
import os
print ("%s" %(os.uname()))
----
|===
```

But If I replace the code with `print "|"` then the table is broken:

![broken](https://user-images.githubusercontent.com/333276/55486490-b105ae00-562c-11e9-8813-d5a5062e9aa1.png)

**Comment by elextr** [comment]
See https://asciidoctor.org/docs/user-manual/#escaping-the-cell-separator its a known limitation I think.

**Comment by Mogztter** [comment]
@elextr thanks for the pointer, and there's also a good workaround in the documentation:

> The cell separator is controlled using the separator attribute on the table block. You’ll want to select a character that will never be used for content. A good candidate is the broken bar, or ¦.

```
[cols=2*,separator=¦]
|====
¦The default separator in PSV tables is the | character.
¦The | character is often referred to as a "`pipe`".
|====
```

So I guess you could define a separator. You could also use `{vbar}` to use a pipe (`|`) within the content of a cell without creating a new cell.

If it's a limitation, I would argue that the documentation is a bit misleading because the AsciiDoc column style is described as:

> Supports block-level elements (paragraphs, delimited blocks, and block macros). This style effectively creates a nested, standalone AsciiDoc document. Implicit attributes such as doctitle from the parent document will be shadowed. Custom attributes are inherited.

But in a standalone AsciiDoc document I can use the symbol `|` in my listing blocks.

**Comment by elextr** [comment]
@Mogztter I guess (reading @mojavelinux mind) that the paragraph you quote above is the intended operation of Asciidoc, and the paragraph I posted is a current limitation of the _implementation_ for which the workaround you noted is provided.

**Comment by deftmaster** [comment]
Thanks guys for your time and help!
