### ISSUE TITLE
The comment sequence is wrong.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#3243]
I have a document as following:

```
[source,bash]
----
$ docker run busybox <3>
$ docker container prune <4>
----
<3> When you call run, the Docker client finds the image (busybox in this case), loads up the container and then runs a command in that container.
<4> delete container。
```

<img width="579" alt="Xnip2019-04-06_15-29-04" src="https://user-images.githubusercontent.com/2121467/55666382-c96e0680-5880-11e9-9922-f82a3439d310.png">

**The sequence in the source code starts from `3`, but the sequence in the comments starts from `1`.**

**Comment by mojavelinux** [comment]
Callout lists have to start with the number 1. That's always been a requirement of AsciiDoc.

**Comment by diguage** [comment]
I test it again:

```
$ asciidoctor --version
Asciidoctor 2.0.2 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

It's OK.

**I found the problem in Antora 2.0.0.**

**Comment by mojavelinux** [comment]
Can you clarify what you mean by "it's ok"? Does that mean you understand my recommendation, or that the behavior changed? I want to make sure you're on the right path.

**Comment by diguage** [comment]
> Can you clarify what you mean by "it's ok"? Does that mean you understand my recommendation, or that the behavior changed? I want to make sure you're on the right path.

"It's OK." means that the two sequences start from `1`.

**Comment by celtic-coder** [comment]
Hi @diguage, what you are calling "comments" are actually "callouts". See https://asciidoctor.org/docs/user-manual/#callouts

**Comment by mojavelinux** [comment]
@diguage Excellent. Thanks for clarifying.

**Comment by mojavelinux** [comment]
Do you have additional questions regarding $subject, or can we close this issue?

**Comment by diguage** [comment]
> Do you have additional questions regarding $subject, or can we close this issue?

Yes. You can do it. Maybe it is not a problem of AsciiDoctor.

**Comment by mojavelinux** [comment]
Callout lists have to start at number 1. Is there are reason you are not starting at 1? (I'm trying to understand your use case).

**Comment by diguage** [comment]
> Callout lists have to start at number 1. Is there are reason you are not starting at 1? (I'm trying to understand your use case).

I start the sequence from 1, but the first two commands were unnecessary and were deleted.

**Comment by mojavelinux** [comment]
The sequence has to start from 1 or else you will get a warning. That's just a rule.

Keep in mind, you can autonumber your callouts so you don't have to worry about the number using this syntax:

```
[source,bash]
----
$ docker run busybox <.>
$ docker container prune <.>
----
<.> When you call run, the Docker client finds the image (busybox in this case), loads up the container and then runs a command in that container.
<.> delete container。
```

That may suit your use case better.
