### ISSUE TITLE
Indent for code snippet missing a style.

### ISSUE THREAD

**Issue by russau** [asciidoctor/asciidoctor#3258]
I'm not sure if this is the intended behavior or not.  The first code block in the sample below is rendered in 2.0.7 which no background color.  I guess this is related to the default CSS used when generating HTML.

```
Here is some code:

 odds ==> Object[3] { 1, 3, 5 }

Here is the same code:

[source]
----
odds ==> Object[3] { 1, 3, 5 }
----
```

With 1.5.8

![image](https://user-images.githubusercontent.com/167762/56082638-0b8ecf00-5dd0-11e9-8a76-57dd86c6f7ba.png)

With 2.0.7

![image](https://user-images.githubusercontent.com/167762/56082646-12b5dd00-5dd0-11e9-881c-1df5f854affb.png)

I think it was introduced with this commit: https://github.com/asciidoctor/asciidoctor/commit/23ddbaed6818025cbe74365fec7e8101f34eadca#diff-61cdd94bfd166b7330da0521c81bdec2L206

**Comment by mojavelinux** [comment]
Oh, wow, you're absolutely right. I don't know how I missed that.

To be clear, we lost the background color on **literal** blocks, which is a verbatim block created either from an intended paragraph or a delimited block with 4 dots. This is a different block type than a listing or source block. The latter is the only true "code block". Nonetheless, the description of the regression is accurate.
