### ISSUE TITLE
Asciidoctor.js does not remove preamble from embedded SVG

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3261]
Due to the fact that the regular expression is not defined in a portable way, Asciidoctor.js does not remove the preamble from an embedded SVG.

Here's a test case:

```xml
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- An SVG of a black circle -->
<svg
viewBox="0 0 120 120" version="1.1"
xmlns="http://www.w3.org/2000/svg" style="width:500px;height:500px"
width="500px" height="500px">
  <circle cx="60" cy="60" r="50"/>
</svg>
```

When embedded into the output document using:

```adoc
image::black-circle.svg[]
```

The result is expected to match:

```xml
<div class="imageblock">
<div class="content">
<svg
viewBox="0 0 120 120" version="1.1"
xmlns="http://www.w3.org/2000/svg" style="width:500px;height:500px"
width="500px" height="500px">
  <circle cx="60" cy="60" r="50"/>
</svg>
</div>
</div>
```

Notice the missing xml declaration, doctype declaration, and comment. However, Asciidoctor.js is including all this markup.

**Comment by mojavelinux** [comment]
@Mogztter it would be great to add a test in Asciidoctor.js for this scenario. See https://github.com/asciidoctor/asciidoctor/blob/3190ab298ea751984d28ba9778418fadefa9deaf/test/converter_test.rb#L623-L628

**Comment by Mogztter** [comment]
> it would be great to add a test in Asciidoctor.js for this scenario

Definitely!
I've opened an issue in Asciidoctor.js to make sure I don't forget 😉
