### ISSUE TITLE
:toc: doesn't work when there are one or more empty lines between header and :toc:.

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#3266]
Hello!

When there are no any empty lines after document header, `:toc:` works fine:

```
= Header
:toc:

== subheader 1

== subheader 2

Asciidoctor version: {asciidoctor-version}
```
![image](https://user-images.githubusercontent.com/33900895/56199463-a217f600-6045-11e9-934d-3d29f6b37653.png)

When there are one or more empty lines between header and `:toc:`, TOC doesn't work:

```
= Header

:toc:

== subheader 1

== subheader 2

Asciidoctor version: {asciidoctor-version}
```
![image](https://user-images.githubusercontent.com/33900895/56199574-d4c1ee80-6045-11e9-9638-f3a997d1601b.png)

> **P.S.** I use Ruby version of Asciidoctor, but Javascirpt version has the same issue.

Best regards,
Andrey.

**Comment by mojavelinux** [comment]
This behavior is to spec. See https://asciidoctor.org/docs/user-manual/#doc-header

**Comment by elextr** [comment]
Also note that https://asciidoctor.org/docs/user-manual/#user-toc specifies that `:toc:` is to be set only in the command line or header.  That section also explains how to locate the TOC where you want it.

**Comment by sindzicat** [comment]
I understand now. But sorry, I still can't understand why it's by design. What is the thing preventing make `:toc:` as a usual variable?

**Comment by mojavelinux** [comment]
AsciiDoc has a clear idea of a header, like for instance in HTTP. The header sets document-wide settings. Below the header, it's just content. This is a very common pattern in tech, and hence why AsciiDoc adopted it. And the pattern predates me by many, many years.

**Comment by elextr** [comment]
Well for the original Asciidoc Python it had to be set early so the required javascript could be included in the HTML head that was emitted at the end of the Asciidoc header, before any document was processed.

**Comment by mojavelinux** [comment]
Indeed, there was also historically a technical limitation. But when I implemented Asciidoctor as a two-phase processor, I choose to honor the distinction between a header and body. (After all, it's why you set CSS in the `<head>` tag, and PDF info in the PDF preamble, and document settings in the LaTex header, etc).

**Comment by sindzicat** [comment]
OK.

Let me concretize my problem.

I have many `.adoc` files. I'd like my settings to be the same for all them. So I created `conf.adoc` in the root of my folder and use the following in each `.adoc` file.

```
= My header
:root: ../..
include::{root}/conf.adoc[]
```

I'd like all my `.adoc` files have a TOC. But I didn't know that blank lines are not allowed between `:toc:` and document header. I "fixed" this removed all blank lines from `conf.adoc`. But also I must remember that blank line isn't allowed before `include` in target file too. It's not difficult for me but confusing me a little.

-- Andrey.

**Comment by mojavelinux** [comment]
>  I "fixed" this by removing all blank lines from conf.adoc. But also I must remember that blank line isn't allowed before include in target file too.

Your understanding is exactly correct.

If you are interested in the discussion about making the header rules more lenient, please follow #3267.
