### ISSUE TITLE
Advice for building git documentation

### ISSUE THREAD

**Issue by bneumeier** [asciidoctor/asciidoctor#3268]
I have been using asciidoctor to build documentation for the git version control system for some time; the git build machinery supports both asciidoc and asciidoctor for this purpose. However, it requires a docbook 4.5 backend, and it appears that asciidoctor 2.0 has removed support for docbook 4.5.

I am looking for suggestions about the best way to build the git documentation now. The options I can think of are:
- add support for docbook 4.5 to asciidoctor 2, somehow; if this is possible, it's not clear to me how.
- use asciidoctor 1.5.8 rather than the latest stable asciidoctor
- use python asciidoc rather than asciidoctor
- migrate git documentation to docbook 5; I'm not sure how big this effort is but I suspect it is substantial

Is one of these recommended? Is there a better option that I have not thought of?

**Comment by Mogztter** [comment]
In my opinion, the two good options are:

1. migrate git documentation to docbook 5; I'm not sure how big this effort is but I suspect it is substantial
2. add support for docbook 4.5 to asciidoctor 2, somehow; if this is possible, it's not clear to me how.

Using a deprecated implementation (AsciiDoc Python) or a deprecated version (Asciidoctor 1.5.8) is not a good idea.

I can't tell if migrating the Git documentation to DocBook5 will require a big effort or not. The easiest way is probably to take the code from 1.5.8 and develop a custom converter (as mentioned in the release note):


> In Asciidoctor 2.0, we say goodbye to the DocBook 4.5 converter. DocBook 4.5 was superceded by DocBook 5 nearly a decade ago and there's no reason anyone should be using it anymore. But, if for some reason, you still rely on DocBook 4.5 output, it wouldn't be hard to take the code from 1.5.8 and develop a custom converter to produce it.

https://github.com/asciidoctor/asciidoctor/releases/tag/v2.0.0

The original code is here: https://github.com/asciidoctor/asciidoctor/blob/v1.5.8/lib/asciidoctor/converter/docbook45.rb

And if you don't want to rely on the docbook5 converter, you can extend `Converter::Base` and use `register_for 'docbook45'`.

You can also search in the Asciidoctor organization, there's a few converters written in Ruby:

- https://github.com/asciidoctor/asciidoctor-bespoke
- https://github.com/asciidoctor/asciidoctor-mallard

**Comment by danyill** [comment]
There is a stylesheet for conversion to docbook5 so I suspect it depends on
your tool chain complexity.

https://docbook.org/docs/howto/howto.html#convert4to5

**Comment by elextr** [comment]
@bneumeier you don't explain why you depend on Docbook 4.5?  

The Asciidoc Python 3 version is not deprecated, but its open source development and few people contribute to it so its likely few use it, so you would be essentially supporting it yourselves.  Or as @Mogztter says you can support your own Asciidoctor backend, but that then ties you into that implementation instead.

This is unfortunately the lock in that occurs when you use extensions or special processing (guessing the answer to the Docbook 4.5 question above).

Probably the best solution is to upgrade to Docbook 5 (like presume the code is periodically updated to newer versions of C) or plain Asciidoc and let @mojavelinux and @Mogztter take the support strain :)

**Comment by mojavelinux** [comment]
@bneumeier The right thing to do is to migrate to DocBook 5. If you're using the DocBook toolchain (which I assume you are if you're producing DocBook), then DocBook 5 is already supported. So it's likely you don't even have to change anything other than switching the backend from docbook45 to docbook (or docbook5).

All other options are only prolonging the use of legacy software, so it doesn't actually solve your problem. (DocBook 5 became a standard almost 10 years ago: http://docs.oasis-open.org/docbook/specs/docbook-5.0-spec-os.html).

To help smooth the transition in the interim, I'd be happy to push up the DocBook 4.5 converter code into a separate repository. I don't plan to release it, and it will be entirely community supported, but it should help give you a safety net if the upgrade to DocBook 5 takes longer than anticipated.

**Comment by mojavelinux** [comment]
> There is a stylesheet for conversion to docbook5 so I suspect it depends on your tool chain complexity.

@danyill If they were going to take that path, I think they would need it to be the other way around. But there's really no reason for downgrading to DocBook 4.5 since the DocBook toolchain can process both DocBook 4.5 and DocBook 5.x.

**Comment by mojavelinux** [comment]
@bneumeier Here's the DocBook 4.5 converter. https://github.com/asciidoctor/asciidoctor-docbook45

Feel free to submit PRs with tests if you find anything missing.

**Comment by danyill** [comment]
Oh quite right, silly me 🙄

**Comment by bneumeier** [comment]
Thank you all for your thoughtful responses!

@elextr re: "you don't explain why you depend on Docbook 4.5?" -- I don't work on the git project, I just build it and use it. Precisely why the Makefile specifies "ASCIIDOC_DOCBOOK = docbook45", I don't know. The documentation target for git uses asciidoc and xmlto; I suspect that xmlto will be the sticking point, since it's apparently orphaned with a most recent release in 2015.

I concur with the general consensus that trying to use docbook 5 is a good idea, but if xmlto chokes on docbook 5 input then I'd either need to try to fix _that_ or find some other way to produce man page output -- which appears to be what the docbook intermediate format is used for. The INSTALL file says that producing info files also requires docbook2X, which would be another point where docbook 5 might be an issue.

@mojavelinux I appreciate the pointer -- if docbook 5 is problematic, I'll try the docbook 4.5 converter and see if that works.

**Comment by elextr** [comment]
If it only needs docbook to make manpages then asciidoctor does them directly without any docbook.

**Comment by mojavelinux** [comment]
> If it only needs docbook to make manpages then asciidoctor does them directly without any docbook.

Great point. There may be a reason why the git project is still using the DocBook toolchain for this, but I certainly thing it's worth reevaluating that choice. Plus, we have plenty of room now to improve the manpage converter, so bring on the use cases!

**Comment by mojavelinux** [comment]
> I suspect that xmlto will be the sticking point, since it's apparently orphaned with a most recent release in 2015.

xmlto is just a light wrapper around the DocBook toolchain, so technical it isn't even needed. It's possible to invoke the DocBook toolchain directly. (All these wrappers like xmlto and a2x end up just creating a maintenance problem in the long run). Just something to think about.

**Comment by mojavelinux** [comment]
If the proposed solutions work for you, @bneumeier, feel free to either close or follow up with more questions.

**Comment by bneumeier** [comment]
If I were more familiar with the DocBook toolchain, I probably could have found a way to get DocBook 5 to work. As it is, simply using the deprecated extension gem works fine and is really easy! So that's what I did to get past my immediate issue.

I do think it's a good idea to simplify the whole documentation toolchain used by git -- since, as @elextr mentioned, Asciidoctor is able to produce man pages directly, there's not necessarily any need to involve the DocBook toolchain at all for that format. So maybe I'll look into doing that in my voluminous free time.

(The git documentation also uses DocBook as an intermediate format when producing an info file, although for that it looks like the toolchain uses docbook2X rather than xmlto. Docbook2X appears to be just as orphaned as xmlto (last release 2007 for docbook2X, 2015 for xmlto), so it seems worthwhile to remove them both from the git documentation build system.)

BTW, the Asciidoctor user manual still has lots of references to the docbook45 backend; it might make sense to at least add a note advising people that it is removed in 2.0?

Thanks again all!

**Comment by mojavelinux** [comment]
@bneumeier Thanks for updating the docs!
