### ISSUE TITLE
Unable to escape periods in IDs

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#3273]
First of all, I've already read other similar issues before creating this one, but none was specific enough.

For very particular (and peculiar) reasons, I really need to use periods in my section IDs. Other special characters such as "-" or "_" won't suit as replacement.

I've been trying to escape them, but all attempts fail miserably.
By the way, HTML5 allows periods in IDs.

If I use (unescaped):
`[#part1.part2]`
`part1` is taken as the ID, and...
`.part2` becomes the ID's role/class, which is not the expected result.

Resulting HTML:   `<body id="part1" class="article part2">`

If I use (escaped):
`[#+part1.part2+]`
`+part1` is taken as the ID (the `+` sign is taken literally), and...
`.part2+` is taken as the ID's role/class. Again, wrong result.

Resulting HTML:   `<body id="+part1" class="article part2+">`

The same above happens if I quote the ID.
So... is it possible to escape periods in IDs?

**Comment by Mogztter** [comment]
I think you should use the long format:

```
[id=part1.part2]
Hello world
```


```html
<div id="part1.part2" class="paragraph">
<p>Hello world</p>
</div>
```

**Comment by PauloFrancaLacerda** [comment]
> I think you should use the long format:
> ```
> [id=part1.part2]

Yup! That did it! Thank you!   :+1:

**Comment by mojavelinux** [comment]
This is indeed one of the limitations of the shorthand.

Keep in mind you can also use the older anchor syntax:

```
[[part1.part2]]
```

**Comment by PauloFrancaLacerda** [comment]
> Keep in mind you can also use the older anchor syntax:
> [[part1.part2]]

Yes, it works well for literal IDs but, when an attribute is used for the ID and preceding a section, it messes up the section id -- at least in my docs.

For instance, this...
```
:a: part1.part2
[[{a}]]
====== Section and more text here determined by attributes.
```
is creating a wrong ID for Section, containing something like:
`<h6 id="Section_and_more_text_here_determined_by_attributes">Section`

I'm trying to reproduce the error with a small code.
Didn't manage yet. I'll keep trying tomorrow.

**Comment by mojavelinux** [comment]
That's correct. The older anchor syntax does not support the use of attributes for the ID. This is for compatibility reasons. To use attributes in the ID, you need to either use the shorthand syntax (which in this case you cannot) or the explicit ID assignment (which is your best bet).

**Comment by PauloFrancaLacerda** [comment]
The `[id=part1.part2]` format (with attributes) is working very well for me.
I use it for compound IDs like:
`TSomeClass.SomeProperty`
`TSomeClass.SomeProperty.Examples`
`TSomeClass.SomeMethod`
`TSomeClass.SomeMethod.Parameters.ParamX`
`TSomeClass.SomeMethod.Parameters.ParamY`

I think all is clear now. I'm fully satisfied with the explanations and results. :+1:

**Comment by mojavelinux** [comment]
I'll add a note in the docs as well.
