### ISSUE TITLE
Alternate single-line comments token

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#3288]
Some days ago, I missed an alternate way of using the **single-line comments** feature and realized there's no option for this. Even though I'm not a Ruby programmer, I've decided to jump into this adventure and cook some dirty-and-ugly hack for that. Well, after a few and painful minutes, I got something that does the job (for my needs).

As a result, now I'm able to use a single-quote character (`'`) as the "token" for single-line comments, aside from the traditional double-slashes (`//`), which keeps working as usual. In order to make it configurable, I've added a constant to the code in `Asciidoctor.rb`, so the "token" can be easily changed as needed.

The downsize in my "code" is the fact there must be an alternate token defined, that is, I can't just leave the constant set to `nul` (or equivalent). I didn't add the code necessary to check for the undefined condition. Doing so in Ruby could be too much for a Delphi programmer's brain.   :)

So, I'd like to leave this **suggestion**: provide a new, official attribute which, once defined, will be used as an alternative for the double-slashes. This attribute could be called something like "**alt-comments**" or such.

In case someone would like to see my ugly hacks, just let me know. For now, I'm sparing you all.   :D

**Comment by mojavelinux** [comment]
Could you explain the justification for this setting? This is a very abnormal thing to want to do in a computer language. In every language I know about, the line comment character is fixed. That's because it should be (and really must be) context free. And most languages only support one prefix (in the case of AsciiDoc, it's the C-style '//'). I think this request would add unnecessary complexity to the language, hurt portability, and make it that much more difficult to develop tools for AsciiDoc (such as syntax highlighting the the IDE).

**Comment by PauloFrancaLacerda** [comment]
Well, I don't have an orthodox justification for it, just my personal taste as user.
Now, talking "abnormality"... isn't **flexibility** the reason of the user attributes? If to be "fixed" is the best approach, than why provide the user-attributes and make these attributes change the tool's behavior?

**Comment by mojavelinux** [comment]
User attributes are able changing output behavior and styling, not core parsing rules. That's the difference, IMO.

**Comment by elextr** [comment]
And changing a language randomly makes it hard for others to read.  The point of a language (human or computer) is that its _inflexibility_ is what ensures that everyone has the same understanding of its meaning.

**Comment by PauloFrancaLacerda** [comment]
> User attributes are able changing output behavior and styling, not core parsing rules. That's the difference, IMO.

Doesn't `relfileprefix` change the parsing rules?

**Comment by PauloFrancaLacerda** [comment]
I can't see why a reader/parser/highlighter couldn't just read the value of the new token's attribute -- eg: `{alt-comments}` -- then take it into account while parsing the rest of the code.

**Comment by elextr** [comment]
> Doesn't relfileprefix change the parsing rules?

`relfileprefix` changes a file search path, not the language.

> I can't see why a reader/parser/highlighter couldn't just read the value of the new token's attribute -- eg: :alt-comments: $$ -- then take it into account while parsing the rest of the code.

This is requiring tooling to understand the semantics of a language, but most tooling is only designed to handle a fixed syntax.

And I don't disagree that it can be done.  But I believe it should NOT be done.

**Comment by PauloFrancaLacerda** [comment]
Ok, guys, let's forget my suggestion. I just dreamed of this, and managed to make it come true for myself:

![sample](https://user-images.githubusercontent.com/17791112/57000099-8144ba00-6b88-11e9-87c8-0d91867b4e37.png)

**Comment by PauloFrancaLacerda** [comment]
> > Doesn't relfileprefix change the parsing rules?
> 
> `relfileprefix` changes a file search path, not the language.

In other words, "parsing rules".  :D

**Comment by mojavelinux** [comment]
I disagree that changes the parsing rules. relfileprefix is about output.

You're absolutely free to implement your own preprocessor to process the AsciiDoc in the way the best suits you (as you have). But this simply cannot be part of the standard language because it violates the very structure of what we call AsciiDoc.
