### ISSUE TITLE
Title on excerpt quote block renders on top of quote bar

### ISSUE THREAD

**Issue by jlmuir** [asciidoctor/asciidoctor#3289]
When I use a title on a quote block with an excerpt role

```
.Comments
[.excerpt]
____
This is a comment.
____
```

the title is rendered in HTML partially on top of the quote bar

<img width="200" alt="title-quote-excerpt" src="https://user-images.githubusercontent.com/959381/57041860-dc2dee00-6c28-11e9-84b8-675f2e16292c.png">

This is with Asciidoctor 2.0.9 and Google Chrome 73.0.3683.103.

The excerpt role was added in commit 0672524.

**Comment by jlmuir** [comment]
A horrible hack

```
.Comments
--
--
[.excerpt]
____
This is a comment.
____
```

produces something closer to what I was wishing for

<img width="194" alt="title-quote-excerpt-hack" src="https://user-images.githubusercontent.com/959381/57042552-9bcf6f80-6c2a-11e9-9cac-0cb78feb548b.png">

**Comment by Mogztter** [comment]
Are you using the browser extension or Asciidoctor Ruby (either the command line `asciidoctor` or the Gem) ?

**Comment by jlmuir** [comment]
The command line `asciidoctor` invoked as

```
$ asciidoctor my-doc.adoc
```

**Comment by mojavelinux** [comment]
You are correct that the block title is not being accounted for in the styles for an excerpt quoteblock.

A cleaner workaround is to apply the title to an enclosing open block:

```
.Comments
--
[.excerpt]
____
This is a comment.
____
--
```

It's also almost identical semantically speaking.

**Comment by jlmuir** [comment]
Thanks for the cleaner workaround!  It works!

**Comment by jlmuir** [comment]
I confirm that using the stylesheet from commit 4d1683e as a custom stylesheet fixes the problem!  Thank you!

**Comment by mojavelinux** [comment]
@jlmuir Thank you for taking the time to confirm the fix!
