### ISSUE TITLE
asciidoc plugin for IntelliJ IDEA 2019.1 has regressions

### ISSUE THREAD

**Issue by jmalin-signalfx** [asciidoctor/asciidoctor#3290]
I don't know who supports the Asciidoc plugin for IntelliJ IDEA 2019.1, but its blurb links to asciidoctor.org which links to this GitHub repo.

Today (May 1, 2019 PDT) I received notification that a new version of the Asciidoc plugin for IntelliJ IDEA was available. Since I use asciidoctor in IntelliJ, I installed the plugin. The listed version is v0.25.9.

This version breaks features that were previously working, specifically:

- The plugin now interprets single `_` as underlines and highlights them in the plain text with italics. Previously, it didn't change their highlighting.
- Editing in an adoc file eventually hangs IntelliJ. The only way to fix the problem is to force quit. I've had to uninstall the plugin.

**Comment by mojavelinux** [comment]
This repository is for the core processor. The repository for the plugin is here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/. Please refile this issue in that repository so it gets the attention of the right person. Thanks!

**Comment by mojavelinux** [comment]
Actually, I might be about to transfer it. I will try.
