### ISSUE TITLE
Anchors defined via [id=name] or [#name] won’t work for table cells.

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [asciidoctor/asciidoctor#3292]
I haven't found any example for anchors within table cells in the documentation, so I'm not sure if this is a bug or a feature.

**ADOC**:
```
[id=issue]
.Issue:
Anchors defined via `[id=name]` or `[#name]` won't work for table cells.

[id=table]
[cols=">,>,^,<", caption="", options="autowidth"]
.Table:
|===
^| Row         ^| Method   ^| Result  ^| Reason
 | [[row1]] #1 m| \[[name]] | works    | this is the expected behavior.
 |[id=row2] #2 m| [id=name] | *fails* >| `"[id=row2]"` is taken literally.
 |  [#row3] #3 m| [#name]   | *fails* >| `"[#row3]"`   is taken literally.
|===

Links: +
<<issue,issue>> <<table,table>> <<row1,row1>> <<row2,row2>> <<row3,row3>>
```
**HTML**:
![issue](https://user-images.githubusercontent.com/17791112/57069406-ef819d80-6caa-11e9-929a-b138eabfe24e.png)

Is this the expected behavior?

**Comment by mojavelinux** [comment]
You're correct that there's no ID shorthand for table cells. That's because table cells themselves do not support block attributes, which is being discussed here: #3293. Thus, it's necessary to use an inline anchor. An inline anchor does not have a shorthand variation. Though you can use the long form `anchor:name[]` to make it more clear.

**Comment by PauloFrancaLacerda** [comment]
The reason why I'd like to use the `[id=name]` form within a cell is because it accepts attributes, whereas the other forms don't, so I'd be able to prefix the cells' IDs, like this:
```
:a: v213
[id={a}]
[cols="<,<", caption="", options="autowidth"]
.Product Version 2.1.3:
|===
^| Changelog ^| Description
 | [id={a}-add-1] addition 1 | the following symbols have been added....
 | [id={a}-fix-1] bugfix 1 | the bug X has been fixed.
 | [id={a}-fix-2] bugfix 2 | the bug Y has been fixed as well.
|===
```

**Comment by mojavelinux** [comment]
The formal anchor macro allows you to use attributes in the ID.

```
anchor:{a}-add-1[]
```

**Comment by PauloFrancaLacerda** [comment]
> The formal anchor macro allows you to use attributes in the ID.
> 
> ```
> anchor:{a}-add-1[]
> ```

Thank you for the tip.
Actually, I deleted my last post because I did a test and found out I can use the `[[{a}-add-1]]` form, and it works with the embedded attribute.  :)

**Comment by mojavelinux** [comment]
Super! Options abound!

**Comment by mshaposhnik** [comment]
Similar question. I have an csv table:
```
 +CHE_WORKSPACE_PROBE__POOL__SIZE,"10","This property specifies how much threads to use for workspaces servers liveness probes".
 +CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS+,"NULL","Http proxy setting for workspace JVM"
```

I want property names to be addressable, i.e., anchors. So if i try:
```
[[CHE_WORKSPACE_PROBE__POOL__SIZE]] +CHE_WORKSPACE_PROBE__POOL__SIZE+,"10","This property specifies how much threads to use for workspaces servers liveness probes".
 +CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS+,"NULL","Http proxy setting for workspace JVM"
```
doctor applies formatting inside anchor (due to `__` symbols) and they became unusuble and resulting in 
`[CHE_WORKSPACE_PROBEPOOLSIZE]] +CHE_WORKSPACE_PROBEPOOLSIZE` as a result. Any hints? Thanks.

**Comment by mojavelinux** [comment]
> doctor applies formatting inside anchor (due to __ symbols) and they became unusable:

The unconstrained formatting in the anchor must be escaped using a backslash in this case:

```
[[CHE_WORKSPACE_PROBE\__POOL__SIZE]]+CHE_WORKSPACE_PROBE__POOL__SIZE+
```
