### ISSUE TITLE
AsciiDoctor based documentation generator

### ISSUE THREAD

**Issue by pzdcdoc** [asciidoctor/asciidoctor#3295]
Hi all,

first of all thanks a lot for doing of this great product.
AsciiDoctor gave us so needed standardizing and flexibility and I found it the best currently existing solution for making software documentation.
However there were some missing things from my perspective:
- orientation on large *.adoc files;
- no recommended structure for storing resources;
- references checking;
- search in created documentation using JS.
I know, that partially it might be solved using converting to DocBook format first.
But we went our way, and short time ago our solution was published here: https://github.com/pzdcdoc/pzdcdoc 
So it has to be some restricted and maximally simplified way of building documentation.
I kindly ask everybody here about feedback:
- is such thing needed for somebody else;
- does it make sense to keep it separately or better try to integrate in one of existing projects.

**Comment by mojavelinux** [comment]
I'm excited to see a growing interest in building tools on top of AsciiDoc and Asciidoctor. I support it. We certainly need more options for users to be comfortable their decision with choosing AsciiDoc over other writing formats. That's one of the key motivators for us developing Antora (which will power the documentation site for Asciidoctor itself). And I hope we can align on a common cross-page referencing system.

Having said that, the issue tracker is not the appropriate place to make announcements and gather feedback. Please use either the mailinglist at http://discuss.asciidoctor.org or the gitter channel at https://gitter.im/asciidoctor/asciidoctor. Thanks!
