### ISSUE TITLE
Hide source block `tag`/`end` entries from HTML output

### ISSUE THREAD

**Issue by tomassedovic** [asciidoctor/asciidoctor#3298]
I'm writing a tutorial and trying to generate the final source code file out of an Asciidoctor text so the two are always in sync. This works great using `tag` and `include`

`tutorial.adoc`:

```adoc
= A Hello World Program

Let's create a `main` function calling `message`:

[source,rust]
----
// tag::main[]
fn main() {
    println!(message());
}
// end::main[]
----

And this is what the function will look like:

[source,rust]
----
// tag::message[]
fn message() -> &'static str {
   "Hello, world!"
}
// end::message[]
----
```

`program.adoc`:

```adoc
:doctype: inline
:outfilesuffix: .rs

++++
include::tutorial.adoc[tag=message]

include::tutorial.adoc[tag=main]
++++
```

Running `asciidoctor *.adoc` produces the `tutorial.html` as well as `program.rs` files, the latter looking like this:

```rust
fn message() -> &'static str {
   "Hello, world!"
}

fn main() {
    println!(message());
}
```

This is exactly what I was going for.

However, the source code blocks in the HTML file still contain the `//tag::name[]` and `// end::name[]` sections. Is there a way to exclude them from the generated HTML? They're instructions for Asciidoctor, not intended for the reader. They take up space, complicate copy-pasting and will likely confuse the target audience.

I've got this workaround: hide the authoritative source block and add another (visible) one right after it with a single `include::` line bringing the text in. Something like this:

```adoc
[role=hide]
----
// tag::main[]
fn main() {
    println!(message());
}
// end::main[]
----

[source,rust]
----
include::tutorial.adoc[tag=main]
----
```

This works, but it feels like unnecessary boilerplate. Plus I worry it would confuse the drive-by contributors as it's not obvious what this indirection is for.

Would it be possible to add something that would hide the tags on a source block / entire document basis? Something like `[source, rust, tag(hidden)]`. Or just remove them by default, though I can see that causing false positives.

Is this something that you think would be worth adding? I'd be happy to give it a go, though I'd appreciate any pointers in that case -- I've never hacked on the asciidoc codebase.

**Comment by Mogztter** [comment]
May I ask why you are not writing `program.rs` in Rust directly ?

```rs
// tag::main[]
fn main() {
    println!(message());
}
// end::main[]

// tag::message[]
fn message() -> &'static str {
   "Hello, world!"
}
// end::message[]
```

And then use the include directive with tags in the `tutorial.adoc` ?

**Comment by tomassedovic** [comment]
I forgot to mention that, thanks! Reading the writer's guide this seems like the normal way of doing things. But, it's kind of backwards for what my use case.

All this is in a tutorial/book context where the document builds the program up over time. And it is much easier to write and maintain when the relevant source snippets are right there in the text.

Having the source for the code block in a different file would break the flow and it's probably not worth it for me. Right now, I actually maintain both the text and source separately and taking the duplication hit.

I guess what I'd like to achieve is akin to literate programming -- everything in a single place and being able to generate the final document and sources with `asciidoctor` as the tool.

**Comment by tomassedovic** [comment]
Oh and I forgot to add -- this runs into a similar issue with the leftover tag/end comments -- they're just on the Rust file's side. Ultimately, both outputs (the doc and source code) should be for the end-reader's consumption and anything that's not directly relevant shouldn't be there.

**Comment by Mogztter** [comment]
> I guess what I'd like to achieve is akin to literate programming -- everything in a single place and being able to generate the final document and sources with asciidoctor as the tool.

Then I would recommend to use an extension to generate the `program.rs`.
You could define a `TreeProcessor` to get all the source blocks defined in the `tutorial.adoc` file.

If you do that then you don't even need to add tags comments in the source blocks. I think it's the best approach here because it doesn't add any cognitive load on the writer's side.

Does it make sense ?

**Comment by tomassedovic** [comment]
Yeah, that's another possibility. There will still have to be something akin to tags, though. It is the writer who defines the final shape of the program. So they need the option to choose which pieces (or their subsets) are included and how they're combined.

In reality (my case) there's `part-1.adoc` through to `part-13.adoc` with 18 Rust files sharing maybe 30% of the code (each chapter has a "here's the complete code so far section or two"). So it's not as simple as just gluing all the source blocks together. The writers need to be able to fully control both the text and the output.

The reason I opened this issue is that it feels Asciidoctor is 98% there all by itself and I wondered if it's possible to close that final 2 percent. It's not a huge deal if something like this is not in fact desirable in core -- there are several ways to get around this with or without external tools.

**Comment by Mogztter** [comment]
You can define custom attributes on the source block, so you could define an "order" attribute to define the order in the program.rs file (and if the attribute is absent the block should not be appended to the program.rs file).

I don't see a good way to include the feature you've described in core... Maybe Dan will come up with a good idea but in this case I think you should use an extension (it's really straightforward).

**Comment by tomassedovic** [comment]
Ah, I didn't know about custom block-level attributes. Yeah, that might get me far enough. I do actually also just use parts of the code block (as opposed to wrapping the whole thing in a tag):

```adoc
[source]
// tag::foo_begin[]
fn foo() -> Bar {
    let a = example();
// end::foo_begin[]
    // NOTE: we will fill this middle section later
// tag::foo_end[]
   Bar::new(a)
}
// end::foo_end[]
```

And then pull `foo_begin`, `foo_middle` (defined in a different source block) and `foo_end` into the final source. But that's something I could work around in the doc text without too much trouble.

Paging @mojavelinux just in case he's got other ideas (and I'll close this if the consensus here is the custom extension).

**Comment by mojavelinux** [comment]
The scenario you described in the original post is already supported.

> the source code blocks in the HTML file still contain the //tag::name[] and // end::name[] sections.

To include a file in such a way that all lines with tag directives removed, you need to set the `tags` attribute on the include directive to `**`. This activates tag filtering, but includes all lines except for lines that contain tag directives.

```
[source,rust]
----
include::tutorial.adoc[tag=**]
----
```

If you only want to include lines that are inside (any) tags, then you can use a single `*`.

```
[source,rust]
----
include::tutorial.adoc[tag=*]
----
```

For more details, please see https://asciidoctor.org/docs/user-manual/#tag-filtering.

**Comment by tomassedovic** [comment]
Oh this is fantastic, thanks!

I have read that section, but I didn't find it relevant because I was looking for a way to remove the tags from the source document (and/or outputs thereof). That I could create a new file with just an `include::doc.adoc[tag=**]` that would add everything *except for the tags* (and use that to produce the final output) did not occur to me.

I've moved my tutorial/code to this and I am quite happy with it. Thank you!

**Comment by mojavelinux** [comment]
Thanks for sharing that perspective @tomassedovic. I'll try to incorporate that point into the section to shed light on that feature.

**Comment by mojavelinux** [comment]
I've updated the documentation.

**Comment by tomassedovic** [comment]
[That's much clearer](https://github.com/asciidoctor/asciidoctor.org/commit/0cd157ce45ad8406607dfa0d9e5937b2e12fd33a), thanks!
