### ISSUE TITLE
Is signature of SyntaxHighlighter::docinfo correct?

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#3300]
I started work on support for SyntaxHighlighters in Java.
When I implemented the first stub for a SyntaxHighlighter I implemented the method `docinfo location` as defined here: 
https://github.com/asciidoctor/asciidoctor/blob/7503c74302d37217890392d60a5595d6867fc5ad/lib/asciidoctor/syntax_highlighter.rb#L30-L37

However, it seems like the html5 backend passes 3 parameters to this method:
https://github.com/asciidoctor/asciidoctor/blob/7503c74302d37217890392d60a5595d6867fc5ad/lib/asciidoctor/converter/html5.rb#L156

And the rouge syntax highlighter also defines a method with 3 parameters:
https://github.com/asciidoctor/asciidoctor/blob/7503c74302d37217890392d60a5595d6867fc5ad/lib/asciidoctor/syntax_highlighter/rouge.rb#L52

Therefore JRuby rejects calling my implementation of `docinfo` with 1 parameter and I also have to implement it with 3.

Wouldn't it make more sense to also define the method in the module SyntaxHighlighter with 3 parameters?

**Comment by mojavelinux** [comment]
You're absolutely correct. The signature of this method didn't get updated. I'll do that for 2.0.10.
