### ISSUE TITLE
ifdef and ifndef treated differently in code blocks

### ISSUE THREAD

**Issue by NormanDunbar** [asciidoctor/asciidoctor#3304]
Good Afternoon All,

When I have a conditional statement (`ifdef`, `ifndef`, `endif`) in a source code block, it gets evaluated unless I prefix it with a backslash, as per the manual. (https://asciidoctor.org/docs/user-manual/#processing.)

I have a source file that has the following snippet of code in it, to explain the use of `ifdef` and `ifndef`:

````
[source]
----
\ifdef::backend-pdf[]
[width=50%, cols="20%, 80%", align = "center"]  <1>
\endif::[]

\ifdef::backend-html5[]
[width=50%, cols="20%, 80%", float = "center"]  <2>
\endif::[]

\ifndef::backend-pdf+backend-html5[]            <3>
[width=100%, cols="80%, 20%"] 
\endif::[]
----
<1> Using `align` for PDF output.
<2> Using `float` for HTML output.
<3> Multiple conditions being tested here.
````
When rendered into pdf, with `asciidoctor-pdf` or html with `asciidoctor`, the backslash in front of `ifndef` is present in the output while the one in front of `ifdef` and `endif` is not rendered. If I remove the backslash, the conditional is evaluated, as per another quick test that I did, not shown here and as explained in the manual.

In addition, the manual is incorrect at https://asciidoctor.org/docs/user-manual/#summary-tables where it mentions that `align` is "Not yet implemented in Asciidoctor. Applies to HTML output only. The align and float attributes are mutually exclusive."  `Align` actually works fine in `asciidoctor-pdf` for pdf outut, and `float` works in `asciidoctor` for html. :)

Cheers,
Norm.

**Comment by mojavelinux** [comment]
A preprocessor directive with a trailing callout number is not a valid preprocessor directive, so there's no reason to escape it.

```
ifndef::backend-pdf+backend-html5[]            <3>
[width=100%, cols="80%, 20%"] 
\endif::[]
```

I know this looks a bit weird, but it's a situation created by the presence of the callout number.

**Comment by NormanDunbar** [comment]
Ok, thanks very much @mojavelinux. I'll make a note for myself to remember this.

Thanks again for all you do for us users.


Cheers,
Norm.
