### ISSUE TITLE
`image: image` does not set png as default extension since 2.0.0.rc.1

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor#3308]
As mentioned here: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/406

Using `icons: image` sets `image` as the icons extension.
Not this is an issue or expected behavior, but to me is at least odd and I'd dare say an unnecessary compatibility break.

**Comment by abelsromero** [comment]
If this is a expected behavior I think the documentation is not 100% clear. 

As @rquinio points out in the issue, documentation says the icons documentation https://asciidoctor.org/docs/user-manual/#icons states: `If you want icons to display using images, set the icons attribute to an empty value in the document header`, which is consistent with the current behavior.
However in the [attributes tables](https://asciidoctor.org/docs/user-manual/#builtin-attributes) below, the columns `Default value` and  `Allowed values` for `icons` say respectively `not set (image)` and `font or image`. And below for `iconstype` it is stated that `Only used when icons attribute is set to image.`.

So, reading that I would expect that if `icons: image` is set, asciidoctor would check "icontype" and, if it is not set, then apply the default for icontype, which is "png", not add the "image" extension.

**Comment by mojavelinux** [comment]
Yes, this is a regression that needs to be corrected.
