### ISSUE TITLE
Inline attributes not passed to 'a' formatted table cells

### ISSUE THREAD

**Issue by GauntletPL** [asciidoctor/asciidoctor#3310]
The issue is best described by the simple snippet below. If I set an attribute inline (which is the only possible way if I want to set it within the table block) then this attribute is not visible inside the table cell formatted with an 'a' style. Another issue I noticed (also presented below) is that you can't reset the attribute to the new value using inline syntax.

    = Attributes test
    
    :attr1: One
    {set:attr2:Two}
    
    |===
    |Cell 1 |Cell 2
    
    |{attr1} |{attr2}   // this properly renders One and Two
    
    a|{attr1} a|{attr2}   // this renders One and {attr2}
    
    {set:attr2:Three}
    |{attr1} |{attr2}     //this renders One and Two, although attr2 should be Three now
    
    |===

**Comment by mojavelinux** [comment]
This comes down to a timing issue. Setting an attribute inline is evaluated during the conversion phase, which is after the table has been parsed. The attributes that an AsciiDoc table cell inherits are those that are defined at parse time. Thus, it won't see attributes set using the inline assignment.

It's also not possible to set an attribute inside of an AsciiDoc table cell and have it impact the parent document.

In both cases, these are just limitations in how the language is defined. You'll need to use the attribute entry syntax to define attributes you want the AsciiDoc table cell to see. If you can't do that directly in the document, you could use a custom block macro to do it.
