### ISSUE TITLE
cross references inside codeblocks?

### ISSUE THREAD

**Issue by jmarcop** [asciidoctor/asciidoctor#3318]
Is this possible?

I've tried e.g. this without success:

```
[source,json, subs="+macros"]
----
{
"result": String
"rejectReason": RejectReason
"productList":  <<dto_SignonDTO>> 
}
----
```

**Comment by mojavelinux** [comment]
The syntax you're using is correct. Can you describe more about your environment (how you are calling Asciidoctor) so we can understand why it doesn't work for you?

**Comment by jmarcop** [comment]
I'm running Asccidoctor in Windows 10 like:

asciidoctor-pdf  	 -a pagenums ^
				 -a pdf-style=themes/my-theme.yml ^
				 ^-a icons=font@ ^
				 index.adoc -o document.pdf

```
[source,json, subs="+macros"]
----
{
"result": String
"rejectReason": RejectReason
"productList":  <<dto_ProductDTO,ProductDTO>> 
}
----
```

And in the section dto_ProductDTO:

```
[[dto_ProductDTO]]
=== ProductDTO
```

This is the output in the PDF, as you can see the cross reference is not displayed correctly inside the code block. If I put the same cross reference outside, then is rendered correctly.

![Capture2](https://user-images.githubusercontent.com/7803838/58691088-56b66e80-838b-11e9-8331-77f125dae926.PNG)






The section dto

**Comment by mojavelinux** [comment]
Ah, so we are talking about Asciidoctor PDF. In that case, it's true, you cannot use both syntax highlighting and custom substitutions. This is a limitation with how syntax highlighting is handled in PDF (since it's not HTML-based). If you disable the syntax highlighting by making it a listing block, then it will work.

**Comment by jmarcop** [comment]
Ok, now it works. Thanks a lot! 

Is possible to disable/enable the syntax highlighting for few sections in the document? Or is enable/disable for all the document?

This is what I had in the beginning of my index.adoc (now I removed the line):
:source-highlighter: coderay

**Comment by mojavelinux** [comment]
Currently, the syntax highlighter is a global switch only.

**Comment by jmarcop** [comment]
Wow! I tested and it works :P 

This is what I did:

`
<<<

**:source-highlighter: coderay**

include::productDTO.adoc[]

<<<
**:source-highlighter:** 

include::signonDTO.adoc[]

<<<
`
The syntax in productDTO.adoc is enabled, and the syntax in signonDTO.adoc is disabled again.

**Comment by mojavelinux** [comment]
Oh, yes, that will work for PDF. It won't work for HTML, however, since Asciidoctor 2.

**Comment by jmarcop** [comment]
Great! Thanks for your time and help!
