### ISSUE TITLE
XML comment-style callout not guarded by comment in output

### ISSUE THREAD

**Issue by tjquinno** [asciidoctor/asciidoctor#3319]
An `.adoc` file contains
```
[source,xml,subs="attributes+"]
----
<dependency> <!--1-->
...
----
```

This is rendered on GitHub as this:
```
<dependency> (1)
...
```
Because the rendered callout is no longer commented, it is not correct XML and a reader cannot copy and paste the rendered output into a `pom.xml` without cleaning it up.

In contrast, callouts in a Java example are rendered behind the Java `//` so such examples can be copied and pasted directly.

**Comment by tjquinno** [comment]
And, as Dan commented when I originally posted this as https://github.com/github/markup/issues/1276

>Asciidoctor operates exactly the same on GitHub and when running locally. The difference is whether you're using font-based icons or not. When not using font-based icons (as is the case on GitHub), the comment guard needs to be preserved. That guard is not being preserved when the syntax  is used. That's the issue and it needs to be handled in Asciidoctor.

**Comment by mojavelinux** [comment]
That's for raising this issue. You are correct that the XML comment-style callout should be preserved when font-based icons are not enabled just like the line comment-style callouts.

**Comment by mojavelinux** [comment]
I implemented a solution in #3343.

However, I'm uncertain whether it should be displayed as:

```
<!-- (1) -->
```

or

```
<!--1-->
```

The first would be more consistent with how non-XML callouts are emitted (e.g., `// (1)`), though it is rather verbose. We could drop the space, though I'm still concerned about consistency.

**Comment by tjquinno** [comment]
Good question. Personally, I guess I prefer the first option for the consistency reasons you pointed out. Yes, it is longer but at the moment I feel as if I can live with that.

I might have preferred option 2 if the Java-style callouts similarly preserved the original comment in the rendered output, as in `// <n>`. But given the `(n)` convention it seems worthwhile to do the same in XML.

I'm also seeing if our team has different thoughts.

**Comment by mojavelinux** [comment]
> I guess I prefer the first option for the consistency reasons you pointed out. Yes, it is longer but at the moment I feel as if I can live with that.

:+1:

**Comment by mojavelinux** [comment]
Any more feedback before we proceed?
