### ISSUE TITLE
Add a hover on link to the table of content (TOC) entry of a header from each header

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3322]
Currently, when I click on header, I get a link to the header.

What I would like, would be when I hover over the header, for it to also show a second link that I can click on (e.g. an Unicode upwards arrow ↑) that will take me to the table of content entry for that header.

I often want this because I'm reading a header, and I want to get a quick overview of which headers are nearby to it.

**Comment by mojavelinux** [comment]
This is something that would most likely need to be done in a custom converter. I could see the possibility of adding a "back to top" link on the heading in the default HTML output. However, you'd need to provide some examples we could evaluate to help determine where this would fit in the design.

**Comment by cirosantilli** [comment]
Hi Dan,

Yes, this is something I felt while developing my humoungous README.adoc + code tutorials: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/77ef0dadf1ddd8e5cb0a359543ab4db9d01450b7#linux-kernel-module-cheat

In this particular case, GitHub's features are enough for me, so it would only considerably benefit me if GitHub would also possibly use it (users can also build the README locally, but this would be a minority).

However, I plan on writing some maths / physics stuff at some point, and those will need to go on GH Pages for maths, so those would also benefit even if GH does not support.

This is especially useful when you give a link to someone to one of the sections and the reader lands in the middle of the thing.

Direct link to parent section is another good link to have.

**Comment by hanckmann** [comment]
I would also be interested in a function to automatically add a link to the TOC near every header.

Did you manage to get this working in your setup?

**Comment by mojavelinux** [comment]
We are going to consider #4220, but we are not going to link every heading back to the TOC.

If you need to add this functionality, you can extend the converter to customize the HTML to your liking. See https://docs.asciidoctor.org/asciidoctor/latest/convert/custom/#extend-and-replace-a-registered-converter and related pages in that section of the docs.
