### ISSUE TITLE
Callout numbering for multiple sections of source from one file

### ISSUE THREAD

**Issue by bwittman** [asciidoctor/asciidoctor#3323]
Callouts are not numbered correctly when more than one separate section of source code is included from the same file.

Consider a toy Java file `Things.java`:
```java
public class Things {
	public static void main(String[] args) { //<1>	
		for( int i = 0; i < 100; i++ ) //<2>
			System.out.println(i);
	}
}
```

Consider Asciidoctor source that quotes two parts of it:
```
[source, java]
----
include::Things.java[lines=1..2]
----
<1> `main()` method

Now, I discuss some other things.

[source, java]
----
include::Things.java[lines=3..6]
----
<2> Loop
```

The output from the HTML backend is:
![image](https://user-images.githubusercontent.com/7459448/59046764-8f08f180-8850-11e9-9f67-9ac03f8abf9a.png)

Numbering callout 2 as 1 is confusing to the reader.

Also, a warning message is given:
```
asciidoctor: WARNING: test.adoc: line 28: callout list item index: expected 1, got 2
asciidoctor: WARNING: test.adoc: line 28: no callout found for <1>
```

This particular example looks absurd, but a program of dozens or hundreds of lines is much more readable broken into chunks. This issue may focus on a narrow use case, but a fix would be useful to me for the Java textbook that I'm writing in Asciidoctor.  Since explaining code is something Asciidoctor's frequently used for, others might benefit from such a feature.

**Comment by mojavelinux** [comment]
This is where you'd want to take advantage of the autonumbered callouts.

```java
public class Things {
	public static void main(String[] args) { //<.>	
		for( int i = 0; i < 100; i++ ) //<.>
			System.out.println(i);
	}
}
```

Then the numbers will just go in order starting from 1.

**Comment by bwittman** [comment]
You're right: autonumbered callouts are helpful in this case.  I was not aware that they were available and, indeed, see that they're a relatively new feature.

I'd still prefer to be able to refer to explicit callouts by number in my example.  In other words, it would be nice to refer to <2> and have the circled 2 graphic appear in both cases.  My use case is intended to show a progression through details in a single large source, even though it's broken into parts.

To me, it feels parallel to the desire to have `[start=2]` (for example) in numbered lists.

**Comment by mojavelinux** [comment]
I could definitely see where having `start` support on the callout list would be useful. Please file a separate issue that states that request specifically. We'll then take it from there.
