### ISSUE TITLE
How to use the default HTML CSS style as the CLI tool when using convert_file from the Ruby API?

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3324]
When I do

```
asciidoctor -o README.html README.adoc
```

it produces a nice default CSS to the HTML.

Now I started playing around with extensions to modify the output, but I would like to keep thta nice style.

However, if I do something like:

```
require 'asciidoctor'
require 'asciidoctor/extensions'

class Main < Asciidoctor::Extensions::InlineMacroProcessor
  use_dsl
  named :link
  def process parent, target, attrs
    %(#{(create_anchor parent, target, type: :link, target: '../' + target).convert})
  end
end

Asciidoctor::Extensions.register do
  inline_macro Main
end

(Asciidoctor.convert_file(ARGV[0]))
```

then the generated output does not have the nice CSS.

How to use the nice default CSS in that case as well?

This can be minimized to:

```
#!/usr/bin/env ruby

require 'asciidoctor'

Asciidoctor.convert_file(ARGV[0])
```

Tested in asciidoctor Asciidoctor 2.0.10.

**Comment by mojavelinux** [comment]
When using the API, you must set the safe mode to enable all the features (including the embedded stylesheet).

```
Asciidoctor.convert_file ARGV[0], safe: :safe
```

Keep in mind, you can still use the CLI if you are using an extension. Just require the extension using `-r`.

```
asciidoctor -r ./my-extension.rb README.adoc
```

**Comment by cirosantilli** [comment]
Thanks Dan! I didn't know about those two points, problem solved beautifully, my links to local files now work! https://github.com/cirosantilli/linux-kernel-module-cheat/blob/77ef0dadf1ddd8e5cb0a359543ab4db9d01450b7/asciidoctor/link-target-up.rb

**Comment by mojavelinux** [comment]
\o/
