### ISSUE TITLE
Consider making it possible to set `allow-uri-read` via document header

### ISSUE THREAD

**Issue by p-himik** [asciidoctor/asciidoctor#3327]
[This page](http://discuss.asciidoctor.org/Content-not-included-allow-uri-read-amp-unsafe-td1602.html) says: "The only way to enable uri reads is via the document options, and its disabled by default regardless of safe mode. We can revisit this level of paranoia after 1.5.0."

Has this ever been revisited? I couldn't find anything.

**Comment by mojavelinux** [comment]
No. It's a very important security restriction that the author cannot control this behavior. Otherwise, there would be really no point in having the restriction. I'm even skeptical allowing it in unsafe mode is a good idea. But feel free to make the case for why this would not be an attack vector.

**Comment by p-himik** [comment]
Oh, I'd be glad to, but I have no idea what to talk about since I'm just starting with asciidoctor.
I'll close the issue for now. Thanks for the explanation.
