### ISSUE TITLE
`[[80-character-limits]]` is not accepted as secondary section id

### ISSUE THREAD

**Issue by pirj** [asciidoctor/asciidoctor#3328]
```
=== 80 character limits [[80-character-limits]]
```

renders
![image](https://user-images.githubusercontent.com/6916/59135872-5456a480-8989-11e9-82cf-65d104622ac2.png)

And the anchor is set to `#80-character-limits-80-character-limits`.

```
[#80-character-limits]
=== 80 character limits
```

renders properly, and the anchor is properly set. Also, an arbitrary id can be used (i.e. tried `#8000-character-limits`).
![image](https://user-images.githubusercontent.com/6916/59135991-cb8c3880-8989-11e9-8aa7-7e27b445d34d.png)

Checked on [GitHub document](https://github.com/rubocop-hq/ruby-style-guide/#80-character-limits) and locally with Asciidoctor 2.0.9.

[Related fix in the doc](https://github.com/rubocop-hq/ruby-style-guide/commit/181d81c96c7abbb0635a35914fa3dafa4999afce).

**Comment by mojavelinux** [comment]
This is one of those weird legacy things in AsciiDoc that's shining through. The old syntax for defining an anchor (i.e., ID) (`[[80-character-limit]]`) does not allow the value to start with numbers. The newer syntax (`[#80-character-limit]`, defined above the block) doesn't have this restriction.

We had a choice to make: either update the old syntax or encourage users to migrate. We've choosen to encourage users to migrate.

**Comment by mojavelinux** [comment]
See #2117 for more details. I've also added this information to the documentation.

**Comment by pirj** [comment]
Thanks for the detailed explanation.

Would you recommend to exclusively use a newer `[#id]` syntax in the new documents?
My intention is in case of section title changes keep both the older one (that was generated for the changed title), and the new one. The plan was to stack up the historical ids, e.g.:

```diff
- === Old title [[old-title]]
+ === New title [[new-title]] [[old-title]]
```

```diff
- === New title [[new-title]] [[old-title]]
+ === Newer title [[newer-title]] [[new-title]] [[old-title]]
```

**Comment by mojavelinux** [comment]
> Would you recommend to exclusively use a newer [#id] syntax in the new documents?

Yes, I would.

> The plan was to stack up the historical ids

While the inline anchors enable this capability today, we'll likely want to consider a clear way of doing this, such as introducing a supplemental anchors attribute. I hadn't given this much thought before, but it's a real world use case to consider supporting (in a cleaner way). I really don't like the inline anchors on the section title.

**Comment by pirj** [comment]
Thank you, it's clear and makes total sense.
