### ISSUE TITLE
Pass specified basebackend when initializing backend traits of a converter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3341]
The order of initialization for backend traits for a converter can lead to the specified basebackend from seemingly being ignored. For example, consider the following declaration:

```rb
register_for 'bespoke'

def initialize backend, opts = {}
  ...
  basebackend 'html'
  htmlsyntax 'html'
end
```

In this case, the outfilesuffix ends up as `.bespoke` and the filetype as `bespoke`. However, we expect these values to be `.html` and `html`, respectively.

This happens because while setting the basebackend, the traits are initialized from the backend value. However, this mostlly defeats the purpose of the basebackend setting, which is intended to control the outfilesuffix and filetype (among other purposes). Aside from the behavior being nonintuitive, this breaks compatibility with 1.5.x.

This situation could be resolved by passing the basebackend to the method that initializes the backend traits so it gets used instead of deriving the value from the backend.

We will still recommend that the basebackend always be set first. But at least in the case that it is, the result will be as expected.

To guarantee the most dependable outcome, you should explicitly set the basebackend, filetype, outfilesuffix, and (if applicable) htmlsyntax.

**Comment by Mogztter** [comment]
It might be related to https://github.com/asciidoctor/asciidoctor-reveal.js/issues/257 no ?

**Comment by mojavelinux** [comment]
Exactly the same. This was a use case I somehow managed to overlook. Though, it is a bit of a chicken-egg as I mentioned, so easy to miss.
