### ISSUE TITLE
red box in syntax highlighted code block (w/ pygments)

### ISSUE THREAD

**Issue by heckj** [asciidoctor/asciidoctor#3347]
I'm not entirely sure if this is a question or if I'm reporting a bug.

I'm using Asciidoctor in my repo (version 2.0.10), rendering adoc to a variety of formats. When rendering to HTML or ePub3, but not PDF, some symbols in my code blocks are getting highlighted with "red blocks" around them.

The code sample is swift, and the highlighter I'm using is pygments, defined with
`:source-highlighter: pygments` in https://raw.githubusercontent.com/heckj/swiftui-notes/master/docs/using-combine-book.adoc

The example:

<img width="544" alt="Screen Shot 2019-06-24 at 4 04 39 PM" src="https://user-images.githubusercontent.com/43388/60057779-a3dfe480-969a-11e9-9f8e-b52cb2a71708.png">

is from https://heckj.github.io/swiftui-notes/#patterns-update-interface-network-request, and the source for this section is in https://github.com/heckj/swiftui-notes/blob/master/docs/patterns.adoc (~ line 400)

Interestingly, when rendered at github, the syntax highlighter isn't showing the red box.

Is this an issue with asciidoctor, with pygments, or something I'm simply doing incorrectly in my setup of the highlighter?

**Comment by mojavelinux** [comment]
This is an issue with Pygments. It's not recognizing the syntax.

**Comment by mojavelinux** [comment]
Use rouge instead. It's more current.

**Comment by heckj** [comment]
@mojavelinux thank you, I'll give that a shot!

**Comment by mojavelinux** [comment]
Note that this is still an issue with Pygments at the time this issue was closed. It's simply not recognizing the syntax. There's nothing we can do about that in Asciidoctor. As I stated in an earlier comment, Rouge gets this right.

**Comment by heckj** [comment]
Right - didn't think carrying the bug here was helpful - more an issue with Pygments, so closed it - I moved over to Rogue myself.
