### ISSUE TITLE
Special sections are not handled if they are the heading section

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor#3356]
For example, the following file will not create a bibliography section:
```
[bibliography]
= Test

- [[[item]]] an item.
```

There is code in [parser.rb](https://github.com/asciidoctor/asciidoctor/blob/v2.0.10/lib/asciidoctor/parser.rb#L303) for detecting the first section in a document. This path does *not* call `initialize_section`, so does not set `sectname`, so the section will not be detected as a bibliography later in parsing.

Why would anyone do this? This is the structure that's typical for books. But won't the bibliography be included into the spine, so it won't be the first section after all? Yes - but the `asciidoctor-epub3` gem has a special include processor that loads all the chapters as separate files, so in this case the bibliography *is* the first section in a standalone document.

You could argue that this is a bug in `asciidoctor-epub3`, but I think it's a bug in core. The example I gave is weird, but sensical, and if we support it then `asciidoctor-epub3` can continue to work as it currently does.

**Comment by michaelpj** [comment]
*Possibly* the right fix is just calling `initialize_section` on the other path, but it's very unclear to me what the consequences of this would be.

**Comment by mojavelinux** [comment]
Technically this would not be valid. I think the better approach is that the Asciidoctor EPUB3 converter strips (or overrides) this line, since it's the one with the special (non-standard) need.

Another approach is to make the style conditional, as in:

```
ifndef::backend-epub3[]
[bibliography]
endif::[]
```

**Comment by michaelpj** [comment]
> Another approach is to make the style conditional

But then the bibliography anchors in the body of the bibliography won't work properly in the epub version. Which isn't any better than the current situation!

If it's not valid, then it's an issue with the epub3 converter. Not sure what the fix is. Shall I close this an open one against that repo?

**Comment by mojavelinux** [comment]
> But then the bibliography anchors in the body of the bibliography won't work properly in the epub version. Which isn't any better than the current situation!

Then add the bibliography style on the list itself. Only putting it on the section title is a shorthand anyway intended for single source documents.

**Comment by mojavelinux** [comment]
> If it's not valid, then it's an issue with the epub3 converter. Not sure what the fix is. Shall I close this an open one against that repo?

Yes, this needs to be dealt with in the EPUB3 converter. It's just not a core issue.

**Comment by michaelpj** [comment]
> Then add the bibliography style on the list itself.

I had no idea you can do this! However, the manual says:

> You promote a normal unordered list to a bibliography list by adding the bibliography style. However, to be conforming, bibliography lists must be contained inside a bibliography section. A bibliography section is a section with the special bibliography style.

So it suggests that it needs to be in a `bibliography`-styled section. Is that not the case?

**Comment by michaelpj** [comment]
It would also be nice to know if glossaries need a `glossary`-styled header, which also isn't clear from the manual.

**Comment by mojavelinux** [comment]
It's conforming when it's creating a conforming document (which is really referring to DocBook). In EPUB3, the semantics of the section are meaningless, so it's perfectly safe.

It's important to understand the EPUB3 converter was largely an experiment to see how we could go straight from AsciiDoc to a multi-file output format. It does weird things in some cases because it was so experimental. It doesn't mean it's the best way. We learned stuff. Some of it is very strange. It's very likely Antora will eventually replace the EPUB3 converter because it's expressely designed for multi-file output. I'm not convinced the EPUB3 converter is really doing the job all that well. But we didn't know what we would get at the time.

**Comment by mojavelinux** [comment]
> It would also be nice to know if glossaries need a glossary-styled header, which also isn't clear from the manual.

If you are creating DocBook, yes. If you aren't, it really doesn't matter because it's really only used for DocBook output.

**Comment by michaelpj** [comment]
> It's important to understand the EPUB3 converter was largely an experiment to see how we could go straight from AsciiDoc to a multi-file output format. It does weird things in some cases because it was so experimental. It doesn't mean it's the best way.

Do you recommend people use it today? Sadly today is when I need to make my ebook ;)

I'll close this and open an issue on the other repo anyway just so it's written down.

**Comment by mojavelinux** [comment]
> Do you recommend people use it today? Sadly today is when I need to make my ebook ;)

If it works for you use it. If it doesn't, don't use it. It is what it is. But I can tell you it's not our main focus right now. There simply isn't enough time. So it ends up being largely community driven. My goal is to make sure updates move through it in a timely manner.

You always have the option of converting to DocBook and making an EPUB3 using the DocBook toolchain. While it's harder to customize, it's the most mature path to EPUB3. The beauty of AsciiDoc is that you have options.
