### ISSUE TITLE
asciidoctor-diagram leads to undefined method `cursor_at_mark'

### ISSUE THREAD

**Issue by lalebarde** [asciidoctor/asciidoctor#3360]
I have installed `asciidoctor-diagram` with `gem`, but when I compile my _asciidoc_, here is what happens:

```
$ asciidoctor -r asciidoctor-diagram my.adoc --trace
/var/lib/gems/2.3.0/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/extensions.rb:104:in `process': asciidoctor: FAILED: /home/lalebarde/Documents/my.adoc: Failed to load AsciiDoc document - undefined method `cursor_at_mark' for #<Asciidoctor::PreprocessorReader:0x0055ce87ecf940> (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:1088:in `[]'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:1088:in `build_block'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:883:in `next_block'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:315:in `next_section'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:303:in `next_section'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:67:in `parse'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:475:in `parse'
        from /usr/lib/ruby/vendor_ruby/asciidoctor.rb:1348:in `load'
        from /usr/lib/ruby/vendor_ruby/asciidoctor.rb:1466:in `convert'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:86:in `each'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from /usr/bin/asciidoctor:14:in `<main>'
```

Here is my.adoc:

```
Test
====

== blabla
ere etrezt eztz tyuuiyujhfdzd tyuuityur t(y(-u- t'(yè-iè_iyerfdf gbh jtygqrgfs jyuj rshjturty
hey trhy etyurty trhy
tyertyut rthyeyyry yrytry rrg:w

[plantuml, diagram-classes, png]    
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....
```

I am under Debian Stretch

**Comment by mojavelinux** [comment]
It looks like you are using an old version of Asciidoctor core (one that did not have this method). Can you report the output of `asciidoctor -v`?

**Comment by lalebarde** [comment]
Sure:
```
asciidoctor -v
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

```

**Comment by mojavelinux** [comment]
Asciidoctor Diagram does not support that version of Asciidoctor core (although it doesn't make this clear).

It seems to me that the asciidoctor-diagram package for Debian is not running the test suite against the version of asciidoctor provided with Debian. That's a packaging issue. I recommend reporting that to Debian.

In the meantime, I recommend either installing Asciidoctor via RVM or using the Docker image. The version bundled with the Debian distro you are using is just too far out of date (and clearly untested). Or try to install from stretch-updates (though that only gets you to 1.5.6). https://packages.debian.org/stretch-backports/ruby-asciidoctor

**Comment by mojavelinux** [comment]
@pepijnve I recommend adding a note to the README that states the oldest acceptable version of Asciidoctor core that Asciidoctor Diagram supports.

**Comment by lalebarde** [comment]
Tanks Dan, RVM looks complex to me. Can I use `gem install` instead ?

**Comment by pepijnve** [comment]
@mojavelinux TBH I don't really know which version that is. I'll try to figure out bisect-wise and update the gemspec accordingly.

**Comment by lalebarde** [comment]
I have uninstalled the debian asciidoctor package and re-installed it with gem. I have now version 2.0.10 and the problem is solved. Many thanks for your kind help.
