### ISSUE TITLE
Abbreviated quote syntax and quote paragraph syntax should wrap the content in a paragraph

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor#3361]
A quote can be define using the following syntax:

**1. Abbreviated quote syntax**
```adoc
"I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical."
-- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
```

**2. Quote paragraph syntax**
```
[quote,Thomas Jefferson, Papers of Thomas Jefferson: Volume 11]
I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.
```

**3. Markdown-style quote syntax**
```
> I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.
-- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
```

**4. Quote block syntax**
```adoc
[,Thomas Jefferson, Papers of Thomas Jefferson: Volume 11]
____
I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.
____
```

The abbreviated quote syntax (1) and the quote paragraph syntax (2) will produce the following HTML:

```html
<div class="quoteblock">
<blockquote>
I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.
</blockquote>
<div class="attribution">
— Thomas Jefferson<br>
<cite>Papers of Thomas Jefferson: Volume 11</cite>
</div>
</div>
```

As you can see the content is directly inside the `<blockquote>` element.

On the other hand, the Markdown-style quote syntax (3) and the block quote syntax (4) will produce the following HTML:

```html
<div class="quoteblock">
<blockquote>
<div class="paragraph">
<p>I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.</p>
</div>
</blockquote>
<div class="attribution">
— Thomas Jefferson<br>
<cite>Papers of Thomas Jefferson: Volume 11</cite>
</div>
</div>
```

Here the content is wrapped inside a `<div class="paragraph">` and a `<p>` element.

I think we should either produce the same HTML or specify in which case the content will be wrapped in a "paragraph".

The HTML5 specification does not require to use a `<p>` element inside a blockquote element:

> This example shows the use of a blockquote for short snippets, demonstrating that one does not have to use p elements inside blockquote elements

https://www.w3.org/TR/html50/grouping-content.html#the-blockquote-element

But arguably it's easier to apply a style when the content is wrapped in an element (especially if the attribution is inside the `<blockquote>` element):

> Attribution for the quotation, may be be placed inside the blockquote element, but must be within a cite element for in-text attributions or within a footer element.

```html
<blockquote>
<p>I hold it that a little rebellion now and then is a good thing,
and as necessary in the political world as storms in the physical.</p>
<footer>— Thomas Jefferson <cite>Papers of Thomas Jefferson: Volume 11</cite></footer>
</blockquote>
```

**Comment by Mogztter** [comment]
I did some experiments in https://github.com/asciidoctor/asciidoctor/commit/8d7acaa0e407de60158890181b3a67cec7932545 but I think the question we need to answer is should the above syntax produce the same AST (ie. a compound block with a child paragraph node) ?

So far I can produce the same AST for the abbreviated quote syntax (1), the markdown-style quote syntax (3) and the quote block syntax (4).
The quote paragraph syntax (2) uses a special condition in the `build_block` method:

https://github.com/asciidoctor/asciidoctor/blob/8d7acaa0e407de60158890181b3a67cec7932545/lib/asciidoctor/parser.rb#L1006-L1009

So it will require a few changes to produce the expected AST.

**Comment by mojavelinux** [comment]
> I think we should either produce the same HTML or specify in which case the content will be wrapped in a "paragraph".

This is something that should be specified in the language specification. I agree that we should get rid of the paragraph forms of blocks. All blocks should behave the same, regardless of whether they are defined as a styled paragraph or a delimited block. We can implement this in the new HTML converter. At this point, I don't want to change the existing HTML converter in an incompatible way.
