### ISSUE TITLE
Writing BLOG in Asciidoctor

### ISSUE THREAD

**Issue by blueray453** [asciidoctor/asciidoctor#3365]
I am planning to start a blog. Most of my contents are in adoc format. I am planning a solution which support adoc format.

I  searched the net. It talks about Hugo. Is it something the community recommends or is there a better solution?

Should I use asciidoctor stylesheet factory to render the articles according to my theme? 

I need a custom header, footer and sidebar. Can I render the Asciidoctor file inside a div? What is the way to go here?

**Comment by mojavelinux** [comment]
Please ask this type of question in the [gitter channel](http://gitter.im/asciidoctor/asciidoctor) or on the [discussion list](http://discuss.asciidoctor.org/). This issue tracker is for tracking code changes. Thanks!

**Comment by blueray453** [comment]
@mojavelinux I asked the question in both the places, but not getting any response. Can you please help me out in http://discuss.asciidoctor.org/Writing-BLOG-in-Asciidoctor-td7015.html

**Comment by mojavelinux** [comment]
I'll try to follow up when I get a chance. Sometimes it takes a few days to
get any feedback. Remember, this is volunteer work (and mid summer in the
northern hemisphere, so not everyone is around).
