### ISSUE TITLE
When building documents with markdown lists numbers are not handled correctly

### ISSUE THREAD

**Issue by leleabhinav** [asciidoctor/asciidoctor#3366]
When including a markdown document in a asciidoc the list numbering is not handled correctly in the below scenario -
Example markdown 
1. Some Text1
2. Some Text2

````ruby
class Something
end
````

3. Some Text3

The actual render by asciidoc make the item numbered 3. to be 1.

The error in logs is - 

list item index: expected 1, got 3

**Comment by mojavelinux** [comment]
You are missing a list continuation. Here's how the source should look:

```
. Some Text1
. Some Text2
+
````ruby
class Something
end
````

. Some Text3
```

(Note that the list numbers are not required in the source, though you are free to include them).

For more information, see https://asciidoctor.org/docs/user-manual/#list-continuation

**Comment by leleabhinav** [comment]
Thanks!
