### ISSUE TITLE
Warning tags not found in included file - linux

### ISSUE THREAD

**Issue by KyleAure** [asciidoctor/asciidoctor#3373]
When trying to use nested tags with asciidoctor like in the following scenerio

```python
from datetime import datetime

#tag::outer[]
now = datetime.now()
mm = str(now.month)

#tag::inner1[]
dd = str(now.day)
#end::inner1

yyyy = str(now.year)

#tag::inner2[]
hour = str(now.hour)
#end::inner2[]

mi = str(now.minute)
ss = str(now.second)
#end::outer[]
print mm + "/" + dd + "/" + yyyy + " " + hour + ":" + mi + ":" + ss
```
I am unable to choose the outer tag, while excluding the inner tags using the following syntax

```adoc
= Title

== Test

[source, python, numbered]
----
include::test.py[tags=outer;!inner1;!inner2]
----
``` 

Instead the following error is thrown:

```bash
kaure  $  asciidoctor test.adoc
asciidoctor: WARNING: test.adoc: line 7: tags '!inner1,!inner2' not found in include file: /home/kaure/Desktop/testAscii/test.py
```
This only happens when running on my Linux operating system.
Running the same test on MacOS works.   

```
OS: 
  Distributor ID:	Ubuntu
  Description:	Ubuntu 18.04.2 LTS
  Release:	18.04
  Codename:	bionic
ASCIIDOC:
  Asciidoctor 1.5.5 [http://asciidoctor.org]
  Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by Mogztter** [comment]
Hello @KyleAure, could you try with the latest version of Asciidoctor (currently 2.0.10).
The version you are currently using is quite outdated.
I think this feature was introduced in Asciidoctor 1.5.6.

**Comment by Mogztter** [comment]
There's a small typo in your Python file:

```py
#tag::inner1[]
dd = str(now.day)
#end::inner1
```

It should be:
```py
#tag::inner1[]
dd = str(now.day)
#end::inner1[]
```

I can confirm that this is working fine with Asciidoctor 2.0.10:

```console
$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

```console
$ asciidoctor test.adoc -s -o -
```
```html
<div class="sect1">
<h2 id="_test">Test</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-python" data-lang="python">now = datetime.now()
mm = str(now.month)


yyyy = str(now.year)


mi = str(now.minute)
ss = str(now.second)</code></pre>
</div>
</div>
</div>
</div>
```

**Comment by mojavelinux** [comment]
As @Mogztter points out, this feature was implemented in a newer version than you are using (specifically in 1.5.6). See https://github.com/asciidoctor/asciidoctor/blob/master/CHANGELOG.adoc#156-2017-07-12---mojavelinux

**Comment by KyleAure** [comment]
@mojavelinux and @Mogztter Thanks for the help.
Updating version worked.  I thought I had the latest version as `apt-get update asciidoctor ` did not pull anything.  Instead I had to use `gem install asciidoctor` to get the latest version.  
Closing this issue, but hopefully my woes will help someone else :+1:
