### ISSUE TITLE
Feature Request : .adoc as an output type

### ISSUE THREAD

**Issue by olib963** [asciidoctor/asciidoctor#3374]
I was hoping to use asciidoctor to create some of my github documentation, but as has been reported multiple time you cannot use the `include` macro or any diagram generation on github. I was wondering if it would be possible to add another output type that just merges all input `.adoc` files into one output `.adoc` file? If possible generating diagrams as something like `svg` and linking them in the `.adoc` file so that they would show up on github.

I think it would be a good feature since we wouldn't have to wait for github to allow such functionality out of the box. Please let me know if this is already possible and I just haven't found the right documentation :D

Thanks for all your great work :D

**Comment by mojavelinux** [comment]
There's already a script available in the extensions lab that does this. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb

**Comment by olib963** [comment]
I ah see. Nice :D is this just not available to the CLI?

**Comment by mojavelinux** [comment]
It's not built into the Asciidoctor processor. It's a separate script (as it requires multiple invocations of the Asciidoctor API).

**Comment by olib963** [comment]
awesome. Thank you :D

**Comment by mojavelinux** [comment]
Thinking about it a bit more, it could be repurposed as an extension or converter so it integrates directly with the CLI. I recommend opening an issue in the extensions-lab with that idea and perhaps someone can make it happen.
