### ISSUE TITLE
Is it possible to create numbered blocks with working xref caption like tables or images in an extension?

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3378]
I'm basically looking for an extension solution for https://github.com/asciidoctor/asciidoctor/issues/3354 in particular now that I've made progress on KaTeX sever rendering! https://github.com/cirosantilli/cirosantilli.github.io/blob/d1c519ecb1e13de62627b24ad65393b56b6795af/katex.rb | https://github.com/asciidoctor/asciidoctor/pull/3338

Do you think that is possible, and if so is there an example somewhere?

I want something like:

Block multi-liner: xref:math-test-math[]

```
Block multi-liner: xref:math-test-math[]

[katex,id=math-test-math]
.A test block equation
[katex]
....
\sqrt{1+1} \\
\sqrt{1+1}
....
```

to render in HTML as:

```
Block multi-liner: Equation 1, "A test block equation"

Equation 1. A test block equation

<katex markup>
```

just like images and tables currently do.

I could hack up the label above the equation myself easily I guess, but I don't see an easy way to make the `xref` also show it.

**Comment by mojavelinux** [comment]
Please direct questions about writing extensions to the project chat at https://chat.asciidoctor.org. Thanks!
