### ISSUE TITLE
Custom style on body level

### ISSUE THREAD

**Issue by andraz-kozelj** [asciidoctor/asciidoctor#3379]
Is there a way to insert custom role on the `<body style="book toc2 toc-left">` level?
I would like to add custom styling rules depending on this, document wide.

**Comment by mojavelinux** [comment]
Yes. See https://github.com/asciidoctor/asciidoctor/issues/2387.

This is not yet documented in the user manual (though could be implied based on the pattern it follows).

**Comment by andraz-kozelj** [comment]
Thanks, stands to reason. :)
