### ISSUE TITLE
Some observations about default CSS and related things

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3380]
1. Quotes

```
[quote, Monty Python and the Holy Grail]
____
Dennis: Come and see the violence inherent in the system. Help! Help! I’m being repressed!

King Arthur: Bloody peasant!

Dennis: Oh, what a _giveaway_! Did you hear that? Did you hear that, eh? That’s what I’m on about! Did you see him repressing me? You saw him. Didn’t you?
____
```

* `text-align: justify` looks a bit unexpectedly. Typically, we expect `text-align: justify` in books and newspapers and `text-align: left` in websites. I never saw these typographic styles to be mixed.

* It could be a good idea to add something like

```
.quoteblock blockquote em, .quoteblock p em {
    font-style: normal;
}
```

Note, that the word "giveaway" cannot be distinguished from the others otherwise.

2. The excessive period

```
.{blank}
|===
| Column 1 | Column 2
|          |
|          |
|===
```

Sometimes we need the tables to be numbered and have "Table" captions, but these tables have no names. In such a case we could use `.{blank}`. The full caption will look as "Table 1." - with period.

Essentially, the captions are just titles. We don't use end periods in titles:

* Correct: Monty Python and the Holy Grail
* Incorrect: Monty Python and the Holy Grail.

and therefore the period after "Table 1" is excessive.

* Correct: Table 1. Variables and values
* Correct: Table 1

The same goes for "View footnote." tooltip when you hover the footnote mark.

3. `code` in tables.

Everything is consistent here:

```
[%header]
|===
| Variables | Values
| `a`       | `x`
| `b`       | `y`
|===
```

However, sometimes it will not be so good:

```
[%header]
|===
| Variables | Values
| `a`      a| `x`

Sometimes the value could be `z`.

| `b`       | `y`
|===
```

`x` and `z` have background, but `a`, `b`, and `y` haven't.

4. Automatic lead paragraph

```
= Title

Automatic lead paragraph.

Normal paragraph.

== Heading
```

It is very opinionated, but I found that quite often I need to disable it. Automatic lead paragraph works well for well-written books and articles, but when you write some ad-hoc quick and dirty document (or the first draft of your future masterpiece), the first paragraph under the title doesn't semantically differs from the next paragraph. And therefore the large font for the first one looks inappropriate.

When you write the final draft of your document, thoughtfully and carefully, there is no problem to add `[.lead]` manually.

**Comment by mojavelinux** [comment]
Please split this into multiple issues. Combining unrelated issues makes it very difficult to address them, and will likely end up becoming idle.

**Comment by mojavelinux** [comment]
> Automatic lead paragraph

This can already be disabled by adding a role to the first paragraph. (See #2624).

```
= Document Title

[.normal]
This is a normal paragraph.

This is another normal paragraph.

== Heading
```

Here's the CSS rule that implements this:

```css
#preamble>.sectionbody>[class="paragraph"]:first-of-type p{font-size:1.21875em;line-height:1.6;color:rgba(0,0,0,.85)}
```

(This is also why I'm asking to split the issues. Because this is a solved problem, yet the whole issue remains open because it's only one part of it).

**Comment by mojavelinux** [comment]
I will give you a chance to file separate issues. Then, I'll close this one.

**Comment by john-cj** [comment]
Separated into multiple issues:

* https://github.com/asciidoctor/asciidoctor/issues/3381
* https://github.com/asciidoctor/asciidoctor/issues/3382
* https://github.com/asciidoctor/asciidoctor/issues/3383
* https://github.com/asciidoctor/asciidoctor/issues/3384
