### ISSUE TITLE
Quotes: italic text cannot be distinguished from the normal

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3382]
```
[quote]
____
Lorem ipsum dolor sit _amet_, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
____
```

Excerpt from the current stylesheet:

```
.quoteblock blockquote, .quoteblock p {
    font-style: italic;
}
```

The word "amet" cannot be distinguished from the others. Possible fix:

```
.quoteblock blockquote em, .quoteblock p em {
    font-style: normal;
}
```

**Comment by mojavelinux** [comment]
Italics aren't usually expected in a block quote. If you want to provide some sort of emphasis, I would recommend these alternatives:

* strong emphasis (bold)
* marked phrase with color role
* underline (marked phrase with "underline" role)

We don't plan to change the default stylesheet to display emphasis differently in a block quote.
