### ISSUE TITLE
Question: How to detect asciidoc is serving pages on github and/or gitlab

### ISSUE THREAD

**Issue by dibog** [asciidoctor/asciidoctor#3386]
Hi all,

Gitlab and Github can display Asciidoc documents directly from the repo.
Is it possible to detect if such a doc is rendered there to modify some
variables pointing to image or include directories?

Best regards,
Dieter

**Comment by mojavelinux** [comment]
The integration layer automatically adds the document attribute env-github when running on GitHub and env-gitlab when running on GitLab. You can see an example if you view the source of the README for this doc.

**Comment by dibog** [comment]
Thanks. That is great news.
