### ISSUE TITLE
Use cell borders instead of table border

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3387]
I think we should use cell borders (configured to collapse) instead of an outer border defined on the table. The rendering looks the same but the main advantage is that if the table is spread on multiple pages then the border will not be visible when the row ends at the end of a page (see the bottom of the page) and the repeated table header will have a top border (see the top of the page).

Initial discussion: https://github.com/Mogztter/asciidoctor-pdf.js/pull/10

**Comment by mojavelinux** [comment]
I wrote a script to generate a test page for all combinations of frame and grid for all table scenarios. It's a matrix of the following axes:

* frame = all, none, sides, ends
* grid = all, none, rows, cols
* content = header + body + footer, header only, body only, footer only, header + body, header + footer, body + footer, and one for rowspan and colspan

That's 112 possibilities without the rowspan/colspan example, and 128 with it included.

```rb
buffer = <<~'EOS'.lines.map(&:chomp)
= Table Border Testing
:toc: left
:toc-title: Combinations
:!table-caption:
:nofooter:
EOS

%w(all none sides ends).each do |frame_style|
  %w(all none rows cols).each do |grid_style|
    buffer.concat <<~EOS.lines.map(&:chomp)

    :table-frame: #{frame_style}
    :table-grid: #{grid_style}
    == frame=#{frame_style}, grid=#{grid_style}

    .header, body, and footer
    [%header%footer]
    |===
    |header |header
    |body |body
    |body |body
    |footer |footer
    |===

    .header only
    [%header]
    |===
    |header |header
    |===

    .body only
    |===
    |body |body
    |body |body
    |===

    .footer only
    [%footer]
    |===
    |footer |footer
    |===

    .header and body
    [%header]
    |===
    |header |header
    |body |body
    |body |body
    |===

    .header and footer
    [%header%footer]
    |===
    |header |header
    |footer |footer
    |===

    .body and footer
    [%footer]
    |===
    |body |body
    |body |body
    |footer |footer
    |===

    .rowspan and colspan
    |===
    |Column 1 |Column 2 |Column 3

    .2+|Content in a single cell that spans rows 1 and 2
    |Cell in column 2, row 1
    |Cell in column 3, row 1

    2.+|Content in a single cell that spans columns 1 and 2
    |===
    EOS
  end
end

puts buffer.join ?\n
```

**Comment by mojavelinux** [comment]
Borders on a table with rowspan and/or colspan will always work correctly when the frame and grid are congruent. That means they are attempting to add borders on the same edges. These are those scenarios:

* frame=all, grid=all
* frame=all, grid=none
* frame=all, grid=rows
* frame=all, grid=cols
* frame=ends, grid=rows
* frame=sides, grid=cols
* frame=none, grid=none

It's cases where the borders on cells have to be disable that it can get confused by rowspan and colspan.

We should document this.

**Comment by mojavelinux** [comment]
Also make sure to test this case from #2563.

```
[cols=">1h,^.^4,^.^4",options="header"]
|====
|           |Day 1       |Day 2
|08:00   .2+|Task 1   .4+|Task 4
|09:00
|10:00   .2+|Task 2
|11:00
|12:00    2+|*Lunchhour*
|13:00   .4+|Task 3   .4+|Task 5
|14:00
|15:00
|16:00
|17:00
|====
```

**Comment by mojavelinux** [comment]
@Mogztter Could you test the proposed change with Asciidoctor Web PDF and let me know if it gives you the result you are looking for?
