### ISSUE TITLE
img tag is not handled for markdown included documents

### ISSUE THREAD

**Issue by leleabhinav** [asciidoctor/asciidoctor#3389]
Step 1: Lets say I have a markdown document which has images referenced using <img> tag. 
Step 2: Include the markdown document in a asciidoc. 

Result: Rendered html has &lt;img src=.....&gt; which is incorrect.

**Comment by mojavelinux** [comment]
AsciiDoc doesn't process Markdown. (Granted, it's true AsciiDoc does support *some* Markdown syntax in select cases, like headings).

You could write an extension that would process the Markdown at the time it is imported into the AsciiDoc document, though.
