### ISSUE TITLE
unconstrained monospace not supported

### ISSUE THREAD

**Issue by hupfdule** [asciidoctor/asciidoctor#3390]
According to #714 uncontrained monospace text via double backticks should be supported now.
But apparently it isn't.

It tried with asciidoctor 1.5.8 and 2.0.10. Both do not convert the double backticks to `<code>` tags, but insert them literally.

**Comment by mojavelinux** [comment]
Double backticks for unconstrained monospace text is supported. However, it's disabled if you have compat mode enabled (which you really shouldn't be using at this point). See https://asciidoctor.org/docs/migration/#compat-mode for details.

**Comment by hupfdule** [comment]
You are right. compat-mode was active, since I have a setex-style document title.
Without compat-mode the double backticks work as expected.

Thank you!
