### ISSUE TITLE
asciidoctor-mathematical in Atom

### ISSUE THREAD

**Issue by Nathan-Furnal** [asciidoctor/asciidoctor#3392]
Hi, basically I'm unable to render mathematical equations on the preview pane on Atom but found a simple setting that might help other people when exporting to PDF.

With ``asciidoctor-mathematical`` installed and the relevant Atom packages installed :

go into the asciidoc preview settings, open the Export as PDF option and under "Command line additional argument" put :  

`-r asciidoctor-mathematical`

This made rendering easier on Atom,

thank you for the good work and the great package

**Comment by Mogztter** [comment]
Thanks for the hint.
I think it should be moved to: https://github.com/asciidoctor/atom-asciidoc-preview.
We should probably add a note in the documentation and/or in the settings panel.

**Comment by Nathan-Furnal** [comment]
@Mogztter Would you like I open an issue there and close it here ?

**Comment by Mogztter** [comment]
@mojavelinux could you please move this issue to the Atom extension repository?

**Comment by mojavelinux** [comment]
Since Atom has been sunset, so has the extension and thus this issue.
