### ISSUE TITLE
Consider reintroducing the tests in a 2nd flavor of the gem

### ISSUE THREAD

**Issue by aerostitch** [asciidoctor/asciidoctor#3393]
Hi,

I've been fighting for a few weeks to make the version 2 of asciidoctor work.
But as we're using gem2deb, it's really a headache to deal with packages that don't ship their tests, so asciidoc v2 is still not in Debian.
In nokogiri, they ended up doing a specific flavor of their gem: https://github.com/sparklemotion/nokogiri/issues/1855
Do you think it would be an acceptable solution for asciidoctor?

Thanks for your help,
Joseph

**Comment by mojavelinux** [comment]
Why don't you just take the tarball from the tag on GitHub? The tests can
be run directly from the tarball.

I'm not making a separate gem. If anything, we would put the tests back in
this gem. But that seems to be solving the problem on the wrong end.
There's no reason to ship tests for a runtime package.

**Comment by aerostitch** [comment]
I do for the package but in the ruby team we use gem2deb to build that pulls the gem from rubygems.org, so that's a problem.
But I just discovered that someone's working on getting gem2deb modified to fetch directly from github so we should be able to fix that issue.
So closing.

**Comment by mojavelinux** [comment]
Awesome news!

If for some reason that doesn't pan out, I'm willing to entertain the idea of putting the tests in the gem. It's not ideal, but a concession I'm willing to make as a last resort.
