### ISSUE TITLE
Issue loading the syntax_highlighter

### ISSUE THREAD

**Issue by aerostitch** [asciidoctor/asciidoctor#3394]
Hi,

Asciidoctor 2.0.10 has finally entered Debian archive and we're seeing a bug report that I'm not sure where the problem would be: https://bugs.debian.org/935196
It looks like for whatever reason it's looking for the syntax_highlighter in /usr/lib/ruby/lib/asciidoctor/syntax_highlighter instead of /usr/lib/ruby/vendor_ruby/asciidoctor/syntax_highlighter

Have you ever experienced that issue?

Thanks,
Joseph

**Comment by mojavelinux** [comment]
Is the Debian package modifying the LIB_DIR (or ROOT_DIR) by chance?

Here's where the syntax highlighter is loaded: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L514

**Comment by mojavelinux** [comment]
There's no relationship between how the syntax highlighter was loaded before 2.0 with how it is loaded after 2.0. The mechanism completely changed. So there's no use in saying "it used to work" because it isn't even the same code. It's more than something new (the autoload) doesn't work correctly in the Debian environment.

**Comment by mojavelinux** [comment]
I noticed that we're not doing autoload the same way as in the converter.

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L514-L515
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter.rb#L44-L45

See if changing LIB_DIR to __dir__ fixes the issue. Then I'll go ahead and make that change for 2.0.11.

**Comment by aerostitch** [comment]
Thanks a lot fo ryour help, I'll let you know in a bit.

**Comment by aerostitch** [comment]
Your solution worked, thanks! :)
Pushed a PR with the fix.
