### ISSUE TITLE
Internal cross references in code block

### ISSUE THREAD

**Issue by facewindu** [asciidoctor/asciidoctor#3397]
Hi

I was having a code block like 
```
[source.java,subs="attributes,verbatim,quotes,+macros"]
.Using the <<foo_appendix>> 
--
some java code
--
```

For various reasons, I'm trying to move everything in the code block, like
```
[source.java,subs="attributes,verbatim,quotes,+macros"]
--
Using the <<foo_appendix>> 
some java code
--
```

The internal reference is rendered as
```
<a href="#foo_appendix">
  <span class="typ">Foo</span>
  <span class="pln"> </span>
  <span class="typ">Appendix</span><
</a>
```
so it is clickable, but it's styled with the `typ` and `pln` classes from the java block.
How can I avoid that, and get it rendered as `<a href="#build_scan_api">Foo Appendix</a>` like it was before ?

**Comment by Mogztter** [comment]
> For various reasons, I'm trying to move everything in the code block, like

In my opinion, it is not semantically valid.
"Using the <<foo_appendix>>" should not be part of the source block because it's not code.

Could you please give some context? What were the reasons for this change?

Also, I'm not sure if it's intended or not but the definition should be:

```adoc
[source,java,subs="attributes,verbatim,quotes,+macros"]
.Using the <<foo_appendix>> 
--
some java code
--
```
(notice the comma instead of the dot after `source`)

Otherwise the language won't be defined on the `<code>` element (ie. `data-lang="java"`)

**Comment by mojavelinux** [comment]
While you might be able to get this to work by manipulating the subs on the block, as @Mogztter points out, this is not semantically sound. You are free to manipulate the document as you need to, perhaps even using extension, but I just don't recommend it.

**Comment by facewindu** [comment]
> notice the comma instead of the dot after `source`

Yes, this was a typo from my part.

Regarding the main issue, I was using a post-processing JS code block to add some buttons and show/hide code blocks depend on those buttons. I improved the JS logic to be able to support multiple code blocks per button, hence being able to keep the semantically correct approach.

Thank you for your insights
