### ISSUE TITLE
Automatic reference text for simple paragraphs (not headings)

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3398]
The cross references to the section headings automatically takes the referenced text as the reference text. Example:

``` adoc
[[sect]]
== Section

See <<sect>>.
```

Is it possible to use same approach for simple paragraphs and parts inside them? Here are my attempts which doesn't work currently:

``` adoc
[[para]]
Paragraph.

Counter [#counter]#{counter:step}#.

See <<para>>. (Currently: *[para]*. Desired: *Paragraph.*)

See <<counter>>. (Currenlty: *[counter]*. Desired: *1*.)
```

**Comment by mojavelinux** [comment]
Yes, you need to define reftext.

```
[[para,Text To Display In Reference]]
paragraph

See <<para>>
```
