### ISSUE TITLE
Author names with more than two spaces interfere with rendering email address

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor#3403]
If I create a new main index file with an author name with two (or fewer) spaces, I get a rendered, linked email address as expected.

If I create a new main index file with an author name with three (or more) spaces, the email address is treated like text and displayed inside angle brackets in the output.

This works:

```
= AsciiDoctor Testing
Word Word Word <test@example.org>
:revnumber: v0.1
:revdate: 08-29-2019

testing!
```

This does not:

```
= AsciiDoctor Testing
Word Word Word Word <test@example.org>
:revnumber: v0.1
:revdate: 08-29-2019

testing!
```

PS Yes, I am the same Janice with a different company :)

![threespaceauthor](https://user-images.githubusercontent.com/54671493/63942219-4326ac80-ca3b-11e9-93f6-4e382e5cfddd.png)
![twospaceauthor](https://user-images.githubusercontent.com/54671493/63942221-4326ac80-ca3b-11e9-97f4-27d9bcca1735.png)

**Comment by Mogztter** [comment]
The regular expression used to extract the author name and email address has some limitations.
As a workaround, you can define the author name and email as attributes:

```adoc
= AsciiDoctor Testing
:author: Word Word Word Word
:email: test@example.org
:revnumber: v0.1
:revdate: 08-29-2019

testing!
```

**Comment by mojavelinux** [comment]
The parser does account for this scenario. You need to use an underscore in place of the space to adjoin names. You only get 3 positions.

```
Jan Hendrik van_den_Berg
```

See for https://asciidoctor.org/docs/user-manual/#author-and-email for details.

So it would need to be:

```
Word Word_Word Word <test@example.org>
```

(adjoin where appropriate)

**Comment by mojavelinux** [comment]
As Guillaume points out, if you can't use the implicit parsing, use dedicated attributes.

**Comment by janicemhdc** [comment]
Sorry, I missed the underscore in the doc - I'm still getting back in the swing of things!

**Comment by mojavelinux** [comment]
Great! Welcome back!
