### ISSUE TITLE
Support for Aligning Equations

### ISSUE THREAD

**Issue by dillonredding** [asciidoctor/asciidoctor#3405]
Is there support for aligning multiline equations?

I'm new to AsciiMath, but I don't see any inherent support in the [docs](http://asciimath.org/). If I do something like the STEM block below, the equals signs don't quite line up.

```asciidoc
[stem]
++++
f(x) = x^2 + x^2

\ \ \ \ \ \ \ = 2x^2
++++
```

There does seem to be support for this in LaTeX, but I'm entirely sure how the syntax translates to AsciiDoc.

**Comment by mojavelinux** [comment]
This question seems to pertain to AsciiMath. I would ask it here instead: https://github.com/asciimath/asciimathml

Asciidoctor merely passes through the equation to MathJax, which then lays the equation out on the page. Asciidoctor itself doesn't interpret the AsciiMath equation.

**Comment by dillonredding** [comment]
It's not just about AsciiMath. I'm perfectly fine with LaTeX as well, but neither of the following seem to work.

```asciidoc
[stem]
++++
f(x) = x^2 + x^2\\
     = 2x^2
++++
```

```asciidoc
[stem]
++++
\begin{align*}
f(x) &= x^2 + x^2\\
     &= 2x^2
\end{align*}
++++
```

**Comment by mojavelinux** [comment]
Then it's a MathJax issue. Again, Asciidoctor loads MathJax and hands it the equation. If MathJax doesn't honor it, then that's where the problem is.

(If you can demonstrate that what Asciidoctor is giving to MathJax is wrong, then it's an Asciidoctor issue).

**Comment by mojavelinux** [comment]
Here's what Asciidoctor gives to MathJax in the second case:

```
<div class="stemblock">
<div class="content">
\[\begin{align*}
f(x) &amp;= x^2 + x^2\\
     &amp;= 2x^2
\end{align*}\]
</div>
</div>
```

As far as I can see, the equal signs are aligned.

**Comment by mojavelinux** [comment]
Btw, to make latexmath, you either need to set `stem` to `latexmath`, or use:

```
[latexmath]
++++
\begin{align*}
f(x) &= x^2 + x^2\\
     &= 2x^2
\end{align*}
++++
```

**Comment by mojavelinux** [comment]
The following AsciiMath works for me:

```
:stem:

[asciimath]
++++
f(x) = x^2 + x^2 \
     = 2x^2
++++
```

**Comment by dillonredding** [comment]
Gotcha. Messing around with it a bit more, my previewer was broken for LaTeX, but worked fine when compiling the document with the `asciidoctor` CLI. Upgrading the CLI from 1.5.7.1 to 2.0.10 fixed that issue. This also fixed the issue with the AsciiMath alignment, but like you said, there's some _excessive_ spacing happening.

I didn't realize my CLI was _so_ far behind. Sorry about that. I really do appreciate your help on this!

P.S. I'd love to know when the AsciiMath spacing gets fixed as I prefer the simplified syntax over the more complex LaTeX.

**Comment by mojavelinux** [comment]
> Unfortunately, my previewer still doesn't show the alignment correctly.

That's an entirely different issue. Though I see you've found the right place to report it.

> I'd love to know when the AsciiMath spacing gets fixed as I prefer the simplified syntax over the more complex LaTeX.

I've filed an issue to look into it. See #3407.
