### ISSUE TITLE
Destination directory relative to input file

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3406]
Is there an option to specify destination directory relative to input file, instead of relative to working directory? 

Consider the following case:

1. I'm on Windows. I have some documents in `C:\Users\John\Desktop\Docs`. I start cmd.exe; by default, it starts in `C:\Users\John`.
2.  I enter the command: `asciidoctor C:\Users\John\Desktop\Docs\test.adoc --destination-dir=HTML`
3. I want HTML directory to be created in `C:\Users\John\Desktop\Docs`, but it will be created in `C:\Users\John` instead. 

Is there an option to change it?

(Currently I'm working on a GUI utility which could be used as a replacement of Guard, almost done. Of course, I will publish it on GitHub. The question is related to it.)

**Comment by mojavelinux** [comment]
The `:to_dir` option (which is what `--destination-dir`) sets, is always resolved relative to the current directory. However, it does accept an absolute path. So you can precompute that path and pass it to `--destination-dir`.

**Comment by mojavelinux** [comment]
Technically, it's resolved relative to the base dir if set, otherwise the pwd.

It is possible to use a preprocessor extension to manipulate the destination directory, though it may have other side effects on path resolution

```rb
Asciidoctor::Extensions.register do
  preprocessor do
    process do |doc|
      doc.instance_variable_set :@base_dir, (File.join (doc.attr 'docdir'), 'HTML')
      nil
    end
  end
end
```

**Comment by john-cj** [comment]
Thanks. It seems the first way will be better in this particular case.

**Comment by mojavelinux** [comment]
:+1:
