### ISSUE TITLE
Add # Symbol to Predefined Attributes for Character Replacements

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#3415]
# Feature Request

Please, add the hash symbol (`#`) to the list of [predefined attributes for character replacements], for it would be useful to be able to use it inside inline-code like:

```asciidoc
use the `{hash}include` directive.
```

instead of:

```asciidoc
use the `#include` directive.
```

Since this symbol is [called with various names]  (_number sign_, _hash_, _pound sign_ and _sharp_), it might be worthy assigning multiple aliases to it:

- `{hash}`
- `{num}`

# Rationale

Inside in-line code and other verbatim blocks, it's not possible to use the XML Entity for the hash symbol (`&num;`) for it would be treated literally.

Many AsciiDoc editor syntaxes tend to break up when they encounter the `#` symbol, interpreting it as a [custom styling delimiters], and keep waiting for the next `#` to end the current state of parsing.

For the same reason, using a predefined attribute is preferrable for editing reasons too, for it makes it easier to carry out search-&-replace operations in the document sources, separately targetting occurences of the symbol and styling delimiters.

[predefined attributes for character replacements]: https://asciidoctor.org/docs/user-manual/#charref-attributes
[custom styling delimiters]: https://asciidoctor.org/docs/user-manual/#custom-styling-with-attributes
[called with various names]: https://en.wikipedia.org/wiki/Number_sign#Other_names_in_English "See Wikipedia for the various names of the '#' symbol"

**Comment by mojavelinux** [comment]
I don't think this is really necessary. There's already a way to make a literal monospace. The syntax is:

```
`+literal monospace+`
```

This is what you're going to want most of the time anyway.

So it would be:

```
use the `+#include+` directive.
```

You are free to define the `hash` attribute in your documents, of course. But I think that ends up making the content harder to read.

**Comment by tajmone** [comment]
> I don't think this is really necessary. There's already a way to make a literal monospace. The syntax is:
> 
>     `+literal monospace+`
> 
> This is what you're going to want most of the time anyway.
> 
> So it would be:
> 
>     use the `+#include+` directive.

True, but the problem is that most general purpose code editor don't support well this syntax (eg. the ST package for AsciiDoctor, and others), which breaks the syntax and prevents symbols indexing, etc.

Unfortunately the AsciiDoc syntax is too complex to fit general purpose syntax definitions based on RegEx rules, like in the TextMate syntax format (which is what most modern editors are adopting in some variant or another). Only dedicated editors seem to handle the syntax well, possibly because they implement a real code-based parser for the syntax.

The current state of editors lack of support for AsciiDoc might be a contributing factor to the perceived complexity of adopting it as a standard (undoubtedly, having access to advanced editors functions and good highlighting simplifies working on AsciiDoc sources).

Having worked for years with AsciiDoc (Ruby) I still have to struggle with such limitations. There have been fixes for the Asciidoctor extension for ST, but since the package seems no longer actively maintained all fixes PRs have been unanswered for years:

https://github.com/asciidoctor/sublimetext-asciidoc

> You are free to define the hash attribute in your documents, of course. But I think that ends up making the content harder to read.

The downside of this would be in multi-file documents, where the attribute is defined only once in the main file, or via an external file included in each file, which would break previews of the single files (on GitHub, via browser/editor add-ons, ecc.) for the attribute would be unknown.

This wouldn't break any backward compatibility (not with Ruby AsciiDoc anyhow), so I think that any character that is also employed as a formatting delimiter (i.e. `*`, `_`, `#`, and others) ought to be available as a predefined attributes for character replacements (IMO), to prevent similar problems.

**Comment by mojavelinux** [comment]
> True, but the problem is that most general purpose code editor don't support well this syntax (eg. the ST package for AsciiDoctor, and others), which breaks the syntax and prevents symbols indexing, etc.

That problem needs to be addressed at the source, not by changing the language.

**Comment by mojavelinux** [comment]
> The current state of editors lack of support for AsciiDoc might be a contributing factor to the perceived complexity of adopting it as a standard

This is a subjective statement. I work with many organizations who have adopted AsciiDoc and have no problem doing so. By all means, we want to continually strive to make the language as accessible as possible. But that it does not mean that because we see possible improvements that it means there is perceived complexity. Therefore, I don't find this kind of conjecture to be productive.

**Comment by mojavelinux** [comment]
> not with Ruby AsciiDoc anyhow

There is no "Ruby AsciiDoc". AsciiDoc is the language and Asciidoctor is the leading / reference implementation that processes it.

**Comment by tajmone** [comment]
Ok, I don't wan't to give the impression that these were intended as disruptive comments (on the contrary).

> This is a subjective statement. I work with many organizations who have adopted AsciiDoc and have no problem doing so. [...] Therefore, I don't find this kind of conjecture to be productive.

Even if we don't work together I do belong to an organization that has adopted AsciiDoc + Asciidoctor as the official toolchain to handle all documentation. So, I hope there's no shade of doubt that my comments were intended as both subjective impressions and constructive.

Thanks for your support.

**Comment by mojavelinux** [comment]
I'm certainly glad to hear that your organization has adopted the toolchain and I am grateful that you are thinking about ways to make it better. So thank you for your support too.

What I'm aiming to do is focus the conversation on the improvement. There's a place for broad discussions about the accessibility of the language and I don't think an issue like this is the place for it. That's all.

**Comment by mojavelinux** [comment]
> Inside in-line code...it's not possible to use the XML Entity for the hash symbol (`&num;`) for it would be treated literally.

This absolutely works:

```
use the `&num;include` directive.
```

Though in order for it to work in Asciidoctor PDF, you'd need to use the decimal or hexadecimal code:

```
use the `&#35;include` directive.
```

> and other verbatim blocks

Verbatim blocks wouldn't support attribute references either (unless you add `subs=attributes+`). So the proposed change wouldn't help you there anyway.

**Comment by mojavelinux** [comment]
> I think that any character that is also employed as a formatting delimiter ought to be available as a predefined attributes for character replacements

`+` and `*` are already available as `{plus}` and `{asterisk}`.

So that does give some precedent for adding attributes for `_` and `#`.

> it might be worthy assigning multiple aliases to it:

Definitely no aliases. If we do it, we need to pick a name and stick with it. The name `pound` was most popular until hash tags came along, so `hash` is the stronger case right now.

Let's see if there's community support for this idea. Since attributes are essentially global variables that could clash with existing content, we need to add new implicit attributes very carefully.

**Comment by tajmone** [comment]
> Though in order for it to work in Asciidoctor PDF, you'd need to use the decimal or hexadecimal code:
> 
>     use the `&#35;include` directive.

Thanks for this precious tip, I often still struggle with the PDF toolchain (via asciidoctor-fopub) because it's my first approach to both DocBook and FOP (both being huge subjects to learn).


> `+` and `*` are already available as `{plus}` and `{asterisk}`.
> 
> So that does give some precedent for adding attributes for `_` and `#`.

I was in fact giving for granted that `{plus}` and `{asterisk}` were introduced to circumvent editors problems, for unlike special spaces entities these are just plain Ascii chars which don't pose keyobard availability problems nor encoding ones — most editors that do break on AsciiDoc syntax do so due to tokens like these inside inline code, where they mistake them for opening delimiters and keep looping for the closing delimiter in the syntax stack.

I've always relied on `{plus}` and `{asterisk}` to circumvent the ST Asciidoctor package problems — which has ultimately become my excuse for not fixing the issue myself. Today I've decided to create a fork of the original package, and convert the syntax to ST3 and fix all these problems, once and for all.

> Let's see if there's community support for this idea. Since attributes are essentially global variables that could clash with existing content, we need to add new implicit attributes very carefully.

Sure, I wouldn't wont this to introduce problems, I was hoping it might be a harmless addition fully backward compatible.

**Comment by lurch** [comment]
> The name `pound` was most popular until hash tags came along, so `hash` is the stronger case right now.

In the UK, `pound` means `£` so AFAIK `#` has always been `hash` :wink:

**Comment by tajmone** [comment]
> In the UK, `pound` means `£` so AFAIK `#` has always been hash

When the £ was called "Sterling" the `#` was known as "pound" AFAIK.

**Comment by elextr** [comment]
Note, `#` as "pound" is the weight, not the currency.

**Comment by tajmone** [comment]
> Note, `#` as "pound" is the weight, not the currency.

Originally, the Sterling was equal to a pound of silver, hence the name "pound Sterling". Now the £ currency is minted out of vile metals, or even paper, which of course has no counterpart in silver weight nor intrinsic value except mutual consensus. But the pound as weight remains the same, although I've never seen the `#` symbol used for weights, but maybe it was used so in the past.

Definitely, `#` as "hash" seems to be a late name linked to cryptography hash and salt, and although famous among computer programmers it's not the oldest name for the symbol.

The XSL named entity for `#` is `&num;`, which brings us back to the typographical name of the symbol. Other names are often misnomers referring to similar (but not typographically correct) symbols dating back to the Ascii era when substitution by similarity was needed.

**Comment by lurch** [comment]
...at least no-one's suggesting calling it "hashtag" yet! :rofl:

**Comment by elextr** [comment]
https://en.wikipedia.org/wiki/Number_sign

**Comment by mojavelinux** [comment]
There's not a clear path here, and besides this would have to happen in the AsciiDoc Language project. But there is really no need to wait for that. You can define any attribute you want in any place attributes can be defined (the document header, the body, or passed in via the CLI or API).
