### ISSUE TITLE
TSV tables with empty cells don't load correctly

### ISSUE THREAD

**Issue by lurch** [asciidoctor/asciidoctor#3422]
It seems that when I try to load a table in TSV format, and the table has some empty cells, then the display gets screwed up in asciidoctor. I see the same behaviour in both asciidoctor (HTML output) and asciidoctor-pdf (PDF output), which makes me suspect that it's the table-reading code that is messing up?

I've managed to make a small test-case (in the attached zipfile). 
[table-bug.zip](https://github.com/asciidoctor/asciidoctor/files/3632001/table-bug.zip)

AsciiDoctor program versions:
```bash
$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Both the Inline table and the CSV table render correctly as:

| First | Second | Third |
| --- | --- | --- |
| a | b | c |
| A |  | C |
| 1 | 2 |  |
|  | ii | iii |
| x | y | z |

But the TSV table renders as:

| First | Second | Third |
| --- | --- | --- |
| a | b | c |
| A |  | C |
| 1 | 2 |  |
| ii | iii | x |

I've got a **lot** of TSV tables, so I'd prefer not having to convert them all to CSV! :wink:

**Comment by lurch** [comment]
I've found that it _only_ goes wrong when a line in the tab-separated-table ends with one or more empty cells, and it then causes cells on subsequent rows to also become misaligned. (it's almost as though asciidoctor is collapsing `\t\n` to just `\n`)

I've **also** found that I can place `{blank}` as the cell-content in any empty cells at the end of a row in a TSV file, and it displays as originally intended, so this is a valid workaround for now :slightly_smiling_face:

**Comment by mojavelinux** [comment]
> it's almost as though asciidoctor is collapsing \t\n to just \n

Oh, that is true. Asciidoctor strips all trailing whitespace before it parses the document. That behavior can't be changed.

> I've also found that I can place {blank} as the cell-content in any empty cells at the end of a row in a TSV file, and it displays as originally intended, so this is a valid workaround for now

Given how an AsciiDoc parser works, that will need to be documented as that is the only way to address this.

I think the other solution is to load the data from a separate file, since those lines aren't subject to the same whitespace normalization.

**Comment by mojavelinux** [comment]
> those lines aren't subject to the same whitespace normalization.

hmm, they shouldn't be. perhaps that is the issue here.

**Comment by mojavelinux** [comment]
Aha! If the file extension of the include is not AsciiDoc, it doesn't look for preprocessor directives (a flag we call "process lines"). However, it's still normalizing the lines (a flag we call "prepare lines"). But there's no reason it should be doing that. These two flags should be linked. The parser should only normalize lines when it's going to parse those lines as AsciiDoc. I might file this is a separate issue so it's clear what we're fixing.

**Comment by mojavelinux** [comment]
Let's continue in #3436.
