### ISSUE TITLE
Clearing a cellbgcolor inline 'deletes' the cell's content

### ISSUE THREAD

**Issue by lurch** [asciidoctor/asciidoctor#3425]
AsciiDoctor program versions:
```bash
$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.3 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Small test-case: 
[table-colours.zip](https://github.com/asciidoctor/asciidoctor/files/3635527/table-colours.zip)

Using the information in https://github.com/asciidoctor/asciidoctor/wiki/How-to-set-the-background-color-of-a-table-cell I've been adding background colours to my table cells (with the caveat that colour-names like `red` don't work in `asciidoctor-pdf`, but `#ff0000` does work for both HTML and PDF output).
Whilst `{set:cellbgcolor:#ff0000}` works "inline", unfortunately if I try to clear the background colour inline `{set:cellbgcolor!}` then the background colour _does_ get cleared, but the cell's content vanishes!

This means that:
```
|===
|First |Second |Third

|a
{set:cellbgcolor:#ff0000}
|b
{set:cellbgcolor!}
|c
{set:cellbgcolor:#ffff00}

|A{set:cellbgcolor:#ff0000}
|B{set:cellbgcolor!}
|C{set:cellbgcolor:#ffff00}

|===
```
renders the first column in red and the last column in yellow, but the contents render as:

| First | Second | Third |
| --- | --- | --- |
| a | b | c |
| A |  | C |

The reason that this is important (to me), is that being unable to clear the cellbgcolor inline means that I can't fully specify the cell background colours in an external CSV file, as shown in the zipfile above. (Unless there's some cunning workaround?)

**Comment by lurch** [comment]
Alternatively, it might be useful if there was a way to specify "set the cell background colour, but **only for this cell**", so that I don't need to reset the background colour in the next cell.

**Comment by mojavelinux** [comment]
The request to add a role to a table cell is already covered here: https://github.com/asciidoctor/asciidoctor/issues/1338

Unsetting an attribute using set clears the line. So you have to place it on a separate line.

A simpler way to clear the background color is to use the value "transparent" instead of unsetting the attribute.

```
|===
|First |Second |Third

|a{set:cellbgcolor:#ff0000}
|b{set:cellbgcolor:transparent}
|c{set:cellbgcolor:#ffff00}

|A{set:cellbgcolor:#ff0000}
|B{set:cellbgcolor:transparent}
|C{set:cellbgcolor:#ffff00}
|===
```

If this doesn't solve your issue, please feel free to reopen.

**Comment by lurch** [comment]
That's fantastic, thanks for the clarification @mojavelinux :+1: 
If I remember, I'll add some extra notes to the mentioned wiki article on Monday.

It works fine with the HTML backend, but unfortunately `asciidoctor-pdf` errors with:
```
Unknown type of color: "ransparent"
  Use --trace for backtrace
```
Should I open a separate issue for that at https://github.com/asciidoctor/asciidoctor-pdf ?

**Comment by mojavelinux** [comment]
Yes please. That shouldn't be tough to support.
