### ISSUE TITLE
WARNING: image to embed not found or not readable.

### ISSUE THREAD

**Issue by smru** [asciidoctor/asciidoctor#3429]
Asciidoctor generates a warning.

**asciidoctor: WARNING: image to embed not found or not readable: /home/smru/bitbucket/hg/smru/public/doc/text/images/icons/callouts/1.png**

Contents of the adoc file:

```
// Make sure that images are embedded.
:data-uri:

:icons:

// Make sure that css files are embedded.
:linkcss!:

= Test 1

----
powershell.exe Get-Tpm  <1>
----
<1> Windows 8.1 and later.

```

The Font Awesome icons are not embedded and the html file falls back to text instead of icons.
If **:icons:** is replaced by **:icons: font** then the following link is added to the html file.

**&lt;link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"&gt;**

I would like to be able to create an html file that can be viewed offline.
Why is the following line added to the html file?

**&lt;link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700"&gt;**

**Comment by smru** [comment]
_<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">_

_<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700">_

**Comment by smru** [comment]
sssss

**Comment by Mogztter** [comment]
Hello @smru 

> Asciidoctor generates a warning.
> asciidoctor: WARNING: image to embed not found or not readable: /home/smru/bitbucket/hg/smru/public/doc/text/images/icons/callouts/1.png

Asciidoctor does not have a set of default icon images.
So if you want to use icons images, you will need to provide these images.
Alternatively, you can use text, or font icons (using FontAwesome) for callouts.

I believe, you can use the `:iconfont-remote!:` to load `fontawesome.css` from your local disk.


> I would like to be able to create an html file that can be viewed offline.
> Why is the following line added to the html file?
> <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700">

Because your are using the default stylesheet and the default stylesheet is using these fonts but you can provide your own stylesheet.

Related: 
- https://github.com/asciidoctor/asciidoctor/issues/1244
- https://github.com/asciidoctor/asciidoctor/issues/1588
-

**Comment by mojavelinux** [comment]
@Mogztter is correct, to go completely offline, you need to provide the assets yourself. (We use the CDN so you don't have to do this).

If you set `:icons:`, then it's going to look for admonition icons relative to output document. You need to place those there.

If you set `:icons: font`, then it loads the FontAwesome font and uses those glyphs in place of images.

Setting `:data-uri:` is only applicable when using image-based icons. It reads the image from disk during processing an embeds it into the document (creating a self-contained HTML file).

`:linkcss!:` is the default, so you don't need to set it.

The other issue I see is that you have split up your document header. You can't have any blank lines in your document header, so it should look like this:

```
= Test 1
:data-uri:
:icons:

----
powershell.exe Get-Tpm  <1>
----
<1> Windows 8.1 and later.

```

**Comment by wibrt** [comment]
another option is to link the icons directory for your project, to the static dir of asciidoc (the original python version for asciidoc)

`ln -s /usr/share/asciidoc/images/icons icons`

(ideally the fallback, basic icons would be part of asciidoctor)

**Comment by mojavelinux** [comment]
I do not want to ship icons with Asciidoctor. You need to bring your own or point to a URL where they are hosted.

I've explained the options available in my earlier comment. I'm closing this issue to avoid confusion.
