### ISSUE TITLE
Image inline/block are not consistent for PDF/markdown export

### ISSUE THREAD

**Issue by pingtimeout** [asciidoctor/asciidoctor#3431]
Hello Asciidoctor team.  I am running into a weird image behaviour when I export my asciidoc file to either PDF or markdown (with pandoc).

Here is the source asciidoc file to reproduce the issue.  There are two images in a table.  The first is an inline image while the second is an image block.

```
= Image rendering issue

[%autowidth,cols="1*,2*a",options="header"]
|===
| Attribute
| Inline image
| Image block

| Server metrics
| image:https://play.grafana.org/render/dashboard-solo/db/grafana-play-home?orgId=1&width=300&height=250&tz=UTC&timeout=10000&from=now-2h&to=now&panelId=2[]
| image::https://play.grafana.org/render/dashboard-solo/db/grafana-play-home?orgId=1&width=300&height=250&tz=UTC&timeout=10000&from=now-2h&to=now&panelId=4[]
|===
```

When I convert it to PDF using `asciidoctor -b pdf -r asciidoctor-pdf -a data-uri -a allow-uri-read`, only the image block is correctly transformed.  The inline image seems to be replaced by a fragment of the URL.  See this PDF result: [README.pdf](https://github.com/asciidoctor/asciidoctor/files/3662785/README.pdf).

And when I convert it to markdown using `asciidoctor -b docbook -o - | pandoc -f docbook -t markdown_strict --wrap=none`, the problem is the other way around.  Only the inline image is transformed to an `<img>` tag.  The image block seems to be replaced by a similar URL fragment.

The problem is that I need both output formats.  I use the markdown version as a middle format to publish reports to Confluence, and the PDF export to archive them for offline viewing.

Do you have any recommendation on how to work around this issue?

Environment:

* OSX 10.14.5
* Asciidoctor 2.0.10
* ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15] (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by mojavelinux** [comment]
Since the URL doesn't have a file extension, you likely need to specify the image format using the format attribute.

```
image:https://play.grafana.org/render/dashboard-solo/db/grafana-play-home?orgId=1&width=300&height=250&tz=UTC&timeout=10000&from=now-2h&to=now&panelId=2[format=png]
```

You also don't need to set `data-uri` when converting to PDF as that is already implied.

I'm not able to dig any deeper since those URLs don't send back and image. Perhaps it's timing out?

**Comment by mojavelinux** [comment]
The conversion from DocBook to Markdown is a shortcoming of pandoc. It's not reading the image object correctly.

**Comment by mojavelinux** [comment]
On my machine, Asciidoctor embeds the image in ~5s, around the same time as curl. Asciidoctor is using the standard HTTP client in Ruby, so the content negotiation is outside the scope of Asciidoctor.

Are you sure Docker wasn't downloading the container image in your test? Can you try it multiple times? If the latency remains, it's something in the network layer.

> I am using a block inside a table, and now I am wondering if this is a correct thing.

A block image is allowed in a table cell as long as the table cell has the AsciiDoc (a) style.

Though it still depends on what the DocBook toolchain supports. I don't think the DocBook toolchain supports remote or data URIs by default. So that could be part of the problem. I recommend using Asciidoctor PDF instead.

**Comment by pingtimeout** [comment]
This is very interesting.  I could reproduce the problem with both the docker image and asciidoctor-pdf standalone:

```
$ time docker run -it -v $PWD:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf -a allow-uri-read -o /documents/README.pdf /documents/README.adoc
docker run -it -v $PWD:/documents asciidoctor/docker-asciidoctor  -a  -o    0,04s user 0,02s system 0% cpu 4:04,69 total
$
$ time asciidoctor-pdf -a allow-uri-read -o README.2.pdf README.adoc
asciidoctor-pdf -a allow-uri-read -o README.2.pdf README.adoc  0,64s user 0,18s system 0% cpu 4:02,33 total
```

The attempt at using docker was actually to be 100% sure I was running in a correct environment, with all libraries available.  Sorry for the confusion.

Anyway, the two are based on recent Asciidoctor PDF:

```
$ docker run -it -v $PWD:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.5 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.4 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

But another interesting point is that you say "On my machine, Asciidoctor *embeds* the image".  Here, I still end up with the alt-text and not the image itself, in the PDF.  This suggests some environment or version issue, doesn't it?

**Comment by mojavelinux** [comment]
If you are getting the alt text and not the image, the image is failing to download.

**Comment by pingtimeout** [comment]
Yeah, this is really strange.  So far, I ran with three different asciidoctor-pdf and ruby combinations and always end up with a 4min wall clock time.  Most certainly the time it takes for the image download to timeout.

- asciidoctor-pdf 1.5.0-beta4 and ruby 2.4
- asciidoctor-pdf 1.5.0-beta5 and ruby 2.5
- asciidoctor-pdf 1.5.0-beta6 and jruby 9.1.13.0

So it must come from the environment.  Continuing the investigations...

**Comment by mojavelinux** [comment]
I would encourage you to drop down to Ruby so you can find the latency more easily. Here's the code:

https://github.com/asciidoctor/asciidoctor-pdf/blob/7512d55cf8af9863f5170c2aae2bb3d46b66c4d4/lib/asciidoctor/pdf/converter.rb#L3903-L3924

**Comment by pingtimeout** [comment]
This becomes even weirder...  I went back to Ruby and tried to profile the application.  It seems that most of the time is spent out of the ruby process, given the CPU `user+system` values compared to the wall clock time.

```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.6 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$
$ time ruby -rprofile -S asciidoctor-pdf -a allow-uri-read -o README.ruby24-pdfbeta6-profile.pdf README.adoc 2>&1 | tee profile.2.txt
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 23.27     2.46      2.46    32148     0.08     0.30  TTFunk::Table::Kern::Format0#initialize
  8.23     3.33      0.87    35636     0.02     0.03  TTFunk::Reader#to_signed
  3.12     3.66      0.33    39582     0.01     0.01  Array#hash
  2.93     3.97      0.31    11423     0.03     0.13  Prawn::Font::AFM#parse_afm
  2.65     4.25      0.28   134152     0.00     0.00  Integer#*
  2.65     4.53      0.28    52141     0.01     0.01  Hash#[]=
  2.18     4.76      0.23     1026     0.22    18.58  Kernel#require
  2.08     4.98      0.22     5724     0.04     0.15  TTFunk::Table::Cmap::Format04#parse_cmap!
  2.08     5.20      0.22   130162     0.00     0.00  Array#[]
  1.99     5.41      0.21       56     3.75   102.68  Integer#times
  1.89     5.61      0.20     5734     0.03     3.06  Array#each
[...]
  0.00    10.57      0.00        1     0.00 10570.00  #toplevel
ruby -rprofile -S asciidoctor-pdf -a allow-uri-read -o  README.adoc 2>&1  10,65s user 1,26s system 4% cpu 4:13,52 total
tee profile.2.txt  0,00s user 0,01s system 0% cpu 4:13,53 total
```

Yet, the `curl` command still fetches the image in a reasonable time.

```
$ for i in {0..9}; do time curl --silent 'https://play.grafana.org/render/dashboard-solo/db/grafana-play-home?orgId=1&width=300&height=250&tz=UTC&from=now-2min&to=now&panelId=2' >image.$i.png; done
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 7,162 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 3,070 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 5,838 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 5,635 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 6,606 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 8,505 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 5,366 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 2,458 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 5,222 total
curl --silent  > image.$i.png  0,01s user 0,01s system 0% cpu 4,915 total
```

Do you have any idea on how I can investigate this further?  Also, to be 100% sure, could you confirm how the `docker run -it -v $PWD:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf -a allow-uri-read -o /documents/README.pdf /documents/README.adoc` command behaves on your machine?

**Comment by pingtimeout** [comment]
I also reproduced the issue on a separate Linux machine located elsewhere

```
automaton@ip-10-200-180-53:~$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.beta.6 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
automaton@ip-10-200-180-53:~$ time asciidoctor-pdf -a allow-uri-read -o README.2.pdf README.adoc

real	4m2.037s
user	0m1.004s
sys	0m0.192s
```

**Comment by mojavelinux** [comment]
The problem is with the play.grafana.org server. Sometimes it's not closing the connection, which hangs the HTTP client. If I catch the error internally, this is what I see:

```
#<Net::ReadTimeout: Net::ReadTimeout>
```

This really has nothing to do with the AsciiDoc processor.

**Comment by pingtimeout** [comment]
Woah...  Then it must mean that the problem is in Grafana itself.  That would explain why I have this issue with my own Grafana servers.

Thank you very much for your help!  I am going to investigate on Grafana's side and see if there is anything I can do there.
