### ISSUE TITLE
Spaces in url are escaped

### ISSUE THREAD

**Issue by teble** [asciidoctor/asciidoctor#3432]
- I use the asciidoctor-maven-plugin(version is 1.5.3) to generator my api doc，but i have a api and the url such as `api/products?beginTime=2019-01-01 12:00:00&endTime=2020-01-01 12:00:00`
- after run tests,i foud `GET api/products?beginTime=2019-01-01+12%3A00%3A00&endTime=2020-01-01+12%3A00%3A00 HTTP/1.1` in my http-request.adoc
- what should i do?

**Comment by mojavelinux** [comment]
Spaces must be escaped in a URL to make it portable. But perhaps you don't want the URL to be interpreted as a URL. In that case, you can escape it using an inline passthrough (surround in +).

Can you provide a complete example so that we can understand the context better?

**Comment by teble** [comment]
ummm, you may understand what I mean wrong. I want to express is that the url is abnormally escaped.
- eg: I want to use doc to generate documentation for an api: `http://localhost:8080/api/products?beginTime=2019-01-01 12:00:00&endTime=2020-01-01 12:00:00`, **that the url contains spaces**.
But, in the subsequently generated document, i found HTTP request `GET api/products?beginTime=2019-01-01+12%3A00%3A00&endTime=2020-01-01+12%3A00%3A00 HTTP/1.1`, The ` `(space) exception becomes `+` and `:` exception becomes `%3A`. Under normal circumstances, the ` `(space) in the url should be changed to `%20`, and the `:`does nothing.

**Comment by mojavelinux** [comment]
> i found HTTP request GET `api/products?beginTime=2019-01-01+12%3A00%3A00&endTime=2020-01-01+12%3A00%3A00` HTTP/1.1, The (space) exception becomes `+` and `:` exception becomes `%3A`. Under normal circumstances, the (space) in the url should be changed to `%20`, and the `:` does nothing.

Asciidoctor adheres to the rules defined by RFC-3986, which stipulates that `:` is not a reserved character and space should be escaped as `+`.

These rules are explained in more detail on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Description.

**Comment by mojavelinux** [comment]
To implement these escaping rules, Asciidoctor relies on CGI.escape from the Ruby core library.

**Comment by mojavelinux** [comment]
There is debate over whether + or %20 should be used for spaces. In my experiments, browsers and other HTTP clients use these characters interchangeably, so both are correct.
