### ISSUE TITLE
Menu macro breaks inline image that follows in paragraph

### ISSUE THREAD

**Issue by zwaldowski** [asciidoctor/asciidoctor#3433]
See this gist: https://gist.github.com/zwaldowski/a7b3257e97f9ce1d786f6cbd9d7247e2. This doesn't seem to be related to other macro expansion issues as they _shouldn't_ (AFAIK) be expanding inside each other.

**Comment by mojavelinux** [comment]
This is only a bug on GitHub because it's not running the latest version of Asciidoctor (2.0.7 instead of 2.0.10). This issue was addressed by #3279.

**Comment by zwaldowski** [comment]
Thank you for the quick response. It also appears asciidoctor/asciidoctor.js and asciidoctor/asciidoctor-vscode are behind, so appearing more than once fooled me. More issues for everyone else! 😉

**Comment by mojavelinux** [comment]
The good news is that we did pick up on this and address it. It will just take some time for that fix to roll out. :+1:

**Comment by zwaldowski** [comment]
Yes, thank you. 😄

I understand the GitHub preview being a bit behind, but I'm struggling right now to understand why the latest asciidoctor/asciidoctor-vscode (2.7.6) doesn't appear to have the fix, despite it using the latest asciidoctor/asciidoctor.js (2.0.3) which should include the fix from 2.0.9. Does that sound familiar at all?

**Comment by zwaldowski** [comment]
OK. Was seeing some spooky-action-at-a-distance. I _do_ have 2.0.9 with the fix (the regex change) from #3280, it doesn't seem to be working as a fix when in JS. Maybe a regex engine difference? Filed asciidoctor/asciidoctor.js#754, I'll shut up about it over here. Thanks again!

**Comment by mojavelinux** [comment]
Let's continue the discussion there and make sure there's a test in place.

**Comment by mojavelinux** [comment]
As it turns out, this is a bug in core that only shows up in Asciidoctor.js. The group expression that matches empty string is also marked as optional. While this works in Ruby, it doesn't work in JavaScript. Removing the optional flag does not impact the behavior of core, so we can change it here.

**Comment by mojavelinux** [comment]
@zwaldowski nice detective work!
