### ISSUE TITLE
Only normalize included content if target ends in a known AsciiDoc extension

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3436]
The parser only runs the AsciiDoc preprocessor on included content if the target ends with a known AsciiDoc extension (e.g., .adoc). However, it always normalizes the lines (removes trailing whitespace). This can result in data, such as TSV data, being normalized when it shouldn't be.

The two behaviors should be linked. The lines should only be normalized *if* they are going to be parsed as AsciiDoc.

If necessary, in the future, we may consider an option to force the parser to normalize the lines.

**Comment by mojavelinux** [comment]
This actually gets complicated pretty quickly because the logic to reencode the data to UTF-8 is coupled with the logic to strip the trailing whitespace. However, I think we can add an extra argument to the helper function that controls how the lines are cleaned. The default option will match the current behavior, which is to call `rstrip` on each line. This can be overridden by passing `chomp` instead (which only removes the trailing newline).

**Comment by Mogztter** [comment]
> I'm wondering whether this should go in the next minor, or whether it's okay in the patch.

I think it should go in the next patch release. 

> It does slightly change the behavior of the processor

That's true but it wasn't intended so we fixed it.

> which is why I'm leaning towards the minor.

I think it can go in a minor/feature version if you introduce a mechanism to support the old behavior. In this case it's a new feature where you can choose if you want to normalize the content or not. But, to be honest, I think it's outside the scope of what the processor should provide.
