### ISSUE TITLE
allow list formatting inside variables/attributes

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor#3443]
I have a few short lists that logically should be variables (user defined attributes) in my scheme of things because they are subject to modification/addition/subtraction on a semi-regular basis. I tried defining them as multi-line attributes using the " + \\" syntax for end of line and it worked, but I realized that they really are lists and, as such, should be rendered as unordered lists. I tried adding the formatting for this but it just renders as text. I tried using passthrough and subs per the doc but that either resulted in the same formatting as not using them or in a single line that rendered the + symbols (I did not try every possible combination of subs and do not profess to fully understand what each option does so it's possible a different combination may work).

I am going to define these lists in separate includable files as a workaround, but as this is content expected to change fairly regularly it breaks my documentation model to do so. If there is a way to define these in my variables file (my document-wide global list of user-defined attributes) it would be a much more elegant solution.

ETA: It won't let me attach an asciidoctor file so here's the test file I worked up showing some of the variations I tried:

```
//list start
:mylist1: * A + \
* B + \
* C + \
* D
//list end

//list start
:mylist2: pass:quote[* A + \
* B + \
* C + \
* D]
//list end

//list start
:mylist3: pass:q[* A + \
* B + \
* C + \
* D]
//list end

List 1:

{mylist1}

List 2:

{mylist2}

List 3:

{mylist3}

List 1 with subs:

1:
[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
{mylist1}

2:
[subs="specialchars,attributes,quotes"]
{mylist1}

3:
[subs="attributes,quotes"]
{mylist1}

4:
[subs="attributes,quotes,replacements"]
{mylist1}

5:
[subs="attributes,quotes,macros,post_replacements"]
{mylist1}
```

**Comment by Lunadoz** [comment]
A alternate methode, include list like this : 

main.adoc
`=My guide for blabla
include::_mylist.adoc[]`

_mylist.adoc
`* A
* B
* C
* D`

**Comment by Mogztter** [comment]
> I have a few short lists that logically should be variables (user defined attributes) in my scheme of things because they are subject to modification/addition/subtraction on a semi-regular basis

Using a variable makes sense if you are using it in more than one place. Is that your case? i.e., do you use the same list in different places/files?

As mentioned by @Lunadoz it's probably better to use an include for this task. Is there any reason why you want to use attributes?

In the future, please direct usage questions to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). You can find out more about our support policies on the following page: [docs.asciidoctor.org/about/support](https://docs.asciidoctor.org/about/support).

**Comment by mojavelinux** [comment]
It's not possible to do block-level formatting in an attribute value. That is not the intended design of an attribute. As others have pointed out, the include (and if not that, a syntax extension) is the right solution here.
