### ISSUE TITLE
nesting description lists

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor#3445]
The documentation talks about nesting lists, but the examples that include description lists have them as the outer list. I want to nest description lists inside an ordered list and it doesn't appear to work (I tried a few different spacing variations to see if it helped and it didn't).

Basically, the numbered list works and the :: is rendered as text.

```
. foo1::bar1
. foo2::bar2
```
renders as seen in the screenshot.

![nesteddl](https://user-images.githubusercontent.com/54671493/66208417-03c72d80-e683-11e9-99fc-1d3a978f9c4f.png)

**Comment by Mogztter** [comment]
Hello @janicemhdc 


You can use the following:

```adoc
. {empty} +
foo1:: bar1
. {empty} +
foo2:: bar2
```

![nested-list](https://user-images.githubusercontent.com/333276/66211198-d64aa600-e6bb-11e9-9b8f-71c42c6614a0.png)

Is it what you expected?

**Comment by Mogztter** [comment]
The following is also working:

```adoc
. {empty}
foo1:: bar1
. {empty}
foo2:: bar2
```

![nested-list-desc](https://user-images.githubusercontent.com/333276/66211390-45c09580-e6bc-11e9-944f-e34b61711235.png)

**Comment by janicemhdc** [comment]
The second case is what I wanted. Thanks.
