### ISSUE TITLE
collapsible doesnt work on IE/Edge

### ISSUE THREAD

**Issue by barbich** [asciidoctor/asciidoctor#3453]
Hi
On Microsoft Edge 41.16299.1004.0 (yes I know who uses Edge), the collapsible feature doeswork (while the same content in Chrome works fine).
Are there some conditions for IE/Edge use?

tx

**Comment by Mogztter** [comment]
The collapsible feature is using `<details>` and `<summary>` elements: https://caniuse.com/#search=summary

You will need to use Edge 76 (Chromium based) or to write a custom converter to implement this feature for IE/Edge 18 (most likely using JavaScript to show/hide element contents).

**Comment by mojavelinux** [comment]
It's not up to the converter to polyfill the browser. So this built-in feature is simply not available on outdated browsers. If you want support, you can extend the converter and modify the output, as @Mogztter hinted at.

**Comment by mojavelinux** [comment]
This feature works fine on Edge.
