### ISSUE TITLE
Definition lists are broken up by comments

### ISSUE THREAD

**Issue by jroessel** [asciidoctor/asciidoctor#3454]
Sample code:

```
Term::
Definition

Term 2::
Definition

// some comment

Term 3::
Definition
```

The last term gets its own definition list in the output. Removing the comment or the empty lines around it seems to resolve this, but I guess they shouldn't make a difference in parsing in this case.

I've solved this with a preprocessor by now that strips comments.

**Comment by mojavelinux** [comment]
This is by design. A comment line surrounded on either side by a blank line is a list break indicator.

If you want to include a comment between two entries, the lines need to be contiguous.

```
Term::
Definition

Term 2::
Definition
//
// some comment
//
Term 3::
Definition
```

(There are other combinations that work as well, but this is the most clear).
