### ISSUE TITLE
Preserve repeating backslashes in manpage output

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3456]
Currently, none of the following is working:

```
\\
```
```
\\\
```
```
\\\\
```
```
{backslash}{backslash}
```

Initially reported as a question on Stackoverflow: https://stackoverflow.com/questions/56864050/how-to-escape-double-backslashes-so-i-can-get-in-man-page

**Comment by mojavelinux** [comment]
The regular expression that is used to preserve literal backslashes is malfunctioning. The backslash in the content is somehow getting mixed up with the backslash in the replacement. And we're also missing a test.
