### ISSUE TITLE
Percent width on inline svg image does not work

### ISSUE THREAD

**Issue by krOoze** [asciidoctor/asciidoctor#3464]
Source:
```
image:image.svg[width=50%, opts="inline"]
```

Output (`asciidoctor -b html5 width.adoc`):
```
<svg version="1.1" viewBox="0 0 8.9818 8.9818" xmlns="http://www.w3.org/2000/svg" width="50%px">
```

The [Image sizing attributes](https://asciidoctor.org/docs/user-manual/#image-sizing-recap) table says percent sizes are allowed.

**Comment by mojavelinux** [comment]
I agree, that appears to be an oversight in the SVG cleaner.

**Comment by krOoze** [comment]
PS: Actually [Summary](https://asciidoctor.org/docs/user-manual/#summary-2) table says it is in pixels though; should probably be updated there.

**Comment by mojavelinux** [comment]
We should point out that the % width is not portable as described in #1894. Here's where that's stated: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-width

Browsers seem to allow the width attribute to be a %. But it doesn't validate.

> Bad value 50% for attribute width on element img: Expected a digit but saw % instead.

So I don't think we should document how to set a percentage width until #1894 is solved (the percentage width needs to go in the style attribute instead).

**Comment by mojavelinux** [comment]
Or we can say that a % width is allowed when the image is an SVG with opts=inine as that validates.

**Comment by krOoze** [comment]
Right. Actually seems invalid in HTML5. Weird.
Might be a reason to instead use `style="width: 50%"`...

**Comment by mojavelinux** [comment]
Which is what #1894 is proposing.
