### ISSUE TITLE
Blank lines above document header not skipped when sourced from an include file

### ISSUE THREAD

**Issue by hkp-wcd** [asciidoctor/asciidoctor#3470]
### Version
```
asciidoctorjs --version
Asciidoctor.js 2.0.3 (Asciidoctor 2.0.9) [https://asciidoctor.org]
Runtime Environment (node v10.14.2 on darwin)
CLI version 3.0.1
```

### Description

An error appears depending on if an included file contains a newline as first line.
```
    "severity": "ERROR",
    "message": {
      "text": "level 0 sections can only be used when doctype is book",
```
### Minimum reproducible example
_index.adoc_
```asciidoc
include::shortcuts.adoc[]
= Bug Demo

```

_shortcuts.adoc_
```

:demo:
```

To produce the error message run
_adoc.js_
```javascript
const asciidoctor = require('asciidoctor.js')();
const fs = require('fs');

const memoryLogger = asciidoctor.MemoryLogger.$new();
asciidoctor.LoggerManager.setLogger(memoryLogger);

const adocFileContents = fs.readFileSync('index.adoc');
const doc = asciidoctor.load(adocFileContents, { 'safe': 'safe', 'catalog_assets': true });
Opal.gvars.VERBOSE = true;
doc.convert();
console.log(JSON.stringify(memoryLogger.getMessages(), null, 2));
```

Here is a repository contaning the files https://github.com/hkp-wcd/adoc-bugs
Extract the zip files if copy pasting from this issue doesn't work.

Best regards!

**Comment by mojavelinux** [comment]
The parse_document_header needs to start with a call to `reader.skip_blank_lines`. We can also skip removing leading blank lines when preparing lines in the reader, since lines may be contributed by an include file.

**Comment by hkp-wcd** [comment]
Thank you for taking this issue up so quickly!
