### ISSUE TITLE
Infinite loop when an invalid callout list follows a list item

### ISSUE THREAD

**Issue by cawalch** [asciidoctor/asciidoctor#3472]
```javascript
const asciidoctor = require('asciidoctor')()
asciidoctor.convert(Buffer.from('103a3a0a393e0901', 'hex'))
```
**Version** 2.0.3

Found with [jsfuzz](https://github.com/fuzzitdev/jsfuzz)

**Comment by mojavelinux** [comment]
The problem occurs when an old-style callout list item follows another list item. Here's another example:

```
* foo
1> bar
```

It also happens for this case:

```
* foo
<.> bar
```

All part of the same problem.

**Comment by Mogztter** [comment]
Thanks for your report @cawalch!
Is it worth to run jsfuzz as part of the CI on Travis?

@mojavelinux Do you reproduce this issue in Ruby?

**Comment by mojavelinux** [comment]
Yep, I can reproduce it using exactly the scenario the NOTE in the code warns about.

> Is it worth to run jsfuzz as part of the CI on Travis?

It certainly couldn't hurt.
