### ISSUE TITLE
How to convert AsciiDoc to Microsoft Word?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#3481]
I like writing all my documents with AsciiDoctor. It is a great tool.

Sometimes, I have to write a document with Microsoft Word. Handling styles is cumbersome.

**Why does AsciiDoctor support to convert AsciiDoc to Microsoft Word?**

I study the idea simply.

Microsoft Word is a series of documents in Open Office XML, WordprocessingML (docx). The DocBook and HTML5 are XML. **So maybe add a Microsoft Word backend  to support to convert the AsciiDoc document to Microsoft Word.**

- [Office Open XML - What is OOXML?](http://officeopenxml.com/)
- [Office Open XML - Wikipedia](https://en.wikipedia.org/wiki/Office_Open_XML)
- [OOXML Format Family -- ISO/IEC 29500 and ECMA 376](https://www.loc.gov/preservation/digital/formats/fdd/fdd000395.shtml)
- [DOCX Transitional (Office Open XML), ISO 29500:2008-2016, ECMA-376, Editions 1-5](https://www.loc.gov/preservation/digital/formats/fdd/fdd000397.shtml)

_The OOXML Spec is very big. There are over five thousand pages(From Wikipedia)._

**Comment by kubamarchwicki** [comment]
I've started playing with that long time ago, as kind of pet project. While initially I was willing to use it to build project documentation for client, we ended up collaborating on github and creating PDF as a finalized version of the document.

The code is here https://github.com/kubamarchwicki/asciidoctor-fodt, and in some situations it works. It outputs openoffice compliant format

**Comment by mojavelinux** [comment]
You can also find a related converter here: https://github.com/gregturn/asciidoctor-packt. Though it's focused on book publishing, it provides a solid foundation on which to build.

There's room in the Asciidoctor ecosystem for a converter to Word / ODF. It's not something I have the time or interest to do, but I will support whoever does however I can.

As this is a general ecosystem discussion, it should be moved to https://discuss.asciidoctor.org.

**Comment by pihentagy** [comment]
Why not https://rmoff.net/2020/04/16/converting-from-asciidoc-to-google-docs-and-ms-word/ ?

**Comment by diguage** [comment]
> Why not https://rmoff.net/2020/04/16/converting-from-asciidoc-to-google-docs-and-ms-word/ ?

It's a great idea. Thanks a lot.

**Comment by grexe** [comment]
that's still the best option it seems, worked fine for me, thanks @pihentagy

**Comment by KingJulianS** [comment]
It works👍 but removed my admonitions.

**Comment by grobmeier** [comment]
I know this is old and closed, but I made a simple Docker container based on the blog post mentioned earlier. For those in need, you can get the Docker container here:
https://github.com/grobmeier/asciidoc-to-word

**Comment by adamryczkowski** [comment]
The walkaround method via docbook does not work with equations.
