### ISSUE TITLE
Error Parsing Internal Reference

### ISSUE THREAD

**Issue by Alphastrick** [asciidoctor/asciidoctor#3483]
| Version | Platform | Format | Example |
|:-:|:-:|:-:|-:|
| 2.0.10 | Ruby | HTML | [issue.zip](https://github.com/asciidoctor/asciidoctor/files/3845544/issue.zip) |

Converting a internal reference like `<<my__reference.adoc#anchor__withname, Reference>>` will be converted to `my<em>reference.html#anchor</em>withname`.

**Comment by mojavelinux** [comment]
The double underscore is an unconstrained formatting mark. You will need to escape it.

```
<<my\__reference.adoc#anchor__withname,Reference>>
```

Generally, I recommend avoiding the use of double underscores in filenames and IDs.

**Comment by Alphastrick** [comment]
I know and I've done that already, but I don't see why it should be interpreted as emphasized text. Due to the reference, it's clear that this shall be a link.

**Comment by mojavelinux** [comment]
Until #61 is resolved, what you're asking for cannot be implemented. The parsing is currently context free (mostly). There's no way for the parser to know that what it is parsing is inside of an xref.

You can somewhat control it by using the pass macro, which allows you to parse in chunks.

```
pass:n,-q[<<my__reference.adoc#anchor__withname, Reference>>]
```

**Comment by mojavelinux** [comment]
`n,-q` is "normal minus quotes" (which you can also write longhand).
