### ISSUE TITLE
Escape (generated) text inside pass

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor#3485]
Say I have a piece of text that I want to output as-is (using a PDF, html, or whatever backend).

The [manual](https://asciidoctor.org/docs/user-manual/#escaping-unconstrained-quotes) tells me to use pass:c[the piece of text], inside quotes.

Problem: the text may itself contain ]. Or any other strange characters (such as [U+2019 Right Single Quotation Mark](https://unicode-table.com/en/2019/), ’, or quotes, `). In fact, I need a most general escaping solution, as the text comes from an external source and is not under my control.

(Might be related to #3251, but I do not understand the suggestion there.)

How should I (programmatically) escape the piece of text before surrounding it with pass:c[…] and quotes? (Or should I adopt an entirely different approach?)

**Comment by mojavelinux** [comment]
You need to escape any `]` in the text inserted inside the contents of the `pass:[]` macro. That's just how AsciiDoc is defined. You can escape it using `\]` or `&#93;`

In the future, please ask questions about the syntax in the project chat at https://chat.asciidoctor.org. Thanks.
