### ISSUE TITLE
reference to dotted folder (.folder)

### ISSUE THREAD

**Issue by torsten-github** [asciidoctor/asciidoctor#3489]
Refernce to document does not work, when a folder starts with a dot:

`<<.app/README.adoc#,click-me>>`
`<<abc/.idea/README.adoc#,click-me>>`

without dot it's fine:

`<<app/README.adoc#,click here>>`

**Comment by mojavelinux** [comment]
As far as I can tell, Asciidoctor is producing the correct result. When I try the following with Asciidoctor 2.0.10:

```
<<.app/README.adoc#,click-me>>
```

I get:

```
<div class="paragraph">
<p><a href=".app/README.html">click-me</a></p>
</div>
```

Are you expecting something different? If so, please describe.
