### ISSUE TITLE
Improve support of embedded YouTube playlists

### ISSUE THREAD

**Issue by yurloc** [asciidoctor/asciidoctor#3490]
YouTube embedded player now has three forms of showing a [playlist](https://developers.google.com/youtube/player_parameters#Selecting_Content_to_Play).

The playlist type is determined by the `listType` parameter.

## 1. Playlist ID

`listType=playlist&list=PLAYLIST_ID`

## 2. User uploads

`listType=user_uploads&list=USERNAME`

## 3. Search query

`listType=search&list=QUERY`

Asciidoctor doesn't support the `listType` parameter. Use case 1 can be achieved using the undocumented custom list syntax introduced in #1187 like this:
```
video::/PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns[youtube]
```
and results in:
```
<iframe src="https://www.youtube.com/embed/?rel=0&list=PLJY69IMbAdq0uKPnjtWXZ2x7KE1eWg3ns" allowfullscreen="" frameborder="0"></iframe>
```
which works but `listType=playlist` is missing.

The other two use cases are not achievable because it's not possible to specify the `listType` parameter.

**Comment by Mogztter** [comment]
Out of curiosity, do you know what does `listType=playlist`? I've been using the `list` attribute on the `video` macro (instead of an iframe where `listType=playlist` was present in the URL) but I didn't notice any notable difference... ?

**Comment by yurloc** [comment]
@Mogztter I think `listType=playlist` might be the default value so effectively it does nothing because even if you leave it out, the value after `list=` is interpreted as a playlist ID.

https://developers.google.com/youtube/player_parameters#listtype

**Comment by mojavelinux** [comment]
Please propose how this could be expressed using the video macro and I'd be happy to consider supporting it. Once we decide the syntax, you can speed up the process by submitting PR, if you can.

**Comment by yurloc** [comment]
That's the hard part :slightly_smiling_face:. I wouldn't mind learning some Ruby and contribute the enhancement but I don't have a clear vision of the syntax yet. Therefore I wanted to open an issue first so that we have a place to discuss possible solutions. I'll think about it and try to propose something later.

Everyone else, feel free to share your proposal!

**Comment by mojavelinux** [comment]
The search value for listType has been removed as of Nov 2020. I really don't see much use for the user uploads as this can be replaced by a playlist (which is likely going to be more organized anyway). Therefore, I don't want to pursue this idea in Asciidoctor core. However, you are welcome to extend the HTML converter to provide your own implementation.
