### ISSUE TITLE
Allow plugging "convert_outline"

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#3491]
I'd like to be able to override the TOC conversion behavior, at least some. Right now the html5 converter has `convert_outline doc` but if it did something like `doc.converter.convert doc, 'outline'` then I could plug in my conversions. Is that a thing you'd be ok doing?

**Comment by mojavelinux** [comment]
I'm not sure I understand the question. You've described how to customize the outline. What's the problem?

You can either extend the converter like so:

```rb
class MyHtmlConverter < (Asciidoctor::Converter.for 'html5')
  register_for 'html5'
  def convert_outline node, opts {}
    # do your thing
  end
end
```

Or you can pass a template that has the name `outline` (or `block_outline`), like https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/block_outline.html.slim.

**Comment by mojavelinux** [comment]
I think I see what you're saying. The second approach doesn't work when using the built-in converter since the calls to block_outline doesn't get routed back through the converter dispatcher. Yes, we could consider doing that.

**Comment by nik9000** [comment]
Sorry I wasn't clear! I was trying to do this:
```
rm -rf t && mkdir t && echo 'asdf' > t/block_outline.html.slim && echo '== Foo' | bundle exec asciidoctor -b html5 -atoc -T t -
```

And it wasn't working. I *think* it is because the html 5 converter calls `convert_outline` directly so the delegation the composite converter doesn't kick in.

**Comment by mojavelinux** [comment]
Yes, you are correct. It's clear now.

**Comment by mojavelinux** [comment]
Though without any loss of functionality otherwise, you could use the extended converter I shared above. And, in fact, you could use that to enable this behavior without having to wait on a change in Asciidoctor.

Here's how you'd do it:

```rb
class MyHtmlConverter < (Asciidoctor::Converter.for 'html5')
  register_for 'html5'

  def convert_outline node, opts = {}
    if opts.fetch :internal, true
      (doc = node.document).converter.convert doc, 'outline', (opts.merge internal: false)
    else
      super
    end
  end
end

```

**Comment by nik9000** [comment]
> Yes, you are correct. It's clear now.

Thanks for replying! I'd be happy to try and put together a PR on Monday if you'd like one.

**Comment by mojavelinux** [comment]
That would be excellent. No rush.
