### ISSUE TITLE
Allow custom attributes in include preprocessor

### ISSUE THREAD

**Issue by krOoze** [asciidoctor/asciidoctor#3492]
Allow custom attributes in include preprocessor.
For example:
include.adoc:
```
Hello {your_name}!
```
include_test.adoc:
```
include::include.adoc[your_name=Ursula]

include::include.adoc[your_name=Bernhard]
```

Should result in:

>Hello Ursula!
>
>Hello Bernhard!

The attribute values would be scoped to the included file and the value outside not disturbed. Basically a pretty shorthand for:
```
ifdef::your_name[]
:your_name_backup: {your_name}
endif::[]
:your_name: Ursula
include::include.adoc[]
ifdef::your_name_backup[]
:your_name: {your_name_backup}
:!your_name_backup:
else::[]
:!your_name:
endif::[]
```

Would allow nice templating, without the ugly code above.

**Comment by marcdexet-cnrs** [comment]
This is a very interesting feature to my opinion.

**Comment by mojavelinux** [comment]
Custom attributes are permitted. But they are directive attributes, not document attributes. Therefore, they must be processed by a custom include processor. One of the things a custom include processor can do is translate them into document attribute entries. That is not something that's supported in the language itself and therefore will not be implemented by the built-in include processor.
