### ISSUE TITLE
"id assigned to block already in use" when parsing block content from extension

### ISSUE THREAD

**Issue by lo48576** [asciidoctor/asciidoctor#3499]
## Abstract

Parsing block content by `parse_content` from custom `BlockProcessor` warns that there are duplicate ID, when the block contains a child with ID.

## Environment
* Asciidoctor 2.0.10

## Input

`figure-block.rb`:

```ruby
require 'asciidoctor/extensions'
include Asciidoctor

# ```
# [figure]
# ====
# foo
#
# bar
# ====
# ```
class FigureBlock < Extensions::BlockProcessor
  use_dsl
  named :figure
  on_context [:paragraph, :open, :example]
  content_model :compound

  def process parent, reader, attrs
    doc = parent.document
    if !(doc.basebackend? 'html')
      raise "Unsupported backend #{doc.basebackend}"
    end

    wrapper = create_pass_block parent, nil, attrs, content_model: :compound
    parse_content wrapper, reader.lines

    html = %(<figure>
#{wrapper.render}
</figure>)
    create_pass_block parent, html, attrs, subs: nil
  end
end

Extensions.register do
  block FigureBlock
end
```

`test.adoc`:

```asciidoc
= Title

[#figure-id]
[figure]
====
foo

[#inner]
inner block.

====
```

terminal:

```
# `-a stylesheet!` is optional, it doesn't affect the warning.
$ asciidoctor --require ./figure-block.rb --backend xhtml5 -a stylesheet! test.adoc
asciidoctor: WARNING: test.adoc: line 9: id assigned to block already in use: inner
$
```

## Expected result

HTML with `<figure>`, with no warnings.

## Actual result

Generated HTML is what I expected, but there are extra warning `asciidoctor: WARNING: test.adoc: line 9: id assigned to block already in use: inner`.

* * *

I think this might be caused by `parse_content`, which seems to be checking ID duplicates.
(With `parse_content ...` line commented-out, no warnings are emitted.)

Is there a way to get the AST of the block?
If so, I should use it rather than parsing it manualy...

**Comment by Mogztter** [comment]
It might be due to the fact that you get a copy of the lines: 
https://github.com/asciidoctor/asciidoctor/blob/f4eaf65195e19caf99cabf386bd52fd2e2307977/lib/asciidoctor/reader.rb#L515-L520

Could you please try to use `read_lines` instead so the processor won't parse the lines again?
I'm just guessing here, it might not be related.

**Comment by lo48576** [comment]
Thank you, parsing `reader.read_lines` instead of `reader.lines` works as expected, without no warnings!
