### ISSUE TITLE
Unsetting table cell background color removes text

### ISSUE THREAD

**Issue by znerd** [asciidoctor/asciidoctor#3507]
**Steps to reproduce:**
1. Have a simple AsciiDoc file like this:
```
|===
| Cell 1
| Cell 2 {set:cellbgcolor:red}
| Cell 3 {set:cellbgcolor!}
| Cell 4
|===

```
2. Render the AsciiDoc using an HTML renderer, the PDF renderer, or the IntelliJ IDEA plugin.

**Expected results:**
1. Four rows are rendered.
2. First row shows one cell with contents: “Cell 1” with no particular background color.
3. Second row shows one cell with contents: “Cell 2” with a red background color.
4. Third row shows one cell with contents: “Cell 3” with no particular background color.
5. Fourth row shows one cell with contents: “Cell 4” with no particular background color.

**Actual results:**
1. OK: Four rows are rendered.
2. OK: First row shows one cell with contents: “Cell 1” with no particular background color.
3. OK: Second row shows one cell with contents: “Cell 2” with a red background color (except when using the PDF renderer, but that is a separate issue).
4. NOK: Third row shows one cell, with no particular background color, but **with no contents**.
5. OK: Fourth row shows one cell with contents: “Cell 4” with no particular background color.

Screenshot using the HTML renderer:
![Screen Shot 2019-12-13 at 17 40 57](https://user-images.githubusercontent.com/117866/70816449-ccd26e00-1dcf-11ea-8cc7-69965f489ebe.png)

Screenshot using the PDF renderer:
![Screen Shot 2019-12-13 at 17 42 14](https://user-images.githubusercontent.com/117866/70816504-ebd10000-1dcf-11ea-8abf-aa1e9d2048e9.png)

Screenshot using the IntelliJ IDEA plugin renderer:
![Screen Shot 2019-12-13 at 17 39 23](https://user-images.githubusercontent.com/117866/70816356-9f85c000-1dcf-11ea-9136-ce91d6c9009b.png)

**Comment by Mogztter** [comment]
I think it's the same issue as: https://github.com/asciidoctor/asciidoctor/issues/3425

**Comment by mojavelinux** [comment]
Correct. Unsetting an attribute using set clears the line. You either have to place it on a separate line or change the behavior by setting the `attribute-undefined` attribute to `drop`. See https://asciidoctor.org/docs/user-manual/#undefined-attribute.
