### ISSUE TITLE
Error running Asciidoctor with JRuby of RVM on command line (may be related to #3500)

### ISSUE THREAD

**Issue by uma-hh** [asciidoctor/asciidoctor#3509]
_Hi. This issue may be related to #3500 but the error message is different. I tried to run Asciidoctor with the jruby version that is available via rvm. Result:_

```
~ % asciidoctor -v         
NoMethodError: undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x40dd552c @replaced_methods={}>
    setup at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84
    check at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124
   <main> at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131
  require at org/jruby/RubyKernel.java:984
   (root) at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
  require at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:135
   <main> at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4
     each at org/jruby/RubyArray.java:1792
      run at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50
   <main> at /Users/uma/.rvm/gems/jruby-9.2.6.0/bin/jruby_executable_hooks:10
```

_The gem installation already yielded warnings:_

```
~ % gem install asciidoctor
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/Users/uma/.rvm/gems/jruby-9.2.6.0@global/gems/jruby-openssl-0.10.2-java/lib/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Fetching: asciidoctor-2.0.10.gem (100%)
Successfully installed asciidoctor-2.0.10
1 gem installed
```

_Environment (this is the jruby version rvm currently fetches):_

```
~ % rvm use jruby          
Using /Users/uma/.rvm/gems/jruby-9.2.6.0
```

```
~ % java -version
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

_All this is on a Mac with current OS._

_I also looked for AsciidoctorJ but there is no gem for this. My unterstanding is that you use  AsciidoctorJ if you want to use Asciidoctor with in a Java program you write but not for running it from the CL. Correct?_

_Thanks & Best, Ulf_

**Comment by Mogztter** [comment]
Hello Ulf

Could you please edit the issue to add fenced blocks around console output so it's easier to read.
For instance:

\```console
~ % asciidoctor -v
NoMethodError: undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x40dd552c @replaced_methods={}>
setup at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84
check at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124
at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131 require at org/jruby/RubyKernel.java:984 (root) at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1 require at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:135 at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4 each at org/jruby/RubyArray.java:1792 run at /Users/uma/.rvm/rubies/jruby-9.2.6.0/lib/ruby/gems/shared/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50 at /Users/uma/.rvm/gems/jruby-9.2.6.0/bin/jruby_executable_hooks:10
\```

Thanks

**Comment by mojavelinux** [comment]
> I also looked for AsciidoctorJ but there is no gem for this. My unterstanding is that you use AsciidoctorJ if you want to use Asciidoctor with in a Java program you write but not for running it from the CL. 

You are correct. There is no gem. It's a jar. AsciidoctorJ also provides a CLI. You can install it either by downloading the distribution zip or using sdkman.

**Comment by uma-hh** [comment]
I have fixed the code typography. Sorry for the inconvenience!
I should say that I have stopped playing with Asciidoctor shortly after. I am now back to Pandoc and enjoy its configurability with Lua.

**Comment by mojavelinux** [comment]
Since you don't seem to have interest in helping this project, and instead use the opportunity to take a veiled shot at our work, I'm closing this issue.
