### ISSUE TITLE
Passthrough text not reinserted when using an inline macro on monospaced text

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor#3511]
I'm using the following inline macro to do syntax highlighting:

```rb
class MonospacedTextHighlightingInlineMacro < Extensions::InlineMacroProcessor; use_dsl
  named :monospaced_text_highlighter
  match %r/<code class="src-([a-z]+)">([^<]+)<\/code>/i
  positional_attributes :content

  def process(parent, target, attrs)
    raw_text = attrs[:content]
    highlighted_text = Highlighter.highlight(target, raw_text, parent.document)
    (create_block parent, 'pass', %(<code class="rouge">#{highlighted_text}</code>), attrs).convert
  end
end
```

The above extension is working as expected when using the following definition:

```
[src-cypher]`MATCH (c:Customer {customerName: 'ABCCO'}) RETURN c.BOUGHT.productName`
```

But If I want to use a passthrough to avoid replacements substitution then the content is `\u00960\u\u0097`.

```
[src-cypher]`+MATCH (p:Product)<-[:BOUGHT_BY]-(:Customer 'ABCCO') RETURN p.productName+`
```

I believe that the content is not yet reinserted when the extension is executed:

https://github.com/asciidoctor/asciidoctor/blob/fb3c647c5e306c520f87e90ff0ad3d8d80a0123a/lib/asciidoctor/substitutors.rb#L1006

https://github.com/asciidoctor/asciidoctor/blob/fb3c647c5e306c520f87e90ff0ad3d8d80a0123a/lib/asciidoctor/substitutors.rb#L1130

I'm pretty sure this issue will be resolved when we have a proper inline parser but in the meantime what's the best approach?
For now I just avoid to use passthrough and revert the replacements manually:

```rb
raw_text = raw_text.gsub('&#8594;', '->') if raw_text.include? '&'
raw_text = raw_text.gsub('&#8592;', '<-') if raw_text.include? '&'
```

**Comment by mojavelinux** [comment]
This is true of all inline macros and we don't really have a great solution for it. The only reasonable approach is to do what Asciidoctor does internally, which is to call `restore_passthroughs` on the text.

```rb
raw_text = parent.restore_passthroughs attrs[:content]
```

It's safe to call that method as many times as you want for a given parent since the placeholders are indexed.

Here's how that would look in context:

```rb
class MonospacedTextHighlightingInlineMacro < Asciidoctor::Extensions::InlineMacroProcessor
  use_dsl
  named :code_source_tag
  match %r/<code class="src-([a-z]+)">([^<]+)<\/code>/i
  positional_attributes :content

  def process parent, target, attrs
    raw_text = parent.restore_passthroughs attrs[:content]
    highlighted_text = Highlighter.highlight target, raw_text, parent.document
    create_inline_pass parent, %(<code class="rouge">#{raw_text}</code>)
  end
end
```

Notice I create an inline pass, not a pass block in return.
