### ISSUE TITLE
table not using the full size of the browser

### ISSUE THREAD

**Issue by itsme-narahari** [asciidoctor/asciidoctor#3512]
Hello Friends:

Thank you in advance for your time and attention.
If I am doing something wrong please forgive me.

Here is the code I copied from asciidoctor user guide manual.
`
![ascii_issue](https://user-images.githubusercontent.com/310790/71287740-29390e80-2337-11ea-9b56-789825960c68.jpg)
![ascii_issue](https://user-images.githubusercontent.com/310790/71287762-33f3a380-2337-11ea-8666-c36e4ebeead9.jpg)
[%autowidth.stretch]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===
`

When I type asciidoctor -b html5 adoc_tester.doc, it produces adoc_tester.html.

However the output on the browser is not using up the full screen.
Please see [here.](https://imgur.com/gallery/l9n6T9v)

Have I not understood how it is supposed to work ?
What mistake am I doing ?

Please advise.

**Comment by john-cj** [comment]
The table takes the width of the `#content` element. And it's width is `max-width: 1000px;` (actually, it's 62.5%, but it recalculates to 1000 pixels).

Actually, you don't need `[%autowidth.stretch]` here, it is much easier:

```
|===
| aaa | bbb
|===
```

```
asciidoctor test.adoc
```

Type a long line of text outside of table and see that it have the same width as the table itslef. That is, 1000 pixels.

I'm just a user, not an Asciidoctor developer and therefore I'm free to not be too polite: learn Markdown and use it properly, always. It's a basic thing of etiquette.

**Comment by mojavelinux** [comment]
@john-cj is exactly right. The default stylesheet limits with width of the content by default for readability (62.5em).

You can supply your own CSS overrides using docinfo to modify the width without modifying the document.

There is a `max-width` document attribute that is supposed to influence this value, but it turns out it doesn't work. I'll look into solving that.

**Comment by itsme-narahari** [comment]
Thank you both for your time and help.  Much appreciated.

> I'm just a user, not an Asciidoctor developer and this is why I'm free to not be too polite: learn Markdown (its about 5 minutes) and use it properly, always. It's a basic thing of etiquette.

Will look into this.

-N
