### ISSUE TITLE
Inline anchor and block ID for block element

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3516]
I'm working on my personal AsciiDoc style guide, currently a draft, and one of its rules sounds as

> To style, use `[#block-id]`. To reference, use `[[inline-anchor]]`.

However, I found one case that looks impossible:

```
++++
<style>
#foo {color: red;}
</style>
++++

See <<notice, reftext>>.

[[notice]]
[#foo]
* li
* li
* li
```

Is there some way to make them work together?

**Comment by mojavelinux** [comment]
I think you're getting the concepts mixed up. What you're looking for is an ID / anchor for referencing and a role / CSS class for styling.

```
++++
<style>
.foo {color: red}
</style>
++++

See <<notice,reftext>>.

[#notice.foo]
* li
* li
* li
```

You could also choose to forgo the role and style the notice ID directly:

```
++++
<style>
#notice {color: red}
</style>
++++

See <<notice,reftext>>.

[#notice]
* li
* li
* li
```

FYI: `[#notice]` and `[[notice]]` are the same thing. Just different was to express it.

**Comment by john-cj** [comment]
Not exactly. What I'm looking for is simple rule about

* a) where to use inline anchors?
* and b) where to use block anchors?

The first attempt, which is posted above, seems do doesn't work well in real life.

Another possible variations:

**2nd**

> * Use `#` syntax when you need
>   * a) to style an element;
>   * b) to reference it and to style it at the same time.
> * Use `[[]]` syntax when you only need to reference it.

(And there is an exception when we need a reference for a single or multiple words inside the middle of the sentence. `[[]]` syntax will not work.

And there is another exception when we need multiple anchors for single element.)

A disadvantage of this approach is that it is not easy to remember.

**3rd**

> Don't use `[[]]` syntax. Use `#` syntax instead.

The disadvantage of this approach is that it clutters the markup without necessity.

```
* aaa aaa aaa
* [#step2]#bbb ##highlighted## bbb#
* ccc ccc ccc
```

**Comment by mojavelinux** [comment]
> where to use inline anchors?

on inline elements, like a word.

> where to use block anchors?

on block elements like a list or paragraph

> Use [[]] syntax when you only need to reference it.

The `[[]]` syntax is a legacy syntax, nothing more.

The legacy syntax is still useful in one case. When the anchor is not otherwise attached to any element. For example:

```
* [[step2]]bbb #highlighted# bbb
```

Thus, it's not useless. It's just recommended only for that case. Use the `[#id]` syntax if you can.

> The first attempt, which is posted above, seems to doesn't work well in real life.

Please explain.

**Comment by john-cj** [comment]
> Please explain.

I wrongly assumed that I can use `[[]]` syntax for referencing and `#` syntax for styling (as a supplement to roles). I.e., to use each syntax for a different purpose.

This idea is actually bad because `[[]]` and `#` syntaxes can't be used for a single block element.

```
// Works

++++
<style>
.important { color: orange; }
#most-important { color: red; }
</style>
++++

[[ref-notice]]
[#most-important]#This is the most important paragraph in the whole document.#
```

```
// Works

++++
<style>
.important { color: orange; }
#most-important { color: red; }
</style>
++++

* list item
* [[ref-step2]][#most-important]#This is the most important list item in the whole document.#
* list item
```

```
// Doesn't work

[[notice]]
[#most-important]
* li
* li
* li
```

> The `[[]]` syntax is a legacy syntax, nothing more.

Oh, that makes things a lot clearer.

> * Inline anchors - use on inline elements, like a word.
> * Block anchors - use on block elements, like a list or paragraph.

It seems we understand each other, but there is a subtle difference in our terminology that I would to spot out.

* What I initially called "inline anchors" is the anchors with `[[]]` syntax.
* What I initially called "block anchors" is the anchors with `#` syntax.

You say to use inline anchors for inline elements; but we can't use `[[]]` syntax for inline elements.

It leads me to the following rephrasing, which sounds really weird to me:

> * Block anchors (with a newline) - use on block elements, like a list or paragraph.
> * Inline anchors - use on list items. (Despite they are much closer to the block elements then to the inline ones.)
> * Block anchors (without a newline) - use on inline elements, like a word.

```
// This is a block anchor used for a block element
[#most-important]
* li
* [[step2]]This is an inline anchor used for a list item.
* li [#special-word]#foo#. This is a block anchor used for an inline element.
```

It leads me the point that "inline anchor" and "block anchor" names aren't very precise.

**Comment by mojavelinux** [comment]
> I wrongly assumed that I can use `[[]]` syntax for referencing and `#` syntax for styling (as a supplement to roles).

As you now understand, it's just two different ways of expressing the same thing. An element can only have one ID, so you have to pick which way you want to express it. (Keep in mind an element can have an unlimited number of roles).

Roles are better suited for styling. So I still argue that what you want is something like:

```
[#ref-notice.most-important]
This is the most important paragraph in the whole document.
```

(If the CSS isn't being applied, it means that it doesn't have high enough precedence. In other words, some other style is winning out. Just make it more specific or use the `!important` modifier to for it).

```
<style>
.most-important * { color: red !important; }
</style>
```

> `#` syntax works as block anchor when it is located on a separate line. When it is located on the same line, it works as an inline anchor.

This is almost correct, but you're explaining it by describing the secondary trait. When an attribute line is placed above a block, those attributes are block attributes (and thus a block anchor). When attributes are placed before an inline phrase, those attributes are inline attributes (and thus an inline anchor). So it's not just about what line they are on. It's about what you are applying them to.

Your examples are correct.

> The name "inline anchor" for `[[]]` anchors could be misleading for some people

We're not saying `[[]]` is an inline anchor. It depends on the context. Sometimes it's a block anchor, sometimes its an inline anchor. The syntax doesn't determine what it is. It's where it is placed that matters.

> But at the same time, they are "block" in that sense that they affects the block elements.

The only case where this is true is a list item. That's a known shortcoming in the AsciiDoc syntax that we plan to address. The hoisting of the inline anchor to a block anchor is a stopgap solution until it can be solved properly. See https://github.com/asciidoctor/asciidoctor/issues/2716.
