### ISSUE TITLE
Admonitions inside multilevel lists: to easily detect the level

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3523]
When the admonition block is located inside (or before, after) the multilevel list, it is hard to say at which exact level it is located.

Here, for example, the caution is located outside the list, despite it looks as a part of the first level:

```
* list item
** list item

[CAUTION]
====
caution
====
```

![list](https://user-images.githubusercontent.com/18004961/71544860-240e3c00-2995-11ea-9b83-e58cfe4347d1.png)

A possible fix:

![list2](https://user-images.githubusercontent.com/18004961/71545015-1ce82d80-2997-11ea-80c8-6b44a90b908c.png)

**Comment by mojavelinux** [comment]
This is just the way it is. If you want different styling, you can use your own stylesheet.
