### ISSUE TITLE
Hyperlinks: to replace "underline" with "border-bottom"

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3524]
I have an idea to change the way the hyperlinks are underlined: from `text-decoration: underline` to `border-bottom: 1px solid`. It will make underscored hyperlinks easier to read.

![firefox](https://user-images.githubusercontent.com/18004961/71547717-af4afa00-29b4-11ea-9fd6-5214dd3e289c.png)

It isn't very good from the semantic point of view, though. "Underline" is something typography-related, like "italic" or "bold": "hey, look here! this text has special meaning!". "Border" is something more abstract, more general-purpose. It doesn't has strict semantic connotation.

**Comment by mojavelinux** [comment]
You are free to add this to your own stylesheet. I do not want to do anything non-standard like this in the default stylesheet.
