### ISSUE TITLE
Can't put a name with underscore in author attribute

### ISSUE THREAD

**Issue by billop** [asciidoctor/asciidoctor#3528]
Things I've tried and that don't work:
```asciidoc
:author: "d_"
```
```asciidoc
:author: d\_
```
```asciidoc
:author: pass:m[d_]
```

The only thing that works so far is:
```asciidoc
Title
"d_"
```
but the quotes become included in the output.

Why doesn't the author attribute accept arbitrary text?

**Comment by mojavelinux** [comment]
It's not possible to use a literal underscore in the implicit author line. Underscore is a reserved character that represents a space. The implicit author line is a shorthand designed to support to the most common cases. For complex name requirements, use the explicit `author` attribute entry instead.

```
= Document Title
:author: d_a
```

**Comment by billop** [comment]
That doesn't work. So I'm assuming it is impossible for asciidoctor. Not that I mind that much but I was hoping I was missing something.

**Comment by mojavelinux** [comment]
You are correct. I misspoke. The underscore is interpreted regardless of how author is defined. It's a very strong reserved character. You need to express the underscore using a character reference:

```
= Document Title
D&#95;A

[%hardbreaks]
{author} +
{firstname}
```

or

```
:author: D&#95;A
```

**Comment by billop** [comment]
That's exactly what I was trying to find. Thanks.
