### ISSUE TITLE
Unsetting Boolean Attributes Via Document Header - Possible?

### ISSUE THREAD

**Issue by AXGKl** [asciidoctor/asciidoctor#3531]
I can overwrite any attribute with a value given on the CLI via a document header value, when I append '@' to the value on the CLI.   
Example: `-a icontype=png@` is overwritten by `:icontype: svg` in the doc header. Good.

Problem: *Boolean* attributes.  
How would I UNSET a **boolean** attribute given on the CLI, like `-a data-uri`.   
Use Case: My .adoc renderer by default sets `-a data-uri`, but I would like to switch it off *sometimes* via a document header attribute.

Is that possible?

**Comment by Mogztter** [comment]
I think you need to use `:data-uri!:` (notice the explanation mark): https://asciidoctor.org/docs/user-manual/#using-attributes-set-assign-and-reference

**Comment by AXGKl** [comment]
@Mogztter 
Confirmed & sorry for the noise!
So:

CLI: `-a data-uri=@`  sets the boolean, IF not unset in the doc header  
Doc Header: `:data-uri!:`  unsets it.

Nice!

**Comment by Mogztter** [comment]
I'm glad it's working for you :+1: 
If you have other questions, feel free to ask on Gitter: gitter.im/asciidoctor/asciidoctor

**Comment by AXGKl** [comment]
Merci bien for the invite, will bug you there for the next one :-)  
But for the evening I'm well entertained with your blog anyway, many thanks also for that!
