### ISSUE TITLE
Nested horizontal description list capturing more content than it should

### ISSUE THREAD

**Issue by PHLAK** [asciidoctor/asciidoctor#3535]
When creating a `horizontal` description list with the last term containing a nested `horizontal` description list it captures content even after multiple new lines.

Given this markup

```asciidoc
[horizontal]
Term 1:: Some definition...
Term 2:: Some definition...
+
[horizontal]
Term 3::: Some definition...

A separate paragraph of text.
```

You get this output

![image](https://user-images.githubusercontent.com/53531/72182583-04b9da80-33a9-11ea-9d05-c36108e36f0d.png)

Note how the last paragraph is being captured as part of the description list.

**Comment by mojavelinux** [comment]
You're correct that it is capturing more lines than it should. However, the list continuation is redundant in this case and removing it happens to solve the issue. I'll look into how to get it to behave correctly in either case.

**Comment by mojavelinux** [comment]
Found it. It was a regression that was not covered by a test that was caused by changing `=~` to `.match?`
