### ISSUE TITLE
The letter "A" in front of the single appendix

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3540]
Markup:

```
= Abc
:toc:

== Aaa

== Bbb

[appendix]
== Ccc
```

Output TOC:

```
Aaa
Bbb
Appendix A: Ccc
```

Since `sectnums` option isn't enabled and there is only one appendix, the letter "A" looks excessive. Instead, it should be

```
Aaa
Bbb
Appendix: Ccc
```

**Comment by mojavelinux** [comment]
If you don't want the number to be displayed, you can override the converter (either by extending it or with templates).

**Comment by john-cj** [comment]
What's your opinion about this behavior? As I understand, you agree that ideally it should be somehow changed in the default converter?

**Comment by mojavelinux** [comment]
I think some people will want it, and they can have it. But it goes against the default behavior of other standard platforms like DocBook. Our goal is to produce output that follow the same well-accepted rules. And that is to number the appendix even if there's only one.

**Comment by mojavelinux** [comment]
I was able to confirm that both dblatex and fop in the DocBook toolchain include the number of the single appendix. So the default behavior in Asciidoctor is consistent with "industry standards". But I do want you to feel free to be able to customize the behavior if it suits you. If you have any trouble doing that, please mention it.
