### ISSUE TITLE
inter-document xref links do not work after asciidoctor 1.5.6.2

### ISSUE THREAD

**Issue by aollier** [asciidoctor/asciidoctor#3541]
Hello,

In the repositories [progit2](https://github.com/progit/progit2), [progit2-fr](https://github.com/progit/progit2-fr) and friends, we are using asciidoctor version 1.5.6.2 (previously 1.5.6.1) to build the tutorial for git (called **progit**) available on the [Git](https://git-scm.com) website, documentation section.

Starting from version 1.5.7, xref links do not work on any format: HTML, epub, mobi nor PDF.
This looks like to be a regression. We use links like &lt;chapter&gt;&num;&lt;section&gt;, which works perfectly until now on every format.

**Comment by mojavelinux** [comment]
I'm going to update the CHANGELOG for 1.5.7 to make sure this change is clearly stated. Here's the origin PR. https://github.com/asciidoctor/asciidoctor/commit/4d1b60e8f314e37245aad67ca48924845deafe78 (Note that in a later commit, support for the extensionless xref with hash was restored).

**Comment by aollier** [comment]
In addition to the changes I told you, I changed the title of Progit by removing the two-lines:
```diff
diff --git a/progit.adoc b/progit.adoc
index f2e0ca0..6c05550 100644
--- a/progit.adoc
+++ b/progit.adoc
@@ -1,5 +1,4 @@
-Pro Git
-=======
+= Pro Git
 Scott Chacon; Ben Straub
 :doctype: book
 :docinfo:
```

Now I can build the book in format EPub et Mobi using asciidoctor version 1.5.8. Great! :smiley: 

But this does not work for asciidoctor 2.0.10. I suppose that some other changes are required?

Regards,
Adrien Ollier

**Comment by mojavelinux** [comment]
I don't see any reason why it wouldn't work in Asciidoctor 2 since the breaking xref change (in your case) actually came in 1.5.7. However, I didn't get a chance to test Asciidoctor 2 on the book.

**Comment by mojavelinux** [comment]
Aha! That looks like an incompatibility between Asciidoctor EPUB3 and Asciidoctor 2. It must be the same as this issue: https://github.com/asciidoctor/asciidoctor-epub3/issues/210 Since that's covered by an issue already, I'm going to close this one and we can focus our attention there.

> In addition to the changes I told you

As it turns out, the only change you need to make for the references is to update the doctitle format. And we also need to address the bug in Asciidoctor EPUB3.
