### ISSUE TITLE
stack level too deep on infinite header xref recursion

### ISSUE THREAD

**Issue by cirosantilli** [asciidoctor/asciidoctor#3543]
```
= asdf

[[h2]]
== h2 xref:h3[]

[[h3]]
=== h3 xref:h2[]
```

then at asciidoctor 20.10:

```
asciidoctor main.adoc
```

fails with:

```
stack level too deep
  Use --trace for backtrace
```

On GitHub: https://github.com/isaacs/github/issues/1718

**Comment by mojavelinux** [comment]
Here's the simplest case:

```asciidoc
[#a]
== A xref:b[]

[#b]
== B xref:a[]
```

**Comment by mojavelinux** [comment]
I think the logic should be changed such that if the xreftext itself contains an xref, the conversion should stop and use the fallback text instead (i.e., the target ID enclosed in square brackets), which effectively disabling the automatic xreftext. If the xreftext still contains an HTML anchor of any sort (which it might), the fallback text is also used.

Putting an xref inside of an xref doesn't make sense, so we can short-circuit eagerly if this happens, and thus avoid the risk of any recursion.

For the example I cited, the output would be as follows:

```html
<div class="sect1">
<h2 id="a">A <a href="#b">[b]</a></h2>
<div class="sectionbody">

</div>
</div>
<div class="sect1">
<h2 id="b">B <a href="#a">[a]</a></h2>
<div class="sectionbody">

</div>
</div>
```
