### ISSUE TITLE
gt entity may be badly formed

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor#3548]
example file:

```
= Test

Every project on GitHub is accessible over HTTPS as `https://github.com/<user>/<project_name>`, and over SSH as `git@github.com:<user>/<project_name>`.
```

is rendered in html as :

```
<div class="paragraph">
<p>Every project on GitHub is accessible over HTTPS as <code><a href="https://github.com/&lt;user&gt;/&lt;project_name&gt" class="bare">https://github.com/&lt;user&gt;/&lt;project_name&gt</a>;</code>, and over SSH as <code>git@github.com:&lt;user&gt;/&lt;project_name&gt;</code>.</p>
</div>
```

Note the missing ; in https urls.

**Comment by mojavelinux** [comment]
I think you are missing the fact that the purpose of the backticks changed in Asciidoctor 1.5 (not compat mode). Backticks are for monospace only. So you have to think about what would happen if the backticks weren't there. That's how it will be parsed.

What you probably mean to enter (or need to enter) is:

```
`+https://github.com/<user>/<project_name>+`
```

That combines monospace and literal formatting. See https://asciidoctor.org/docs/migration/#migration-scenarios

**Comment by jnavila** [comment]
This one is different: the `gt` entity is not correctly rendered in 
<a href="https://github.com/&lt;user&gt;/&lt;project_name&gt" <--- here

**Comment by mojavelinux** [comment]
But that's not a valid URL anyway. Why do you want it to be a URL? So my suggestion is correct. You want it to be shown literally.

Another way to express it is to escape the URL:

```
`\https://github.com/<user>/<project_name>`
```

**Comment by jnavila** [comment]
I don't want it as a real URL, it wasn't in compat mode. Escaping the pseudo-URL works. Another regex in the conversion script, then :gear: .

**Comment by mojavelinux** [comment]
Excellent.
