### ISSUE TITLE
Combine table column alignment and width not working

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor#3549]
I have a table with 3 columns and I want to change the column width and make the 2nd column centered.

I thought that this should work but it does not:

```
[cols="10<,20^,70<"]
|===
|Header 1 |Header 2 | Header 3

|Column 1, row 1
|Column 2, row 1
|Column 3, row 1

|Column 1, row 2
|Column 2, row 2
|Column 3, row 2
|===
```

It behaves as if nothing is specified at all. The widths are not taken into account, and the alignment is also not taken into account.

If I only specify `[cols="10,20,70"]`, then I get the proper widths. If I only specify `[cols="<,^,<"]`, then I get the proper centering of the content in the second column, but not the proper widths.

This was tested with Asciidoctor 2.0.10. Both the PDF and the HTML output show consistent behaviour on this.

**Comment by robertpanzer** [comment]
Hi Wim,
according to https://asciidoctor.org/docs/user-manual/#cols-format the alignment has to come after the width specification: https://asciidoctor.org/docs/user-manual/#cols-format
Therefore this works for me:
```asciidoc
[cols="<10,^20,<70"]
|===
|Header 1 |Header 2 | Header 3

|Column 1, row 1
|Column 2, row 1
|Column 3, row 1

|Column 1, row 2
|Column 2, row 2
|Column 3, row 2
|===
```

**Comment by robertpanzer** [comment]
It's not stated that explicitly there, but it's the order of the options in the list :)

**Comment by wimdeblauwe** [comment]
Thanks! Maybe the docs could be more clear on the required order?

(You have a typo in your comment, you state "alignment after width", but your example shows correctly that alignment has to come before width)

**Comment by mojavelinux** [comment]
The docs state:

> A style operator is always placed in the last position on a column’s specifier or multiplier.

If you feel that needs to be clearer, please click "Edit this Page" and propose a revision.

**Comment by elextr** [comment]
Everybody, the OPs problem is not with style its with alignment, so the @robertpanzer example is right, but references the wrong manual page.

[This page](https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-column/) is about alignment and is clear " and in front of a column’s width (if present)".
