### ISSUE TITLE
[Question] How to add id or class name to table row or cell?

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor#3553]
Hello all!

How can I add id or class name for table cell (`<td>`) or row (`<tr>`)?

I can't find this id Asciidoctor manual.

**Comment by Mogztter** [comment]
Hello @sindzicat 

Not sure about id but if you want to add roles to cells or columns, then there's already an open issue: https://github.com/asciidoctor/asciidoctor/issues/1338

**Comment by mojavelinux** [comment]
The ID would fall under #1338 too. So I'm going to mark as a duplicate. Let's continue the discussion there.
