### ISSUE TITLE
Ruby API documentation missing in 2.0.10 release

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor#3554]
The Ruby API documentation at <https://www.rubydoc.info/gems/asciidoctor/2.0.10> contains only the README; the entire API documentation is missing. This apparently was broken recently because the full documentation does exist at <https://www.rubydoc.info/gems/asciidoctor/2.0.9>.

**Comment by mojavelinux** [comment]
We are aware of this. The API docs were not generated correctly by the rubydoc.info server and the owners refuse to fix the cache. So it will be fixed when 2.0.11 is released, but not sooner.

**Comment by owenh000** [comment]
>So it will be fixed when 2.0.11 is released

Okay. Thanks for the explanation!

**Comment by mojavelinux** [comment]
The API docs are working again. See https://www.rubydoc.info/gems/asciidoctor/
