### ISSUE TITLE
I should be able to get a date input in ISO format displayed in some configurable format to the reader

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor#3558]
When writing a document with lots of dates, it would be nice to be able to input these dates in ISO format, independently of the way they are to be seen by the reader.

When converted, all these dates should be visible in a different format, configured by the author.

The author would be able to specify the output format using attributes: short form, long form, fixed format (DDD-MM-YYYY), … The output would display the date in a format localized to the language of the document, by default.

**Comment by Mogztter** [comment]
Hello Olivier,

What you are describing is a good candidate for an extension.
Here's an example:

```adoc
:date-format: dd/MM/yyyy
:lang: en

The Normandy landings were the landing operations on date:1944-06-06[] of the Allied invasion of Normandy in Operation Overlord during World War II.

On date:1944-07-09[format="d MMMM yyyy"], Field Marshal Bernard Montgomery demanded a massive air assault against Caen in hopes of clearing the way for an attack the following morning.
```

```html
<p>The Normandy landings were the landing operations on 06/06/1944 of the Allied invasion of Normandy in Operation Overlord during World War II.</p>

<p>On 9 July 1944, Field Marshal Bernard Montgomery demanded a massive air assault against Caen in hopes of clearing the way for an attack the following morning.</p>
```

Please note that date formater highly depends on the underlying programming language.
In the above example I'm using a inline macro extension name `date`. I would recommend to have a look at the [asciidoctor-extensions-lab repository](https://github.com/asciidoctor/asciidoctor-extensions-lab) and in particular, the [`tel` inline macro](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/tel-inline-macro.rb).
