### ISSUE TITLE
Idea: Asciidoctor for scientific writing

### ISSUE THREAD

**Issue by Nadano** [asciidoctor/asciidoctor#3579]
More and more of the scientific community is using tools like GIT or even publishing their research in github under the frame of open science. Unfortunately, given that there are not many alternatives markdown or r-markdown are becoming the de facto standard, using pandoc, knitr::kable and similar shortcuts to circumvent markdown's weaknesses.
I believe that just a few changes and additions to asciidoctor would make it a better suited language, but without a clear focus in this field it will never take momentum. Is it a priority of the working group?

Some ideas:

- merging ascidoctor-latex into the main project.
- bibtex-citations in the main project, not as an extension, or at least being able to put citations in a different file
- inline comments/notes - useful to review information in tables
- better vscode support, which everyone is using nowadays 
    - Avanced table support like in https://github.com/qjebbs/vscode-markdown-extended
    - A citation helper like in https://github.com/notZaki/PandocCiter

**Comment by mojavelinux** [comment]
> merging ascidoctor-latex into the main project.

We're not going to do that. For one, that project is not being kept up to date. But it also adds entirely too much complexity to core. If it is going to continue, it should be an add-on converter. To simplify installation, it could be included in the Docker/OCI container...but in order for that to happen, it needs to be more stable.

> bibtex-citations in the main project, not as an extension, or at least being able to put citations in a different file

It's going to remain as an extension, similar to reasons stated above. However, there's no reason it can't be a good extension.

> inline comments/notes - useful to review information in tables

It's already possible to create line and block comments. That's the extent to which AsciiDoc is going to support comments. If you need something that gets passed through to the output, you can write a custom inline macro.

> better vscode support, which everyone is using nowadays 

This is happening. The VS Code extension is under active development. The plugin for IntelliJ is also incredibly good.

If you want to share other ideas for where to take this community, or advocate for such ideas, you can do so in the project chat at https://chat.asciidoctor.org.
