### ISSUE TITLE
Escape url to prevent autolinking behavior on GitHub

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor#3585]
Asciidoctor User Manual [says](https://asciidoctor.org/docs/user-manual/#url): “To prevent automatic linking of an URL, prepend it with a backslash (\).”

Doing this on GitHub fails to prevent it from turning the URL into a hyperlink. See example [here](https://github.com/oliviercailloux/testrel/blob/master/test.adoc).

Please consider documenting a workaround or contacting GitHub to ask for an update of Asciidoctor, if that’s the problem and assuming someone knows how to do that…

**Comment by mojavelinux** [comment]
This behavior actually has nothing to do with the AsciiDoc processor and I'm not sure how to work around it. GitHub postprocesses the HTML that Asciidoctor produces. It's there that bare URLs get turned into links. So you'll need to take this issue up with GitHub. See https://github.com/github/markup

**Comment by oliviercailloux** [comment]
[Seems like](https://github.com/github/markup/issues/1218#issuecomment-422215462) the referenced library “doesn't directly handle AsciiDoc rendering”; we’re told to “reach out to [the support team](https://github.com/contact) directly”. Which I’ll do (with no great hope).

**Comment by mojavelinux** [comment]
I know it can be frustrating. But it's outside of our control. Those are the rules of this platform. We can only ask.

**Comment by oliviercailloux** [comment]
No worries, that’s understood.
