### ISSUE TITLE
Using a boolean value for the copycss attribute (from the API) throws an exception

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3592]
Consider the following code:

```rb
Asciidoctor.convert_file 'sample.adoc', safe: :safe, standalone: true, attributes: {'stylesheet' => 'stylesheets/custom.css', 'copycss' => true, 'linkcss' => ''}
```

When running, it throws:
```console
NoMethodError: undefined method `empty?' for true:TrueClass
    /path/to/asciidoctor/lib/asciidoctor/convert.rb:150:in `convert'
    /path/to/asciidoctor/lib/asciidoctor/convert.rb:183:in `block in convert_file'
    /path/to/asciidoctor/lib/asciidoctor/convert.rb:183:in `open'
    /path/to/asciidoctor/lib/asciidoctor/convert.rb:183:in `convert_file'
    /path/to/asciidoctor/test/document_test.rb:197:in `block (3 levels) in <top (required)>'
```

Is that an invalid usage? In other words, an attribute value must be a string or should we allow it?

```rb
{'copycss' => true} # is equivalent to 'copycss' => ''
{'copycss' => false} # is equivalent to 'copycss!' => ''
```

**Comment by mojavelinux** [comment]
Asciidoctor assumes that a truthy value is an empty string. However, there are some integrations where this is inconvenient, and the value may come in as a boolean. Since we're treating the value as a string in that case, the processor should make a distinction between these two value types.

**Comment by mojavelinux** [comment]
> {'copycss' => false}

FYI, the processor will never see the attribute in this case since the Document constructor removes the attribute from the map of document attributes.
