### ISSUE TITLE
Error during rendering Doc.adoc  : Failed to load AsciiDoc document - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by mmouatta** [asciidoctor/asciidoctor#3595]
When trying to render the .adoc file to a pdf or html format I get : "Error during rendering Doc.adoc  : Failed to load AsciiDoc document - invalid byte sequence in UTF-8", the file contains some Latin characters such as 'é', 'ç', 'è' .

**Comment by abelsromero** [comment]
Asciidoctor only support UTF-8 encoding. You get that error if the sources are not in that encoding.

Could you doble check the encoding of the file is actually UTF-8? I recall that on Windows by default it uses some local enconding.
For example vscode shows it in the lower-right corner.
![image](https://user-images.githubusercontent.com/5781153/76632656-d345c280-6543-11ea-965b-f171705fa946.png)

**Comment by mmouatta** [comment]
> Asciidoctor only support UTF-8 encoding. You get that error if the sources are not in that encoding.
> 
> Could you doble check the encoding of the file is actually UTF-8? I recall that on Windows by default it uses some local enconding.
> For example vscode shows it in the lower-right corner.
> ![image](https://user-images.githubusercontent.com/5781153/76632656-d345c280-6543-11ea-965b-f171705fa946.png)

It worked Thank You :)
