### ISSUE TITLE
Why not use mathjax to render math fomulas as svg?

### ISSUE THREAD

**Issue by Googolplex-C** [asciidoctor/asciidoctor#3599]
Hi, I am new to AsciiDoc, and it looks really great for academic writing.

But here' s a problem:
For me, math content is of great importance, and I have to write a lot of formulas in my docs.
1. I noticed that AsciiDoc use mathjax to render math, but the HTML files I generate could be put on both local OS and online. 
2. Also, asciidoc-mathematical, based on mathematical, is not as powerful as mathjax in formula handling -- as far as I know at least.

So why not just use mathjax to render math to svg directly?? I sincerely hope for response and know the reason.

(I am not English native speaker, so perhaps my words sound a little bit ... But I meant NO offense, Thank you)

**Comment by mojavelinux** [comment]
Because at the time we integrated MathJax, it didn't have this capability.

The Asciidoctor processor is also optimized for speed, so we defer anything we can to the browser by default. It's possible to extend the converter and handle the stem and inline_stem handlers to call out to MathJax to produce an SVG. It would make a nice extension.

**Comment by Googolplex-C** [comment]
How can I extend the converter to let mathjad render STEM content to svg?
I've searched this repository and find an issue about customizing converter by modifying template,
about which I know little. 
So may I get more tips and help?

Appreciate it really.

**Comment by sorpaas** [comment]
I'm actually looking for this feature as well. A way possible without going through the asciidoctor release support would be to write a inline macro extension, somehow invoke the mathjax's new offline rendering functionality, and then put the result svg directly in docs. Only obstacle is calling mathjax -- I haven't found a good library that allows me to do this in Ruby.

**Comment by mojavelinux** [comment]
If you need help implementing this extension, please ask in the `#users` stream of the community chat at https://asciidoctor.zulipchat.com. The issue tracker is reserved for bug reports and feature requests that have been accepted.
