### ISSUE TITLE
:menu: doesn't render correctly in html5 

### ISSUE THREAD

**Issue by Alberth289346** [asciidoctor/asciidoctor#3600]
``` adoc
:experimental:
:book:

menu-bug
========

Menu item is not rendered correctly in html.

The
menu:First entry[]
and the
menu:second entry[]
must be selected.
```
yields
![Screenshot_20200316_114450](https://user-images.githubusercontent.com/3254232/76748749-97953d80-677b-11ea-9dcc-e3e8c90c4a1f.png)

EDIT: These are not buttons!.

Version numbers:
```
OS: Fedora 30

$ gem -v
3.0.3

$  asciidoctor -v
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

$  ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

**Comment by mojavelinux** [comment]
This is a bug that has already been fixed in Asciidoctor (in version 2.0.9). See #3279.

**Comment by mojavelinux** [comment]
I also noticed you are using the legacy doctitle syntax (which puts the document into legacy mode). I recommend using the single-line doctitle (e.g., `= menu-bug`).

**Comment by Alberth289346** [comment]
Thanks for the quick response. I did search for the bug but apparently not thorough enough.

As for the doc-title: You may want to fix the "Recommended Practice" document then:
https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-title

**Comment by mojavelinux** [comment]
Notice, however, that even in the tip, disabling compat mode is recommended. That's a valid combination for a modern document. So if you use the setext style, you absolutely should also be disabling compat mode unless you have a good reason for not doing it.
