### ISSUE TITLE
Multi-line title of a collapsible block is rendered incorrectly

### ISSUE THREAD

**Issue by vwildi** [asciidoctor/asciidoctor#3604]
Multi-line title of a collapsible block is rendered incorrectly. The resulting html summary block contains just the first line.

When rendering the following snippet: https://gist.github.com/vwildi/851fcf1dc3e91962bee618c12ae3e37f

The results look like this in HTML:
![html-bug](https://user-images.githubusercontent.com/3668514/77257248-6e8d1500-6c73-11ea-918d-7619e152b9c9.png)

and in PDF:
![pdf-bug](https://user-images.githubusercontent.com/3668514/77257250-6fbe4200-6c73-11ea-8c4a-8f1ff15ddf29.png)

The correct HTML page should be rendered like this:
![correct](https://user-images.githubusercontent.com/3668514/77257640-eeb47a00-6c75-11ea-83b0-96476e807948.png)

**Comment by mojavelinux** [comment]
AsciiDoc doesn't support multi-line block titles natively (and certainly not titles that contain other blocks). So this has nothing to do with the collapsible block. It's a limitation / restriction of block titles in general.

There's one hack / workaround you can use to force a hard line break in a block title.

```
:block-title: pass:c,q[This is a *multi-line* title of a block + \
second line]

.{block-title}
====
content
====
```

What we're doing is forcing the substitutions that get applied before attribute replacement to be applied to the attribute value, then using the result of that in the block title.

**Comment by Mogztter** [comment]
According to MDN, the permitted content in a `<summary>` element are: [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) or one element of Heading content.
So, technically, `<ul>`, `<li>` and `<br>` are not valid in a `<summary>` element.

If you are writing a quiz, I would suggest to use one `[%collapsible]` block per question/answer, or use a checked list with a custom converter to hide/show correct answers.

**Comment by vwildi** [comment]
Thanks for your quick replies!

@Mogztter: I wasn't aware of my syntax incorrectness! But, you're right. However, the Firefox browser renders it correctly.
I don't require it for a quiz, but for defining my coding conventions (similar to the Google C++ Style Guide which used the collapsible layout several years ago). Therefore, I want to define the important things in the `<summary>` element and further details in the `<details>` content.

**Comment by Mogztter** [comment]
@vwildi You're welcome!

> I don't require it for a quiz, but for defining my coding conventions (similar to the Google C++ Style Guide which used the collapsible layout several years ago).

That's not the case anymore? Do you have a link where I can find an example, I'm curious to see the rendering.

> Therefore, I want to define the important things in the <summary> element and further details in the <details> content.

In my opinion, you should not wrap more than a short sentence in a `<summary>` so I would probably write something like:

```
1.1 Primitives: When you access a primitive type you work directly on its value.

- `string`
- `number`
- `boolean`
- `null`
- `undefined`
- `symbol`
- `bigint`

.Example
[%collapsible]
====
[source,js]
----
const foo = 1;
let bar = foo;

bar = 9;

console.log(foo, bar); // => 1, 9
----

Symbols and BigInts cannot be faithfully polyfilled, so they should not be used when targeting browsers/environments that don’t support them natively.
====

5.5.1 Top-level functions

Top-level functions may be defined directly on the exports object, or else declared locally and optionally exported.
See 3.3.3 goog.module Exports for more on exports.

Examples:

[source,js]
----
/** @param {string} str */
exports.processString = (str) => {
  // Process the string.
};
----

.Longer example
[%collapsible]
====
[source,js]
----
/** @param {string} str */
const processString = (str) => {
  // Process the string.
};

exports = {processString};
----
====
```

![yo](https://user-images.githubusercontent.com/333276/77422798-64335e00-6dce-11ea-9aa9-fc384325aa57.png)

That way you are not limited to what you can write in the short description/summary and you can use the collapsible block to hide longer explanation and/or code sample.

**Comment by vwildi** [comment]
The current Google Style Guides look like this: [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)
Many years ago, they looked like this [Good old days style guide](https://web.archive.org/web/20100126161522/http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml)

However, I have to admit that they solved with JavaScript and not how I tried to resolve it.

@Mogztter Thanks for the detailed description. I will check it and probably I have to re-think my approach.
