### ISSUE TITLE
footnote title & mouse hover to see the content

### ISSUE THREAD

**Issue by toyboot4e** [asciidoctor/asciidoctor#3608]
Feature request: I suggest making an attribute to change `title="View footnote."` to `title="<Content of the footnote>"` (example below).

Background: We can write footnotes and they surely work. However, after jumping, users often have to look for a corresponding note by themselves, since there's no animation. Therefore, it would be more comfortable if they can read a footnote by only hovering their mouse on it.

Example: This is an ordinary footnote html:

```html
<sup class="footnote">
<a id="_footnoteref_1" class="footnote" href="#_footnotedef_1" title="View footnote.">1</a>
</sup>
```

If the attribute is specified, we would be able to read footnote with mouse hover.

```html
<sup class="footnote">
<a id="_footnoteref_1" class="footnote" href="#_footnotedef_1" title="<Content of the note>">1</a>
</sup>
```

**Comment by toyboot4e** [comment]
I found I should do it as an [extension](https://github.com/asciidoctor/asciidoctor-extensions-lab). Closing

**Comment by agrexgh** [comment]
Was this function realized?
