### ISSUE TITLE
Maybe there is an error

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#3611]
I have a AsciiDoc file:

```
= Test Case
D瓜哥 <http://www.diguage.com/>
:doctype: book

== Section Title Level 1

. list-1
.. list-1-1
+
List Content
+
List Content Subtitle:: This is subcontent


=== Section Title Level 2

This is my another content.

```

But the `Section Title Level 2` did not converted to HTML header tag.

![image](https://user-images.githubusercontent.com/2121467/78340314-73818b00-75c8-11ea-8680-e823c69259c1.png)

----

If I add a line of content on the  `=== Section Title Level 2`, like as following:

```
= Test Case
D瓜哥 <http://www.diguage.com/>
:doctype: book

== Section Title Level 1

. list-1
.. list-1-1
+
List Content
+
List Content Subtitle:: This is subcontent

Why is not shown as a new line??

=== Section Title Level 2

This is my another content.
```

![image](https://user-images.githubusercontent.com/2121467/78340721-2520bc00-75c9-11ea-81ae-dff0d900715f.png)

**Comment by mojavelinux** [comment]
It's because this is a description list entry:

```
List Content Subtitle:: This is subcontent
```

And description lists can be very greedy. You can force a break using a line comment:

```
+
List Content Subtitle:: This is subcontent

//

content after list
```

This just a quirk of the list parsing code.

**Comment by diguage** [comment]
`//` is a good solution. Thanks.

**Comment by Mogztter** [comment]
If you do have more questions, please feel free to ask in the gitter channel at: https://gitter.im/asciidoctor/asciidoctor.

@diguage can we close this issue?

**Comment by diguage** [comment]
@Mogztter Thanks.
