### ISSUE TITLE
solid macro examples and documentation

### ISSUE THREAD

**Issue by 42sol-eu** [asciidoctor/asciidoctor#3612]
Hi There,
thanks for your great tool and documentation.
Diving deeper into asciidoctor, I was getting my feet wet with the InlineMacro and BlockMacro.

I was not able to create a block macro that also runs for asciidoctor-pdf - something to do with the `create_pass_block`.

Examples and documentation would be really awesome. If there is none - just help me to find the right source (read the source luke...)

Sincerly
   Felix

**Comment by mojavelinux** [comment]
I recommend either looking at the docs here: https://asciidoctor.org/docs/user-manual/#extensions (which admittedly need elaboration) or the extensions lab (https://github.com/asciidoctor/asciidoctor-extensions-lab) where you can find loads of examples.

**Comment by 42sol-eu** [comment]
Hi Dan,
that's it I do not know how I missed those. Thanks.

I would say I close this issue.

Sincerely
  Felix
