### ISSUE TITLE
asciidoctor: FAILED: input file mysample.adoc is missing

### ISSUE THREAD

**Issue by ywramn** [asciidoctor/asciidoctor#3613]
Hello Super good people,
I am new to GitHub. and totally novice to programing / coding.  I was looking for a document creation platform and I cam across this amazing thing (asciidoctor), so I though to give it a try. 

I am using Windows 10, I somehow managed to install Bash and RVM, and Ruby through RVM. I also successful installed the asciidoctor Gem (at least my the response from Bash say so) .

The I am facing an issue with the conversion of an "adoc" file via terminal.  
I am following the guidelines from  https://asciidoctor.org/ but still no luck. 

Steps to reproduce:

1. I write a little text via notepad ++ and saved it with adoc exteniosn on desktop.
2. I want to now preview and convert the file in HTML, so I use the Bash terminal and type: 
**user@LAPTOP-C39ALSK:/mnt/c/WINDOWS/system32$ asciidoctor mysample.adoc**
3. The response is "**asciidoctor: FAILED: input file mysample.adoc is missing**"

I have installed ruby from ruby installer and also from RVM
The ruby installer ruby has been installed at C: \ruby .

**Following is result of RVM version, ruby version, and asciidoctor version, that my system shows.
rvm 1.29.10 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]**

**ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]**

**Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)**

I also need to know that if I am doing the things right, or there is any thing that is missing. Please guide me I have spent more thank one week on this and still unable to produce anything.

Thanking you all in advance:
Ywramn.

**Comment by Mogztter** [comment]
Hello Ywramn, the error indicates that the file "mysample.adoc" cannot be found in the path `/mnt/c/WINDOWS/system32`. Are you sure that your file is saved at this location?

When using the `asciidoctor` CLI, you can use an absolute path to your file and/or your current directory using the command `cd`. For instance if your file is saved in `/mnt/c/Users/Ywramn/Downloads/mysample.adoc` you can change the directory using:

```
cd /mnt/c/Users/Ywramn/Downloads
```

And then run the command again:

```
asciidoctor mysample.adoc
```

Alternatively you can also do:

```
asciidoctor /mnt/c/Users/Ywramn/Downloads/mysample.adoc
```

**Comment by ywramn** [comment]
Hi Mogztter,
I really appreciate your prompt response,helped me a lot. You suggestions worked like magic and solved my problem. I was able to get an HTML file, I also downloded the PDF gem and successfully created a PDF file. 
Asciidoctor is such a powerful text processor. Kudos to the people behind this. They really  have worked marvelously. 

I am also thankful to you and the GH for providing such an active and easy meeting place that nurtures the learning and development. 
Best, 
Ywramn.

**Comment by Mogztter** [comment]
I'm glad that it's working for you!

> Asciidoctor is such a powerful text processor. Kudos to the people behind this. They really have worked marvelously.

Thanks for your kind words ❤️ 
You can join our Gitter channel at: https://gitter.im/asciidoctor/asciidoctor if you have any questions about Asciidoctor 😄 

Have a nice day/evening.
Guillaume
