### ISSUE TITLE
Source blocks: to substitute characters that aren't separated by spaces

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3620]
For example:

```
----
some_app <startup parameters>
----
```

Angle brackets should be highlighted using `<mark>`. Here is what I tried:

```
[subs="quotes,attributes"]
----
some_app #<#{blank}statup parameters{blank}#>#
----
```

```
[subs="normal"]
----
some_app #<#{blank}statup parameters{blank}#>#
----
```

The `<` is highlighted as I need, but the `>` is displayed as `#>#`. What I'm doing wrong?

**Comment by mojavelinux** [comment]
> `[subs="quotes,attributes"]`

This is dangerous. You should use incremental subs: https://asciidoctor.org/docs/user-manual/#incremental-substitutions

**Comment by mojavelinux** [comment]
What you're looking for it:

```
[subs=+quotes]
----
some_app ##<##statup parameters##>##
----
```

**Comment by mojavelinux** [comment]
In the future, please ask usage questions in the gitter channel at https://gitter.im/asciidoctor/asciidoctor.
