### ISSUE TITLE
backticks in text rendered inconsistently

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor#3624]
I'm very new to Asciidoctor, in fact this is my first project using it.

Versions: 
- asciidoctor 2.0.10
- asciidoctor-epub3 1.5.0.alpha.15
- asciidoctor-pdf 1.5.3
- rouge 3.18.0

I am trying render the following paragraph:

```
Netmasks are represented using 32bit binary numbers.
All the bits before the chosen divide are set to `1`, and all the bits after the divide are set to `0`.
When written in binary, a netmask MUST be 32 bits long, and MUST consist of a series of `1`s
followed by a series of `0`s.
The chosen dividing line represented by the netmask is the point where the `1`s change to `0`s.
```

No matter what I do, only the 1 and 0 in the second sentence are rendered correctly, the others are passed through as is.

<img width="905" alt="Screenshot 2020-04-18 at 10 16 31" src="https://user-images.githubusercontent.com/7474858/79632149-b95c5880-815d-11ea-8771-096dc4efd8c1.png">

When I switch to double backticks it's the same behavior. I've already checked for gremlins, but there are none.

Am I doing something wrong or did I find a bug?

**Comment by mojavelinux** [comment]
To understand the behavior you are observing, I recommend reading the following section to understand the difference between constrained formatting and unconstrained formatting. https://asciidoctor.org/docs/user-manual/#constrained-quotes

In short, if there are word characters around the formatting marks, you need to use double formatting marks.

Questions like this are best asked in the gitter channel at https://gitter.im/asciidoctor/asciidoctor.

**Comment by hepabolu** [comment]
I did read that section and I tried both double and single backticks, but the problem remains.

**Comment by Mogztter** [comment]
@hepabolu How do you render your document? Here I'm using the browser extension:

![raw](https://user-images.githubusercontent.com/333276/79642260-ca788a00-819c-11ea-8892-c153ef0e5730.png)

![render](https://user-images.githubusercontent.com/333276/79642261-cba9b700-819c-11ea-9dd1-806d806bdf62.png)

As you can see, it's working as expected.

**Comment by mojavelinux** [comment]
As @Mogztter pointed out, I think you'll find that the following source gives you the result you are looking for:

```
Netmasks are represented using 32bit binary numbers.
All the bits before the chosen divide are set to `1`, and all the bits after the divide are set to `0`.
When written in binary, a netmask MUST be 32 bits long, and MUST consist of a series of ``1``s followed by a series of ``0``s.
The chosen dividing line represented by the netmask is the point where the ``1``s change to ``0``s.
```

**Comment by hepabolu** [comment]
Ok, I've tested it once again, although I'm pretty sure I've tried all kinds of combinations of single and double backticks.

I fixed the text to be exactly like @mojavelinux wrote up in the previous post. The result is like my image in my original post, only with double backticks.

I don't use a browser plugin, but I generate the HTML page using the CLI. The resulting HTML is where I took the screenshot from. I use asciidoctor-pdf to generate the PDF, which also has double backticks and the same goes for asciidoctor-epub3 and the resulting ePub. Note, the text in the ePub has single backticks, not double.

I've tested some more and it seems to be not in the snippet or the file it's in but it's more subtle:

* when I generate just the page on its own I get the output as expected (aka correct)
* when I generate the page as part of a larger set I get the output I explained originally (aka wrong)
* I just stripped the spine document of all attributes except, title and author and the include of the file and the problem still remains

I don't know what else to do to narrow this down.

**Comment by mojavelinux** [comment]
This seems like it could be a problem introduced by Asciidoctor EPUB3. If it's no just Asciidoctor EPUB3, we're going to need you to provide us with a full not-working example so that we're able to debug. Otherwise, we can only guess at what the problem might be.

**Comment by hepabolu** [comment]
I prepared something. This is the smallest example I can create that still has the problem.

[Archive.zip](https://github.com/asciidoctor/asciidoctor/files/4505848/Archive.zip)

**Comment by mojavelinux** [comment]
Thank you. That's exactly what I needed.

You problem is this line:

```
My book
=======
```

That puts Asciidoctor into legacy (i.e., compat) parsing mode, which does not support unconstrained monospace. You can fix it by changing it to:

```
= My book
```

For more information about legacy parsing mode, see https://asciidoctor.org/docs/migration/

In general, two-line section titles are strongly discouraged and will likely be removed in the future (when it's the appropriate time to do so).

**Comment by hepabolu** [comment]
Yes, that fixed it. Thank you. I didn't look at the migration page very thoroughly because I started  new, but I copied the content for the spine from the Progit2 book and adjusted as needed and neve looked at it again. They still have this header.

**Comment by mojavelinux** [comment]
Yes, the Progit2 book is one of the remaining documents using the legacy syntax. I've been in contact with them about it, but it can be tricky to migrate such a large manuscript. Due to their use of the legacy compat mode, it's not the best starting point for writing modern AsciiDoc.

**Comment by comps** [comment]
Thanks for the document title hint!

I've been pulling my hair out why double backticks are not working (and a few other things) despite me never enabling compat mode. It was the sneaky document title (for which I was using a different header style as the old python-based asciidoc documentation presented both as equivalent).
