### ISSUE TITLE
include:: and special characters

### ISSUE THREAD

**Issue by fishermans** [asciidoctor/asciidoctor#3628]
When I try to include an external adoc that contains special characters, only ? is shown:

```
:toc:

= Test

== Hallo

include::test2.adoc[]
```

with test2.adoc
```
== Test
ÄÖÜ and so on
```

I am getting the following result:
![Bildschirmfoto 2020-04-20 um 19 31 13](https://user-images.githubusercontent.com/4817889/79781303-9092b980-833d-11ea-832d-3bf32a1daab7.png)

If the content is inserted directly, it looks like that:

```
:toc:

= Test

== Hallo

== Test
ÄÖÜ and so on
```

![Bildschirmfoto 2020-04-20 um 19 33 33](https://user-images.githubusercontent.com/4817889/79781493-d8b1dc00-833d-11ea-8363-4309eb3f81a3.png)

Same happens when I am using the asciidoc-maven-plugin to convert to PDF.
Encoding is set to UTF-8.
Both adoc files are UTF-8 encoded.

**Comment by mojavelinux** [comment]
It appears that the include file is not encoded in UTF-8, despite what you are claiming. Please recheck it.

In the future, this is where #3248 is going to help (pending the 2.0.11 release).

**Comment by mojavelinux** [comment]
If you want me to be able to help you debug further, you'll need to provide a sample git repository where I can reproduce the issue.

**Comment by fishermans** [comment]
> It appears that the include file is not encoded in UTF-8, despite what you are claiming. Please recheck it.
> 

Thanks, Dan.

Indeed, one file was encoded differently. Please excuse!

**Comment by mojavelinux** [comment]
Excellent news! Glad to help.
