### ISSUE TITLE
Specify the path to generated files for the HTML src attribute.

### ISSUE THREAD

**Issue by zivbk1** [asciidoctor/asciidoctor#3635]
Here is some frontmatter code that I have set up now.

```
ifdef::backend-pdf[]
:imagesdir: /builds/tecidev/support/static/images
:imagesoutdir: /builds/tecidev/support/static/images
endif::[]
ifdef::backend-html5s[]
:imagesdir: /images
:imagesoutdir: /images
endif::[]
```

The PDF backend writes images to the correct location and reads images from the same location.  No problem there.

The HTML backend is where the problem appears.
If I set `imagesoutdir` to the absolute path of `/builds/tecidev/support/static/images` as I do for the PDF backend, which is where I want them to go, then they will write there no problem, but then the `src` path in the HTML for that image is `src="/builds/tecidev/support/static/images/stem-hash.svg"` instead of `src="/images/stem-hash.svg"` which is what I would expect it to be based on my `imagesdir` attribute.

Currently, in the HTML backend, I set both the `imagesdir` and `imagesoutdir` to `/images` so that the path is correct in the HTML src attribute, but the images the HTML is pointing to were actually created by the PDF backend process. The HTML process writes them to the 'images' folder in the root of my project that I just .gitignore and delete from time to time. The unwanted byproduct of a broken process. 😢 

It seems that we need a way to specify where the file should write to as an absolute path like `imagesoutdir`, and also specify the file path for the output files relative to the `imagesdir` attribute.  Something like the following would be great.
```
ifdef::backend-html5s[]
:imagesdir: /images
:imagesoutdir: /builds/tecidev/support/static/images
:imagesoutpath: 
endif::[]
```
You should default the value of `imagesoutpath` to be the `imagesdir` attribute if it isn't defined.

A more complex example where you wanted the generated images to be in a subdirectory of your main images folder would look like this.
```
ifdef::backend-html5s[]
:imagesdir: /images
:imagesoutdir: /builds/tecidev/support/static/images/gen
:imagesoutpath: gen
endif::[]
```
In this case the stem SVG image generated for the HTML processor would go to `/builds/tecidev/support/static/images/gen` and the image src attribute in the output HTML would be `/images/gen/stem-hash.svg`.

Having said all this, I could totally be missing something and there is a better way to do it all that will solve this issue.

**Comment by bwklein** [comment]
Here is a video tour of the situation.
https://www.youtube.com/watch?v=SVezqj6jCww

I thought this would be better than lots of words here so you can see for yourself how things are setup.  The project is in a private repo that I am glad to invite people to if they want to pull the site and test it locally, but I can't make it public at this time.

**Comment by zivbk1** [comment]
Moved to https://github.com/asciidoctor/asciidoctor-mathematical/issues/83
