### ISSUE TITLE
Implement support for rouge-linenums-mode (add inline mode)

### ISSUE THREAD

**Issue by hepabolu** [asciidoctor/asciidoctor#3641]
I'm using asciidoctor 2.0.10 to generate HTML. I use Rouge for syntax highlighting.

According to https://asciidoctor.org/docs/user-manual/#rouge I should use 
```
:rouge-linenums-mode: inline
```
for sourceblocks that have long lines. However, that option doesn't seem to work. It doesn't make any difference if I use 'table' or 'inline'.

In both cases the codeblock renders as a table with 2 cells, one containing a '<pre>' tag with all the line numbers, one with the lines as spans wrapped in 1 '<pre>' tag.

On a large block of long lines the linenumbers end way earlier than the actual lines.

This code: https://rouge-ruby.github.io/docs/Rouge/Formatters/HTMLLineTable.html suggests there should be a row with a linenumber + source code line per line.

But that class is never used in https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/syntax_highlighter/rouge.rb

I'm not good in Ruby, so I might be overlooking something. If so, please let me know.

**Comment by mojavelinux** [comment]
Please provide a sample listing block that isn't working properly.

FYI, Asciidoctor does not use the table and line formatters provided by Rouge. Instead, we use the ones from here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/rouge_ext.rb

**Comment by mojavelinux** [comment]
Aha! Asciidoctor does not currently support modifying the linenums mode in Rouge, so you're correct that this setting has no effect.

**Comment by mojavelinux** [comment]
The formatter class you linked to was added to Rouge after the last release of Asciidoctor: https://github.com/rouge-ruby/rouge/commits/master/lib/rouge/formatters/html_line_table.rb

**Comment by mojavelinux** [comment]
I updated the docs to reflect that this attribute is not yet supported.

**Comment by mojavelinux** [comment]
For the sake of keeping the styles aligned with the default stylesheet, we'll probably need to implement our own formatter...or at least tune the settings of the one provided by Rouge.

**Comment by keryell** [comment]
I am involved in a project where we are migrating a big specification document from LaTeX to AsciiDoctor with a lot of source code formatting and tables (https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf).
I am still fighting to have source highlighting working correctly both in HTML and PDF with line numbers.
While the discussion in https://github.com/asciidoctor/asciidoctor-pdf/issues/224#issuecomment-745642723 proposes to go with `rouge` for the PDF side, it looks like `inline` mode for `rouge` does not work yet.
By looking at `asciidoctor` around `lib/asciidoctor/syntax_highlighter.rb`, it is not clear how far we are...

**Comment by mojavelinux** [comment]
This issue is about table mode, but your comment mentions inline mode. Do you mean table mode?

Can you elaborate on how you're "still fighting to have source highlighting working correctly". What is not working? If this is a new issue, can you please open a new issue?

**Comment by keryell** [comment]
What I mean is that I would like to have `:rouge-linenums-mode: inline` working too, as suggested at the start of this issue.
It is not a new issue, just asking about the status of this feature.

**Comment by mojavelinux** [comment]
I was confused because the issue subject is ignore. I've renamed it.

I suppose you could use Pygments, which has support for linenums mode and works for both HTML and PDF. Though keep in mind that the Pygments bridge sometimes fails and requires Python 2 by default.

**Comment by mojavelinux** [comment]
If someone would like to try to implement this, I'd be happy to review the code. I don't have the time to work on it now or for the foreseeable future.

**Comment by keryell** [comment]
Thanks for the feedback.
I could in theory spend some time on it but I do not know Ruby, so it is very hard for me to grasp the big picture... :-(
So, in the meantime, either I try to survive with `rouge` with table mode and tweak the CSS to remove the line wrapping in the HTML as an OK solution or goes the Pygments way and solve the obsolete Python 2 issue... Perhaps the simpler is to survive with `rouge` for now.

**Comment by mojavelinux** [comment]
You can remove the line wrapping by setting the following in the document header (or via the CLI or API):

```
:!prewrap:
```

That will only apply to HTML (since it is only relevant for HTML).

**Comment by hepabolu** [comment]
I have taken a stab at making this work and I got to the point that I got a
working version but tests showed that the placement of the annotation
bullets was broken by my fix.
I have very limited (virtually none) knowledge of Ruby, so fixing that
problem was beyond my capability. So that’s where I stopped.

If somebody is interested I can put it up on GitHub somewhere for someone
to take over and finish it.

**Comment by keryell** [comment]
@mojavelinux Interestingly `:!prewrap:` is working in my case with the default AsciiDoctor CSS but not with the CSS I have inherited from... So I thought it was not working at all.
I will reverse engineer the non working CSS to understand why/where.
Thanks.

**Comment by mojavelinux** [comment]
@hepabolu that would be fantastic. It would certainly plant some seeds for someone else coming along (and perhaps me in the future). Trust me when I say that when I start a feature, I usually have no idea what I'm doing too. It's the doing that gives me knowledge.

**Comment by hepabolu** [comment]
Added a pull request #3899 with the code and the tests so far.

**Comment by mojavelinux** [comment]
I have submitted and merged a different implementation which is more consistent with the output of Pygments.

**Comment by mojavelinux** [comment]
I'm considering backporting this one to v2.0.x, but I haven't made a decision whether to do it yet. Technically, it's an enhancement, though the fact that it was once documented also allows us to look at it as a bug.

**Comment by mojavelinux** [comment]
For reference, this has not (yet) been backported to 2.0.x. The label on the issue indicates which version the fix is first available.
