### ISSUE TITLE
Convert asciidoctor to Jupyter notebooks

### ISSUE THREAD

**Issue by christianpeel** [asciidoctor/asciidoctor#3643]
My understanding is asciidoctor does not export to [Jupyter](https://jupyter.org/) notebooks.  Is this correct, or did I miss something?

Would it be a big project to do such a thing?  I think that `nbconvert` can  be used to go the other way (from Jupyter to .asciidoc). I'm interested in converting [ThinkJulia](https://github.com/BenLauwens/ThinkJulia.jl/issues/43) to Jupyter.

**Comment by mojavelinux** [comment]
There's no converter to Jupyter notebooks to my knowledge (other than maybe pandoc).

Asciidoctor provides a Converter API that you can use to implement this converter. See https://www.rubydoc.info/gems/asciidoctor/2.0.9/Asciidoctor/Converter. It's pretty easy to get the basics working, but takes quite bit of time to make it complete. Best just to start and see how it goes.

You can also use converter templates (https://github.com/asciidoctor/asciidoctor.org/issues/80), though if you are doing an entire converter, it's best to work from the API I think.

**Comment by christianpeel** [comment]
Thanks!

**Comment by prudhomm** [comment]
@chrisvwx there is https://github.com/neo4j-documentation/asciidoctor-jupyter which works very nicely
