### ISSUE TITLE
Numbering equations and labels in latexmath fails

### ISSUE THREAD

**Issue by EganSolo** [asciidoctor/asciidoctor#3649]
I am trying to number mathematical equations automatically or at least give them a label. 
Here's what I tried:

```
:stem: latexmath

[stem]
++++
\begin{equation}
 C = \alpha
\end{equation}
++++
```

and 

```
[stem]
++++
\label{eq:ref}
 C = \alpha
++++
```

and  even

```
.Equation One
[stem]
++++
 C = \alpha
++++
```

**Comment by mojavelinux** [comment]
In the future, please ask usage questions on the discussion list at https://discuss.asciidoctor.org or the chat channel at https://gitter.im/asciidoctor/asciidoctor. The issue tracker is for tracking bugs and feature requests.

**Comment by mojavelinux** [comment]
You need to enable equation numbering on the document using the `eqnums` attribute.

```
:stem: latexmath
:eqnums:

[stem]
++++
\begin{equation}
 C = \alpha
\end{equation}
++++
```
