### ISSUE TITLE
Math block inside tables does not work?

### ISSUE THREAD

**Issue by EganSolo** [asciidoctor/asciidoctor#3650]
Tried the following but the math block is rendered literaly without any transformation.

```
:stem: latexmath

[cols="2,2a"]
|===
|Equation 1
|
[stem]
++++
  C = \alpha
++++
 
|Ruby
|Programming Language
```

**Comment by mojavelinux** [comment]
That seems to work fine for me. Are you sure MathJax didn't fail to load in the browser?

**Comment by mojavelinux** [comment]
I can assure you that stem blocks work fine inside AsciiDoc table cells.

**Comment by EganSolo** [comment]
Thank you for your quick response!
I am actually using AsciiDoc inside Gitlab and it's been an uphill struggle. 
I'm heartened to hear that it works! Now I need to figure out a way to debug it from within Gitlab running inside a docker container.

What are you using to debug? Do you have any tips and tricks?

**Comment by mojavelinux** [comment]
It's best if you report issues with AsciiDoc rendering on GitLab with GitLab. We cannot control what GitLab enables or disables.

> I am actually using AsciiDoc inside Gitlab and it's been an uphill struggle.

Given that the repository view of GitLab wasn't designed to be a publishing environment, that's to be expected. I think we can be appreciative that they have been receptive to making it an adequate preview (and still more can be done). But it's never going to match publishing a standalone HTML file (such as through GitLab Pages) which allows you to fully control the integrations and output.

**Comment by EganSolo** [comment]
Thankd @mojavelinux 
I've logged a few posts in the Gitlab forum to no availd :) 

I'll try pages though an dsee if that'll work better. 

Much appreocated.

**Comment by mojavelinux** [comment]
> I've logged a few posts in the Gitlab forum to no avail :)

Open source requires patience ;)

> I'll try pages though and see if that'll work better.

GitLab Pages seems to be what you really want because then you can run the Asciidoctor command directly (in a GitLab CI job), thus giving you complete control.

> Much appreciated.

:+1:
