### ISSUE TITLE
indexterm doesn't work if text contains =

### ISSUE THREAD

**Issue by stallio** [asciidoctor/asciidoctor#3652]
The indexterm macro and triple-parenthesis macro return different results if any of the terms to be indexed contain an equals sign.

The triple-parenthesis form does what I expect it to, but `indexterm:` does not.

Here is my test file:

```
= index test

indexterm:[index1, id=indexo]

(((index1, id=indexo)))

indexterm:[id=indexo, index2]

(((id=indexo, index2)))

indexterm:["id=indexo", index2]

((("id=indexo", index2)))
```

The top two should return the same result, and the bottom four should return the same result. But here is what I get when I convert to Docbook 5:

```
<simpara><indexterm>
<primary>index1</primary>
</indexterm></simpara>

<simpara><indexterm>
<primary>index1</primary><secondary>id=indexo</secondary>
</indexterm></simpara>

<simpara><indexterm>
<primary>i</primary><secondary>d</secondary><tertiary>=</tertiary>
</indexterm></simpara>

<simpara><indexterm>
<primary>id=indexo</primary><secondary>index2</secondary>
</indexterm></simpara>

<simpara><indexterm>
<primary>id=indexo</primary><secondary>index2</secondary>
</indexterm></simpara>

<simpara><indexterm>
<primary>id=indexo</primary><secondary>index2</secondary>
</indexterm></simpara>
```

If the second term (or any subsequent term) contains `=`, it disappears. If the first term contains `=`, then it gets split by character.

**Comment by mojavelinux** [comment]
You are right. This was broken when #2047 was implemented. In that case that named attributes are detected, it was only considering the first term. I've submitted a PR to fix it.

This fix should be backported to 2.0.x.
