### ISSUE TITLE
Allow setting HTTP Header for allow-uri-read

### ISSUE THREAD

**Issue by Xaseron** [asciidoctor/asciidoctor#3662]
We would like to embedd source code snippets for our library from some demo projects that are resident in separate Github Enterprise repostories. For the raw file access we have to set an authorization header.
e.g.:
`curl -H 'Authorization: token MY_TOKEN' https://raw.git.example.com/DemoProject/master/Jenkinsfile`

How can we pass this header to asciidoctor?

**Comment by Mogztter** [comment]
Hello @Xaseron 

As a workaround, I think you can pass the token as a query parameter:

```
include::https://raw.git.example.com/DemoProject/master/Jenkinsfile?token=MY_TOKEN[]
```

**Comment by Xaseron** [comment]
No,
i'vet tried this and the web ui generates some token that is only usable for one file.
It is not possible to use a personal access token.

**Comment by Mogztter** [comment]
Indeed, the token is unique per file 😣

**Comment by mojavelinux** [comment]
This would be an appropriate use of docinfo. You can add additional elements to the HTML head using a docinfo file. See https://asciidoctor.org/docs/user-manual/#head-docinfo-files

**Comment by Xaseron** [comment]
Can you elaborate how this can work? I've tried something like with this with the html backend:
```html
<head>
    <meta name="Authorization" content="token MY_GITHUB_TOKEN">
</head>
```
Without success. 

Actually my goal is convert this snippet to docbook and then to github flavored markown:
```adoc
=== Demo Project
[source, groovy]
----
include::https://raw.git.example.com/DemoProject/master/Jenkinsfile[tags=unittest, indent=0]
----
```

**Comment by mojavelinux** [comment]
The documentation explains how to apply docinfo. If that's not clear, please file a documentation issue at https://github.com/asciidoctor/asciidoctor.org/ explaining what you tried and what output you got and we'll try to improve it.

**Comment by mojavelinux** [comment]
btw, you don't need to include `<head>` in docinfo as the content is already injected in the `<head>`.

**Comment by Xaseron** [comment]
@mojavelinux i've studied the documentation and i don't think that this is the right solution.
I am NOT trying to set something in the generated http document. 
During my search i've found that in the https://github.com/asciidoctor/asciidoctor/blob/54de03df73e565ed8cae6c4da693b827df06c7d5/lib/asciidoctor/reader.rb#L1103 the reading of the URI is exectued and only the constant `URI_READ_MODE` is passed as an argument.

My feature request is to make this customizable with an attribute. 
e.g. [Additional header fields can be specified by an optional hash argument.](https://ruby-doc.org/stdlib-2.6.3/libdoc/open-uri/rdoc/OpenURI.html) 
This would enable me to set
` "Authorization" => "token MY_GITHUB_TOKEN",`

**Comment by mojavelinux** [comment]
I see what you're saying. You need to send authentication headers to access a remote include file. That requires using a custom include processor. That's not something the Asciidoctor processor offers out of the box, nor do I think it should.

**Comment by Xaseron** [comment]
Ok, thank you for your time. :-)
I've already though that it might be out of scope.

**Comment by mojavelinux** [comment]
I will add that we'll be working on making creating an include processor / resolver simpler. It should only have to consist of the lines that deal with fetching the content. So something like this use case should be very straightforward to implement via the extension mechanism. See #571 (which may end up being more than one kind of hook).

**Comment by Xaseron** [comment]
I've got it working with some hacking methods:
1. run a proxy to inject the header:
`mitmdump -R https://raw.git.example.com --setheader :~q:Authorization:'token MY_GITHUB_TOKEN'`
2. export the proxy
`export https_proxy=http://127.0.0.1:8080`
3. disable ssl verification (add this to the beginning of `/usr/bin/asciidoctor`
```ruby
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

@mojavelinux Can we add an attribute `disable-ssl-verification` to asciidoctor to skip point 3

**Comment by mojavelinux** [comment]
> disable ssl verification (add this to the beginning of /usr/bin/asciidoctor)

It's not necessary to hack the bin script. You can load a custom Ruby script when invoking Asciidoctor.

First, create the script:

*disable-ssl-verification.rb*
```
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

Then load it when invoking the asciidoctor command as follows:

```
asciidoctor -r ./disable-ssl-verification.rb doc.adoc
```

(Though it's better to configure the certs for your proxy).

I do not want to encourage disabling SSL verification in core. That would be a bad security practice for a library. But you are free to do it yourself as I showed.

I might be mistaken, but I think you can also use a Ruby script to configure global headers that are sent with each request. If not, you can monkeypatch OpenURI.open_uri.

**Comment by Xaseron** [comment]
I went with the monkey patching approach. I despaired 3 hours on `alias_method`. So i just copied the whole code.
openuri-monkey.rb:
```ruby
require 'open-uri'

module OpenURI
def OpenURI.open_http(buf, target, proxy, options)
if proxy
      proxy_uri, proxy_user, proxy_pass = proxy
      raise "Non-HTTP proxy URI: #{proxy_uri}" if proxy_uri.class != URI::HTTP
    end

    if target.userinfo
      raise ArgumentError, "userinfo not supported.  [RFC3986]"
    end

    header = {"Authorization" => "token #{ENV["GITHUB_TOKEN"]}"}
    options.each {|k, v| header[k] = v if String === k }

    require 'net/http'
    klass = Net::HTTP
    if URI::HTTP === target
      # HTTP or HTTPS
      if proxy
        unless proxy_user && proxy_pass
          proxy_user, proxy_pass = proxy_uri.userinfo.split(':') if proxy_uri.userinfo
        end
        if proxy_user && proxy_pass
          klass = Net::HTTP::Proxy(proxy_uri.hostname, proxy_uri.port, proxy_user, proxy_pass)
        else
          klass = Net::HTTP::Proxy(proxy_uri.hostname, proxy_uri.port)
        end
      end
      target_host = target.hostname
      target_port = target.port
      request_uri = target.request_uri
    else
      # FTP over HTTP proxy
      target_host = proxy_uri.hostname
      target_port = proxy_uri.port
      request_uri = target.to_s
      if proxy_user && proxy_pass
        header["Proxy-Authorization"] =
                        'Basic ' + ["#{proxy_user}:#{proxy_pass}"].pack('m0')
      end
    end

    http = proxy ? klass.new(target_host, target_port) : klass.new(target_host, target_port, nil)
    if target.class == URI::HTTPS
      require 'net/https'
      http.use_ssl = true
      http.verify_mode = options[:ssl_verify_mode] || OpenSSL::SSL::VERIFY_PEER
      store = OpenSSL::X509::Store.new
      if options[:ssl_ca_cert]
        Array(options[:ssl_ca_cert]).each do |cert|
          if File.directory? cert
            store.add_path cert
          else
            store.add_file cert
          end
        end
      else
        store.set_default_paths
      end
      http.cert_store = store
    end
    if options.include? :read_timeout
      http.read_timeout = options[:read_timeout]
    end
    if options.include? :open_timeout
      http.open_timeout = options[:open_timeout]
    end

    resp = nil
    http.start {
      req = Net::HTTP::Get.new(request_uri, header)
      if options.include? :http_basic_authentication
        user, pass = options[:http_basic_authentication]
        req.basic_auth user, pass
      end
      http.request(req) {|response|
        resp = response
        if options[:content_length_proc] && Net::HTTPSuccess === resp
          if resp.key?('Content-Length')
            options[:content_length_proc].call(resp['Content-Length'].to_i)
          else
            options[:content_length_proc].call(nil)
          end
        end
        resp.read_body {|str|
          buf << str
          if options[:progress_proc] && Net::HTTPSuccess === resp
            options[:progress_proc].call(buf.size)
          end
          str.clear
        }
      }
    }
    io = buf.io
    io.rewind
    io.status = [resp.code, resp.message]
    resp.each_name {|name| buf.io.meta_add_field2 name, resp.get_fields(name) }
    case resp
    when Net::HTTPSuccess
    when Net::HTTPMovedPermanently, # 301
         Net::HTTPFound, # 302
         Net::HTTPSeeOther, # 303
         Net::HTTPTemporaryRedirect # 307
      begin
        loc_uri = URI.parse(resp['location'])
      rescue URI::InvalidURIError
        raise OpenURI::HTTPError.new(io.status.join(' ') + ' (Invalid Location URI)', io)
      end
      throw :open_uri_redirect, loc_uri
    else
      raise OpenURI::HTTPError.new(io.status.join(' '), io)
    end
  end
end  
```
jenkins pipeline:
```groovy
withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
    sh '''
    for f in *.adoc; do asciidoctor --failure-level=WARN -r asciidoctor-diagram -r ./openuri-monkey.rb -b docbook $f -a allow-uri-read; done
   '''
}
```

**Comment by mojavelinux** [comment]
That's great news.

I should have shared with you the simplest way to monkeypatch a Ruby class method.

```rb
require 'open-uri'

OpenURI.singleton_class.prepend (Module.new do
  def open_http buf, target, proxy, options
    options['Authorization'] = %(token #{ENV["GITHUB_TOKEN"]}) if ENV.key? 'GITHUB_TOKEN'
    super
  end
end)
```

(You might even be able to override open_uri directly).

(see https://sikac.hu/how-to-use-module-prepend-to-override-class-method-in-ruby-4197c6159cd3)

**Comment by Xaseron** [comment]
Awesome. Your snippet works like a charm.

Thank you very much for all the time you have taken to help me. 🥇

**Comment by mojavelinux** [comment]
I'm so glad to hear that! A happy user is all the reward I need ;)

**Comment by DEvil0000** [comment]
looks like this is quite a common use case - will there be a flag/option to disable ssl verification?

**Comment by lfvjimisola** [comment]
> I see what you're saying. You need to send authentication headers to access a remote include file. That requires using a custom include processor. That's not something the Asciidoctor processor offers out of the box, nor do I think it should.

It would be useful if it was available out-of-the-box because then it would work on SaaS such GitLab.com as well.

Could it not be a parameters to the regular include? E.g.

include::https://raw.git.example.com/DemoProject/master/Jenkinsfile[<parameters here>]

You can then specify using parameters:

1. what type of auth: token in header etc
2. how auth should be read i.e. from ENV (token, user/pass) or hard-coded in parameters (not recommend for security reason)

**Comment by mojavelinux** [comment]
The AsciiDoc integration on GitLab already uses an include processor to handle the include directive, so even if we made a change to core, it wouldn't help with that scenario. The logic needs to be added to the include processor that was developed for GitLab.

> I'm trying to understand why your think that it should be offered out of the box. It would be useful if it was available out-of-the-box as it might not be that uncommon having to authenticate.

I'm not going to bring this functionality into core because I can see how it's going to play out. This would open the door for a stream of requests for yet another authentication mechanism or environment, and the responsibility to integrate and maintain those alternatives is going to fall on my shoulders. I'm not prepared to do that.

I also don't think that the Asciidoctor processor should be in the business of authentication. Just look at how quickly you went from thinking about embedding a private token into the AsciiDoc source (which isn't acceptable in the slightest bit) to needing a token to be resolved from an environment variable (or AsciiDoc attribute). There is way too much personalization required to support this in core. This is precisely why we offer extensions. So I'm sticking with my earlier statement that this isn't something the core processor is going to provide.

**Comment by DEvil0000** [comment]
@mojavelinux I understand and partialy agree on your point about integration of some auth mechanism but what about just a more simple "ssl_check_none" flag/parameter?
also letting the user add a auth header content from a parameter or env var should be quite the end of the feature list and maybe the most common auth variant. don't think it would be much effort to maintain.
would you accept a PR for such features?

**Comment by mojavelinux** [comment]
No, I would not. I have made my position clear and the reasoning behind it. I'm not going to keep restating it. You can create an Asciidoctor extension if you need this functionality.
