### ISSUE TITLE
<stdin> input results in html output not having title block

### ISSUE THREAD

**Issue by liljenstolpe** [asciidoctor/asciidoctor#3664]
Greetings,

I was tearing my head out when previews created by OmniMarkupPreviewer (sublime editor) was not showing my title block, but running the text through asciidoctor rendered correctly.  Specifically, the OmniMarkupPreviewer output starts with a normal text rendering of "Table of Contents".  It also doesn't process the include directives.

Looking at the code, the previewer uses the following to render the asciidoc document:
```
text = $stdin.read
$stdout.write Asciidoctor::Document.new(text).render
```
To test, I then took my document and ran it through the asciidoctor command line for stdin, and got the exact same output that the Previewer generated.
```
$ asciidoctor -s - < doc.adoc > doc.html
```

The first lines of my content are here:
```
= Annoying Title Here
:author: My details
:email: more details
:revnumber: {git-metadata-sha-short}
:revdate: {git-metadata-date} {git-metadata-time} {git-metadata-timezone}
:revremark: {git-metadata-commit-message}
:version-label!:
:title-separator: {sp}|
:title-page:
:toc:
:sectnums:
:sectnumlevels: 2

Some pithy text went here

== Executive Summary

include::020-currentEnvironment.adoc[leveloffset=+1]

== Partner Segmentation
```
The results, as I said before, are missing the entire title/author/e-mail block, and starts with a normal text rendering of "Table of Contents".  Also, the include is rendered as a link, rather than an include.

Thoughts?

**Comment by mojavelinux** [comment]
By default, the embedded output does not include the document title (because it's intended for embedding). If you want the document title to be included, invert the `notitle` attribute:

```
$ asciidoctor -a notitle! -e - < doc.adoc > doc.html
```

The embedded output does not currently include the author, date, and revision info. That's a duplicate of #2408.

**Comment by mojavelinux** [comment]
>  the include is rendered as a link, rather than an include.

That's because you haven't set the safe mode. See https://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

**Comment by liljenstolpe** [comment]
Thank's @mojavelinux I've got both working now, and weighed in on [#2408](https://github.com/asciidoctor/asciidoctor/issues/2408).  I'm closing this now.  Sorry for missing it in the docs.
