### ISSUE TITLE
Admonitions, callouts and syntax highlighting not rendered in html

### ISSUE THREAD

**Issue by knzudgt** [asciidoctor/asciidoctor#3666]
I am on a Ubuntu 14.04 LTS machine.
I just installed asciidoctor and chose to use `Guard` + `Epiphany` web browser for live preview.
So I created an empty Guardfile in the same directory as my `my_doc.adoc` document, and filled in it with the following content, as suggested in the documentation:

```ruby
require 'asciidoctor'

guard 'shell' do
  watch(/^my_doc\.adoc$/) {|m|
    Asciidoctor.convert_file m[0]
  }
end
```

Live preview works well, but the generated html file does not have any picture or stylesheet so the html document does not render properly graphic elements like admonitions, callouts and syntax code highlighting. My `adoc` document is below:

```asciidoc
:icons: font
:source-highlighter: highlightjs

= Heading Level 1
This is a short presentation on AsciiDoc's core capabilities.

Preview as you type, including formatting like *this* or _this_

It automatically preview as you type

WARNING: You need to install AsciiDoc

[source,ruby]
----
require 'asciidoctor'  # <1>
puts Asciidoctor.convert_file 'mysample.adoc'  # <2>
----

WARNING: Asciidoctor does not work
```

The generated html file is instead:

![Screenshot](https://user-images.githubusercontent.com/15718033/82685949-5165ca00-9c55-11ea-8c9e-d6666da04952.png)

In the directory of my `my_doc.adoc` document there are three files: `my_doc.adoc`, `my_doc.html` and `Guardfile`, nothing else. I uploaded `my_doc.html`, for sake of completeness.

[my_doc.zip](https://github.com/asciidoctor/asciidoctor/files/4669141/my_doc.zip)

I would appreciate any help to solve this issue.

**Comment by mojavelinux** [comment]
You need to add the `safe: :safe` option to the call to `Asciidoctor.convert_file` (offset by a comma). See https://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely
