### ISSUE TITLE
Modify outline (TOC) generation to support leaders/page numbers in web pdf.

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor#3670]
The current TOC/outline list structure is perhaps peculiar, as a sub-list is included as part of the list item it follows rather than being the next item. AFAICT this makes it impossible to use the apparently normal way of simulating leaders in html used in https://www.pagedjs.org/posts/2020-02-19-toc/ and many of the examples in https://stackoverflow.com/questions/2508732/create-leading-dots-in-css, which rely on filling up the li with dots and covering some of them with the <a> and a::after.  I'm suggesting:

- putting the ul sublist inside a separate li
- adding classes to the li to indicate if they are a top-item or a sublist.

This makes all li that contain entries the same structure (having only an <a>) and all li that contain sublists have a simpler structure, containing only one type of element, the ul.

**Comment by mojavelinux** [comment]
I agree we want to move in this direction / accommodate this use case. But we cannot modify the existing HTML5 converter as that would break countless sites. This has to be done in the new semantic HTML5 converter. So add it to the #3418 list.

The reason it is the way it is was to conform to the existing stylesheets written for AsciiDoc Python (back in the day).

Your other option is to extend the converter or use a custom template to override the outline method.

**Comment by lwchkg** [comment]
> Your other option is to extend the converter or use a custom template to override the outline method.

How do I "use a custom template to override the outline method"? Thanks!

**Comment by mojavelinux** [comment]
I don't agree the current structure is peculiar. In fact, it's the most common way of structuring nested lists on the web. It's right there on the MDN page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul If we did it the way you're proposing, each nested list would get a double bullet without the addition of custom styles. I don't think that's right.
