### ISSUE TITLE
InlineAnchorScanRx overrecognising anchors 

### ISSUE THREAD

**Issue by opoudjis** [asciidoctor/asciidoctor#3672]
The regex InlineAnchorScanRx is used to recognise instances of internal anchors, and discover whether they are being repeated.

However, a repeated initial bracket can occur in a macro, e.g. `stem:[[j_1, j_2, ..., j_n\]]`. In that instance the `[[` should not be recognised as an internal anchor.

Currently the regex is defined as 

````
InlineAnchorScanRx = /(?:^|[^\\\[])\[\[([#{CC_ALPHA}_:][#{CC_WORD}\-:.]*)(?:, *(#{CC_ANY}+?))?\]\]|(?:^|[^\\])anchor:([#{CC_ALPHA}_:][#{CC_WORD}\-:.]*)\[(?:\]|(#{CC_ANY}*?[^\\])\])/
````

Something like

````
InlineAnchorScanRx = /(?:^|[^:\\\[])\[\[([#{CC_ALPHA}_:][#{CC_WORD}\-:.]*)(?:, *(#{CC_ANY}+?))?\]\]|(?:^|[^\\])anchor:([#{CC_ALPHA}_:][#{CC_WORD}\-:.]*)\[(?:\]|(#{CC_ANY}*?[^\\])\])/
````

might be enough to address this (disallow colon right before first `\[\[` instance.

**Comment by mojavelinux** [comment]
The scan for inline anchors in intentionally naive until #61 is complete (which is being worked on as part of the AsciiDoc specification). I don't want to add naive workarounds on top of that. It's valid to have a semi-colon before an anchor. The only way to be truly sure it's inside a passthrough element like a stem is to replace them all first, and I don't want to do that.

The correct short term workaround is to add an empty space around the equation inside the macro's contents:

```
stem:[ [j_1, j_2, ..., j_n\]] and stem:[ [j_1, j_2, ..., j_n\]]
```
