### ISSUE TITLE
Reveal JS problem with asciidoctor

### ISSUE THREAD

**Issue by lucki1000** [asciidoctor/asciidoctor#3673]
I don't know if this is the right place for it, I want to use Reveal JS autoslide for a presentation, and would overwrite this function with `:data-autoslide: integer` like it is descript in this [document](https://asciidoctor.cn/docs/asciidoctor-revealjs/#reveal-js-optionst) but it won't change his first value.

```
asciidoctor-revealjs -v 
Asciidoctor reveal.js 4.0.1 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by Mogztter** [comment]
Hello @lucki1000, you should open an issue in the Asciidoctor reveal.js repository: https://github.com/asciidoctor/asciidoctor-reveal.js

To answer your question, I think this feature is not implemented despite the fact that the documentation mentions it. Maybe it was forgotten 😅
I believe that the syntax would be: 

```
[autoslide=15000]
== Slide
````

**Comment by lucki1000** [comment]
> Hello @lucki1000, you should open an issue in the Asciidoctor reveal.js repository: https://github.com/asciidoctor/asciidoctor-reveal.js
> 
> To answer your question, I think this feature is not implemented despite the fact that the documentation mentions it. Maybe it was forgotten sweat_smile
> I believe that the syntax would be:
> 
> ```
> [autoslide=15000]
> == Slide
> ```

Thanks but unfortunately does not work either, i will create the issue there https://github.com/asciidoctor/asciidoctor-reveal.js
