### ISSUE TITLE
qanda: Is it possible to have questions without answer?

### ISSUE THREAD

**Issue by 0x1af** [asciidoctor/asciidoctor#3676]
```
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.

What if every single word document magically turns into asciidoc overnight?::
// No answer 

What is the answer to the Ultimate Question?:: 42
```

Background: I was thinking about using qanda for assignment questions, where usually no answer is given.

Thanks a lot!  :blush:

**Comment by Mogztter** [comment]
Hello @0x1af 

You can maybe use `{empty}` or `{blank}` ?

```
[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.

What if every single word document magically turns into asciidoc overnight?:: {empty}

What is the answer to the Ultimate Question?:: 42
```

![blank](https://user-images.githubusercontent.com/333276/83952005-0becf380-a836-11ea-80dd-9dbc4f8fcfdd.png)

**Comment by mojavelinux** [comment]
@Mogztter is correct.

Unfortunately, this does leave behind an empty `<p>`. It shouldn't be visible, but we probably should eliminate it. If you agree, let's open a separate issue to address that case.

@Mogztter we'll need to think about a cleaner way to have a term without a description in the spec. Something to keep in mind.

**Comment by 0x1af** [comment]
@Mogztter @mojavelinux : Thank you both :fireworks: , this will do nicely for me! 

From my point, the issue can be closed, but I will leave that to @Mogztter

**Comment by mojavelinux** [comment]
We can close this issue. If we want to pursue the other idea I suggested, we'll need new issue.
