### ISSUE TITLE
Support of hjson in code block

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor#3683]
I would be happy to have something like [hjson] support similar to json - https://hjson.github.io

Ideally to point to hjson file as include to the block and see it compile well to html and eventually  pdf.

**Comment by mojavelinux** [comment]
This sounds like a great use case for an extension. This is not something that would be part of the core language, but that's a good thing. See https://github.com/asciidoctor/asciidoctor-extensions-lab for ideas about how to get going.
