### ISSUE TITLE
ordered list:  A custom counter, which is shared across multiple ordered lists

### ISSUE THREAD

**Issue by 0x1af** [asciidoctor/asciidoctor#3686]
**Example:**

```
[counter={counter:qnum:3}]
. Step four
. Step five
. Step six

[counter={counter:qnum}]
. Step seven
. Step eight
. Step nine
```
The counter is incremented for each list item.

**Use case:** I have questions spread across a document (usually always multiple together as a list), and I would like to have them numbered, for easier referencing.

Is something like that already possible somehow?

If not, is this something I could implement as an addon - as it might not be useful to everyone?

A workaround might be to use an unordered list and to hide the bullets, plus adding the counter in front of each item, but I yet have to try that.

**Comment by Mogztter** [comment]
I'm not sure I fully understand what you are asking but it sounds like you want to control the start value of the ordered lists?

If that's the case, then you can use the `start` attribute:

```adoc
[start=4]
. Step four
. Step five
. Step six

[start=7]
. Step seven
. Step eight
. Step nine
```

![olist-start](https://user-images.githubusercontent.com/333276/85227697-4a121780-b3df-11ea-99f1-5565ba172351.png)


Reference: https://asciidoctor.org/docs/user-manual/#numbering-styles


The best medium for questions is probably the Asciidoctor gitter channel at gitter.im/asciidoctor/asciidoctor. If you do have more questions, please feel free to join 😄

**Comment by mojavelinux** [comment]
If there is still a need, please raise this question in the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal (see https://docs.asciidoctor.org/about/get-help/#issue-tracker), but we welcome any and all questions in the chat.
