### ISSUE TITLE
Question: How to cache the default font or CSS?

### ISSUE THREAD

**Issue by ChinaLym** [asciidoctor/asciidoctor#3687]
**Reason**
- Generated pages are slow to load in China mainland since Google font is a Google service.

**Suggestion**
- I'd like to use a switch to control whether cache them to local or use google service.
- I'd like to use a config item to control font or css files link.

**Comment by Mogztter** [comment]
Hello,

> I'd like to use a switch to control whether cache them to local or use google service.

You can use the `webfonts` attribute, see: https://github.com/asciidoctor/asciidoctor.org/issues/410
If you want to use the default stylesheet, you can disable the use of webfonts with `:webfonts!:` and then use a [docinfo file](https://asciidoctor.org/docs/user-manual/#head-docinfo-files) to load the Open Sans, Noto Serif and Droid Sans Mono fonts.

> I'd like to use a config item to control font or css files link.

You can use a custom stylesheet using the `stylesheet` attribute: https://asciidoctor.org/docs/user-manual/#applying-a-theme
The custom stylesheet will replace the default one.

The best medium for questions is probably the Asciidoctor gitter channel at https://gitter.im/asciidoctor/asciidoctor. If you do have more questions, please feel free to join 😄
