### ISSUE TITLE
Question: Plantuml Mindmap Subnode to Asciidoc 

### ISSUE THREAD

**Issue by Aryanam84** [asciidoctor/asciidoctor#3688]
## Description

I have a big mindmap where i like to output just one subnode and include it in my document. 

## Screenshots

Your screenshot.
![grafik](https://user-images.githubusercontent.com/7318459/85295281-fadfeb80-b49f-11ea-9bb0-29c78f59885a.png)

## Syntax example

Plantuml with tag "thought1"
```puml
@startmindmap

+ myThoughts
'tag::thought1[]
++ Thought 1
+++_ Thought 1.1
+++_ Thought 1.2
'end::thought1[]
++ Thought 2
++ Thought 3

@endmindmap
```
I like to output just "thought1"
```adoc
[plantuml,mindmap,png]
----
include::test.puml[tags=thought1]
----
```

is there something possible like "leveloffset=-1"
```adoc
[plantuml,mindmap,png]
----
include::test.puml[tags=thought1,leveloffset=-1]
----
```

**Comment by mojavelinux** [comment]
No, there is not. The AsciiDoc language has no awareness of PlantUML content.

An appropriate solution would be to use a custom include processor. You can find an example in the extensions lab. A custom include processor gives you complete control over resolving, processing, and returning the lines to include. It also has access to attributes defined on the directive. See https://github.com/asciidoctor/asciidoctor-extensions-lab/

**Comment by Aryanam84** [comment]
Thank you for your advise. I solved it just for my actual case like this:

mindmap.puml
```puml
@startmindmap
!$s = "+"
+ myThoughts

!startsub t1
$s+ Thought 1
$s++_ Thought 1.1
$s++_ Thought 1.2
!endsub
++ Thought 2
++ Thought 3

@endmindmap
```

subnode.puml
```puml
@startmindmap
!$s = ""
!includesub mindmap.puml!t1
@endmindmap
```
