### ISSUE TITLE
Footnotes that share the same ID are duplicated

### ISSUE THREAD

**Issue by Nadreck** [asciidoctor/asciidoctor#3690]
According to [Externalizing a Footnote](https://asciidoctor.org/docs/user-manual/#externalizing-a-footnote), you should be able to create a footnote as an attribute, and then call the attribute to be able to reuse a footnote:

> This approach works since attribute references are expanded before footnotes are parsed. The redundant text in the second disclaimer footnote is simply ignored.

However, this does not appear to be working. Using the text from the docs example:
```
:fn-hail-and-rainbow: footnote:[The double hail-and-rainbow level makes my toes tingle.]
:fn-disclaimer: footnote:disclaimer[Opinions are my own.]

The hail-and-rainbow protocol can be initiated at five levels:
double, tertiary, supernumerary, supermassive, and apocalyptic party.{fn-hail-and-rainbow}
A bold statement!{fn-disclaimer}

Another outrageous statement.{fn-disclaimer}
```

The result I get has the first use of fn-disclaimer as footnote 2, and the second use as footnote 3:
>1. The double hail-and-rainbow level makes my toes tingle.
>2. Opinions are my own.
>3. Opinions are my own.

I feel like this used to work. I've tried this in Antora, and also Asciidoctor.js, using the latest LTS for node and npm (12.18.1 and 6.14.5, respectively).

**Comment by mojavelinux** [comment]
I have tried this example in all versions of Asciidoctor and it doesn't work in any version. However, a case could be made that if the ID is specified, and a footnote is already registered with that ID, the parser should not create another footnote (effectively ignoring the text in the second instance, regardless of whether it's the same). So let's address this as a bug.

**Comment by mojavelinux** [comment]
For the record, this has nothing to do with externalizing the footnote (though it's easy to reproduce that way).

**Comment by dflock** [comment]
This still happens if you don't give the footnote and explicit id. If you change `footnote:disclaimer` to `footnote:`, like this:

```
:fn-hail-and-rainbow: footnote:[The double hail-and-rainbow level makes my toes tingle.]
:fn-disclaimer: footnote:[Opinions are my own.]

The hail-and-rainbow protocol can be initiated at five levels:
double, tertiary, supernumerary, supermassive, and apocalyptic party.{fn-hail-and-rainbow}
A bold statement!{fn-disclaimer}

Another outrageous statement.{fn-disclaimer}
```

You get this:

![image](https://user-images.githubusercontent.com/47756/107909269-ab599e80-6f0c-11eb-84fc-987238c6f3cd.png)

Using 2.0.12:

```
asciidoctor --version
Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by elextr** [comment]
The `disclaimer` ID is what tells Asciidoctor that these two reference the same footnote.  When a footnote does not have an ID its considered a different footnote, doesn't matter if the text is the same.

**Comment by mojavelinux** [comment]
Yep.
