### ISSUE TITLE
Document header attributes only work under title heading when single '=' is used

### ISSUE THREAD

**Issue by nuket** [asciidoctor/asciidoctor#3692]
Hi,

This relates to the docs at https://asciidoctor.org/docs/user-manual/#doc-header

I've traditionally put document-header attributes under the title heading, all of the examples do this.

_However_, they will be parsed in by Asciidoctor _only_ if the title is marked as a '=' top-level heading.

This works:

```
= OK
:app-name: Test
```

If you mark the title as '==' or any lower heading, _it will not pull in any doc header attributes after the title_.

This does not work:

```
== Not OK
:app-name: Test
```

This works again:

```
:app-name: Test
== OK Again
```

* So, either there's a bug here where doc-header attributes should be pulled in from the block following the title heading in a document, regardless of what level it is.

* Or, the documentation should suggest that users always pass doc-header attributes as the first lines in a document, before specifying the title heading.

This tripped me up for a few hours.

**Comment by mojavelinux** [comment]
I'm not sure why you are confuse by this. The document header attributes either need to go directly under the document title or, if there is no document title, at the very top of the document. There is no context for putting them underneath a other section title. If you feel the documentation can be rephrased, feel free to suggest a revision.

**Comment by nuket** [comment]
It was confusing that after changing the heading in a file from '=' to '==' 
that the header attributes completely disappeared. Basically means that all 
documents need to have a title.


In my case I had a number of different files with '==' headings. I could 
switch them all to '=' headers and use leveloffset when including them in 
an aggregating document, but I simply expected a standalone file starting 
with an '==' heading to keep all of its header attributes when being 
rendered standalone by the html5 backend.

**Comment by mojavelinux** [comment]
> Basically means that all
documents need to have a title.

No, that is not true. The attribute entries just need to be at the top of the document in that case.

>  I simply expected a standalone file starting
with an '==' heading to keep all of its header attributes when being
rendered standalone by the html5 backend.

A file that begins with a `==` heading is not a document header!

**Comment by mojavelinux** [comment]
I will make sure the documentation states where the header attributes need to be when the document has no doctitle.

**Comment by mojavelinux** [comment]
I have updated the documentation to make it as clear as I can. See https://asciidoctor.org/docs/user-manual/#doc-header
