### ISSUE TITLE
Indentation issues in description lists with tagged regions

### ISSUE THREAD

**Issue by lcawl** [asciidoctor/asciidoctor#3693]
While playing with description lists, I noticed that the first item in the list is often indented improperly (i.e. not indented).

Here's a simple example involving a glossary of terms:
````
= Link test

:doctype:           book

== Glossary

L::

[[glossary-leader-index]] leader index:::
+
--
include::test-glossary.asciidoc[tag=leader-index-def]
--

[[glossary-local-cluster]] local cluster:::
+
--
include::test-glossary.asciidoc[tag=local-cluster-def]
--

M::

microwave:::
Test

muffin:::
Test
````

The two terms that use tagged regions are pulling them from a file that contains content like this:

````
[[glossary-leader-index]] leader index ::  
// tag::leader-index-def[]
My definition for leader index.
// end::leader-index-def[]

[[glossary-local-cluster]] local cluster ::
// tag::local-cluster-def[]
My definition for local cluster.
// end::local-cluster-def[]
````

When I build this page (e.g. `asciidoctor test.asciidoc -D output/docs`), you can see that the "leader index" description is not indented properly:

![image](https://user-images.githubusercontent.com/26471269/85789922-4256b980-b6e4-11ea-9fcd-16b8d69cc4f6.png)

It seems to consistently be a problem only for the first item in the list. When I inspect the output, it seems to show that the `<dd>` is missing as follows:

````
<dl>
--
  | <dt class="hdlist1">L</dt>
  | <dd>
  | <div class="dlist">
  | <dl>
  | <dt class="hdlist1"><a id="glossary-leader-index"></a> leader index</dt>
  | </dl>
  | </div>
  | <div class="openblock">
  | <div class="content">
  | <div class="paragraph">
  | <p>My definition for leader index.</p>
  | </div>
  | </div>
  | </div>
  | <div class="dlist">
  | <dl>
  | <dt class="hdlist1"><a id="glossary-local-cluster"></a> local cluster</dt>
  | <dd>
  | <div class="openblock">
  | <div class="content">
  | <div class="paragraph">
  | <p>My definition for local cluster.</p>
  | </div>
  | </div>
  | </div>
  | </dd>
  | </dl>
  | </div>
  | </dd>
````

I can work around the problem by omitting the continuation character from the first entry in each list. For example:
````
L::

[[glossary-leader-index]] leader index:::
include::test-glossary.asciidoc[tag=leader-index-def]

[[glossary-local-cluster]] local cluster:::
+
--
include::test-glossary.asciidoc[tag=local-cluster-def]
--

````

But that work-around falls apart when there happen to be more than one paragraph in the tagged region.  For example:

![image](https://user-images.githubusercontent.com/26471269/85790891-da08d780-b6e5-11ea-8d40-0cfcd2b3dfa4.png)

**Comment by mojavelinux** [comment]
The includes are a red herring here. This happens even without them. The problem seems to be the empty line after the terms in the outermost list:

```
L::

leader index:::
+
--
My definition for leader index.
--

local cluster:::
+
--
My definition for local cluster.
--

M::

microwave:::
Test

muffin:::
Test
```

If those lines are removed, it behaves as expected:

```
L::
leader index:::
+
--
My definition for leader index.
--

local cluster:::
+
--
My definition for local cluster.
--

M::
microwave:::
Test

muffin:::
Test
```

The expectation is that those empty lines between nested lists don't matter. I'll try to track down why this is happening.
