### ISSUE TITLE
Allow fallback source highlighters

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/asciidoctor#3697]
AsciiDoc allows only one source highlighter to be specified in the document header. The problem is that there is no source highlighter that works with *all* AsciiDoctor implementations.

I commonly preview AsciiDoc files using AsciiDoctor.js, then convert them using Asciidoctor PDF. No matter which source highlighter I specify in the header, one of my tools will always fail to perform syntax highlighting.

I realize that the AsciiDoctor CLI tools allow me to override the `source-highlighter` attribute. However, I mostly use graphical tools that use AsciiDoctor under the hood, so I'm not in a position to change the way they invoke AsciiDoctor.

What I need is a form of fallback mechanism: a way to specify a prioritized list of source highlighters. An AsciiDoctor implementation could then use the first highlighter it supports.

**Comment by mojavelinux** [comment]
If you want a fallback mechanism, you're free to implement one using a custom adapter. You can then publish this as an Asciidoctor extension if you want others to be able to benefit from it.

See https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/

Adding this capability in core is out of scope.
