### ISSUE TITLE
Use Hugo page variables inside literal block

### ISSUE THREAD

**Issue by xexio** [asciidoctor/asciidoctor#3705]
There's a way to use the Hugo page variables inside a literal block?

I have this in the header of the document:

```
---
title: Page test
author: me
email: me@me.com
orgname:  myself
---
```
And I have this in the body:
```
[source,bash]
....
# test {{% param orgname %}}
....
```
But this renders as:
```
# test {{% param orgname %}}
```
instead of:
```
# test myself
```

**Comment by mojavelinux** [comment]
This feature request belongs in Hugo rather than in Asciidoctor as it pertains to the integration (Asciidoctor core cannot know about Hugo). This integration enhancement can be achieved using an extension such as a tree processor.

**Comment by xexio** [comment]
Thanks for your quick reply @mojavelinux. But I made another test and this example works well. I'm going to close this issue and open another related to this. My fault.
