### ISSUE TITLE
Use Hugo shortcodes in files imported with include function

### ISSUE THREAD

**Issue by xexio** [asciidoctor/asciidoctor#3706]
There's a way to use the Hugo shortcodes inside files that I imported with the include function?

I have two files, _fileOne.adoc_ and _fileTwo.adoc_

In the file _fileOne.adoc_ I have this:

```
include::fileTwo.adoc[]
```
And in the _fileTwo.adoc_ I have this:
```
---
title: Page test
author: me
email: me@me.com
orgname:  myself
---
.
.
.
[source,bash]
....
# test {{% param orgname %}}
....
```
But this renders as:
```
# test {{% param orgname %}}
```
instead of:
```
# test myself
```
I understand that this is not directly related to AsciiDoctor. But, is there any way to fix it using some extension?

**Comment by mojavelinux** [comment]
Again, not in this project. This is an integration issue and belongs in
Hugo. The code in Hugo can leverage Asciidoctor extensions to influence the
processing.
