### ISSUE TITLE
Markup language of parts, help with extension, BlockProcessor

### ISSUE THREAD

**Issue by helmsaccess** [asciidoctor/asciidoctor#3716]
Hello, everyone,

since it is currently not possible to mark up blocks and inline elements with a specific language (HTML attribute "lang") and thus the criterion [3.1.2 Language of Parts](https://www.w3.org/TR/WCAG21/#language-of-parts) of the W3C Content Accessibility Guidelines (WCAG) 2.1 cannot be fulfilled, I am currently developing a workaround based on an extension.
For inline elements I succeeded with an inline macro:

```
class InlineLanguage < Asciidoctor::Extensions::InlineMacroProcessor
  use_dsl
  named :lang
  parse_content_as :text

  def process parent, target, attrs
    lang = target
    text = attrs['text']
    return %(<span lang="#{lang}">#{text}</span>)
  end
end
```

For block elements like open blocks and the different lists this is not succeeded.
My current BlockProcessor is curiously only executed for
Paragraphs and open blocks. Since I can't get the create_block method to work, I can currently
only supplement the language markup of paragraphs.
Maybe you have an idea how I can expand my BlockProcessor to work with open blocks and all list types supported?

```
class BlockLanguage < Asciidoctor::Extensions::BlockProcessor
  use_dsl
  named :lang
  on_contexts [:paragraph, :open, :quote, :ulist, :olist, :colist, :dlist]

  def process parent, reader, attrs
    lang = attrs[2]
    lines = [%(<span lang="#{lang}">)]
    lines.concat reader.lines
    lines.push '</span>'
    attrs['subs'] = 'quotes,attributes,replacements,macros,post_replacements'
    #create_block parent, attrs['cloaked-context'], lines, attrs
    if attrs['cloaked-context'] == :paragraph
      create_paragraph parent, lines, attrs
    end
  end
end
```

Currently I'm using the Asciidoctor version 2.0.11.dev (GitHub master branch) with Ruby 2.7.

**Comment by mojavelinux** [comment]
Please direct usage questions to the `#users` stream of the community chat at https://asciidoctor.zulipchat.com.
