### ISSUE TITLE
Generate toc from different files

### ISSUE THREAD

**Issue by xexio** [asciidoctor/asciidoctor#3720]
There's a way to generate a toc from different files without using the include function?

I'm going to explain what I'm looking for.

I have three different files: **file1.adoc**, **file2.adoc** and **file3.adoc**

In the **file1.adoc** I have something like this:

````
= Title of the book

[abstract]
This is the introduction....

:toc: << But this toc take the list from the files file2.adoc and file3.adoc
````

In the **file2.adoc** I have something like this:

````
== Section 1
This is the section 1...
````

In the **file3.adoc** I have something like this:

````
== Section 2
This is the section 2....
````

And I can't use the include function in **file1.adoc** because I don't want to include the content of the other two files.

**Comment by mojavelinux** [comment]
This seems to be the same question as #3735. Let's continue the discussion there.
