### ISSUE TITLE
Horizontal Table Header

### ISSUE THREAD

**Issue by blueray453** [asciidoctor/asciidoctor#3721]
My current table is like:

```
[cols="3*",options="header,footer,autowidth"]
|===
|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2

|Cell in column 1, row 3
|Cell in column 2, row 3
|Cell in column 3, row 3
|===
```

I want to make column 1 the header, instead of row 1. How can I do that?

**Comment by Mogztter** [comment]
Hello @blueray453 

You can apply an header style on a column:


```adoc
[cols="1h,2*",footer,autowidth"]
|===
|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2

|Cell in column 1, row 3
|Cell in column 2, row 3
|Cell in column 3, row 3
|===
```

![table](https://user-images.githubusercontent.com/333276/88275946-7f5f9d00-ccde-11ea-8b73-58c36ae06c0c.png)

https://asciidoctor.org/docs/user-manual/#cols-format

**Comment by blueray453** [comment]
Thank you very much

**Comment by blueray453** [comment]
Just one more question.

The documentation says

> To horizontally center the content in all of the columns, add the ^ operator after the multiplier.
> 
> ```
> [cols="3*^"]
> |===
> |Cell in column 1, row 1
> |Cell in column 2, row 1
> |Cell in column 3, row 1
> 
> |Cell in column 1, row 2
> |Cell in column 2, row 2
> |Cell in column 3, row 2
> |===
> ```
> 

How do we horizontally center the content in all of the columns when our table looks like:

```
[cols="1h,2*",footer,autowidth"]
|===
|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2

|Cell in column 1, row 3
|Cell in column 2, row 3
|Cell in column 3, row 3
|===
```
I mean where do we put `^` in `cols="1h,2*"` so that it affects all the columns.

**Comment by Mogztter** [comment]
@blueray453 the order is (apparently) important so the syntax is:

```
[cols="^1h,2*^",footer,autowidth"]
```

**Comment by blueray453** [comment]
Thank you very much.
