### ISSUE TITLE
issue with passing attributs to tags in a include file

### ISSUE THREAD

**Issue by ludwigmair** [asciidoctor/asciidoctor#3723]
Hi,

in my case i find out that to pass a attribute (located in a config.adoc) to a tag (located in a _tags.adoc) is not working.

config.adoc
`:version-m2if: 3.8.0`

_tags.adoc
`// tag::m2if-welcome-attention-note[]
[[section-m2if-attention-info]]

[CAUTION]
====
As of version `{version-m2if}`, the structure of the setup has changed considerably, and the previous configuration files are no longer be used.

To avoid complex adjustments of the configuration, version `{version-m2if}` merged the configuration for all entities into one but dedicated
overwriting of individual settings is now possible, e. g. for the log level.
====
`
welcome.adoc
`[[section-welcome]]

== Welcome

include::_tags.adoc[tag=m2if-welcome-attention-note]
`

is there any possibility to that?

i appreciate any help

best regards
Ludwig

**Comment by Mogztter** [comment]
@ludwigmair could you please reformat the description? Use three backticks to create a code block: `` ``` ``.

**_tags.adoc**
```
// tag::m2if-welcome-attention-note

// ...
```

**Comment by mojavelinux** [comment]
You need to include `config.adoc` somewhere in order to attributes that it defines.

In the future, please direct usage questions to the `#users` stream of the community chat at https://asciidoctor.zulipchat.com. You'll find that you will get more timely responses that way.
