### ISSUE TITLE
How to control indentation of code blocks for DocBook -> Word (docx)?

### ISSUE THREAD

**Issue by mmatrosov** [asciidoctor/asciidoctor#3730]
I convert AsciiDoc to Word via DocBook. The db->docx conversion is done with Pandoc.

I provide a reference file with --reference-doc to Pandoc. I specified indentation for the Body Text style in the reference file. Now the text is indented. But source code is not.

![image](https://user-images.githubusercontent.com/3617951/89923004-8f490d80-dc08-11ea-8165-2881141fde75.png)

Is it possible to carry some information about indentation to DocBook and to Word? E.g. by explicitly specifying a style Word should use? Seems like Pandoc can import a style: https://groups.google.com/g/pandoc-discuss/c/jzwKbGjIQCs/m/8w_sipTZAwAJ

**Comment by mojavelinux** [comment]
This is a pandoc issue. There's nothing the AsciiDoc processor (in this case Asciidoctor) can do once the DocBook file is made. Perhaps you could add a role to the code block that would be later interpreted. That's about all I can suggestion.

This type of question is better suited for the mailing list (https://discuss.asciidoctor.org) or the chat channel (https://gitter.im/asciidoctor/asciidoctor). The issue tracker should be used for requests to change the processor in a concrete way, either to fix a bug or add a missing feature.
