### ISSUE TITLE
Callouts not rendered in html

### ISSUE THREAD

**Issue by knzudgt** [asciidoctor/asciidoctor#3731]
My Ubuntu 18.04 LTS machine is running `Asciidoctor 2.0.10`, and I use Guard + Epiphany web browser for live preview.
I created an empty Guardfile in the same directory as my `my_doc.adoc` document, and filled in it with the following content:

```ruby
require 'asciidoctor'

guard 'shell' do
  watch(/^.*\.adoc$/) {|m|
    Asciidoctor.convert_file m[0], safe: :safe
  }
end
```
I tried to use callouts, as reported in the following extract of my adoc document, however I am not getting the expected callout number bubbles:

```asciidoc
:icons: font
:source-highlighter: highlightjs
:sectanchors:
:highlightjs-theme: default
:toc: left

|===
| *Host* | *Type* | *Destination*
| * | AAAA | IPV6 address
| * | A | IPV4 address
| @ | AAAA | IPV6 address
| @ | A | IPV4 address
| www | CNAME | @
| @ | TXT | sendinblue spf record <1>
| @ | TXT | sendinblue-code:... <2>
| mail_domainkey | TXT | k=rsa;... <3>
| _dmarc | TXT | sendinblue dmarc record <4>
|===
```
As you can see below from my screenshot, I am not getting the numbered bubbles in the last four lines of the table:

![Screenshot from 2020-08-11 18-19-27](https://user-images.githubusercontent.com/15718033/89924075-cb2ca480-dc01-11ea-8a80-2b96828d2e19.png)

Any help would be appreciated

**Comment by mojavelinux** [comment]
This is not a valid location for callout numbers. The callout numbers can be used at the end of a line in a verbatim block such as source, listing, or literal.

If you want to include callout numbers in other locations, you need to enable them on the block. For example:

```
| @ | TXT a|
[subs=+callouts]
sendinblue spf record <1>
```

Notice the addition of the "a" to the start of the cell and the block attribute line.
