### ISSUE TITLE
Cannot override xrefstyle per xref

### ISSUE THREAD

**Issue by akhayyat** [asciidoctor/asciidoctor#3733]
According to #2365, it should now be possible to override `xrefstyle` per cross reference.

According to the associated commit (6f16adaab7487fbfe61a2d21ab364366839786fe), the syntax for doing that is:

    xref:#_foo[xrefstyle=short]

Using Asciidoctor 2.0.10, I tried the following forms:

1. `xref:#_foo[xrefstyle=full]`
2. `xref:_foo[xrefstyle=full] `
3. `xref:_foo[xrefstyle="full"]`

none of which produced the desired effect, which is to override the `xrefstyle` to become `full` for this particular reference. Instead, they all produce a link whose text is `xrefstyle=full` or `xrefstyle="full"`.

**Comment by mojavelinux** [comment]
If you're seeing an unprocessed attribute in the output, that's an indication you are not actually using Asciidoctor 2.0.10. (This has been a feature since Asciidoctor 1.5.7). Please verify your version and try again.

**Comment by akhayyat** [comment]
I created a MWE, and now I'm seeing different behavior.

`test.adoc`:

```asciidoc
= Title
:xrefstyle: full

== Section 1

This is section 1.

== Section 2

This is a reference to <<_section_1>>.
```

Running:
```bash
» asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
» asciidocter test.adoc
```

Results in the default refstyle, as if the `xrefstyle` attribute is not used.

Using the command:

    » asciidoctor -a xrefstyle=full test.adoc

does not change anything.

The resulting HTML contains this line, confirming the Asciidoctor version:

    <meta name="generator" content="Asciidoctor 2.0.10">

On a positive note, when using the alternative macro syntax (`xref:_section_1[xrefstyle=full]`), the attribute text is no longer rendered in the output, but it still has no effect (same output as described above).

**Comment by mojavelinux** [comment]
In your first example, the xrefstyle doesn't have any affect because section numbering is not enabled. You'll need to run this command to see the impact:

```
asciidoctor -a xrefstyle=full -a sectnums test.adoc
```

Then the reference will appear as:

```
Section 1, “Section 1”
```

You can change how this appears using `xref:_section_1[xrefstyle=short]`.

```
Section 1
```

Because of how you named your sections, that looks exact the same as `xrefstyle=basic`. If you change the section title, you'll see it still appears as "Section 1".

**Comment by mojavelinux** [comment]
What is an MWE?

**Comment by akhayyat** [comment]
Thank you for the fast reply, and for catching what was breaking the example.

MWE is Minimal Working Example.

I updated my sample document to:

```asciidoc
= Title

== First Section

This is section 1.

== Second Section

This is a reference to xref:_first_section[xrefstyle=full].

This is a reference to <<_first_section>>.
```
Now, running:

    » asciidoctor -a sectnums test.adoc

does actually work as expected: the first reference uses the full style, and the second uses the default style.

However, on another larger document, the `xref:_foo[xrefstyle=full]` syntax still results in a correct hyperlink with the link text being the string `xrefstyle=full`. I get this with no in-document attributes, and with the same command used above:

    » asciidoctor -a sectnums document.adoc

The generated HTML also has the line:

    <meta name="generator" content="Asciidoctor 2.0.10">

Is there anything else that could interfere with the `xref:_foo[xrefstyle=X]` syntax?

BTW, the command line attribute `-a xrefstyle=full` does change the reference styles, but I'm unable to use the `xref:_foo[xrefstyle=X]` syntax to override the reference style of a specific reference.

**Comment by akhayyat** [comment]
Good news! It turns out the issue was the document title syntax. I was using the form:

```asciidoc
Document Title
==============
```
which seems to disable some Asciidoctor features. Once I changed it to:
```asciidoc
= Document Title
```
The `xrefstyle` attribute worked as expected.

I recall seeing somewhere in the docs something about the effect of the title syntax, but I cannot find it anymore. Is this still captured by current documentation?

**Comment by mojavelinux** [comment]
Ah yes. That is exactly correct. When you use the setext (two-line) syntax for the document title, it implicitly puts the document into AsciiDoc Python compat mode. This disables many of the features that Asciidoctor has introduced, including xrefstyle.

See https://asciidoctor.org/docs/migration/#compat-mode for details.

It's possible to turn off compat mode either by using the atx syntax for the document title, or unsetting the `compat-mode` attribute.
