### ISSUE TITLE
Syntax highlighting - Improper use of Lexer#lex warning

### ISSUE THREAD

**Issue by dregad** [asciidoctor/asciidoctor#3734]
This is related to #3336, but since it that was closed over a year ago and my case seems slightly different, I thought it would be appropriate to open a separate issue. Feel free to close if not.

Using AsciiDoctor 2.0.10 with Rouge 3.22.0 for syntax highlighting, I'm getting the following error:
_Improper use of Lexer#lex - this method does not receive options. This will become an error in a future version._
Code is properly highlighted as expected, despite the warning.

The snippet below allows reproduction
```adoc
:source-highlighter: rouge
:source-language: php

[source]
....
echo 'hello world';
....
```

Interestingly, I don't get the warning if I 
- use another language (e.g. _ruby_) in the header `:source-language: ruby` 
- override the language at block level `[source,ruby]`, .
- don't specify a language in the header

    ```adoc
    :source-highlighter: rouge
    
    [source,php]
    ....
    echo 'hello world';
    ....
    ```

**Comment by mojavelinux** [comment]
This is a known issue with 2.0.10 and has been resolved in master. The fix will be available in the 2.0.11 release.

**Comment by dregad** [comment]
Thanks for the feedback. Is there any ETA for 2.0.11 ?

**Comment by mojavelinux** [comment]
I'm trying to get it out asap, but that is limited by my availability. Getting the AsciiDoc spec process started has been taking a lot of my time.
