### ISSUE TITLE
How to passthrough within a reference label?

### ISSUE THREAD

**Issue by il86be** [asciidoctor/asciidoctor#3747]
According to the user guide [1], the special characters can be escaped with pass-through constructions, such as  ++ and pass:c[].
None of them appear to work inside the label text of a reference, at least not in HTML mode.
Here is an example:

`I am referring to <<myref>> and <<another>>.`

`== References`

`+[1]+ [[myref,+[1]+]] _Asciidoctor User Manual._ Section 40.1 _Passthrough Macros_, https://asciidoctor.org/docs/user-manual/#passthroughs, Checked on2020-09-02. `
`+[2]+ [[another,pass:c[[2\]]]] _Another attempt_.`

When I generate PDF with Docbook back end, the text looks as it should be:
> I am referring to [1] and [2].

But in HTML it contains some garbage:
> I am referring to +[1]+, pass:c[[2

Am I missing something?
What is the proper way to specify an reference label that contains special characters?
Thank you.

**Comment by mojavelinux** [comment]
What you are trying to achieve can be accomplished using a bibliography. Use this instead:

```adoc
I am referring to <<myref>> and <<another>>.

[bibliography]
== References

* [[[myref,1]]] _Asciidoctor User Manual._ Section 40.1 _Passthrough Macros_, https://asciidoctor.org/docs/user-manual/#passthroughs, Checked on 2020-09-02.
* [[[another,2]]] _Another attempt_.
```

This will give you the desired output:

```text
I am referring to [1] and [2].
```
