### ISSUE TITLE
How to set `image-rendering` to `pixelated`?

### ISSUE THREAD

**Issue by Ziriax** [asciidoctor/asciidoctor#3750]
First of all, thanks a lot for asciidoctor, it is amazing!

I'm writing a doc with pixel art images, so I would like to [disable pixel interpolation when scaling images](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering).

In CSS this can be done with the `image-rendering` property.

Is this supported in asciidoc(tor)?

Thanks,
Peter

**Comment by mojavelinux** [comment]
You can add this declaration in a custom stylesheet or by appending extra styles using docinfo. See https://asciidoctor.org/docs/user-manual/#applying-a-stylesheet and https://asciidoctor.org/docs/user-manual/#docinfo-file.

If you feel this is something that should be set by the default stylesheet, please suggest where that addition should be made.

**Comment by Ziriax** [comment]
Thanks. 

I guess some other trick will be needed when rendering to PDF?

**Comment by mojavelinux** [comment]
I have no idea how that would apply for PDF or what it would even mean. It
might be relevant for asciidoctor-web-pdf (which uses CSS), but for
Asciidoctor PDF, there's no such switch or setting that I know of.

**Comment by Ziriax** [comment]
I think then the best option would be to pre-scale the images, so they are huge, but compression would make them small anyway. Thanks for the feedback.
