### ISSUE TITLE
toc positioning wrt to content in default css

### ISSUE THREAD

**Issue by frankieliu** [asciidoctor/asciidoctor#3751]
I have been staring at asciidoctor.css for a while trying to figure out how it achieves the position of both of these elements:
the toc with respect to the content.

This is what I know:

For toc-right there is an extra padding-right: 15em,
This is compared with at toc-left which defaults to body.toc2 which has a padding-left: 15em

But I have been trying to figure out how the toc2 and content are positioned with respect to one another to achieve the nice effect of one followed by the other.   For example the toc element comes before content (in both cases), so that when the window becomes small enough, the toc pops to the top of the content (nice desirable effect).  But I was wondering what makes toc-right show to the right of the content div (conversely for toc-left).  And what sets the min window width threshold at which the toc pops to the top of the content.

I looked for different ways of achieving vertical split in css, but they all rely on some for of 'grid' like split of the horizontal space, but I don't think this is happening here, sorry for the newbie question.  The closest that comes to this is using a float or a inline-block, both techniques not being used in asciidoctor.css.  If you can point out to me how this is done, or can recommend some post/reference to how this is accomplished that would be greatly appreciated.

Thanks in advance.

**Comment by mojavelinux** [comment]
Please ask questions like this either on the mailing list (https://discuss.asciidoctor.org) or the chat channel (https://gitter.im/asciidoctor/asciidoctor). This helps us manage the project better. The issue tracker should be reserved for confirmed bugs and feature requests. Thanks!

**Comment by frankieliu** [comment]
Thanks!  I was looking for such forum(s) but couldn't find them.
