### ISSUE TITLE
Numeric HTML entities outside the Basic Multilingual Plane aren't supported

### ISSUE THREAD

**Issue by peyremorgan** [asciidoctor/asciidoctor#3754]
Example input : `&#x1F61B;`
Expected output : `😛`
Actual output : `&#x1F61B;`

**Comment by peyremorgan** [comment]
Okay, nevermind. Tested with `master`, can't reproduce the issue. My ancient v1.5.4 was the problem.

**Comment by mojavelinux** [comment]
The regular expression allows a decimal code up to 6 characters (`\d\d\d{0,4}`) and a hexadecimal code up to 5 characters (`[\da-f][\da-f][\da-f]{0,3}`). So what you have entered will work fine.

**Comment by peyremorgan** [comment]
Okay, nevermind. Tested with `master`, can't reproduce the issue. My ancient v1.5.4 was the problem.

**Comment by mojavelinux** [comment]
Yep, it used to be more limited.
