### ISSUE TITLE
Dynamic boilerplate text

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/asciidoctor#3758]
I'm working on a document that will be published in two ways:

1. as an HTML document in a folder structure with other HTML documents, including generated API documentation
2. as a standalone PDF document.

There are many places in my document where I want to reference the API documentation.

* If the output format is HTML, I can place a (relative) deep link into the API documentation, allowing the reader to jump from my document directly to the specific API doc topic.
* If the output format is PDF, I can't add such a direct link. Instead, I just add a cross reference to an appendix that lists further resources.

A typical example looks like this:

```adoc
A `Duration` represents a fixed (and calendar-independent) length of time.
ifdef::backend-pdf[See its API documentation (see <<appendix-other-docs>>)]
ifndef::backend-pdf[See its link:../api/classes/duration.html[API documentation]]
for details on how it differs from `Period`.
```

This works, but makes the source text a bit hard to read. Also, the structure of these preprocessor directives is always identical, just the link changes.

I'd love to extract this block to some kind of parameterized boilerplate text, the parameter being a suffix to the target URL. But unless I'm missing something, neither attributes nor includes allow parameters. What's the best approach to a situation like this?

**Comment by mojavelinux** [comment]
The solution is to use attribute references in an include file, include it using the include directive, and change the attribute values around the include directive. In other words:

```
:url-api-link: See its link:../api/classes/duration.html[API documentation]
ifdef::backend-pdf[:url-api-link: See its API documentation (see <<appendix-other-docs>>)]
include::_duration.adoc[]
```

Then the template can replace the ifdef logic with `{url-api-link}`.

With that said, this is really the best you can do with plain AsciiDoc when you need this kind of switch. However, there is a better alternative, which is an apiref inline macro. That can hide all the details of how to make the link to the API reference so no logic needs to be present in the AsciiDoc source itself.

If you need further help or clarification, please ask in the project chat https://chat.asciidoctor.org.
