### ISSUE TITLE
Don't highlight monospaced phrase in verse block when using highlight.js

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3761]
A monospaced phrase in a verse block matches the selector `pre code`, which is used by highlight.js to match tags to highlight. This selector should be more specific so that these phrases are not inadvertently matched. This will require use of a customize init function for highlight.js.

Example:

```
:source-language: highlight.js

[verse]
____
`puts 1`
____
```

**Comment by mojavelinux** [comment]
@Mogztter This may also affect the browser extension. If so, have you applied this change there too?

**Comment by Mogztter** [comment]
We are not using the `initHighlighting` function but the following code (which I believe is roughly equivalent to what you are doing):

https://github.com/asciidoctor/asciidoctor-browser-extension/blob/124369bc8d09e1d86f1b6d29118b162c93c12c31/app/js/renderer.js#L254-L261

**Comment by mojavelinux** [comment]
Perfect! Thanks for confirming.
