### ISSUE TITLE
Natively Compiled Implementation 

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor#3771]
Is it possible to have a natively compiled compliant implementation of Asciidoctor in a natively compiled language like C/C++ or Rust or Go or Nim?

**Comment by mojavelinux** [comment]
I encourage you to follow the AsciiDoc Language Specification project (currently through https://accounts.eclipse.org/mailing-list/asciidoc-wg), as having multiple implementations is a primary goal. This is not a concern of the Asciidoctor project.
