### ISSUE TITLE
Asciidoc not processes in variables

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctor#3773]
Hi,

In my doc I use very often this call to action text (an icon + a formatted text):

`icon:hand-o-right[role="red", size=2x] [red big]#Call to action#`

Because I use it very often and needed to change the colour of the icon, I thought "why not refactor and use a variable": 

```
:call-to-action: icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

{call-to-action}
```

But when I invoke the `{call-to-action}` variable, the icon is displayed (so it shows that the `icon` macro is processed), but the text `[red big]#Call to action#` is displayed as it is, without being processed. I tried to play with the different [substitutions](https://asciidoctor.org/docs/user-manual/#inline-pass-macro-and-explicit-substitutions) but didn't work out.

Do you now why the icon is processed but not the text ? Is there a way to process the entire thing ?

Thanks

**Comment by mojavelinux** [comment]
Generally speaking, this is not what attributes were designed to do. It's possible, but you should still use caution. Attributes are more about values, not markup.

That said, you can accomplish this by forcing substitutions to be applied to the attribute value at assignment time. Then the attribute reference will emit the right value (so it is not affected by substitution order). See https://asciidoctor.org/docs/user-manual/#altering-attribute-entry-substitutions

This type of question is more appropriate for the chat channel at https://gitter.im/asciidoctor/asciidoctor.

**Comment by agoncal** [comment]
Thanks to @mojavelinux I finally got it right. The idea is to use the `pass` macro and use the right substitutions[1]: `m` for macro (so, it `icon` macro) and `q` for the text. The result is:

```
:call-to-action: pass:m,q[icon:hand-o-right[role="red", size=2x] [red big]#Call to action#]
```

I had a second problem though. As I am building my documents with Maven, I was setting this into a variable:

```
<call-to-action>pass:m,q[icon:hand-o-right[role="red", size=2x] [red big]#Call to action#]</call-to-action>
```

This **does not work** because it is essentially API attributes that are used as is, with no substitutions. So you need to set it into your document, not in your `pom.xml`.

[1] https://asciidoctor.org/docs/user-manual/#inline-pass-macro-and-explicit-substitutions
