### ISSUE TITLE
Table Cell reading direction from top to bottom first instead of from left to right

### ISSUE THREAD

**Issue by ElWomSa** [asciidoctor/asciidoctor#3774]
Hi all, maybe someone can give me a short answer on this. I looked in the Asciidcotor documentation and googled a lot but didn't find anything:

I'm having a table with 2 columns ordered with values in the second column from highest to lowest. So like:
 | signal 	| value	| 
|---	|------	|
| x 	| 27,2 	| 
| q 	| 19,2 	|
| b 	| 15,1 	| 
| d 	| 14,9 	|  

When I add these two columns in a book type pdf but actually into 4-columned table (to save  some space in the document), I'm getting a table with reading direction from left to right, top to bottom:
 | signal 	| value	|  signal 	| value	| 
|---	|------	|---	|------	|
| x 	| 27,2 	| q 	| 19,2 	|
| b 	| 15,1 	| d 	| 14,9 	|

But actually I want to have this with a reading direction from top to bottom at first (and then left to right). Like:
 | signal 	| value	|  signal 	| value	| 
|---	|------	|---	|------	|
| x 	| 27,2 	| b 	| 15,1 	|   	|
| q 	| 19,2 	| d 	| 14,9 	|   	|

How to achieve this? Thanks in advance

Right now I use this code to insert my table:

```
[cols="<1,<1,<1,<1", frame=topbot, grid=rows, stripes=none, options="header", title="xxx"]
|===
|Signal |value |Signal |value
content
|===
```

**Comment by mojavelinux** [comment]
AsciiDoc tables are defined row-wise. Therefore, you have to define your rows in a way that gives you the reading direction you want. In other words:

```

|===
| signal | value | signal | value

| x
| 27,2
| b
| 15,1

| q
| 19,2
| d
| 14,9
|===
```

Another option would be to define a custom block that reads in raw data and produces a table for you.

**Comment by mojavelinux** [comment]
Please reopen if you have additional questions.
