### ISSUE TITLE
support Pikchr for diagram generation 

### ISSUE THREAD

**Issue by linsong** [asciidoctor/asciidoctor#3775]
First of all, I love Asciidoctor very much and use it for most of my documents, thanks for the great work! 

Recently I found a tool named [Pikchr](https://pikchr.org/home/doc/trunk/homepage.md), it is pretty good at generating diagram(svg format) from PIC-like markup language. More examples [here](https://pikchr.org/home/doc/trunk/doc/examples.md). If it can be supported in Asciidoctor, that will be great.

**Comment by Mogztter** [comment]
Hello @linsong 
You should take a look at https://github.com/asciidoctor/asciidoctor-diagram

This extension supports Pikchr diagrams. As a prerequisite, you will need to install the `pikchr` binary on your machine (and make it available in your `PATH`).

Then, you can use the following syntax:
```
[pikchr]
....
scale = 1.0
eh = 0.5cm
ew = 0.2cm
ed = 2 * eh
er = 0.4cm
lws = 4.0cm
lwm = lws + er
lwl = lwm + er

ellipse height eh width ew
L1: line width lwl from last ellipse.n
line width lwm from last ellipse.s
LV: line height eh down

move right er down ed from last ellipse.n
ellipse height eh width ew
L3: line width lws right from last ellipse.n to LV.end then down eh right ew
line width lwm right from last ellipse.s then to LV.start

move right er down ed from last ellipse.n
ellipse height eh width ew
line width lwl right from last ellipse.n then to L1.end
line width lwl right from last ellipse.s then up eh
....
```

**Comment by linsong** [comment]
Hi @Mogztter, 

  Sorry, I just checked the [diagram document page](https://asciidoctor.org/docs/asciidoctor-diagram/) but not the asciidoctor-diagram git repo before. This is awesome and I find some more tools about diagrams. 

  I will close this issue now, thanks for your time.

**Comment by Mogztter** [comment]
Oh, you're right, this page is outdated!
I've opened the following pull request to fetch the latest version of the Asciidoctor Diagram documentation: https://github.com/asciidoctor/asciidoctor.org/pull/974
