### ISSUE TITLE
The syntax highlighting package for Sublime Text appears to be unmaintained

### ISSUE THREAD

**Issue by jwillikers** [asciidoctor/asciidoctor#3776]
I use Sublime Text to edit Asciidoctor every single day.
The official syntax highlighting package provided by the Asciidoctor organization has not received any updates in 5 years, see [this issue](https://github.com/asciidoctor/sublimetext-asciidoc/issues/19).
I have created my issue in this repository in the hope that it will get a response, which doesn't seem very likely in the package's own repository.

The syntax highlighter still contains irritating bugs and it would great to see this fixed.
Does the project need find a new maintainer?
There are a couple of forks with recent activity, so perhaps someone would be willing to maintain the project.
I'd even consider stepping up to do that since I find the plugin so helpful each day.

**Comment by mojavelinux** [comment]
You'd need to take this up with that repository / project. This is not something that pertains to core. It's a package contributed by the community. Apart from that, the focus of this community right now is on IntelliJ, Atom, and VS Code.

It does sound like the project needs a new maintainer. (I'm not even sure it had one originally. It was merely a contribution.) The best way to find a new maintainer is to either volunteer yourself or encourage someone you know who has the time to do it.

**Comment by mojavelinux** [comment]
You could also ask on https://discuss.asciidoctor.org or https://gitter.im/asciidoctor/asciidoctor.

**Comment by jwillikers** [comment]
@mojavelinux Got it, I'll make sure to follow up in those places. Thanks for taking the time to respond to my issue, that was quite helpful!
