### ISSUE TITLE
Wrong `document.options[:to_dir]` when setting `--out-file` (:to_file) and `--destination-dir` (:to_dir) to absolute paths

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor#3778]
I am still figuring out the problem, but I could reduce it down to these combinations.
* Windows 10
* asciidoctor + asciidoctor-diagram
* Setting and absolute `--out-file` and any `--destination-dir`

It seems to me the issue is not related to asciidoctor-diagram, but it is through it that I could reproduce it.
Under those conditions the diagram image generation fails with the message 

```
asciidoctor: ERROR: index.adoc: line 3: Failed to generate image: Invalid argument @ dir_s_mkdir - C:/Users/user/asciidoctor/issue_diagrams/dest_dir/C:
```
If I add a "puts" to print the return of the `document.options[key]` in `doc_option` method https://github.com/asciidoctor/asciidoctor-diagram/blob/fd8ab7d9eb9d5de3c55a0e27c4276206c728a917/lib/asciidoctor-diagram/diagram_processor.rb#L317 I get these

```
C:/Users/user/asciidoctor/issue_diagrams/dest_dir/C:/Users/user/asciidoctor/issue_diagram/custom1
```

_env_
asciidoctor 2.0.10
asciidoctor-diagram 2.0.5
ruby 2.7.1p83

**To reproduce**
Create project with these 2 files

index.adoc
```adoc
= Demo Document

plantuml::demo.puml[]

```
demo.puml
````
@startuml

A->B

@enduml
````

And run with
```
asciidoctor -r asciidoctor-diagram -o "C:\$PATH_TO FILE\custom\custom.html" -D dest_dir index.ado
```

The whole history can be seen here 👉  https://github.com/asciidoctor/asciidoctor-diagram/issues/298.

**Comment by mojavelinux** [comment]
This is a known issue / restriction. The output file, output dir, and base_dir values must be written as a posix path on Widnows (meaning it must use forward slashes). Otherwise, Asciidoctor will not recognize it as an absolute path.

I will look into whether we can loosen this restriction.

**Comment by mojavelinux** [comment]
I think you are also asking it to do something which is invalid. You're setting the the destination dir to a location which is not the parent of the out file. The destination dir must be the directory of the out file (and thus not necessary to set explicitly if you set the out file).

**Comment by mojavelinux** [comment]
For the record, the same issue occurs on Linux. If :to_dir (the destination directory) and :to_file (out file) do not agree, the :to_dir option on the document is the directory of :to_file plus the destination directory as entered. In other words, the input is invalid, so the result is invalid. This is an incorrect use of the API / CLI.

**Comment by abelsromero** [comment]
Sorry, I was simplifying the case, bad idea on my side.

Full case comes from the maven-plugin where all paths are made absolute, there we have:
* to_dir -> C:/Users/user/asciidoctor/issue_diagrams/dest_dir/
* to_file -> C:/Users/user/asciidoctor/issue_diagrams/dest_dir/my-file.html
Also we run in usafe.

That should work I understand?

**Comment by mojavelinux** [comment]
I'm investigating.

**Comment by mojavelinux** [comment]
This does seem like a bug, though it has nothing to do with Windows. If both :to_file and :to_dir are set, the value of :to_dir is wrong.

**Comment by mojavelinux** [comment]
PR sent.

**Comment by abelsromero** [comment]
Awesome! I will generate a local Asciidoctorj with the master versionto run a full test later.

**Comment by abelsromero** [comment]
It worked in the full maven-plugin build 🥳

**Comment by mojavelinux** [comment]
Thanks for testing!!
