### ISSUE TITLE
Table of Contents disapears is there is an empty line between version details and settings

### ISSUE THREAD

**Issue by auslavs** [asciidoctor/asciidoctor#3779]
The below code shows a Table of Contents as you would expect.

**TOC rendered as expected**
```
= Title
Author
v1.0, 2014-01-01
:organization: Company Name
:doctype: book
:icons: font
:listing-caption: Listing
:sectnums:
:toc:

== Heading

Paragraph
```

However, if there is an empty line before the :toc: instruction, the table of contents does not render.
It does not appear to matter where the empty line is.

**No TOC rendered, newline before :icons:**
```
= Title
Author
v1.0, 2014-01-01
:organization: Company Name
:doctype: book

:icons: font
:listing-caption: Listing
:sectnums:
:toc:

== Heading

Paragraph
```

I have tested using Asciidoctor 2.0.10, with the vs-code extension and asciidoctor-pdf

**Comment by elextr** [comment]
The toc attribute has to be set in the command line or header, but a blank line ends the header so the second won't work.

**Comment by auslavs** [comment]
Thanks, I did not realise the header was a specific thing with certain requirements 🤦‍♂️
I thought it was just a handy spot to put document attributes.

**Comment by mojavelinux** [comment]
> I did not realise the header was a specific thing with certain requirements

This is described with big bold text here: https://asciidoctor.org/docs/user-manual/#doc-header
