### ISSUE TITLE
Items from attributes-fr not rendered

### ISSUE THREAD

**Issue by boydkelly** [asciidoctor/asciidoctor#3783]
It seems at least some items from locale/attributres-fr are not rendered,  for example the toc-title.

Witth the following doc:

`= Toc test
:lang: fr
:toc:
  
include::locale/attributes.adoc[]

== Niveau 1
=== Niveau 2

.Example
[width="80%",cols="2",frame="topbot",options="header,footer",stripe="even"]
|====
|This is a only a test| Voici un test seulement
|====
`

The table is correctly translated as "tableau", but the toc-title is not rendered in french.

This occurs with:

`[bkelly@toolbox pages]$ asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
`
and also asciidoctor.js plugin for chrome browser has the same issue.

(Also notice in Antora the "Contents" on the right side panel is not translated.   This must be another string.   Should it not also be translated somewhere?)

![Screenshot from 2020-10-18 21-46-12](https://user-images.githubusercontent.com/3412972/96386677-2fcd2800-118c-11eb-816f-6c5da42f1e54.png)

**Comment by mojavelinux** [comment]
You have put a blank line before the include, which pushes the attributes out of the document header. When this happens, they will not be used. See https://asciidoctor.org/docs/user-manual/#doc-header
