### ISSUE TITLE
A space in the end of inline code

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3789]
Not sure a bug (actually, two of them) or not

```
foo `.{sp}`
```

```
foo `.{sp}` (a period followed by a space)
```

In the first example, the space will be trimmed.

In the second example, there will be no space between a code and an opening parenthesis.

Replacing `{sp}` with `{nbsp}` is not always an option.

**Comment by mojavelinux** [comment]
What you're observing is browser behavior. Here's what Asciidoctor produces:

```html
<div class="paragraph">
<p>foo <code>. </code></p>
</div>
<div class="paragraph">
<p>foo <code>. </code> (a period followed by a space)</p>
</div>
```

Therefore, there's nothing Asciidoctor can do about this. It's a browser quirk/bug. You'll need to find another way to represent the character (see http://www.fileformat.info/info/unicode/category/Zs/list.htm).

**Comment by mojavelinux** [comment]
You can also solve this using CSS. You can append the following to your stylesheet:

```css
code {
  white-space: pre-wrap;
}
```

or more specifically:

```css
:not(pre) > code {
  white-space: pre-wrap;
}
```

That has other side effects, but if those are tolerable for you, then you can rely on this solution.

**Comment by mojavelinux** [comment]
We do have support for the built-in nowrap role on a monospaced phrase. That wouldn't help you here, but we could consider adding support for the built-in prewrap (or perhaps just pre) role.

```
[.prewrap]`.{sp}`
```

(You could also add this role to your own stylesheet).
