### ISSUE TITLE
Unable to style sidebar block with attributes

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/asciidoctor#3796]
I want to use the sidebar block to create a sidebar in the magazine sense, a block of text set aside by a border that appears on the side of the main text. However, the current sidebar block cannot accomplish this as written, it's assumed to extend the width of the page.

I was able to mock up what I wanted to achieve with an inline CSS style, and I created the following example. (_Locally, I use a style on `.sidebarblock` instead of a CSS ID. I chose the ID to create a side by side comparison._)

This issue is a request to support sidebar configuration via block attributes and have them styled with themes instead.

```asciidoc
++++
<style>
#styled_sidebar {
  width: 35%;
  float: right;
  margin-left: 1.5em;
}
</style>
++++

****
Current sidebar implementation
****

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa eget egestas purus viverra accumsan in. Ac ut consequat semper viverra nam. Et ultrices neque ornare aenean. Arcu ac tortor dignissim convallis. Aliquam faucibus purus in massa tempor nec feugiat. Auctor elit sed vulputate mi sit. Vivamus at augue eget arcu dictum varius duis at consectetur. Eget lorem dolor sed viverra. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Lectus urna duis convallis convallis tellus. Sit amet nisl purus in mollis nunc. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Vitae tortor condimentum lacinia quis. Tellus elementum sagittis vitae et leo. Urna nec tincidunt praesent semper feugiat. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Velit aliquet sagittis id consectetur purus ut faucibus.

[id='styled_sidebar']
****
Sidebar with inline styling
****

Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Feugiat in fermentum posuere urna nec. Rhoncus
aenean vel elit scelerisque mauris pellentesque pulvinar. Morbi tristique senectus et netus et malesuada. Laoreet
suspendisse interdum consectetur libero id faucibus nisl. Amet commodo nulla facilisi nullam vehicula ipsum a arcu
cursus. Convallis convallis tellus id interdum velit. Aliquam malesuada bibendum arcu vitae elementum curabitur.
Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Varius quam quisque id diam vel. Ac felis donec et odio
pellentesque diam. Volutpat diam ut venenatis tellus in metus vulputate eu. Nunc sed id semper risus.
```
That produces the following output with `asciidoctor test.adoc`:

<img width="1003" alt="test-adoc-rendering" src="https://user-images.githubusercontent.com/96451/97492386-15801080-1929-11eb-9f29-615d35ff79c6.png">

**Comment by mojavelinux** [comment]
Using CSS is never going to be possible with this converter (as stated here: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#language-overview). That's because this converter does not use a browser engine. It, therefore, cannot apply CSS and it also cannot float elements.

If you want to be able to restrict the width of a block, we could certainly consider supporting a width defined either on the block or in the theme file. But it would still be stacked vertically.

If you do want to be able to use HTML+CSS and get a PDF out of it, then I recommend evaluating Asciidoctor Web PDF, which does use the browser stack. See https://github.com/mogztter/asciidoctor-web-pdf

**Comment by neontapir** [comment]
That's fair. I included the CSS more as a way to illustrate what I wanted to achieve. I'd have to do some digging to see other ways it could be accomplished.

**Comment by mojavelinux** [comment]
Everything that is possible to theme is described in the theming guide. We can always consider adding support for extra properties. We would need a dedicated issue for each proposal.

What the converter definitely cannot do is float blocks (at least not in any sort of general purpose way). There's just no concept of that in the PDF generator that this converter uses. If you extend the converter, it's possible to use the low-level bounds operations to sort of fake it, or perhaps use a columnar layout. But it would likely be very content specific.
