### ISSUE TITLE
automatically wrap code in a readable manner

### ISSUE THREAD

**Issue by ericzolf** [asciidoctor/asciidoctor#3820]
Asciidoc was able to automatically wrap code with some goodies to still keep the code readable. I found an old rendered PDF and it looked like this:

![image](https://user-images.githubusercontent.com/3105685/97878102-72f7d100-1d1e-11eb-8ddd-87af41501c7a.png)

Notice:
* the end of the broken line is marked with an arrow
* subsequent lines have a hanging indentation (I'd slightly prefer them to be right aligned, but it's really optional)

It would be really nice to have this feature also in asciidoctor, where I couldn't find anything related. Thanks!

**Comment by mojavelinux** [comment]
I'm not sure what code you're referring to. If you are talking about the AsciiDoc source itself, this is not a feature of AsciiDoc, but rather of your code editor. A code editor can soft wrap lines, show an indicator where the wrap occurs, and intent subsequent lines. None of this has to do with how AsciiDoc is processed.

**Comment by ericzolf** [comment]
I meant code in my documentation, more correctly "listing blocks". They currently can be either wrapped or non-wrapped, non-wrapped doesn't always work (especially not in PDFs), and wraped makes the code/listing not very readable resp. can lead to confusion, hence the idea to have a nicer/clearer way to wrap lines. Asciidoc was able to do it, AFAICJ asciidoctor can't do it, and that's what I'd like to have.

To give an example, I'd have something like:

```asciidoctor
---
## the required sizing depends on the current and constantly growing of each software repository.
---
```

which would be rendered like in the description of this issue.

Is this clearer?

**Comment by mojavelinux** [comment]
In that case, wrapping of lines is handled by either the browser for HTML or by the PDF generator for PDF. Asciidoctor PDF already supports wrapping of lines (though not with an indentation). But that's a separate project. If you want to do it in the browser, you can use additional CSS.

Btw, you can control whether wrapping is enabled or not for a block using the nowrap option (it will wrap by default). https://asciidoctor.org/docs/user-manual/#to-wrap-or-to-scroll

The CSS for wrapping verbatim blocks in the default stylesheet is already exceptional complex (since we have to consider the styling provided by the syntax highlighters as well). So I'd rather this enhancement be something you do in your own stylesheet.

**Comment by mojavelinux** [comment]
> Asciidoc was able to automatically wrap code with some goodies to still keep the code readable.

Please cite a reference. I am not aware that AsciiDoc Python had any such feature.

**Comment by elextr** [comment]
I recall seeing something like that, it was probably part of the Docbook/Latex toolchain somewhere.

**Comment by mojavelinux** [comment]
Thanks for that insight, @elextr.

In that case, the feature is still available with Asciidoctor, assuming that you generate DocBook and use the DocBook toolchain to enable it...somewhere ;)

**Comment by ericzolf** [comment]
The screenshot from the issue's description comes from an old PDF rendered with asciidoc six years ago.

Let me try to scrap some more information (I don't have the toolchain installed anymore):

* the (wanted) behavior appears in PDF, not in HTML (where I care less, scrolling is always an option, not on paper)
* nevertheless the rendered HTML tells me that I was using 'AsciiDoc 8.6.9' in October 2014
* the PDF rendering was done AFAICJ with `a2x -f pdf -L xyz.adoc` (just for sake of completeness, the HTML rendering was done with `asciidoc -b html5 -a icons -a toc2 -a theme='flask' -a max-width='1920px' xyz.adoc`)

**Comment by mojavelinux** [comment]
`a2x -f pdf` tells me it was made using dblatex. You can still use that toolchain today.

```
asciidoctor -b docbook doc.adoc
a2x -f pdf -L doc.xml
```

(a2x accepts DocBook as input, bypassing the use of the AsciiDoc parser in AsciiDoc Python).

**Comment by ericzolf** [comment]
Our comments crossed each other: couldn't this be made a feature of asciidoctor-pdf? (I'll try your approach, sounds at least like a workaround)

**Comment by mojavelinux** [comment]
> couldn't this be made a feature of asciidoctor-pdf

Perhaps, though you'd need to propose it there. I don't have time to work on something like that at the moment, but someone else may be interested in giving it a shot.

**Comment by ericzolf** [comment]
Fair enough, I've lived 6 years without this feature, I'll survive a little longer without it (but I'm missing it though :cry: ). Closing after I've create a copy in asciidoctor-pdf.

**Comment by mojavelinux** [comment]
Thanks for reposting the issue there.
