### ISSUE TITLE
asciimath stem block doesn't do new lines

### ISSUE THREAD

**Issue by SpyrosRoum** [asciidoctor/asciidoctor#3859]
Hello, I tried to write an asciimath stem block like this:
```
[asciimath]
++++
V_(p-p) = 0,5 * 50 * 10^(-3) = 0,025V \
V_p = (0,025) / 2 = 0,0125V
++++
```
But this was all one line.
I read through #2497 and also tried to leave a blank line between the two but that didn't do anything either. 

Any help would be appreciated!

**Comment by mojavelinux** [comment]
What you have entered is correct. Please make sure you are using Asciidoctor 2.0.12.

**Comment by SpyrosRoum** [comment]
```
$ asciidoctor-pdf -v
Asciidoctor PDF 1.5.3 using Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]) (lc:US-ASCII fs:US-ASCII in:US-ASCII ex:US-ASCII)
```

I am trying to get a pdf but generating html directly from asciidoctor produces a single line as well

**Comment by gemmaro** [comment]
Excuse me for interrupting. For HTML output by Asciidoctor, I was able to write a multi-line formula as follows.

```adoc
:stem: asciimath

.If the decimal point is a period
[stem]
++++
{: ( V_(p-p) , = 0.5 * 50 * 10^(-3) , = 0.025V )
 , ( V_p     , = (0.025) / 2        , = 0.0125V )
 :}
++++

.If the decimal point is a comma. (I'm not sure whether this is the correct way or not.)
[stem]
++++
{: ( V_(p-p) , = "0,5" * 50 * 10^(-3) , = "0,025"V )
 , ( V_p     , = ("0,025") / 2        , = "0,0125"V )
 :}
++++
```

![Screenshot_2020-11-23 Untitled](https://user-images.githubusercontent.com/29575029/99922870-22e8b900-2d76-11eb-839a-fbb714dad129.png)

Commas are special characters and need to be escaped.

Asciidoctor version is:

```
$ asciidoctor -v
Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

I haven't tested yet, but does this work work with Asciidoctor PDF?

## Reference

* http://asciimath.org/ -> Syntax -> Special Cases -> "Matrices can be used for layout..."

**Comment by SpyrosRoum** [comment]
Replacing commas for dots and adding the whole `{: (..) , (..) :}` syntax seems to have done the trick. 

Using only `\` to break the line still didn't work though so I wonder why that may be and if it is documented somewhere and I just missed it

**Comment by gemmaro** [comment]
I'm sorry.... I didn't read #2497 carefully; I didn't know that the Asciidoctor syntax supports multi-line expressions.
Actually, when I tried the AsciiDoc document at the beginning (using only `\` to break line), it generated a multi-line formula in my environment successfully. I don't know the cause now...

**Comment by SpyrosRoum** [comment]
Yeah it *should have* worked..
In any case, your solution works for now so thanks for that.

I'll leave this open because we might have a potential bug? Unless I'm missing something somewhere else but I'm not sure what it could be

**Comment by mojavelinux** [comment]
If you are asking about Asciidoctor PDF, then that's not an issue with this repository. You must be using Asciidoctor Mathematical, and that is then an issue for that project.

The correct syntax is as follows:

```
[asciimath]
++++
V_(p-p) = 0,5 * 50 * 10^(-3) = 0,025V \
V_p = (0,025) / 2 = 0,0125V
++++
```

Just as you wrote it original. If that does not work, file the issue with Asciidoctor Mathematical. (Asciidoctor PDF does not do STEM processing).

**Comment by mojavelinux** [comment]
> For HTML output by Asciidoctor, I was able to write a multi-line formula as follows...

Support for hard lines breaks in AsciiMath when using the HTML converter was added in 1.5.7 and further refined in 2.0.11. A simple `\` at the end of the line does the trick. This is a tested feature, so I'm confident it works.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctor-mathematical/issues/91

**Comment by SpyrosRoum** [comment]
You are once again correct. 
It was failing to generate correct html for me earlier because I run `asciidoctor -r asciidoctor-mathematical erg.adoc`. 
I'll follow the issue over on mathematical

**Comment by mojavelinux** [comment]
That's good to hear. I look forward to discussing there. I may have time this week to add a patch. I'm first waiting for other PRs I submitted to be merged so that I can start with a clean slate.
