### ISSUE TITLE
Autolink is a bit too permissive

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor#3864]
For instance, something like:

```
`https://github.com/<user>/<project>/`
```
raises three issues

* is a url without the trailing `[]` supposed to be converted
* This is not a real URL so converting is undesirable
* Even if we let it converted, the conversion has a bug which does not handle the < and > entities correctly and produces invalid xhtml code.

**Comment by jnavila** [comment]
See https://github.com/progit/progit2/pull/1564#

**Comment by mojavelinux** [comment]
Autolinks are always going to be difficult to get right in all cases. If what you want is literal monospace, then you should be using the literal monospace syntax:

```
`+https://github.com/<user>/<project>/+`
```

> is a url without the trailing [] supposed to be converted

Yes, an AsciiDoc processor will convert a bare URL wherever normal substitutions (specifically the macro substitution) are enabled. Normal substitutions are enabled in monospace phrases.

> This is not a real URL so converting is undesirable

Then use literal monospace (or escape the URL using a backslash)

> Even if we let it converted, the conversion has a bug which does not handle the < and > entities correctly and produces invalid xhtml code.

The processor does not attempt to correct invalid URLs. You cannot have < and > in a URL unless they are URL encoded.

**Comment by jnavila** [comment]
Thank you for this reply. I was more or less expecting it. This is just a surprise for writers migrating from previous syntax/semantics.

**Comment by mojavelinux** [comment]
I agree, it is different. But a very important difference to understand. We will work to improve the documentation for literal monospace in the new docs site and alert writers to that difference.
