### ISSUE TITLE
Subtitle not rendering properly

### ISSUE THREAD

**Issue by 8thHalfHour** [asciidoctor/asciidoctor#3873]
The subtitle in my document is not rendering properly, and I am unsure how to fix the problem. Here is what I have in my header:

```
= Libraries and Frameworks: Make Use of gRPC
Bob Smith <bsmith@example.com>
```

The result I get:

# Title: Subheading

What I expect:

# Title
## Subheading

I am going nuts trying to figure out what's going on. No stylesheets or external resources are being used.

**Comment by mojavelinux** [comment]
The subtitle is only supported in the DocBook backend.

**Comment by mojavelinux** [comment]
See #2749.

**Comment by 8thHalfHour** [comment]
Aha, thanks. Perhaps this should be explained in the docs? I could not find any caveats about this issue there, just that it would work. So, from that other thread, I see that only three types currently support the subtitle feature. Good to know. Please update the docs when you can; I one of the few maybe that really needs manuals and sees them as a source of truth. I love asciidoctor, and I appreciate you responding to me so quickly!

**Comment by mojavelinux** [comment]
The user manual does state that subtitle partitioning is not supported by the HTML converter. https://asciidoctor.org/docs/user-manual/#subtitle-partitioning The new docs (soon to be released) state in clearer terms, though I think I'll revise it to be even more clear.
