### ISSUE TITLE
Add option to preserve leading and trailing blank lines when pushing AsciiDoc content onto the reader using push_include

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor#3875]
Asciidoctor 2.0.12 introduce a severe regression due to https://github.com/asciidoctor/asciidoctor/issues/3470

---
Given this setup:

```
docs
├── content
│   ├── chapter01.adoc
│   ├── chapter02.adoc
│   └── chapter03.adoc
└── document.adoc
```

`document.adoc` content:

```adoc
= My book

include::content/chapter01.adoc[]
include::content/chapter02.adoc[]
include::content/chapter03.adoc[]

This is the end.
```

`content/chapter01.adoc` content:

```adoc

== chapter 1

Lorem ipsum

* lorem
* ipsum

```

`content/chapter02.adoc` content:

```adoc

== chapter 2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

```

`content/chapter03.adoc` content:

```adoc

== chapter 3

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

* Duis aute irure dolor in reprehenderit 
* Voluptate velit esse cillum dolore
* Eu fugiat nulla pariatur.

```

I test it with gradle and asciidoctorj:

```gradle
plugins {
    id 'org.asciidoctor.convert' version '2.4.0'
}

asciidoctorj {
    version = '2.4.2'
}

asciidoctor {
    sourceDir = file('docs')
    sources {
        include 'document.adoc'
    }     
    outputDir = file('build/generated-docs')
    repositories {
        mavenCentral()
    }
}
```

---

This setup correspond to the tips given by @aalmiray :

<img width="635" alt="Tips_4" src="https://user-images.githubusercontent.com/1222165/100993663-f98a1300-3555-11eb-8131-7459ab28c482.png">

Video recording: https://youtu.be/8PuIeBn8Qg4?t=487

---

With `2.0.12` and the new trim of blank line the created document is broken:

<img width="1039" alt="Output with Asciidoctor 2.0.12" src="https://user-images.githubusercontent.com/1222165/100994598-0a875400-3557-11eb-9bd5-4c0f40feffbe.png">

With asciidoctorj `2.4.1` (using Asciidoctor `2.0.10` internally) it was working:

<img width="1028" alt="Output with Asciidoctor 2.0.10" src="https://user-images.githubusercontent.com/1222165/100994612-0f4c0800-3557-11eb-8b65-1d4313f2486e.png">

---

As explained in https://github.com/asciidoctor/asciidoctorj/issues/978, this is causing me trouble in my project.

---

The workaround is to add a comment line at the top of the included document:

`content/chapter01.adoc` content:

```adoc
// chapter01 start

== chapter 1

Lorem ipsum

* lorem
* ipsum

```

`content/chapter02.adoc` content:

```adoc
// chapter02 start

== chapter 2

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

```

`content/chapter03.adoc` content:

```adoc
// chapter03 start

== chapter 3

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

* Duis aute irure dolor in reprehenderit 
* Voluptate velit esse cillum dolore
* Eu fugiat nulla pariatur.

```

**Comment by mojavelinux** [comment]
I updated the title to better reflect the situation.

> Asciidoctor 2.0.12 introduce a severe regression due to #3470

It's important to note that this is not a regression. The code is working as designed. Asciidoctor 2.0.11 just happened to fix a bug that was allowing undocumented behavior.

When including AsciiDoc content using push_include, leading and trailing blank lines are removed. But there are cases when this is undesirable. So we need a way to control whether it happens or not using an option. It may be that when using push_include from an extension, this behavior is automatically disabled (because we can assume the lines have already been condensed).

**Comment by mojavelinux** [comment]
> The code is working as designed. Asciidoctor 2.0.11 just happened to fix a bug that was allowing undocumented behavior.

To be fair, the behavior has toggled back and forth over a variety of releases. A more accurate statement is that the behavior was never well defined. So let's focus on making it so and documenting it.

**Comment by mojavelinux** [comment]
After further assessment, I've determined that the change is, in fact, a regression. I have reopened this as #3997, which will address this problem universally.
