### ISSUE TITLE
Unexpected 'possible invalid reference' log entry when referencing an anchor defined in a description list

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor#3879]
Given this snippet:

```adoc
== Title

Links: <<lorem, lorem>>, <<ipsum, ipsum>>

CPU:: [[lorem]] The brain of the computer.
Hard drive:: 
    [[ipsum]] Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
```

That is combining:

* [22. Description List](https://asciidoctor.org/docs/user-manual/#description-list)
* [27.2. Defining an Anchor](https://asciidoctor.org/docs/user-manual/#anchordef) 

Those log entries are generated by Asciidoctor:
```
Dec 08, 2020 7:21:02 AM uri:classloader:/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: lorem
Dec 08, 2020 7:21:02 AM uri:classloader:/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: ipsum
```

**Comment by mojavelinux** [comment]
This is the expected behavior when debug/verbose mode is enabled (meaning the logging level is set to DEBUG). The parser cannot validate these xrefs, so it flags them as potentially invalid.

The correct place for the anchor (given the current state of the parser) is at the start of the term.

```text
Links: <<lorem, lorem>>, <<ipsum, ipsum>>

[[lorem]]CPU:: The brain of the computer.
[[ipsum]]Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
```

It's also more logical to reference the term than the description.

**Comment by kadang** [comment]
> The correct place for the anchor (given the current state of the parser) is at the start of the term.
That _kind of_ contradicts the docs, doesn't it? In [27.2 Defining an Anchor](https://asciidoctor.org/docs/user-manual/#anchordef), it says:
> For example, you would not put an anchor in front of a list item 
And the example has the caption "**Wrong position** for an anchor ID in front of a list item" (emphasis mine).

I agree that it's more logical to reference the term, but that's not what the docs tell me to do.

**Comment by mojavelinux** [comment]
> For example, you would not put an anchor in front of a list item

That's a true statement. But we're not talking about a list item in this case. We are talking about a definition list item (not the same). The correct location for an anchor on a definition list item is in front of the term. (Here's the test case: https://github.com/asciidoctor/asciidoctor/blob/6dca7bc0502ed32d85696b5805737c2b1ceab2c3/test/lists_test.rb#L2465). However, the documentation does not provide an example for this particular case. I'll follow up on that.
