### ISSUE TITLE
Enable `:chapter-label:` along with `attributes-uk.adoc`

### ISSUE THREAD

**Issue by Harmyder** [asciidoctor/asciidoctor#3887]
Inclusion of `attributes-uk.adoc` undoes `:chapter-label:` effect

```asciidoc
:doctype: book
:numbered:
:chapter-label:

include::/usr/share/ruby-asciidoctor/locale/attributes-uk.adoc[]
```

produces:

![image](https://user-images.githubusercontent.com/9980064/102918324-b59f7500-4454-11eb-8d5d-24e5a5f60463.png)

**Comment by mojavelinux** [comment]
I notice two problems. First, chapter-label is deprecated. The name of the attribute is now chapter-signifier. (See https://github.com/asciidoctor/asciidoctor/blob/master/data/locale/attributes-uk.adoc#L5). Second, you have a blank line in front of the include, which means the attributes are not defined in the document header. You need to remove this line.
