### ISSUE TITLE
Formatting escapes in section titles in the man page output are being malformed by the uppercase transform

### ISSUE THREAD

**Issue by boutil** [asciidoctor/asciidoctor#3892]
Hi,

I am relaying a bug report we had in Debian about conversion to manpage with asciidoctor.
These have been found when processing some manuals of linux-perf packages.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972842

Dear Maintainer,

  I found defects in some manuals in the linux-perf-5.[89] packages.

1) Wrong escape, '\F' (which means the font family)

perf_5.9-data.1:.SH "OPTIONS FOR \FICONVERT\FP"
perf_5.9-sched.1:.SH "OPTIONS FOR \FIPERF SCHED MAP\FP"
perf_5.9-sched.1:.SH "OPTIONS FOR \FIPERF SCHED TIMEHIST\FP"

 '\F' must be '\f'.

  So the text should first be capitalized and
then the straight quotes ('...') be changed to "\fI...\fP".

( It could be better
a) to keep the text in lower case with just the
sentence starting with a capital;
or
b) not to capitalize the whole text.)

  The source lines are:

OPTIONS for 'convert'

OPTIONS for 'perf sched map'

OPTIONS for 'perf sched timehist'

2) Trailing space with the .URL macro

perf_5.9-diff.1:.URL "file://filename" "" " "

perf_5.9-report.1:.URL "file://filename" "" " "

perf_5.9-script.1:.URL "file://filename" "" " "

  These are made from the text line:

file://filename entries.

  The third argument of ".URL" should be empty
as there is no punctuation mark attached to the web address.

**Comment by mojavelinux** [comment]
If split off the second issue as #4004.

In the future, please file each problem as a separate issue.

**Comment by mojavelinux** [comment]
> not to capitalize the whole text

This is done for conformance with the man page output of the DocBook toolchain and is a common practice for formatting man pages in general. If you want to propose a setting to control this behavior, please do so using a separate issue.
