### ISSUE TITLE
:sectnums: being rendered as text if it comes at the top of an included file

### ISSUE THREAD

**Issue by bzbarsky-apple** [asciidoctor/asciidoctor#3905]
Consider the following situation.  I have `main.adoc` that looks like this:
```
include::one.adoc[]
include::two.adoc[]
```
`one.adoc` looks like this:
```
== First Doc

First doc text
```
and `two.adoc` looks like this:
```
:sectnums:

== Second Doc

Second doc text.
```
When I run `asciidoctor -b html main.adoc` I get `main.html` that looks like this:
```
....
<div class="sect1">
<h2 id="_first_doc">First Doc</h2>
<div class="sectionbody">
<div class="paragraph">
<p>First doc text
:sectnums:</p>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_second_doc">Second Doc</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Second doc text.</p>
...
```
with the `:sectnums:` as part of the rendered text and no section number on the "Second Doc" section, which is not the intent.

If I add a blank line at the top of `two.adoc`, before the `:sectnums:` line, then I get the expected behavior: a section number on "Second Doc" and no rendered `:sectnums:` text....

**Comment by mojavelinux** [comment]
The solution is to put a blank line between the include directives, not inside the included file.

The behavior of the processor changed in attempt to fix the opposite of this problem, where blank lines at the top of the file were being interpreted as significant. We're considering a partial rollback. See #3875.

**Comment by bzbarsky-apple** [comment]
Note that I'm on 2.0.10, so not suffering from the issue #3875 describes.  But OK, understood: must have a blank line before every include.

**Comment by mojavelinux** [comment]
Indeed, you should because it communicates an indent that what you are including are separate sections. When you cram them together, it communicates that you don't want space between the content, which you might use inside a listing block for example.
