### ISSUE TITLE
Using data-uri with an image macro to display a PDF only shows a empty

### ISSUE THREAD

**Issue by bobbradley** [asciidoctor/asciidoctor#3906]
If I have :data-uri: at the beginning of the document then use the image macro to display a PDF file, it shows an empty square instead of the image. I'm using it like this:

image::MyImage.pdf[]

If I remove :data-uri: from the file then it displays the PDF.

Note: I'm using the default HTML output with the asciidoctor tool, not asciidoctr-pdf.

**Comment by mojavelinux** [comment]
The HTML converter does not support embedding a PDF (and I can't see how that makes any sense). You'll need to convert it to an image file (or files).

**Comment by bobbradley** [comment]
It's using the image macro with a PDF because the PDFs have some vector portions that scale/print nicely along with some bitmap portions. If we convert to another image format like png or jpg, we lose that scaling ability and it's much larger.

It looks like at least tries to embed the PDF since I see this:
```
<img src="data:image/pdf;base64,JVBER
... more Base64 text ...
 alt="MyImage">
```
But it doesn't seem to display correctly. Maybe it's a browser issue with data URLs and PDF? I tried Chrome and Safari.

**Comment by bobbradley** [comment]
I experimented a little and if I use the old asciidoc tool, it seems to work. The output is a little different though. It uses this:

```
<img alt="MyImage.pdf" width="900" src="data:application/pdf;base64,JVBER ... more Base64 ...  />
```

**Comment by mojavelinux** [comment]
Embedding PDFs directly into a web page is not supported across browsers. You can perhaps convert it to an SVG, which would allow it to keep its vector properties.

**Comment by mojavelinux** [comment]
You're correct that application/pdf would be the correct MIME type. But the HTML is still not portable and we don't want to encourage it. We could document which MIME types are supported on this page: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/#embed-images-with-the-data-uri-attribute

**Comment by mojavelinux** [comment]
I've done a bit more research into this and I see that if we use an object tag instead of an img tag, it taps into the browser's ability to embed a PDF using a frame. But this has nothing to do with data-uri. It works fine with a relative path reference. So I'll open a new issue to consider it.

**Comment by mojavelinux** [comment]
See #3908.

I'll be honest, the chances of implementing that anytime soon are slim. But you could implement a custom block macro and have it working today.
