### ISSUE TITLE
To have span and class attributes inside col tags

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor#3907]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup

Nothing special to say. I think this is a pretty useful thing in technical writing and it would be very useful to have it in Asciidoctor.

**Comment by mojavelinux** [comment]
I don't understand what the point of this issue is. The built-in HTML converter in Asciidoctor already uses the colgroup tag. Can you clarify what you want changed?

**Comment by john-cj** [comment]
Sorry, I should have been clearer.

I mean to have an option to use `span` and `class` attributes inside `col` tags. An excerpt from the example from the link above:

```
<colgroup>
  <col>
  <col span="2" class="batman">
  <col span="2" class="flash">
</colgroup>
```

**Comment by mojavelinux** [comment]
This is not likely something that the built-in HTML converter can / will support. It's not possible to specify roles for a column or even a cell. There are some proposals in the issue tracker for adding that, but until those are addressed / resolved, there's no way to specify this in AsciiDoc anyway.

**Comment by mojavelinux** [comment]
*If* you want that level of control now, you can use your own template for the table block or extend the converter. (All the HTML the converter generates can be customized).

**Comment by mojavelinux** [comment]
> there's no way to specify this in AsciiDoc anyway.

You could add a custom attribute to the block, which your custom converter / template references. But that's still an extension, not part of the language.

**Comment by john-cj** [comment]
Thanks, Dan. So I think it would be better to close this issue for now )

**Comment by mojavelinux** [comment]
For reference, here's the issue about roles on a cell: #1338. I haven't even thought about how we might add roles to a column.
