### ISSUE TITLE
"Unresolved directive in" when including files from subdirectory which include relative includes as well

### ISSUE THREAD

**Issue by MLThal** [asciidoctor/asciidoctor#3915]
Hi,

I have the following structure:

```
a
|--b
|   |--b1.adoc
|   |--b2.adoc
|
|--c
|   |--c1.adoc
|   |--c2.adoc
|
|--a1.adoc
```

The files look like this

* `b2.adoc`
```
My B content
```

* `b1.adoc`
```
:rootpath: ../../

include::{rootpath}a/b/b2.adoc[]
```

* `c2.adoc`
```
My C content
```

* `c1.adoc`
```
:rootpath: ../../

include::{rootpath}a/c/c2.adoc[]
```

* `a1.adoc`
```
:rootpath: ../

include::{rootpath}a/b/b1.adoc[]
include::{rootpath}a/c/c1.adoc[]
```

My goal is to be able to read both, `b1.adoc` and `c1.adoc` as separate documents with all its includes. But I want to read the document `a1.adoc` as collection of documents which are located in subdirectories as well. The problem is the relative path structure.

Finally I came up with the provided solution, but then a strange behaviour occurs:

In document a1.doc an expection raises when I add the second include. Both work well alone, but when adding both, the second one raises this exception:

`Unresolved directive in a1.adoc - include::../../a/c/c1.adoc[]`

Why does this happen? Is there another approach to reach my goal?

I tried using `ifndef:rootpath[:rootpath: ../]` instead the `:rootpath: ../` in every file as well, but then the relative path in the subfile are not resolved properly.

Thanks in advance for your help :)

**Comment by Mogztter** [comment]
Unless I'm missing something, I don't think you need to use `..` or an attribute.

`a1.adoc` can include both `b1.adoc` and `c1.adoc` as follows:

```
include::b/b1.adoc[]

include::c/c1.adoc[]
```

`b/b1.adoc` can include `b2.adoc` (the include will be resolved from the `b` directory):


```
include::b2.adoc[]
```

Same thing for `c/c1.adoc`.

See the attached zip: [relative-includes.zip](https://github.com/asciidoctor/asciidoctor/files/5849729/relative-includes.zip)


And here's the result:

`a1.html`

![a1](https://user-images.githubusercontent.com/333276/105360408-d6481f80-5bf8-11eb-8181-249c4a31137c.png)

`b/b1.html`

![b1](https://user-images.githubusercontent.com/333276/105360462-e3650e80-5bf8-11eb-9cb1-8060bd7c4cc7.png)


`c/c1.html`

![c1](https://user-images.githubusercontent.com/333276/105360460-e233e180-5bf8-11eb-82d7-5e2e10d50c9c.png)

**Comment by MLThal** [comment]
Thanks for your effort.

However, that, in fact, solves the problem, but doesn't explain it.

In fact, my structure is a bit more complicated than showed previously (I just minimized it to focus on the exception). In fact, I am using the `rootpath` variable for creating some relative links and referencing the `images` path which is located next to directory `a`: 

```
root
  |--a
  |   |--b
  |   |   |--b1.adoc
  |   |   |--b2.adoc
  |   |
  |   |--c
  |   |   |--c1.adoc
  |   |   |--c2.adoc
  |   |
  |   |--a1.adoc
  |  
  |--z
  |   |--z1.adoc
  |
  |-images
      |--img1.png
      |--img2.png
```

E.g. `c2.adoc` has a link reference to `a1.doc`:

```
{rootpath}/a/a1.doc
```

Both, `a1.adoc` and `c2.adoc` reference a document in directory `z` (or images in the `images` directory) as well:

```
{rootpath}/z/z1.doc
```

So, I don't just reference the directory tree down, but also up. That's why I am explicitly defining the `rootpath` variable. I wanted to create a structure where I can reference everything I need (includes, links, images) always from the same point. That works fine unless `a1.adoc` only has one single include as described above. And that's why I need to solve the original problem: How can I work with relative paths in which the documents reference to each other no matter which level they are.
