### ISSUE TITLE
test "should preserve cgi-style options on language when setting start_inline option for PHP" fails

### ISSUE THREAD

**Issue by pvalena** [asciidoctor/asciidoctor#3916]
While upgrading to 2.0.12 in Fedora, the following test started to fail:

```

  1) Failure:
Minitest::Test::TestSyntaxHighlighter::TestRouge#test_should_preserve_cgi_style_options_on_language_when_setting_start_inline_option_for_PHP [/builddir/build/BUILD/asciidoctor-2.0.12/usr/share/gems/gems/asciidoctor-2.0.12/test/syntax_highlighter_test.rb:761]:
Expected "<div class=\"listingblock\">\n<div class=\"content\">\n<pre class=\"rouge highlight\"><code data-lang=\"php\"><span class=\"nf\">cal_days_in_month</span><span class=\"p\">(</span><span class=\"no\">CAL_GREGORIAN</span><span class=\"p\">,</span> <span class=\"mi\">6</span><span class=\"p\">,</span> <span class=\"mi\">2019</span><span class=\"p\">)</span></code></pre>\n</div>\n</div>" to include "<span class=\"nx\">cal_days_in_month</span>".

```
[Full build+test log](https://download.copr.fedorainfracloud.org/results/pvalena/rubygems/fedora-rawhide-x86_64/01890566-rubygem-asciidoctor/builder-live.log.gz).

Ruby version:  3.0.0
Rubygems version: 3.2.3
Gems versions: 
```
coderay 1.1.2
concurrent ruby 1.1.5
erubi 1.7.0
haml 5.2.0
io console 0.5.6
irb 1.3.0
json 2.5.1
minitest 5.14.3
nokogiri 1.11.1
openssl 2.2.0
psych 3.3.0
racc 1.5.2
rdoc 6.3.0
rouge 3.26.0
devel 3.2.3
slim 4.1.0
temple 0.8.2
tilt 2.0.10

```

**Comment by tmzullinger** [comment]
Thanks for filing this Pavel.  The test began failing with 2.0.11 in Fedora, in case that helps anyone here to bisect the problem.

**Comment by mojavelinux** [comment]
This is more than likely caused by the updates to the lexer in Rouge. The test is probably being over-zealous in what it asserts. We'll need to make the test less specific so it can accommodate output from different versions of Rouge.

**Comment by mojavelinux** [comment]
...so it has nothing to do with the version of Asciidoctor. It's the version of Rouge that impacts the test.
