### ISSUE TITLE
[docs] Clarify where docinfo files are searched for

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor#3918]
The docs say that docinfo files by default are searched for in the document's directory, but this is true only for file conversion with standalone Asciidoctor, or accidentally otherwise.  It's more accurate to say that they are looked up in `base_dir` which happens to be the document's directory for standalone file conversion.

In addition, let's explain that the  `docinfodir` is resolved relative to `base_dir`.

I'm documenting a docinfo feature for jekyll-asciidoctor and having more correct info here will considerably reduce cognitive dissonance between the pages.

**Comment by mojavelinux** [comment]
I have clarified this in the docs. The docinfodir value is resolved relative to the document directory if the value is relative. See https://docs.asciidoctor.org/asciidoctor/latest/docinfo/#resolving
