### ISSUE TITLE
How to properly link to directory ancestors or siblings from different levels

### ISSUE THREAD

**Issue by MLThal** [asciidoctor/asciidoctor#3922]
Hi,

I have the following directory/document structure:

```
root
  |--a
  |   |--b
  |   |   |--b1.adoc
  |   |
  |   |--a1.adoc
  |  
  |--z
  |   |--z1.adoc
  |
  |-images
      |--img1.png
      |--img2.png
```

`a1.adoc` includes `b1.adoc`
`include::b/b1.adoc[]`

Furthermore a1.adoc has a link to an image and to `z1.adoc`. `b1.adoc` has a link to both documents, `a1.adoc` and `z1.adoc` and to an image as well.

It is very important that I can render both, `b1.adoc` and `a1.adoc` (which includes `b1.adoc`) separately. So, my problem is, that I don't know how to set the link paths to images and document properly in the document in that way, that they work for different directory levels. I came up with this approach:

`b1.adoc`:
```
:rootpath: ../../
:imagesdir: {rootpath}images
...
link:{rootpath}a/a1.adoc[]
link:{rootpath}z/z1.adoc[]
image:img2.png[]
```

`a1.adoc`:
```
:rootpath: ../
:imagesdir: {rootpath}images
...
link:{rootpath}z/z1.adoc[]
image:img1.png[]
...
include::b/b1.adoc[]
```

However, that doesn't work properly. `b1.adoc` as stand-alone document acts as expected, the links work. But when I try `a1.adoc` it seems like the rootpath variable isn't used as I expected. For the original links, the a1.adoc's own rootpath variable is used. But for the part, where b1.adoc is included, it seems like the rootpath variable of `b1.adoc` is used instead of `a1.adoc`. This is why the links in that included sections fail. The same is for images: The images in the included section are not shown.

I tried to change the `rootpath` definition in `b1.adoc` to
`ifndef::rootpath[:rootpath: ../../]`

But this didn't make a change for me.

So, finally, how can I achieve a proper including in a nested directory structure, while the nested documents should also be available as they are?

Thanks in advance for any help?

**Comment by mojavelinux** [comment]
It's important to keep in mind that the path you use to link to images is in no way related to the path you use to include documents. The include is a preprocessor directive that is resolved as the document is processed. So those paths are relative to the document you are currently in. No matter where you are in the hierarchy, you can include a sibling document without any directory reference. And the reference always begins with the current directory of the file doing the including.

Image references are entirely different. They are resolved after the document is converted, which means after the document has been combined. Image references have absolutely no knowledge of includes or the hierarchy of the documents from which content is taken. You can think of image references being relative to the primary document (usually the root of your tree).

**Comment by MLThal** [comment]
Hi, thanks for your reply. 

I am not sure how this helps. As you can see, the include of b1.adoc is not using the rootpath variable, whereas the links do. So, I am already handling links and includes differently. 

So, what could you recommend how to handle my problem?

**Comment by mojavelinux** [comment]
Trying to render documents both as includes an as standalone documents without the help of a build tool is not recommended. You are going to run into these sorts of problems. It's really outside the scope of the processor to accommodate such a scenario. What I recommend is that you create one set of include documents and a separate set of primary documents. Each of the primary documents can then include the include documents and it will be more clear how to make links work.

**Comment by mojavelinux** [comment]
In other words, without the help of a build tool and a deep understanding of the processor, I'm afraid the hierarchy you are trying to use is too complex. That's not to say it isn't possible. But you need to develop your understanding by taking incremental steps to get there so that you can understand the impact of each change. Otherwise, it's really difficult to explain what you need to do in order to make it work (without me having to spend a lot of time helping you set it up, time which I simply don't have).

**Comment by mojavelinux** [comment]
For help with usage, you might try the chat channel. https://gitter.im/asciidoctor/asciidoctor. There are lots of people there who might have more time to help. I'd like to reserve the issue tracker for tracking changes to the software. Thanks!
