### ISSUE TITLE
Bibliograpy reference labels are not printed.

### ISSUE THREAD

**Issue by benibilme** [asciidoctor/asciidoctor#3926]
My environment is as follows:

    Asciidoctor 2.0.12 [https://asciidoctor.org]
    Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Following is a simple test asciidoc document.

    = Test

    == Bibliography test

    Some text, not meaninful. This is a reference. <<myreference>>

    [bibliography]
    == References
     [[[myreference]]] This is the origin of the references

In generated html file,  `myreference`  label is not displayed in the bibliograpy. It only shows emty `[]`. Reftext are not being honored as well for example  `[[[myreference,1]]]`, still shows `[]`.  

The described behaviour above does not conform to the documentation at https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography

**Comment by Mogztter** [comment]
I believe that `[[[myreference]]]` should be in a list:

```
= Test

== Bibliography test

Some text, not meaningful. This is a reference. <<myreference>>

[bibliography]
== References

* [[[myreference]]] This is the origin of the references
```

**Comment by benibilme** [comment]
Hello, 

Thank you for the answer. Yes you are right. Bibliography references should have been in the list. I will close the issue. Do you know any way, to list the bibliograpy without list bullets?

**Comment by Mogztter** [comment]
You can apply a custom style on the bibliography list:

```css
ul.bibliography {
  list-style-type: none;
  margin-left: 0;
}
```

For reference, here's a self-contained example:

```
= Test

== Bibliography test

Some text, not meaningful. This is a reference. <<myreference>>

[bibliography]
== References

++++
<style>
ul.bibliography {
  list-style-type: none;
  margin-left: 0;
}
</style>
++++

* [[[myreference]]] This is the origin of the references
```

Please note that you should *not* use a passthrough block (`++++`) to apply styles but instead you should use a custom stylesheet: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/

**Comment by benibilme** [comment]
Thank for the response and saving time.  I will take a note of this.
