### ISSUE TITLE
In-memory docinfo/stylesheet parameters for Asciidoctor.convert

### ISSUE THREAD

**Issue by stephenwhittle** [asciidoctor/asciidoctor#3930]
I'm generating an Asciidoctor document as a string and passing it into `Asciidoctor.convert`, which is working great. 

However, given that the document never exists on disk, it's a bit awkward to have to embed a docinfo or stylesheet path to a file on disk, rather than also being able to provide an in-memory stylesheet alongside the in-memory input.

As an example, this would allow me to use `primary_stylesheet_data` and append some additional tweaks (abusing css ordering precedence, yay) , then pass the entire thing into `convert`. 
Alternatively, is there a way I can do this at the moment?

**Comment by mojavelinux** [comment]
Yes, docinfo is an extension point. See https://docs.asciidoctor.org/asciidoctor/latest/extensions/docinfo-processor/. You can also find examples in the lab. See https://github.com/asciidoctor/asciidoctor-extensions-lab
