### ISSUE TITLE
Provide decimal (or char) alignment in tables

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor#3931]
This is to make numerical tables prettier and easier to read. The immediate case is for HTML tables with currency amounts, but the obvious extension would be to align on any character, in all outputs. I can fudge it now by using a fixed number format, with either right alignment or centre alignment and leading zeroes, but this is not ideal and presumably would not work with variable width fonts.

**Comment by mojavelinux** [comment]
I don't think this is the responsibility of the processor. It's getting far too deep into the content. Instead, this might be a good use case for an inline macro that can be used to prepare the content for display in a table cell. Something like:

```
format:value[type=currency]
```
