### ISSUE TITLE
Allow multi-line header attribute values

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor#3942]
Use case from jekyll-asciidoc project:
Jekyll page variables are objects parsed from yaml.
Global page attributes (i.e., defined in the Jekyll configuration file `_config.yml`) with the appropriate (`page-` by default) prefix are automatically converted to page variables.
When defined globally, these automatically appear as Ruby objects from the yaml parsing done by Jekyll.

A page header attribute will also be parsed as yaml by the jekyll-asciidoc extension.
However, due to the limitation that attributes are single line, the yaml must be single-line format.
For complex objects this can be quite inconvenient.
This was brought up in https://github.com/asciidoctor/jekyll-asciidoc/issues/158

This issue proposes investigating supporting multi-line page attributes, possibly only for header attributes.
A new syntax might be needed, perhaps `::attribute-name:: attribute value.
Most likely this will be done in cooperation with  the spec working group.

**Comment by mojavelinux** [comment]
We are considering changes to how multi-line values in an attribute entries are handling in the language project. No change will happen in Asciidoctor until that is decided, so I'm closing down this issue.
