### ISSUE TITLE
Сhanging text font size when applying 'a' operator to a table cell

### ISSUE THREAD

**Issue by tadmi** [asciidoctor/asciidoctor#3949]
Apply **a** operator to a table cell, and font size of the text in that cell becomes larger by 1 px.

CSS rule from default asciidoctor.css is triggered last:

`p, blockquote, dt, td.content, span.alt {
    font-size: 1.0625rem;
}`

As a result, the table looks inconsistent.

[Example from Asciidoctor Docs](https://docs.asciidoctor.org/asciidoc/latest/tables/format-cell-content/#ex-asciidoc)

![Asciidoctor - table - format content by cell - operator a](https://user-images.githubusercontent.com/63556979/108334846-691daf00-71e3-11eb-80d1-75c2dcaba4d9.png)

**Comment by mojavelinux** [comment]
Although it may seem odd when looking at it from the lens of this comparison, this was a conscious design choice to consolidate the text of basic (and very common) table cells.

```css
.sidebarblock p, .sidebarblock dt, .sidebarblock td.content, p.tableblock {
  font-size: 1em;
}
```

The paragraph in an AsciiDoc table cell is a paragraph block in an embedded document. The paragraph in a normal table cell is, in fact, just a data cell. Hence, there is an important distinction.

If you prefer them to be the same, you can apply that change to your own stylesheet.
