### ISSUE TITLE
How to change font arts in output html?

### ISSUE THREAD

**Issue by lucki1000** [asciidoctor/asciidoctor#3950]
Hi,

I've try to change my font art to firacode for all \<code\> tags, I've tried with a docinfo.html and this command `asciidoctor  --attribute docinfo=shared my.adoc` but nothing changes.

How can I change this font to firacode?

output of my docinfo.html:
````
<style>
        @font-face {
    font-family: Firacode;
    src: url(./fonts/firacode.ttf);
        }
        code{
                font-family: Firacode;
        }
</style>
````
Asciidoctor version: `Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)`

Regards Lucki1000

**Comment by mojavelinux** [comment]
What you have entered should work fine for inline `code` tags, but it will miss any blocks wrapped in `pre`. You also may want to increase the precedence of the selector just to be sure. There could be situations where the built-in styles have a stronger rule.

```
code,
pre,
pre > code {
  font-family: Firacode;
}
```

Also, make sure that the browser is actually loading the font. You can do so by using the Developer Tools in your browser (i.e., the Inspector).
