### ISSUE TITLE
When using a label inside a section header, the label text is not picked up properly

### ISSUE THREAD

**Issue by bzbarsky-apple** [asciidoctor/asciidoctor#3955]
Consider the following markup:

```
:xrefstyle: full

[[http_section_formal]]
== [[http_section_informal, HTTP]] How to do HTTP right
....
As described in <<http_section_formal>>, .....
...
When using <<http_section_informal>>, ....
```

The idea here is that sometimes I want to reference a given section by section number and name, and sometimes I want to see a simpler label for it.  And I want to avoid typing that simpler label in the cross-ref sites.

This almost works.  Asciidoctor generates this HTML:
```
<h2 id="http_section_formal">1. <a id="http_section_informal"></a> How to do HTTP right</h2>
...
<p>As described in <a href="#http_section_formal">Section 1, &#8220; How to do HTTP right&#8221;</a>, &#8230;&#8203;..</p>
...
<p>When using <a href="#http_section_informal">[http_section_informal]</a>, &#8230;&#8203;.</p>
```
which has the two anchors and correct links to them.  But the nice label text from the second label is not getting picked up.

**Comment by mojavelinux** [comment]
You are correct, this is not a feature that AsciiDoc currently supports. A section can only have a single primary ID for use in cross referencing. The auxiliary IDs (aka anchors) are only used for deep linking from the URL.

**Comment by bzbarsky-apple** [comment]
I'm not asking for the section to have multiple ids.  I understand that that doesn't work and why it doesn't work.

I'm asking for the text replacement for the reference to the label that's inside the section (and is not the section label itself) to actually get used...  Or is that text replacement attached to the section id, not the label?

**Comment by mojavelinux** [comment]
To clarify, there's no such term as label in AsciiDoc. Instead, we refer to them as IDs (just like in XML and HTML). IDs are defined either using a block anchor or an inline anchor. The reference text is associated with the ID. Each element can only have one primary ID and thus one reference text. Secondary IDs do not contribute reference text. So what you're asking about is simply not possible in the current design of the referencing system in AsciiDoc.

**Comment by mojavelinux** [comment]
> Secondary IDs do not contribute reference text.

This is a capability we could consider. But it would have to be entered as a new feature request.

**Comment by bzbarsky-apple** [comment]
Thanks, that clarifies things.

Is there any better way to accomplish what I am really trying to do here?  To whit:

1. References that point to (about) the same point in the document.
2. Some of the references have the full section number and section name of the section being referenced as their text.
3. Some of the references have some custom string as their text.
4. The custom string does not need to be manually typed at every reference; it's entered once somewhere and hence is easy to change globally.

**Comment by mojavelinux** [comment]
What you're asking to be able to do falls firmly in the new feature category.

At the most basic level, you can use custom text at the location of the reference:


```asciidoc
As described in <<http_section,How to do HTTP right>>, ...

When using <<http_section,HTTP>>, ...
```

I recognize, though, that you don't get to benefit from the automatic text (requirement # 4)

When you specify reference text on a block, the xrefstyle does not apply. It always shows the reference text as entered. There's another open issue in which we discussed the relationship between custom reference text and the xrefstyle, but it remains open. See #2212.

So there's no way to do what you are asking about out of the box. It just wasn't a use case we considered. If you're willing to venture into extensions, there are likely things you could do to make it work.

**Comment by bzbarsky-apple** [comment]
> So there's no way to do what you are asking about out of the box. 

Understood, thanks!  I can absolutely work around this; I just wanted to make sure I wasn't missing something obvious.  Thank you for the quick responses!

**Comment by mojavelinux** [comment]
This is the same as #3866.
