### ISSUE TITLE
GEM_HOME="${HOME}/.gem"; gem install asciidoctor-diagram

### ISSUE THREAD

**Issue by marmalodak** [asciidoctor/asciidoctor#3957]
How do I use asciidoctor-diagram when I have it installed under ~/.gem?

    ❯ asciidoctor -r asciidoctor-diagram -b html index.adoc
    asciidoctor: FAILED: 'asciidoctor-diagram' could not be loaded

**Comment by mojavelinux** [comment]
Please use either rvm or bundler to manage gems. We don't support other configurations (because they are just too hard to support).

**Comment by marmalodak** [comment]
Thank you, I was able to succeed by using rvm.

**Comment by mojavelinux** [comment]
Fantastic!
