### ISSUE TITLE
Unexpected output by multiple new window links without space character between

### ISSUE THREAD

**Issue by reosablo** [asciidoctor/asciidoctor#3962]
I found a problem with new windows link like the below.

```adoc
link:https://example.com/hide[hide^]-and-link:https://example.com/seek[seek^]

// expected: <a href="https://example.com/hide" target="_blank" rel="noopener">hide</a>-and-<a href="https://example.com/seek" target="_blank" rel="noopener">seek</a>
// output:   <a href="https://example.com/hide">hide<sup></a>-and-<a href="https://example.com/seek">seek</sup></a>
```

This problem often happens to avoid "unwanted space characters in Japanese language." #1420

```adoc
吾輩はlink:https://ja.wikipedia.org/wiki/%E3%83%8D%E3%82%B3[猫^]である。link:https://ja.wikipedia.org/wiki/%E5%90%8D%E5%89%8D[名前^]はまだ無い。
```

I tried Asciidoctor 2.0.12 by [docker-asciidoctor:1.3.3](https://hub.docker.com/layers/asciidoctor/docker-asciidoctor/1.3.3/images/sha256-81af0d6e4ac3bd7d258dab9b3b2ba56e6ff2632c94609a1faac15a9059d382c4?context=explore) and [Asciidoctor.js 2.2.1](https://www.npmjs.com/package/asciidoctor/v/2.2.1)

**Comment by mojavelinux** [comment]
Although admittedly the behavior is quirky, this is operating as expected. The `^` is being matched as a pair, so it is applying superscript before the links are converted. There are (at least) two ways to work around this.

You can escape the first `^`

```
https://example.com/hide[hide\^]-and-link:https://example.com/seek[seek^]
```

Or you can use the long form of the window attribute:

```
https://example.com/hide[hide,window=_blank]-and-link:https://example.com/seek[seek,window=_blank]
```

Notice I did not use the `link:` prefix for the first link (instead, opting for a URL macro) as the `link:` prefix is not needed there.

**Comment by reosablo** [comment]
@mojavelinux 
I understand! Thank you for your kind answer.
