### ISSUE TITLE
Wrong instructions in "Migrate from Confluence XHTML" doc page

### ISSUE THREAD

**Issue by juliojgd** [asciidoctor/asciidoctor#3994]
The page published here: https://docs.asciidoctor.org/asciidoctor/latest/migrate/confluence-xhtml/ (Retrieved April 7th, 2021 at 12:48PM Spain Mainland Time) describes how to execute a groovy script to acomplish the migration of Confluence HTML.
I checked that and those instructions are wrong, they don't work. I managed to obtain the right result but with modifications to that instructions.

I will attach a PR fixing: https://github.com/asciidoctor/asciidoctor/blob/master/docs/modules/migrate/pages/confluence-xhtml.adoc with the steps that I checked to work.

Any comment will be welcomed.

**Comment by mojavelinux** [comment]
Thanks for catching this and offering a pull request!
