### ISSUE TITLE
xrefs turn into links when you add an xreflabel

### ISSUE THREAD

**Issue by stallio** [asciidoctor/asciidoctor#3996]
Per the documentation, I should be able to add an xreflabel to an xref, but when I try it and export to XML, they show up as links instead.

Test file: 
````
[#listingtest]
----
code code code
----

Look at <<listingtest>>. Look at <<listingtest,this listing>>. Look at xref:listingtest[this listing].
````

All of these should return an `<xref>` when I convert to XML, but here's what I get with Docbook 5:

````
<simpara>Look at <xref linkend="listingtest"/>. Look at <link linkend="listingtest">this listing</link>. Look at <link linkend="listingtest">this listing</link>.</simpara>
````

(If I put the xreflabel inside the element I'm referencing, that works as expected.)

**Comment by mojavelinux** [comment]
The reason the `link` tag was chosen instead of the `xref` tag when link text is specified was for compatibility with the DocBook produced by AsciiDoc.py. (See https://github.com/asciidoc-py/asciidoc-py2/blob/master/docbook45.conf#L245-L251). And, in fact, we find the reason for that original decision in the DocBook reference:

> The xref element forms a cross-reference from the location of the xref to the element to which it points. Unlike link and the other cross-referencing elements, xref is empty. The processing system has to generate appropriate cross-reference text for the reader.
> https://tdg.docbook.org/tdg/5.1/xref.html

Unless you can use the DocBook reference to make a case for what it should be, it has to remain as it is in order to be compliant.

**Comment by stallio** [comment]
OK, then could someone update the documentation to clarify that this doesn't work as expected for XML output?

It's confusing to use the `xref` macro and have it return a `link` instead of an `xref`. 

https://docs.asciidoctor.org/asciidoc/latest/macros/xref/
https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/

In particular, the "document to document" page explicitly says to use `xref:` instead of `link:`.

**Comment by mojavelinux** [comment]
I think you're confusing the AsciiDoc macro names with the DocBook tag names. In DocBook, the link tag with the linkend attribute is the correct choice for making an internal reference with custom link text. It makes a clickable anchor from the link text to the target.

This has nothing to do with the xref vs link macro discussion for the document-to-document feature of AsciiDoc. An xref macro sometimes has to output a link tag in DocBook to be functional. That doesn't make it not an xref. Rather, which tag is used is an implementation detail of DocBook.

> could someone update the documentation to clarify that this doesn't work as expected for XML output

This is a community project, and if you want something updated, then it's best to take that initiative yourself. In other words, that someone is you. Please don't instruct other people to do work for you or that you want to see done.

**Comment by stallio** [comment]
Where would I find that part of the documentation to update it? I get as far as https://github.com/asciidoctor/asciidoctor/tree/master/docs/modules and then I'm stumped.

**Comment by mojavelinux** [comment]
You can find an "Edit this Page" link in the upper right of every page in the documentation. That will get you where you need to go.
