### ISSUE TITLE
Attribute expansion is not performed in parts of the document using 'manpage' doctype

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor#4000]
Attribute expansion is performed differently in the 'Name' section of the following document depending on whether it's processed with default or 'manpage' document type:

> = attribs(3)  
> :value: fnord  
>   
> == Name  
>   
> Name - value is {value}  
>   
> == Synopsis  
>   
> Synopsis - value is {value}  

When run through 'asciidoctor -b html5 -d manpage', the body of the 'Name' section looks like:

> Name - value is {value}

When run through 'asciidoctor -b html5', the body looks (as intended) like:

> Name - value is fnord

In https://discuss.asciidoctor.org/Should-attribute-expansion-be-suppressed-in-the-Name-section-of-a-manpage-document-tp8583p8584.html, @mojavelinux asked that I file this issue.

Using asciidoctor 2.0.12, Ruby 2.5.3

**Comment by mojavelinux** [comment]
I cannot find any reason why substitutions are not applied to the manpurpose in the NAME section. I think at the very least the processor should substitute attribute references. I found a similar change when we added attribute substitution to the manname in that same NAME section. See https://github.com/asciidoctor/asciidoctor/commit/3826b88692b75e763b1517dc5346c77c390562f4 Seems reasonable to extend it to the manpurpose as well.
