### ISSUE TITLE
cross-reference links with __ are not rendered correct

### ISSUE THREAD

**Issue by markusschaefer** [asciidoctor/asciidoctor#4016]
Hi,

I try to write a cross-reference link to a file, that contains double underscores in its path. In the rendered result the __ are replaced with `<em>` and `</em>`.

```
<<./doc__with_double__underscore.adoc#, MyLink>>
```
is rendered to 
```
<a href="./doc<em>with_double</em>underscore.html">MyLink</a>
```

**Comment by mojavelinux** [comment]
The double underscore sequence has special meaning in AsciiDoc. If you don't want it to be interpreted, you have to escape it.

```
<<./doc\__with_double__underscore.adoc#, MyLink>>
```

While we're on the topic of that example, we recommend using the xref macro for interdocument links:

```
xref:./doc\__with_double__underscore.adoc[MyLink]
```

For more context, see these pages in the documentation:

* https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/#escape-with-backslashes
* https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/

**Comment by markusschaefer** [comment]
Thanks for the fast support :thumbsup:
