### ISSUE TITLE
avoid inline style

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor#4045]
Consider this nearly-minimal document

````
= Test article: This is the subtitle

== tables

[cols=2*]
|===
|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===


[cols=2*,options=header]
|===
|Name
|Group

|Firefox
|Web Browser

|Ruby
|Programming Language

...
|===

````

converting it to html with `asciidoctor --embedded index.adoc` generates

````
<div class="sect1">
<h2 id="_tables">tables</h2>
<div class="sectionbody">
<table class="tableblock frame-all grid-all stretch">
<colgroup>	
<col style="width: 50%;">
<col style="width: 50%;">
</colgroup>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">Firefox</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">Web Browser</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">Ruby</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">Programming Language</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">TorqueBox</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">Application Server</p></td>
</tr>
</tbody>
</table>
<table class="tableblock frame-all grid-all stretch">
<colgroup>
<col style="width: 50%;">
<col style="width: 50%;">
</colgroup>
<thead>
<tr>
<th class="tableblock halign-left valign-top">Name</th>
<th class="tableblock halign-left valign-top">Group</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">Firefox</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">Web Browser</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">Ruby</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">Programming Language</p>
<p class="tableblock">&#8230;&#8203;</p></td>
</tr>
</tbody>
</table>
</div>
</div>
````

per se the document is fine, but `<col style="width: 50%;">` is problematic with a `style-src` csp policy that does not permit unsafe-inline (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src).

Would it be possible, just like it happens in all other places, not to use inline style?

**Comment by mojavelinux** [comment]
The alternative to using the width style on the column is to use the width attribute. However, the width attribute is deprecated. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col And we have to be able to specify a width to conform to the contract. Therefore, it's necessary to use an inline style in this case.

If you don't want a width set, you can add the %autowidth option to the table.

```
[%autowidth,cols=2*]
|===
|Firefox
|Web Browser
|===
```

**Comment by mojavelinux** [comment]
@Mogztter We could consider it a policy for the modern HTML converter to avoid the use of inline styles. However, since we still have to be able to specify a width on the column, that would mean using the deprecated width attribute. To be honest, I don't understand why it is deprecated. So perhaps we can use it anyway, caveat emptor?

**Comment by fekir** [comment]
@mojavelinux 

thank you for the suggested workaround.

Can I ask why not define a css class and use it instead of using inline css?
that would be the real alternative, instead of using a deprecated attribute.

I know it seems a dumb workaround... but it would make it possible to use a csp-policy with unsafe-inline without any changes.
And it would also allow avoid special-casing modern HTML.

**Comment by mojavelinux** [comment]
Defining a CSS class in the default stylesheet for every possibly permutation of column counts and widths is unreasonable. If you want to use CSS to set the column widths for your table, you can still do so by combining autowidth with a custom role:

```
[%autowidth.stretch.cols-25-75]
|===
...
|===
```

where the role is defined in the stylesheet as:

```
table.cols-25-75 > colgroup > col:nth-child(1) {
  width: 25%;
}
table.cols-25-75 > colgroup > col:nth-child(2) {
  width: 75%;
}
```

If you want even column widths, the CSS is a bit simpler:

```
table.cols-50-50 > colgroup > col {
  width: 50%;
}
```

**Comment by fekir** [comment]
> Defining a CSS class in the default stylesheet for every possibly permutation of column counts and widths is unreasonable

Of course, but what about defining only those needed like the ones you suggested?

**Comment by mojavelinux** [comment]
And how exactly do you propose we would do that? Tables in AsciiDoc can have an arbitrary number of columns with an arbitrary number of width ratios. How could a default / generic stylesheet possibly define all of those an not end up being absurdly large?

**Comment by fekir** [comment]
I admit I have no idea how asciidoc works internally.

I was thinking something like the following would have been possible
 * during generation, asciidoc enumerates what tables are generated
 * instead of writing `style="width: 50%;"`, it uses `class=50px`
 * afterwards a class `50px` is added to the css, which is the equivalent of `width: 50%`

**Comment by mojavelinux** [comment]
As far as I'm concerned, all that does is add unnecessary complexity to the toolchain. Is that really any more "secure" than using inline styles? If it's something you want to do in your own toolchain (by extending the converter), you are free to do so. I don't think it makes any sense for this project to do it by default.

**Comment by fekir** [comment]
> Is that really any more "secure" than using inline styles?

I know `unsafe-inline` is there to prevent css hijacking, just like with javascript.
I do not know (yet) how it works in practice, I was not able to find a resource.
Unfortunately with csp it is not possible to whitelist only some inline styles.

I made the feature request as I noticed the error messages on a webpage that otherwise does not use inline css, I hoped it would have been an "easy change", as AFAIK inline css is not used otherwise, thus it would have made the resulting html more consistent.

Please correct me if I am wrong about the fact that this is the only place where inline css is used.
I know now (thank you for your suggestions!) how to avoid the issue with tables, but it would be nice to know in advance if there are other possible places where to pay attention.

**Comment by mojavelinux** [comment]
You are free to browse the code for the HTML converter to find where else inline styles are used. Most of the time, it's to specify dynamic widths, which are optional. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb

**Comment by mojavelinux** [comment]
> during generation, asciidoc enumerates what tables are generated...afterwards a class is added to the css

The problem with this approach is that it's also constrained by CSP. Asciidoctor doesn't always have control over the stylesheet, and when it does, it's usually to embed it into the HTML. It's a hit or miss solution that, itself, is going to create confusion.

**Comment by mojavelinux** [comment]
@Mogztter Given that there's no other reasonable solution when the CSP is configured to disallow inline styles, I'm strongly reconsidering switching back to using the width attribute on the col element in the built-in HTML converter. The fact that it's marked as deprecated is absurd. (To hell with the HTML5 validator). I think we can start by using the width attribute in the modern HTML5 converter, and perhaps enable it via a flag in the existing built-in HTML converter.
