### ISSUE TITLE
Single shorthand exclusion tag on include directive no longer works

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor#4048]
This shows up in the Asciidoc plugin.

https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/744

The exclusion tag:

`include::file.adoc[tags=!foo]`

doesn't work anymore. The whole file is left out of the include.

The full version still works however:

`include::file.adoc[tags=**;!foo]`

**Comment by mojavelinux** [comment]
This seems to be a regression caused by #3932. You're correct in saying that `!foo` should behave the same as `**;!foo`. It looks like we are missing a test for this case, which is why it wasn't caught.

**Comment by mojavelinux** [comment]
It's interesting to note that `!*` does still work as expected.

**Comment by mojavelinux** [comment]
I found the error. It was indeed a regression caused by the fix for #3932.
