### ISSUE TITLE
How can I set the letter of the appendix?

### ISSUE THREAD

**Issue by lyndsey-ferguson** [asciidoctor/asciidoctor#4056]
I have several appendices in separate asciidocs. For example:

appendixA-trickcars.asciidoc
```
[appendix]
= Tricking out cars

== Cars cars cars

content
```
That I want to render in PDF as:
```
Appendix A: Tricking out cars
...
```

appendixB-troubleshooting-engines.asciidoc
```
[appendix]
= Troubleshooting engines

== Troubleshooting oil issues
content
```
That I would like to render in PDF as:
```
Appendix B: Troubleshooting engines
...
```

Is there a way to do this? I tried searching the docs and this repo, and the only thing I could find that seemed like it _could_ work, was to add `:appendix-number: B` but that didn't work. Any tips? 
(I'm open to monkey patch the code I'm calling to do this as I'm comfortable with Ruby, I just have no idea of where to start)

**Comment by mojavelinux** [comment]
What you're looking for is the appendix-number attribute, which is documented here: https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-reference/#builtin-attributes-i18n

For example:

```
= Document Title
:sectnums:
:doctype: book
// set appendix-number to the one before the one you want the processor to select
:appendix-number: A

[appendix]
= Troubleshooting engines

== Troubleshooting oil issues

content
```

Think of the value of the `appendix-number` as "previous appendix number".

In the future, please ask usage questions in the community chat at https://asciidoctor.zulipchat.com.

**Comment by lyndsey-ferguson** [comment]
Thank you @mojavelinux, the direct answer and the link to this section in the docs (I totally missed this!) are truly helpful. I have also signed up for the forum if find that the docs don't answer other questions.

**Comment by mojavelinux** [comment]
I'm very happy to hear that. And welcome!

**Comment by lyndsey-ferguson** [comment]
Oh, and for those of you visiting with the same issue, make sure you upgrade to at least asciidoctor 2.0.14
