### ISSUE TITLE
Number character references (NCR) are not converted correctly in man pages

### ISSUE THREAD

**Issue by felipec** [asciidoctor/asciidoctor#4059]
Any character reference is rendered as-is in the man page (e.g. `&#43;` is not converted to `+`).

Obviously they work correctly in HTML pages.

```asciidoc
= test (1)

== NAME

test - A test

== DESCRIPTION

This is just a test. This is a plus: `{plus}` `&#43;`.
```

This gets converted to:

```
This is just a test. This is a plus: \f(CR&#43;\fP \f(CR&#43;\fP.

```

But should be:

```
This is just a test. This is a plus: \f(CR+\fP \f(CR+\fP.

```

**Comment by mojavelinux** [comment]
That's correct. These are the replacements that are currently implemented. https://github.com/asciidoctor/asciidoctor/blob/35f34fcb7ff09fa33fbfbced9d23f2d098ac9323/lib/asciidoctor/converter/manpage.rb#L717-L748 I do not know how to do numeric character references in a generic way. If you know how, please point me to a reference and I'd be willing to implement it.

We certainly could map well-known numeric character references. I'll go ahead and add the one for plus and also one for the degree sign.

**Comment by mojavelinux** [comment]
I have added the NCR for plus and the degree sign. Are there any others that need to be added for your use case?

**Comment by mojavelinux** [comment]
I'm marking this as resolved until other characters are brought forward (or a general purpose solution can be found).
