### ISSUE TITLE
Images in Menu UI Macros

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor#4073]
Hello, I found some behavior and I can't say if it's intended or not.

### Ex. 1
In AsciiDoc you can add use a menu macro like this:
`menu:Open[[.ph .uicontrol]*Close* > [.ph .uicontrol]*Closer*  > Closest]`

### Ex. 2
But sometimes it's easier to just add an image of a button than to describe it in words:
`menu:image:buttons/verticalDots.png[][[.ph .uicontrol]*Close* > [.ph .uicontrol]*Closer* > Closest]`
this is the wrong way to use the macro, obviously.

### Ex. 3
However, there's a way around that if you add and image of a button at the end of the macro:
`menu:Open[[.ph .uicontrol]*Close* > [.ph .uicontrol]*Closer* > image:buttons/verticalDots.png[]]`

### Ex. 4
But anything that follows the image of a button is clipped. It is possible to put an image in any position, but everything beyond it will not be displayed.
`menu:Open[[.ph .uicontrol]*Close* > [.ph .uicontrol]*Closer* > image:buttons/verticalDots.png[]  > Closest]`

## Expected behavior
I don't know if what I've shown here is expected behavior or a bug. But it would be nice to see fixed behavior: 
- no images allowed inside the menu macro or
- images inside the menu macro are allowed in any position.

Here's a screenshot of the examples. written in AsciiDoc in IntelliJ Idea.
![2021-06-03_14-16](https://user-images.githubusercontent.com/75079192/120636570-74d17080-c476-11eb-8bbc-d356ecdaa3ba.png)

**Comment by mojavelinux** [comment]
It's necessary to escape the closing square bracket in the image macro or else it prematurely terminates the menu macro:

```
menu:Open[Close, Closer, image:buttons/verticalDots.png[\]]
```

In the future, please ask usage questions first in the community chat at https://asciidoctor.zulipchat.com.
