### ISSUE TITLE
Admonition does not break lines inside of table cell on GitHub

### ISSUE THREAD

**Issue by Kukulkano** [asciidoctor/asciidoctor#4079]
Hi. I'm not sure if I'm here at the right place but this is my problem:

```
[cols="1,4"]
|=======
|Description
a|Search words do not have to be complete and case does not matter. The search always begins on the left and returns all matches there. Thus, you can simply enter "joh foo" to find John Foobar.

NOTE: This only works if the <<enablesearchfunction>> function was called before using <<add>> or <<update>> calls. You can only search for entries that were pushed or updated with search function enabled.
|=======
```

In my local editors, this is rendered fine. On GitHub, **the NOTE admonition part is not breaking the lines** and therefore the webbrowser creates a **horizontal scrollbar** for the table. 

It looks very similar to this:
https://i.imgur.com/Tj2GwA5.png

How can I make the admonition in the table break lines automatically and prevent the horizontal scroll bar?

**Comment by mojavelinux** [comment]
This is not something we can control in Asciidoctor. The stylesheet used on github.com is provided by https://github.com/primer/css. Please report the issue there.
