### ISSUE TITLE
Enable Wiki Editing and Discussions

### ISSUE THREAD

**Issue by tajmone** [asciidoctor/asciidoctor#4081]
Could you please make the Wiki editable by any GitHub user? There are numerous typos that could be fixed, and the setup instructions for Windows could do some added notes on how to run `bundle exec rackup` with Ruby 3, via `ridk use` to switch to Ruby 2.x, since it won't work with Ruby 3.

I've opened all my Wikis to third party editors, and in 7 years and 100 repositories I've never experienced problems (like spammers, etc.). Of course, it could always happen, but since Wikis are repositories it's always easy to revert and unwanted edits.

If you could also enable Discussion for the repository, we could have a community space to discuss Rouge without polluting the repository Issues.

Thanks

**Comment by Mogztter** [comment]
I didn't even know that we had content in the Wiki 😅

Wouldn't it be better to migrate useful/valuable content to https://docs.asciidoctor.org/asciidoctor/latest/ (and disable GitHub Wiki)?

**Comment by tajmone** [comment]
> Wouldn't it be better to migrate useful/valuable content to https://docs.asciidoctor.org/asciidoctor/latest/ (and disable GitHub Wiki)?

Migrating valuable contents to the docs is indeed worth it, but there might be also good reasons to keep them in the Wiki. Usually in Wikis it's considered OK to add external links to live examples, related projects or even similar (but unrelated) projects (if one doesn't want to follow the link he/she can just ignore it), but these type of off-topic links might be considered cluttering in official docs.

Discussions are a middle ground between Issues and Forums: they are closer to Issues in that they still pertain to the repository, but (unlike Issues) they don't always refer to immediate actions for the maintainers (e.g. bugs. new features, etc.) Usually discussion a potential feature in Discussion, and only creating an Issue once it's approved, allows cleaner Issues, focusing on the actual implementation.

**Comment by mojavelinux** [comment]
We're not going to enable either of the things suggested, and I'll explain why.

The docs are now stored with the code and published to https://docs.asciidoctor.org. We will use the pull request workflow to manage changes just like we do with the code and other artifacts. Like Guillaume, I had forgotten we even had the wiki enabled on this repository. It's a relic of a time before we had documentation. This discussion has prompted me to clean it out. I will go through the pages and redirect any relevant content to the documentation site and remove pages that are outdated.

Discussions are hosted in our community chat at https://asciidoctor.zulipchat.com (and to a lesser degree, the discussion list at https://discuss.asciidoctor.org). I'm not open to creating yet another place for discussions as it will further split the conversations.

I'm sure the Wiki and Discussion features on GitHub are useful for other projects. But they are not helpful for this community.
