### ISSUE TITLE
Load asciidoctor-kroki from Gollum

### ISSUE THREAD

**Issue by HWiese1980** [asciidoctor/asciidoctor#4090]
Hello,

I'm using asciidoctor in conjunction with Gollum to run a local version of my GitLab wiki repo. Unfortunately it does not want to render PlantUML diagrams via Kroki. The `asciidoctor-kroki` extension is installed but it does not seem to be used. 

I know I can load the extension via the `--require` parameter. However, that's apparently not possible through Gollum. 

How can I tell `asciidoctor` to load `asciidoc-kroki` by default?

**Comment by Mogztter** [comment]
Hello,

You should probably ask the [Gollum](https://github.com/gollum/gollum) how to require/load additional gems.
In the future, please ask usage/integration questions first in the community chat at https://asciidoctor.zulipchat.com.

**Comment by mojavelinux** [comment]
:point_up_2: 

...especially when it pertains to the integration of Asciidoctor and its extension into non-Asciidoctor software.
