### ISSUE TITLE
Prevent warnings from being triggered on missing include files

### ISSUE THREAD

**Issue by jade-armstrong** [asciidoctor/asciidoctor#4093]
I have 3 includes in my nav.adoc and am only building 2 of the 3 files. Thus I am expecting the 3rd one not to be there and have made it optional using the opts=optional attribute. The documentation seems to imply that using this attribute will prevent warnings but I am still receiving a warning.

The nav.adoc is as follows:

```
include::./partials/procedures/nav.adoc[opts=optional]
include::./partials/simple-compute/nav.adoc[opts=optional]
include::./partials/calling-functions/nav.adoc[opts=optional]
```

The warning is as follows:

`asciidoctor: ERROR: nav.adoc: line 3: include target not found: ./partials/calling-functions/nav.adoc`

I cannot submit work with error warnings. Allowing the file to be optional without a warning will make things easier for me since we are rolling out parts of the site at different intervals and I won't have to rewrite the nav.adoc to remove warnings.

**Comment by mojavelinux** [comment]
From the looks of it, this is an Antora question. Antora does now support the optional option, but that support wasn't added until Antora 3 (currently in alpha). See https://gitlab.com/antora/antora/-/issues/678

This page explains how to install and use the Antora 3 alpha release: https://docs.antora.org/antora/3.0/install-and-run-quickstart/#install-antora
