### ISSUE TITLE
I submit a ticket to GitHub to ask for improving the ability to process AsciiDoc.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#4094]
I submit a ticket to GitHub to ask for improving the ability to process AsciiDoc.

https://support.github.com/ticket/personal/0/1218140

**Comment by Mogztter** [comment]
Please use the community chat for such announcement. This issue tracker is for tracking code changes. Thanks!


Also, and as far as I know, support tickets are private, so we cannot access your link.
