### ISSUE TITLE
Add a class to cross-reference links (HTML output).

### ISSUE THREAD

**Issue by gbmhunter** [asciidoctor/asciidoctor#4095]
I would like to be able to add custom .css styling to the generated `<a>` links that are created when making cross-references. However, these `<a>` links have no custom class added to them, so I are unable to select them via CSS without also affecting all normal `<a>` links that you would find in paragraphs.

See the attached image below for an example:

![image](https://user-images.githubusercontent.com/2396869/124341342-bd17b600-dc0f-11eb-9c8d-f5e79543d9ab.png)

My specific use case is for `bibliography` cross-references (I want to make the cross-reference text less invasive to the reading of the paragraph by making the text small and superscript by using CSS) but I feel like this class could be useful for any cross-reference.

**Comment by mojavelinux** [comment]
I've broadened this issue to include all the link attributes. See #4104. As such, I'm marking this as a duplicate since it will be covered by that one.

**Comment by mojavelinux** [comment]
As a general rule, the built-in HTML converter does not add implicit class names to links. However, you will be able to add a class name using the role attribute. If you want that behavior to be automatic, then you'll need to use a custom converter.

We might consider adding implicit class names to links in the modern HTML5 converter, currently under development.

**Comment by gbmhunter** [comment]
@mojavelinux are you saying we can already add class names via the role attribute OR we will be able to once #4104 is complete?

**Comment by mojavelinux** [comment]
I'm saying you can add a class name via a role if the target of the xref is a path (interdocument xref). If the target of the xref is internal (an anchor), the role is not passed through to the HTML. (Though you could extend the built-in converter to pass it through yourself).

**Comment by gbmhunter** [comment]
@mojavelinux ahh gotcha. Thanks my use case is for internal (anchors), so I'll look into extending the built-in converter.

**Comment by mojavelinux** [comment]
For reference, that would look like:

```rb
class MyHtmlConverter < (Asciidoctor::Converter.for 'html5')
  register_for :html5

  def convert_inline_anchor node
    if node.type == :xref && !(node.attr 'path')
      # do your work here
    else
      super
    end
  end
end
```

See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L1115-L1131 for reference.

**Comment by gbmhunter** [comment]
Thanks for the help @mojavelinux . Now I hoping that hugo (which is what I am using to build a site, it is what is calling Asciidoctor) allows the use to Asciidoctor templates. I'll go investigate.

**Comment by mojavelinux** [comment]
I believe it now does. See https://github.com/gohugoio/hugo/issues/7698#issuecomment-758524496

If you need help using Asciidoctor, I encourage you to ask questions in the community chat at https://asciidoctor.zulipchat.com.

**Comment by mojavelinux** [comment]
It just dawned on me that you can already target internal xrefs using a CSS selector:

```css
a[href^="#"] {
  color: green;
}
```

If this is matching too many elements, you can narrow it down:

```css
#content a[href^="#"]:not([class]) {
  color: green;
}
```

Give that a try.

**Comment by gbmhunter** [comment]
@mojavelinux interesting, I didn't know you could use a form of "regex" in selectors! Alas --- even that is not specific enough though, as I want to only target cross-references to Bibliographic items, and not say cross-references to other sections, images e.t.c in the main content (which also don't have any classes attached to the link element, so the `not` can't work either).

**Comment by mojavelinux** [comment]
> I didn't know you could use a form of "regex" in selectors!

It's actually string matching. But yep, it's been around since CSS 3. See https://www.w3.org/TR/2018/REC-selectors-3-20181106/#attribute-selectors

If you name your IDs consistently, it's possible to look deeper into the anchor value. For example, you could prefix all your bibliography IDs with bib-. If that's not something that you can do, then extending the converter is the right approach for you.
