### ISSUE TITLE
Do add a config option to output compressed file?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#4096]
Is it possible to add a configuration option to output compressed files?

Today, I  found a configuration option `--minify` for `hugo` that it asks `hugo` to minify any supported output format.

I think it is a  useful configuration option. AsciiDoctor should have the same option.

**Comment by mojavelinux** [comment]
Minifying the output is outside the scope of what an AsciiDoc processor should be responsible for. If this is something you'd like to pursue, you can do so using a postprocessor extension.

Please post general questions and future ideas in the community chat at https://asciidoctor.zulipchat.com. The issue tracker should be reserved for reporting bugs and tracking features we've decided to implemented.
