### ISSUE TITLE
Ruby asciidoctor Failed to load AsciiDoc document on post request

### ISSUE THREAD

**Issue by demagnevalCegelec** [asciidoctor/asciidoctor#4097]
Launching the command :

bundle exec asciidoctor -a toc -r asciidoctor-kroki Figures.adoc -D public
return

asciidoctor: FAILED: documentation/Figures.adoc: Failed to load AsciiDoc document - undefined method `request_post' for Net::HTTP:Class

**Comment by abelsromero** [comment]
I think this is already being taken care in https://github.com/Mogztter/asciidoctor-kroki/issues/277 and can be closed.

**Comment by Mogztter** [comment]
Yes, please do not cross-post, this is not related to Asciidoctor core.

**Comment by demagnevalCegelec** [comment]
Sorry, bug with the trace it was not clear if it was an asciidoctor-kroki issue or just in asciidoctor.
My bad !
