### ISSUE TITLE
The docs that explain how to create man pages is confusing

### ISSUE THREAD

**Issue by mbrittb00** [asciidoctor/asciidoctor#4098]
I am wanting to use  asciidoc to help create man pages for some of the utilities I have developed at work.  I was looking at the asciidoctor manual https://asciidoctor.org/docs/user-manual/#man-pages, specifically section 66 on Man Pages in order to make sure I am formatting my file correctly.  It would be great to have an example of a *.adoc file along with a visual of what the corresponding man page looks like.  This section of the manual appears to be trying to do this, but actually ends up creating some confusion, as it appears that it is referencing three different man pages for the various demonstration components.  Early in this section there is a link to the roff man page, which is there to explain the final formatting of the man page, which is what asciidoc is used to convert a *.adoc file into.  A little further down there is an "example" man page in the *.adoc format for the "eve" command which shows how to write the *.adoc file.  Then at the bottom there is a table that is supposed to be cross-referencing lines from the above example and explain what each is.  Unfortunately, that table appears to be a cross-reference into the "asciidoctor" *.adoc file, not the "eve" *.adoc file that is listed above. :(

**Comment by mojavelinux** [comment]
I agree that the documentation on this page is out of sequence, which makes it confusing. I have updated the title of this issue to more accurately describe the problem. I also moved the issue to where the source of this page is now located.
