### ISSUE TITLE
Text copied from single-line code blocks has extra newlines

### ISSUE THREAD

**Issue by dasl-** [asciidoctor/asciidoctor#4100]
Example: https://gist.github.com/dasl-/fd171c4bd219f8a9d608521710bfcf85

Steps to reproduce:
1. Triple click the text in my example gist to select the entire line
2. Copy the selected text
3. Paste the copied text into a text editor

Observe that your text editor now shows content like:
```


this is a test


```

There are two extra line breaks above and below the pasted text (pasted text is 5 lines total). I would prefer if only a single line were pasted.

**Comment by mojavelinux** [comment]
This seems to be an issue with your browser / operating system. I cannot reproduce the issue. And I don't see any extra lines inside the `<pre>` tag in the example you provided. So there's nothing Asciidoctor can do about this as far as I can see.

**Comment by dasl-** [comment]
Interesting, I was testing with firefox 88.0.1 (64-bit) on mac osx 11.3.1. When testing on chrome, pasting the text results in only one extra line break after the message:
```
this is a test

```

Still, this is different behavior than what happens with markdown. Pasting stuff from markdown seems to behave better in my testing. Markdown example: https://gist.github.com/dasl-/3d7604e31ae34502cd578b3ce999bdc6

I understand the problem isnt necessarily with asciidoc, but it is a something that will make me reconsider using asciidoc regardless.

**Comment by mojavelinux** [comment]
It has nothing to do with AsciiDoc. If there is a difference, then it must be caused by the GitHub interface. There are no extra newlines in the HTML source. If this is what would make you reconsider using AsciiDoc, I really have nothing to say.
