### ISSUE TITLE
Two dashline is not rendered correctly in url links

### ISSUE THREAD

**Issue by anilogutveren** [asciidoctor/asciidoctor#4102]
Two dashline is not rendered correctly in url links

For example:   https://matter.i.abc.com/api/channels/administration--claro   

The links is rendered as https://matter.i.abc.com/api/channels/administration-claro

**Comment by mojavelinux** [comment]
This is expected behavior of the AsciiDoc language / processor. If a URL contains replacement character sequences, either they or the whole URL must be escaped. See https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/
