### ISSUE TITLE
Source code highlighting with Pygments but specifying my own syntax theme CSS file?

### ISSUE THREAD

**Issue by rben01** [asciidoctor/asciidoctor#4108]
When using source code highlighting with, say Pygments, (although I believe this applies to Rouge and CodeRay as well), I would like to keep the CSS classes generated by Pygments for code blocks in Asciidoctor's output HTML, but I don't want to use any stylesheet provided by Pygments to style the source blocks -- I would like to use my own syntax theme via a custom CSS file.

<details>
<summary>I.e., I want the HTML to contain something like the following, but have the styles applied to Pygment's classes be ones that I specify, not the ones in <code>pygments-&lt;theme&gt;.css</code>. I'd use my own styles for <code>.tok-kd</code>, <code>.tok-nx</code>, etc. 
</summary>

```html
<div class="content">
<pre class="pygments highlight"><code data-lang="javascript"><span></span><span class="tok-kd">function</span> <span class="tok-nx">f</span><span class="tok-p">()</span> <span class="tok-p">{</span>
        <span class="tok-k">if</span> <span class="tok-p">(</span><span class="tok-nx">foo</span><span class="tok-p">)</span> <span class="tok-p">{</span>
                <span class="tok-nx">bar</span><span class="tok-p">()</span>
        <span class="tok-p">}</span>
<span class="tok-p">}</span></code></pre>
</div>
```

</details>

It's easy enough to just `@import` my own syntax theme CSS file into the main CSS file I'm using (the one specified by `:stylesheet:`), but I can't find a way to prevent Asciidoctor from linking to the Pygments CSS file, which undoes my own CSS. Is there some way to accomplish this, or if not could this functionality be added?

**Comment by mojavelinux** [comment]
Yes, all the behavior of syntax highlighters is controlled using the syntax highlighter adapters, including where, when, and which stylesheet to include. Creating a custom adapter is covered on this page: https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/

If you just want to get rid of the stylesheet reference, use this adapter:

```rb
class MyPygmentsAdapter < (Asciidoctor::SyntaxHighlighter.for 'pygments')
  register_for :pygments

  def docinfo? location
    false
  end
end
```

If you want to point it to another location, such as a URL, use this adapter instead:

```rb
class MyPygmentsAdapter < (Asciidoctor::SyntaxHighlighter.for 'pygments')
  register_for :pygments

  def docinfo location, doc, opts
    slash = opts[:self_closing_tag_slash]
    %(<link rel="stylesheet" href="path/to/pygments-theme.css"#{slash}>)
  end
end
```

In the future, please ask questions about usage in the community chat at https://asciidoctor.zulipchat.com. Thanks!

**Comment by mojavelinux** [comment]
This is now documented here: https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/#extend
