### ISSUE TITLE
Generated reference IDs are not properly replaced everywhere in manpages

### ISSUE THREAD

**Issue by ericzolf** [asciidoctor/asciidoctor#4110]
When writing https://raw.githubusercontent.com/rdiff-backup/rdiff-backup/ericzolf-fix-restrict-doc/docs/rdiff-backup.1.adoc using internal references to sections with auto-generated IDs, the manpage is sometimes not rendered properly, meaning the references aren't replaced with the original name of the section.

For example, the first occurrence of `<<_remote_operation>>` is properly rendered with `REMOTE OPERATION whereas the 2nd occurrence is wrongly rendered as `[_remote_operation]`:

```
rdiff-backup can also operate in a bandwidth efficient manner over a pipe, like *rsync*(1).
Thus you can use ssh and rdiff-backup to securely back a hard drive up to a remote location, and only the differences will be transmitted.
Using the default settings, rdiff-backup requires that the remote system accept ssh connections, and that rdiff-backup is installed in the user's PATH on the remote system.
See the <<_remote_operation>> section for details.
```
![image](https://user-images.githubusercontent.com/3105685/127101246-d9a6e9e8-9ae3-4192-9564-1b42774e302b.png)
vs.
```
--remote-schema _remoteschema_::
Specify an alternate method of connecting to a remote computer.
This is necessary to get rdiff-backup not to use ssh for remote backups, or if, for instance, rdiff-backup is not in the PATH on the remote side.
See the <<_remote_operation>> section for details.
```
![image](https://user-images.githubusercontent.com/3105685/127101303-5ed110c4-c82b-41bb-a775-c26c7965c0c3.png)

Both referencing:

```
== REMOTE OPERATION
```
It seems to be related to the 2nd occurrence being in a more complex construct than a simple paragraph. The rendering in HTML or PDF is correct. The workaround for now is to add an explicit label as in `<<_remote_operation,REMOTE OPERATION>>`, but it's of course ugly.

The command used is roughly `executing ('asciidoctor -b manpage -a revdate="{date}" -a revnumber="{ver}" -o {outfile} {infile}', ('docs', 'rdiff-backup.1.adoc'), ('build', 'rdiff-backup.1'))` (sorry, it's part of our pipeline).

**Comment by mojavelinux** [comment]
I'm not able to reproduce this problem. Can you please tell me which version of Asciidoctor you are using?

I would also appreciate it if you could contribute a test case, or at least a minimal reproducible example that I can use to create a test case.

**Comment by mojavelinux** [comment]
Here's what I see using Asciidoctor 2.0.15.

![remote-schema](https://user-images.githubusercontent.com/79351/127109672-9edee02d-0c3c-44c5-ba1d-bf8fc2c6cb4c.png)

**Comment by mojavelinux** [comment]
Oh, I see what happened. The AsciiDoc source you provided already has your fix applied. I needed to remove that to see the problem. Now I'm able to reproduce it.

**Comment by mojavelinux** [comment]
I see the problem. You are correct that it only happens with a second occurrence. That's because an internal state variable is not being properly reset. That should give me what I need to create a test case.

**Comment by ericzolf** [comment]
You were so fast that I didn't manage to react. Thank you for the fix!
I meant to point you at the commit and pointed you at the branch, sorry for this!

**Comment by mojavelinux** [comment]
No worries. This was a great catch. I can't believe this one slipped through.
