### ISSUE TITLE
Allow curved quotes substitutions when quoting a space

### ISSUE THREAD

**Issue by Jayman2000** [asciidoctor/asciidoctor#4122]
I’m currently working on a pull request for [Fedora](https://docs.fedoraproject.org/en-US/project/)’s [Installation Guide](https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/) ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)). When it’s not required for technical reasons, I would like to change the documentation so that it presents the user with double curved quotes instead of ASCII quotes because that’s what [Unicode recommends](https://www.unicode.org/charts/PDF/U0000.pdf#page=3).

I’m having trouble fixing this sentence from [the Boot Options section](https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/advanced/Boot_Options/#sect-boot-options-sources):

>For example, `\x20` is a white space ("").

When I try to fix that sentence, AsciiDoctor doesn’t substitute my quotes. Including the non-ASCII quotes in the AsciiDoc works, but including characters that aren’t on most keyboards goes against AsciiDoc’s goal of being easy to write.

### Sample document

```
"` `"
```

#### Expected result

“ ”

#### Actual result

"\` \`"

**Comment by mojavelinux** [comment]
While I agree that would be easier to type in this case, it would violate the syntax rules of AsciiDoc and likely impact existing documents. The curved quotes replacement is constrained formatting as described here: https://docs.asciidoctor.org/asciidoc/latest/text/#constrained If such a change were to be made, it would have to be considered by the AsciiDoc language project. (The challenge with crafting shorthand is that it can match in cases you don't anticipate).

The simplest thing I recommend in your case is to use the curved quote characters directly.

```
“ ”
```

If you prefer to keep the abstraction, there are several ways you can type it:

```
"`pass:[ ]`"
```

or

```
"`++ ++`"
```

I think the first of those two makes the intent the most clear, though the second is the shortest shorthand that will work.

You can also use pass in another way to switch the order of substitutions:

```
pass:q,a["`{sp}`"]
```

And, finally, you can use the XML character reference:

```
"`&#32;`"
```

Short of a change to the AsciiDoc language specification, those are your options.

Some have previously suggested having an unconstrained curved quotes replacement for cases such as this:

```
""` `"" or "`` ``"
```

...which is certainly something to consider.
