### ISSUE TITLE
Feature request: Optionally remove asciidoctor meta tag

### ISSUE THREAD

**Issue by rpavlik** [asciidoctor/asciidoctor#4143]
https://github.com/asciidoctor/asciidoctor/blob/eafb271a3afc9c331b9807168a8ecfd092ec700d/lib/asciidoctor/converter/html5.rb#L109

I'm trying to make some doc builds more easily reproducible. While I assume that the same version of AsciiDoctor will probably be required to make things work well, it would be helpful if I could disable that meta tag (the way I can the date ones) by defining or removing an attribute from the document.

**Comment by mojavelinux** [comment]
It seems completely reasonable to me that if the `reproducible` attribute is set on the document (see https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-reference/#compliance-attributes), that it will also suppress this tag. I'll accept a PR with that code change.

**Comment by rpavlik** [comment]
Thanks, I've submitted a PR.

**Comment by mojavelinux** [comment]
Thanks! I'll review tonight and either follow-up or merge.
