### ISSUE TITLE
Use width attribute instead of inline style to specify column width

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4160]
The column width is currently specified using an inline style (e.g., `style="width: 25%;"`). A growing number of users want to avoid the use of inline styles to adhere to avoid CSP warnings (specifically the unsafe-inline restriction on style-src). Although the HTML 5 spec recommends against using the width attribute on the col element, that group is ignoring the dilemma it causes in the era of CSP. There must be a way to specify the width without using inline styles or else its not possible for the user to specify arbitrary widths in a reasonable way (the use of CSS classes for this purpose is unreasonable). Besides, the width attribute is recognized by all major browsers. Without a better alternative, I propose that we move forward using the width attribute for this purpose. (e.g., `width="25%"`)

**Comment by mojavelinux** [comment]
An open question is whether to use the width attribute on the table element for the same reason. Again, it is supported in all major browsers. The only caveat is that the stylesheet wins out. However, there are ways to write the stylesheet so it never applies a width if the width attribute is set directly on the table.

**Comment by mojavelinux** [comment]
It's true that the so-called HTML 5 validator is going to compliant, but CSP is much more important in the modern era. Technically, HTML 5 has no schema, so the validator result is not recognized by the HTML 5 spec.

**Comment by mojavelinux** [comment]
Note that the converter will still rely on the CSS stretch class to set the width of a table to 100%.

**Comment by mojavelinux** [comment]
@Mogztter Do you think this violates semver to make this change in a minor?

**Comment by Mogztter** [comment]
> It's true that the so-called HTML 5 validator is going to complain (...)

@mojavelinux Is this the reason why you are asking if this change violates semver?

I would say it's "safe" since I can't think of any use case where this would create issues... 

> (...) but CSP is much more important in the modern era

I think it's fair point 👍🏻

**Comment by mojavelinux** [comment]
I should have been more clear. I was asking if it violates semver because we are changing the HTML. Although unlikely, it could affect behavior if a custom stylesheet is used. Enough to call it a breaking change, though?

Though your point about it changing the results of the HTML 5 validator as it relates to semver is relevant as well.

**Comment by Mogztter** [comment]
We can argue that the fact that the HTML produced is not compliant with `Content-Security-Policy: style-src 'unsafe-inline';` is actually a "bug" or at least a limitation that needs to be fixed.

> I should have been more clear. I was asking if it violates semver because we are changing the HTML.

We are indeed changing the HTML but it's such a small change.

> Enough to call it a breaking change, though?

In my opinion the potential impact is pretty low. And in the unlikely event that this change has bigger impact than expected we can still release a new bug fix release to revert it.

> Although unlikely, it could affect behavior if a custom stylesheet is used. 

That would be very unlikely, I don't even see how... Using a CSS selector on the attribute `style`?

> Though your point about it changing the results of the HTML 5 validator as it relates to semver is relevant as well.

Yes that's my only concern, I can see companies using HTML 5 validator before publishing content. So if all of the sudden the HTML produced by Asciidoctor is not compliant anymore that could potentially break some publishing pipelines.

**Comment by mojavelinux** [comment]
Thank you for your very thoughtful response. I'm prepared to test the waters by moving forward with this change in 2.1.0. If it turns out to create too much of a stir, we can revert it in a patch release to defer it to the next major.

**Comment by mojavelinux** [comment]
@Mogztter It looks like there was at least one test in Asciidoctor.js that was relying on the use of style attribute in the HTML.
