### ISSUE TITLE
Table column with minimal width to fit content

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctor#4164]
How can I make a column shrink to the minimal width that is enough to display its content, while making the table as wide as possible (full page width) by distributing the remaining available size on the other columns? 

If this matters, the content of each row for that column has only one word.

Perhaps I should use the “[autowidth](https://docs.asciidoctor.org/asciidoc/latest/tables/width/#mix-fixed-and-autowidth-columns)” setting, but I do not understand it. For, say, three columns with the last one having minimal width, I think I need to set the `cols` attribute to `"x%, y%, ~"`, but what should I set as `x` and `y`? What is 100% here? In other words, what is that percentage a proportion of? (Not directly related: shouldn’t this setting be discussed in the [Adjust Column Widths](https://docs.asciidoctor.org/asciidoc/latest/tables/adjust-column-widths/) section?)

I tried to set `x` and `y` to `50` but `asciidoctor-pdf` then refuses to produce a PDF and spits: `Prawn::Errors::CannotFit`. I tried to set `x` and `y` to `25`, then `asciidoctor-pdf` does produce a PDF, but the last column is much larger than required to fit its content.

Possibly related: [SO](https://stackoverflow.com/q/51502874), #1844, and to a lesser extent, #1713 and #3080.

**Comment by mojavelinux** [comment]
Please ask usage questions in the community chat at https://asciidoctor.zulipchat.com. I'll be happy to answer your question there. The issue tracker is reserved for tracking the status of bug reports and change requests.
