### ISSUE TITLE
Interoperability with Docbook/pandoc: xml:id issue for AsciiDoc > Docbook > reStructuredText

### ISSUE THREAD

**Issue by windsurfer1122** [asciidoctor/asciidoctor#4173]
I prefer to maintain my docs with AsciiDoc[tor], but for PyPi.org I convert them into a single reStructuredText with [pandoc](https://pandoc.org/): `AsciiDoc > DocBook > reStructuredText`.
When converting AsciiDoctor's DocBook with pandoc to reStructuredText I get `malformed hyperlink target` warnings in editors (e.g. VS Code), when using the checker for PyPi.org (plain reStructuredText, no Sphinx extensions) and failures when uploading to PyPI.org.

I found out that the syntax warnings are caused by the leading underscore (`_`) in AsciiDoctor's resulting Docbook XML and that spaces are replaced with underscores (`_`) and not dashes (`-`).
If I remove the leading dash and convert the underscores for spaces into dashes, then pandoc recognizes the `xml:id` as the `<title>` and does not create additional hyperlink targets which cause that issue.

I couldn't find any DocBook specifications for [`xml:id`](https://tdg.docbook.org/tdg/5.1/ref-elements.html#common.attributes) what format is the correct one.
The only specs for `xml:id` I could find are from [W3.org](https://www.w3.org/TR/xml-id/) (normalized values #20, [NCname](https://www.w3.org/TR/xmlschema-2/#NCName) [[2]](https://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName)) , that showed that a leading underscore is not necessary if the first character is a letter (**hint!**), but didn't help what should be used for replacing spaces in DocBook xml:ids.
So either AsciiDoctor and/or pandoc are doing something "wrong" or the DocBook specs just have a gap.

That's why I post this issue here to get more information from the community and  to document this interoperability issue plus my workaround (see below).
Maybe there are some other options that would help in my case.
Thanks for reading and any information is heartly welcome.

**Example README.adoc:**
```
= My Great Library
:toc:

== Installation of My Great Library
It's funky, just install it.

== Credits
Me, myself and I.
```

**DocBook result of `asciidoctor -b docbook -o README.xml README.adoc`:**
All xml:ids in the `<section>` tags have a leading underscore and also use underscore to replace the spaces of the `<title>`.
```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>My Great Library</title>
<date>2021-09-22</date>
</info>
<section xml:id="_installation_of_my_great_library">
<title>Installation of My Great Library</title>
<simpara>It&#8217;s funky, just install it.</simpara>
</section>
<section xml:id="_credits">
<title>Credits</title>
<simpara>Me, myself and I.</simpara>
</section>
</article>
```

**reStructuredText result of `pandoc -f docbook -t rst -s --toc -o README.rst README.xml`:**
All xml:ids are converted to additional hyperlink targets with an additional underscore (so double), leading to reStructuredText syntax warnings and failed usage on PyPI.org (conversion to HTML).
```
================
My Great Library
================

:Date:   2021-09-22

.. contents::
   :depth: 3
..

.. __installation_of_my_great_library:

Installation of My Great Library
================================

It’s funky, just install it.

.. __credits:

Credits
=======

Me, myself and I.
```

**My workaround:**
"Fix" the xml:ids in each section tag with GNU awk.
```
gawk -i inplace -e '
{
  if (match($0, /xml:id="[^"]*"/, result)) {
    sub("=\"_", "=\"", result[0])
    gsub("_", "-", result[0])
    print substr($0, 1, RSTART-1) result[0] substr($0, RSTART+RLENGTH)
  } else {
    print $0
  }
}
' README.xml
```

"Fixed" DocBook:
```
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
<info>
<title>My Great Library</title>
<date>2021-09-22</date>
</info>
<section xml:id="installation-of-my-great-library">
<title>Installation of My Great Library</title>
<simpara>It&#8217;s funky, just install it.</simpara>
</section>
<section xml:id="credits">
<title>Credits</title>
<simpara>Me, myself and I.</simpara>
</section>
</article>
```

"Fixed" reStructuredText result of `pandoc -f docbook -t rst -s --toc -o README.rst README.xml`:
No additional hyperlink targets as xml:ids have been recognized as the `<title>`.
```
================
My Great Library
================

:Date:   2021-09-22

.. contents::
   :depth: 3
..

Installation of My Great Library
================================

It’s funky, just install it.

Credits
=======

Me, myself and I.
```

**Comment by mojavelinux** [comment]
You can control the characters Asciidoctor uses in ID generation using the idprefix and idseparator attributes. When Asciidoctor generates IDs, it removes any characters which are not valid in an XML ID. See https://docs.asciidoctor.org/asciidoc/latest/sections/ids/ for details. If these rules are not sufficient, you can set the ID explicitly.

The current behavior is not something we plan to change, certainly not anytime soon. If these rules are refined or redefined, it will be done in the AsciiDoc Language project.

**Comment by windsurfer1122** [comment]
Thanks for pointing out the these settings. I totally missed them.

I adapted the AsciiDoctor conversion by passing these settings on the command line:
`asciidoctor -b docbook -a 'idprefix=' -a 'idseparator=-' -o README.xml README-psntools.adoc`

**Comment by mojavelinux** [comment]
If you have other questions, please feel free to follow-up in the `#users` stream in the community chat at https://asciidoctor.zulipchat.com.
