### ISSUE TITLE
Support multi-paragraph sections in man pages

### ISSUE THREAD

**Issue by hwittenborn** [asciidoctor/asciidoctor#4174]
I'm wanting to do something like this in a man page, but I can't figure out how to do it properly:

```
SECTION
        subsection
            blah blah blah paragraph 1

            blah blah blah paragraph 2
```

I've tried both of the following, but neither are achieving what I want:

```
== SECTION
*subsection*::
  blah blah blah paragraph 1

  blah blah blah paragraph 2
```

```
== SECTION
*subsection*::
blah blah blah paragraph 1

blah blah blah paragraph 2
```

**Comment by mojavelinux** [comment]
If you want subsections, just use subsections in AsciiDoc.

```
== SECTION

=== subsection

blah blah blah paragraph 1

blah blah blah paragraph 2
```

See https://docs.asciidoctor.org/asciidoc/latest/sections/titles-and-levels/

In the future, please ask support questions in the `#users` stream of the community chat at https://asciidoctor.zulipchat.com.

**Comment by hwittenborn** [comment]
Your proposed solution ends up adding 4 spaces at the beginning, instead of the 8 that I'm wanting.

Your solution:

```
SECTION
   subsection
       blah blah blah paragraph 1

       blah blah blah paragraph 2
```

What I want:

```
SECTION
       subsection
           blah blah blah paragraph 1

           blah blah blah paragraph 2
```

Any way I can do it with the indentation I'm wanting?

**Comment by hwittenborn** [comment]
Was just messing around, and this worked out fine:

```
== SECTION
*subsection*::
  blah blah blah paragraph 1
  ++++
  blah blah blah paragraph 2
```

Not sure how safe it is to use, but it's working fine.

**Comment by mojavelinux** [comment]
That's non-nonsensical. But here's a version that is correct that seems to give you what you are after. Granted, subsection is not actually a subsection, but rather a term with a description and an attached paragraph (see https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#list-continuation)

```
== SECTION
*subsection*::
blah blah blah paragraph 1
+
blah blah blah paragraph 2
```

**Comment by hwittenborn** [comment]
Did some testing on my end, and your approach is working just fine unless I'm wanting to introduce indentation into my asciidoc file:

```
= TEST(5)
:doctype: manpage
:hardbreaks:

== SECTION
*subsection*::
  Paragraph one
  +
  Paragraph two with *bolding*
  +
  Paragraph three with *bolding*
```

On my system, that ends up producing the following (disregard the lack of bolding):

```
SECTION
       subsection
           Paragraph one
           +
           Paragraph two with bolding
           +
           Paragraph three with bolding
```

If it shouldn't for some reason, here's my system info:

```
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
> unless I'm wanting to introduce indentation into my asciidoc file:

Indentation is not valid in this location. AsciiDoc is a left-aligned language. So it must be written as:

```
*subsection*::
Paragraph one
+
Paragraph two with *bolding*
+
Paragraph three with *bolding*
```

**Comment by hwittenborn** [comment]
Understood, I'll keep that in mind when I'm writing in the future.

On a side note, is there any reason AsciiDoctor isn't printing a warning for my usage if it isn't valid?

**Comment by mojavelinux** [comment]
The usage is not invalid, it just isn't what you think it is. It's doing exactly what you are asking it to do according to the language rules.
