### ISSUE TITLE
Support the hash parameter for Vimeo private video embeds

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor#4176]
Vimeo introduced a hash parameter (h) that has to be appended to private video URLs in order to be embedded. You need to take the hash of the URL and append it to the iframe src URL. <iframe src="//player.vimeo.com/video/{id}?h={hash}"></iframe>

So this is something new that we'll need to support. We could add support for the `hash` attribute on the video macro.

So for a Vimeo private URL such as https://vimeo.com/617673871/701316cc64 (I changed the last digit as the exemplar) the proposed macro with the `hash` parameter support would look something like:

`video::617673871[vimeo, hash=701316cc64]`

I wonder if as a short-term workaround we could note this as a known issue in the docs then link to this bug ID?

Here is some rough proposed text:

> Vimeo private videos require extra video ID information to be embedded using the video macro.
> 
> If your Vimeo URL looks similar to https://vimeo.com/617673871/701316cc64 (I changed the last digit as the exemplar) the video is set as a private video. You will need to specify both IDs in the macro for the video to display.
> 
> Substitute the / for ?h= in the macro. For example, using the example URL the macro would look like this:
> 
> `video::617673871?h=701316cc64[vimeo]`

**Comment by mojavelinux** [comment]
> I wonder if as a short-term workaround we could note this as a known issue in the docs then link to this bug ID?

I don't want to document workarounds. Let's just focus on fixing the issue.

**Comment by mojavelinux** [comment]
This fix should be backported to v2.0.x since it's necessary for private videos on Vimeo to continue to work.

**Comment by mojavelinux** [comment]
I've decide to support an alternative format as a shorthand for using the hash attribute.

```
video::617673871/701316cc64[vimeo]
```

This is consistent with the URL of the video on Vimeo and builds on the syntax already in used for youtube videos (although with a different purpose).

**Comment by jaredmorgs** [comment]
That feels like a good call, Dan. It will be more intuitive for users that
way.
