### ISSUE TITLE
Column style offset by span

### ISSUE THREAD

**Issue by per42** [asciidoctor/asciidoctor#4177]
```asciidoc
[cols=">,^,"]
|===
|a |b |c

.2+|1

|2 |3

|2 |3
|===
```
![image](https://user-images.githubusercontent.com/1432278/135260224-567b795a-80cd-4eae-8cca-c9aadd10c548.png)

Asciidoctor 2.0.10

**Comment by mojavelinux** [comment]
When you use rowspans, you have to set the alignments directly on the cells. This is a well known issue. See #989 and #1558.
