### ISSUE TITLE
How to notate tables with Markdown?

### ISSUE THREAD

**Issue by brimstone** [asciidoctor/asciidoctor#4178]
I love this project and using asciidoc so far for one personal project has been great. I'm trying to interoperate with a another project using markdown, and I'm having some issues. At the bottom of https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/ there's a mention:
> Certain Markdown flavors, such as Markdown Extra, support additional features such as tables and description lists. However, since these features don’t appear in “plain” Markdown, they’re not included in the comparison table. But they’re supported natively by AsciiDoc.

Some formatting like headings and constrained monospace do work, but tables don't seem to render correctly. What's the right way to either 1) enable Markdown Extra and get table support, or 2) notate tables in a way that both markdown and asciidoc render as a table?

Thanks!

**Comment by mojavelinux** [comment]
I think you are misunderstanding the purpose of this project. This is an AsciiDoc parser, not a Markdown parser. While it's true there are a few overlaps between the two languages, they are not the same markup language. The table syntax is not one of the areas where they overlap. Asciidoctor only supports the table syntax as defined by AsciiDoc. See https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/

**Comment by mojavelinux** [comment]
If you need to convert your Markdown syntax to AsciiDoc, you may be interesting in [kramdown-asciidoc](https://github.com/asciidoctor/kramdown-asciidoc). If you have other general questions about AsciiDoc, please ask them in the `#users` channel of the community chat at https://asciidoctor.zulipchat.com.
