### ISSUE TITLE
Variable definition inside table doesn't work

### ISSUE THREAD

**Issue by gdromard** [asciidoctor/asciidoctor#4197]
I would like to do something like this from a main file:

```
[width=100%,cols="~,40,~,~,~",stripes=even]
|===
| ID |Action | Actor | Date | Comment

:momname: MOM-001
include::{momname}-actions.asciidoc[tag=actions]
:momname: MOM-002
include::{momname}-actions.asciidoc[tag=actions]
|===
```
Having file `MOM-001-actions.asciidoc` containing the following:
```
[width=100%,cols="~,40%,~,~,~",stripes=even]
|===
| ID |Action | Actor | Date | Comment

//tag::actions[]
| {momname}-1 |Action n°1 | TT | 26/11/2021 |
| {momname}-2 |Action n°2 | DD| 02/11/2021 | 
//end::actions[]
|===
```

Am I doing something wrong ??

Regards,
Gabriel

**Comment by mojavelinux** [comment]
Your observation is correct. You cannot set document attributes in the middle of a table. That's not a valid location for document attribute entries.

You can set document attributes in an AsciiDoc table cell, though they are only scoped to that table cell.

In the future, please direct usage questions to the community chat at https://asciidoctor.zulipchat.com. Thanks!

**Comment by gdromard** [comment]
Ok, thank you for your answer.
Are you saying that I can not do what I tried to? Is there another way to do it?
