### ISSUE TITLE
Improve DocBook translation of checklist

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#4199]
The attribute `mark` in the DocBook `itemizedlist` element is intended for giving a symbolic name for the type of bullet used for the items. DocBook does not provide predefined names of bullet types,  its up to the reader to decide the interpretation of the given names.  A `listitem` element may have the attribute `override` , which allows to give the type of the bullet for a single list item, overriding the default of the parent list. 

For lists with a common bullet type, asciidoctor follows this intention, e.g. setting `mark=square`, letting the DocBook reader decide how square bullets shall be rendered. However, see the example checklist in the AsciiDoc manual, this is currently translated as follows:

```
<itemizedlist mark="none">
<title>A titled checklist</title>
<listitem>
<simpara>&#10003; checked</simpara>
</listitem>
<listitem>
<simpara>&#10003; also checked</simpara>
</listitem>
<listitem>
<simpara>&#10063; not checked</simpara>
</listitem>
<listitem>
<simpara>normal list item</simpara>
</listitem>
</itemizedlist>
```

Here the bullet marks are hardcoded using unicode symbols, which makes them harder to extract and customize. (Also, one may want different horizontal layout of a list item having a mark compared to an unmarked item.) I would instead expect a translation utilizing the `override` attribute with suitable symbolic names, for example:

```
<itemizedlist mark="checked">
<title>A titled checklist</title>
<listitem>
<simpara>checked</simpara>
</listitem>
<listitem>
<simpara>also checked</simpara>
</listitem>
<listitem override="unchecked">
<simpara>not checked</simpara>
</listitem>
<listitem override="none">
<simpara>normal list item</simpara>
</listitem>
</itemizedlist>
```

**Comment by mojavelinux** [comment]
The purpose of using symbols for Unicode for a checklist is so that it would work out of the box. If you prefer different output, you are free to customize it using an extended converter or custom converter templates. If we were to remove the symbols and replace them with an unrecognized attribute, then users would complain that it doesn't work and that's not acceptable.
