### ISSUE TITLE
Adding %collapsible for other block styles

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor#4201]
Is it reasonable to support %collapsible for non-example block types, esp. sidebar blocks? The generated HTML for sidebars seems to pose no structural reason this won't work - I have manually retrofitted it in a few places for testing - although some CSS changes would probably be needed to account for the details/summary tag structure affecting the CSS hierarchy of the block..

**Comment by Oblomov** [comment]
Description lists are another block that could benefit from this.

**Comment by mojavelinux** [comment]
I disagree. A collapsible block is a specific type of block. It makes an HTML [disclosure element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). We're not just producing an expandable phrase / term. That's not the same thing semantically. If you need general collapsible behavior, you can do so by adding custom JavaScript to the HTML page that responds to a role. If you need help with doing that, please ask in the project chat at https://chat.asciidoctor.org.
