### ISSUE TITLE
Specifing "window=_blank" for a url causes the next underscore in the paragraph to be misinterpreted

### ISSUE THREAD

**Issue by cod3licious** [asciidoctor/asciidoctor#4202]
I noticed some curious behavior when specifying that a url should be opened in a new window. This is the code, for the same link normally and to be opened in a new tab:
```
here is some https://developers.google.com/[url] (and then some italic text: _bla bla_)

here is some https://developers.google.com/[url,window=_blank] (and then some italic text: _bla bla_)
```
This is the result: the first looks as expected, for the second the first underscore is not interpreted correctly (probably, because of the "_blank" in the url attributes):

<img width="433" alt="Screenshot 2021-11-10 at 11 50 46" src="https://user-images.githubusercontent.com/1093567/141100703-2df094bd-70d8-43c2-bed2-c6c6b772cbff.png">

This is the output of `asciidoctor --version` (on macOS 10.15.7):
```
Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin19]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
This is an unfortunate side effect of the language. The underscore is making a constrained match. There are at least three solutions:

```
here is some https://developers.google.com/[url^] (and then some italic text: _bla bla_)
```

or

```
here is some https://developers.google.com/[url,window=\_blank] (and then some italic text: _bla bla_)
```

or

```
here is some https://developers.google.com/[url,window=_blank] (and then some italic text: __bla bla__)
```

**Comment by graphitefriction** [comment]
I've confirmed that the solutions for this scenario (escape with `\` and `^` shorthand are in the docs: https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-attribute-parsing/#target-a-blank-window
