### ISSUE TITLE
Is it possible to use attributes recusively?

### ISSUE THREAD

**Issue by hacker-DOM** [asciidoctor/asciidoctor#4207]
It would be great if I could do something like the following, but it seems to me it is not currently supported:

```asciidoc
// initialize a counter
{counter:item}
// Set 1-title to string
:{counter}-title: Item title!
// Print 1-title
{{counter}-title}
```

**Comment by mojavelinux** [comment]
It is not possible to use an attribute reference inside an attribute reference. We feel strongly that this kind of syntax will make the syntax overly complete. If you need this kind of computed behavior, you should be looking instead at creating an extension, which can manipulate the document in a whole host of ways.

In the future, please ask question about the syntax in the `#users` channel of the community chat at https://asciidoctor.zulipchat.com. Thanks!
