### ISSUE TITLE
Localization: inversion in French translations

### ISSUE THREAD

**Issue by cyChop** [asciidoctor/asciidoctor#4212]
French translations for warning and caution seem inverted.

"A warning" is "un avertissement."
"Caution!" is "Attention !"

Right now, the attributes-fr.adoc contains the following:

```asciidoc
:caution-caption: Avertissement
// ...
:warning-caption: Attention
```

According to the French translations, the opposite would make more sense and be more consistent with other locales. I verified with the EN, DE and ES translations, which would all go the same way (Caution = Achtung = Attention VS Warning = Warnung = Avertissement).

**Comment by mojavelinux** [comment]
Please consult this explanation and let me know if your assertion still holds. https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/#caution-vs-warning If so, I'm happy to change it.

**Comment by cyChop** [comment]
Still holds. I've read this distinction many times (almost every time I start a new AsciiDoctor/Antora documentation project). It was why I went and checked the other translations to start with. :)

[The link in the description](https://www.differencebetween.com/difference-between-caution-and-vs-warning/) also makes me think this would be a better translation.

@Mogztter knows the project better though. His insight will likely be more relevant, and I'm interested to know where I went wrong if I did. :)

**Comment by Mogztter** [comment]
I think you are right, warning should be "Avertissement" or "Mise en garde" and caution should be "Attention" ou "Prudence" (which is literally "act carefully")

**Comment by mojavelinux** [comment]
When I open up the lid of my pressure cooker, it says "Mise en garde" (French) above Caution (English) with the caution symbol. So I think we should avoid using this term for Warning as it's already being used for caution in consumer products. Plus, I think using a single word for the label is in line with the English translations.
