### ISSUE TITLE
Glossary divisions

### ISSUE THREAD

**Issue by manuel-rubio** [asciidoctor/asciidoctor#4217]
I was trying to get working the glossary divisions, at the moment I'm injecting the XML as this:

```
+++++++++++++++++++++++++++++++
<glossdiv>
    <title>A</title>
+++++++++++++++++++++++++++++++
...
+++++++++++++++++++++++++++++++
</glossdiv>
+++++++++++++++++++++++++++++++
```

Is there any better way to do it?

**Comment by Mogztter** [comment]
You could extend the built-in DocBook5 converter and provide your own implementation for `convert_dlist` when the style is `glossary`: https://github.com/asciidoctor/asciidoctor/blob/d4b576c990ec001b13c1ea298b1ead91e8cf01f1/lib/asciidoctor/converter/docbook5.rb#L98-L152

I don't think that AsciiDoc has a syntax to group items in a description list but you could use something like:

```asciidoc
.water
[glossary]
river:: a large natural stream of water flowing
rain::
	water falling from the sky

.dirt
[glossary]
mud:: wet, cold dirt
sand::
	a loose granular substance, typically pale yellowish brown, resulting from the erosion of siliceous and other rocks
```

In your converter, you will need to aggregate all the description lists with the glossary style and use the title as a glossary division title.

**Comment by Mogztter** [comment]
In the future, please ask usage questions in the community chat at https://asciidoctor.zulipchat.com. We use the issue tracker for reporting bugs and submitting feature requests.
