### ISSUE TITLE
:footnote-number:

### ISSUE THREAD

**Issue by aowss** [asciidoctor/asciidoctor#4218]
Hi,

Is it possible to add a `footnote-number` document attribute in the same way we have `table-number` ?
This would allow us to have footnotes that use the arabic-indic numbers.

Thanks

**Comment by Mogztter** [comment]
I didn't know it was possible to use Arabic numbers on tables, that's very cool:

```
:table-number: ٠

.First table
[opts="header",cols="1,1"]
|===
|Foo
|Bar

|1
|2
|===

.Second table
[opts="header",cols="1,1"]
|===
|Foo
|Bar

|1
|2
|===
```
![image](https://user-images.githubusercontent.com/333276/146672315-05ce4e6d-3566-4bf5-951a-e858aa6f37f6.png)

And it seems to be working on footnotes as well:

```
:footnote-number: ٠

The hail-and-rainbow protocol can be initiated at five levels:

. doublefootnote:[The double hail-and-rainbow level makes my toes tingle.]
. tertiary
. supernumerary
. supermassive
. apocalyptic

A bold statement!footnote:disclaimer[Opinions are my own.]

Another outrageous statement.footnote:disclaimer[]

Asciidoctor version: {asciidoctor-version}
```

![image](https://user-images.githubusercontent.com/333276/146672432-e7014795-0912-4b56-9107-8539622038e4.png)


Which version are you using?

**Comment by aowss** [comment]
I tried it even though it was not documented. It would be good to add it to the documentation.

I applied it to the root document and it didn't apply to included documents.
When I applied it to the specific document, it worked. **thanks**.

But the formatting isn't right as you can see in the picture

![Screen Shot 2021-12-19 at 12 29 46 PM](https://user-images.githubusercontent.com/6297886/146684730-553647a8-7163-4fbe-9a79-1dd96be5d3e9.png)

**Comment by Mogztter** [comment]
> I tried it even though it was not documented. It would be good to add it to the documentation.

You can click on "Edit this Page" (top right corner) to add it to the documentation: 

![image](https://user-images.githubusercontent.com/333276/146686442-42edf0f9-64ec-4917-8cc3-03de14fd223d.png)

I believe it should be added in the "Localization and numbering attributes" table: https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/#builtin-attributes-i18n

> I applied it to the root document and it didn't apply to included documents.
When I applied it to the specific document, it worked. thanks.
> But the formatting isn't right as you can see in the picture and you can't click the number to go back to the original text, as is the case with standard footnotes:

I cannot reproduce neither of these issues, could you please provide a reproduction case with a sample AsciiDoc document and the command you are running?

**Comment by aowss** [comment]
Thanks again for your prompt responses,

- I agree it should be added there

- I applied this style

```
#footnotes .footnote a:first-of-type {
  margin-left: 0em
}
```
and it's now working properly.

if you can't reproduce it, it probably means that it was introduced by the fact that i use this css ( my css skills are close to 0 so i might have messed things up while trying to get the layout i wanted )

[main.css.zip](https://github.com/asciidoctor/asciidoctor/files/7741398/main.css.zip)

**Comment by Mogztter** [comment]
> and it's now working properly.

Awesome 👍🏻 

> if you can't reproduce it, it probably means that it was introduced by the fact that i use this css ( my css skills are close to 0 so i might have messed things up while trying to get the layout i wanted )

Probably, might be a CSS/font issue, here's what I see using latin alphabet:

![image](https://user-images.githubusercontent.com/333276/146773517-782eb303-937a-4903-bf1b-a12c42969458.png)

Even though everything seems to be working as intended, we can keep this issue open until this feature is documented. I can update the title of this issue to reflect that.

If you have additional usage questions, please ask in the community chat at https://asciidoctor.zulipchat.com.

**Comment by aowss** [comment]
Thanks for everything.
I double checked and the attribute is propagated to included documents ( this was my mistake, sorry ).

I created a PR to update the documentation https://github.com/asciidoctor/asciidoc-docs/pull/107.

I think Asciidoctor is not far from handling Arabic well out of the box. It would be nice to get the exact result without needing any css.

**Comment by Mogztter** [comment]
> I double checked and the attribute is propagated to included documents ( this was my mistake, sorry ).

No worries.

> I created a PR to update the documentation asciidoctor/asciidoc-docs#107.

Awesome, thanks 👍🏻 

> I think Asciidoctor is not far from handling Arabic well out of the box. It would be nice to get the exact result without needing any css.

That's great to hear!
I think the main issue is that you cannot enable RTL support using an AsciiDoc attribute: https://github.com/asciidoctor/asciidoctor/issues/1601 

It would definitely help us if you could provide a sample AsciiDoc document and maybe highlight on a screenshot (using the default CSS) where (and potentially why) it requires some adjustments. Since this issue is about `footnote-number`, you should comment on #1601 (not on this issue). I think that would give us a clear understanding on what needs to be done when `:text-direction: rtl` is defined.

**Comment by aowss** [comment]
i will do that
