### ISSUE TITLE
Add a back to top button document attribute

### ISSUE THREAD

**Issue by HarshKapadia2** [asciidoctor/asciidoctor#4220]
Add a `:back-to-top-btn:` document attribute using the [Intersection Observer API](https://caniuse.com/?search=intersection%20observer).

[Example](https://harshkapadia2.github.io/git_basics/#_git_internals) (bottom right):

![image](https://user-images.githubusercontent.com/50140864/146793791-06a85475-3c70-48de-bd37-7ac2657f4e2f.png)

**Comment by mojavelinux** [comment]
There a myriad of ways that this could be implemented and I don't think there is universal agreement on how it should look or work. Instead, I have create a docinfo extension in that lab that adds this widget to the page. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/main/lib/back-to-top-docinfo-processor.rb If that garners interested and we can decide how that might be integrated into the built-in HTML converter, then we can consider promoting it.
