### ISSUE TITLE
Link to a tagged region

### ISSUE THREAD

**Issue by dfarley1** [asciidoctor/asciidoctor#4221]
Hi! I'm wondering if it's possible to create a link to a tagged region (or singular tag) similar to how they can be [included](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/)? Sometimes the relevant code blob is too big/cumbersome to include directly, but we want to provide a link to the source code to explore without relying on line numbers.

It'd also be cool to have a link to the tagged region right above/below the include itself so that readers can dive in further without needing to manually search for the tag or anything like that.

Is any of this possible?

**Comment by mojavelinux** [comment]
This is only possible if the include file contains an ID or anchor that can be used as the target of an xref. The include tags themselves are not part of the document structure and thus not referencable. Making them referencable is very far outside of the scope of this project and not something we ever plan to pursue.
