### ISSUE TITLE
docbook table generation

### ISSUE THREAD

**Issue by aowss** [asciidoctor/asciidoctor#4223]
Hi,

i might be doing something wrong but while investigating Arabic support i tried to use the docbook backend.

I used the following command to generate the xml file : `asciidoctor -a lang=ar -b docbook فقه.adoc`

I then tried to process that using https://github.com/docbook/xslTNG but Norman Walsh mentions in https://github.com/docbook/xslTNG/issues/130#issuecomment-997380611 that he thinks that the generated table has a wrong structure.

Is my asciidoc table wrong ? 
When i use the html backend, that table renders properly and the generated html is valid

[files.zip](https://github.com/asciidoctor/asciidoctor/files/7762794/files.zip)
![Table](https://user-images.githubusercontent.com/6297886/147098038-9130110c-7e74-49e3-bc45-7e484674c90d.png)

**Comment by mojavelinux** [comment]
This problem is outside the scope of Asciidoctor as it pertains to the DocBook toolchain. Unless you can identify an error in the DocBook markup itself, this issue should be filed with that other project.
