### ISSUE TITLE
-a For Mantitle Attribute Does Not Take Precedence Over Source .adoc File

### ISSUE THREAD

**Issue by lemosbash** [asciidoctor/asciidoctor#4224]
**What is the operating system used?**
Linux 5.10.87-1-lts #1 SMP Fri, 17 Dec 2021 10:43:27 +0000 x86_64 GNU/Linux

**Wich is asciidoctor's version?**

Asciidoctor 2.0.16

**Wich version of gem is being used?**
3.2.29

**Wich version of ruby is being used?**
3.0.3p157 (2021-11-24 revision 3fb7d2cadc

_Bug description:_

Taking a file named conforming-sample.adoc, with the following content: 
````
    = sample(1)
    Lemos
    v1.0
    :doctype: manpage
    :mansource: foo
    :manmanual: bar
    
    == Name 
   
     Lorem - ipsum  dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
````

A manpage file can be generated with no issues, as expected.

But, some files may need changes on the title, since they are meant to be used to another stuff that do not comply with the manpage standards, this leads us to the -a flag, wich sets attributes, like **mantitle**, this can be used to turn non-compliant documents into documents that comply with the desired standard.

As the **manual entry** for asciidoctor says:

_Command-line attributes take precedence over attributes defined in the source file unless either the name or value ends in @._

But, this is not the noticed behaviour for the mantitle attribute, when used on a non-conforming file named non-conforming-sample.adoc, with the following content:

````
= sample
Lemos
v1.0
:doctype: manpage
:mansource: foo
:manmanual: bar

== Name 

 Lorem - ipsum  dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
````

The command **asciidoctor -v -a mantitle="sample(1)" -d manpage -b manpage non-conforming-sample.adoc** will give the following output:

_asciidoctor: ERROR: non-conforming-sample.adoc: line 1: non-conforming manpage title_

Wich shows the title included into the source file is taking precedence over the command-line attribute.

**Comment by mojavelinux** [comment]
The `mantitle` attribute is a derived attribute, and thus cannot be overridden. The correct way to override the `mantitle` and `manvolnum` attributes is to override the `doctitle` attribute (from which these attributes are derived).

```
asciidoctor -a doctitle="sample(1)" -d manpage -b manpage sample.adoc
```

However, note that only changes the `mantitle`, not the `manname` and `manpurpose`. The latter two are computed from the Name section by default. I have added a section to the documentation that describes how to accomplish what it is that I think you're trying to do. See https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/#repurpose-a-man-page
