### ISSUE TITLE
How to do vertical text direction and multiple header span in table?

### ISSUE THREAD

**Issue by wxguy** [asciidoctor/asciidoctor#4232]
**Asciidoctor 2.0.16** 

Trying to accomplish the table header as shown below:-
![asciidoctor-comples-table](https://user-images.githubusercontent.com/9054645/147767582-4c64e5d9-bbba-48d4-b37f-0bd7432bd9ab.png)

Here is what I have done:-

```
|===
2+|Wind force .2+|Wind speed Kt .2+|Visual wind force indicators observed onboard 3+|Sea surface state with wind waving

|a |b |c |d |e
|===

```
But it appears that we can not apply row and  span on header. I am getting the below result:-

![asciidoctor-comples-table-result](https://user-images.githubusercontent.com/9054645/147767817-05f38342-99de-4157-aadd-d510798c304d.png)

Can someone help to move in right direction please...

**Comment by mojavelinux** [comment]
I'd like to ask that you direct usage questions to the project chat at https://asciidoctor.zulipchat.com. The issue tracker is reserved for bug reports and feature requests. Thanks!
