### ISSUE TITLE
Asciidoctor(j) - Direct generated inlined svg possible?

### ISSUE THREAD

**Issue by ThraaxSession** [asciidoctor/asciidoctor#4236]
Hi!

I am trying to generate my plantuml diagram with these options:
`[plantuml, architecture-diagram, svg, svg-type="inline"]`

I took those options (as I can't find the documented) here: 
https://github.com/asciidoctor/asciidoctor/issues/1301#issuecomment-222620678

Currently the svg will be generated somewhere in the project folder where my app can't find it. As I suspect asciidoctorj-diagram will put it directly in the HTML file.

Can you help me to solve it?

The error:
![image](https://user-images.githubusercontent.com/3085830/147997550-f7b4007c-36a9-4b9d-8c33-473b1e8b9e25.png)

My code how I generate it:
```kotlin
val adoc = this.javaClass.getResource("/docs/asciidoc/index.adoc")!!.readText()

        val asciidoc = Asciidoctor.Factory.create()
        asciidoc.requireLibrary("asciidoctor-diagram")
        val attr = Attributes.builder()
            .tableOfContents(true)
            .tableOfContents(Placement.LEFT)
            .build()

        val options = Options.builder()
            .headerFooter(true)
            .backend("html5")
            .build()
        options.setAttributes(attr)

        return asciidoc.convert(adoc, options)
```

**Comment by mojavelinux** [comment]
Please ask usage questions in the project chat at https://asciidoctor.zulipchat.com. The issue tracker is reserved for verified bug reports and feature requests. Thanks!
