### ISSUE TITLE
Hyperlinks with `...` do not render correctly

### ISSUE THREAD

**Issue by MLNW** [asciidoctor/asciidoctor#4238]
I'm trying to create a changelog in the style described here: https://keepachangelog.com/en/1.1.0/

For this purpose, I want to use Asciidoc as the resulting changelog is integrated into my Antora based documentation.

The changelog style liked above adds links to GitHub comparison pages to show changes between different versions.
To replicate this I used the following link definitions:

```adoc
:base: https://github.com/DAG-OS/ansible-role-git
:v1_0_0: {base}/compare/3d73638...v1.0.0[v1.0.0]
:unreleased: {base}/compare/v1.0.0...HEAD[Unreleased]
```

The problem is that the resulting links are mangled so that GitHub does not understand them:

* Expected: <https://github.com/DAG-OS/ansible-role-git/compare/v1.0.0...HEAD>
* Actual: <https://github.com/DAG-OS/ansible-role-git/compare/v1.0.0%E2%80%A6%E2%80%8BHEAD>

I tried to fix this by applying the workaround mentioned [here](https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/) but none of them solved the issue.

### Workaround

For now, I use two periods instead of three which produces a working link, though not exactly the one I want.

Clicking on the [resulting link](https://github.com/DAG-OS/ansible-role-git/compare/v1.0.0..HEAD) GitHub states:

> This is a direct comparison between two commits made in this repository or its related repositories. View the default comparison for this range [here](https://github.com/DAG-OS/ansible-role-git/compare/v1.0.0...HEAD).

**Comment by mojavelinux** [comment]
Replacements come very last in substitutions, so simply defining the URL as an attribute is not sufficient. Instead, you will need to escape the ellipses using a backslash.

```
:base: https://github.com/DAG-OS/ansible-role-git
:v1_0_0: {base}/compare/3d73638\...v1.0.0[v1.0.0]
:unreleased: {base}/compare/v1.0.0\...HEAD[Unreleased]

{v1_0_0}
```

In the future, please direct usage questions to the project chat at https://asciidoctor.zulipchat.com.

**Comment by mojavelinux** [comment]
The other option is to remove the replacements substitution at the point where the attribute is referenced:

```
pass:n,-r[{v1_0_0}]
```

That says "apply normal substitutions, but not replacements"
