### ISSUE TITLE
The ifeval is expanded by preprocesser before attributes are set

### ISSUE THREAD

**Issue by Light6533** [asciidoctor/asciidoctor#4242]
I found that the ifeval of asciidoctor have some issue when i use plugin(preprocessor) to build document.
It will expand all the ifeval at the phase preprocessor is parsing document(function has_more_lines?), which is before parsing attributes (function Parser.process_attribute_entry()), so that all the ifeval can't expand correct attribute to compare.

**Comment by mojavelinux** [comment]
You're observation is not abnormal. The preprocessor has side effects and can change how parsing is performed. Unless you are prepared to address those side effects, I strongly recommend not using a preprocessor to read lines.

In the future, please ask usage questions in the project chat at https://asciidoctor.zulipchat.com. If we determine there that there is a bug in the processor, then we can proceed with an issue. This helps keep the project maintainable.
