### ISSUE TITLE
Create Mallard backend

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#425]
Create a Mallard backend based on this work:

https://groups.google.com/group/asciidoc/browse_thread/thread/ac297b7365d90fa0

Mallard is similar to DocBook, except it seems to be a much easier publishing toolchain to install and use.

http://projectmallard.org/

**Comment by bk2204** [comment]
Okay.  It looks like this is in a generally useful state at https://github.com/bk2204/asciidoctor-mallard.  It can convert the Asciidoctor User Manual (with XML fixups for the entities) and it has doctest tests as well.

Comments or thoughts on things that need improving?

**Comment by jirutka** [comment]
Great work! I'll look at it soon. I'd like to merge the classes for testing XML-based backends into DocTest core.

**Comment by mojavelinux** [comment]
I agree, the Mallard backend is looking really excellent. Great work @bk2204!

There are a handful of things I'd like to get fixed before we bring it into the Asciidoctor organization. I've sent 10 independent pull requests which should merge cleanly. If you have trouble merging, just let me know.

I'm also excited to say that I got a chance to use doctest for the first time. It's truly an excellent tool. I got all the tests passing except for stuff that deals with math. We'll need to handle that separately since we probably need to do some processing with AsciiMath or the LaTeX parser.

I've also converted on of the Gnome guide pages to AsciiDoc and Mallard. It would be nice to be able to use this in doctest to very the output of a whole document. I've shared it in a gist for reference.

https://gist.github.com/mojavelinux/17a7b31e1ae5b55c6c05

I did some cleanup on the original Mallard file (threw out some things we aren't producing and formatted it) so that it serves as a target for our converter.

Once the changes are made and all tests are passing, I'd like to see what Shaun McCance things about it.

**Comment by mojavelinux** [comment]
The mallard backend now exists here: https://github.com/asciidoctor/asciidoctor-mallard. Shall we close this issue now or wait for an alpha release first?

**Comment by mojavelinux** [comment]
If Mallard supports inline MathML, we should be able to reuse the [asciimath](https://rubygems.org/gems/asciimath) gem in that backend as well.

**Comment by bk2204** [comment]
I'd close this.  I'll try to get an alpha release up on rubygems this weekend.

**Comment by mojavelinux** [comment]
Cool. Thanks @bk2204!

**Comment by mojavelinux** [comment]
@bk2204 I had a bunch of local changes I had prepared but never submitted for the Mallard backend. I took the time to get everything synced so there's no outstanding work from my end. I did some cleanups as well with the repo. There are still a few missing converters, but I'm happy with where it is for an alpha release. I think that should help encourage more participation as well.
