### ISSUE TITLE
Source code block with < and > not generated correctly

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor#4253]
Consider following minimal document

````
= dummy
fekir

[source, cpp]
----
constexpr const node<4> tree
{
	node<4 >
	{
	}
};

constexpr const node<4> tree2
{
	node<4>
	{
	}
};
----
````

with `Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)`

the generated HTML looks like (I can eventually attach the file)

````
dummy
fekir

constexpr const node<4> tree
{
	node<4 >
	{
	}
};

constexpr const node<4> tree2
{
	node(4)
	{
	}
};
````

Note that in the second code snippet, the last `node<4>` has been rewritten as `node(4)`.
If I add some space, like in `node<4 >`, then `<>` are not replaced by `()`.

The offending HTML is

````
constexpr const node&lt;4&gt; tree2
{
	node<b class="[conum]()">(4)</b>
	{
	}
};
````

instead of

````
constexpr const node&lt;4&gt; tree
{
	node&lt;4&gt;
	{
	}
};
````

**Comment by elextr** [comment]
It looks like the `<4>` at end of line is being detected as a [callout](https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/)

**Comment by mojavelinux** [comment]
That's correct. You can disable callouts for a block using the -callouts incremental substitution.

```
[,cpp,subs=-callouts]
----
constexpr const node<4> tree
{
	node<4 >
	{
	}
};

constexpr const node<4> tree2
{
	node<4>
	{
	}
};
----
```
