### ISSUE TITLE
Inline stem equations with plus sign in superscript renders incorrectly

### ISSUE THREAD

**Issue by plevold** [asciidoctor/asciidoctor#4254]
There seems to be some incorrect handling of inline `stem:[]`-equations when using `latexmath` and the equations contain multiple plus signs as superscripts. Or maybe I'm doing something wrong? Take the following minimal example:

```asciidoc
= Example
:stem: latexmath

These inline equations works:

* stem:[S^{+}]
* stem:[S^{+} + S^{-}]

But these don't:

* stem:[S^{+}] and stem:[S^{+}] is not properly separated
* stem:[S^{+} + S^{+}] is missing superscript plus signs

Non-inlined works fine though:

[stem]
++++
S^{+} + S^{+}
++++
```

Building with `asciidoctor example.adoc` yields the following output:
![image](https://user-images.githubusercontent.com/10157556/153431134-91f43865-3638-44a5-b0d9-26a5e469c9e2.png)

The generated HTML looks incorrect:
```html
<div class="paragraph">
<p>But these don&#8217;t:</p>
</div>
<div class="ulist">
<ul>
<li>
<p>\(S^{}] and stem:[S^{}\) is not properly separated</p>
</li>
<li>
<p>\(S^{} + S^{}\) is missing superscript plus signs</p>
</li>
</ul>
</div>
```

I'm using the latest Ruby asciidoctor version to produce this:
```
❯ asciidoctor --version
Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
This happens because the + formatting pair takes precedence over the stem inline macro. Therefore, in certain circumstances, the + formatting pair has to be escaped to tell the processor to ignore it.

```
* stem:[S^{\+}] and stem:[S^{+}]
* stem:[S^{\+} + S^{+}]
```

This is one of the side effects of mixing two markup languages in the same line.

**Comment by mojavelinux** [comment]
If you need further assistance, I encourage you to ask questions in the project chat at https://asciidoctor.zulipchat.com.
