### ISSUE TITLE
Is it possible to get the raw title of a block?

### ISSUE THREAD

**Issue by Alwinator** [asciidoctor/asciidoctor#4259]
I need to fix [an issue](https://github.com/Alwinator/asciidoctor-lists/issues/6) in my asciidoctor-lists extension. To do this, I would need the raw title attribute, not just a string. How is it possible to get the `@title` from outside?

https://github.com/asciidoctor/asciidoctor/blob/5206b40fcd8dc8f79e2097a307ef530b8b82d789/lib/asciidoctor/abstract_block.rb#L286-L290

**Comment by Mogztter** [comment]
I'd like to ask that you direct usage questions to the project chat at [asciidoctor.zulipchat.com](https://asciidoctor.zulipchat.com/). The issue tracker is reserved for bug reports and feature requests. Thanks!

**Comment by Alwinator** [comment]
@Mogztter Sorry, I've put here because it is a programming question. See you on zulipchat.com.

**Comment by mojavelinux** [comment]
Zulip is appropriate for all question types, whether about AsciiDoc or the
programming APIs.
