### ISSUE TITLE
Using pipe symbol in source block does not work inside table cell

### ISSUE THREAD

**Issue by anotherandi** [asciidoctor/asciidoctor#4261]
When using the pipe symbol inside of a source code block in a table cell, the pipe symbol is interpreted as cell separator.

```
[cols="1,4a", options="unbreakable"]
|===
| Code |

[source,cpp]
----
if (a | b)
----
|===
```

**Comment by mojavelinux** [comment]
You're observation is correct. A pipe symbol separates table cells and has higher precedence. To prevent it from being interpreted this way, you either need to escape it using a backslash:

```
[cols="1,4a"]
|===
| Code
|
[,cpp]
----
if (a \| b)
----
|===
```

 or change the table cell separator to a different character.

```
[cols="1,4a",separator=¦]
|===
¦ Code
¦
[,cpp]
----
if (a | b)
----
|===
```

This is covered in the following section of the docs: https://docs.asciidoctor.org/asciidoc/latest/tables/data-format/#escape-the-cell-separator

In the future, please direct support questions to the #users stream of the project chat at https://asciidoctor.zulipchat.com. Thanks!
