### ISSUE TITLE
Include optional add custom message

### ISSUE THREAD

**Issue by Zorbo** [asciidoctor/asciidoctor#4266]
Hi AsciiDoctor Team,

It would be a big help if the user could define a custome message, when an Include file or piece is missing.
Right now we can skip the warning message with: **include::includeFile.adoc[opts=optional]**

But it would be super nice if the user could specify the message like:
**include::includeFile.adoc[opts=optional, "No component found for this section"]**

It could be specify here in the code:
lib/asciidoctor/reader.rb 

`if raw_attributes && ((AttributeList.new raw_attributes).parse.key? 'optional-option')
            shift
          else
            warn %(asciidoctor: WARNING: #{line_info}: include file not found: #{inc_path})
            replace_next_line %(Unresolved directive in #{@path} - include::#{target}[#{raw_attributes}])
          end`

Thank You!

**Comment by Zorbo** [comment]
I cannot found any custom processor where I can customize this **Unresolved directive** message. If it possible, please show me how can I create a custom WARN message in Java language (AsciidoctorJ), maybe in IncludeProcessor?

**Comment by Mogztter** [comment]
I don't think we should allow users/writers to customize warning messages, that's really too low level. In my opinion, it has nothing to do in an AsciiDoc file.

Your best bet is probably to use a custom logger to capture this log and provide your own message. The AsciidoctorJ documentation explains how to do that: https://docs.asciidoctor.org/asciidoctorj/latest/logs-handling/#logs-handling-api

**Comment by Zorbo** [comment]
Hi @Mogztter ,

Thanks for the info, unfortunately the AsciiDoctorJ is not capable yet to create a custom log manager. You can fetch and cache the logs but cannot change (set) it. Only the JavaScript AsciiDoc library capable for this right now.

**Comment by Zorbo** [comment]
Hi @Mogztter ,

Thanks for the info, unfortunately the AsciiDoctorJ is not capable yet to create a custom log manager. You can fetch and cache the logs but cannot change (set) it. Only the JavaScript AsciiDoc library capable for this right now.

**Comment by Zorbo** [comment]
Hi @Mogztter ,

Thanks for the info, unfortunately the AsciiDoctorJ is not capable yet to create a custom log manager. You can fetch and cache the logs but cannot change (set) it. Only the JavaScript AsciiDoc library capable for this right now.

**Comment by Zorbo** [comment]
Oh, how could I overlooked this option?!

==== Cassandra Database
ifeval::["{cassandraDb}" == "false"]
There is no such component.
endif::[]
ifeval::["{cassandraDb}" == "true"]
[%header,format=csv,separator=;]
|===
include::subdir/cassandra.csv[opts=optional]
|===
endif::[]

Thank you for the advices, and for this awesome template :)

**Comment by mojavelinux** [comment]
> I don't think we should allow users/writers to customize warning messages, that's really too low level. In my opinion, it has nothing to do in an AsciiDoc file.

For what it's worth, I agree with this assessment.
