### ISSUE TITLE
Description list next item mistakenly a child after nesting

### ISSUE THREAD

**Issue by jaskij** [asciidoctor/asciidoctor#4268]
Below is description adapted from https://github.com/asciidoctor/asciidoctor/issues/1872#issuecomment-247241825, originally by @mojavelinux.

> ```
> Operating Systems::
> [horizontal]
>   Linux::: Linux
>   BSD::: BSD
> 
> Cloud Providers::
>   PaaS::: PaaS
>   IaaS::: IaaS
> ```
> 
> The second label is getting caught up as a child of the nested list. To workaround this problem, you can attach the nested list using a list continuation.
> 
> ```
> Operating Systems::
> +
> [horizontal]
>   Linux::: Linux
>   BSD::: BSD
> 
> Cloud Providers::
>   PaaS::: PaaS
>   IaaS::: IaaS
> ```

I'm experiencing this on Arch Linux, Asciidoctor and Ruby version below.

```shell
$ asciidoctor --version
Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
```

**Comment by mojavelinux** [comment]
Thanks for reminding me of this parsing issue. This is a good test case. I'll schedule it for the 2.1.0 release and backport it to 2.0.x if possible.

**Comment by mojavelinux** [comment]
The contract in AsciiDoc is that list items can be nested without a list continuation. If the nested list has a block attribute line above it, that should still be permitted. That's what's not being allowed but should be.

One restriction is that the block attribute line must be directly adjacent to the term or wrapped principal text (no empty line above it). However, if an adjacent block attribute line is found, then there can be empty lines between subsequent block attribute lines (they are tolerated).

> The second label is getting caught up as a child of the nested list. 

That's not actually what's happening. Instead, there are two top-level lists. If you write it that way explicitly, you would observe the same behavior.
