### ISSUE TITLE
References inside image captions don't work if image is given an ID/label.

### ISSUE THREAD

**Issue by gbmhunter** [asciidoctor/asciidoctor#4269]
Assuming we have:

```
[bibliography]
## References

* [[[bib-ref-1]]] My bib reference.
```

Then trying to link to the reference inside the image caption, when the image is also labelled, does not work properly:

```
[[image-label]]
.Test comment<<bib-ref-1>>.
image::image-path.png[width=700px]
```

and gives the warning:

```
WARN 2022/03/17 21:31:18 index.adoc: asciidoctor: INFO: possible invalid reference: bib-ref-1
```

Getting rid of the image label removes the warning:

```
.Test comment<<bib-ref-1>>.
image::image-path.png[width=700px]
```

**Comment by mojavelinux** [comment]
As far as I'm aware, this is no longer an issue with the last release of Asciidoctor. If it is, you can reopen and provide a reproducible example step by step and I will look at it closer.
