### ISSUE TITLE
Header & Footer on each page in PDF ?

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor#4272]
Hello, 

I am using vs with asciidoc and i am wondering if it is possible to have headers and footers in a generated PDF file. 
Not only text but i would like to place a logo on each page in the upper right corner. Except the index pages. 

Is this possible?

Thanks!

Johan

**Comment by abelsromero** [comment]
> Is this possible?

It is 🎉 

You can attach a style theme to the build to customize several aspects using `pdf-stylesdir` and `pdf-style` attributes.

Some initial notes:
* No need to build a full theme, you can extend the default https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#basic-extended-theme
* Specifics about header & footer https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#running-content-header--footer

If you struggle, feel free to drop by https://asciidoctor.zulipchat.com. You should also be able to find other theming questions already answered.

**Comment by Johan1974** [comment]
Hello Abel,

Tried a question in zulipchat but there i not much repsonse there.

Read you articles where i do not see if this is for vscode.

Met vriendelijke groet / With Kind regards,

Johan Lijffijt
