### ISSUE TITLE
Escaping to avoid "list item index: expected A, got P"

### ISSUE THREAD

**Issue by Hextremist** [asciidoctor/asciidoctor#4276]
This is probably related to #901
I did not find any sane way of escaping this:

````
== Escape Trouble

Let's go....

P. O. Box 34

How do I escape the first dot in the line above?
````

**Comment by mojavelinux** [comment]
The quickest way to do it is as follows:

```
P{empty}. O. Box 34
```

I could probably come up with other ways. If we all agree on one way of doing it, we can add it to the docs.

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks!

**Comment by mojavelinux** [comment]
This is actually a duplicate of https://github.com/asciidoctor/asciidoctor/issues/1464#issuecomment-145390534.

**Comment by Hextremist** [comment]
> The quickest way to do it is as follows:
> 
> ```
> P{empty}. O. Box 34
> ```
> 
> I could probably come up with other ways. If we all agree on one way of doing it, we can add it to the docs.

Yes, it would be nice if the page I read mentioned this  https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/

> In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks!

Will do, sorry!

--Kjell

**Comment by mojavelinux** [comment]
> it would be nice if the page I read mentioned this [docs.asciidoctor.org/asciidoc/latest/subs/prevent](https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/)

That page is really about escaping inline substitutions. I think a more appropriate place would be on the unordered list page, perhaps below "Forcing lists apart". https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/

Regarding the chat request, no need to apologize. It's a new policy to help manage the ever-growing project better. We're trying to keep the issue tracker focused on scheduled work. And the chat gives us plenty of space to communicate freely about anything.

**Comment by Hextremist** [comment]
I am happy as long as the word "escape" is used so it can be found in google search :)

**Comment by mojavelinux** [comment]
Done.
