### ISSUE TITLE
Blank leading/trailing lines in [source] blocks

### ISSUE THREAD

**Issue by vdshb** [asciidoctor/asciidoctor#4277]
I'm documenting some live-templates for IDEA and stuck. 
I can't add leading/trailing blank lines (at the beginning and at the end of a [source] block).

It must be some option as highly probably there are other cases / languages where leading/trailing blank lines actually matters. But I failed find one.

Is there any option/workaround to actually show them in [source] blocks?

**Comment by mojavelinux** [comment]
Please ask usage questions in the `#users` stream of the project chat at https://chat.asciidoctor.org. The issue tracker is reserved for reporting confirmed bugs and new feature proposals. Thanks!
