### ISSUE TITLE
Update the URLs in "README-zh_CN.adoc" to sync with the English doc

### ISSUE THREAD

**Issue by awxiaoxian2020** [asciidoctor/asciidoctor#4279]
I found that many URIs in the Chinese readme document is out of sync with the English one.
There is a link `:uri-render-doc: {uri-docs}/render-documents`  in [README-zh_CN.adoc](https://github.com/asciidoctor/asciidoctor/blob/main/README-zh_CN.adoc) in **line 49 (source code mode)**. But it has lost.

I found the reason was that it didn't sync with #3999.

**Comment by mojavelinux** [comment]
This is the correct target: https://docs.asciidoctor.org/asciidoctor/latest/get-started/

**Comment by awxiaoxian2020** [comment]
> This is the correct target: https://docs.asciidoctor.org/asciidoctor/latest/get-started/

You means that `render-documents` is the `get-started` doc?
So how to update the readme? I found that many links seems to be out-of-date.

**Comment by awxiaoxian2020** [comment]
Hi, @mojavelinux 
I know the reason is that it didn't sync with the PR #3999.
I will update the Chinese doc later.
And I think we can make a TODO list **issue** when updating the master document to keep track of the synchronization of documents in other languages.
