### ISSUE TITLE
{plus} expands to &#43; on manpage output

### ISSUE THREAD

**Issue by vinipsmaker** [asciidoctor/asciidoctor#4281]
It should expand to the sole `+`.

**Comment by mojavelinux** [comment]
Can you clarify which version of Asciidoctor you are using. I'm pretty sure this issue is already fixed as of Asciidoctor 2.0.17 and in the main branch. See #4059.

**Comment by vinipsmaker** [comment]
I'm using asciidoctor 2.0.15. I'll try the newer version. Thanks.

**Comment by mojavelinux** [comment]
Thanks for following up. If it still gives you trouble, I'll be happy to revisit it.
