### ISSUE TITLE
The source highlighter may be have some error.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor#4292]
Today, I wrote a document with Asciidoctor. But I found that there is some wrong in the source block.

The converted document: https://www.diguage.com/post/hessian-protocol-interpretation-and-practice-1/
The original document: https://github.com/diguage/www.diguage.com/raw/master/content/post/hessian-protocol-interpretation-and-practice-1.adoc

<img width="246" alt="image" src="https://user-images.githubusercontent.com/2121467/166420145-5707e6ad-3e1f-4c7c-8a1b-86b443541f13.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/2121467/166420243-2c21f8e0-c27c-472c-8a8e-eaac10594716.png">

I tried to change the document to a normal Asciidoctor document, as following:

```
= Hessian 协议解释与实战（一）
:icons: font
:source-highlighter: pygments
:pygments-style: monokai
:pygments-linenums-mode: table
:source_attr: indent=0,subs="attributes,verbatim,quotes,macros"
:image_attr: align=center

// ---
// title: "Hessian 协议解释与实战（一）"
// date: 2022-05-02T17:22:01+08:00
// draft: false
// keywords: ["Hessian","序列化","协议","Java","微服务","架构","程序设计"]
// tags: ["Java","微服务","架构","设计","序列化"]
// categories: ["系统架构","程序设计"]
// thumbnail: "images/common/confused-target-vector.jpg"

// weight: 1
// ---


前段时间，翻译了 Hessian 2.0 的序列化协议，发布在了 https://www.diguage.com/post/hessian-serialization-protocol/[Hessian 2.0 序列化协议（中文版）^]。但是，其中有很多言语不详之处。所以，接下来会用几篇文章来详细解释并实践一下 Hessian 序列化协议，以求做到知其然知其所以然。

== 基础工具方法

Hessian 序列化之后的数据，都是字节数组，为了方便查看字节数组的二进制形式和十六进制形式，在正式开始之前，先介绍一下期间用到的辅助工具方法。闲言少叙，直接上代码：

[source%nowrap,java,{source_attr}]
----
/**
 * 创建 Hessian2Output 对象，以便用于序列化
 *
 * @author D瓜哥 · https://www.diguage.com/
 */
private Hessian2Output getHessian2Output(OutputStream stream) {
    SerializerFactory serializerFactory = new SerializerFactory();
    serializerFactory.setAllowNonSerializable(true);
    Hessian2Output result = new Hessian2Output(stream);
    result.setSerializerFactory(serializerFactory);
    return result;
}

/**
 * 打印字节数组
 *
 * @author D瓜哥 · https://www.diguage.com/
 */
private void printBytes(byte[] result) {
    for (byte b : result) {
        String bitx = Integer.toBinaryString(Byte.toUnsignedInt(b));
        String zbits = String.format("%8s", bitx).replace(' ', '0');
        if (0 <= b) {
            System.out.printf("%4d 0x%02X %8s %c %n", b, b, zbits, b);
        } else {
            System.out.printf("%4d 0x%02X %8s %n", b, b, zbits);
        }
    }
}

/**
 * 将 long 转化成二进制字符串（前面补0）
 *
 * @author D瓜哥 · https://www.diguage.com/
 */
private String getBinaryString(long value) {
    String bits = Long.toBinaryString(value);
    char[] chars = String.format("%64s", bits)
                         .replace(' ', '0').toCharArray();
    StringBuilder result = new StringBuilder(64 + 7);
    for (int i = 0; i < chars.length; i++) {
        result.append(chars[i]);
        if (i % 8 == 7 && i != chars.length - 1) {
            result.append(",");
        }
    }
    return result.toString();
}

/**
 * 将 int 转化成二进制字符串（前面补0）
 *
 * @author D瓜哥 · https://www.diguage.com/
 */
private String getBinaryString(int value) {
    String bits = Integer.toBinaryString(value);
    char[] chars = String.format("%32s", bits)
                         .replace(' ', '0').toCharArray();
    StringBuilder result = new StringBuilder(64 + 7);
    for (int i = 0; i < chars.length; i++) {
        result.append(chars[i]);
        if (i % 8 == 7 && i != chars.length - 1) {
            result.append(",");
        }
    }
    return result.toString();
}
----
```

And then deal it with `asciidoctor example.adoc`, but the converted document is the same as the previous document.

**Comment by mojavelinux** [comment]
First, please ask usage questions in the project chat at https://chat.asciidoctor.org. If we determine from that discussion that there is a bug in Asciidoctor, then we'll encourage you to file an issue. This keeps the issue tracker organized and the project easier to manage.

What I can tell you is that you are encourtering a bad interaction between the custom substitutions (in particular macros) and the syntax highlighter. You should avoid mixing these if all possible and use the default substitutions instead. The custom substitutions can confuse the syntax highlighter or match sequences you don't expect. That's what's happening here. It's dangerous to apply the `subs` attribute globally for this very reason.

**Comment by diguage** [comment]
@mojavelinux Sorry, I used to submit a problem to Issue. I will try to submit a problem to https://chat.asciidoctor.org/.
Thank you very much.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by diguage** [comment]
[Customize the Substitutions Applied to Blocks | Asciidoctor Docs](https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/#the-subs-attribute) -- The document about the problem.

**Comment by diguage** [comment]
I submit a similar problem to Zulip, https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/How.20to.20only.20use.20the.20link.20attribute.20of.20macro.20in.20the.20subs.3F
