### ISSUE TITLE
What is the correct syntax to apply "Line numbering on a source block"?

### ISSUE THREAD

**Issue by manueljordan** [asciidoctor/asciidoctor#4296]
What is the correct syntax to apply "Line numbering on a source block"?

I saw #1981 - is closed but it does not indicate what is the correct solution - I tried the latest syntax shown in that post and does not work.

I tried the syntax according with (practically same content and old):

* [Awesome Asciidoc: Adding Line Numbers to Source Code Listings](https://blog.jdriven.com/2014/08/awesome-asciidoc-adding-line-numbers-source-code-listings/)
* [Awesome Asciidoctor: Adding Line Numbers to Source Code Listings](https://blog.mrhaki.com/2014/08/awesome-asciidoc-adding-line-numbers-to.html)

And they don't work ...

Even when I checked in the official _AsciiDoc Syntax Quick Reference_ page at the [More delimited blocks](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#more-delimited-blocks) section, the close scenario is the _Example 66. Passthrough block_ and does not work too.

Is possible reach accomplish the desired goal? How?, if I did do incorrectly the research in the _AsciiDoc Syntax Quick Reference_ page - under what section and example is the correct syntax?

**Comment by mojavelinux** [comment]
You can learn how to enable line numbering on the following page in the documentation: https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/#enable-line-numbering

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. This page explains how we communicate in this project: https://docs.asciidoctor.org/about/support/

**Comment by manueljordan** [comment]
Thanks for the quick and polite reply

**Comment by mojavelinux** [comment]
I look forward to seeing you in the chat!

**Comment by manueljordan** [comment]
As usual thanks for the polite support
