### ISSUE TITLE
AsciiDoctor does not work on my machine

### ISSUE THREAD

**Issue by AdilTestelin** [asciidoctor/asciidoctor#4303]
I've downloaded the latest version of AsciiDoc on Intellij IDEA 2022 1.2 and it keeps giving me this error message : 
![image](https://user-images.githubusercontent.com/49147566/174319429-78893422-ca12-4e9e-9cf4-d23ba8f8721a.png)

I've checked if the jar is present in my .m2 file and he's present, i've googled the error but found nothing. 

Thank you in advance for your help !

**Comment by abelsromero** [comment]
Welcome! I am sorry to say, this should probablly be addressed to github.com/asciidoctor/asciidoctor-intellij-plugin or you can drop a question in https://chat.asciidoctor.org/ unders #users.

This repository is for the core Asciidoctor Ruby gem.

**Comment by mojavelinux** [comment]
As Abel said, please ask questions about installation in the project chat. In the project chat, you don't have to worry so much about whether you are asking the question in the right project because the project chat is for all projects in Asciidoctor.
