### ISSUE TITLE
Disallow [ as character in attribute list on formatted (quoted) text

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4306]
The attribute list that precedes formatted text forbids the use of `]`, but allows `[`. This can lead to unexpected matches when the quotes substitution is enabled on a code block. However, this character is not relevant in an attribute list. Therefore, it should be disallowed.

**Comment by mojavelinux** [comment]
We can start with the following repeating character group: `[([^\]]+`

I think the parser should be even more restrictive about what it allows in the attribute list on formatted text. It should thus match by inclusion rather than exclusion.

Here are the characters I think it should match:

* `\p{Word}` (any valid word character)
* `-` (hyphen)
* `:` (colon) - sometimes used in a role name or in an attribute reference
* `.` (dot) - used to separate roles
* `#` (hash) - used to initiate an ID
* `{` and `}` (round brackets) - use to represent an unprocessed attribute reference
* space - deprecated syntax to separate roles
* `,` (comma) - reserved for future use

Here's the repeating character group: `[#.\p{Word}\-:{} ,]+`

**Comment by Mogztter** [comment]
Is there a reason why we don't use the same logic to parse inline macro attributes list and  formatted text attributes list?

I think it would be useful to define a tooltip/title or even data attributes:

```
[.lang,data-ref=abc,title="AsciiDoc is a human-readable plain text markup"]_AsciiDoc_
```

**Comment by mojavelinux** [comment]
Because that would be a major spec change and likely introduce side effects we aren't considering. It was not anything that AsciiDoc.py ever supported. We do essentially permit the characters when parsing, so there's definitely room to do it. But we need to deal with that in the proper place.

**Comment by Mogztter** [comment]
My point is, as you've mentioned, that we currently do permit the characters when parsing. So, in effect, my example produces a text formatted with the role `lang`. If we change/restrict the regular expression then it won't.

In other words, we currently do allow the syntax but we don't use the same logic to extract attributes. If the mid/long term goal is to use the same logic to parse inline macro attributes list and formatted text attributes list then I think we should reserve additional characters for future use, such as `=`, `"`...

> likely introduce side effects we aren't considering

We do need to make a proper analysis but I don't think they will be more side effects than what we have today. It's important to note that comma is not a valid identifier character so `[.lang,something]` should not be interpreted as a role named `lang,something`.

> But we need to deal with that in the proper place.

I agree but I feel like it's not the right time to change the regular expression unless we consider that it's a bug and `[.lang,title="AsciiDoc is a human-readable plain text markup"]_AsciiDoc_` should be interpreted differently?

**Comment by mojavelinux** [comment]
> I feel like it's not the right time to change the regular expression

We definitely need to add `[` to the list of restricted characters because this is creating a nasty parsing bug. But I agree that restricting the regexp further might be going to far beyond the issue at hand. That's why I posed it more as a suggestion.

However, I'm not convinced it's the wrong time to change it. The goal right now is to get the parser to match the docs and vice versa. The docs are very clear that the only allowable characters are role names separated by spaces (`foo bar`) or the shorthand ID/role syntax (`#baz.foo.bar`). No one should be relying on any other syntax right now as it's not part of the documented language.

I think I'll move forward with excluding `[` and then post the additional restrictions as a separate issue.

(As for why comma is allowed right now...that's a case where the parser went too far in the name of undocumented compliance, but there's no good reason to break it now. See https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/substitutors.rb#L1482-L1483)

**Comment by mojavelinux** [comment]
See #4308 for follow-up.
