### ISSUE TITLE
Upgrade nokogiri (development dependency) to 1.13.x

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#4310]
We might be able to remove the `BUNDLE_BUILD__NOKOGIRI=--use-system-libraries` environment variable in:

https://github.com/asciidoctor/asciidoctor/blob/cd9b07c75323be97bb8364554f9a4ee095baec33/.github/workflows/ci.yml#L76

I believe we are using `--use-system-libraries` because of this issue: https://github.com/flavorjones/mini_portile/issues/101
Since this issue is now fixed in version 2.5.2 and Nokogiri 1.13.x is using version 2.8+ of mini_portile, I think it would make sense to upgrade.

Initial discussion: https://asciidoctor.zulipchat.com/#narrow/stream/279656-dev-.F0.9F.9B.A0.EF.B8.8F/topic/bundle.20install.20in.20asciidoctor.20with.20Ruby.203.2E1.20.28on.20Ubuntu.29

**Comment by mojavelinux** [comment]
The main reason we're using `--use-system-libraries` is because it's takes an excruciatingly long time to rebuild nokogiri. By linking instead, it speeds up installed dramatically.

**Comment by mojavelinux** [comment]
The problem with upgrading is that it requires Ruby >= 2.6 and we test back to Ruby 2.3.

We are reevaluating how we drop old versions of Ruby, but suffice to say, core has to be prudent with the minimum Ruby version to support all the Linux distributions and macOS. So I don't think we can make this jump yet.

What exactly is the reason for wanting to upgrade? All the tests are passing in CI right now.

**Comment by Mogztter** [comment]
As an intermediate step we could upgrade to Nokogiri 1.12 which uses mini_portile 2.6.1 and requires Ruby 2.5.

The main reason is that it does not install on Ubuntu 20.4 LTS when building from source (i.e. without `--use-system-libraries`).
It's not a big deal but we might want to add a note in the contributing guide.

**Comment by mojavelinux** [comment]
This was resolved by #4339.
