### ISSUE TITLE
include failure after nested includes

### ISSUE THREAD

**Issue by ryanaponte** [asciidoctor/asciidoctor#4318]
Note: I am having an AsciiDoc rendering problem specifically on GitLab.com. AsciiDoctor renders it fine locally and in the VSCode extension.

I'm creating an issue here bc I'd like to know what I can do to fix things in the markup so it renders correctly, everywhere. GitLab is unlikely to modify their implementation. I want my team to trust and rely on the baked-in AsciiDoc rendering in GitLab, so I'm keen to make this work.

I'm nesting includes, and the .adoc file I include _after_ a nested include is failing.

```
title-1.adoc
     |--includes/1.adoc
     |--includes/2.adoc
     |--includes/3.adoc
                   |--includes/4.adoc
                   |--includes/5.adoc
                   |--includes/6.adoc
                                  |--modules/6a.adoc
                                  |--modules/6b.adoc
                                  |--modules/6c.adoc
                                  |--modules/6d.adoc
     |--includes/5.adoc                                        <-- ⚠️ includes in this file fail
```

You can see the problem in the GitLab render here:
https://gitlab.com/ryanaponte/nested-includes/-/blob/main/titles/title-1/title-1.adoc

I suspect that some scope has to be reset or something but I'm stumped. Thanks for your help!

**Comment by ryanaponte** [comment]
Oh man, it's an arbitrary include limit in GitLab itself:
https://gitlab.com/gitlab-org/gitlab/-/issues/354468

**Comment by mojavelinux** [comment]
In the future, if you have questions about AsciiDoc on GitLab (or GitHub), please direct the inquiry to the project chat at https://chat.asciidoctor.org. Thanks!
