### ISSUE TITLE
Feature suggestion: Org Mode and/or Literate Programming

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor#4320]
Hi all,

I would like to suggest a feature please: Org Mode.
Specifically, what I think is the killer feature of Org Mode is [tangling](https://orgmode.org/manual/Extracting-Source-Code.html).
Or, even more specially, please add [Literate Programming](https://en.wikipedia.org/wiki/Literate_programming) abilities to Asciidoctor.
Org Mode tangling is in my opinion would be best for Asciidoctor+Literate Programming.

Thanks.

**Comment by mojavelinux** [comment]
The correct place to share new ideas is the project chat at https://chat.asciidoctor.org. If someone is interested in the idea, they may decide to help you work on it as an extension. It's also possible someone will decide to try to implement themselves. The issue tracker is reserved for bug reports and formal proposals for an enhancement. That helps us better maintain the project. Thanks for understanding. You can more information about our process on the following page in the docs: https://docs.asciidoctor.org/about/support/

**Comment by refaelsh** [comment]
Thank you very much for your answer and patience :-)
I understand.
