### ISSUE TITLE
Can you both link one CSS file and copy a different CSS file?

### ISSUE THREAD

**Issue by kxygk** [asciidoctor/asciidoctor#4325]
I can't seem to get this working.. I either get a CSS inlined, or linked - but never both.

The documentation has a section called "Copy from one place, link to another" but it seems to describe something different... 

At the top of my document I'd like to have something that looks like 

``` asciidoc
# My Super Cool Webpage
:stylesdir: ../css
:linkcss: brand.css
:copycss: retest.css
```

 It seems a central design of CSS that there is a 3 layer cake with "remote CSS" "local <style> CSS" and "inline CSS". 

My usecase is I separate the page "branding" into a remote CSS file and page styling into a in-HTML `<style>` CSS

The end result (and desired behavior!) is when a user saves my webpage's HTML to their computer the linked CSS no longer resolves and the branding vanishes and they're just left with the bare document for their archive/reference.

I have this working in Orgmode actually, but it's a bit hacked together (b/c their inline CSS has to be hacked with HTML header macros)

Am I just doing it wrong..? Or is what I'm trying to do simply impossible? Do I need to hack the HTML header again with an @import?

Thanks for the great tool and the help :)

**Comment by kxygk** [comment]
Okay, so a sensible option is to just link the "branding" CSS file at the top one the CSS file that's getting inlined

So you'd have
```asciidoc
# My Super Cool Webpage
:stylesheet: ../css/mystylesheet.css
```
And then at the top of `mystylesheet.css` you'd have the import
```css
@import '../css/brand.css';

body {
  background-color: blue;
}

```
Then this whole thing gets dropped into the HTML in `<style>` tags


Based on what I read here.. https://github.com/asciidoctor/asciidoctor/issues/4299

The only drawback is that the path to `brand.css` is baked into `mystylesheet.css` BUT it'll be relative to the resulting HTML - not `mystylesheet.css`

**Comment by mojavelinux** [comment]
Please direct usage questions to the project chat at https://chat.asciidoctor.org. I'd be happy to follow up there. For more information on our support policy and how we use the communication channels, see https://docs.asciidoctor.org/about/support/
