### ISSUE TITLE
Two link anchors work in dlist element but not three

### ISSUE THREAD

**Issue by bhyslop** [asciidoctor/asciidoctor#4329]
When I try and render...
```asciidoc
I like to <<term-create>> things.  Really, <<term-creating>> is quite fulfilling.

On the other hand, my inner 3 year old loves to <<term-destroy>>.  I find that <<term-destroying>> is much more satisfying.  So why is <<term-destruction>> wrong?

[[term-creating, creating]]
[[term-create,   create]]**create**::
An act of bringing something new to the world.

[[term-destruction, destruction]]
[[term-destroying,  destroying]]
[[term-destroy,     destroy]]**destroy**::
An act of unabashed elimination.
```
... I get unexpected result in the _third_ link substitution.  Unusual that 2 work but 3 don't.  ?

See image below for what it looks like in my VS Code instance; I observe the same with today's github render engine directly.

![image](https://user-images.githubusercontent.com/416642/184159779-a0ab057d-d319-4473-93ba-829a9617a4cb.png)

**Comment by mojavelinux** [comment]
Anchors for a dlist term must be defined on the same line as the term. Otherwise, the syntax is invalid.

```
[[term-destruction,destruction]][[term-destroying,destroying]][[term-destroy,destroy]]destroy::
An act of unabashed elimination.
```

Keep in mind that only the first anchor is registered for use as an xref target. The other anchors are for deep links only (i.e., accessible via a URL fragment).

TIP: There's also no need to apply bold formatting to the term as that is the default.

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. You can find out more about our support policies on the following page: https://docs.asciidoctor.org/about/support

**Comment by bhyslop** [comment]
@mojavelinux I realized on processing your feedback that there are fine reasons this is not a serious problem- inevitable when technologies stack that there are some odd things in the corners.  I'm an embedded guy so my depth in CSS, HTML, JavaScript is low.

I wanted to send a final comment to say... Thank you!  Asciidoc(tor) has become a core tool in how I muse and document things- its long term health is quite important to me and I'll always choose it over Markdown when possible.  So many things work so well for me that I'm really glad that some choose the labor of love of refining an open source jewel.  Be well and if you move on from this project, may it be better and cooler ones that you pursue.

**Comment by mojavelinux** [comment]
Thanks for those kind words @bhyslop. Your acknowledgement really brings a lot of meaning to the work I've been doing along with this community over the past decade. Rest assured, there are still many more challenges that lie ahead and I'm eager to face them. I hope AsciiDoc and Asciidoctor continue to assist your muse. :beers:
