### ISSUE TITLE
How to link to non-ASCII file name

### ISSUE THREAD

**Issue by aviscaerulea** [asciidoctor/asciidoctor#4337]
I want to link from an AsciiDoc built PDF to an external PDF.
But currently only ASCII file names seem to work.

I want to link PDFs with Japanese file names on the same level.
Is there a workaround?
I could not find any similar issue.

```
- link:pass:[SAMPLE_日本語.pdf][]                        🡆 NOT LINKED
- link:pass:[SAMPLE_%E6%97%A5%E6%9C%AC%E8%AA%9E.pdf][]  🡆 NOT LINKED
- link:pass:[SAMPLE.pdf][]                              🡆 LINKED
```

File tree

```
|-- ThisDoc.adoc
|-- ThisDoc.pdf            
|-- SAMPLE_日本語.pdf       🡄 I'd like to link to this.
`-- SAMPLE.pdf             🡄 I'd like to link to this.
```

**Comment by mojavelinux** [comment]
This is an unnecessary use of the pass macro. You can simplify it to:

```
link:SAMPLE_日本語.pdf[]
```

The target of the link macro can be any non-space character in UTF-8.

In the future, please direct usage question to the project chat at https://chat.asciidoctor.org. You can find more information about the support policy on the following page in the docs: https://docs.asciidoctor.org/about/support/
