### ISSUE TITLE
Localize toolbar and toc

### ISSUE THREAD

**Issue by BryanYin** [asciidoctor/asciidoctor#4342]
Hi,

May I know if it is possible to localize below texts?
<img width="570" alt="image" src="https://user-images.githubusercontent.com/25950822/186425591-abfe87fa-5e16-4c7c-8a34-638dbc95430f.png">

**Comment by mojavelinux** [comment]
It appears that you are asking a question about Antora. Please direct questions about Antora to the project chat at https://chat.antora.org. Thanks.
