### ISSUE TITLE
Question: How to recreate your doc website?

### ISSUE THREAD

**Issue by John15321** [asciidoctor/asciidoctor#4344]
Im trying to write documentation for my hardware project and I would love to use `asciidoctor`. I can see all of the examples being very plain but from what I can see your docs website also uses adoc. How can I achieve things like being able to see previous versions etc?

**Comment by mojavelinux** [comment]
Please direct usage questions to the project chat at https://chat.asciidoctor.org. The issue tracker is for reporting bugs and feature proposals.

You can find the build materials for the Asciidoctor docs at https://github.com/asciidoctor/docs.asciidoctor.org. The README explains how it is built.
