### ISSUE TITLE
The position on positional attributes should ignore named attributes

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor#4345]
According to the documentation:

> Entries in an attribute list that only consist of a value are referred to as positional attributes. The position is the 1-based index of the entry once all named attributes have been removed (so they may be interspersed).

https://docs.asciidoctor.org/asciidoc/latest/attributes/positional-and-named-attributes/#positional

For instance:
```
[first,second=value,Sherlock Holmes]
```

The above example should produce:
```rb
expected = { 1 => 'first', 'second' => 'value', 2 => 'Sherlock Holmes' }
```

Currently, it produces:

```rb
expected = { 1 => 'first', 'second' => 'value', 3 => 'Sherlock Holmes' }
```

**Comment by mojavelinux** [comment]
After giving this a lot more thought and experimentation, I've come to the conclusion that this is not the right change. I explain my reasoning in the following comment: https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/36#note_1154382

**Comment by mojavelinux** [comment]
If that decision is reverse, we can revisit.
