### ISSUE TITLE
If hugo have some chinese attributes for asciidoctor, asciidoctor throw error

### ISSUE THREAD

**Issue by zkaip** [asciidoctor/asciidoctor#4351]
if hugo have markup attribute like the follow
<img width="360" alt="Screen Shot 2022-09-08 at 17 38 28" src="https://user-images.githubusercontent.com/705088/189093944-6c540d15-2760-4934-84df-c9d22e00cf02.png">

The error is happened as follow
<img width="600" alt="Screen Shot 2022-09-08 at 17 19 50" src="https://user-images.githubusercontent.com/705088/189094193-52aa5f3a-4dfa-41c0-99df-f5c83c813915.png">

then I edit `lib/asciidoctor/cli/options.rb`
from 
`attr = attr.encode UTF_8 unless attr.encoding == UTF_8`
<img width="600" alt="Screen Shot 2022-09-08 at 17 22 12" src="https://user-images.githubusercontent.com/705088/189094618-881381e2-06d0-4efb-abb8-dc90ea5aa2e0.png">

to 
`attr = attr.force_encoding UTF_8 unless attr.encoding == UTF_8`
<img width="600" alt="Screen Shot 2022-09-08 at 17 01 54" src="https://user-images.githubusercontent.com/705088/189094743-516e5998-1f68-4d59-aa5f-a149e2bddbe9.png">

the bug is fixed!

Please reference my fixed to upgrade asciidoctor!

**Comment by mojavelinux** [comment]
An AsciiDoc processor assumes that all input is either UTF-8 encoded or properly labeled. See https://docs.asciidoctor.org/asciidoc/latest/normalization/. It's likely that when Hugo runs the asciidoctor command using the system call, it ends up causing mislabeled data to be passed to Asciidoctor. The proposed change would be reverting the change made for https://github.com/asciidoctor/asciidoctor/issues/2764. You can find information about how to relabel the strings in the following comment: https://github.com/asciidoctor/asciidoctor/issues/2764#issuecomment-451780160

Here's what I would be willing to do. We could try .encode and if that fails, fall back to force_encoding. In other words:

```rb
            unless attr.encoding == UTF_8
              begin
                attr = attr.encode UTF_8 
              rescue ::Encoding::EncodingError
                attr = attr.force_encoding UTF_8
              end
            end
```

Can you try that logic and see if it works for you?

**Comment by zkaip** [comment]
I solved this problem by modifying the source code, but I hope that this issue can also be updated in the main asciidoctor version, because, if the user passes a non-utf_8 string, then compatibility should also be done

**Comment by mojavelinux** [comment]
Can you please test with the code I provided?

**Comment by zkaip** [comment]
@mojavelinux you code not worked...

if I changed the code as the follow
<img width="775" alt="Screen Shot 2022-09-09 at 12 02 57" src="https://user-images.githubusercontent.com/705088/189280335-932a9898-ccac-4baf-a167-4d5109b62a5d.png">

then the result is follow
<img width="1003" alt="Screen Shot 2022-09-09 at 12 03 55" src="https://user-images.githubusercontent.com/705088/189280440-23febb01-b00b-457f-80d9-9f963390ea0b.png">

**Comment by mojavelinux** [comment]
Thank you for testing. Let me update the code and I'll get back to you once I have something new to test.

The reason I cannot accept the code as you wrote it is that it would break compatibility with strings that are properly labeled. But I think we can find a way to support both cases.

**Comment by mojavelinux** [comment]
Can you try this code instead? It looks like I had the name of the error class wrong

```rb
 unless attr.encoding == UTF_8
  begin
    attr = attr.encode UTF_8 
  rescue ::EncodingError
    attr = attr.force_encoding UTF_8
  end
end
```

**Comment by zkaip** [comment]
@mojavelinux Yes, this code resolved the problem. 

```
unless attr.encoding == UTF_8
  begin
    attr = attr.encode UTF_8 
  rescue ::EncodingError
    attr = attr.force_encoding UTF_8
  end
end
```

**Comment by mojavelinux** [comment]
Thanks for verifying! I'll go ahead and proceed with that change.

**Comment by mojavelinux** [comment]
I'll backport this change to 2.0.x as well.
