### ISSUE TITLE
`toc-title` built-in label is not translated when converting to HTML

### ISSUE THREAD

**Issue by georgeraraujo** [asciidoctor/asciidoctor#4356]
Hi,
I found that the `toc-title` built-in label is not translated when converting to HTML.

I did my tests with Asciidoctor 2.0.17. Here's the source code for the MWE:

[localization-bug.zip](https://github.com/asciidoctor/asciidoctor/files/9600053/localization-bug.zip)

I followed the instructions given in the [Localization Support](https://docs.asciidoctor.org/asciidoctor/latest/localization-support/) documentation page and used [attributes.adoc](https://github.com/asciidoctor/asciidoctor/blob/main/data/locale/attributes.adoc) and [attributes-pt_BR.adoc](https://github.com/asciidoctor/asciidoctor/blob/main/data/locale/attributes-pt_BR.adoc) from the [main](https://github.com/asciidoctor/asciidoctor/tree/main/data/locale) repo.

I ran this command:
``` shell
asciidoctor -a lang=pt_BR localization-bug.adoc
```

`chapter-signifier` and `appendix-caption` are correctly translated to `Capítulo` and `Apêndice` respectively, but `toc-title` is not translated to `Índice` and shows the Default English Value `Table of Contents`:

![image](https://user-images.githubusercontent.com/4930759/191048329-8c3e04a8-cfdc-4f53-adc4-8d092af299d4.png)

**Comment by mojavelinux** [comment]
The problem is that the `toc-title` is not defined in the document header as required. There is an empty line before the attributes include, which ends the document header. See https://docs.asciidoctor.org/asciidoc/latest/document/header/#document-header-structure
