### ISSUE TITLE
monospace and highlight do not work together

### ISSUE THREAD

**Issue by fekir** [asciidoctor/asciidoctor#4360]
Consider following document

````
= Test

**S**ome *bold* text.

__T__his is is _italic_.
**__B__**old *_italic_*.

``T``his is `monospace`.
``**T**``his is `*bold and monospace*`.
``**__T__**``his is `*_monospace_*; *bold* and _italic_`.

##S##ome #highlighted text#.
##``**__T__**``##his is #`*_highlighted, bold, italic and monospace_*`#.

````

with `asciidoctor-pdf`, the output looks like 

![image](https://user-images.githubusercontent.com/11912465/193136830-0304c072-9f22-426d-b757-235ba32516b1.png)

and with `asciidoctor` the output looks like

![image](https://user-images.githubusercontent.com/11912465/193136986-f8c927a0-f6f5-42bb-99fc-79c524dcb019.png)

It seems that in the pdf output, it is possible to combine highlight and monospace, but in the html output the highlighted text, if monospace, is not highlighted.

If it helps I can also upload the generated files

````
Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
````

**Comment by mojavelinux** [comment]
Yes, there are limits to how many formatting pairs can be nested. The general rule of thumb is that you can't nest more that two pairs. You may be able to figure out certain combinations that work with deeper nesting, but the language is not currently designed in such a way to support that explicitly.

If you have questions about the use of formatting, please direct them to the project chat at https://chat.asciidoctor.org.

**Comment by fekir** [comment]
@mojavelinux 

> you can't nest more that two pairs

monospace and highlight would be exactly two, not more. (unsure if this argument would eb enoguh for reopening this tickete)

````
= Test

##S##ome #highlighted text#.
##``T``##his is #`highlighted and monospace`#.
````
![image](https://user-images.githubusercontent.com/11912465/193140751-ee9fa59d-6655-448e-a780-28e50320aec9.png)

**Comment by mojavelinux** [comment]
The processor does exactly the right thing in this case. The following input:

```
##S##ome #highlighted text#.
##``T``##his is #`highlighted and monospace`#.
```

produces the following output:

```
<div class="paragraph">
<p><mark>S</mark>ome <mark>highlighted text</mark>.
<mark><code>T</code></mark>his is <mark><code>highlighted and monospace</code></mark>.</p>
</div>
```

The CSS does not permit the background on the mark tag to be inherited by the code tag. Technically, it's possible to support that with an override, but I don't consider it to be worth the effort. However, if you'd like to pursue it, please open a separate issue that is focused on behavior of the default stylesheet.

**Comment by mojavelinux** [comment]
Btw, this CSS would do the trick:

```
mark:not([class]) code {
  background: none;
}
```

I'm willing to add that to the default stylesheet if you open an new issue. Please frame the request as clearing the background on a code span in the default stylesheet when the code span is nested within a highlight (mark) span.
