### ISSUE TITLE
Custom markers in nested lists not honoured

### ISSUE THREAD

**Issue by someth2say** [asciidoctor/asciidoctor#4361]
HI!

When nesting bulleted lists, sometimes we want different markers for the parent list than for the nested list.
For example, 
```
[none]
* Parent
[circle]
** Child
```
This generates a correct list in HTML format:
```html
<ul class="none">
<li>
<p>Parent</p>
<div class="ulist circle">
<ul class="circle">
<li>
<p>Child</p>
</li>
</ul>
``` 
And the render is also nice:
![image](https://user-images.githubusercontent.com/13310156/194223593-1a59902c-5388-43f2-bfc4-9520fcbee569.png)

Nevertheless, this only seems to work if the parent marker is `none` or `unstyled`.
Using any other marker leads to the style of the nested list to be overwritten with the style of the parent list:
```
[disc]
* Parent
[circle]
** Child
```
correctly transforms to:
```html
<ul class="disc">
<li>
<p>Parent</p>
<div class="ulist circle">
<ul class="circle">
<li>
<p>Child</p>
</li>
</ul>
```
but the render does honour the expectations:
![image](https://user-images.githubusercontent.com/13310156/194223894-335b14a0-3645-4386-ad6c-1d8fc291c328.png)

As @mojavelinux commented in Zulip, it seems to be a problem with styles: 
>  it seems like the styles are too strong such that it isn't letting you override it in the nested list. So that's actually a bug.

Thanks for the support!

**Comment by mojavelinux** [comment]
Thanks! And a new release is on the way too!

Btw, I also noticed the same problem in the Antora default UI, so I fixed it there too.

**Comment by mojavelinux** [comment]
...and released.
