### ISSUE TITLE
Indicate that the Atom editor is being sunset

### ISSUE THREAD

**Issue by stoobie** [asciidoctor/asciidoctor#4362]
It would be helpful to update [IDEs and text editors](https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors) so that new users don't waste their time installing and learning to use Atom. :(

See the official statement on the atom site: https://github.blog/2022-06-08-sunsetting-atom/

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor/pull/4363
I guess we should cherry-pick this commit onto the main branch.

**Comment by mojavelinux** [comment]
I've already ported it. See ebd63ad96000108fdaa2e97010bf0e66c888fe9a. Thanks for pointing out that this didn't get closed.
