### ISSUE TITLE
Feature request: HTML4 backend

### ISSUE THREAD

**Issue by ponchofiesta** [asciidoctor/asciidoctor#4364]
# Problem

Actually Asciidoctor is good in generating HTML5 files. But in some cases such modern file formats are not working. For example I wanted to generate documentation in PDF (for delivery as is) and in HTML4 (for embedding in the applications javahelp (HTML 3.2 and parts of CSS1) tool). Unfortunately there are many old libs out there that doesn't support HTML5 or CSS3.

# Request

Add a simple HTML4 backend using no or very few CSS. Might be good to use tables for placement formatting.

# Workaround

As a workaround I'm using a modified version of https://github.com/asciidoc-py/asciidoc-py which provides a HTML4 backend.

**Comment by mojavelinux** [comment]
You are free to develop a custom converter to generate HTML4 if that is what you need. See https://docs.asciidoctor.org/asciidoctor/latest/convert/custom/ There are numerous examples of converters on which you can build. If you need help, please ask in the project chat at https://chat.asciidoctor.org.

We're not going to be looking backwards in this project to create an HTML4 converter. That just doesn't make any sense for us. In fact, we are looking forward to develop a more semantic HTML5 converter.
