### ISSUE TITLE
Metadata: contributors and translators

### ISSUE THREAD

**Issue by toastal** [asciidoctor/asciidoctor#4365]
To follow the [creative work schema](https://schema.org/CreativeWork), just like [*author(s)*](https://docs.asciidoctor.org/asciidoc/latest/document/author-attribute-entries/), I'd like to see contributor(s) and translator(s). Ideally this would look like (with optional email like author line)

```asciidoc
= My Document
:author: toastal <toastal@email.test>; toastal2
:contributor: mojavelinux <mojavelinux+asciidoc@email.test>; mojaves_best_friend
:translation-of-work: /es/mi-documento
:translator: Juan_M Doe <juan.doe@email.test>
```

**Comment by mojavelinux** [comment]
Again, similar to #4366, you can use an extension or extended converter to add this to the HTML. The built-in HTML converter can only support a finite number of attributes. With your own extension or converter, you can add support for any number of additional meta attributes. Since there are no restrictions on how many document attributes you define, these will be available in the document model.

**Comment by toastal** [comment]
I understand that this could be done with an extension, but as a "CreativeWork", this may be relevant to the community at large and not just myself--especially given that there are many place (e.g. GitLab.com, Codeberg) where you can use AsciiDoc, but aren't in control of the extensions.

**Comment by mojavelinux** [comment]
I guess I wasn't clear enough. I'm drawing a line. We're not going to keep adding meta tags to satisfy different schemas. If you need to do that, then an extension is the right approach.

> given that there are many place (e.g. GitLab.com, Codeberg) 

Those places don't use the `<head>` generated by the built-in HTML converter in Asciidoctor, so adding this to the converter would have absolutely no impact on those environments.

**Comment by toastal** [comment]
> no impact on those environments

I thought that author information would show up in the `#header .details` section, but at least in a test quick of GitLab snippets, I'm assuming the no header flag is passed to whatever tool is rendering the content. So you're probably right that this info would never be shown.

> I guess I wasn't clear enough. I'm drawing a line.

It's open source, so that's reasonable.

**Comment by mojavelinux** [comment]
> I'm assuming the no header flag is passed to whatever tool is rendering the content. 

That's correct.

> It's open source, so that's reasonable.

Thanks for understanding. Though it's more than that. We are 3/4 of the way to 1,000 issues and many of them are extremely high priority. Plus, we are trying to move the AsciiDoc Language project forward. So it's just not the right area of focus right now...especially given that there is a way to do this with extensions and it's not something that most people would even consider to be important, or even notice.
