### ISSUE TITLE
Support installation on Windows by WinGet

### ISSUE THREAD

**Issue by foxtrottNB** [asciidoctor/asciidoctor#4373]
Hello,

now that winget is usable, I prefer it to Choco. Maybe AD could be made insallable by WínGet?

BR

**Comment by mojavelinux** [comment]
This project does not handle packaging for external systems. If you want such a package to exist, please direct your request to WinGet. You can raise the topic in the project chat at https://chat.asciidoctor.org if you want to get other people involved and to help out.
