### ISSUE TITLE
Split default stylesheet into "minimal" vs "default" styles

### ISSUE THREAD

**Issue by infinity0** [asciidoctor/asciidoctor#4376]
I am using `asciidoctor -s` to create embeddable HTML fragments to put into other templates.

As explained [here](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#why-provide-a-default), these HTML fragments depend on the asciidoctor default stylesheet.

However, the asciidoctor default stylesheet also includes stuff that the HTML fragments do **not** depend on, and that actually **interferes** with the use-case of outputting HTML fragments to embed elsewhere. For example, specific color choices for headings and links, specific choices for padding, etc. It is not feasible to override these, because either (1) you must predict exactly how specific the original CSS selector used by the asciidoctor stylesheet was, or (2) you can use `!important`, but neither option is scalable.

In order to properly support embeddable HTML then, this stylesheet should be split into a "minimal" stylesheet (for the `-s` option for embeddable HTML fragments) and a "default" option (for standalone HTML documents).

Note that python-docutils does this already - it splits its stylesheets into [minimal.css](https://github.com/docutils/docutils/blob/master/docutils/docutils/writers/html5_polyglot/minimal.css) for embeddable HTML fragments, vs [plain.css](https://github.com/docutils/docutils/blob/master/docutils/docutils/writers/html5_polyglot/plain.css) for standalone HTML documents.

**Comment by mojavelinux** [comment]
I have no plans to implement a separate default stylesheet for Asciidoctor. If it's something you'd like to create and share with others, you are free to do so. But it's not something I want to add (and have to maintain) in this repository at this time.

**Comment by infinity0** [comment]
The idea is not a "separate" default stylesheet, it is to split the existing stylesheet, like docutils does. The long-term maintenance burden is just to think about the existing stylesheet in a more modular way, to help others avoid duplicating work that you've already done designing the existing stylesheet.

For example if I want to just change the colours, I have to understand the whole current stylesheet.

**Comment by mojavelinux** [comment]
Again, it's just not something I'm interested in having in core right now, so I have no plans of working on this. However, the stylesheet bundled in the gem is built from a source stylesheet. So if you'd like to propose a way to split that stylesheet and have the stylesheet build reassemble it, you are welcome to propose a PR and I will consider it.

**Comment by infinity0** [comment]
OK, thanks for the extra info. That will help me in my private project for the time being and we'll see if something publicly reusable comes out of it eventually.

**Comment by ggrossetie** [comment]
Somehow related: https://github.com/asciidoctor/asciidoctor/issues/4124

Also, we are working on a semantic HTML converter which will use its own stylesheet (and we will probably leverage CSS variables).

**Comment by mojavelinux** [comment]
Indeed, the new converter will be an excellent opportunity to set up this structure.
