### ISSUE TITLE
Highlight Select Lines NOT OK

### ISSUE THREAD

**Issue by life888888** [asciidoctor/asciidoctor#4378]
[Highlight Select Lines](https://docs.asciidoctor.org/asciidoc/latest/verbatim/highlight-lines/)

Highlight Select Lines NOT OK

```bash
$ asciidoctor -v
Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ asciidoctor-pdf -v
Asciidoctor PDF 2.3.3 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**a1.adoc**

```adoc
= Source highlight lines
//https://docs.asciidoctor.org/asciidoc/latest/verbatim/highlight-lines/
//OK - Highlight Select Lines
//:source-highlighter: pygments
//FAIL - Highlight Select Lines
//:source-highlighter: rouge
//:rouge-style: colorful
//:rouge-style: monokai
//FAIL - Highlight Select Lines
:source-highlighter: coderay
:icons: font
 
**source-highlighter** = **{source-highlighter}**
 
== Creating an application
 
To create a simple Ratpack application we write
the following code:
 
.Simple Groovy Ratpack application
[source,groovy,linenums,highlight='7-9']
----
package com.mrhaki
 
import static ratpack.groovy.Groovy.ratpack
 
ratpack {
    handlers {
        get {
            render "Hello World!" // <1>
        }
    }
}
----
<1> Render output
```

```bash
$ asciidoctor a1.adoc

$ asciidoctor-pdf a1.adoc
```
HTML - asciidoctor a1.adoc
![html](https://user-images.githubusercontent.com/101442875/198816742-4a576ca4-0a0c-4544-bf9c-a221676d011a.png)

PDF - asciidoctor-pdf a1.adoc
![pdf](https://user-images.githubusercontent.com/101442875/198816765-f9510298-b959-4d91-b8cc-8eed97a49ec3.png)

**Highlight Select Lines**
- coderay - HTML FAIL, PDF FAIL
-  rouge - HTML FAIL, PDF OK
- pygments - HTML OK , PDF OK

Do I need to also report Issues in Asciidoctor-PDF?

**Comment by mojavelinux** [comment]
The behavior you are describing is consistent with the documented behavior of the syntax highlighter integrations (and the best we can do with them). See the following page: https://docs.asciidoctor.org/asciidoc/latest/verbatim/highlight-lines/#usage-criteria

In the future, please ask questions in the project chat at https://chat.asciidoctor.org. The issue tracker is for verifiable bugs. Following this policy helps us to better manage this project.

**Comment by mojavelinux** [comment]
> coderay - HTML FAIL

Although subtle, you should notice that the line numbers are emphasized in bold in the CodeRay example. That's all CodeRay supports.
