### ISSUE TITLE
mathjax script tag appearing in pdf

### ISSUE THREAD

**Issue by bhatt-keshav** [asciidoctor/asciidoctor#4387]
I am using the latest Asciidoctor version 2.0.18. 

When I convert an asciidoc to pdf I get the following script on the 4th page of my document

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeXMML-
AM_HTMLorMML"></script>

```
![image](https://user-images.githubusercontent.com/53868299/205038675-51fedd21-dcb2-45d3-bf68-5e2ea6c0ae27.png)

**Comment by mojavelinux** [comment]
It sounds like your AsciiDoc source is producing invalid HTML, or is invalid itself. Please ask your question in the project chat at https://chat.asciidoctor.org and someone will likely be able to help you. When you post, please provide a complete example document and share what are using to convert the file to PDF.

The project chat is the preferred communication channel for support, not the issue tracker. To understand the project support policy, see https://docs.asciidoctor.org/about/support/
