### ISSUE TITLE
Front-matter does not preserve new lines when passed to preprocessor

### ISSUE THREAD

**Issue by verhas** [asciidoctor/asciidoctor#4389]
Asciidoctor documents skip the front matter, which is usually for Jekyll or some similar tool. My preprocessor needs this front matter, and I query it using 

```
final var frontMatter = document.getAttribute("front-matter", null);
```

My issue is that this method returns an empty string when the front matter is empty, but also an empty string when the front-matter is an empty line.

Empty front matter is
```
---
---
```

Front matter with one empty line is:
```
---

---
```

How can I distinguish between the two different cases?

**Comment by mojavelinux** [comment]
It's not currently possible. Empty lines in YAML are not considered to be significant. (See https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/reader.rb#L1276-L1294 for logic). However, since you're writing a preprocessor, you could process the front matter yourself instead of using the built-in functionality.

**Comment by mojavelinux** [comment]
I would challenge why you are relying on an empty line in front matter. It might be better to use a comment line so it is more explicit. But I don't know your use case.

I'd prefer if you asked questions like this in the project chat at https://chat.asciidoctor.org in the future. That makes it easier for us to manage this project.

**Comment by verhas** [comment]
>It's not currently possible. 

I accept that as a statement.

>Empty lines in YAML are not considered to be significant.

I see where this comes from, but I would challenge the relevance. Front-matter for Asciidoc is an opaque text. Jekyll and other tools treat this text as Yaml, but it is their business.

>However, since you're writing a preprocessor, you could process the front matter yourself instead of using the built-in functionality.

That would require the configuration of the plugin. It is a burden that I do not want to put on my users. I may be wrong in this.

>I would challenge why you are relying on an empty line in front matter.

My plugin does not. But for my plugin, the front matter is opaque. As it comes in, it should go out. The issue is that Asciidoctor preliminary consumes it and transforms it, and the transformation loses information. Should not cause any problem, but I am pedantic.

My preprocessor works with `xxx.adoc.jam` files edited in IntelliJ. When it runs it processes the input, and passes the processed output to the Asciidoctor plugin, but at the same time it also saves the `xxx.adoc` file. This `xxx.adoc` file can be processed by the command line Asciidoctor during the build process, or just used to deliver information from GitHub.

My blog site uses Jekyll. I edit my pages with Jamal but Jekyll uses the generated `xxx.adoc` files.

It is not absolutely correct to remove a line from the source when saving into `xxx,adoc`. There are workarounds in the preprocessor, and probably it is not really an issue.

As for the chat: I did not know about that.

Thanks for the clarification.

**Comment by mojavelinux** [comment]
I'm not sure you should be using a preprocessor for what you are doing. Asciidoctor is not designed to preserve the input. It is designed to convert it. How it deals with the front matter is entirely its business. And it is removing lines that are not considered relevant when processing that front matter.

You might want to consider something like Asciidoctor Reducer if all you want to do is process AsciiDoc input and produce AsciiDoc output. This just isn't what Asciidoctor is output. There was never any promise or guarantee that's what was intended to do.

I'm not entirely opposed to keeping the front matter exactly as is. So we could still consider keeping all the lines within the front matter as is. You are correct that Asciidoctor is not actually doing anything with those lines other than holding on to them, so it stands to reason it leaves them as they are.

**Comment by verhas** [comment]
>I'm not sure you should be using a preprocessor for what you are doing.

Jamal is a general-purpose text processor that can fetch textual data from different parts of the project. The idea is that whenever you copy information into your documentation, it gets stale after a while when the project changes and needs updating. This update can be automatic using Jamal. Jamal can include snippets, similarly (this feature is also implemented in Asciidoc), fetch variable names, values, and information from XML files (e.g. project version from pom.xml), and so on. There is no limit. Jamal is open, you can easily extend it in your project or provide libraries of just adding scripting to your macros in Ruby, Groovy, JavaScript, Java, or BASIC. Whenever there is a problem that someone cannot do using Asciidoc, Jamal can manage it as a preprocessor.

Note that Jamal is NOT ONLY an Asciidoctor preprocessor. It can be used in Word documents, JavaDoc, in pom.xml files, to preprocess Markdown or any other markup format.

>Asciidoctor is not designed to preserve the input.

I know that, but the interface I implement is called `Preprocessor`, which implies that it runs BEFORE Asciidoctor processing. I also understand that there is no clear solution because

1. It should run before, so a preprocessor may expect that the input is the same as it is in the file/editor, and at the same time
2. a preprocessor may assume that the input is Asciidoc to some extent. Hence the front matter is removed.

I also understand that the numerous preprocessors that already rely on front matter removal cannot be disturbed by such a change. On the other hand, the attribute "front-matter" could contain the empty line.

This is, however, low priority. There is no practical issue with it.

**Comment by mojavelinux** [comment]
Thanks for sharing that background.

> I know that, but the interface I implement is called Preprocessor, which implies that it runs BEFORE Asciidoctor processing. I also understand that there is no clear solution because

Well, that's just not entirely the case. Preprocessor is more that it runs "during preprocessing", which is a distinct phase of Asciidoctor. If you want to run before Asciidoctor touches the file, then you'd need to run it on whatever input you are passing to Asciidoctor.

> On the other hand, the attribute "front-matter" could contain the empty line.

I'm willing to consider keeping the front matter exactly as we found it. After all, we aren't actually doing anything with it in Asciidoctor, so it does matter much to us.

Please open a new issue to request that the front matter be kept as is. The current description is not clear enough because it talks about what it doesn't do. Let's frame it as what it should do.
