### ISSUE TITLE
test suite fails with ruby3.2.0 rc1 and onwards

### ISSUE THREAD

**Issue by mtasaka** [asciidoctor/asciidoctor#4390]
With asciidoctor b6ddf7d66c619f30e9e19deb398b0db1d7a4a82e or 2.0.18, asciidoctor test suite fails with ruby3.2.0 rc1 like:

```
[mockbuild@localhost asciidoctor]$ ruby -v
ruby 3.2.0dev (2022-12-10 master 0645c8b3c1) [x86_64-linux]
[mockbuild@localhost asciidoctor]$ LANG=C.UTF-8 ruby -I"lib:test" -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
Run options: --seed 43232

# Running:

...... <omitting many dots>.............................asciidoctor: ERROR: fixtures/iso-8859-1.txt: line 1: include file not readable: /builddir/build/GIT/asciidoctor/test/fixtures/iso-8859-1.txt
asciidoctor: WARNING: fixtures/iso-8859-1.txt: line 0: unterminated literal block
F.......................................

Finished in 3.155137s, 863.6709 runs/s, 3098.7561 assertions/s.

  1) Failure:
ReaderTest::TestPreprocessorReader::TestIncludeDirective#test_should_fail_to_read_include_file_if_not_UTF_8_encoded_and_encoding_is_not_specified [/builddir/build/GIT/asciidoctor/test/reader_test.rb:883]:
invalid byte sequence in UTF-8.
StandardError expected but nothing was raised.

2725 runs, 9777 assertions, 1 failures, 0 errors, 0 skips
```

With ruby3.2.0 rc1 and onwards, this fails. Looks like with ruby3.2.0preview3 this was okay. Not sure what changed this.

**Comment by mojavelinux** [comment]
This is very surprising considering Asciidoctor has been running on Ruby since 1.8.7. My gut tells me this is either a bug in Ruby or a major breaking change. I'm inclined to wait for another RC to see how this plays out, unless you have more information about what change is coming in Ruby.

**Comment by mtasaka** [comment]
Okay, after debugging, this code https://github.com/asciidoctor/asciidoctor/blob/b6ddf7d66c619f30e9e19deb398b0db1d7a4a82e/lib/asciidoctor/helpers.rb#L110 

is not working with ruby3.2.0rc1 when `data` is `"O\xF9 est l'h\xF4pital ?\n"` and `trim_end` is true.

This is definitely: 
https://github.com/ruby/ruby/commit/571d21fd4a2e877f49b4ff918832bda9a5e8f91c
https://bugs.ruby-lang.org/issues/18931
this is consistent that asciidoctor test passes with ruby3.2.0preview3, but not with rc1.

**Comment by mtasaka** [comment]
Confirmed that with the above test failing with ruby3.2.0rc1, `Encoding::CompatibilityError` is actually happening there.

**Comment by mojavelinux** [comment]
This is potentially a frustrating change in Ruby because we get all sorts of messy strings and we need to do everything we can do to make it work.

**Comment by mojavelinux** [comment]
I've done some more research and determined that the problem is not that Ruby behaves different with an invalid encoding, but rather that it behaves differently sooner. And due to the order of operations in Asciidoctor, this earlier exception gets swallowed into an application error message. I'll rearrange the order of calls so that the test assertion holds true.
