### ISSUE TITLE
Svg build badge doesn‘t display in table. 

### ISSUE THREAD

**Issue by donnels** [asciidoctor/asciidoctor#4391]
The following asciidoc code shows the SVG badge outside of the table but not in the table when the output is PDF. -a allow-uri-read is set. The table works fine in HTML. 

Is this a bug or is it a feature?

image::https://github.com/donnels/openscad-examples/actions/workflows/adoc.yml/badge.svg[badge]            

.status table
[format=csv,separator=",",options="header"]    
|===
status, comment
image::https://github.com/donnels/openscad-examples/actions/workflows/adoc.yml/badge.svg[badge] , working?
|===

.test table
[format=csv,separator=",",options="header"]    
|===
status, comment
test , working?
|===

the first badge displays but the second does not.

**Comment by mojavelinux** [comment]
It's necessary to set the "a" style on the column that contains block elements. Though it might be simpler in this case to switch to an inline image (a single colon).

In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal. Thanks!

**Comment by donnels** [comment]
> It's necessary to set the "a" style on the column that contains block elements. Though it might be simpler in this case to switch to an inline image (a single colon).
> 
> In the future, please direct usage questions to the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal. Thanks!

Thanks. I had assumed it was an issue as it still doesn't fly and the double colons had been a cut and paste error (very stupid mistake of mine) of the wrong test as the one I wanted to paste already had the single colon. The issue turns out to be with enterprise github and not with asciidoctor as I performed the test on github.com also and it works there. The answer still helps me though and I thank you. My apologies for the mix up.
