### ISSUE TITLE
Default CSS bug: Sidebar Combined with `[.right]` or `[.left]` produces ugly output

### ISSUE THREAD

**Issue by JSchrepp** [asciidoctor/asciidoctor#4396]
Using a sidebar to place content to the side has a spacing issue. `.sidebarblock` contains padding to separate its text from its border, but it does not contain a side margin to separate it from the text it is facing. We get the following spacing.

![image](https://user-images.githubusercontent.com/15899212/209842225-331aacd0-89ac-408f-9175-6161588553fc.png)

In this situation, the class should have margins equivalent to the padding, separating it from the text, as shown.

![image](https://user-images.githubusercontent.com/15899212/209842645-c81ffe33-cd35-47d0-b226-e1d39c3afcc9.png)

The class should only include these margins in this scenario, otherwise the standard spacing is ruined and the sidebar doesn't meet the edge of the document. This can be achieved with something like the following (1.25em was chosen since `.sidebarblock` contains `padding:1.25em;`).

```css
.sidebarblock.left {
    margin-right: 1.25em;
}
.sidebarblock.right {
    margin-left: 1.25em;
}
```

**Comment by mojavelinux** [comment]
The sidebar block does not support a restricted width. Therefore, there is no reason to support alignment on it. If you are using a custom stylesheet that restricts the width of sidebar blocks, then you can add the styles you cited into that stylesheet as well.
