### ISSUE TITLE
Advice on using the Table

### ISSUE THREAD

**Issue by ziwen1002** [asciidoctor/asciidoctor#4397]
首先定义如下简单的表格:
```
|===
|R1C1 |R1C2 |R1C3 |R1C4
|R2C1 |R2C2 |R2C3 |R2C4
|R3C1 |R3C2 |R3C3 |R3C4
|R4C1 |R4C2 |R4C3 |R4C4
|R5C1 |R5C2 |R5C3 |R5C4
|===
```
将单元格R1C1、R2C1、R3C1进行合并，将单元格R2C2和R3C2进行合并，当前的写法如下：
```
|===
.3+|R1C1 |R1C2 |R1C3 |R1C4
.2+|R2C2 |R2C3 |R2C4
|R3C3 |R3C4
|R4C1 |R4C2 |R4C3 |R4C4
|R5C1 |R5C2 |R5C3 |R5C4
|===
```

将会有如下的问题：

- 在编写过程中我可能随时修改合并的单元格个数
- 如果新增一行进行合并，将导致修改的地方很多，甚至要修改整个表格的格式
- 修改一个地方导致预览混乱，此时预览对修改没有任何帮助，只能检视代码

如果我按照如下方式使用将会简单很多:
```
|===
.3+|R1C1 |R1C2 |R1C3 |R1C4
|.2+|R2C2 |R2C3 |R2C4
|||R3C3 |R3C4
|R4C1 |R4C2 |R4C3 |R4C4
|R5C1 |R5C2 |R5C3 |R5C4
|===
```

- 每一行的写法是固定的
- 修改合并单元格时，我只需要修改合并单元格的个数就可以
- 预览不会很混乱，并且对修改有帮助

**Comment by mojavelinux** [comment]
Please ask support questions in the project chat at https://chat.asciidoctor.org. Thanks!
