### ISSUE TITLE
Include Multiple Auto Generated PlantUML into one diagramm.

### ISSUE THREAD

**Issue by CrazyToken** [asciidoctor/asciidoctor#4398]
Hi,

I am using asciidoctor to generate class diagramm svg automatically out of my c# sourcecode.
Therefore I am triggering https://github.com/pierre3/PlantUmlClassDiagramGenerator in my Jenkins Pipeline and afterwards convert the generated puml file into an asciidoctor export.

Lets take the following scenario:
File1.puml
`
@startuml
class People <<partial>> {
    + Name
}
@enduml
`

File2.puml
`
@startuml
class Car <<partial>> {
    + Name
}
@enduml
`

And the according Test.adoc:
`
[plantuml, github-demo, svg, width=800]
----
include::File1.puml[lines=1..-1]
include::File2.puml[lines=1..-1]
----
`

Using a regular include without the line filter ascidooctor-diagramm cuts off after finding the first @enduml tag in the File1.puml.
So I found the lines -1 filter option in the docs which seems amazing for my use case, as my @startuml and @enduml tag have to be unique for the whole diagramm (which is automatically splitted into seperate files).

But using latest asciidoctor version this does not work. It seems that the -1 line filter does not work at all.
Using absolut line numbers like 1..6 everything works, but as of the usecase, that the puml files are auto generated, I do not want to include hard coded line numbers.

`Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]) (lc:CP850 fs:UTF-8 in:UTF-8 ex:UTF-8)`

Any Ideas for my scenario to get line filter -1 working?

Thanks
Maik

**Comment by CrazyToken** [comment]
Unfortunately the formatting of the puml and adoc files are a mess in github issues, so I attached them here:
[AsciiDocIssue4398.zip](https://github.com/asciidoctor/asciidoctor/files/10390145/AsciiDocIssue4398.zip)

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org. We don't use the issue tracker for support. This policy is stated on the following page: https://docs.asciidoctor.org/about/support/ Thanks for understanding. I hope to see you in the project chat!
