### ISSUE TITLE
Create (or use an existing) message (logging) facility

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#44]
We'll need to be able to report warnings (and other messages) to the user. Rather than printing these to stdout, we should pass them through a message facility which can queue them, print them with styling, etc.

**Comment by jirutka** [comment]
What do you think about using core’s [Logger](http://www.ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html)? It seems that it’s quite flexible and extensible.

**Comment by mojavelinux** [comment]
That has come up before, perhaps in an IRC chat. I'm not opposed to using Logger. I've just been conditioned to dislike default Logger implementations based on the disaster in the Java ecosystem. If Logger provides the flexibility we need, then it's definitely worth prototyping a solution that uses it.

Keep in mind we didn't have a Logger originally because...we'll, the processor wasn't doing sophisticated things back then :) Now, we need a proper facility for handling messages...so we're on the market for the cleanest solution.

**Comment by mojavelinux** [comment]
One of the things I definitely want to do when we switch to the Logger interface is remove the need to hard code the application name with the message. The message formatter should allow us to insert this context into the message.

For an example of what I'm talking about, see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L275

**Comment by lordofthejars** [comment]
Yes logger interface may be an option, for example we Can create a ruby
class which fits the Logger interface so from Asciidoctorj point of view we
won t need to do anything, rather than passing an instance of Logger into
ruby code, like we do in converters or extensions
El dt., 6 de gen., 2015 a les 7.50 Dan Allen <notifications@github.com> va
escriure:

**Comment by jirutka** [comment]
> That has come up before, perhaps in an IRC chat.

Is there any other IRC channel than #asciidoctor on FreeNode IRC? I’m here almost all the time, but I’ve never seen there any core dev. :(

> I've just been conditioned to dislike default Logger implementations based on the disaster in the Java ecosystem.

JUL is indeed disaster, but Ruby is not Java and not every default logging facility is bad as in Java! It’s absolutely incomparable.

> Keep in mind we didn't have a Logger originally because...we'll, the processor wasn't doing sophisticated things back then :)

I understand that.

Well, I’ll look at it and send some suggestion how it can be possibly done.

**Comment by mojavelinux** [comment]
> Is there any other IRC channel than #asciidoctor on FreeNode? I’m here almost all the time, but I’ve never seen there any core dev. :(

I should have said "a long time ago on IRC" because I haven't been there for awhile. While IRC would be ideal for real-time communication, I find that the issue tracker + mailinglist is about all I can handle. Otherwise, my productivity just plummets.

**Comment by LightGuard** [comment]
In awestruct I switched from ruby core Logger to using the [Logging gem](https://github.com/TwP/logging) which works very similar to log4j. It also has colorization built in which is nice for the console output. We may even be able to easily configure or extend it in asciidoctorj so the default logging is passed on to the Java side.

**Comment by mojavelinux** [comment]
I'm really keen on using the built-in logging facility, though I wonder if it is like JUL in that it can delegate out to a third-party logging facility if present.

**Comment by jirutka** [comment]
I’ve already tried built-in logging facility and it’s too limited. However, [TwP logging](https://github.com/TwP/logging) is the second extreme, it’s IMO quite overkill for Asciidoctor.

**Comment by mojavelinux** [comment]
@jirutka Could you expand on that? (or point to where you already wrote something)

**Comment by jirutka** [comment]
@mojavelinux I’d like to, but it’s a year since I’ve touched logging support for Asciidoctor, I don’t remember any details. :( I didn’t find any branch so it seems that I ended at research phase.

**Comment by mojavelinux** [comment]
Gotcha. If anything comes to mind, I'd definitely be interested to hear it. Once we get past 1.5.5 and master is opened up for 1.6.0, I'd like to move first on this one.

**Comment by robertpanzer** [comment]
I played with semantic logger in my blog post.
Wonder if it would be an option for Asciidoctor as well.
The nice thing was that it allowed to hook in a custom handler, whereas
most other logging gems only supported configuration of a limited set of
handlers/appenders.

Am Mittwoch, 9. März 2016 schrieb Dan Allen :

**Comment by mojavelinux** [comment]
@robertpanzer I'm assuming you mean https://github.com/rocketjob/semantic_logger?

I like the sound of "low latency, high throughput". That's our kind of culture.

**Comment by robertpanzer** [comment]
Yes. I just don't have enough experience to say how it performs. 
But it seems to be an active project.

**Comment by LightGuard** [comment]
Wow! I just went through the code and it is one very well put together gem.
Very well documented also. This guy really knows what he's doing. +1 for
using this. It's also a three, almost four, year old project so it has a
good life. Shame it isn't more well known.

On Thursday, March 10, 2016, Robert Panzer <notifications@github.com> wrote:

> Yes. I just don't have enough experience to say how it performs.
> But it seems to be an active project.
>
>
>
> > Am 11.03.2016 um 01:40 schrieb Dan Allen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> >
> > @robertpanzer I'm assuming you mean
> https://github.com/rocketjob/semantic_logger?
> >
> > I like the sound of "low latency, high throughput". That's our kind of
> culture.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor/issues/44#issuecomment-195208212>
> .
>


-- 
Sent from Gmail Mobile

**Comment by robertpanzer** [comment]
Cool!
Then we would have the solution for the integration in AsciidoctorJ already in my blog post! :-)

> Am 11.03.2016 um 12:03 schrieb Jason Porter <notifications@github.com>:
> 
> Wow! I just went through the code and it is one very well put together gem.
> Very well documented also. This guy really knows what he's doing. +1 for
> using this. It's also a three, almost four, year old project so it has a
> good life. Shame it isn't more well known.
>

**Comment by mojavelinux** [comment]
That's great news!

**Comment by jmini** [comment]
As recommended by @mojavelinux on the mailing list, I am adding here my use case. I would like to generate an XML file with the warning/errors. In order to be able to reuse existing tools (like a Jenkins Plugin in my case) the XML format should be one of the existing static code analysis tools (like Findbugs, Checkstyle or PMD). 

Example: instead of the current output:
```
asciidoctor: WARNING: example-manual.adoc: line 17: list item index: expected 2, got 1
asciidoctor: WARNING: example-manual.adoc: line 25: callout list item index: expected 2 got 3
```

The output should be a separated XML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0">
    <file name="C:\*****\example-manual.adoc">
        <error line="17" message="list item index: expected 2, got 1." severity="warning" source=""></error>
        <error line="25" message="callout list item index: expected 2 got 3" severity="warning" source=""></error>
    </file>
</checkstyle>
```

This way I could offer user-friendly reports/dashboard on our CI-Server (jenkins). See the discussion and the screenshots in this thread: [Asciidoctor warnings as XML file](http://discuss.asciidoctor.org/Asciidoctor-warnings-as-XML-file-td4532.html).

**Comment by mojavelinux** [comment]
I continue to run into situations where I need this feature...so I'm bumping it up to 1.5.7. Even if we can get a quick solution in place, it will help a lot. Writing to stderr is really unwieldy.

**Comment by stevenschlansker** [comment]
We'd love it if the work also included considering the already linked https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/261 -- one of our most common issues with asciidoctor is that our build succeeds but generates broken documentation, and all the warnings / errors are buried in 10,000 line build outputs.

**Comment by ecki** [comment]
+1 for AsciidoctorJ (Java Extension), maybe the logging is not that important (i.e. Can use System.out), but a position (context) object is needed.

**Comment by mojavelinux** [comment]
The position is really a separate issue. That comes down to how the parser works. The focus here is to put the log messages into a place that an integration can use. Putting messages directly to stdout makes them hard to control, hard to find, and hard to filter.

**Comment by mojavelinux** [comment]
I'm happy to say that I almost have a PR for this change ready.

I've decided to use the default Logger in Ruby, but hear me out as to why. It's very important that the Asciidoctor processor not have any mandatory dependencies. This makes integrations and transpiling simpler. But, it doesn't mean you can't integrate the logger of your choice. It's all in the design.

All we really need to accomplish here is to differentiate between a message coming from the processor and a message coming from anywhere else in the Ruby runtime. That's the main problem with using the `warn` function for logging. It's all jumbled up. If we route messages through a logger that was created in Asciidoctor, then it's clear that those messages are coming from Asciidoctor. And you don't have to parse the message to get the level (and perhaps other context).

So the main change we have to make here is to invoke `logger.warn` or `logger.error` instead of `warn`. And that's our hook.

The question is, how is that hook handled? Well, by default, we'll stick a default logger in there to respond to the call and route the message somewhere (probably stderr). But if you want to intercept these messages with your own logger, you just replace the logger singleton. As long as the object you provide responds to the methods on the Logger interface (namely debug, info, warn, error, fatal), then Asciidoctor is none the wiser about how you handle the messages. That's why I think the default Logger is sufficient. Or perhaps I should say we can abstract away that choice.

Here's the logging infrastructure I'm proposing:

```rb
module Asciidoctor
class Logger < ::Logger
  def initialize *args
    super
    self.progname = 'asciidoctor'
    self.formatter = BasicFormatter.new
    self.level = WARN
  end

  class BasicFormatter < ::Logger::Formatter
    SEVERITY_MAPPING = { 'WARN' => 'WARNING', 'FATAL' => 'FAILED' }

    def call severity, _, progname, msg
      %(#{progname}: #{SEVERITY_MAPPING[severity] || severity}: #{msg}\n)
    end
  end
end

module LoggerManager
  @logger_class = Logger
  class << self
    attr_accessor :logger_class

    def logger
      @logger ||= (@logger_class.new $stderr)
    end

    def logger= logger
      @logger = logger
    end
  end
end

module Logging
  def self.included into
    class << into
      private
      def logger
        LoggerManager.logger
      end
    end
  end

  private
  def logger
    LoggerManager.logger
  end
end
end
```

Now to make the `logger` available to any class or module, I just need to include the `Logging` module.

```rb
module Asciidoctor
module Parser
  include Logging
  ...
end
end
```

There are two ways to set your own logger. Before the singleton is created (you've required asciidoctor but not used it yet), you can set the logger class.

```rb
LoggerManager.logger_class = MyLoggerClass
```

After the singleton has been created, or if you just want to set the instance directly, you assign it to the logger property:

```rb
LoggerManager.logger = MyLoggerClass.new
```

I'm also working on adding a `:logger` option to the load/convert API methods. This will overwrite the singleton, but we'll assume you understand that is what is going to happen. (Because of how Asciidoctor is currently implemented, I can't pass a per-instance logger through the processor).

**Comment by mojavelinux** [comment]
Related to this change is #2657, which proposes to store messages that pertain to the document on the document object itself. These messages could still get routed to the logger, but they'll be more accessible (no need to parse the log messages). They can be used by a client to determine if the document has any errors or warnings.

**Comment by mojavelinux** [comment]
I don't think messages produced directly by the CLI (outside of the call to the processor) should go to the log (or, at least, not all of them, such as the usage statement). This would be unconventional for a CLI. Instead, these messages will still get routed directly to stdout and stderr. Now that we have a logging infrastructure in place, we can handle any exceptions to this decision on a case-by-case basis.

**Comment by mojavelinux** [comment]
After I got the logging infrastructure set up, I took a closer look at the messages themselves. Many messages include information about the location in the AsciiDoc document where the problem occurs. This location is represented by a path and line number in the message (e.g., document.adoc: line 5: ...).

While we could just leave this information embedded in the message string, it's as valuable as the reason itself. So I think we should make it more accessible. Asciidoctor is also dropping some important information. When Asciidoctor reports a message that includes a path and line number, it actually knows the absolute file and directory as well. We should make this information available too.

When we have more information than just the message itself, instead of logging a string, I propose that we log an object. Fortunately, the built-in logger in Ruby allows this.

Since we already use the term "source_location" in the API, it's logical and consistent to also use this to pass information about the source of the message to the logger too. Here's what I propose:

```rb
logger.error :text => 'parts must have at least one section', :source_location => reader.cursor
```

This is great since we're now able to pass information about the source of the message to the logger. And the default logger can format the message in the traditional way:

```
asciidoctor: ERROR: document.adoc: line 5: parts must have a least one section
```

However, this extra information is not so nice for custom loggers (unless they provide a custom formatter too). For example, let's assume we want to use the built-in logger in Ruby:

```rb
Asciidoctor.convert_file 'document.adoc', logger: (Logger.new $stderr)
```

Now the message looks like this:

```
E, [<datetime> #27994]  ERROR -- : {:text=>"parts must have a least one section", :source_location=>#<Asciidoctor::Reader::Cursor:0x0000000001b1ae80 @file="/docs/document.adoc", @dir="/docs", @path="document.adoc", @lineno=5>}
```

Yikes!

But there's an easy way to fix this. There's a contract in Ruby's logger that it will coerce the message object to a string by calling `inspect` on it. So all we need to do is override the `inspect` method to have it automatically format in the default way.

To make this a bit easier, I propose introducing a helper method named `enrich_message` that can be used when logging the message. This method accepts the text as the first argument, then a Hash which provides additional context, such as `:source_location`. It then weaves in a module that overrides the `inspect` method.

```rb
logger.error enrich_message 'parts must have at least one section', :source_location => reader.cursor
```

Now the message is automatically formatted by the built-in logger.

```
W, [<datetime> #27994]  ERROR -- : document.adoc: line 5: parts must have a least one section
```

Of course, you can still format the message however you want by passing a custom formatter to your logger. All we're talking about here is just doing something with the message nice by default (and for the test suite).

**Comment by mojavelinux** [comment]
And it's in!

**Comment by jmini** [comment]
This is nice, thank you for this feature.

Can the logger infrastructure be accessed from an AsciidoctorJ extension?
Have you an example/pointer somewhere?

**Comment by Mogztter** [comment]
@jmini https://github.com/asciidoctor/asciidoctorj#logs-handling-api

**Comment by robertpanzer** [comment]
> Can the logger infrastructure be accessed from an AsciidoctorJ extension?

That's actually a good point.
While it's possible to receive the log entries that Asciidoctor logs, it's not possible yet for an extension to log using the same Logger that Asciidoctor is using.
I agree that it would make sense to expose this to extensions as well.
@jmini: Can you please open an issue for AsciidoctorJ?

**Comment by jmini** [comment]
@Mogztter, @robertpanzer thank you both for your answer. I have opened https://github.com/asciidoctor/asciidoctorj/issues/737
