### ISSUE TITLE
consider add a new icon macro font mode attribute to fit font awesome 6

### ISSUE THREAD

**Issue by hahaleyile** [asciidoctor/asciidoctor#4400]
Hi, could we just add a new attribute `icon style` to the icon attribute, like `icon:heart[style=regular]` ?
So that we could support font awesome version 5 and above.

https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4#what-s-changed-from-version-4-to-6

https://docs.asciidoctor.org/asciidoc/latest/macros/icon-macro/#icon-macro-attributes-font-mode-only

**Comment by mojavelinux** [comment]
This issue is already covered by #2535. I'd rather keep the discussion in that issue.

I have made it clear in that issue why this upgrade is so difficult. Font Awesome 5+ is nothing like Font Awesome 4 and requires us rethinking how it is integrated.
