### ISSUE TITLE
Bogus HTML escaping in manpage output

### ISSUE THREAD

**Issue by vinipsmaker** [asciidoctor/asciidoctor#4401]
I'm using asciidoctor for a multi-output documentation project. One of the outputs are manpages. For manpages, I don't expect images to show, so I fill the alt attribute on images as in:

```
.XKCD 1200: Authorization
image::authorization.png["If someone steals my laptop while I'm logged in, they can read my email, take my money, and impersonate me to my friends, but at least they can't install drivers without my permission.",link=https://xkcd.com/1200/]
```

The manpage output correctly identify such block as an image and make sure the user is aware of it by showing “Figure 1. XKCD 1200: Authorization” which is great. The manpage output will also correctly show the alt text instead of the image. However quotes are shown in the manpage output as `&#8217;` which makes no sense.

```
$ asciidoctor -v
Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

While I'm here... is there any way to break `[]` among multiple lines? asciidoctor will refuse to parse this element correctly if I try to break it along multiple lines.

**Comment by mojavelinux** [comment]
The manify function will need to be called on the alt text. I'm open to accepting a PR to fix this issue.

> While I'm here... is there any way to break [] among multiple lines?

Please don't ask unrelated questions in issue reports. That's what the chat at https://chat.asciidoctor.org.
