### ISSUE TITLE
sections with backticks being capitalized in manpages when they shouldn't

### ISSUE THREAD

**Issue by lemosjose** [asciidoctor/asciidoctor#4402]
The `asciidoctor` processor is not dealing well with sections that are currently marked with __backticks__, to be processed as source code by  asciidoctor, capitalizing content that will lead to errors when writing code. 

The backticks can be used to process all of the sections with a fixed width, but this side-effect of capitalizing everything in a `manpage` comes, where the problem of the width doesn't even exist (since it's running in terminals).

Although, since the bacticks mark something that should be seen as __source code__ in any context, this should not happen, since we are dealing with something that is mostly case-sensitive. 

Some samples and examples are provided in: 
`https://pastebin.com/8ncgyTFJ`

asciidoctor version:
`Asciidoctor 2.0.18`

**Comment by ggrossetie** [comment]
@lemosjose Could you please post the samples/example on GitHub?

**Comment by lemosjose** [comment]
Ok! these samples are the ones present in the pastebin, but it does happen with any possible content inserted like that. 

== `exclusive`

this complete file sample can help, you can test it locally with Asciidoctor 2.0.18

```
= sample(1)

== Name

sample - sample for github issue

== `noncapitalized` 

== CAPITALIZED
```
any content with backticks on a h2 heading (==) will be improperly capitalized, with can lead to code that doesn't work, since it's something that is case-sensitize when dealing with source code. it's the case shown at "noncapitalized"

**Comment by mojavelinux** [comment]
I can see the case for not transforming a monospace span to uppercase. I will submit a PR with that enhancement. Though, like all text formatting in the manpage converter, it will not consider nested formatting.

The manpage converter is designed to conform to the output of manpages on Linux, which almost always uppercases (not capitalizes) top-level sections. One workaround is to enclose any section whose titles contains monospace text in a more generic top-level section. The other workaround is the extend the converter and apply your own logic.
