### ISSUE TITLE
Slides template

### ISSUE THREAD

**Issue by bkmgit** [asciidoctor/asciidoctor#4404]
Many people now do online presentations.  Would contributions that:

1. add an example template for slides, see for example
  - CSS only, no javascript [site](https://bkmgit.github.io/PMlib-tutorials/#1) [repo](https://github.com/bkmgit/PMlib-tutorials/tree/html-slides)
  - Minimal javascript [site](https://nikolaialex.github.io/asciidoc-slides-site) [repo]()
  - PDF conversion [description](https://matklad.github.io/2019/05/19/consider-using-asciidoctor-for-your-next-presentation.html) [repo](https://github.com/matklad/rust-course)
2. adding a slides specification to AsciiDoc

be considered?

**Comment by alzeih** [comment]
Have you seen the reveal.js converter?

https://docs.asciidoctor.org/reveal.js-converter/latest/

**Comment by mojavelinux** [comment]
Please bring up ideas like this in the project chat at https://chat.asciidoctor.org. We can discuss there where information like this belongs and next steps.
