### ISSUE TITLE
Improve documentation: List all the valid [source] types

### ISSUE THREAD

**Issue by manueljordan** [asciidoctor/asciidoctor#4409]
In the current documentation at https://asciidoctor.org/docs/, for many sub sections such as [AsciiDoc Language Documentation](https://docs.asciidoctor.org/asciidoc/latest/) and [AsciiDoc Syntax Quick Reference](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) there is no a section listing all the _specific types_ sources codes, I mean, the normal use is 

```
[source]
.Some Name
----
code
----
```

Is valid use

```
[source,java]
.Some Name
----
code
----
```

I know is valid `xml` and `ruby` because they appear in some examples. But Where is the complete list of them?. Can I know if `Linux shellscripting` is valid? such as 

```
[source,???]
.Some Name
----
function abc(){
   cat abc.txt | grep "hello"
}
----
```

Thanks for you understanding

**Comment by mojavelinux** [comment]
The language keywords are inherited by the syntax highlighter. This comes right from the documentation:

> The available source language values are defined by the syntax highlighter library. In most cases, the source language value is the proper name of the language in lowercase (e.g., ruby, java). Most syntax highlighters also accept using the source file extension (e.g., js, rb), though it’s important to be consistent. If the syntax highlighter doesn’t recognize or support the source language, the block will not be highlighted.
> — https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/#apply-source-highlighting

 The AsciiDoc language itself does not define any language keywords itself.

If you're using Rouge (the recommended syntax highlighter), then the language keywords that are available can be found here:https://github.com/rouge-ruby/rouge/blob/master/docs/Languages.md

I'll add this reference to the docs for convenience.

I kindly request that you direct future questions about usage to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). We do not use the issue tracker as a support portal. Thanks!
