### ISSUE TITLE
Add Linux ShellScripting type syntax for [source]

### ISSUE THREAD

**Issue by manueljordan** [asciidoctor/asciidoctor#4410]
Can be added `[source]` support for _Linux ShellScripting_? Something like 

```
[source,???]
.Some Name
----
function abc(){
   cat abc.txt | grep "hello"
}
----
```

Thanks for your understanding

**Comment by alzeih** [comment]
Are you using rouge as your source highlighter? You may be looking for `shell`.

**Comment by mojavelinux** [comment]
The language keywords are inherited by the syntax highlighter. The AsciiDoc language itself does not define any language keywords itself. As alzeih has pointed out, if you are using rouge, then the correct language keyword for shell scripting is shell (or bash if you want it to be more specific). See https://github.com/rouge-ruby/rouge/blob/master/docs/Languages.md

I kindly request that you direct future questions about usage to the project chat at https://chat.asciidoctor.org. We do not use the issue tracker as a support portal. Thanks!
