### ISSUE TITLE
Wrong warning when displaying tag-like text as inline monospaced text

### ISSUE THREAD

**Issue by frederic-tingaud-sonarsource** [asciidoctor/asciidoctor#4414]
I am trying to display some text that would say
```
You should use the C++ feature `+[[noreturn]]+`.
```
The problem I have is that when my text refers a second time to `[[noreturn]]` I get a warning saying `id assigned to anchor already in use: noreturn`.
I believe that warning is wrong because the HTML generated does contain `<code>[[noreturn]]</code>` and no anchor and if I try to escape the brace with 
```
You should use the C++ feature `+\[[noreturn]]+`.
```
The resulting HTML contains the backslash `<code>\[[noreturn]]</code>`

**Comment by mojavelinux** [comment]
The correct way to write this would be as follows:

```
You should use the {cpp} feature `\[[noreturn]]`. You should use the {cpp} feature `\[[noreturn]]`.
```

You can't use a backslash inside an inline passthrough (or literal monospace).

In the future, I kindly ask that you direct usage questions to the project chat at https://chat.asciidoctor.org. Thanks!

**Comment by opoudjis** [comment]
Noting for posterity (FWIW) a similar issue with `stem:[[j, k\]]`: this is likewise being incorrectly recognised by the inline anchor parser as an inline anchor, because the Regex LeadingInlineAnchorRx has no lookbehind. The workaround for such macros is to introduce a space (or ZWJ) between the two brackets: `stem:[ [j, k\]]`

**Comment by mojavelinux** [comment]
I'm confident it works correctly if you are using the latest version of Asciidoctor.

**Comment by opoudjis** [comment]
No. As of this writing, the latest version of Asciidoctor is 2.0.23.

````
> cat a.adoc

= Document title
Author

== CLause

To evaluate the sparse matrix for the position stem:[[j, k\]] when *order* is *by_rows*,
1) evaluate *index* at position stem:[j] to obtain stem:[mlo],
2) evaluate *index* at position stem:[(j+1)] to obtain stem:[mhi],
3) search *loc* at positions stem:[mlo <= m < mhi] looking for the entry stem:[k],
4) if evaluation of *loc* at position stem:[m] returns stem:[k], then evaluate *val*
at position stem:[m] to obtain the sparse matrix entry for position stem:[[j, k\]], otherwise,
5) (stem:[k] not an entry in *loc* in the computed interval), the sparse matrix entry
for position stem:[[j, k\]] is *default_entry*. If the *order* is *by_columns*,
the roles of stem:[j] and stem:[k] are reversed.


> bundle info asciidoctor
  * asciidoctor (2.0.23)

> bundle exec asciidoctor a.adoc
asciidoctor: WARNING: a.adoc: line 11: id assigned to anchor already in use: j
asciidoctor: WARNING: a.adoc: line 13: id assigned to anchor already in use: j
````

The instances on line 11 and 13 are the two instances of `stem:[[j, k\]]`
