### ISSUE TITLE
MathML directly in STEM expressions

### ISSUE THREAD

**Issue by franklinvp** [asciidoctor/asciidoctor#4422]
MathML and LaTeX/AsciiMath don't express the same type of information.
For that reason, it is not always easy to convert to AsciiiDoc a large project that contains equations in MathML, for example from DITA.

Could AsciiDoc allow embedding MathML directly, for example, in the `STEM` expression or other?

----

One way in which the MathML can be embedded is to put it inside a passthrough block. For example,

```
A displayed
++++
<equation-figure>
<mathml>
<math xmlns="[http://www.w3.org/1998/Math/MathML"](http://www.w3.org/1998/Math/MathML%22) display="block">
  <msqrt>
    <mn>2</mn>
  </msqrt>
</math>
</mathml>
</equation-figure>
++++
equation
```

Conversion to HTML works fine. MathJax takes care of rendering the equation.
However, `asciidoctor-pdf` gives `ERROR: failed to parse formatted text`.

**Comment by mojavelinux** [comment]
If you want to embed MathML directly, you can do so using a passthrough block as you suggested. As to whether Asciidoctor PDF permits that or not is a concern of that converter, not the core processor.

**Comment by franklinvp** [comment]
I see, I had not realized that `asciidoctor-pdf` is a separate project.
