### ISSUE TITLE
Convert AsciiMath to MathML in conversions using the html5 backend.

### ISSUE THREAD

**Issue by expeehaa** [asciidoctor/asciidoctor#4423]
The html5 converter currently adds a script tag for MathJax to render AsciiMath. MathJax is loaded by the client from Cloudflare’s CDN, which has both security issues and, most importantly, is not available without an internet connection.
Fortunately, almost all browsers in at least recent versions now natively support MathML rendering and there is a nice gem in this organization called `asciimath` which supports conversion of AsciiMath to MathML.
I prototyped an implementation of this as a `TreeProcessor` extension (based on how `asciidoctor-mathematical` implements it) and it works pretty well, except for my inability to create nice styling.

`asciidoctor` currently does not have any runtime dependencies AFAICT, so I am wondering whether this is intentional (e.g. since different Ruby interpreters are supported) and under which conditions it could be acceptable to include `asciimath`. If it is fine, I would like to try creating a pull request.

**Comment by mojavelinux** [comment]
This is a duplicate of #4237.

**Comment by expeehaa** [comment]
Oh, sorry, I did see that and forgot about it. I’ll comment there then.

**Comment by mojavelinux** [comment]
Thanks!
