### ISSUE TITLE
Need of Rasciidoc

### ISSUE THREAD

**Issue by aksigkvgithub** [asciidoctor/asciidoctor#4434]
I have been an Rmarkdown user since long. Wrote a book and published too. When I was a quarter depth into writing that book, then I realized that this Rmd format is not sufficient for writing a book. It was however good at merging the R-code output into the main text beautifully. But, I had to go to latex as well as html codes, where I was not good at all. Somehow, I completed the book in 3-long-years. But, since then I was trying other platforms, which have all the potentials of writing a book writing capability without help of latex or html or docbook, each of them are complex enough for a common mathematics user like mae. 

I tried markdown - too simple to achieve the goal
I tried latex and html - too complex to find proper code at proper time
I tried restructured text - could not find proper help pages to fulfill my requirements
I asciidoc.py - but it has been phased out

Then I came across asciidoctor. I found it very good and simple enough to handle complex formats too.  But, I am finding following types of difficulties, and am proposing based on them only:

1. Asciidoctor has a source block structure, which renders many languagues inside the block. However, it does not handle R-codes inside the source block structure. At present, I am handling it somehow following the instructions at https://kbroman.org/knitr_knutshell/pages/Rmarkdown.html,

2. This entails two major problems:
    i) when running the codes inside the comment blocks, as advised therein the reference cited above, some R-code outputs are not contiguous and have some line breaks in-between. There the continuity of the asciidoc paragraphs, adhered to by putting plus (+) signs in-between the paragraphs and R-code blocks, breaks out the outline numbering and alignments of entire output, i.e. fully disturbed.
    ii)  I cannot envisage the output of R-code blocks from within asciidoc, so composition of entire article/book becomes painful.

3. Asciidoc html output is wonderful, even with the stem blocks, especially at latex type math stems. By the way, I am a heavy user of mathematics, hence the requirement of mathematical formulae and computations using R-codes.

4. Its pdf through asciidoctor-pdf is very nice, **but does not render the stem blocks**, neither asciimath nor latexmath, **because I failed to install asciidoctor-mathematical many many times**.

5. In the search, I came across asciidoctor-web-pdf too. Its output is wonderful, it converts all the stem blocks too. **But, its page break is problematic.** I have written about the same among the issues at its github platform.

6. Looking into all of above problems and solutions, I think that there are thousands of Rmarkdown users who really need a platform like Rasciidoc.

7. When I say, Rasciidoc, then I mean the type of system Rmarkdown has adopted.

8. That is, the basic text would be in asciidoc though asciidoctor, but the source block could be rendered with R-codes too, inside the asciidoc while writing the codes, as well as after rendering the same.

9. Rendering could have both options:
    i) though asciidoctor-pdf - for non-mathematics users
    ii) through docbook-pandoc-pdf toolchain for mathematics users, but this loses the page-settings
    iii) Or, though docbook-latex-pandoc, for mathematics users, here too the platform may ensure proper page setting
    iv) html throgh asciidctor - for all users, as it is already fantastic
     v) through asciidoc-web-pdf - for all users, but page break issue may be handled.

10. My proposition for Rasciidoc is for the route though latex and pandoc to pdf, which asciidoctor is completely lacking, while at the same time asciidoctor-mathematical is completely uninstallable without docker, which is very heavy for common computers. 

11. The language R has a package too with name of Rasciidoc too, which was deprecated because probably nobody at asciidoctor or pandoc furthered this concept. There are thousands of Rmarkdown users who need platform like Rasciidoc. I propose that now is the time to revive the use of Rasciidoc with active support from asciddoctor and pandoc.

Thanking in advance.

**Comment by mojavelinux** [comment]
I have asked you to post questions about usage (which includes sharing needs you have) in the project chat rather than the issue tracker. The issue template also asked you to do so as well. If you continue to ignore this policy, you will not be permitted to participate in this community. The issue tracker is for verifiable bugs, regressions, security vulnerabilities, and formal and specific change requests. It is not a support portal. Please respect this policy.
