### ISSUE TITLE
Incorrect formatting when URLs contain <> angle brackets

### ISSUE THREAD

**Issue by Querela** [asciidoctor/asciidoctor#4441]
I seem to have some weird input construct (URL with angle brackets) that is being rendered incorrectly. This then fails to correctly format primarily in `asciidoctor-pdf` but the HTML one also seems to contain artifacts. Monospacing does not seem to be the issue, just URLs containing at least `<>` or with some letters inbetween.

My example document fragment was:
```
{empty}... the URI `http://repos.example.org/resource.cgi/<pid>` is a ...
```

It produces:
> ... the URI `http://repos.example.org/resource.cgi/<pid>;` is a ...

But it should produce:
> ... the URI `http://repos.example.org/resource.cgi/<pid>` is a ...

*Note, the trailing semicolon `;`.*

I tried using \`\` instead of \`. I tried escaping either or both of `<`, `>` with `&gt;`, `&lt;`.

I tested it online in the https://asciidoc.org/ first texteditor box, and I currently use the `asciidoctor/docker-asciidoctor` Dockerimage in my Github Actions workflow (it seems to always pull the latest, `sha256:6d1ebfc7e985b8f7aa5d98a97fc065a6655d00050022496bddd2ba3dadd48df4`, which might still not be current enough? (9 days ago))

Output of `asciidoctor-pdf` is:
```
asciidoctor: ERROR: failed to parse formatted text: In the following example, the URI <code><a href="http://repos.example.org/resource.cgi/&lt;pid&gt" class="bare">[http://repos.example.org/​resource.cgi/​&lt;pid&gt](http://repos.example.org/%E2%80%8Bresource.cgi/%E2%80%8B&lt;pid&gt)</a>;</code> is a ... (reason: Expected ';' after <code><a href="http://repos.example.org/resource.cgi/&lt;pid&gt" class="bare">[http://repos.example.org/​resource.cgi/​&lt;pid&gt](http://repos.example.org/%E2%80%8Bresource.cgi/%E2%80%8B&lt;pid&gt) at byte 163)
```

The smallest example would be: `http://<>` that still shows the error. It seems to be a combination of both rendering a hyperlink and escaping entities. In `http:/<>` it is ok (no valid URL, the issues does not appear anymore).

My intended use was showing placeholders in template URLs. It might be possible (not sure) to disable the URLification of the URL at this specific location?

**Comment by Querela** [comment]
Ok. Sorry, I thought it was an issue. Next time I will try the chat first.

**Comment by mojavelinux** [comment]
No worries. I look forward to seeing you there!
