### ISSUE TITLE
Escaped replacement in doctitle (mantitle) creates invalid output in DocBook output

### ISSUE THREAD

**Issue by felipec** [asciidoctor/asciidoctor#4445]
Some manpages require double dashes (`--`), but there's no consistent way to write them:

    = foo--bar(1)

This generates a proper output for the `manpage` backend, but not `html` or `docbook5`, they get replaced with `&#8212;&#8203;`.

If they are escaped:

    = foo\--bar(1)

Then the `manpage` and `html` backends work fine, but `asciidoctor -b docbook5 -d manpage` doesn't, as it generates this:

    <refentrytitle>foo\--bar</refentrytitle>

And docbook stylesheets doesn't generate a proper manpage.

It seems no combination works, except using an attribute, and then do something like `foo{dd}bar`, but that seems far from ideal.

If there was a way to globally disable this replacement (as suggested in #1061) then I suppose things would just work.

It seems `mantitle` is not being parsed correctly, but it can't be specified either.

**Comment by mojavelinux** [comment]
The issue reads more like a diatribe than a change request. Can you please save such commentary for the project chat?

If I'm understanding correctly, you would like to be able to escape the em dash replacement in the doctitle and not have that backslash appear in text in the `<refentrytitle>` tag. Is that what you're asking?

> This generates a proper output for the manpage backend, but not html or docbook5, they get replaced with `&#8212;&#8203;`.

This **is** the proper output. You've used the syntax for an [em dash](https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/) and it was replaced as it should be. If you don't want the replacement to happen, then the markup has to be escaped using a backslash. That's how the AsciiDoc syntax is defined. (The fact that the backslash shows up in the `<refentrytitle>` is the outstanding issue at hand).

Another option would be to allow the `mantitle` attribute to be specified explicitly. This has never been requested before. However, I can see how it could help with corner cases. If you feel strongly that should be possible, please file a separate issue for that.

**Comment by mojavelinux** [comment]
I don't like your tone and therefore I'm closing this issue. I am the lead of this project and you are showing me tremendous disrespect. I don't need to put up with that.
