### ISSUE TITLE
Cross-references to ordered list items with non-Arabic numeration render as Arabic numerals

### ISSUE THREAD

**Issue by billandel** [asciidoctor/asciidoctor#4460]
If I create an ordered list with a numeration other than `[arabic]`, e.g.,

```
:ref-caption: Reference
[loweralpha]
. [[thing-one,{ref-caption} {counter:ref-no}]]The Cat in The Hat
. [[thing-two,{ref-caption} {counter:ref-no]]The Cat in The Hat Came Back
```

...I get a list which (correctly) looks like:

```
a. The Cat in The Hat
b. The Cat in The Hat Came Back
```

...but, when I use the references...

`See <<thing-one>> and <<thing-two>>.`

...I get numbers vs. letters:

`See Reference 1 and Reference 2.`

...which was not my intent.  Is there any way to make such references render as:

`See Reference a and Reference b.`

...instead?

**Comment by mojavelinux** [comment]
Counters have no relationship to the list numeration. You would need to define the first counter as {counter:ref-no:a} to switch it to alpha too.

I'll warn you that, in general, counters are very poorly designed in AsciiDoc (See https://docs.asciidoctor.org/asciidoc/latest/attributes/counters/). In light of that, there is only so deep you can go with them. We're exploring alternate solutions in the AsciiDoc Language.

**Comment by billandel** [comment]
Thanks, Dan.  Don't know how I missed that in the manual.  And don't be too hard on the counters  - they work well enough.  Thanks for this amazing tool.
