### ISSUE TITLE
Include directives with target containing spaces not working with -S secure

### ISSUE THREAD

**Issue by dometto** [asciidoctor/asciidoctor#4461]
The following syntax:

```
include::foo bar.adoc[]
```

* works as intended with `-S unsafe`
* outputs the following with `-S secure`: `link:foo bar.adoc[role=include]`

It looks like:
1. it's converting the `include` directive to a `link` directive because of `secure` mode (intended)
2. but this `link` directive is not being rendered because of the space

Since [it's intended functionality that asciidoctor supports include directives with targets including spaces](https://github.com/asciidoctor/asciidoctor/issues/798#issuecomment-28855366), this seems like a bug to me. If targets including spaces are supported, and include directives with `-S secure` are too, shouldn't `include` targets with a space in secure mode also be fully supported?

I think the intuitive behavior would be for the link in secure mode to be rendered as follows: `<a href="foo%20bar.adoc" class="bare include">foo bar.adoc</a>`

**Comment by bartkamphorst** [comment]
Thanks for the fix @mojavelinux !
