### ISSUE TITLE
How to display a button for downloading PDF in HTML

### ISSUE THREAD

**Issue by jiangxinshang** [asciidoctor/asciidoctor#4464]
I want to download the PDF document directly from the generated HTML page. I'm not sure if there are any components to implement it

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org as the issue template suggested and is stated in the docs https://docs.asciidoctor.org/about/support/#chat. The issue tracker is not the right place for it.
