### ISSUE TITLE
Column style should not affect header in DocBook table

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor#4473]
Given a table with a header and a format style qualifier for a column, for example:
```
[cols="3,4m,3", options="header"]
|===
| Assignment | Syntax | Eval
| simple | A = B | Deferred
   ...
|===
```
the DocBook translation gives the literal style also to the header term `Syntax`. Have not checked all the style options but the same behavior is shown using  `s` and `l`. This does not seem right as you typically want to style the header independently of the table body. Also, the header is not affected in this way with the HTML translator.

**Comment by mojavelinux** [comment]
This is not a true statement. The style is never applied to cells in the header row. In fact, even the style on a cell in the header row is ignored. If I feed the following source into Asciidoctor:

```
[%header,cols="3,4m,3"]
|===
|Assignment |Syntax |Eval
|simple |A = B |Deferred
|===
```

Then the result I get is as follows:

```
<informaltable frame="all" rowsep="1" colsep="1">
<tgroup cols="3">
<colspec colname="col_1" colwidth="30*"/>
<colspec colname="col_2" colwidth="40*"/>
<colspec colname="col_3" colwidth="30*"/>
<thead>
<row>
<entry align="left" valign="top">Assignment</entry>
<entry align="left" valign="top">Syntax</entry>
<entry align="left" valign="top">Eval</entry>
</row>
</thead>
<tbody>
<row>
<entry align="left" valign="top"><simpara>simple</simpara></entry>
<entry align="left" valign="top"><simpara><literal>A = B</literal></simpara></entry>
<entry align="left" valign="top"><simpara>Deferred</simpara></entry>
</row>
</tbody>
</tgroup>
</informaltable>
```

That's precisely what we expect it to do.

It's possible you are either using a custom converter or that the syntax is off somewhere else and is affecting the parsing of the table.

**Comment by mojavelinux** [comment]
If you need further help, please ask in the project chat at https://chat.asciidoctor.org.
