### ISSUE TITLE
description lists: orthogonalize the `marker` `starts` `indented`

### ISSUE THREAD

**Issue by goyalyashpal** [asciidoctor/asciidoctor#4475]
Hi! thanks a lot for this wonderful project.

### Current Scenario:

following block styles are avaliable for [description lists]   i.e. the double-colons `::` in asciidoctor

[description lists]: https://docs.asciidoctor.org/asciidoc/latest/lists/description-with-marker/

Note:
* The style given in first column results in properties given on right.
* Alignment of `dt` is applicable only when `dd` is indented at full width.

| style | marker | start-as (dd) | indent-at (dd) | align-dt | formatting (dt)
| -- | -- | -- | -- | -- | -- |
default (no style) | no | stacked | fixed | NA | _**bold-italic**_ or **bold**
`horizontal` | no | run-in | full-width | left | **bold**
`qanda` | number | stacked | no | NA | _italic_
| experimental 👇 | 
`unordered` <br/>or `ordered` | bullet <br/>or number | either | no | NA | **bold**

### Problems

Currently:
* these 4 features: marker, stack, indent & formatting are coupled very strongly.
* which bans certain styles to be attainable

so, for example:
* you can't have a list with a run-in starting `dd` with fixed indent.
reference: this is the default style of the `itemize` environment in latex if i recall correct. 
* you can't specify the `dt` to be right aligned with the [indentation river]. 
yet again, this style is used in documentations of several libraries or programmes in programming languages. 

+ example: `lshort`, `latex-cribsheet` ; examples: `source2e`, `tocloft`, `xcolor`

[indentation river]: https://www.sqlstyle.guide/#white-space

<details><summary>styles not possible currently with description lists in asciidoc</summary>

Screenshots:

+ <img src="https://github.com/asciidoctor/asciidoctor/assets/19423063/8d907ba4-991a-4a0f-8f4b-2d891254b5d9" width=300px title="lshort preface"/>

+ <img src="https://github.com/asciidoctor/asciidoctor/assets/19423063/4ed55550-333a-4136-9fff-9c952c7f271a" width=300px title="source-2e"/><img src="https://github.com/asciidoctor/asciidoctor/assets/19423063/99cdb8d9-7189-4c43-9866-600189332b0c" width=300px title="xcolor"/><img src="https://github.com/asciidoctor/asciidoctor/assets/19423063/2a493b7a-b94b-4303-8068-c79638a456b9" width=300px title="tocloft"/>

</details> 

### Thoughts

* But this coupling should not be the case, these options should exist independently & usably orthogonally:
* This orthogonality will reverse the direction of dependence 
* ... & will make the current styles as merely combination presets of these options, 
* with only `qanda` still remaining as a preset with relevant combination.
* and `horizontal`, `ordered` and `unordered` presets being left meaningless and confusing
* but kept around as deprecated-legacy for bwd compatibility

#### Proposal:
the proposal is about the exact idea, not the exact words 
(quote: "most difficult prob in CS is naming things" - & i leave that to u lol)

Note: _default_ is italicised

* **marker**: _none_ | ordered | unordered
to define if there is a marker or not

* **start**: run-in | _stacked_
to define how or say at which line the `dd` starts w.r.t `dt`

* **indent**: no | _fixed_ | full-width
to define how much `dd` indented additionally with respect to `dt`

* if indent=full-width; only then: **align-dt**: left | _right_
to define the alignment of `dt` with respect to the indentation river of `dd`

* **formatting**: _bold_ , italic, monospace

### Signoff

I think that currently proposals are not accepted, but as this is already under discussions due to being experimental, i thought to share these here.

* this issue can supersede the issue: https://github.com/asciidoctor/asciidoctor/issues/821#issuecomment-917364303

**Comment by mojavelinux** [comment]
I don't understand why a new issue was necessary here. I think these points can be raised in #821 instead. That said, this proposal introduces entirely too much coupling between markup and presentation, especially indent and formatting. I'd be open to slight modifications of the existing proposal in #821 to allow more combinations, but not by introducing new presentation controls. We're getting too far away from semantic markup. If that is something you desire, it's better done in an extension where you have such freedom..

**Comment by goyalyashpal** [comment]
> I think these points can be raised in #821 instead

fine
