### ISSUE TITLE
blank line in all table cells (man pages)

### ISSUE THREAD

**Issue by strager** [asciidoctor/asciidoctor#4482]
Tables in man pages have a blank line at the top of each table cell. For example:

    [cols="1,1"]
    |===
    |Cell in column 1, row 1
    |Cell in column 2, row 1

    |Cell in column 1, row 2
    |Cell in column 2, row 2

    |Cell in column 1, row 3
    |Cell in column 2, row 3
    |===

Man page output (using Linux's man command):

    ┌────────────────────────┬─────────────────────────┐
    │                        │                         │
    │Cell in column 1, row 1 │ Cell in column 2, row 1 │
    ├────────────────────────┼─────────────────────────┤
    │                        │                         │
    │Cell in column 1, row 2 │ Cell in column 2, row 2 │
    ├────────────────────────┼─────────────────────────┤
    │                        │                         │
    │Cell in column 1, row 3 │ Cell in column 2, row 3 │
    └────────────────────────┴─────────────────────────┘

I don't like the blank lines. I think the output should instead look like this:

    ┌────────────────────────┬─────────────────────────┐
    │Cell in column 1, row 1 │ Cell in column 2, row 1 │
    ├────────────────────────┼─────────────────────────┤
    │Cell in column 1, row 2 │ Cell in column 2, row 2 │
    ├────────────────────────┼─────────────────────────┤
    │Cell in column 1, row 3 │ Cell in column 2, row 3 │
    └────────────────────────┴─────────────────────────┘

**Comment by strager** [comment]
Proposed fix: #4480

**Comment by mojavelinux** [comment]
This issue came up again in #4529. Since the fix changes the appearance of the output, I made the decision to not include it in a 2.0.x patch release as I assert that would violate the semantic versioning contract. If you disagree, feel free to make your case here.

**Comment by mojavelinux** [comment]
I think you've misunderstood me. This fix has already been applied to the main branch (see https://github.com/asciidoctor/asciidoctor/pull/4480) and will be included in the upcoming 2.1.0 release.

The question is not whether to fix it, but whether backporting it to 2.0.x violates semver. I assert that it would.

**Comment by mojavelinux** [comment]
> Though idk if .sp's inside the cells are a feature for some table types

They are for multi-paragraph table cells and AsciiDoc table cells. We're absolutely not going to remove them in those cases since doing so would be unreasonable and lead to incorrectly formatted cells. However, it is correct to remove them from the top of normal table cells, which this fix already does.

**Comment by mojavelinux** [comment]
> Is Asciidoctor's manpage generator designed to emit groff extensions to roff?

Yes. The origin of the converter is to mirror the output of the DocBook toolchain, which itself makes use of groff.

> If that is the case then it will be good to consider -b manpage-roff -b manpage-groff. 

No. We're targeting the man pager we are targeting and it is has worked for well over a decade. If you need something different, you are welcome to create your own converter or extend the built-in one. (See https://docs.asciidoctor.org/asciidoctor/latest/convert/custom/)

> limit themselves to -roff which is compatible everywhere I guess.

That's not a limitation we need to concern ourselves with in this project. That's more of a deficiency of the man pager and should be addressed there (or, like I said, you're free to create or customize your own converter).

> I mean as a developer the last thing you would want is that your manpage

We have never received any other report of a man pager crashing when viewing man pages produced by Asciidoctor. Again, it seems to be a deficiency of the pager itself and should be reported there.

If you need further assistance, you are welcome to ask in the project chat. I don't want this thread to veer off course from what it was originally indented for, which is the remove the excess blank lines at the top of table cells.

**Comment by mojavelinux** [comment]
> Could you provide some examples that I can test with FreeBSD manpages? 

You can consult the test suite if you are interested in examples.

**Comment by mojavelinux** [comment]
I'd be open to including that notation if you submit a PR to add it.

**Comment by mojavelinux** [comment]
Btw, the API docs for the manpage converter states the following:

> The output of this converter adheres to the man definition as defined by groff and uses the manpage output of the DocBook toolchain as a foundation.

So this has never not been true. See https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/converter/manpage.rb#L4-L13

**Comment by mojavelinux** [comment]
I understand that. I was just clarifying why such a statement would be acceptable in the docs. In fact, you may choose to reuse some of that wording.
