### ISSUE TITLE
Free positioning of callouts within code blocks

### ISSUE THREAD

**Issue by svetterIO** [asciidoctor/asciidoctor#4489]
Free positioning of callouts would improve documentations and point audience focus to respective callout.

A rendered example of a console command I could think of would look like this:
![image](https://user-images.githubusercontent.com/2234705/188167463-281821f3-7208-4d65-b860-b69813b2acc4.png)

The code block might look like this then:
```
----
[user@host ~]# command -a<1> arg1 -b<2> arg2 ...
----
<1> first argument a
<2> second argument b
```

I'm not sure how much effort this requires or if there are blockers preventing implementation.
E.g. Copy and paste friendly callouts wouldn't work for this (https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/). This would even require a different solution for inline callouts to work on C&P. Maybe additional `line-comment suffix` to the existing `line-comment prefix` feature ?!

I would like to use this issue ticket to discuss ideas or find alternatives...
appreciate any help

**Comment by ggrossetie** [comment]
I believe it's a duplicate of #3037 no?

**Comment by mojavelinux** [comment]
Yes, this is a duplicate.
