### ISSUE TITLE
"Images / Position and Frame Images" Doesn't Support "Headings"

### ISSUE THREAD

**Issue by paulmcquad** [asciidoctor/asciidoctor#4507]
I want to have 2 Paragraphs next to each other with a image on the right side like this ->

![image](https://github.com/asciidoctor/asciidoctor/assets/980002/78fd3841-5cac-4549-9ccd-4dc682cfe1cc)

The problem is that is doesn't support Headings for the Paragraphs.
Here's the code i used:
```
[.float-group]
--
[.center]

=== What is an Operating System?

.Operating System Levels
image::images/Operating_system.png[OS,150,150,float="right"]

An Operating System performs all the basic tasks like managing file, process, and memory. Thus operating system acts as manager of all the resources, i.e. resource manager. Thus operating system becomes an interface between user, applications and hardware. <<intro-os>>

=== What is Computer hardware?

Computer hardware includes the physical parts of a computer, such as the case, central processing unit (CPU), random access memory (RAM), monitor, mouse, keyboard, computer data storage, graphics card, sound card, speakers and motherboard.<<intro-hardware>>
--
```

Addition Info:
Position and Frame Images
https://docs.asciidoctor.org/asciidoc/latest/macros/image-position/#control-float

**Comment by mojavelinux** [comment]
When you put a heading inside a block, you must add the `discrete` style to it. See https://docs.asciidoctor.org/asciidoc/latest/blocks/discrete-headings/.

In the future, please direct questions about usage to the project chat at https://chat.asciidoctor.org. The issue tracker is for verified issues and formal proposals.

**Comment by paulmcquad** [comment]
Thanks but you can't use discrete style on 2 headings without the Second heading leaving the Image Frame and printing below the image not the side. Thanks in advance.

**Comment by mojavelinux** [comment]
In that case you need to further nest the elements so that there are only two elements inside the float group. This is just a constraint of the language.

**Comment by mojavelinux** [comment]
I would prefer to have this discussion in the chat. Please honor that request.
