### ISSUE TITLE
Edgar Allan Poe's name misspelled in unordered-list example

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor#4519]
In the files `data/reference/syntax.adoc` and `test/fixtures/lists.adoc`, the celebrated writer's middle name is spelled `Allen` rather than the correct `Allan`.

(If the misspelling was deliberate, and intended to match the lead developer's own name, this issue may be ignored.)

**Comment by mojavelinux** [comment]
I can tell you it was not intentional to misspell his name. If you'd like to submit a PR to fix it, I'll merge it in.

**Comment by ggrossetie** [comment]
> writer's middle name is spelled Allen rather than the correct Allan.

Edgar Dan Allen Poe 😂
