### ISSUE TITLE
Replace a tagged region during include

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor#4521]
Image an HTML file with an SVG embedded, something like this:

```
<!-- tag::html[] -->
<html>
  <h1>My title</h1>
  <!-- tag::svg[] -->
 <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor"> <path d="..."></path> </svg>
 <!-- end::svg[] -->
</html>
<!-- tag::html[] -->
```

I would like to be able to replace the long `<svg>` contents with some placeholder.

I can currently just remove the SVG like this:

```
== Documentation

[source,html]
----
include::index.html[tags=html;!svg]
----
```

But I would like a way to replace it with something. Preferable end result:

```
== Documentation

[source,html]
----
<html>
  <h1>My title</h1>
  <svg> ... </svg>
</html>
----
```

**Comment by mojavelinux** [comment]
If you need this kind of feature, you need to write an include extension. We're not going to keep adding functionality onto the include directive in core. It has all the feature it is going to have, at least until the AsciiDoc language specification is complete and starts evolving from there.
