### ISSUE TITLE
Stylesheet: Avoid a second border below the main heading

### ISSUE THREAD

**Issue by Larhzu** [asciidoctor/asciidoctor#4523]
These apply to both v2.0.x and main branches.

If `<div class="details">` is missing when using `:toc: left` or `:toc: right`, an extra border is drawn below the main heading if the viewport is narrow (when the TOC is shown below the heading).

A minimal test case (use a narrow browser window):

```
:toc: left

= Foo

== Bar
```

It seems simple to fix based on `toc` vs. `toc2` class:

```
-#header > h1:first-child + #toc {
+#header > h1:first-child + #toc.toc {
```

I tried to test that it doesn't break any other combinations and didn't find any issues but of course it's possbile that I missed a corner case still.

Unrelated but it's so tiny thing that I mention it here anyway: The following could be added for consistency with `sup.footnote a:active` (and `#toc a:active`).

```
#footnotes .footnote a:first-of-type:active {
  text-decoration: underline;
}
```

Thanks!

**Comment by mojavelinux** [comment]
I agree that does look a bit odd...and it looks like it has been this way since at least the 1.5.x days. I'll see what we can do to clean that up.

> Unrelated but it's so tiny thing that I mention it here anyway: 

Please don't bundle issues.

**Comment by mojavelinux** [comment]
The correct fix is to only draw the bottom border when the sidebar toc appears, which means the rule should be enclosed in the same media query. That way, the extra border won't be there when the toc is collapsed into the main content.

**Comment by Larhzu** [comment]
Your fix is definitely better. Thanks!

> Please don't bundle issues.

I apologize. I won't do it again.

**Comment by mojavelinux** [comment]
No worries. Thanks for noticing and reporting this issue!
