### ISSUE TITLE
Syntax highlighter pygments.rb not working out of the box

### ISSUE THREAD

**Issue by 72757373656c6c** [asciidoctor/asciidoctor#4527]
## Steps
1. I installed asciidoctor via [distribution's package manager ](https://docs.asciidoctor.org/asciidoctor/latest/install/linux-packaging/)(pacman). 
2. adoc contains the attribute :source-highlighter: [pygments](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/pygments/)
3. I executed asciidoctor and got the errors below.

### First run, snippet:

===> asciidoctor -b html5 -D 'html' -o "${outhtml}" "${adoc}"

Output:

asciidoctor: WARNING: optional gem 'pygments.rb' is not available (reason: cannot load 'pygments'). Functionality disabled.

### Second run, script snippet:

declare -x SAFE=0
declare -x RUBYLIB=/usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.20/lib/asciidoctor/syntax_highlighter
asciidoctor -b html5 -D 'html' -o "${outhtml}" "${adoc}"

Output:

uninitialized constant Pygments
  Use --trace to show backtrace

### Steps show pygments.rb is already installed on the system

Download (this is what the distribution downloads too) 
===> wget https://rubygems.org/downloads/asciidoctor-2.0.20.gem

Unpack it
===> gem unpack asciidoctor-2.0.20.gem

Change directory into it
===> cd asciidoctor-2.0.20

Find pygments.rb
===> find -iname 'pygment*'
./lib/asciidoctor/syntax_highlighter/pygments.rb

Find pygments.rb on the system
===> locate pygments.rb
/usr/lib/ruby/gems/3.0.0/gems/asciidoctor-2.0.20/lib/asciidoctor/syntax_highlighter/pygments.rb

The above location also contains coderay.rb, highlightjs.rb, html_pipeline.rb, prettify.rb, and rouge.rb.

Check gem cache
===> gem list|grep -i pygments

===> asciidoctor --version
Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

I've worked with asciidoc (python) for a number of years, but new to asciidoctor (ruby).

**Comment by mojavelinux** [comment]
You need to install the pygments.rb gem in the same location that the asciidoctor gem is installed.

Since this is a question about usage, I'm going to direct you to ask it in the project chat at https://chat.asciidoctor.org as the issue template already tried to do.

**Comment by mojavelinux** [comment]
You shouldn't be copying files around that are installed from a gem. That is just not how you install gems. You should either install the package for the gem (e.g., https://packages.debian.org/bookworm/ruby-pygments.rb) or using `gem install`. Again, if you need help, please ask in the project chat.

**Comment by mojavelinux** [comment]
The message is serving the purpose it is meant to serve. Yes, installing via a package manager is going to be more limited as the package manager does not always provide all the gems. If it does not provide a gem, then that gem is essentially unavailable and you'll have to use an alternate syntax highlighter that is available. As I said, if you need assistance, please ask in the chat. I'm not going to comment further in this thread.
