### ISSUE TITLE
macOS: This manpage is not compatible with mandoc(1) and might display incorrectly

### ISSUE THREAD

**Issue by 0-issue** [asciidoctor/asciidoctor#4528]
macOS's ``/usr/bin/man`` stalls for a second to display an incompatibility message ``This manpage is not compatible with mandoc(1) and might display incorrectly.`` for manpages with tables generated by asciidoctor. What is annoying is not the message itself, but 1 second stall before the page is displayed (it seems to render correctly though). The same issue is not observed with gnu man on macOS (from homebrew), but gnu man has its own difficulties with macOS at times and might not be available at most user's end. Problem doesn't seem inherent in macOS's man, as it does open other man pages with tables without this hiccup.

Note: I have attached xxd output as I am not sure if this is because of some special or control character like [this discussion](https://github.com/orgs/Homebrew/discussions/2506).

file: ``test-man_table.adoc``
```adoc
= testasciidoc(1)

== Name

testasciidoc - a test document

== Description

Hello, World!

[cols="1"]
|===
|Table cell
|===
```

command:
```zsh
$ asciidoctor -b manpage \
  -a doctitle="TEST-TABLE(1)" \
  -a doctype=man \
  -a manname=TESTTABLE \
  -a manpurpose="Test asciidoc manpage table" \
  test-man_table.adoc

$ /usr/bin/man ./TESTTABLE.1
```

result:

<img width="837" alt="test_asciidoc_man_table" src="https://github.com/asciidoctor/asciidoctor/assets/25681815/c74bee96-7c6a-4e22-b2a7-a5d52722c949">

xxd (with mac's ``/usr/bin/man``):

<img width="835" alt="Screenshot 2023-12-27 at 8 49 44 PM" src="https://github.com/asciidoctor/asciidoctor/assets/25681815/79897cd0-7e3f-4637-8f1a-fba1a2f22338">

xxd (with gnu man ``gman``, just for comparison, as ``gman`` does not give any warnings):
<img width="783" alt="Screenshot 2023-12-27 at 10 15 14 PM" src="https://github.com/asciidoctor/asciidoctor/assets/25681815/c2cd4327-7959-41b7-8455-934de0abe7a9">

**Comment by mojavelinux** [comment]
Let's consolidate this into #4529.
