### ISSUE TITLE
Spurious sp in manpage table causes differing spacing on Linux and macOS's man

### ISSUE THREAD

**Issue by 0-issue** [asciidoctor/asciidoctor#4529]
The manpage generator for table adds spurious .sp in table cells. That gets rendered as extra line in gnu man, but is ignored bsd man. Manually deleting the .sp from the cells solves the problem, and rendered without extra line by both gnu man as well as bsd man.

Here's a test file with single cell table:
```adoc
= testasciidoc(1)

== Name

testasciidoc - a test document

== Description

Hello, World!

[cols="1"]
|===
|Table cell
|===
```

command:
```zsh
$ asciidoctor -b manpage \
  -a doctitle="TEST-TABLE(1)" \
  -a doctype=man \
  -a manname=TESTTABLE \
  -a manpurpose="Test asciidoc manpage table" \
  test-man_table.adoc
```

Contents of table in TESTTABLE.1:
```roff
.TS
allbox tab(:);
lt.
T{
.sp
Table cell
T}
.TE
```

Now, manually edit TESTTABLE.1 to remove .sp from cells in tables and save it as TESTTABLE.2.

Contents of table in TESTTABLE.2 (with ``.sp`` stripped from above listing):
```roff
.TS
allbox tab(:);
lt.
T{
Table cell
T}
.TE
```

Here's the result comparing how the two manpages are rendered by GNU man and BSD man. GNU man can be installed on macOS using ``brew install man-db``, though the same problem is seen on ``man`` on a Linux machines (which by default is GNU man).

<img width="798" alt="manpage_table_sp" src="https://github.com/asciidoctor/asciidoctor/assets/25681815/055cfd7e-e6a7-430e-815c-f1c8fd27ca45">

**Comment by mojavelinux** [comment]
In the linked issue, I was going to say that unless you can tell me what mandoc on macOS is not handling properly, I have no way to know how to fix it. But this issue provides some more insight. This definitely looks like a deficiency of the mandoc tool on mac OS, but if the workaround is benign, I'm willing to consider it.

**Comment by mojavelinux** [comment]
In fact, this is a duplicate for #4482. Since this affects the appearance of the output, it's not something that can be fixed in a patch release. It has to wait for the next minor (2.1.0). I'll comment on the related issue, where we can discuss that decision.
