### ISSUE TITLE
Stylesheet: License should be included

### ISSUE THREAD

**Issue by Larhzu** [asciidoctor/asciidoctor#4532]
The default stylesheet, that gets embedded into the HTML output by default, only includes the following line that refers to the license or copyright info:

```
/*! Asciidoctor default stylesheet | MIT License | https://asciidoctor.org */
```

The MIT license requires that the copyright notice and the license itself must be included in all substantial portions of the licensed work. The stylesheet is clearly a substantial portion of Asciidoctor (it's much more than a dozen simple lines of code).

My interpretation is that to legally distribute the HTML-with-the-default-stylesheet output of Asciidoctor one would need to include the copyright and license info manually. This obviously won't usually get done.

Including the copyright notice and the license text in full would make the stylesheet slightly bigger but it seems the most practical option. Including only an URL to the license isn't enough:

1. The document might be read offline.
2. The document must stay redistributable in the future even if the license URL no longer worked for whatever reason.

The copyright notice should include the end year like "2012-2023" instead of "2012-present" as (at least in theory) copyright is meant to expire some day and "present" will become inaccurate when the document gets old.

I understand this can feel annoying and also be somewhat annoying to implement in practice (keeping the notice up to date). So I sympathize but still think this is worth doing.

**Comment by mojavelinux** [comment]
No. This is entirely unnecessary, not worth doing, and disruptive to the output. I'm not going to make this change.

It's a common misconception that a license has to be repeated in its entirety in every source file. The license identifier and URL serves exactly the same purpose and is thus sufficient. (I have consulted legal counsel on this exact topic on numerous occasions and this assertion has always been confirmed). It's also very common to use this shorthand form for citing the license of web assets, so there is established precedent. Doing so also avoids bloating web assets with superfluous headers.

If this presents a problem for you in your particular usage (which I understand), you're free to write a postprocessor extension (or similar) to inject it into the output. See https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/postprocessor/ to find an example.

> The copyright notice should include the end year like "2012-2023" instead of "2012-present" 

This is also a common misconception. Using a specific end year, especially with open source, is a dated practice and overstated. All it does is waste maintainers time to have to constantly keep it up to date every New Years Day. The copyright and license is MIT from now until forever, and that's what this line expressed. I'm not changing it.

**Comment by Larhzu** [comment]
> It's a common misconception that a license has to be repeated in its entirety in every source file.

Maybe it is common but I know it's not true. Having just one copy is indeed fine in the source tree.

> If this presents a problem for you in your particular usage (which I understand), you're free to write a postprocessor extension (or similar) to inject it into the output.

The MIT license is the only thing that gives me and others a legal permission to distribute the stylesheet (or any other file from Asciidoctor), thus I will follow the requirements in the license carefully. Adding the copyright notice and license is indeed a trivial thing for me to do. I merely thought that it would have been convenient default for users in general as well.

I apologize for the noise. Thanks for the great software!
