### ISSUE TITLE
Warn users about the use of Google Fonts

### ISSUE THREAD

**Issue by Timmmm** [asciidoctor/asciidoctor#4540]
The use of Google Fonts in Asciidoctor-generated HTML (that uses the default style and doesn't go out of its way to add a consent form) violates the GDPR - see [here for example](https://www.cookieyes.com/documentation/google-fonts-and-gdpr/).

As stated [here](https://github.com/asciidoctor/asciidoctor/issues/2515#issuecomment-1915402879):

> A majority of users prefer and rely on this feature, so the default will not be changed.

I'll give you the benefit of the doubt for that, but either way it doesn't help users who don't even *know* about the use of Google Fonts. I was certainly very surprised to see that I was *accidentally* violating the GDPR. It was surprising that Asciidoctor by default uses Google Fonts.

I think you should at least warn users about this. It is mentioned [here](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#web-fonts) but that is pretty deep in the docs and not highlighted. I would suggest a note on the command line like

```
NOTE: Using Google Fonts.
```

Or failing that, a warning box on [this page](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/).

Alternatively, you could inline the fonts. WOFF2 fonts are very small (a few 10s of kB). That may be a better solution actually. Would you accept a PR for that?

**Comment by mojavelinux** [comment]
I'd be willing to accept a PR to update the docs to notify users that Google Fonts will be used by default when using the default stylesheet. I'm not open to changing the code at this point.

The claim that Google Fonts is violating GDPR is an issue you need to take up with Google. That is not our concern.

**Comment by Larhzu** [comment]
When one is otherwise happy with the default stylesheet, it's enough to unset the `webfonts` attribute. It is explained on the [next page](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#disable-or-modify-the-web-fonts) in the documentation. Maybe referring to that would be better in the warning than the docs about custom stylesheet. A _commented-out_ link to Google Fonts will still remain but it is only a comment. (Note that I'm only a happy Asciidoctor user, not its developer.)

**Comment by mojavelinux** [comment]
I've proposed alternate wording in the PR. Once we settle on the statement, I'll merge it.

**Comment by mojavelinux** [comment]
This statement has been merged. See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/#backend-and-converter
