### ISSUE TITLE
Substitutions on XREF ID, why? breakage with special chars, escapes don't work (plus/backslash/pass), especially problematic in tables.

### ISSUE THREAD

**Issue by jbthiel** [asciidoctor/asciidoctor#4542]
Seeing with AsciidocFX 1.8.6, in PDF generation (and/or HTML, seems to be different effects, but I'm mainly examining the PDF). 
A series of cascading unexpected effects, difficult to understand if it's one bug, several, or just implicit byproducts of the current design.

Condition is triggered by having special chars < > & in custom section ids, 
for which I am using the supposed most powerful [id=xxx] definition syntax, 
which claims it should be supported.  For example:
```
[id=a->b]
== Section about a to b
```
Now the goal is to reference this section via xref, but it seems to be forcing substitutions on the XREF ID
and it's hard/confusing/broken to stop it.

Trying:
`A reference to section  xref:#a->b[+A->B testing+]`
I get error:
`INFO => possible invalid reference: a&#8594;b`
and in the PDF the link is not working.

After much experimenting and reading, I found the following works,
makes the xref link active in PDF.

```
[subs="macros"]
A reference to section xref:#a->b[+A->B testing+] WORKS
```
As I understand, this works because the subs override throws out all the other substitutions,
but gives macros, which is needed to expand the xref.
Other permutations of that idea also work, for example:

```
[subs="-specialchars,-quotes,-attributes,-replacements,+macros,+post_replacements"]
A reference to section xref:#a->b[+A->B testing+]  WORKS

[subs="-specialchars"]
A reference to section xref:#a->b[+A->B testing+]  WORKS
```
Note that `&#8594; ` in the error above appears to be the RightArrow special symbol,
as done by the "replacements" substitution.
However, `[subs="-replacements"] ` does NOT work, it makes a different error:
`INFO => possible invalid reference: a-&gt;b`

So the first issue is, why is XREF doing any substitution on the XREF ID at all?  
Seems like a faulty design or implementation -- It's not a visible output, so why does it not accept
the ID sequence exactly, like you can assign arbitrary IDs via [#xxx] or [id=xxx]?
At least it should accept any chars you can validly use there.
What's the usecase/rationale for doing substitutions on the XREF ID ?

Then, given it does the substitution, how to turn it off?
I found most of the usual escape mechanisms don't work.

For example, single double triple plus, all FAIL, produce non-working link in PDF:
```
reference to section xref:#+a->b+[+A->B testing+]
reference to section xref:#++a->b++[+A->B testing+]
reference to section xref:#+++a->b+++[+A->B testing+]
```

Backslash FAIL:
`  backslash reference to section xref:#a-\>b[+A->B testing+]`
produces error
`INFO => possible invalid reference: a-\&gt;b`
and non-working link in PDF
 
And further curiously the pass:[] macro is also useless, even when 
apparently replicating the (macros on, everything else off) logic that worked for [subs] above.
FAIL
```
pass m reference to section pass:m[xref:#a->b[+A->B testing+]]
pass qarmp reference to section pass:q,a,r,m,p[xref:#a->b[+A->B testing+]]
```
Neither of these even make a link in the PDF, they just pass thru the literal xref text inside the inner brackets.
ie. the "m" setting does not enable the xref macro to be evaluated, why not, a bug?

Finally, with the objective of producing a XREF link inside a table to a section ID with special chars,
the complexity is even further magnified.
Since the only way that worked above is giving the block
`[subs="macros"]  or [subs="-specialchars"]`
attributes, it seems the table cell must have "a" style, with an embedded [subs] block.
It does *not* inherit a [subs] setting from the whole table.

(should it inherit? is that another bug? is there a way to set that default for all table cells?)

This greatly complicates using XREF inside a table cell if you have many section IDs that have
specialchars.  (or simply could have specialchars, if trying to design a transparent overall naming/usage convention).

It seems the current best/only approach is either
A) ensure no special chars in the custom ID, or
B) Use the `[subs="-specialchars"]` block attribute universally on such xrefs (with "macros" on too).

Both of these are troublesome and heavy workarounds, especially in quantity, automated or standardized processes, etc.
Documenting programming languages for example may commonly use < > chars.

ASIDE: In general the whole substitution, escape, passthru system is too complex
and easily becomes a trial-and-error user experience.
Maybe some of the six (!) substitutions and myriad escapes are rare enough to be dropped or folded into others.

THANKS for your and everyone's work on Asciidoc and related tools -- a very useful and excellent writing platform.

-- jbthiel

See Also: I found this related issue:
  #1678  Cannot escape anchor id in xref macro
which covers some different cases.

**Comment by mojavelinux** [comment]
IDs should not contain special characters, especially HTML special characters. This is stated in the docs here: https://docs.asciidoctor.org/asciidoc/latest/attributes/id/#valid-id-characters As that page warns, if you don't adhere to this rule, you're likely going to encounter problems in the converted document.

Since this is a question about usage, I prefer that it be asked in the project chat. There's no clear code change needed here as Asciidoctor is operating within the bounds of how it is designed. As the [Get Help](https://docs.asciidoctor.org/about/get-help/) page states, issues should only be used for verified bugs or formalized feature requests. For all other concerns, you should be asking in the chat.

> In general the whole substitution, escape, passthru system is too complex and easily becomes a trial-and-error user experience.

I'm sorry you feel that way, but that is how AsciiDoc is designed. While we are revisiting this design in the AsciiDoc Language project, that effort is still a work in progress.
