### ISSUE TITLE
Attribute `window=_blank` is not honored for `image:` on Github

### ISSUE THREAD

**Issue by lwbt** [asciidoctor/asciidoctor#4543]
I wanted to embed an asciinema screen cast in one of my repositories. After experimenting with the [video element](https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/) and looking at https://github.com/asciidoctor/asciidoctor/issues/1798 I understood that it may not be that easy. So I decided to use an image with a link.

- https://docs.asciidoctor.org/asciidoc/latest/macros/images/
- https://docs.asciidoctor.org/asciidoc/latest/macros/image-link/

The code seems to be properly formatted, but the link opens in the same tab, not a new tab, as I wanted. My repo/adoc file is hosted on Github as a README.adoc.

Example:

```
image:https://asciinema.org/a/569727.svg["asciinema.org",link=https://asciinema.org/a/569727,window=\_blank,opts=nofollow]
```

Alternatives I may consider:

- Using `++++` blocks `++++` use HTML embed code (this has not worked on first attempt either)
- Using `++++` blocks `++++` to include an iframe
- Download a GIF from asciinema.org, add it to the repo itself, use it as an image my document

**Comment by mojavelinux** [comment]
The behavior you are describing is a side effect of GitHub's HTML sanitizer. There is nothing we can do about that. Asciidoctor produces the correct HTML, but the GitHub application modifies it. One of the things it does (apparently) is remove the window attribute from the `<a>` tag. You'll need to contact GitHub support if you want them to consider changing the behavior.
