### ISSUE TITLE
Docs: Clarify use of [bibliography] on section with level > 1

### ISSUE THREAD

**Issue by nvitucci** [asciidoctor/asciidoctor#4547]
In the current description of the [blbliography section](https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/) it is not very clear whether the `[bibliography]` style can be used with a section at any level above 1. For example, is there anything wrong in using it for a `=== References` section only within an `== Introduction` section?

I have done this myself and it works, but I think the docs could clarify if it _should_, or if it's a bad practice.

**Comment by mojavelinux** [comment]
The bibliography section can be used at any level. In the HTML output, all the style is doing is adding the bibliography style to lists in that section. In the DocBook output, it turns the section tag into a bibliography tag. See https://tdg.docbook.org/tdg/slides/5.1/bibliography

I've updated the AsciiDoc Language user guide to make this clearer. Note that this is not an Asciidoctor issue, but rather it pertains to the language itself.

**Comment by nvitucci** [comment]
Excellent, thank you very much for the quick reaction and improvement.

For future reference, what's the best place to raise AsciiDoc (language) issues then?

**Comment by mojavelinux** [comment]
You're most welcome. Thanks for pointing out the need for a clarification.

You can find the repository that goes with a page by clicking on "Edit this Page". In this case, it directs you to https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang
