### ISSUE TITLE
Em dash( -- ), ellipsis(...), copyright(C), and other special characters are rendering as ??? in HTML when converted using Asciidoctor in Ubuntu

### ISSUE THREAD

**Issue by Jsivakot** [asciidoctor/asciidoctor#4555]
Hi Team, 
Text replacements mentioned in [https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements) are not working when we are trying to convert Asciidoc file to HTML by running asciidoctor command in Ubuntu whereas **it is working fine in Windows and Mac**.

**OS where issue observed** - Ubuntu 20.04 and 22.04

**Asciidoctor version (Windows and Ubuntu)** - 2.0.21

**Command** - asciidoctor -D <<output folder path>> <<input Asciidoc path>>

**Issue** - -- rendering as ???, 's rendering as ?s, ... rendering as ?? and rest all other text are rendering as ? in HTML 

Please provide guidance to resolve this issue as it has huge business impact.

**Comment by mojavelinux** [comment]
In the future, please ask questions about usage in the project chat. The issue tracker is for tracking verified bugs. Once we've ruled out its a user, system, or installation error, then we will proceed with an issue.
