### ISSUE TITLE
Support right-to-left languages

### ISSUE THREAD

**Issue by HamidrezaSafari** [asciidoctor/asciidoctor#4557]
Not all disscussions on github are in English and some like Persian, Hebrew or Arabic are written from right to left.
It would be easy to add a checkmark to the editor to switch the direction from LTR to RTL and then represent that piece of text in UI from right to left.

The text is barely readable if it's mixed with an English word (which happens quite a lot in a technical disscussion) and all it needs is a div wrapper with dir='rtl' align='right' or if you want to do it with CSS direction: rtl; text-align: right.

**Comment by ggrossetie** [comment]
I don't see how this is related to Asciidoctor. If you want to share feedback with GitHub: https://docs.github.com/en/support/sharing-feedback-with-github
