### ISSUE TITLE
Customise a block according to its type

### ISSUE THREAD

**Issue by gemkod** [asciidoctor/asciidoctor#4560]
Hello,

Wouldn't it be possible to use a block by specifying the type name and formatting some basic properties (outline, background colour, etc.)?

Here's an example of what I'm trying to do :

![image](https://github.com/asciidoctor/asciidoctor-pdf/assets/102660758/e3351226-3e99-4c1a-8a30-072f66423100)

I use anonymous blocks so that I can easily change the name of the block if something changes.

I have read topics [#483](https://github.com/asciidoctor/asciidoctor-pdf/issues/483) and [#1486](https://github.com/asciidoctor/asciidoctor-pdf/issues/1486) as well as https://docs.asciidoctor.org/pdf-converter/latest/extend/use-cases/#theme-admonition-per-type.

I think I've understood that it's possible via an extension to add other admonition blocks but nothing related to what I want to do.

Perhaps I'm on the wrong way or misusing Asciidoc / Asciidoctor-pdf.

Thank you very much for your feedback. Asciidoc is so wonderful!

**Comment by mojavelinux** [comment]
I've already asked you to use the project chat for questions about usage and customization. Please honor that request.
