### ISSUE TITLE
CSS style for preamble look for an exact class, when they could use a class selector

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor#4564]
The current CSS selector in the default stylesheet to format the preamble has the following code: 

```
#preamble > .sectionbody > [class=paragraph]:first-of-type p
```

When rendering a preview which includes source lines encoded in the class of the html (a common practice for HTML preview for example in the IntelliJ plugin for AsciiDoc) this doesn't render a contents that append additional information to the class. 

```
<div class="paragraph has-source-line data-line-stdin-3">
<p>This is the preamble.</p>
</div>
```

A CSS selector like the following would match the preamble independent of the additional classes.

```
#preamble > .sectionbody > .paragraph:first-of-type p
```

I'll prepare a PR for this.

**Comment by ahus1** [comment]
Thank you for the fast reply. Know I know that I need to find another way for the AsciiDoc plugin.

**Comment by mojavelinux** [comment]
This is something that I think could (and should) be addressed in the next gen HTML converter. We do it the way we do it here to retain backwards compatibility, but the next gen HTML converter is green fields.
