### ISSUE TITLE
Allow all includes to be optional to prevent error messages appearing in output

### ISSUE THREAD

**Issue by cpkio** [asciidoctor/asciidoctor#4567]
It would be useful to have an attribute or a command line parameter to make all includes optional. Documentation readers should not see error messages in most cases. Documentation developers should see log errors and error texts in `stage` builds.

**Comment by mojavelinux** [comment]
This is not a feature I want to implement or encourage. The include directive is meant to be processed and a missing include is an error by nature of being a resource reference. If you want to make an include optional, then it should be required to specify the optional option.

If you don't agree with that design, you can exercise your choice to implement an include processor extension, which allows you to take over the request to resolve an include. You can then choose any logic you want to implement.

**Comment by mojavelinux** [comment]
See https://docs.asciidoctor.org/asciidoctor/latest/extensions/include-processor/ as well as https://github.com/asciidoctor/asciidoctor-extensions-lab to find examples of a custom include processor. You are welcome to ask questions in the project chat at https://chat.asciidoctor.org if you need help.
