### ISSUE TITLE
Fix error message from include directive on first line of AsciiDoc table cell

### ISSUE THREAD

**Issue by mblythe86** [asciidoctor/asciidoctor#4571]
## Example asciidoc file:

```
== Testing an include within a table

include::does_not_exist.adoc[]

|===
| *A* | *B*

| some text
a| include::does_not_exist.adoc[]
|===
```

## Expectation

Expected output (simplified HTML):

> <h2>Testing an include within a table</h2>
> <p>Unresolved directive in table_include.adoc - include::does_not_exist.adoc[]</p>
> <table class="tableblock frame-all grid-all stretch">
> <thead>
> <tr>
> <th><strong>A</strong></th>
> <th><strong>B</strong></th>
> </tr>
> </thead>
> <tbody>
> <tr>
> <td><p>some text</p></td>
> <td><p>Unresolved directive in table_include.adoc - include::does_not_exist.adoc[]</p></td>
> </tr>
> </tbody>
> </table>

Expected errors:

```
asciidoctor: ERROR: table_include.adoc: line 3: include file not found: /path/to/does_not_exist.adoc
asciidoctor: ERROR: table_include.adoc: line 8: include file not found: /path/to/does_not_exist.adoc
```

## Reality

Actual output (simplified HTML):

> <h2>Testing an include within a table</h2>
> <p>Unresolved directive in table_include.adoc - include::does_not_exist.adoc[]</p>
> <table class="tableblock frame-all grid-all stretch">
> <thead>
> <tr>
> <th><strong>A</strong></th>
> <th><strong>B</strong></th>
> </tr>
> </thead>
> <tbody>
> <tr>
> <td><p>some text</p></td>
> <td><p>Unresolved directive in &lt;stdin&gt; - include::does_not_exist.adoc[]</p></td>
> </tr>
> </tbody>
> </table>

Actual errors:

```
asciidoctor: ERROR: table_include.adoc: line 3: include file not found: /path/to/does_not_exist.adoc
asciidoctor: ERROR: <stdin>: line 1: include file not found: /path/to/does_not_exist.adoc
```

## Details

This poor error message makes it more difficult to identify the location of the error.  Fixing this would enable users to more quickly identify and fix problems in their asciidoc files.

Tested using asciidoctor v2.0.16, but I am confident that the issue persists in v2.0.22 because I've root caused the problem to [this line of code](https://github.com/asciidoctor/asciidoctor/blob/v2.0.22/lib/asciidoctor/table.rb#L303).  The `PreprocessorReader` constructor accepts an optional 3rd parameter, `cursor`, that provides the details of what file is being parsed and the location within that file, and that is not being provided here.

Shortly, I'll submit a simple pull request to fix this issue.

**Comment by mojavelinux** [comment]
The reason is a bit more complicated than this. An AsciiDoc table cell is permitted to start directly after a cell separator rather than on the next line. In this situation, an artificial line is created that has no cursor information. As a result, if there's a warning or error that occurs on that line, then it is missing cursor information. Had the include directive been moved to the next line, the line information would have been correct. I need to see if I can create a synthetic cursor for this first line so that any error or warning that occurs on that first line is reported properly.

**Comment by mojavelinux** [comment]
The proposed fixed just happens to work.

**Comment by mojavelinux** [comment]
Btw, we always recommend starting the contents of an AsciiDoc table cell on the following line. It's a convenience that it is allowed to start on the same line as the cell separator, but not recommended.
