### ISSUE TITLE
Missing last row when have even columns and odd rows in table

### ISSUE THREAD

**Issue by YanWenKun** [asciidoctor/asciidoctor#4573]
With table code:

```
[cols=2]
|===
|1
|2
|3
|4
|5
|===
```

Would expect:

| 1 | 2 |
|--|--|
| 3 | 4 |
| 5 ||

But  outputs:

| 1 | 2 |
|--|--|
| 3 | 4 |

This happens on GitHub README and VSCode with AsciiDoc extension.

Thanks in advance!

**Comment by mojavelinux** [comment]
This behavior is correct. The table has an extra cell and since it does not form a complete row, it cannot be accepted.

Asciidoctor should output a warning in this case. I'll figure out where that needs to go and add it.

**Comment by mojavelinux** [comment]
This issue was dependent on #4587, which is now resolved.
