### ISSUE TITLE
Question: Can I use the Liquid template engine with converter templates

### ISSUE THREAD

**Issue by jmooring** [asciidoctor/asciidoctor#4574]
If yes, does anyone have an example, perhaps the equivalent of something like this (`inline_anchor.html.erb`) for example?

```text
<% title = attr "title" %>
<a class="inline-anchor-erb" href="<%= target %>" <% if title != nil %>title="<%= title %>"<% end %>><%= text %></a>
```

I raise the question because I'm looking for template engines that prevent stuff like this:

```text
<% File.delete("/home/rsmith/my-file.txt") %>
```

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat as both the issue template and the Get Help page in the docs asked you to do. See https://docs.asciidoctor.org/about/get-help/#chat
