### ISSUE TITLE
mailto macro should encode spaces in the URI as %20 instead of +

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4576]
According to https://www.rfc-editor.org/rfc/rfc6068#section-5, spaces in the mailto URL should be encoded as %20 instead of +. While some email clients can handle both, others only recognize %20.

**Comment by mojavelinux** [comment]
We have been using CGI.escape, which follows the CGI/HTML forms spec and gives you an application/x-www-form-urlencoded string. What we need to follow is RFC 3986, which requires spaces to be encoded as %20.

**Comment by mojavelinux** [comment]
"When producing 'mailto' URIs, all spaces SHOULD be encoded as %20, and '+' characters MAY be encoded as %2B."

**Comment by mojavelinux** [comment]
This is matter of using the new CGI.escapeURIComponent method in Ruby 3.1 and using CGI.escape with a gsub patch for `+` in Ruby < 3.1.

**Comment by djl101** [comment]
Thank you for resolving this issue!
