### ISSUE TITLE
"no callout found for" when using subs="attributes" in source

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor#4577]
AsciiDoctor issues a warning when using a callout in a source section with `subs="attributes"`, e.g., in https://github.com/aim42/htmlSanityCheck/blob/97728ab7c36e3fbe61dd5fc4b11cc078583bccf5/README.adoc?plain=1#L40C1-L48C1

`asciidoctor: WARNING: README.adoc: line 47: no callout found for <1>`

The asciidoctor/asciidoctor-intellij-plugin#522 issue seems to be related.

**Comment by mojavelinux** [comment]
It's because you have not used incremental subs. Please refer to the docs. In the future, please direct questions to the project chat.
