### ISSUE TITLE
[Feature request] Tabs container

### ISSUE THREAD

**Issue by sdasda7777** [asciidoctor/asciidoctor#4579]
Hi, I was trying to write a bit of documentation today, and I noticed that it doesn't seem like Asciidoc provides any simple way to create tabs/tabs container. More specifically, I think it would be really neat if you could create tabs that would contain code blocks for given OS or programming language or such. For example see this screenshot from [Godot documentation](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/03.coding_the_player.html):

Fig. 1:
![image](https://github.com/asciidoctor/asciidoctor/assets/17746796/ec9a6ec7-c974-4f1d-b4ec-b889589b63ad)

Fig. 2:
![image](https://github.com/asciidoctor/asciidoctor/assets/17746796/40c3d6e4-eb78-4336-9025-2653a01580b8)

In contrast, see [Asciidoctor's Readme page](https://github.com/asciidoctor/asciidoctor) featuring endless lists of commands, where any single user is not likely to use more than one of:
![image](https://github.com/asciidoctor/asciidoctor/assets/17746796/e94a4f0b-d613-4385-a4c7-a410218341e7)

**Comment by ioannisstavrakakis** [comment]
I believe you should check out the https://github.com/asciidoctor/asciidoctor-tabs.

**Comment by sdasda7777** [comment]
> I believe you should check out the https://github.com/asciidoctor/asciidoctor-tabs.

Thanks, I admit I managed to find this repo. I may be wrong on this, but I don't assume there is a simple way to use the extensions on GitHub/GitLab/similar sites, right?

**Comment by ioannisstavrakakis** [comment]
I am not sure that I follow you. What is your exact use case?
This extension can build tabs in exported HTML files; the GitLab adoc preview does not show these tabs, but it does work in the VSC preview, as well as when previewed in a browser as HTML.

**Comment by sdasda7777** [comment]
> This extension can build tabs in exported HTML files; the GitLab adoc preview does not show these tabs, but it does work in the VSC preview, as well as when previewed in a browser as HTML.

Yeah, that's pretty much what I thought.

> What is your exact use case?

My use case is readmes, plain and simple. The [Asciidoctor's readme](https://github.com/asciidoctor/asciidoctor) as stated above is a good benchmark imo.

**Comment by mojavelinux** [comment]
https://asciidoc.org

> Further, do you have any recommendation what to do in the meantime?

I've provided the information I'm willing to provide here. If you have more question, you can ask in the chat.

**Comment by sdasda7777** [comment]
> I've provided the information I'm willing to provide here. If you have more question, you can ask in the chat.

I really don't know how I should read that. I don't see any advantage to asking you in private compared to asking you here, where other people looking for a solution might actually see it. The link provided doesn't answer either of my questions, either 👍

**Comment by mojavelinux** [comment]
> I don't see any advantage to asking you in private compared to asking you here

The chat is not private. Rather, it is the public forum for the Asciidoctor ecosystem. You can learn about it on the following page: https://docs.asciidoctor.org/about/get-help/#chat

> The link provided doesn't exactly answer either of my questions

The link to the AsciiDoc Language project is on that page.

I'm now locking this issue as I have requested for this conversation to happen elsewhere multiple times now.
