### ISSUE TITLE
Any empty line in an non-matching ifdef causes line break

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor#4580]
Assuming `bar` is not defined, the following source
```
Foo.
ifdef::bar[]
endif::[]
Bar.
```
renders as:
```
Foo. Bar.
```
However, if the ifdef contains an empty line like this:
```
Foo.
ifdef::bar[]

endif::[]
Bar.
```
this renders as:
```
Foo.
Bar.
```

I think that empty lines within a non-matching ifdef shouldn't survive the preprocessing.

**Comment by mojavelinux** [comment]
Wow, that is really bizarre. If the blank line is replaced with text, then it doesn't happen. I'm not sure what's going on there or how that behavior slipped through.

As a workaround, you can add an attribute reference to the `empty` attribute on that empty line.

```
Foo.
ifdef::bar[]
{empty}
endif::[]
Bar.
```

**Comment by mojavelinux** [comment]
To be clear, what is happening is that it is separating the two paragraphs. It's not rendering as:

```
Foo.
Bar.
```

It's rendering as:

```
<div class="paragraph">
<p>Foo.</p>
</div>
<div class="paragraph">
<p>Bar.</p>
</div>
```

**Comment by mojavelinux** [comment]
I've got it. I put in an optimization and I overlooked a case which then wasn't covered by a test. All of that is solvable.

**Comment by odrotbohm** [comment]
Thanks for the quick turnaround, Dan!

**Comment by mojavelinux** [comment]
You bet! Thanks for reporting!
