### ISSUE TITLE
Feat: [Code Block] Tabs for Different Coding Languages

### ISSUE THREAD

**Issue by dylanh724** [asciidoctor/asciidoctor#4581]
## Feat Request

Many docs will support multiple coding languages that follow the same tutorials with slightly different syntax. Many docs, much like yours, uses CLI to setup that may vary between Bash|PowerShell|etc (which would even be useful on your installation docs).

This is quite common, and while there's probably an extension for this, I feel this would be pretty essential within Antora, itself for modern technical doc writing.

[Hathora docs](https://hathora.dev/docs/guides/deploy-hathora) has an example-use case that doesn't necessarily require tabs to be specifically for *code*, but anything, where it can mix and match code:

![image](https://github.com/asciidoctor/asciidoctor/assets/8840024/9bed89a5-c3f1-478b-9ac2-002a5b49c972)

That said: Tabs for code blocks, **and/or** mix n match tabs for any type of block

**Comment by mojavelinux** [comment]
Tabs are provided by the [asciidoctor-tabs](https://github.com/asciidoctor/asciidoctor-tabs) project, which is a syntax extension for AsciiDoc developed by the Asciidoctor project. See https://github.com/asciidoctor/asciidoctor-tabs

The tabs component is being considered for inclusion in the AsciiDoc Language by the AsciiDoc Language project based on the implementation in Asciidoctor Tabs. However, that won't happen until the first version of the AsciiDoc Language specification is completed, at a minimum.

In the future, please direct requests such as this one to the project chat at https://chat.asciidoctor.org.

**Comment by dylanh724** [comment]
> Tabs are provided by the [asciidoctor-tabs](https://github.com/asciidoctor/asciidoctor-tabs) project, which is a syntax extension for AsciiDoc developed by the Asciidoctor project. See https://github.com/asciidoctor/asciidoctor-tabs
> 
> The tabs component is being considered for inclusion in the AsciiDoc Language by the AsciiDoc Language project based on the implementation in Asciidoctor Tabs. However, that won't happen until the first version of the AsciiDoc Language specification is completed, at a minimum.
> 
> In the future, please direct requests such as this one to the project chat at https://chat.asciidoctor.org.

Heads up, I almost went to the chat site, but it explicitly mentioned _questions_ (rather than feedback submissions), in case you wanted to update your new issue comment
