### ISSUE TITLE
Asciidoc is not rendering in arm linux machine

### ISSUE THREAD

**Issue by ananta-code** [asciidoctor/asciidoctor#4584]
I have mac m1/m2 laptop and one ubuntu VM is running .intelliJ idea for arm version IntelliJ IDEA 2024.1 (Ultimate Edition).
after installing the Asciidoc plugin version 0.41.14 i am expecting the asciidoc document should be rendered but it is blank nothing is coming.

Could someone suggest if it is a known issue or is there any WA?

**Comment by mojavelinux** [comment]
This is not the correct repository for this issue. It should be filed in the issue tracker for the IntelliJ plugin instead.
