### ISSUE TITLE
Table header styling for fo-pdf

### ISSUE THREAD

**Issue by snaggen** [asciidoctor/asciidoctor#4593]
Table header styling and striping is supported in HTML output, but no support exists in fo-pdf

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org. (This question also seems to pertain to fopub rather than Asciidoctor core, so I don't even think it's relevant for this repository anyway).

**Comment by mojavelinux** [comment]
Sorry, my mistake. I didn't realize this was the issue for an open pull request. Disregard my comment. Though I do need to update the table to make it more clear what the issue is for.
