### ISSUE TITLE
Add option `-E` to output processed AsciiDoc without convernion

### ISSUE THREAD

**Issue by DaveMcEwan** [asciidoctor/asciidoctor#4598]
Request for new feature.
Other tools like, e.g. GCC, have the option `-E` which applies the preprocessor and outputs the resulting C where all preprocessor directives (`#include`, `#define`, etc.) have been resolved.
This is useful for developers to see exactly what C the core compiler is working with, especially because the output of `-E` can be stored in a file and used later. I mean, you can cleanly separate the preprocessing steps from the core compiler steps.

It would be useful for Asciidoctor to have a similar option that processes all include and conditional directives with the usual normalization (exactly as described in the [documentation](https://docs.asciidoctor.org/asciidoc/latest/directives/include/#include-nonasciidoc)) and prints the output to STDOUT.

The same option `-E` would be intuitive, and maybe `--preprocess-only` as the long form.

Usecase 1
---------
I have a collection of adoc files for building modular documentation, c.f. Kurt Ament's book Single Sourcing, and I want to publish a README on GitHub. However, GitHub rendering doesn't do `include` (SAFE mode), so I can't currently publish a `<repo-root>/README.adoc` that's built from documentation modules (I mean `include`'ing several sections from other files).
If Asciidoctor had a preprocess-only feature, I could locally run something like this:
```
cd <repo-root>
asciidoctor -E doc/GitHub-README.adoc > .github/README.adoc
# Commit, push ...
```
Now, viewing `doc/GitHub-README.adoc` is rendered with each `include` converted to a link, but the repo's front page (and `.github/README.adoc`) is rendered as one document.

Usecase 2
---------
I have to work with a very complex codebase and workflow, so it's difficult to understand how each conditional resolves. It may also be difficult to discern whether a file has been `include`'ed multiple times. All pieces of the content is already reviewed, but it's difficult to review that the infrastructure is joining them all together properly. Of course, I shouldn't have such a complex workflow, but this is reality and I need to work on a codebase created by somebody else.
If Asciidoctor had a preprocess-only feature, I could inspect and validate the output using all the usual ways we review content.

Usecase 3
---------
I'm working in an environment where I have access to recent versions of Asciidoctor, but I cannot install [`asciidoctor-reducer`](https://github.com/asciidoctor/asciidoctor-reducer).
It looks like the purpose of asciidoctor-reducer is very similar, maybe exactly the same, so this feature request is essentially to implement it directly in Asciidoctor .

**Comment by mojavelinux** [comment]
This is the purpose of Asciidoctor Reducer. We will not be adding this functionality into core as it is will make it more difficult to maintain.

If you need help installing or using Asciidoctor Reducer, you can ask in the project chat at https://chat.asciidoctor.org.

**Comment by DaveMcEwan** [comment]
For anybody else who finds this:
- Explanation of why this is difficult to implement/maintain is in the [Asciidoctor Reducer README](https://github.com/asciidoctor/asciidoctor-reducer/blob/main/README.adoc#how-it-works).
- If your environment has strict IT policies, perhaps you can argue that Asciidoctor shouldn't be installed normally and you should use it via the [official Docker image](https://github.com/asciidoctor/docker-asciidoctor/blob/main/README.adoc#the-environment) instead, which includes Asciidoctor Reducer.
