### ISSUE TITLE
Option for roman numerals in TOC and page numbers

### ISSUE THREAD

**Issue by KlaBra16F1** [asciidoctor/asciidoctor#4601]
Hi there! I spent some time searching for a way to get roman numerals for my appendix into my TOC and the pagenumbers (through running content footers in my theme file).

Rather by accident I  found out, that I can have roman pagenumbers, when I'm using a preambel and set `toc: preambel`, so it seems that ascidoctor-pdf is capable of different numbering styles. So I think there must  be a way to make use of that with other section types somehow. 

If there are no plans to make this a feature, it would be awesome if someone could give me a hint how to solve this issue in the converter file. Right now I have to export as docbook, convert to docx with pandoc and do a lot of reformating in M$ Word for an otherwise perfect pdf.

Thanks for reading and for your awesome work with asciidoctor and asciidoctor-pdf!

**Comment by mojavelinux** [comment]
The correct place to ask questions about how to use the software is the project chat at https://chat.asciidoctor.org. Furthermore, this question pertains to Asciidoctor PDF, not Asciidoctor, so this is not the correct repository anyway. If you ask your question in the chat, someone will likely follow-up to help steer you towards a solution.
