### ISSUE TITLE
Table display issue in VSCode extension preview

### ISSUE THREAD

**Issue by welch-s** [asciidoctor/asciidoctor#4606]
- Preview in VSCode extension
![image](https://github.com/asciidoctor/asciidoctor/assets/4651390/9eb90dd1-874f-408e-9abb-320c16c49840)

- Preview in Edge browser
![image](https://github.com/asciidoctor/asciidoctor/assets/4651390/c6146e5d-02b6-4e2f-a0e7-de2a58e6f4e7)

AsciiDoc input:

```
.test
|===
16+|・testtest
.5+|1 2.5+|1 2.3+|2 10+|4 .5+|-
9+|6 |7
4+|8 .3+|9 4+|10 .3+|11
.2+|12 .2+|13 .2+|14 .2+|15 .2+|16 .2+|17 2+|18 .2+|19 .2+|20
|21 |22
.2+|a |0 |b |× |× |- |- |- |- |- |- |- |- |- |01 | 
|1 |c |× |○ |11 |12 |13 |10 |- |20 |30 |- |- |- | 
.4+|d |10 |e |× |○ |11 |12 |13 |10 |01 |01 |01 |01 |01 | | 
|11 |f |● |○ |- |12 |13 |10 |01 |01 |01 |01 |01 |- | 
|12 |g |◎ |○ |11 |- |13 |10 |01 |01 |01 |01 |02 |- | 
|13 |h |☆ |○ |11 |12 |- |10 |01 |01 |01 |01 |02 |- | 
.2+|i |20 |j |★ |○ |11 |12 |13 |10 |- |- |30 |01 |- |- | 
|30 |k |△ |○ |11 |12 |13 |10 |- |20 |- |02 |- |- | 
```

**Comment by mojavelinux** [comment]
This is not the correct repository for reporting issues regarding the VSCode extension.

If you need help, you can ask in the project chat at https://chat.asciidoctor.org.
