### ISSUE TITLE
Is there a way to disable role attributes?

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor#4609]
While working on reformatting the git manpages, we stumbled upon an issue with role attributes being triggered in the synopsis of the commands.

Initially we had something like this:

```
[verse]
'git clone' [--template=<template-directory>]
	    [-l] [-s] [--no-hardlinks] [-q] [-n] [--bare] [--mirror]
	    [-o <name>] [-b <name>] [-u <upload-pack>] [--reference <repository>]
	    [--dissociate] [--separate-git-dir <git-dir>]
	    [--depth <depth>] [--[no-]single-branch] [--no-tags]
	    [--recurse-submodules[=<pathspec>]] [--[no-]shallow-submodules]
	    [--[no-]remote-submodules] [--jobs <n>] [--sparse] [--[no-]reject-shallow]
	    [--filter=<filter-spec>] [--also-filter-submodules]] [--] <repository>
	    [<directory>]
```
After reformatting (typesetting keywords in backquotes and placeholders in italic):

```
[verse]
`git clone` [++--template=++__<template-directory>__]
	  [`-l`] [`-s`] [`--no-hardlinks`] [`-q`] [`-n`] [`--bare`] [`--mirror`]
	  [`-o` _<name>_] [`-b` _<name>_] [`-u` _<upload-pack>_] [`--reference` _<repository>_]
	  [`--dissociate`] [`--separate-git-dir` _<git-dir>_]
	  [`--depth` _<depth>_] [`--`[`no-`]`single-branch`] [`--no-tags`]
	  [`--recurse-submodules`[++=++__<pathspec>__]] [`--`[`no-`]`shallow-submodules`]
	  [`--`[`no-`]`remote-submodules`] [`--jobs` _<n>_] [`--sparse`] [`--`[`no-`]`reject-shallow`]
	  [++--filter=++__<filter-spec>__] [`--also-filter-submodules`]] [`--`] _<repository>_
	  [__<directory>__]
```

The problem is that the sequences ```[`--`[`no-`]`shallow-submodules`]``` are interpreted by asciidoctor as a role ``` `--`[`no-`]` ``` applied to the formatted ``` `shallow-submodules` ```. The same sequence is correctly (as intended) interpreted by asciidoc.py, which makes discrepancies between the compiled manpages for distributions and the ones for git-for-windows or for git-scm.com.

For the moment, the hack I found was to insert `{empty}` variables to prevent the roles, e.g. ```[`--`[`no-`]{empty}`shallow-submodules`]```. But this makes the source cumbersome to write and check, but also obscures the source documents when reviewing.

We do not use roles, and do not intend to, because our writers are developpers who just want simple features and praise the "works as intended, not as specified" way for the documentation. The simplest for us would be to just disable roles.

Is it possible to do it inside asciidoctor.rb? I tried to tinker with a Preprocessor, without success so far. The includes are lost when rewriting the document on the fly.

BTW, why are the `<code>` tags considered as blocks by asciidoctor?

Thanks in advance

**Comment by mojavelinux** [comment]
Please ask questions about usage in the project chat (https://chat.asciidotor.org) as the issue template requested. The issue tracker is not a support portal. You are welcome to discuss anything in the project chat.
