### ISSUE TITLE
Need {docdir} but for the currently processed include, not the starting-document.

### ISSUE THREAD

**Issue by SeidChr** [asciidoctor/asciidoctor#4614]
I want to have a variable which returns the path of the currently processed document, and NOT the document which initiated the process. 
So when I process `<root>/docs/test.adoc` which includes `<root>/includes/include.adoc` I need a variable I can use inside of `<root>/includes/include.adoc` to determine the path `<root>/includes`

When I watch the `<root>/docs/test.adoc` document, the `{docdir}` will be set to `<root>/docs`, which is not helping at all when its required to reference something relative to the `<root>/includes` directory.

The actual usecase is to specify a common imagesdir within an include, as it is not possible to pass the imagesdir to asciidoctorjs when using the preview in vscode. But asciidoctorjs is actually loading includes, which then have a variable `root`

The current solution for this is, to specify the imagesdir in EVERY document, which I want to avoid.

**Comment by mojavelinux** [comment]
This is the same request as #2608. See https://github.com/asciidoctor/asciidoctor/issues/2608#issuecomment-433745988 for an explanation why this cannot be implemented in Asciidoctor currently and a link to a extension that fills this need.

We are working to make this information part of the parse tree in the AsciiDoc Language specification, but it requires some necessary changes to how includes are handled.
