### ISSUE TITLE
Custom attribute gets path wrong

### ISSUE THREAD

**Issue by Baerbeisser** [asciidoctor/asciidoctor#4615]
Asciidoctor 2.0.23

# Project structure
```
Project
├── index.adoc
├── deps
│   └── table.tsv
├── media
│   └── picture.jpg
└── pages
    └── page1.adoc
```

# Situation
index.adoc has
```
:pagesdir: ./pages
:imagesdir: ./media
:depsdir: ./deps
include::{pagesdir}/page1.adoc[]
```
page1.adoc has
```
image::picture.jpg[]

[%header,format=tsv]
!===
include::{depsdir}/table.tsv[]
!===
```

# Problem
image gets included, while {depsdir} gets resolved from `page1.adoc` instead of `index.adoc`, complains about `.../Project/pages/deps/table.tsv` not found.

*In summary:*
* `{pagesdir}` gets rsolved, `page1.adoc` included
* image gets included from `{imagesdir}`
* `{depsdir}` stitches path to `<path of included .adoc>/<depsdir-target>` together

# Desired outcome
Custom attribute `depsdir` has same behavior like built-in imagesdir.

**Comment by mojavelinux** [comment]
Please raise questions about how to use AsciiDoc and Asciidoctor in the project chat at https://chat.asciidoctor.org. Thanks.

**Comment by Baerbeisser** [comment]
Meaning, a custom attribute used in an include but defined by the caller, getting the path wrong, is an usage issue?

**Comment by mojavelinux** [comment]
Yes, I'm confident the parser behaves the way it is designed. It is
thoroughly tested and used in production for well over a decade. This is a
misunderstanding about how AsciiDoc behaves.

**Comment by Baerbeisser** [comment]
Ok, are you in the project chat too?
