### ISSUE TITLE
using authorline for contactlist - enhancement ?

### ISSUE THREAD

**Issue by ofunk** [asciidoctor/asciidoctor#4618]
In https://docs.asciidoctor.org/asciidoc/latest/document/author-line/
author is based on: first name, middle name, last name, initials, email

In case https://github.com/asciidoctor/asciidoctor-pdf/issues/800 was a reference to url but I did not find any documentation how to use it outside of themes.

I am looking for a solution to manage contact information e.g. in tables etc which requires phone, title, and social media as well.

Would it help to define this in authors lines or do you have a better workaround?

**Comment by mojavelinux** [comment]
You can put a URL in place of the email address. (see https://docs.asciidoctor.org/asciidoc/latest/document/author-information/#author-and-email-attributes). Beyond that, we're not planning to add any more complexity to the implicit author line. It's only meant to be a convenience for quick editing. You can define any metadata you want using document attributes, and that metadata can then be used in the output however you like.

Generally speaking, there are various ways to organize contact information in an AsciiDoc document. The correct place to ask questions and seek advice is the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). The issue tracker is not a support portal or forum. This policy helps keep the project sustainable. We'll be glad to follow-up in the chat.
