### ISSUE TITLE
variables in plantuml - minmap

### ISSUE THREAD

**Issue by ofunk** [asciidoctor/asciidoctor#4619]
according to https://stackoverflow.com/questions/61858075/how-use-variables-from-asciidoc-in-plantuml-diagrams
variables work for all kind of plantuml

it seems not to work for mindmap https://plantuml.com/mindmap-diagram

is this a asciidoc preprocessor issue or a plantuml preprocessing issue? whom to adress?
thx for your 2c
oliver

**Comment by mojavelinux** [comment]
The correct place to ask questions and seek advice is the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal or forum. This policy helps keep the project sustainable. We'll be glad to follow-up in the chat.
