### ISSUE TITLE
Regression in 2.0.19: repeated `` `+` `` are rendered incorrectly

### ISSUE THREAD

**Issue by dscho** [asciidoctor/asciidoctor#4624]
With AsciiDoctor v2.0.18, multiple `` `+` ``  in the same line are interpreted as individual, monospace plus signs:

```console
$ echo '`+` hello `+`' | asciidoctor - | grep hello
<p><code>+</code> hello <code>+</code></p>
```

This is expected, and in line with what e.g. https://asciidoclive.com/ renders. It is also consistent with my copy of AsciiDoc:

```console
$ echo '`+` hello `+`' | asciidoc - | grep hello
<div class="paragraph"><p><code>+</code> hello <code>+</code></p></div>

$ asciidoc --version
asciidoc 10.1.2
```

Starting with AsciiDoctor v2.0.19 (all the way to the current version, v2.0.23), all of a sudden the matcher is greedy and renders this incorrectly:

```console
$ echo '`+` hello `+`' | asciidoctor - | grep hello
<p><code>` hello `</code></p>
```

Note how the entire line is now one single literal monospace: The first back tick and the first plus sign is misinterpreted as the start of a [literal monospace](https://docs.asciidoctor.org/asciidoc/latest/text/literal-monospace/) and the last plus sign and the last backtick are misinterpeted as the end of that single literal monospace span.

The only workaround I found is to use `` `{plus}` ``, but it would be good if this scenario was handled just like AsciiDoc handles it, again.

Noticed in https://github.com/git/git-scm.com/pull/1879.

**Comment by mojavelinux** [comment]
This change is not a regression, it was intentional. It fixed bug #4458 and was mentioned in the release notes for the 2.0.19 release.

The described behavior is correct. The inline passthrough takes precedence. This is the compliance behavior.

One way to escape it is to use `{plus}` as you mentioned. That is a perfectly viable way to do it. Another way is to use backslash escaping.

```
`\+` hello `+`
```

**Comment by dscho** [comment]
> Another way is to use backslash escaping.

Are you 100% sure that this works? Because I am not:

```console
$ echo '`\+` hello' | asciidoctor - | grep hello
<p><code>\+</code> hello</p>
```

> The described behavior is correct.

I just wish that AsciiDoc and https://asciidoclive.com/ would agree, but they produce different output, and have done so in a very, very long time. Even AsciiDoc v3.2.3 disagrees with you, and it has been released in April this year:

```console
$ asciidoc3 --version
asciidoc3 3.2.3

$ echo '`+` hello `+`' | asciidoc3 - | grep hello
<div class="paragraph"><p><code>+</code> hello <code>+</code></p></div>
```

**Comment by mojavelinux** [comment]
asciidoclive is not an official AsciiDoc project.

AsciiDoc.py is no longer the canonical AsciiDoc implementation (and hasn't been for many years). And asciidoc3 is not even AsciiDoc.py, but some unsanctioned fork.

The behavior in Asciidoctor is the correct behavior.

**Comment by mojavelinux** [comment]
The reason this does not work:

```
echo '`\+` hello' | asciidoctor - | grep hello
```

Is because there is no pair, so the backslash escaping is not needed. Only a pair can be escaped. For example:

```
echo '`\+` hello and `+`' | asciidoctor -d inline -
```

**Comment by dscho** [comment]
> asciidoclive is not an official AsciiDoc project.

It is pretty convenient, and while AsciiDoctor is now the official product, it may be a big effort to make the case against existing mountains of AsciiDoc-formatted documents.

But maybe there is a corpus of known edge cases with sanctioned rendering that any project like asciidoclive could verify correctness against?

I say that because I got admittedly quite frustrated trying to look for any official, clear specification that would state precisely how the corner cases of monospace, inline monospace, backticks and plus signs are expected to be handled.

**Comment by mojavelinux** [comment]
> But maybe there is a corpus of known edge cases with sanctioned rendering that any project like asciidoclive could verify correctness against?

That's the entire mission of the AsciiDoc Language project.

> I say that because I got admittedly quite frustrated trying to look for any official, clear specification that would state precisely how the corner cases of monospace, inline monospace, backticks and plus signs are expected to be handled.

Again, that's what we're currently working towards. See asciidoc.org for more info. You are welcome to join the effort.

**Comment by mojavelinux** [comment]
> (asciidoclive) is pretty convenient, though

There are equivalent projects in Asciidoctor, such as the Asciidoctor browser extension, the AsciiDoc plugin for IntelliJ, and the AsciiDoc extension for VSCode. All of these are developed in a way that validates with the upstream project (until the AsciiDoc Language specification comes into force).
