### ISSUE TITLE
docs.asciidoctor.org rouge-linenums-mode not aligned with  #3641?

### ISSUE THREAD

**Issue by nmwael** [asciidoctor/asciidoctor#4630]
It seems documentation are out of date for this topic:
https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/#rouge-attributes rouge-linenums-mode 

Above links to #3641 which is resolved?

**Comment by mojavelinux** [comment]
The issue is resolved, but the change has not yet been included in a release. The label on the issue indicates the fix is first available in 2.1.0, which has not yet been released. So the docs are still correct. I commented on the related issue.

**Comment by nmwael** [comment]
thanks for the clarification.
