### ISSUE TITLE
Asciidoctor could be more helpful when SOURCE_DATE_EPOCH is malformed

### ISSUE THREAD

**Issue by hawkw** [asciidoctor/asciidoctor#4631]
When the `SOURCE_DATE_EPOCH` environment variable is set to a value which asciidoctor dislikes, such as an empty string, `asciidoctor` fails with the error message `Failed to load AsciiDoc document - invalid value for Integer(): ""`. This doesn't make it particularly clear which environment variable was invalid, and (in my opinion) suggests somewhat that the invalid value was somewhere in the document itself, which is not actually the case. In order to determine that it's actually the environment variable which is erroneous, the user must inspect the stack trace and the asciidoctor source code. It would be nicer if the error message indicated that the `SOURCE_DATE_EPOCH` env var is the problem.

Secondarily, I notice that asciidoctor doesn't mind when this environment variable is unset, but _does_ dislike it when it's emptystring. Perhaps there are reasons for this, but it seems to me like those cases could be equivalent?

For example:
```console 
$ asciidoctor -V; uname -a
Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
Linux theseus 6.11.1 #1-NixOS SMP PREEMPT_DYNAMIC Mon Sep 30 14:31:09 UTC 2024 x86_64 GNU/Linux

$ export SOURCE_DATE_EPOCH=""; asciidoctor -v README.adoc; echo $?
asciidoctor: FAILED: /home/eliza/Code/oxide/rfd/rfd/0520/README.adoc: Failed to load AsciiDoc document - invalid value for Integer(): ""
  Use --trace to show backtrace
1

$ unset SOURCE_DATE_EPOCH; asciidoctor -v README.adoc; echo $?
0
```

**Comment by mojavelinux** [comment]
Inclination is to simply ignore it if it cannot be parsed. It's really not up to Asciidoctor to validate all the inputs as that would be a never-end task. But it can do something sensible in the case the input is malformed.

**Comment by hawkw** [comment]
Just ignoring empty strings here would certainly be my preference as well!

**Comment by mojavelinux** [comment]
The spec is not entirely clear what to do when the environment variable is set, but has no value. (see https://reproducible-builds.org/specs/source-date-epoch/) All the examples indicate that this is a malformed value and thus should result in a non-zero exit code. (see https://reproducible-builds.org/docs/source-date-epoch/#ruby). So technically, Asciidoctor's behavior is to spec. However, logically, it just doesn't make a lot of sense to try to use the environment variable when the value is empty. Therefore, we can go ahead and verify that the value is not nil or empty before attempting to use it.
