### ISSUE TITLE
Cannot Escape A Hash Symbol in File Path for xref

### ISSUE THREAD

**Issue by maddes-b** [asciidoctor/asciidoctor#4633]
If I [xref](https://docs.asciidoctor.org/asciidoc/latest/macros/xref/) a document that has a hash (#) in its path, either in a directory name or the file name itself, then the resulting link is not working.

* `xref:dirname/#file.adoc[]`
  * VS Code: link `dirname/.adoc#file.adoc` with text `dirname/.adoc`
  * Firefox: link `dirname/.adoc#file.adoc` with text `dirname/.adoc`
* `xref:#dirname/file.adoc[]`
  * VS Code: local link `#dirname/file.adoc` with text `dirname/file.adoc`
  * Firefox: local link `#dirname/file.adoc` with text `[dirname/file.adoc]`

Using the info given in https://github.com/asciidoctor/asciidoctor/issues/3415 does not solve this issue:

* `xref:dirname/&#35;file.adoc[]`
  * VS Code: looks correct but does not work - link `dirname/#file.adoc` with text `dirname/#file.adoc`
  * Firefox: link `dirname/&.adoc#35;file.adoc` with text `dirname/&.adoc`
* `xref:&#35;dirname/file.adoc[]`
  * VS Code: just text `xref:#dirname/file.adoc[]`
  * Firefox: just text `xref:#dirname/file.adoc[]`

* `xref:dirname/&num;file.adoc[]`
  * VS Code: link `dirname/file.adoc` with text `dirname/file.adoc`
  * Firefox: link `dirname/#file.adoc` (not URI encoded `%23`) with text `dirname/#file.adoc`
* `xref:&num;dirname/file.adoc[]`
  * VS Code: just text `xref:#dirname/file.adoc[]`
  * Firefox: just text `xref:#dirname/file.adoc[]`

* defining and using `:hash: &#35;` or `:hash: &num;` returns the same results

* defining and using `:hash: #` is like using hash directly

* defining and using `:hash: %23` will work for a filename with hash, but not for a dirname

Is there a way to escape a hash symbol in a path for xref (and maybe also link), or is this a gap in the syntax?
If there is a solution, where can I find it in the docs?

Any help is much appreciated
Maddes

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org as the issue template requested. The issue tracker is not a support portal. If we determine that there is a deficiency in the software, only then will we request an issue to be filed.
