### ISSUE TITLE
Ruby 3.4 test failure

### ISSUE THREAD

**Issue by voxik** [asciidoctor/asciidoctor#4634]
Just did first test runs with upcoming Ruby 3.4 on Fedora and there seems to be failures such as:

~~~
  1) Failure:
Minitest::Test::TestExtensions::TestIntegration#test_should_assign_captures_correctly_for_inline_macros [test/extensions_test.rb:1382]:
--- expected
+++ actual
@@ -1,9 +1,9 @@
 "target=\"\", attributes={}
-target=\"value,key=val\", attributes={1=>\"value\", \"key\"=>\"val\", \"name\"=>\"value\"}
-target=\"\", attributes={\"text\"=>\"\"}
-target=\"[text]\", attributes={\"text\"=>\"[text]\"}
+target=\"value,key=val\", attributes={1 => \"value\", \"key\" => \"val\", \"name\" => \"value\"}
+target=\"\", attributes={\"text\" => \"\"}
+target=\"[text]\", attributes={\"text\" => \"[text]\"}
 target=\"target\", attributes={}
-target=\"target\", attributes={1=>\"value\", \"key\"=>\"val\", \"name\"=>\"value\"}
-target=\"target\", attributes={\"text\"=>\"\"}
-target=\"target\", attributes={\"text\"=>\"[text]\"}
+target=\"target\", attributes={1 => \"value\", \"key\" => \"val\", \"name\" => \"value\"}
+target=\"target\", attributes={\"text\" => \"\"}
+target=\"target\", attributes={\"text\" => \"[text]\"}
 target=\"target\", attributes={}"


... snip ...

 12) Error:
Minitest::Test::TestBlocks::TestAdmonitionIcons#test_embeds_base64_encoded_data_uri_of_icon_when_data_uri_attribute_is_set_and_safe_mode_level_is_less_than_SECURE:
LoadError: cannot load such file -- base64
    <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
    <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
    lib/asciidoctor/abstract_node.rb:380:in 'Asciidoctor::AbstractNode#generate_data_uri'
    lib/asciidoctor/abstract_node.rb:328:in 'Asciidoctor::AbstractNode#image_uri'
    lib/asciidoctor/abstract_node.rb:299:in 'Asciidoctor::AbstractNode#icon_uri'
    lib/asciidoctor/converter/html5.rb:439:in 'Asciidoctor::Converter::Html5Converter#convert_admonition'
    lib/asciidoctor/converter/html5.rb:61:in 'Asciidoctor::Converter::Html5Converter#convert'
    lib/asciidoctor/abstract_block.rb:76:in 'Asciidoctor::AbstractBlock#convert'
    lib/asciidoctor/abstract_block.rb:85:in 'block in Asciidoctor::AbstractBlock#content'
    lib/asciidoctor/abstract_block.rb:85:in 'Array#map'
    lib/asciidoctor/abstract_block.rb:85:in 'Asciidoctor::AbstractBlock#content'
    lib/asciidoctor/document.rb:1012:in 'Asciidoctor::Document#content'
    lib/asciidoctor/converter/html5.rb:227:in 'Asciidoctor::Converter::Html5Converter#convert_document'
    lib/asciidoctor/converter/html5.rb:85:in 'Asciidoctor::Converter::Html5Converter#convert'
    lib/asciidoctor/document.rb:956:in 'Asciidoctor::Document#convert'
    test/test_helper.rb:219:in 'Minitest::Test#convert_string'
    test/blocks_test.rb:3345:in 'block (3 levels) in <top (required)>'
~~~

It seems that the first issue is cause by additional spaces around has rocket, while the latter is caused by extraction parts of StdLib into bundled gems.

Could the `ruby-head` be added to test matrix and these issues addressed? Thx a lot in advance.

**Comment by mojavelinux** [comment]
> Could the ruby-head be added to test matrix and these issues addressed?

I removed it because it continuously gave me problems (for various reasons). I just don't have the time to deal with CI failures every day. So no, that's not something I'm prepared to do. Someone is welcome to add that in a fork and report issues upstream.

I'm EXTREMELY frustrated with the Ruby language right now. They just don't seem to care about compatibility any more. These tests have worked for over a decade and now they are failing. That's unacceptable. I'm not changing the code to fix regressions in Ruby. They need to be addressed upstream.

**Comment by mojavelinux** [comment]
> while the latter is caused by extraction parts of StdLib into bundled gems.

Asciidoctor no longer uses the base64 library, so it appears the tests are running an older version of Asciidoctor.

**Comment by mojavelinux** [comment]
> cause by additional spaces around has rocket

I'm willing to normalize the comparison strings in this case.

**Comment by voxik** [comment]
> > while the latter is caused by extraction parts of StdLib into bundled gems.
> 
> Asciidoctor no longer uses the base64 library, so it appears the tests are running an older version of Asciidoctor. This dependency was removed in the 2.0.22 release.

Yes, sorry, this is likely not the most recent version. Good to hear that.

> I'm EXTREMELY frustrated with the Ruby language right now. They just don't seem to care about compatibility any more. These tests have worked for over a decade and now they are failing. That's unacceptable.

I share your sentiment and appreciate the fix.

**Comment by mojavelinux** [comment]
If the first test still doesn't pass for whatever reason, feel free to reopen and I'll look at it again.

As for base64, we are actually better off without it anyway since the function we were using is provided by the String class. Asciidoctor should have 0 dependencies to operate core functionality and we want to keep it that way.
