### ISSUE TITLE
Is there a TextMate grammer available for Asciidoc?

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor#4640]
Multiple text editors like VScode and Eclipse support syntax highlighting based on a TextMate grammer. 

For example https://github.com/microsoft/vscode/blob/65edc4939843c90c34d61f4ce11704f09d3e5cb6/extensions/razor/syntaxes/cshtml.tmLanguage.json

Is such a grammer officially also available for Asciidoc? I found https://github.com/mattneub/AsciiDoc-TextMate-2.tmbundle and https://github.com/zuckschwerdt/asciidoc.tmbundle but both seemed to be not actively maintained.

**Comment by ggrossetie** [comment]
As mentioned in the issue template:

> If you've arrived here to ask a question about how to use Asciidoctor or the AsciiDoc syntax, please direct your question to the #users stream in the project chat at https://chat.asciidoctor.org instead. You can learn more about the project support policy on the following page: https://docs.asciidoctor.org/about/support/

Please direct your question to the #users stream in the project chat at https://chat.asciidoctor.org. I will happily answer this question on the project chat 😉

**Comment by vogella** [comment]
Thanks @@ggrossetie will do
