### ISSUE TITLE
:revnumber: in revision line must be numeric

### ISSUE THREAD

**Issue by billandel** [asciidoctor/asciidoctor#4643]
If I specify the revision line as follows:

`B, 18-Dec-2024 : CR 1357 - Update branding & markings`

...and then reference `{revnumber}`, it resolves to blanks.  I can manually override by stating ':revnumber: B', but this sort of obviates the point of using the revision line in the first place.

Currently using AsciidoctorJ 2.5.12

**Comment by mojavelinux** [comment]
This behavior is as documented. Please see https://docs.asciidoctor.org/asciidoc/latest/document/revision-line/#when-can-i-use-the-revision-line

If you need further assistance, please ask in the project chat at https://chat.asciidoctor.org. The issue tracker is for **verified** bugs and formal proposals, not support.
