### ISSUE TITLE
Include images by full URL

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctor#470]
For lightweight/instant publishing to HTML it would be useful to include images by full URL. This way the user can point to images located on different services, a blog, clipart, whatever, without having to care about downloading the images and putting them in a specific location.

Here's an example use case:
http://docgist.nawroth.se/

Here, the page is rendered by the browser using asciidoctor.js from a source document stored as a GitHub gist. I added post-processing to turn links to images into images. But I'd prefer a distinct syntax in AsciiDoc for this.

The original use case for this is http://gist.neo4j.org/ but I created the above version where there's no additional Neo4j related stuff. At Neo4j, we want to be able to (as well as enable users to) quickly publish database queries with some surrounding text. Let's say I want a UML diagram on the page, then I use http://yuml.me/ to create it. That gives me an image URL I can use right away, no need to download it and upload it to somewhere.

**Comment by alanconway** [comment]
The URI RFC has rules for relative-URI references, which might help resolve the leading / question.
Assuming the current page is at https://example.com/docs/thing then the following URI refs resolve as indicated:

http://x.y/foo - not relative, entirely new URI - http://x.y/foo
//x.y/foo - new authority relative to current scheme - https://x.y/foo
/foo - new path relative to current authority - https://example.com/foo
./foo or foo - additional path relative to "container" of current resource - https://example.com/docs/foo

For asciidoctor image links I think base URL means {real-base-url}{imagedir}, i.e. the real base URL by default with an optional extension based on type of link. I think this is pretty much what you're proposing anyway, but suggest sticking to the standard URI-ref semantics to avoid surprises.
