### ISSUE TITLE
Hyperlinks with double underscores don't render correctly

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/asciidoctor#625]
I found while including a hyperlink with double underscores in an AsciiDoc file that they are not rendered correctly. To reproduce, I created a document named link.asc whose sole line is:

> Link: http://www.migrations.fr/la_guerre__de__sept__ans.htm

When I render it with Asciidoctor using

> $ asciidoctor link.asc

...the line in question becomes:

```
Link: <a href="http://www.migrations.fr/la_guerre">http://www.migrations.fr/la_guerre</a><em>de</em>sept__ans.htm
```

Notice that the href tag is incorrect and the double underscores have been interpreted as italics. I expect the line to render as:

```
Link: <a href="http://www.migrations.fr/la_guerre__de__sept__ans.htm">http://www.migrations.fr/la_guerre__de__sept__ans.htm</a>
```

AsciiDoc does not render this line correctly either, by the way. I originally posted this question in the [Nabble discussion forum](http://discuss.asciidoctor.org/Hyperlinks-with-multiple-underscores-td558.html).

**Comment by imet** [comment]
Thank you very much @mojavelinux ,

Your solution double dollar escape also worked for http://www.google.com/~example@gmail.com

For asciidoc, we need to escape it like this:

`http://www.google.com/$$~example@gmail.com$$` then I can get one normal url link

**Comment by mojavelinux** [comment]
Great to hear! Note that these techniques are now documented in the user manual. See http://asciidoctor.org/docs/user-manual/#complex-urls.

**Comment by richnsoos** [comment]
Thanks, @ neontapir and @mojavelinux !! Ran into a this very issue today with a link that includes underscores and Solution A works great.

**Comment by mojavelinux** [comment]
Or you can put a backslash in front of ... to take away it's special
meaning as an ellipsis. That's true everywhere AsciiDoc is rendered.
