### ISSUE TITLE
prettify source highlighter renders source with line numbers poorly

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#640]
The prettify source highlighter wraps the `<code>` element in an ordered list. This causes the lines to be decorated in the same way as inline monospaced text, which looks ugly when using the default stylesheet. Add special styles for prettify that prevent the nested `<code>` element from being styled.

Example:

```
:source-highlighter: prettify

[source,java,numbered]
public class Document {
  private String title;
  public Document(String title) {
    this.title = title;
  }
  public String getTitle() {
    return this.title;
  }
}
```

**Comment by stephenhay** [comment]
Here's a rendering of the example you gave using asciidoctor 1.5.4:

![screenshot from 2016-01-08 21 01 36](https://cloud.githubusercontent.com/assets/473099/12208144/2d3b5bf8-b64b-11e5-9eb5-4e0aaa32a7f5.png)

I see two issues here:

1. If I understand you correctly, you would like the "inline-block"-like background color removed, to this effect:

![screenshot from 2016-01-08 21 05 54](https://cloud.githubusercontent.com/assets/473099/12208196/a4c882c2-b64b-11e5-980f-0cf7efa8a77e.png)

2. You have `numbered` in the source, but no numbers appear except for 5. It looks like this is due to the fact that `ol.linenums li.L4` is nowhere to be found in the style sheet. Even stranger is the fact the other `li` elements within `ol.linenums` are styled with `list-style-type: none;`.

What's the correct display supposed to be, given your example?

**Comment by mojavelinux** [comment]
>  you would like the "inline-block"-like background color remove

Exactly. The current styling looks...well, not so "prettified" :)

We currently use `*:not(pre)>code` in the default stylesheet to style code in prose. However, prettify breaks this assumption by putting an element (several) between the pre and code (unlike all the other syntax highlighters).

I guess we'll need something like this to reverse the styles:

```css
pre.prettyprint code {
    font-size: inherit;
    padding: 0;
    word-spacing: 0;
    background-color: inherit;
    border-radius: 0;
    line-height: inherit;
}
```

The other option is to change the `*:not(pre) > code` to `*:not(pre) > code:not([data-lang])`. That would immediately fix the issue as well.

I wish in CSS there was a way to say "code not descendant of pre", but I couldn't find a way (before CSS4). This is why it's probably best if we use a CSS class on code elements in prose in order to be able to distinguish them, as I did in the EPUB3 output (see https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/converter.rb#L777)

> You have numbered in the source, but no numbers appear except for 5. 

This is just how prettify does numbering. It only labels every 5 rows. The style comes from the linked stylesheet, not the default stylesheet in Asciidoctor. (see https://cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.min.css).

**Comment by mojavelinux** [comment]
Here's the area of the SASS file where we've put overrides for prettify.

https://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/sass/components/_asciidoc.scss#L723-L727

Something in that neighborhood would keep things close together...though I wonder whether the idea of using `*:not(pre) > code:not([data-lang])` is a better strategy.

**Comment by mojavelinux** [comment]
We might even be able to get away with just using `code:not([data-lang])` since the `<code>` element is only used inside a `<pre>` when source highlighting is used and then the `data-lang` attribute is always set. That change makes me a little nervous, but it might be the leap we should take here.

**Comment by rahmanusta** [comment]
Hello, I'm getting the following result when using prettify.js

![image](https://cloud.githubusercontent.com/assets/1158804/16334826/07717e26-3a0c-11e6-9fec-4f7434b97cb3.png)

Is there known solution for that?

Thanks.

**Comment by mojavelinux** [comment]
Everything I know about fixing this issue is mentioned in the comments in this issue. It's still an open issue.

**Comment by rahmanusta** [comment]
Do you open some CSS hacks for this issue ?

**Comment by mojavelinux** [comment]
Not yet, other than what I described above.

**Comment by rahmanusta** [comment]
Okay, I will just look forward for further updates. Thanks.

**Comment by stephenhay** [comment]
I feel that changing the selector is the best solution in this case. The change is fairly safe, and moving to class-based selections means adding to markup, and does not eliminate the need for a selector, which also might need to change if Prettify does. With the `[...]:not([data-attr])` change, we accommodate Prettify, limit any future refactoring to this selector only, need no additions to markup, and create practically no danger of style conflicts.

https://github.com/asciidoctor/asciidoctor-stylesheet-factory/pull/32

**Comment by mojavelinux** [comment]
As we've discussed, the main issue is that prettify separates the `<pre>` and `<code>` elements. As a result, the styles from the `:not(pre)>code` styles get applied to the `<code>` elements inside the source block.

At first, I thought the solution would be to use `:not(pre)>code:not([data-lang])`. However, as it turns out, the `data-lang` attribute isn't always set (in the case the source block has no language). Plus, it feels a bit non-specific.

I've since learned that you can exclude multiple parent tags by stacking them. This is an ideal solution because we can actually target the inheritance at hand.

When prettify adds line numbers, it wraps each `<code>` element in an `<li>` tag with a class that begins with L (e.g., L1, L2, L3, L4). Here's how we can exclude that scenario:

```
:not(pre):not([class^=L])
```

Although that looks rather specific, it allows us to handle this case with little to no impact elsewhere.

I'm also going to add a few more styles to align them with the output of the other syntax highlighters.

```
pre.prettyprint .linenums {
  color: #999; 
  line-height: $pre-line-height;
  margin-left: 2em;
}

pre.prettyprint .linenums li {
  background: none;
  list-style-type: inherit;
}
```
