### ISSUE TITLE
A cli / API attribute unassignment should support the precedence inversion flag (@)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#642]
An attribute unassignment passed to the cli or API should support the precedence inversion flag, `@`.

For example, if the `prewrap` attribute is unset as follows:

```
-a 'prewrap!@'
```

NOTE: The quoting is necessary to prevent the shell from expanding `!@`.

In this case, an assignment of the `prewrap` attribute in the document should take precedence:

```
:prewrap:
```

This works in the same way as attribute assignment (e.g., `foo=bar@`).

**Comment by mojavelinux** [comment]
I've done some more thinking about this and I see two scenarios we need to cover.

The **first scenario** is when the attributes are passed to the API as a string or passed to the CLI (always as a string). If we want to be consistent with the syntax for how an attribute is soft set, we'd simply look for the `@` modifier in the value:

```
sectids!=@
```

The other option is to move the `@` modifier to the end of the name (in which case a value is not needed).

```
sectids!@
```

The problem is that this makes the syntax for soft setting and soft unsetting an attribute inconsistent.

To reconcile this inconsistency, we could allow the `@` modifier to be appended to the name in either case, thus offering an alternate (modern) syntax:

```
source-highlighter@=coderay
sectids!@
!toc@
```

I'll be honest, I kind of like this better since `@` is not a valid character for an attribute name anyway. We'd then deprecate `@` at the end of the value and shift it to the end of the name. If we decided to go this route, we wouldn't even recognize `@` in the attribute value when soft unsetting an attribute. We'd only support the new syntax for that case.

The **second scenario** is when attributes are passed to the API as a Hash. In this case, we need a way to differentiate between soft and hard unsetting an attribute. I see some wiggle room here.

We've long stated that to unset an attribute from the API using a Hash entry, you set the value of the entry to nil (not false). To preserve existing behavior, we need to continue treating as meaning hard unset (i.e., unset and lock) the attribute.

At first, I thought about introducing a dedicated symbol to mean soft unset (like `:@nil`). The problem is, we use falsy checks in several places that would have to be updated to account for this special representation of nil. But there's another falsy value we could use to avoid having to do that. That value is false. We can use the falsy characteristic of false to our advantage.

If the attribute value is set to false instead of nil, we can interpret this as an intent to soft unset (i.e., unset but do not lock) the attribute. Instead of assigning the attribute value to false, we'd remove it (like we do when the value is nil), only we'd also allow it to be overridden by the document.

**Comment by elextr** [comment]
Its much better with `@` on the name, then you don't have to handle escaping or some other syntax to actually have a value that ends in `@`

**Comment by graphitefriction** [comment]
:+1: for `@` in the name for soft setting and unsetting

**Comment by mojavelinux** [comment]
Having to quote the CLI option in the following case to avoid shell expansion is really bothering me.

```
-a 'prewrap!@'
```

Therefore, I'm going to allow the `@` to be moved to the value as an alternate syntax for soft unset.

```
-a prewrap!=@
```

I think this will also make it easier to document. We can say the `@` is allowed at the end of the value, but the preferred location is at the end of the name. But the user doesn't have to remember whether it goes on the name or the value.

**Comment by mojavelinux** [comment]
For the record, the `!` can always be escaped when used in an option value for a command. So instead of looking at this as an exception, we could promote this as a general rule of thumb.

```
asciidoctor -a \!icons document.adoc

asciidoctor -a icons\! document.adoc

asciidoctor -a icons\!@ document.adoc
```

In other words, it never hurts to escape it.
