### ISSUE TITLE
Javascripts not added to the HTML created

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor#672]
When using this guard script 

``` ruby
require 'asciidoctor'
require 'erb'

guard 'shell' do
  watch(/^*\.adoc$/) {|m|
    Asciidoctor.render_file(m[0], {
      :in_place => true,
      :attributes => {
          'backend' => 'html5',
          'linkcss' => 'true',
          'stylesdir' => './styles',
          'stylesheet'=> 'asciidoctor.css',
          'scriptsdir' => './javascript/vendor'
      }
    })
  }
end

guard 'livereload' do
  watch(%r{^.+\.(css|js|html)$})
end
```

or this asciidoctor command line 

```
asciidoctor -b html5 -a linkcss -a stylesdir=./styles -a stylesheet=gpe_theme.css -a scriptsdir=./javascript/vendor test.adoc 
```

the javasctipts file ( = modernizer.js) is not added in the header of the HTML generated 

``` xml
<script src="/javascripts/vendor/custom.modernizr.js">
```

**Comment by danyill** [comment]
@mojavelinux Can we work towards a means for including javascript in a similar manner to css?

My use case is this:

I have a range of Asciidoc files which I distribute within a zip file. They might have a layout like this:

```
|---assets
      |---fonts
            |---<various eot svg ttf woff woff2>
      |---tocbot.js
      |---docinfo.html
      |---asciidoctor.css
      |---font-awesome.min.css
|---design_guide---Design_Guide.adoc
|---operating_information---Operating_Information.adoc

```

By using unsafe mode and setting `docinfodir`, `stylesdir`, `stylesheet` and `linkcss` appropriately, I am able to provide an html5 rendered document which doesn't refer to external resources (important for my use case) and have all the resources load from a single root folder.

This might be using, for instance:

```asciidoc
:docinfo: shared
:safe-mode-unsafe:
:docinfodir: ../assets
:stylesdir: ../assets
:iconfont-remote!:
:stylesheet: asciidoctor.css
:scriptsdir: ../assets
:linkcss:
:iconfont-name: font-awesome.min
:imagesdir: media
:icons: font
```

This works well at the moment for everything except javascript where I would like to include e.g. tocbot as per #699.

I can't find a ready mechanism for including the javascript in a similar manner to what the `linkcss` attribute provides (i.e. that it is all relative to the assets folder as it is for fonts and other resources).  

I was hoping I could set `:scriptsdir:` and this would behave similarly to `stylesdir` with `linkcss` set  but this did not appear to help (although maybe it would if I used Asciidoc? [see documentation](http://www.methods.co.nz/asciidoc/chunked/ch07.html))

I guess what I'd like to see is the following:

* a `scriptdir` which could be set to e.g. `../assets`
* a `linkscript` attribute which would adjust the paths correctly.

A standard nomenclature for injecting a script without using either passthrough or docinfo (which seems klunky/untidy). Perhaps a macro which allows a script to be specified.

**Comment by danyill** [comment]
All is not lost!

I discover that I can inject attributes into docinfo files so I have simply done this in my asciidoc:

`:scriptsdir: ../assets`

and 

```html
<script src="{scriptsdir}/tocbot.min.js"></script>
```

Works like a dream!
