### ISSUE TITLE
Optimize default html5 backend performance

### ISSUE THREAD

**Issue by rwinch** [asciidoctor/asciidoctor#779]
It would be valuable to profile the html5 backend Currently larger documents,like the [Spring Reference](http://docs.spring.io/spring-framework/docs/4.0.0.BUILD-SNAPSHOT/spring-framework-reference/htmlsingle/), are a bit sluggish.

Profiling with Chrome Developer tools shows that it renders an average of 2 FPS and one should strive for 60 FPS (to match a standard 60 Hz monitor). More information can be found on the [Chrome Dev Tools site](https://developers.google.com/chrome-developer-tools/docs/timeline#frames_mode).

I'm not an expert in this area, but a few things that stick out to me that will be slow:
- Using `>` within css selectors is often times slow. [See here](https://developers.google.com/speed/docs/best-practices/rendering?csw=1#UseEfficientCSSSelectors)
- Using `text-rendering: optimizeLegibility;` has a fairly drastic impact on the rendering time
- Ensuring the HTML, CSS, JS, etc are easily compressed
- Explicitly stating image sizes. [See here](https://developers.google.com/speed/docs/best-practices/rendering?csw=1#SpecifyImageDimensions)

**Comment by mojavelinux** [comment]
The default stylesheet has been used heavily over the years and I think the combination of improvements to the selectors, browser improvements, and slimming down of the file size has put this issue to rest. If you feel like more could be done, please open a new issue with those suggestions.

(I think we'll still see better performance overall in the stylesheet for #242).
