### ISSUE TITLE
Introduce :uri-protocol: for includes (video, images, audio, etc)

### ISSUE THREAD

**Issue by LightGuard** [asciidoctor/asciidoctor#822]
This was discussed at http://discuss.asciidoctor.org/deck-js-intro-slide-deck-converted-to-AsciiDoc-tt1097.html#none

**Comment by mojavelinux** [comment]
This was implemented in 1.5.0 (https://github.com/asciidoctor/asciidoctor/commit/51eb091b71737af12497f443fce08e7b952dd68e) as the attribute `asset-uri-scheme`.
