### ISSUE TITLE
list level depth limitation

### ISSUE THREAD

**Issue by Vad1mo** [asciidoctor/asciidoctor#825]
Hello, 

I am using asciidoctor/j and I was wondering if ascidoctor supports more then 5 list levels 

I have this tree structure and everything is displayed fine until I reach level => 6 then the html changes to something like this:

```
LEVEL 6
<strong>
    <strong></strong>
</strong>
```

```
* 1
** 2
*** 3
**** 4
***** 5
****** 6
******* 7
******** 8
```

Question is are more then 5 levels supported and if not why?

**Comment by mojavelinux** [comment]
And this can be achieved using a custom block:

```
[tree]
--
* A
** B
*** C
******* H
--
```

The handler for tree can choose to parse the content of the block however it wants.

**Comment by jaikiran** [comment]
> And this can be achieved using a custom block:

> [tree]
> --
> * A
> ** B
> *** C
> ******* H
> --

> The handler for tree can choose to parse the content of the block however it wants.

@mojavelinux, Is there an example of writing handlers for custom blocks that I can follow to create one for tree structure like this one?

**Comment by owenh000** [comment]
@jaikiran, see [Extensions](http://asciidoctor.org/docs/user-manual/#extensions) in the Asciidoctor User Manual and the [asciidoctor-extensions-lab](https://github.com/asciidoctor/asciidoctor-extensions-lab) repository.

**Comment by dfontainenvidia** [comment]
I realize this is an old bug but I really can't understand the attitude being espoused by the maintainers here.

There's no technical reason any implementation has to have any limit whatsoever, as far as I'm aware. This is just abusing the tooling to arbitrarily constrain people's editorial decisions on their own documentation. This decision properly belongs to the maintainers of a given piece of documentation, not the maintainers of the tooling.

Not only is this imposition arbitrary and overstepping, it's completely unexpected (nothing is magic about the 6th level when you're viewing the source), and the tooling doesn't even attempt to catch it and issue a diagnostic. You just silently get bad output. This is just bad design.

**Comment by evaristeg** [comment]
I realize this is an old bug but I really can't understand the attitude being espoused by the maintainers here.

There's no technical reason any implementation has to have any limit whatsoever, as far as I'm aware. This is just abusing the tooling to arbitrarily constrain people's editorial decisions on their own documentation. This decision properly belongs to the maintainers of a given piece of documentation, not the maintainers of the tooling.

Not only is this imposition arbitrary and overstepping, it's completely unexpected (nothing is magic about the 6th level when you're viewing the source), and the tooling doesn't even attempt to catch it and issue a diagnostic. You just silently get bad output. This is just bad design.

**Comment by mojavelinux** [comment]
I'm sorry, but we disagree. And there does happen to be a technical reason. Having no limit severely impacts the performance of the processor. So there has to be a limit. The limit we have chosen is one that is widely adopted as a reasonable list depth, which is six levels. (A limit we adopted from AsciiDoc Python). If you have more than six levels, there's a very good chance you are using lists for something they were not intended...such as to define a tree. We have custom block extensions for that very purpose. So in fact, there is nothing stopping you from taking that approach.

The way you have made your case is very disrespectful to the project and I will not continue to have a dialogue if that is the way you are going to communicate.

**Comment by evaristeg** [comment]
Since our disagreement is axiomatic in nature, I agree this conversation will not be productive. I still consider this limit an editorial decision that should not, if reasonably avoidable, be imposed on users.

**Comment by mojavelinux** [comment]
If you present me with a real world use case (other than a tree, which we've already discussed), I'm willing to reconsider. But I need a reasoned defense, not just accusations and insults.

**Comment by evaristeg** [comment]
My use case is proprietary so unfortunately I can't show you it. It is a functional testing specification where I have subdivided possible states and enumerated things to check in these cases. This seems like a reasonable use for lists.

Where is the documentation for this tree extension?

**Comment by mojavelinux** [comment]
My statement about performance was too vague. A few extra levels will not have a measurable impact on performance. So technically there's no limitation there and we could do it. But I would then be expected to add the styles for those additional levels in the default stylesheet, or else people would complain that the bullets don't properly alternate. So there is overhead there in terms of effort. And we'd still have to have some sort of limit or document why the bullets stop alternating after a certain level.

**Comment by mojavelinux** [comment]
What limit do you require? You have to at least be able to communicate your requirement. Otherwise, how can you expect me to make a determination?

**Comment by mojavelinux** [comment]
The current documentation for a custom block extension is here: https://asciidoctor.org/docs/user-manual/#block-processor-example. It's very thin at the moment. Documenting the extensions thoroughly is on the roadmap for 2.0. The block extension has access to the raw content within a delimited block (such as an open block). That content could be a list of arbitrary depth, which the extension would be responsible for parsing.

**Comment by evaristeg** [comment]
We fundamentally disagree on a design level. I don't want to give you my current requirement and next month hit the new limit. I want there to be no limit. To make a bad analogy, this feels like gcc enforcing curly braces on one-line conditional or loop bodies, and not having a way to silence it.

If I have time, I might try to look into the implementation, but I don't know when I'd be able to do that. For now I feel it's best for me to just work around the current limit, or look into trees.

Thank you for the link.

**Comment by mojavelinux** [comment]
Well, I can tell you for certain that the limit will never be infinite. I'm willing to consider 6-7 levels instead of the current 5 (of a homogeneous list). There are reasons for the limitation and I have cited them. Your unwillingness to make a strong case only further convinces me that there isn't actually a justifiable reason to change the limit that's not already covered either by a diagram block (such as plantuml) or a custom block.

**Comment by elextr** [comment]
There are a number of things in Asciidoc syntax that are unlimited, length of block delimiters for eg, so its not inconceivable that list nesting would be unlimited, after all if you don't like it, just don't use it :)

But, any implementation of Asciidoc can impose limitations based on the way its implemented, there are several major ones in the current implementations.  @mojavelinux who knows the implementation intimately gave reasons for this limitation in the current Asciidoctor implementation (at least fixed CSS and performance).  If the project contributors don't wish to address this limitation for those reasons then thats fine, they don't have to, nobody is paying them to.

But, Asciidoctor is an open source project, so @evaristeg can provide a pull request for a change to the way things are implemented showing that its has no material performance impact and handling any backend issues like CSS and PDF generation support etc.

When that PR shows it can be done and the implications of the change, then the discussion about if it should be done can occur with suitable supporting evidence.

**Comment by mojavelinux** [comment]
I'm telling you that as project lead, I know the code, and I'm not open to a change that introduces no limit. I say that because I respect my community and I want to save someone the trouble of spending time on a pull request that won't get accepted.

The fact that you continue to use such divisive discourse has led me to decide that I'm not interested in receiving a pull request from you.

**Comment by evaristeg** [comment]
@elextr I agree completely. My issue is more that, the rejection was not initially presented as "it's not worth the cost of fixing in the current implementation" or anything like that - it was essentially, "using more than 5 levels of list is wholly illegitimate anyway". And then maintainers doubled down on this statement. At any rate, while I'd be happy to look at the code, @mojavelinux has already judged the quality of any hypothetical patch, so it's pointless.

**Comment by mojavelinux** [comment]
@elextr Generally speaking, that's a good summary of Asciidoctor policy.

In this case, though, I'm being more specific because I don't want to take the language in this direction. Having unlimited lists levels encourages a bad practice for content creation and not something we want to encourage. But we've provided block extensions for the very reason of lifting this type of restriction for specialized use cases...but, in that case, the context around the unlimited level is very clear and purposeful.

**Comment by mojavelinux** [comment]
After encountered a concrete real-world scenario in Antora and completing performance testing to determine the impact, I've decided to change my position on this issue. See #2854.
