### ISSUE TITLE
Allow path for inter-document cross reference (xref) to begin with path segment

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#844]
Allow the path for an inter-document xref to begin with a path segment (e.g., `..` or `/`).

Examples:

```
<<../target#id>>
<</target#id>>
```

**Comment by mboes** [comment]
:+1:

Is this a simple case of fixing the parser, or is there more to it?

**Comment by mojavelinux** [comment]
This may be more complicated since it may change how we store referenced documents internally. If I remember correctly, we are only storing the basename of the document (docname), so path segments aren't considered.

The best way to start is to try to spec out the possible scenarios so we are sure not to miss any or break existing behavior. I'm thinking something like a table of examples.

**Comment by mboes** [comment]
The examples I see are:
```
<<../target#id>>
<<./target#id>>
<</target#id>>
<<../target#>>
<</path/to/target#id>>
<<relative/path/to/target#id>>
```
And perhaps also
```
<<arbitrary-url#id>>
```

so e.g.

```
<<file:///path/to/target#id>>
<<http://www.example.com/path/to/target#id>>
```
All of the above should also allow a `<<target#id,text>>` as they do today. Any others that you see?

**Comment by mojavelinux** [comment]
Excellent!

I think we can say that this matching kicks in when the hash symbol is present. When the hash symbol is not present, then we assume that the value is an id.

The easy part of the code change is losing up the regexp. The hard part is going to be how to detect when a document has been included since we are currently dropping some of the information needed for the comparison. However, when I dive into the code I might find this is easier than I'm anticipating.

**Comment by mojavelinux** [comment]
Let's try to get this into 1.5.4.

**Comment by mojavelinux** [comment]
Jeremie figured out that you can use a fake directory to work around the pattern requirement so that you can reference a file in a parent directory.

```
Go to <<fake/../../document1.adoc#, document1>> 
```

See http://discuss.asciidoctor.org/Relative-InterDocument-Cross-References-one-level-up-td3006.html#a3010

**Comment by mojavelinux** [comment]
> The hard part is going to be how to detect when a document has been included since we are currently dropping some of the information needed for the comparison.

I was wrong. I'm happy to say it already works as expected!

**Comment by pielgrzym** [comment]
Hi,

Just wanted to remark one thing - to cross reference relative documents one need to prefix path with './' - otherwise it defaults to old (not working) behavior:
```
xref:./sub/docu.adoc#[this works fine]
xref:sub/docu.adoc#[this does not]
```

Is it a desired behavior?

**Comment by mojavelinux** [comment]
@pielgrzym Are you sure you are checking against the repository HEAD (i.e., development version). This fix is not yet part of a release.

**Comment by jasonkuhrt** [comment]
I was able to get these two examples to work in Github today:

```adoc
<<fake/../../device-manager/README.adoc#create, create>>

xref:fake/../../device-manager/README.adoc#create[create]
```
But nothing else, including this which I thought would/should:

```
xref:../device-manager/README.adoc#create[create]
```

**Comment by mojavelinux** [comment]
@jasonkuhrt Indeed, that's a good trick to get links working in the interim. Fortunately, the 1.5.3 is happening this week, so this will soon be behind us (assuming GitHub upgrades in a timely manner).

**Comment by jasonkuhrt** [comment]
@mojavelinux It would be _really_ helpful if I could compare a clear changelog for asciidoc with what Github has implemented so that I reduce confusion when reading docs but failing to get expected results in a Github context (which actually occurs occasionally).

**Comment by mojavelinux** [comment]
You can check which version GitHub is running by putting `{asciidoctor-version}` in your document. Currently, they are running 1.5.2. The run GitHub using the following script: https://github.com/github/markup/blob/master/lib/github/markups.rb#L30-L33. However, their rendering pipeline is partially proprietary and has many filters that we don't see (even myself).

Having said that, I think it's an excellent idea to have a document on asciidoctor.org that explains the limitations clearly. The following blog entry is a starting point: http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/ (though obviously slightly out of date).

**Comment by jasonkuhrt** [comment]
@mojavelinux Thanks for tips/links/openness. Perhaps a section in the manual dedicated to Github would be justified?

**Comment by jasonkuhrt** [comment]
Or a much smaller document that just "diffs" the manual in whatever ways the author needs to know to be productive. The manual is already quite large, A github section might just get lost.

**Comment by mojavelinux** [comment]
I've filed an issue: https://github.com/asciidoctor/asciidoctor.org/issues/419
