### ISSUE TITLE
Unexpected shell return value 0 (success) when error is reported

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor#854]
Hi !

I have discovered asciidoctor a month ago and now I have a problem with those test files : 
a.adoc :

```
= A

Hello

= B
```

and test.sh :

``` sh
asciidoctor a.adoc

RETVAL=$?
[ $RETVAL -eq 0 ] && echo Success
[ $RETVAL -ne 0 ] && echo Failure
```

When I launch './test.sh' in a shell, the ouput is : 

```
asciidoctor: ERROR: a.adoc: line 6: only book doctypes can contain level 0 sections
Success
```

So my question is why asciidoctor not return a value different than 0 on this error ?
Is there a flag to enable it ?

(Maybe I need to post this on http://discuss.asciidoctor.org/ ?)

Thanx a lot in advance !
Victor

**Comment by mojavelinux** [comment]
Starting in 1.5.7, such an option is now available. See #2003 for details.
