### ISSUE TITLE
How to get syntax highlighter's CSS?

### ISSUE THREAD

**Issue by ghost** [asciidoctor/asciidoctor#856]
Hello, 

Currenlty I use asciidoctor with option -s to suppress output of header and footer because I insert the result of asciidoctor in my own layout. 

But, if I use a syntax highlighter (-a source-highlighter=pygments) with option -s, no CSS is ouputted, even with -a linkcss. 

So, is there any way to get the highlighter's stylesheet with option -s ? 
Thanks in advance, 

Regards, 
Victor

**Comment by mojavelinux** [comment]
With the new syntax highighter API in 2.0, it's now even easier to get this CSS:

```rb
require 'asciidoctor'

puts (Asciidoctor::SyntaxHighlighter.for 'coderay').read_stylesheet
puts (Asciidoctor::SyntaxHighlighter.for 'rouge').read_stylesheet 'monokai'
puts (Asciidoctor::SyntaxHighlighter.for 'pygments').read_stylesheet 'bw'
```
