### ISSUE TITLE
Use open source fonts in the default stylesheet

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#879]
Given that the culture of Asciidoctor is deeply rooted in open source, it makes complete sense to be using open source fonts in the default stylesheet rather than the old fashioned proprietary ones. I recommend the Liberation Sans 2 fonts, released on the SIL license.

Instead of having a laundry list of fallback fonts, I think we can use the custom font support in CSS3 to provide a consistent experience across platform.

**Comment by chenyong** [comment]
Can we cache fonts? Docs generated are tremendously slow to load in China mainland since Google font is a Google service.

**Comment by ChinaLym** [comment]
> Can we cache fonts? Docs generated are tremendously slow to load in China mainland since Google font is a Google service.

Have you solved the problem? I want to know how to cache them? 
Let me put it another way, how to replace the default font or CSS？

**Comment by wifiprintguy** [comment]
Was disturbed by the HTML output using Google fonts by default, and found this defect, which was closed some time ago. But the current Asciidoctor version (2.0.10) uses Google fonts by default, which is very disappointing to me. Shouldn't this be reopened?

**Comment by mojavelinux** [comment]
The fonts we use from Google Fonts are open source, so no I don't think it should be reopened.

As to whether we should use web fonts (via a CDN) to load fonts, and which CDN to use, is a separate concern. Using web fonts from a CDN is the only way I know how to have consistent fonts across systems. If you know of another way of doing it (that doesn't require the user to mess around with fonts locally), feel free to suggest.

If you want to disable the web fonts (or choose another family), you can unset the `webfonts` attribute (or modify its value). See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L126-L128 for how this attribute is used.
