### ISSUE TITLE
Section links with _underscore at the beginning don't work in GitHub

### ISSUE THREAD

**Issue by DavidGamba** [asciidoctor/asciidoctor#885]
When I render a document in GitHub, if I clink on the anchor, the path has no underscore `_` after the `#` symbol.

Example:
https://github.com/opendevise/asciidoc-samples/blob/master/runtime.adoc#environment-info

However if I generate the html for that document, the path will have the underscore, so the links that work on html don't work on github and viceversa.

**Comment by mojavelinux** [comment]
I believe this is now resolved with recent changes to GitHub. Can you confirm? If it's still a problem, we probably need to be more specific about what the problem is so that either a) GitHub can make the necessary change or b) we can document how to setup a document to render correctly on GitHub.

**Comment by DavidGamba** [comment]
I believe this is not an issue anymore. Thanks :-)

**Comment by mojavelinux** [comment]
Indeed, GitHub is aware of the section title linking and are now taking steps on their end to get the various cases working. \o/
