### ISSUE TITLE
Allow custom backends to specify basebackend explicitly

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#891]
Custom backends need to be able to specify the value of basebackend explicitly. 

Currently, the value is calculated by removing trailing digits from the backend. However, the association between the backend name and "html" is not implicit. For instance, when the backend is "deckjs", the basebackend is "deckjs", not "html". As a consequence, features which are only activated when the basebackend is html, like syntax highlighting, are disabled.

The current workaround is to point Asciidoctor at the templates for an HTML slideshow, but set the backend to html or html5 (the default).

**Comment by mojavelinux** [comment]
Starting in Asciidoctor 2.0, it's possible to set the basebackend using a custom converter. To cite a use case, it's possible to set the backend to deckjs and still be able to use templates that fallback to the HTML5 converter

Start by creating the following script:

```rb
class DeckjsConverter < (Asciidoctor::Converter.for 'html5')
  register_for 'deckjs'
end
```

Then register this script whenever you set the backend to deckjs:

```
asciidoctor -b deckjs -r ./deckjs-converter.rb slides.adoc
```

Now the backend with be `deckjs`, the basebackend will be `html` (which you can customize in the converter initializer), and the processor will fallback to the HTML5 converter if a template is not found.

The last remaining part is being able to do this without the converter registration script.

**Comment by mojavelinux** [comment]
What I'm thinking we could do to make the custom converter unnecessary is to introduce a shorthand for setting an "emulated" backend (`actual:emulated`). This emulated backend will be used to lookup the converter, but the backend attribute will be set to the actual one.

Here's an example:

```
asciidoctor -b deckjs:html5 slides.adoc
```

In the future, we might be able to do other things with this syntax. It's essentially doing what the above script does, without actually registering a custom converter.

**Comment by mojavelinux** [comment]
@Mogztter wdyt? this will make working with ad-hoc backends easier, no?

**Comment by Mogztter** [comment]
> What I'm thinking we could do to make the custom converter unnecessary is to introduce a shorthand for setting an "emulated" backend (`actual:emulated`). This emulated backend will be used to lookup the converter, but the backend attribute will be set to the actual one.

When you are using a template converter ?

```
asciidoctor -b deckjs:html5 -T /path/to/templates slides.adoc
```

Otherwise you still need to create a custom converter to override how a given node will be converted right ? 

> wdyt? this will make working with ad-hoc backends easier, no?

I like the syntax and I think it will make things easier.

**Comment by mojavelinux** [comment]
Correct, this is primarily intended for when you're defining an ad-hoc backend with templates. However, we could still consider the feature for assembling a composite converter dynamically. For that reason, I'm thinking of renaming the option to `:backend_delegate`. I need to play around with it a bit more.

**Comment by mojavelinux** [comment]
So here's what I'm thinking. We could make it so that the `primary:delegate` backend syntax could apply no matter what converter you're using. But it's a lot of logic and there are still some questions to be answered.

Therefore, I think we should limit the scope of this change to when templates are used and the primary backend doesn't resolve to a converter (the ad-hoc scenario). That allows us to test the waters and see how this goes. If we decide we really like this, it's not hard to go on to generalize this.

I've updated the PR with my proposal.

**Comment by mojavelinux** [comment]
I've opened #3116 to handle the general case.
