### ISSUE TITLE
Missing admonition paragraph icons when using xhtml backend

### ISSUE THREAD

**Issue by ptahchiev** [asciidoctor/asciidoctor#947]
Hi guys, 

my admonition paragraph icons don't appear. I'm generating my maven site with asciidoctor and i have defined 

IMPORTANT: blah blah 

but this gets rendered as 

```
 <td class="icon"> Important </td> <td class="content"> blah blah </td>
```

and not 

```
 <td class="icon"><i class="icon-note" title="Note"></i></td><td class="content"> blah blah </td>
```

So looks like the

```
 <i>
```

tag is not generated. I read here http://asciidoc.org/userguide.html#X88 icons attribute can only be used on xhtml11 or html5 and the maven plugin is using just xhtml not xhtml11 (with xhtml11 it doesn't find the view). Could this be the problem?

**Comment by paranoiabla** [comment]
Hi there, I've created a pull request for this: 
https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/158

**Comment by mojavelinux** [comment]
Cool! Thanks @paranoiabla!
