### ISSUE TITLE
asciidoctor changes the LOAD_PATH

### ISSUE THREAD

**Issue by randomstuff** [asciidoctor/asciidoctor#962]
Asciidoctor changes the LOAD_PATH ($:.unshift(File.dirname(**FILE**))). This does not follow best practices : "Gems should not change the $LOAD_PATH variable. RubyGems manages this for you." [1].

[1] http://guides.rubygems.org/patterns/#requiring_rubygems

**Comment by mojavelinux** [comment]
This is being resolved as part of #2764. Therefore, I'm marking as a duplicate.
